### PR TITLE
Generate UI screenshots in different states

### LINKED ISSUE #31007: [$500 bounty] Post UI screenshots on PRs that modify the UI
We have a CI job that generates a bunch of UI screenshots in various states. The goal of this bounty is to get those screenshots posted as a comment to PRs:
* only comment if `selfdrive/ui/` has changes in the PR
* comment gets updated when new commits are pushed
* must be formatted nicely (e.g. doesn't take up the whole screen). maybe put them in a table?

https://github.com/commaai/openpilot/blob/c9531b463a6cb4a2a56792046fd69f9041006d81/.github/workflows/selfdrive_tests.yaml#L320

### PR DESCRIPTION
**Pull request by jakethesnake420**
resolves https://github.com/commaai/openpilot/issues/31007

### CODE REVIEW

**Comment by jakethesnake420** [comment]
This is kinda the idea I'm going for. In the end a bot will be setup to post a link like this https://jakethesnake420.github.io/openpilot/pr--965fa45dc568e079b41944c19d112a5e9e705fca/index.html. I think a commaai admin will need to setup a branch the the action bot can push to. Haven't sorted it all out though, any input/advise is appreciated since I'm not experienced with this stuff.

**Comment by jnewb1** [comment]
> need to setup a branch that the action bot can push to

hmm is there another solution for this? we aren't going to want to push artifacts to the openpilot repo. We can also split this PR up into two, one for generating the 20 different states, and one for doing the compare / clickable link. the 20 states should be easy to merge

**Comment by jakethesnake420** [comment]
> hmm is there another solution for this? we aren't going to want to push artifacts to the openpilot repo, especially images like that. 

yea makes sense but if we want an automatically generated website with a clickable link, we gotta put the images somewhere on a server. The other option is to use a third party CDN, use another github repo or get the bot to post the top 5 changed images directly in the PR comments.

> We can also split this PR up into two, one for generating the 20 different states, and one for doing the compare / clickable link. the 20 states should be easy to merge.

sure i can do that

**Comment by jakethesnake420** [comment]
Oh yea and I run through all the onroad events and all the navigation icons so it's a lot more than 20 pictures. It would be over a hundred and then it does a thresholded comparison to master images.

**Comment by jnewb1** [comment]
> Oh yea and I run through all the onroad events and all the navigation icons so it's a lot more than 20 pictures.
cool but lets just start with 20, I dont think we need all the navigation icons and onroad events.

> post the top 5 changed images directly in the PR comments.
Perhaps it only posts them if it changes >20% or if the "ui" label is applied? I found this repo that has an example of how to post to comments but  t looks like they use an external repo for hosting the images: https://github.com/the-blue-alliance/the-blue-alliance/pull/5719

**Comment by jakethesnake420** [comment]
Still working on this just busy this week

**Comment by adeebshihadeh** [comment]
Closing due to inactivity. This is also way too big. If you'd like to try again, it'll need to be much simpler.

**Pull request closed without merging**
