### PR TITLE
2019 rav4

### PR DESCRIPTION
**Pull request by wocsor**
apologies in advance for leaving in the pedal related stuff. this was based on my devel branch so that's in here too. also, i just overwrote the values in radar_interface rather than detecting the car so this will only work on a 2019 rav4 currently. finally, it doesn't have proper tuning.. but it does work

### CODE REVIEW

**Comment by rbiasini** [comment]
@wocsor , your blackmailing strategy of including the pedal changes in this PR paid out :) Toyota pedal support will be in next OP release.
Back to Rav4 2019: any chance you can clean up this PR a bit to make it back compatible with other toyotas? what about tuning?

**Comment by arne182** [comment]
It would make sense to split RAV4 and RAV4H as the tuning with pedal is significantly different. @Kumar can confirm this.

**Comment by wocsor** [comment]
RAV4 2019 is still untuned, we're running with the Camry / CHR numbers which are still wobbly. @MOREICE on discord can confirm. It will stay in lane though, and the pedal is not needed on this model for stopngo.

I'll work on backwards compatibility, but I need to also make a mod to Panda FW to block 0x343 coming from the camera. Stock long is also not possible in these cars with OP installed

**Comment by rbiasini** [comment]
yeah, makes sense that you can't have (at least for now) stock long controls on this new Toyotas. Same as Honda Nidec.

**Comment by rav4kumar** [comment]
> It would make sense to split RAV4 and RAV4H as the tuning with pedal is significantly different. @Kumar can confirm this.

yes indeed its huge different.

**Comment by rbiasini** [comment]
@wocsor , are you planning on rebasing this PR on latest release?
As far as pedal tuning goes, happy to merge improved tuning but prefer to that on a separate PR.

**Comment by wocsor** [comment]
I haven't had access to the RAV4 to test if both work on the same code

**Comment by wocsor** [comment]
@rbiasini finally was able to make the radar_interface play nicely with other toyotas. i'll make PRs to Panda and opendbc as well for the other modifications necessary

**Comment by njbrown09** [comment]
What exactly is this "toyota pedal" thing being discussed?

**Comment by rbiasini** [comment]
@wocsor, ok. Let us know when ready. tnx!

**Comment by wocsor** [comment]
@rbiasini i refactored and reset everything to get rid of the old pedal baggage. hope this is good enough!

**Comment by wocsor** [comment]
https://community.comma.ai/cabana/?route=cdf2f7de565d40ae%7C2019-04-25--03-53-41&max=20&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Fcdf2f7de565d40ae%2F57185802db4568c465e9ce4f082a3708_2019-04-25--03-53-41

here is a cabana for the 2019 RAV4

**Comment by rbiasini** [comment]
obsoleted by https://github.com/commaai/openpilot/pull/641

**Pull request closed without merging**
