### PR TITLE
Toyota: add missing engine FW for 2023 RAV4 LE (LTA)

### PR DESCRIPTION
**Pull request by sebastianmueller01**
Description:
Added fingerprint for Engine ECU for 2023 RAV4 LE

Verification:
Tested on personal vehicle. Initially wasn't recognized by openpilot and with this fix openpilot works successfully.

### CODE REVIEW

**Comment by vanillagorillaa** [comment]
Be sure to include the dongleID of the device this firmware version was gathered from

**Comment by sebmueller01** [comment]
> Be sure to include the dongleID of the device this firmware version was gathered from

dongleID is `cb4c4fc7644d7b30`

**Comment by sshane** [comment]
@sebmueller01 are you on Discord? Are you aware this car uses a different steering API and so it doesn't work on master yet? We have a channel you might be interested in joining here: https://discord.com/channels/469524606043160576/1047684141963022376

**Comment by sebmueller01** [comment]
Yup, currently running the `toyota-lta` branch forked that includes the updated ECU on my C3. I'm in the discord channel and I was told to target master for my PR. Definitely willing to help out in any way I can to get longitudinal working :)

**Pull request merged**
