### PR TITLE
ui/networking: remove dynamic property and style sheet

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Is this actually faster?

**Comment by deanlee** [comment]
y, possibly 20 times faster.  the dynamic property&style takes ~0.07ms for one item, the setFont  takes only ~0.003ms.

**Comment by adeebshihadeh** [comment]
Nice!

**Comment by adeebshihadeh** [comment]
Btw, did you get my email (sent to hotmail)? We need some more info to ship your stuff

**Comment by deanlee** [comment]
y, replied!

**Pull request merged**
