### PR TITLE
Subaru: update carinfo supported model years and good steering torque

### PR DESCRIPTION
**Pull request by martinl**
This PR updates Subaru supported model years (included in initial Subaru FPv2 import) and adds stars for good steering torque

**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs

### CODE REVIEW

**Comment by sshane** [comment]
In the future we are going to use data to generate the torque star columns, but I'm fine with manually updating this for now, as long as it has enough torque for comfortable highway driving.

**Comment by sshane** [comment]
Actually can you revert the torque changes and just update the model years, we saw from data that the Impreza has about the same torque as some Hondas. We'll use data from the fleet to fill the torque column out later.

**Comment by michaelhonan** [comment]
Might be worth noting that the Imprezas might not be as limited as previously thought:
https://github.com/commaai/openpilot/pull/23530

**Comment by sshane** [comment]
Yeah, will look into that eventually. For now though, let's use the data for the good torque columns, so it's only Forester for now.

**Comment by martinl** [comment]
Which model year Impreza steering torque did you measure - 2020-21 has lower steering torque limit in openpilot because of eps fault issue but Impreza 2016-19 and Crosstrek 2017-19 should have no issues on highway driving. Would it be ok to split Impreza and Crosstrek and remove steering torque star from 20-21?

**Comment by sshane** [comment]
We looked at Impreza Sport 2020, which had 0.66, 0.71, 0.96 m/s/s lateral acceleration at three speed brake points while Forester had 2.01, 1.67, NA m/s/s

**Comment by ClockeNessMnstr** [comment]
> Which model year Impreza steering torque did you measure - 2020-21 has lower steering torque limit in openpilot because of eps fault issue but Impreza 2016-19 and Crosstrek 2017-19 should have no issues on highway driving. Would it be ok to split Impreza and Crosstrek and remove steering torque star from 20-21?

20-21 look to have more torque not less.

**Pull request merged**
