### PR TITLE
Tools: Send web joystick axes via WebSocket instead of XHR

### PR DESCRIPTION
**Pull request by ntegan1**
https://github.com/commaai/openpilot/issues/25996

### CODE REVIEW

**Comment by incognitojam** [comment]
Why not add websockets as a pipenv dependency?

**Comment by ntegan1** [comment]
> Why not add websockets as a pipenv dependency?

I couldn't find where python packages get installed on device, was guessing it's in Agnos somewhere

**Comment by incognitojam** [comment]
Oh, it would be in https://github.com/commaai/agnos-builder/blob/master/userspace.

**Comment by incognitojam** [comment]
I forgot this might have been good in the new AGNOS update

**Pull request closed without merging**
