### PR TITLE
PID backward-Euler implementation. add Derivative, track actual actuator output, back-calculate integrator. 

### PR DESCRIPTION
**Pull request by ClockeNessMnstr**
I have been running this controller for a few weeks. 

Using a derivative term and back-calculating the integrator based on the actual commanded output from saturating the torque ramp up allows for much better tunes without hitting instabilities from actuator / safety saturation. 

There is also a input filter to reduce the noise in the P-term. most of the noise seems to be in the Desired angle so it should not be vehicle dependent.

Includes/depends/related:
https://github.com/commaai/openpilot/pull/21336
https://github.com/commaai/openpilot/pull/21005

Cereal updates for kdBP, kdV, pid.d

PI portion of the controller has the same behavior with current tunes. Only difference would be the 5hz LPF on the error currently.

### CODE REVIEW

**Comment by ClockeNessMnstr** [comment]
Screenshot from 2021-06-27 18-34-28

recoveries from steering overrides short/sharp & windup/long tests.

**Comment by ClockeNessMnstr** [comment]
Screenshot from 2021-06-27 18-31-50

highway stretch, long bends / straights

**Comment by ClockeNessMnstr** [comment]
a3586311666ae480|2021-06-27--18-15-51

**Comment by ClockeNessMnstr** [comment]
Screenshot from 2021-06-26 20-09-52

35mph max torque turns

**Comment by ClockeNessMnstr** [comment]
a3586311666ae480|2021-06-27--18-15-51

**Comment by pd0wm** [comment]
1) Why a LPF on the error? If there is noise on the desired angle this should be fixed in the planner, not masked with a low pass filter. Those changes might provide small benefits on the short term, but make the whole stack hard to reason about and debug.
2) Why not a Kalman filter to compute the rate of change? Many cars also provide a steering rate signal we can use to provide a better estimate.
3) Do you have any comparison drives before/after these changes that show that the (average) tracking error is reduced? You need to measure this error before it enters the LPF.

**Comment by ClockeNessMnstr** [comment]
I'm just going to pull out the error filter. 

I'm seeing a small improvement down to 1.6hz (as far as I had time for) using an average of  (1+err)^2 but it's between 1.2-1.6 and my results were depending pretty heavy on traffic.

Controller was still working fine without it. 

I'll end up trying the lowest filter that doesn't cause problems and seeing how far I can push a tune on it. If it provides a better tune than without a filter I'll make a new PR for the filter.

**Comment by adeebshihadeh** [comment]
any update on this?

**Comment by ClockeNessMnstr** [comment]
> any update on this?

Extra filters are out. 
I can try to capture some comparisons like the tests in the screenshots. 
Haven't had much time the past few weeks.
What do we want to see?
There's two parts essentially. 
PID implementation and integrator back calculation

**Comment by adeebshihadeh** [comment]
These are all very different changes. I'm not sure we're interested in adding a derivative term, but I think uses the final requested torque in the controller makes sense. Can you make a clean PR that only does that?

**Pull request closed without merging**
