### PR TITLE
Hyundai: Car Port for Kia EV6 (HDA1) 2022

### PR DESCRIPTION
**Pull request by hoomoose**
**Checklist**
- [ ] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [X] route with openpilot: 68d6a96e703c00c9%7C2022-08-31--17-53-53
- [X] Harness Type: Hyundai L

**Physical setup**
Top port behind comma three
micro2 fuse power tap <-> power cable with female 5.5/2.5 barrel end <->male 5.5/2.5 barrel end to usb-c adapter <-> comma three
Bottom port behind comma three
Camera Harness <-> Harness Box <-> USB C/C 3.1 <-> Red Panda <-> USB A/A <-> USB A to C OTG Adapter <-> comma three

**Requires**
https://github.com/commaai/panda/pull/1056

**Fingerprint**
I have been force fingerprinting since I hardwire - the fingerprint values are simply copied and pasted from the HDA2 EV6 as space holder

**Need help**
1. I have not been successful making an "if" statement for the Cruise Button can message line in hyundaicanfd.py; HDA1 EV6 uses bus 4 while HDA2 EV6 uses bus 5
2. I do not know how to modify panda to have multiple options for 0x35 signal like you did for 0x1cf; my attempt resulted in errors
3. My resume from stop does not work even though I have the 0x1cf cruise button signal just like the hda2 ev6

### CODE REVIEW

**Comment by hoomoose** [comment]
image

Not sure if I am doing something wrong, but I get this error when attempting to run selfdrive/car/docs.py

**Comment by hoomoose** [comment]
Upon further reflection, a new car may not needed as the signals since the HDA2 flag can account for differences. I am assuming that tuning parameters would be the same regardless of hda1 or hda2 if its the same car otherwise, but that may not be the case. Also, the FW versions in my branch are not my actual FW. I just copied and pasted from Comma's EV6 to act as a placeholder.

**Comment by rafaelcastillolopez** [comment]
It also worked on a Ioniq5 (HDA1), here is a route as proof 4a71ea383083bc6f|2022-09-04--10-57-19--0 (preserved, public, rlogs uploaded).

I hope it could be merged soon.

**Comment by hoomoose** [comment]
Closing car port in lieu of simple fix:
https://github.com/commaai/openpilot/pull/25723

**Pull request closed without merging**
