### PR TITLE
Remove tag when NVMe drive detected

### PR DESCRIPTION
**Pull request by incognitojam**
Delete the `living-in-the-moment` tag when we detect a drive mounted at `/data/media`

### CODE REVIEW

**Comment by incognitojam** [comment]
Should we show an offroad alert when we detect a new drive is installed?

**Comment by adeebshihadeh** [comment]
AGNOS mounts `/persist` as read-only, so you'll also need to remount before and after.

**Comment by incognitojam** [comment]
Just went through this on my Comma 3 as I just installed an NVMe drive. I had to run `mkfs.ext4 /dev/nvme0n1` before I could run `mount /data/media` (before that it complained about a bad filesystem). Would we want to format new drives automatically too?

**Comment by pd0wm** [comment]
@adeebshihadeh I assume we don't want to automatically erase?

A system reset should take care of reformatting the name already: https://github.com/commaai/openpilot/blob/master/selfdrive/ui/qt/setup/reset.cc#L16

**Comment by adeebshihadeh** [comment]
No, I don’t think we do. I’ll clean this up and test it. There may also be a permissions issue here.

**Comment by incognitojam** [comment]
I removed the mount/reformat thing, and I suppose indicating to the user whether there is an NVMe drive mounted/formatted can be tackled in another PR

**Comment by sshane** [comment]
@adeebshihadeh did you ever test this?

**Comment by adeebshihadeh** [comment]
After thinking about this some more, I'm not sure it makes much sense. With this change, if you remove the NVMe drive out of your basic edition, you also have to add back a weird file to get the stock experience of the device. Installing an NVMe is an intentional process, and I think it makes more sense to manually remove the file at that time if you want that configuration.

**Pull request closed without merging**
