### PR TITLE
Longitudinal: add Kf to carParams

### PR DESCRIPTION
**Pull request by ClockeNessMnstr**
"1" isn't really a sane value here.
Edit:  Updated long to be tuneable as well.

### CODE REVIEW

**Comment by pd0wm** [comment]
What is the purpose of this PR? Having no feedforward should be the default case.

**Comment by ClockeNessMnstr** [comment]
> What is the purpose of this PR? Having no feedforward should be the default case.

Yes, thought I'd just throw it up. Lateral feed forward is much lower than one. It also appears that longitudinal tuning has had a feed forward of one with no value to tune. (I don't have long though)

**Comment by pd0wm** [comment]
See: https://github.com/commaai/openpilot/pull/23740

**Comment by ClockeNessMnstr** [comment]
I agree about having the input sanition somewhere else actually. This is different though. 

Also, not sure if people tuning long realize that there's a feedforward?

**Comment by pd0wm** [comment]
Sorry, you're right! Let me reopen.

**Pull request merged**
