### PR TITLE
webrtc camera streaming demo

### PR DESCRIPTION
**Pull request by kfatehi**
This PR adds the following directory `tools/camerastream/webrtc` in which there is an executable `server.py` to start a webrtc streaming server to stream a single camera from the cereal bridge.

To run it, your comma 3 must be running the camera, encoder, and cereal bridge:

```
cd /data/openpilot/system/camerad
./camerad
```

```
cd selfdrive/loggerd
./encoderd
```

```
cd cereal/messaging
./bridge
```

Then, on another computer with a very fast connection to the comma (use ethernet) run the webrtc server:

```
cd ./tools/camerastream/webrtc
./server  --cam 0 <IP address of comma 3>
```

You can use different cameras by passing 0, 1, or 2 ,for the road, wide, and driver cameras, respectively.

There is no audio at this time.

Once your server is running, you can access it on port 8080 by default, and click Start. You should see the camera appear in your browser.

image

```
usage: server.py [-h] [--cam CAM] [--cert-file CERT_FILE] [--key-file KEY_FILE] [--host HOST] [--port PORT]
                 [--verbose]
                 addr

Decode video streams and broadcast via WebRTC

positional arguments:
  addr                  Address of comma three

optional arguments:
  -h, --help            show this help message and exit
  --cam CAM             Camera to stream
  --cert-file CERT_FILE
                        SSL certificate file (for HTTPS)
  --key-file KEY_FILE   SSL key file (for HTTPS)
  --host HOST           Host for HTTP server (default: 0.0.0.0)
  --port PORT           Port for HTTP server (default: 8080)
  --verbose, -v
```

### CODE REVIEW

**Comment by morrislee** [comment]
I am looking forward when this will be available for the comma connect web app!

**Comment by kfatehi** [comment]
I just want to provide an update as to where I am stuck now on this project since it may be quite some time before I make another attempt again.

Currently my approach is to attempt to get the Raspberry Pi 4 hardware accelerated codec working on the first part of the problem which is decoding the HEVC. I got everything compiled and working properly EXCEPT for PyAV being unable to access the decoder (even though it's compiled from the correct ffmpeg libs which CAN use the hevc_v4l2m2m hw accelerated decoder).

Anyways so I think it may require digging deeper into PyAV and the closest discussion about it that I could find is https://github.com/PyAV-Org/PyAV/issues/798

Using a Pi to offload the webrtc stuff is just one possible implementation... Ideally it could have been possible to use hardware acceleration all internal to the pi and not even use the cereal bridge to offload the work, but I also don't mind offloading it either, if I could just get a working implementation. Until the basics are working the robot can't be mobile and so it really limits progress on things like UI/UX (the fun part IMHO) since the machine is relegated to being tethered to a computer with a good CPU for PyAV to be able to work at nominal framerates despite lack of hardware acceleration.

Other ideas are Nvidia Jetson but I dont see PyAV actively supporting that either, so if I were to buy that I'm just sinking cash and time into another potential dead end, so right now I am just thinking to wait a bit for the v4l2m2m codecs to be made to work in PyAV hopefully.

**Comment by adeebshihadeh** [comment]
Nice work. we've got another implementation in #28354 that will be merged soon.

**Comment by kfatehi** [comment]
> Nice work. we've got another implementation in #28354 that will be merged soon.

thanks! yes i have been testing that branch, it's very good and i've been learning a lot from it. Thanks Adeeb

**Pull request closed without merging**
