### PR TITLE
timed: set valid flag

### LINKED ISSUE #32040: track when devices have a reliable time source
If the time is unreliable for an entire route, it would be good to communicate this information in connect.  As far as I can tell we don't currently have a way to know if the time is reliable (set from modem/GPS/internet) since `timed` currently always sets `valid=True` for `clocks`.

### PR DESCRIPTION
**Pull request by adeebshihadeh**
closes #32040

### CODE REVIEW

**Comment by gregjhogan** [comment]
Should we have systemd initialize the time to a consistent date so we don't have to keep bumping the min date?

**Comment by adeebshihadeh** [comment]
> Should we have systemd initialize the time to a consistent date so we don't have to keep bumping the min date?

That's already handled. AGNOS (and other systemd systems) will always hit this path https://github.com/commaai/openpilot/pull/32061/files#diff-2b004c3c55f3349d75b2bbca0c825a2893527466e3f0e77af0d5cf230cb5e850R9, and `_MIN_DATE` is a fallback for other systems.

**Comment by gregjhogan** [comment]
If we didn't care about non-systemd systems they could always be invalid and simplify `time.py`:
```python
import datetime
from pathlib import Path

def system_time_valid():
  # on systemd systems, the default time is the systemd build time
  systemd_path = Path("/lib/systemd/systemd")
  if systemd_path.exists():
    d = datetime.datetime.fromtimestamp(systemd_path.stat().st_mtime)
    return d + datetime.timedelta(days=1)
  return False # no support for systems without systemd
```

**Comment by adeebshihadeh** [comment]
We do care. We want to support everything we reasonably can, and we should be constantly working towards that.

**Comment by gregjhogan** [comment]
Logging the min date value in the log would be better support I think (to compare at log processing time). On non systemd systems once the hard-coded min date is months old again we have no idea if it is an appropriate cutoff. The consumer of the log should make the call on if they consider the time for such unknown systems reliable.

**Pull request merged**
