### PR TITLE
Add UDS VIN query

### PR DESCRIPTION
**Pull request by adeebshihadeh**
Should fix the failed VIN query on some Hyundai's #23519. Needs to be tested on all the cars.

- [ ] Rav4
- [ ] Corolla
- [ ] Sonata
- [x] Optima
- [ ] Accord
- [x] Civic
- [x] EV6

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
@sshane let's merge this right after bumping to 0.8.15 on master and testing on all our cars

**Comment by sshane** [comment]
Subaru supposedly confirmed working by mlp

**Comment by martinl** [comment]
I tested with Subaru Crosstrek 2018, VIN query worked 
route: `05bca04dfbdca165|2022-04-26--18-28-54`

**Comment by adeebshihadeh** [comment]
@jyoung8607 can you give this a quick test when you get a chance?

**Comment by jyoung8607** [comment]
> @jyoung8607 can you give this a quick test when you get a chance?

NFG as written, all zeros default VIN. See test here: `3cfdec54aa035f3f|2022-04-27--15-57-53`.

I kinda thought this should work, so I investigated a little and compared results with the Panda UDS fingerprinting dev tool. Looks like I won't answer that request posed to the powertrain functional/multicast address (or perhaps the reply is being missed or filtered by the ISO-TP/UDS libraries somewhere?) but I will answer that same request posed to the engine ECU physical address.

Patched startup: `3cfdec54aa035f3f|2022-04-27--16-55-44`

```diff
diff --git a/selfdrive/car/vin.py b/selfdrive/car/vin.py
index e8fb323be..a9d9852a5 100755
--- a/selfdrive/car/vin.py
+++ b/selfdrive/car/vin.py
@@ -16,7 +16,7 @@ VIN_UNKNOWN = "0" * 17
 def get_vin(logcan, sendcan, bus, timeout=0.1, retry=5, debug=False):
   for i in range(retry):
     try:
-      query = IsoTpParallelQuery(sendcan, logcan, bus, FUNCTIONAL_ADDRS, [VIN_REQUEST], [VIN_RESPONSE], functional_addr=True, debug=debug)
+      query = IsoTpParallelQuery(sendcan, logcan, bus, [0x7e0], [VIN_REQUEST], [VIN_RESPONSE], debug=debug)
       for addr, vin in query.get_data(timeout).items():
         return addr[0], vin.decode()
       print(f"vin query retry ({i+1}) ...")
```

Debugging steps:

```diff
diff --git a/selfdrive/car/vin.py b/selfdrive/car/vin.py
index e8fb323be..dc823eb6d 100755
--- a/selfdrive/car/vin.py
+++ b/selfdrive/car/vin.py
@@ -27,9 +27,13 @@ def get_vin(logcan, sendcan, bus, timeout=0.1, retry=5, debug=False):
 
 
 if __name__ == "__main__":
+  import argparse
   import time
+  parser = argparse.ArgumentParser()
+  parser.add_argument('--debug', action='store_true')
+  args = parser.parse_args()
   sendcan = messaging.pub_sock('sendcan')
   logcan = messaging.sub_sock('can')
   time.sleep(1)
-  addr, vin = get_vin(logcan, sendcan, 1, debug=False)
+  addr, vin = get_vin(logcan, sendcan, 1, debug=args.debug)
   print(hex(addr), vin)
```

```
comma@tici:/data/openpilot/selfdrive/car$ ./vin.py --debug
ISO-TP: REQUEST - 0x7df 0x22f190
ISO-TP: TX - single frame - 0x7df
CAN-TX: 0x7df - 0x0322f19000000000
ISO-TP: REQUEST - 0x18db33f1 0x22f190
ISO-TP: TX - single frame - 0x18db33f1
CAN-TX: 0x18db33f1 - 0x0322f19000000000
vin query retry (1) ...
ISO-TP: REQUEST - 0x7df 0x22f190
ISO-TP: TX - single frame - 0x7df
CAN-TX: 0x7df - 0x0322f19000000000
ISO-TP: REQUEST - 0x18db33f1 0x22f190
ISO-TP: TX - single frame - 0x18db33f1
CAN-TX: 0x18db33f1 - 0x0322f19000000000
vin query retry (2) ...
ISO-TP: REQUEST - 0x7df 0x22f190
ISO-TP: TX - single frame - 0x7df
CAN-TX: 0x7df - 0x0322f19000000000
ISO-TP: REQUEST - 0x18db33f1 0x22f190
ISO-TP: TX - single frame - 0x18db33f1
CAN-TX: 0x18db33f1 - 0x0322f19000000000
vin query retry (3) ...
ISO-TP: REQUEST - 0x7df 0x22f190
ISO-TP: TX - single frame - 0x7df
CAN-TX: 0x7df - 0x0322f19000000000
ISO-TP: REQUEST - 0x18db33f1 0x22f190
ISO-TP: TX - single frame - 0x18db33f1
CAN-TX: 0x18db33f1 - 0x0322f19000000000
vin query retry (4) ...
ISO-TP: REQUEST - 0x7df 0x22f190
ISO-TP: TX - single frame - 0x7df
CAN-TX: 0x7df - 0x0322f19000000000
ISO-TP: REQUEST - 0x18db33f1 0x22f190
ISO-TP: TX - single frame - 0x18db33f1
CAN-TX: 0x18db33f1 - 0x0322f19000000000
vin query retry (5) ...
0x0 00000000000000000
```

```diff
diff --git a/selfdrive/car/vin.py b/selfdrive/car/vin.py
index e8fb323be..224ebd271 100755
--- a/selfdrive/car/vin.py
+++ b/selfdrive/car/vin.py
@@ -16,7 +16,7 @@ VIN_UNKNOWN = "0" * 17
 def get_vin(logcan, sendcan, bus, timeout=0.1, retry=5, debug=False):
   for i in range(retry):
     try:
-      query = IsoTpParallelQuery(sendcan, logcan, bus, FUNCTIONAL_ADDRS, [VIN_REQUEST], [VIN_RESPONSE], functional_addr=True, debug=debug)
+      query = IsoTpParallelQuery(sendcan, logcan, bus, [0x7e0], [VIN_REQUEST], [VIN_RESPONSE], debug=debug)
       for addr, vin in query.get_data(timeout).items():
         return addr[0], vin.decode()
       print(f"vin query retry ({i+1}) ...")
@@ -27,9 +27,13 @@ def get_vin(logcan, sendcan, bus, timeout=0.1, retry=5, debug=False):
 
 
 if __name__ == "__main__":
+  import argparse
   import time
+  parser = argparse.ArgumentParser()
+  parser.add_argument('--debug', action='store_true')
+  args = parser.parse_args()
   sendcan = messaging.pub_sock('sendcan')
   logcan = messaging.sub_sock('can')
   time.sleep(1)
-  addr, vin = get_vin(logcan, sendcan, 1, debug=False)
+  addr, vin = get_vin(logcan, sendcan, 1, debug=args.debug)
   print(hex(addr), vin)
```

```
comma@tici:/data/openpilot/selfdrive/car$ ./vin.py --debug
ISO-TP: REQUEST - 0x7e0 0x22f190
ISO-TP: TX - single frame - 0x7e0
CAN-TX: 0x7e0 - 0x0322f19000000000
CAN-RX: 0x7e8 - 0x101462f190575657
ISO-TP: RX - first frame - 0x7e8 idx=0 done=False
ISO-TP: TX - flow control continue - 0x7e0
CAN-TX: 0x7e0 - 0x3000000000000000
ISO-TP: RESPONSE - 0x7e8 0x62f190575657
CAN-RX: 0x7e8 - 0x215646374155324a
CAN-RX: 0x7e8 - 0x2257313737333836
ISO-TP: RX - consecutive frame - 0x7e8 idx=1 done=False
ISO-TP: RX - consecutive frame - 0x7e8 idx=2 done=True
ISO-TP: RESPONSE - 0x7e8 0x62f1905756575646374155324a57313737333836
0x7e0 WVWVF7AU2JW177386
```

**Comment by gregjhogan** [comment]
sounds like for VW the ECU on 0x7e0 doesn't listen to the broadcast address

the repsonse on 0x7e8 should get picked up if it was present
https://github.com/commaai/openpilot/blob/fb7d84875bc993beaf75645a7e4b311704742f02/selfdrive/car/isotp_parallel_query.py#L40

**Comment by adeebshihadeh** [comment]
In that case, seems like it's best to fallback to the current query.

**Comment by sshane** [comment]
Works on Civic!

**Comment by sshane** [comment]
It looks like the UDS query doesn't work on the RAV4, but fallback to the OBD query works

**Comment by jyoung8607** [comment]
Moving this here per discussion with Shane.

It now costs us 1.2 seconds to fetch the VIN because we have to wait for all ten UDS broadcasts to timeout before falling back to OBD. It doesn't break Volkswagen as such, but I'm not super stoked about inserting 1.2 extra seconds into every single startup. Can we interleave the attempts UDS-OBD-UDS-OBD, or does that ruin what you're trying to fix with HKG? I'm given to understand Toyota may be in the same boat.

**Pull request merged**
