### PR TITLE
tools/Rerun: Add video logging features

### PR DESCRIPTION
**Pull request by bongbui321**
Replacement of https://github.com/commaai/openpilot/pull/32703

`./run.py --services accelerometer --qcam --dcam --route "a2a0ccea32023010/2023-07-27--13-01-19/0"` to try

Keeping the old `log()` of `logMessages`, but can specify which msg_type to log so that it doesn't take too much memory by using `--services`. I'll add a print function that prints out every openpilot services

Also, looking for ways to reduce memory usage of hevc files

- [x] speedup by multiprocessing for videos
- [x] print out every openpilot service
- [x] Readme
- [x] segment range
- [x] Logging less verbose

### CODE REVIEW

**Comment by maxime-desroches** [comment]
Running `./run.py --services accelerometer --ecam --dcam --fcam --demo` made my machine hang completely.

The second time I ran this, rerun closed after showing the fcam

**Comment by bongbui321** [comment]
@maxime-desroches  wanna give this a try: 
`./run.py --services accelerometer --ecam --dcam --fcam --route "a2a0ccea32023010/2023-07-27--13-01-19/0"`

I suspect it closed since it was out of memory since 3 hevc videos with full route is a lot

**Comment by maxime-desroches** [comment]
Yeah this works great.

 Can you add to your warning about hvec that 16GB of ram minimum is recommended to use this tool and move the Cautions section above the Openpilot services one? 
`./run.py --services accelerometer --qcam --route "a2a0ccea32023010/2023-07-27--13-01-19"` uses 13GB

**Comment by adeebshihadeh** [comment]
I'd put a yes/no prompt too if you try to load a bunch of segments.

**Comment by adeebshihadeh** [comment]
Does Rerun not support incrementally loading this stuff?

**Comment by bongbui321** [comment]
> ./run.py --services accelerometer --qcam --route "a2a0ccea32023010/2023-07-27--13-01-19" uses 13GB

This is mostly the `accelerometer` service, if you tried only with `qcam` then it should only takes a few GB for the whole route. This should be fixed once we have batch logging for the time series data

> I'd put a yes/no prompt too if you try to load a bunch of segments.
Sounds good

> Does Rerun not support incrementally loading this stuff?
Currently no (confirmed by the maintainers), rerun has a feature that limits the memory usage, but it would delete the earliest data.

**Comment by bongbui321** [comment]
I'd prefer to get this in before the improvements until we have batch logging (will do some testing this week with rerun prerelease version)

**Pull request merged**
