### PR TITLE
Assets/icon: Rm redundant PNG file

### PR DESCRIPTION
**Pull request by ugtthis**
**`selfdrive/assets/offroad/icon_openpilot.png`** - _This file gets deleted_
 - size: 43KB
 - Icon used **only** in "Enable openpilot" settings toggle
 - Current size when rendered 80x80 pixels - Refer to `selfdrive/ui/qt/widgets/controls.cc`
 `icon_pixmap = QPixmap(icon).scaledToWidth(80, Qt::SmoothTransformation);` 

<br>

 **`selfdrive/assets/img_chffr_wheel.png`**
- size: 17KB
- Icon **only** used in onroad UI(icon in top right)
- Current size when rendered 144x144 pixels - Refer to `selfdrive/ui/qt/onroad/buttons.h`
`const int btn_size = 192;` 
`const int img_size = (btn_size / 4) * 3;`

<br>

I removed `icon_openpilot.png` because its 532x532 px size is unnecessary for a small 80x80 px icon displayed on a 2160x1080 screen. `img_chffr_wheel.png`(266x266 px) is used for a larger 144x144 px icon but has a smaller file size. Quality of icon when using the smaller file size as the replacement, looks similar/the same to how the old icon rendered, as seen in video below.

<br>

## Comparing files
png-compare

<br><br>

## Comparison video

https://github.com/user-attachments/assets/73f53bf6-3452-46ad-9acf-040f585f6d51

### CODE REVIEW

**Comment by sshane** [comment]
@deanlee know why the DM crosshair changes slightly here? Also can you add a screenshot of the toggles pane? That would help us verify this PR!

**Comment by VirtuallyChris** [comment]
Maybe it's time to rename the chffr wheel? That's such an old reference!

**Comment by adeebshihadeh** [comment]
@BBBmau looks like ui preview is broken: https://github.com/commaai/openpilot/actions/runs/11094371002/job/30821780066?pr=33565

**Comment by adeebshihadeh** [comment]
Manually reviewed since ui preview is down. Nice cleanup!

**Pull request merged**
