### PR TITLE
swaglog: use std::mutex & remove extern "C"

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
Thanks! Another improvement that swaglog could use is a replacement with a C++ class with a proper constructor and destructor. If you're running valgrind on a process using swaglog you'll notice it always leaks memory due to the lack of proper cleanup.

**Comment by deanlee** [comment]
OIC

**Comment by pd0wm** [comment]
Thanks! We already have plenty of PRs to review, so no rush :)

**Comment by deanlee** [comment]
Had a hard weekend LOL :P

**Pull request merged**
