### PR TITLE
Ford: support hybrid Q3 platforms

### LINKED ISSUE #28124: Ford Q3 Hybrids have occasional incorrect PCM message checksums
This is causing controls mismatches for some users, including at least a Maverick and Escape. Haven't hit it on our Bronco yet however. I checked all three message checksums we check in panda (one from RCM, one from ABS, and one from PCM) and only the PCM message has these mismatches (it's behind a gateway, other two are on the same bus...).

```python
Results: 2114
f8eaaccd2a90aef8|2023-05-05--12-27-53--18  FORD ESCAPE 4TH GEN    addr 0x202: 1 mismatches / 3000 msgs
f8eaaccd2a90aef8|2023-05-05--12-58-21--10  FORD ESCAPE 4TH GEN    addr 0x202: 1 mismatches / 2999 msgs
bd37e43731e5964b|2023-05-05--21-42-22--19  FORD MAVERICK 1ST GEN  addr 0x202: 3 mismatches / 3000 msgs
f8eaaccd2a90aef8|2023-05-05--12-27-53--22  FORD ESCAPE 4TH GEN    addr 0x202: 3 mismatches / 3000 msgs
933ad9d04ac82693|2023-02-08--09-19-55--22  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
f8eaaccd2a90aef8|2023-05-05--12-58-21--192 FORD ESCAPE 4TH GEN    addr 0x202: 2 mismatches / 2999 msgs
bd37e43731e5964b|2023-05-05--21-42-22--7   FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
933ad9d04ac82693|2023-03-23--12-18-36--15  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 2999 msgs
bd37e43731e5964b|2023-05-04--17-29-57--31  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
933ad9d04ac82693|2023-03-07--15-35-14--16  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
bd37e43731e5964b|2023-05-05--21-42-22--20  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
bd37e43731e5964b|2023-05-05--16-59-49--26  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
bd37e43731e5964b|2023-05-04--20-59-54--8   FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 3000 msgs
bd37e43731e5964b|2023-05-04--17-29-57--18  FORD MAVERICK 1ST GEN  addr 0x202: 2 mismatches / 3000 msgs
bd37e43731e5964b|2023-05-04--12-06-21--5   FORD MAVERICK 1ST GEN  addr 0x202: 2 mismatches / 3000 msgs
bd37e43731e5964b|2023-05-05--21-42-22--27  FORD MAVERICK 1ST GEN  addr 0x202: 1 mismatches / 2999 msgs

Matches by addr {514: 6199603, 1045: 6211839, 145: 12395638}
Mismatches by addr {514: 23793, 1045: 0, 145: 0}

Checked segments:
FORD BRONCO SPORT 1ST GEN 793
FORD FOCUS 4TH GEN 147
FORD ESCAPE 4TH GEN 243
FORD EXPLORER 6TH GEN 205
FORD MAVERICK 1ST GEN 726

Checked dongles:
FORD BRONCO SPORT 1ST GEN 4
FORD FOCUS 4TH GEN 1
FORD ESCAPE 4TH GEN 3
FORD EXPLORER 6TH GEN 4
FORD MAVERICK 1ST GEN 3

Checked platforms:
FORD BRONCO SPORT 1ST GEN {'54827bf84c38b14f': 717, '62241b0c7fea4589': 38, 'bbe75f19590890c4': 33, '5a08e8ef78cebd9f': 5}
FORD FOCUS 4TH GEN {'86d00e12925f4df7': 147}
FORD ESCAPE 4TH GEN {'f8eaaccd2a90aef8': 205, '26b2cace68e36212': 34, '62241b0c7fea4589': 4}
FORD EXPLORER 6TH GEN {'59a107f5793d9cc0': 22, '62241b0c7fea4589': 16, 'f0709d2bc6ca451f': 151, '8e1bab39e558e773': 16}
FORD MAVERICK 1ST GEN {'bd37e43731e5964b': 374, 'c845bd8c366e6f3d': 96, '933ad9d04ac82693': 256}
```

### PR DESCRIPTION
**Pull request by sshane**
panda PR: https://github.com/commaai/panda/pull/1887

Thanks to @ncoop23 for getting logs!

### CODE REVIEW

**Comment by sshane** [comment]
@incognitojam I've seen some confusion about us not listing hybrids in the car docs, what was the reasoning for not again (before we dashcammed them)?

**Comment by incognitojam** [comment]
The Escape Plug-in Hybrid is a [seperate model](https://www.ford.com/suvs-crossovers/escape/models/) but Ford don't the seperate hybrids for any of the other cars.. You just get a choice of engine after picking the model/trim.

Still it's no big deal if you want to split them out if that's preferred for the docs/to match other brands

**Comment by sshane** [comment]
An example of the confusion https://www.reddit.com/r/Comma_ai/comments/1471quz/comment/jnwkzyq/?utm_source=share&utm_medium=web2x&context=3

**Comment by adeebshihadeh** [comment]
Probably best to split them out. I think we should try and we can change if it's more confusing.

**Comment by sshane** [comment]
@incognitojam can you open a new PR for the docs?

**Pull request merged**
