### PR TITLE
Add Car Hyundai KONA Hybrid 2020

### PR DESCRIPTION
**Pull request by haram-KONA**
<!--- ***** Add hyundai KONA Hybrid 2020 *****

**Description** [](Add Car KONA Hybrid 2020.)

**Verification** [](results: 49f3c13141b6bc87|2021-07-28--08-05-13--0)

**Route**
Route: [49f3c13141b6bc87|2021-07-28--08-05-13]

DonglID : 49f3c13141b6bc87

### CODE REVIEW

**Comment by haram-KONA** [comment]
I don't know how to solve this problem....
Why is the model verification of the car failing?
What are the common causes of these things?

It's difficult .. for a beginner to do ...

**Comment by pd0wm** [comment]
Since this is a new car port we need an example route we can use for our regression tests. Do you have a route we can be made public and used in our test suite?

**Comment by haram-KONA** [comment]
> Since this is a new car port we need an example route we can use for our regression tests. Do you have a route that can be made public and used in our test suite?

(results: 49f3c13141b6bc87|2021-07-28--08-05-13--0)

**Route**
Route: [49f3c13141b6bc87|2021-07-28--08-05-13]

**Comment by haram-KONA** [comment]
Do I have to do something else to apply?
It is very cumbersome to drive by changing the settings every update.

**Comment by adeebshihadeh** [comment]
Merged in #21912

**Pull request closed without merging**
