### PR TITLE
Tune 2020 Corolla safetyParam

### PR DESCRIPTION
**Pull request by jamcar23**
**Description** Update `CAR.COROLLA_TSS2` and `CAR.COROLLAH_TSS2` safetyParam to 50 from 73; the graphs of `STEER_TORQUE_EPS` and `STEER_TORQUE_CMD` now are more aligned in Cabana.

**Verification** Drove on it, was able to take tighter corners better and had better lat handling overall.

**Route** 
https://my.comma.ai/cabana/?route=095142f13f39faf9%7C2020-10-05--20-28-12&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F095142f13f39faf9%2Fb124bd99af11fdd95cacd23186bd34bb_2020-10-05--20-28-12&seekTime=5 

https://my.comma.ai/cabana/?route=095142f13f39faf9%7C2020-10-06--05-05-49&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F095142f13f39faf9%2F2b5f78b0092ddba311935c5c3c80f93a_2020-10-06--05-05-49&seekTime=102

Before and after photos:

safetyParam_73_1
safetyParam_50_1

safetyParam_73_2
safetyParam_50_2

safetyParam_73_3
safetyParam_50_3

### CODE REVIEW

**Comment by brianandyt** [comment]
Honestly 55 seems closer https://prnt.sc/upgvfy

**Comment by jamcar23** [comment]
Do you have a comparison for that graph with 50? When I looked at mine, it seems like 55 is just a little bit too big. If you look at the top of the peaks 55 looks further off than 50.

Top to bottom: 55, 50

safetyParam_55_1007
safetyParam_50_1007

**Comment by SCshredder17** [comment]
I made a indi tune for 2020 corolla LE on safetyparam 73 and it has no ping pong and the lateral is the smoothest and most accurate it has ever been. I have driven 42k miles in 11 months and tested hundred of values of all types including pidf with 4 BPs each value and indi with outerBP. When i tested my tune on safetyparam 55 it ruined it and it caused understeer and sway out of lane. Therefore, changing the safetyparam will result in each tss2 car to need to be dramatically retuned. I attempted to retune for 55 and tried around 100 variations so far but 55 caused lateral to degrade so much i have not been able to tune it. It takes months to find the right tune and I found it on 73, not 55, I recommend staying at safetyparam 73, unless OP has autotuning for pif and indi. Changing it to 55 while using a old tune is dangerous because it causes lateral behavior to degrade dramatically. Sorry i want to support this idea but i had to share my experience because i was so sad that 55 ruined my "flawless" tune on 73. I am reverting to 73 for life, unless there is autotuning.

**Comment by SCshredder17** [comment]
After looking at your commits it seems like you did not edit the opendbc file line 410. When i changed the interface alone it had no effect on the drive. When i did tests on 55 yesterday i changed the safetyparam in the interface and in the opendbc file and then i could feel a huge difference but it made it worse and more dangerous because of increased sway and understeer.
Screenshot_20201009-092750_Samsung Internet

**Comment by ShaneSmiskol** [comment]
Make sure you guys zoom in on smaller sections of the graph to allow for greater fine tuning. The lines in Cabana are just too thick to tune it based on 3 minutes graphed. If you do something like one peak and one trough you can get it dialed in better.

**Comment by jamcar23** [comment]
@SCshredder17 I did make the change in opendbc but I made a new dbc file for the 2020 corolla only. The PR for that is [here](https://github.com/commaai/opendbc/pull/301).

**Pull request closed without merging**
