### PR TITLE
Hyundai: Car Port for Tucson Diesel 2019

### PR DESCRIPTION
**Pull request by sunnyhaibin**
**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/sunnyhaibin/openpilot-1/blob/7c92f1ec091625fa6bf081bc6482336ca17335ca/selfdrive/car/tests/routes.py#L81)
- [x] route with openpilot: `fb3fd42f0baaa2f8|2022-03-30--15-25-05`
- [x] route with stock system: `fb3fd42f0baaa2f8|2022-03-29--20-57-03`
- [x] harness type: [Hyundai L](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)

Thanks to community Tucson Diesel owner fsalsubaei.

### CODE REVIEW

**Comment by sshane** [comment]
@sunnyhaibin Can you have the user try the branch now with the removed legacy safety mode? Bonus for trying out longitudinal, not definitely not required.

**Comment by fsalsubaei** [comment]
> 

I will test it soon. I can also test longitudinal if you want.

**Comment by sshane** [comment]
Any updates to testing the latest commit here @fsalsubaei?

**Comment by fsalsubaei** [comment]
@sshane  I tested it and provided @sunnyhaibin access to the logs.
As a side note, C3 gets too hot and stops working. This is worse than C2 in terms of temp!!!

**Comment by sunnyhaibin** [comment]
@sshane Please see attached route ID with rlogs uploaded! Stock longitudinal:

`fb3fd42f0baaa2f8|2022-04-07--14-40-37`

**Pull request merged**
