### PR TITLE
add HONDA INSPIRE 2019 HYBRID ‘s fingerprint

### PR DESCRIPTION
**Pull request by panketing**
it is almost the same as the ACCORD HYBRID 2018 in China.

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Please include a Cabana share link of it driven with Giraffe set to stock ADAS.

**Comment by panketing** [comment]
It is almost the same as the ACCORD HYBRID 2018 in China，and it is tested usable by myself in dragonpilot.
https://github.com/dragonpilot-community/dragonpilot

**Comment by ErichMoraga** [comment]
Please don't talk about DragonPilot here.  Waiting on Cabana share link from stock ADAS.

**Comment by panketing** [comment]
> Please include a Cabana share link of it driven with Giraffe set to stock ADAS.
Is this OK?
https://my.comma.ai/cabana/?route=7dddaf0fa7d09e4c%7C2019-10-26--11-20-35&exp=1603630204&sig=CwqoBpY7lqIk8aUWr1yZDwWA37rVd5fW4pRexj8Z%2BX4%3D&max=-1&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F7dddaf0fa7d09e4c%2F72356c5c979808393bc66c1f63d45412_2019-10-26--11-20-35

**Comment by energee** [comment]
This change literally does nothing

**Comment by ErichMoraga** [comment]
No comment (pun intended).

**Comment by panketing** [comment]
> No comment (pun intended).

comment removed.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
