### PR TITLE
Ford: add Edge 2022

### PR DESCRIPTION
**Pull request by incognitojam**
Follow up to https://github.com/commaai/openpilot/pull/30762 since there were conflicts preventing it being merged. (changes one less file!)

FW is from `3d4e31f900dd3a88` (2022 Ford Edge, VIN: `2FMPK4J95NBA30321`) and `26da1db30eff4fcc` (2022 Ford Edge Titanium but retrofit ACC, VIN: `2FMPK4K98NBA52134`)

**Alternate steering message**
- ~I'd also like to double check that there is no other steering angle signal that we can use...~
- `SteeringPinion_Data` sent by the PSCM moved to 0x85; `StePinComp_An_Est` is not populated (-1600) and `StePinCompAnEst_D_Qf` is faulty/not populated (0).
- `BrakeSnData_6` containing `StePinOffst_An_Est` is missing (couldn't find the new address if it has moved)
- `ParkAid_Data.ExtSteeringAngleReq2` has an estimated steering angle we can use instead, and the raw values `32766` and `32767` can be used to detect unknown/invalid state.

The `2GC` platform code in the EPS pn/fw is only on the Edge/Nautilus (and Fusion/Continental/MKZ but they can't be supported). (from the [Ford FW table](https://docs.google.com/spreadsheets/d/1tp6ZYW9fYdDu_xmZWH2Kt39Aw592Ep_7cNJ2kUdPt7M/edit))
image

**Dependencies**
- https://github.com/commaai/opendbc/pull/1026

**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: `3d4e31f900dd3a88|2023-12-15--11-31-09` (experimental mode: `3d4e31f900dd3a88|2023-12-15--11-19-47`)
- [x] route with stock system: `3d4e31f900dd3a88|2023-12-17--16-47-36`
- [x] car harness: Ford Q3

Full credit goes to @MikeDoyal for getting this supported and @mikehundley for testing

### CODE REVIEW

**Comment by incognitojam** [comment]
Just need a new test route since I moved the `ParkAid_Data` message to the camera CAN parser instead

**Comment by incognitojam** [comment]
I moved the `ParkAid_Data` message to the camera CAN parser since the DBC says it comes from `IPMA_ADAS`, but it actually comes from the car side of the harness (bus 0)?

image

**Comment by incognitojam** [comment]
`ParkAid_Data.ExtSteeringAngleReq2` is probably not the "estimated steering angle", but the actual steering angle requested from the PAM. I assume if park assist is enabled this will not be what we want, and I assume not every Edge has the park assist package.

**Comment by incognitojam** [comment]
The PAM seems to learn the true steering angle after 1 second. I'm still not sure how it knows the steering angle offset before the vehicle starts moving (it either learns itself and stores it, or it's getting it from another module?)

image

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
