### PR TITLE
IsoTpParallelQuery: don't extend timeout if rx/tx is finished

### LINKED ISSUE #27361: IsoTpParallelQuery hits total timeout on Mazda
### Describe the bug

Finger printing has been slow when using 9.0 for months. I thought it was just my car but it seems to work fine on my C2 with 0.8.13. I have been putting off reporting this issue. This issue only happens after clearing the cached fingerprint. 

Here is the cleaned up tmux output.

```
Waiting for wayland
wayland ready
adjusting time from '2022-08-31 10:27:49.994168' to '2023-02-16 14:50:10'
Thu 16 Feb 2023 02:50:10 PM UTC
INFO:root:System time valid
fatal: no upstream configured for branch 'new_mazda_C3_stage'
Using Wayland-EGL
gbm_create_device(156): Info: backend name is: msm_drm
qt.qpa.wayland: "wl-shell" is a deprecated shell extension, prefer using "xdg-shell-v6" or "xdg-shell" if supported by the compositor by se
tting the environment variable QT_WAYLAND_SHELL_INTEGRATION
Using the 'wl-shell' shell integration
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
scons: Reading SConscript files ...
Git commit hash for gitversion.h: dc9270f6
scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=False to SConscript calls.
Missing SConscript 'selfdrive/navd/SConscript'
File "/data/openpilot/SConstruct", line 436, in <module>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
corrupted double-linked list
selfdrive/loggerd/bootlog.cc: bootlog to /data/media/0/realdata/boot/2023-02-16--08-50-29
fatal: no upstream configured for branch 'new_mazda_C3_stage'
gbm_create_device(156): Info: backend name is: msm_drm
: QPixmap::scaleWidth: Pixmap is a null pixmap
: "wl-shell" is a deprecated shell extension, prefer using "xdg-shell-v6" or "xdg-shell" if supported by the compositor by setting the envi
ronment variable QT_WAYLAND_SHELL_INTEGRATION
: Wayland does not support QWindow::requestActivate()
NVME not mounted
Panda 1b0023001850335332313620 connected, version: DEV-dc9270f6-DEBUG, signature ab79f3c5faf4c5c0, expected ab79f3c5faf4c5c0
selfdrive/boardd/main.cc: starting boardd
selfdrive/boardd/boardd.cc: attempting to connect
selfdrive/boardd/boardd.cc: connected to board
./selfdrive/sensord/sensors/i2c_sensor.h: Reading chip ID failed: -107
./selfdrive/sensord/sensors/i2c_sensor.h: Reading chip ID failed: -107
selfdrive/sensord/sensors/bmx055_magn.cc: Enabling power failed: -107
./selfdrive/sensord/sensors/i2c_sensor.h: Reading chip ID failed: -107
ioctl returned -1 with errno 22
Waiting for CAN messages...
IOCTL_KGSL_DRAWCTXT_CREATE: creating context with flags 0x4001ad2
selfdrive/loggerd/loggerd.cc: logging to /data/media/0/realdata/2023-02-16--08-52-15--0
waiting for modem to come up
ioctl returned -2147482595 with errno 2
dt is 12
selfdrive/locationd/ubloxd.cc: starting ubloxd
child selfdrive.updated got SIGINT
ond torqued controlsd deleter dmonitoringd laikad rawgpsd navd pandad paramsd ubloxd pigeond plannerd radard thermald tombstoned updated up
loader 
loaded model with size: 4443461
Getting VIN & FW versions
dt is 12
ioctl returned -1 with errno 22
model: input_img -> outputs
input product is 1382400
adding index 1: calib
dt is 12
response: ''
IOCTL_KGSL_DRAWCTXT_CREATE: creating context with flags 0x4001ad2
Thneed::clinit done
Thneed::load: loading from models/supercombo.thneed
response: ''
system.micd lagging by 517.31 ms
system.micd lagging by 417.49 ms
system.micd lagging by 317.56 ms
system.micd lagging by 217.62 ms
system.micd lagging by 117.67 ms
system.micd lagging by 17.73 ms
response: ''
Thneed::load: adding input features_buffer with size 50688
Thneed::load: adding input traffic_convention with size 8
Thneed::load: adding input desire with size 3200
Thneed::load: adding input big_input_imgs with size 1572864
Thneed::load: adding input input_imgs with size 1572864
Thneed::save: adding output with size 24432
selfdrive/modeld/modeld.cc: models loaded, modeld starting
response: ''
response: ''
quectel setup done
no almanac backup found
Sending current time to ublox
Pigeon GPS on!
Starting listener for: camerad
selfdrive/loggerd/encoderd.cc: encoder fcamera.hevc init 1928x1208
selfdrive/loggerd/encoderd.cc: encoder dcamera.hevc init 1928x1208
selfdrive/loggerd/encoderd.cc: encoder ecamera.hevc init 1928x1208
selfdrive/modeld/dmonitoringmodeld.cc: connected with buffer size: 4804608
selfdrive/modeld/modeld.cc: connected main cam with buffer size: 4804608 (1928 x 1208)
selfdrive/modeld/modeld.cc: connected extra cam with buffer size: 4804608 (1928 x 1208)
selfdrive/modeld/modeld.cc: vipc_client_main no frame
iso-tp query bad response: (2017, None) - 0x7f2231
iso-tp query bad response: (1988, None) - 0x7f2231
selfdrive/modeld/modeld.cc: skipping model eval. Dropped -1 frames
iso-tp query bad response: (2016, None) - 0x7f2231
iso-tp query bad response: (2017, None) - 0x7f2231
iso-tp query bad response: (1799, None) - 0x7f1012
iso-tp query bad response: (1856, None) - 0x7f1012
ond torqued controlsd deleter dmonitoringd laikacamerad clocksd logcatd proclogd logmessaged micd timezoned dmonitoringmodeld encoderd logg
erd modeld sensord ui soundd locationd calibrationd torqued controlsd deleter dmonitoringd laikad rawgpsd navd pandad paramsd ubloxd pigeon
d plannerd radard thermald tombstoned uploader 
selfdrive/loggerd/loggerd.cc: rotated to /data/media/0/realdata/2023-02-16--08-52-15--1
iso-tp query timeout while receiving data
Error processing UDS response: (1882, None)
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/car/isotp_parallel_query.py", line 108, in get_data
    dat, updated = msg.recv()
  File "/data/openpilot/panda/python/uds.py", line 445, in recv
    self._isotp_rx_next(msg)
  File "/data/openpilot/panda/python/uds.py", line 488, in _isotp_rx_nextA
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
AssertionError: isotp - rx: invalid consecutive frame index
Error processing UDS response: (1882, None)
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/car/isotp_parallel_query.py", line 108, in get_data
    dat, updated = msg.recv()
  File "/data/openpilot/panda/python/uds.py", line 445, in recv
    self._isotp_rx_next(msg)
  File "/data/openpilot/panda/python/uds.py", line 488, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
AssertionError: isotp - rx: invalid consecutive frame index
iso-tp query bad response: (2016, None) - 0x7f2231
iso-tp query bad response: (2017, None) - 0x7f2231
iso-tp query bad response: (2016, None) - 0x7f2231
iso-tp query bad response: (2017, None) - 0x7f2231
iso-tp query bad response: (2017, None) - 0x7f2231
iso-tp query bad response: (2016, None) - 0x7f2231
iso-tp query bad response: (2016, None) - 0x7f2231
iso-tp query bad response: (2017, None) - 0x7f2231
iso-tp query bad response: (1840, None) - 0x7f2231
iso-tp query bad response: (2016, None) - 0x7f3e13
iso-tp query bad response: (2016, None) - 0x7f2231
Fingerprinted MAZDA 3 2019 using fuzzy match. 2 matching ECUs
Fingerprinted MAZDA 3 2019 using fuzzy match. 3 matching ECUs
VIN JM1BPBML7M1302695
selfdrive/boardd/boardd.cc: finished FW query at OBD port
selfdrive/boardd/boardd.cc: waiting for params to set safety model
{"event": "fingerprinted", "car_fingerprint": "MAZDA 3 2019", "source": 1, "fuzzy": true, "cached": false, "fw_count": 9, "ecu_responses":
[[1848, null, 1], [1864, null, 1], [1807, null, 1], [1848, null, 0], [1896, null, 1], [1900, null, 1], [2024, null, 0], [2024, null, 1], [1
996, null, 1], [1896, null, 0], [2025, null, 1], [1900, null, 0], [2025, null, 0]], "vin_rx_addr": 2024, "error": true}
selfdrive/boardd/boardd.cc: got 1392 bytes CarParams
selfdrive/boardd/boardd.cc: panda 0: setting safety model: 29, param: 0, alternative experience: 1
ond torqued controlsd deleter dmonitoringd laikacamerad clocksd logcatd proclogd logmessaged micd timezoned dmonitoringmodeld encoderd logg
erd modeld sensord ui soundd locationd calibrationd torqued controlsd deleter dmonitoringd laikad rawgpsd navd pandad paramsd ubloxd pigeon
d plannerd radard thermald tombstoned uploader 
selfdrive/loggerd/loggerd.cc: rotated to /data/media/0/realdata/2023-02-16--08-52-15--6
selfdrive/loggerd/loggerd.cc: rotated to /data/media/0/realdata/2023-02-16--08-52-15--7
selfdrive/loggerd/loggerd.cc: closing logger
child system.micd got SIGINT
caching torque params
child selfdrive.locationd.calibrationd got SIGINT
caught sig 2, disabling quectel gps
child selfdrive.navd.navd got SIGINT
child selfdrive.locationd.laikad got SIGINT
SIGINT received, exiting
ioctl returned -1 with errno 1
ioctl returned -2147482611 with errno 1
ioctl returned -2147482611 with errno 1
ioctl returned -2147482611 with errno 1
ioctl returned -2147482611 with errno 1
ioctl returned -2147482611 with errno 1
Storing almanac in ublox flash
child selfdrive.controls.radard got SIGINT
Stopping listener for: camerad
loader 
response: ''
response: ''
quectel cleanup done
No response from ublox
child selfdrive.monitoring.dmonitoringd got SIGINT
child selfdrive.locationd.paramsd got SIGINT
child selfdrive.controls.plannerd got SIGINT

```

### Provide a route where the issue occurs

164080f7933651c4|2023-02-16--08-52-15--0

### openpilot version

0.9.0.x

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by sshane**
Related: https://github.com/commaai/openpilot/pull/25897

https://github.com/commaai/openpilot/issues/27361 is caused by an ECU using one of the diagnostic addresses we query and assume will always be a diagnostic address continually sending messages which extends our timeout for that query/address (0x743+8, combinationMeter for Nissan).

The flow goes like:

Send:

```python
set rx_done=False for 0x743
ISO-TP: REQUEST - 0x743 0x10c0
ISO-TP: TX - single frame - 0x743
CAN-TX: 0x743 - 0x0210c00000000000
```

Receive:

```python
set rx_done=True for 0x743 b'\x00\x15\xff\xe7\xff\xf0\x00\xa8' 0 b''
ISO-TP: RX - single frame - 0x74b idx=0 done=True
```

Then in `IsoTpMessage->recv`:

```python
rx_done is True, tx_done is True for 0x743
```
and we return `updated=True`.

Then similar data (posted above in Receive) is continually received from this address, which continually returns `updated=True`, and we update the timeout, despite both rx and tx being considered done by `IsoTpmessage`. It runs until we hit the total IsoTpParallelQuery timeout of 1 minute.

Some data received by 0x743's RX addr (0x74b). It looks to be >100Hz:
Screenshot from 2023-02-17 12-21-36

### CODE REVIEW

**Comment by sshane** [comment]
@gregjhogan this may be caused by @MoreTore's custom ECU he has in his car (which we don't support), do you know of any cars where ECUs send on the diagnostic address range we assume in openpilot?

**Comment by sshane** [comment]
Then again, this would only work if the first byte from this rogue ECU happens to be interpreted as a single frame response. If this is a custom ECU broadcasting in the wrong address range, then I don't see too much worth in merging this.

**Comment by MoreTore** [comment]
Ah yes of coarse! I send diagnostic data on 0x74A,x74B,x74C. I can change the addresses

**Comment by sshane** [comment]
Closing unless we see this in the field in a supported car. Will check data now

**Comment by sshane** [comment]
This may be needed, as our Optima broadcasts a message on address 0x738, which is actually the response address of the driving ADAS ECU in CAN-FD cars, which the fingerprinting code confuses since we query CAN FD also on bus 0/1/2/3 now

**Comment by sshane** [comment]
PR to better handle this: https://github.com/commaai/openpilot/pull/27762

**Pull request closed without merging**
