### PR TITLE
Create onboarding widgets as needed

### PR DESCRIPTION
**Pull request by deanlee**
1. Remove `OnboardingWindow` 
2. Dynamic create `TrainingGuide` & `TermsPage`

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
I like the simplicity of the way it's done now: one loop to get all the alerts initially and another to update them. What do these changes accomplish?

**Comment by adeebshihadeh** [comment]
Oops that comment was meant for the offroad alert PR.

**Comment by deanlee** [comment]
lol,I know~

**Comment by adeebshihadeh** [comment]
I think the terms and training widgets along with their logic are nicer wrapped in the separate window. The MainWindow class should mainly be a glue class that connects the signals/slots for all the other classes.

**Comment by adeebshihadeh** [comment]
Closing this one for now.

**Pull request closed without merging**
