### PR TITLE
refresh OffroadAlert only when alert is changed

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
What's the benefit of this? Redrawing the widget shouldn't be that expensive, right?

**Comment by deanlee** [comment]
Personally, Ithink the added code is worth it.destroy and create widgets,recalc layouts&show, load release text from disk and set it in the Qlabel, all these operations are much more expensive compared to one comparison.
there is not much complexity added in this PR. If we reduce the refresh interval in the future, we can still benefit from it.

**Comment by adeebshihadeh** [comment]
We don't really need to destroy the layout. Let's just write the OffroadAlerts widget properly, and I don't think we'll need to add this hack.

**Comment by deanlee** [comment]
yes,that will be better

**Comment by adeebshihadeh** [comment]
Cool, I think the re-write will be a nice red diff as opposed to this green diff :)

**Pull request closed without merging**
