### PR TITLE
params: add put_bool_nonblocking

### PR DESCRIPTION
**Pull request by ZwX1616**

### CODE REVIEW

**Comment by pd0wm** [comment]
I don't think this works with the `ensure_bytes`. Why don't you just add a new function `put_bool_nonblocking`?

**Comment by ZwX1616** [comment]
> 

I am confused. `ensure_bytes` here operates on the key no? Was it intended to `ensure_bytes(dat)` ?

**Comment by ZwX1616** [comment]
> I am confused. `ensure_bytes` here operates on the key no? Was it intended to `ensure_bytes(dat)` ?

nvm. we ensure the key here and put() itself ensures the dat. But check_key also ensures the key anyways... (duplicate ensure key in put_nonblocking?)

**Comment by pd0wm** [comment]
Ah you're right. My bad!

**Comment by ZwX1616** [comment]
> Ah you're right. My bad! Still not a fan of the "is_bool" flag. Think a separate function is cleaner.

Yeah I actually prefer that the more I look at it. Thanks for the cleanup

**Pull request merged**
