### PR TITLE
Lane Departure Warning icon add

### PR DESCRIPTION
**Pull request by crwusiz**
settings icon add

### CODE REVIEW

**Comment by crwusiz** [comment]
icon is google search.. hyundai icon

**Comment by sshane** [comment]
Let's revert the icon change, we need to be sure any new icons are free to use

**Comment by crwusiz** [comment]
> Let's revert the icon change, we need to be sure any new icons are free to use

ok..this pr close

**Comment by crwusiz** [comment]
revert

**Comment by crwusiz** [comment]
> Let's revert the icon change, we need to be sure any new icons are free to use

https://www.google.com/search?sxsrf=ALiCzsb78CPRQ2MpzLHWkUU1c9B7op34VA:1668039291877&source=univ&tbm=isch&q=free+icon+lane&fir=ppi9hN6pnsBadM%252CwG9mqgPe9Y1RlM%252C_%253Bf1-WgBHhnThkBM%252C64FAyfKW3e-FMM%252C_%253BsdgSCBNXJLeVMM%252CwZaqB9alCvC2xM%252C_%253BcffpebzrqPuNnM%252CpDfxi1bTHogc5M%252C_%253BLocP39xXoqhepM%252Cjcf23ktXo9iSlM%252C_%253BNcHzvfTQcy1AgM%252CqR2e9pNLpG0BzM%252C_&usg=AI4_-kQ-RHan88NEiOlEO3_30Bt7fcrGug&sa=X&ved=2ahUKEwiJp9rLqqL7AhWGPHAKHYu7DHEQ7Al6BAgJEEI&biw=412&bih=753&dpr=3.5#imgrc=o9apH5JdIRq4jM

this free license icon

**Pull request closed without merging**
