### PR TITLE
UI:  fix buggy poll

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What issue does this fix?

**Comment by deanlee** [comment]
safe_poll is used to skip read visionstream if there is no data during the timeout period to avoid ui laggy or freezing.

**Comment by deanlee** [comment]
possible fix for: #19579

**Comment by dingyf12593** [comment]
I tried this plan tonight, but the problem still exists.

**Comment by deanlee** [comment]
@dingyf12593 Has the problem improved or gotten worse?

**Pull request closed without merging**
