### PR TITLE
c++ replay: chunking and concurrent downloads

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by deanlee** [comment]
added CURLlGlobalInitializer
> If you did not already call curl_global_init(3), curl_easy_init(3) does it automatically. This may be lethal in multi-threaded cases, since curl_global_init(3) is not thread-safe, and it may result in resource problems because there is no corresponding cleanup.

**Comment by pd0wm** [comment]
Video looks strange when running from qcameras:

2021-09-23-224108_1905x1076_scrot

**Comment by deanlee** [comment]
how about  #22195? I think it can handle switch between qcamera and normal video

**Comment by pd0wm** [comment]
Sorry, this comment was not supposed to be in this PR. It's happening on master and also on 22195. Let me move it into the appropriate issue.

**Pull request merged**
