### PR TITLE
ui/map: fix ETA widget text spacing

### LINKED ISSUE #29062: ui: fix ETA widget text spacing in map
@deanlee alex noticed that this PR changes the spacing between the elements, can we revert that?

Before:
image

After:

image

_Originally posted by @sshane in https://github.com/commaai/openpilot/issues/28780#issuecomment-1644485385_

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/issues/29062 . make the spacing between text  same as the original version before refactor: (`font-size` 70px, `cell-spacing`:3px, `eta` padding-left:40px, padding-right 40px)

after:
Screenshot from 2023-07-21 05-26-32

### CODE REVIEW

**Comment by sshane** [comment]
@jnewb1 can you check this matches the old style in a few conditions?

**Comment by jnewb1** [comment]
Close destination:

master:
image

740380bf05f67aebfba77fefdc808789c741b75b (before refactor):
image

this branch:
image

**Comment by jnewb1** [comment]
"min" needs the correct color

**Comment by jnewb1** [comment]
this branch with a further destination:

image

**Comment by jnewb1** [comment]
cross country

image

**Comment by jnewb1** [comment]
LGTM except the color

**Comment by sshane** [comment]
can we fix the color and merge?

**Comment by sshane** [comment]
we also like to double check the languages don't overflow, but we won't worry too much here since it won't be a regression

**Comment by sshane** [comment]
thanks!

**Comment by deanlee** [comment]
@jnewb1 thanks for the fix.

**Pull request merged**
