### PR TITLE
cabana/chart: use different colors to distinguish similar signals

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/discussions/26091#discussioncomment-6860946 :

[Kazam_screencast_00123.webm](https://github.com/commaai/openpilot/assets/27770/ce52fa45-fe95-474b-ad38-6bc439f0003b)

### CODE REVIEW

**Comment by sshane** [comment]
Does it make sense to keep the new color rather than revert?

**Comment by deanlee** [comment]
too convoluted, and there may be some side effects. I recommend keeping it as it is.

**Comment by sshane** [comment]
Is this done by signal name? My problem is different signals with the same/similar colors

image

**Comment by deanlee** [comment]
It looks like I should use the value of hueF to check for similar colors

**Comment by deanlee** [comment]
How now？

**Comment by sshane** [comment]
Looks better! Maybe can we keep the lightness on the lighter side?

image

**Comment by sshane** [comment]
thanks! really handy

**Pull request merged**
