### PR TITLE
Add Merge Chance badge to README

### PR DESCRIPTION
**Pull request by mayfieldiv**
Add Merge Chance badge to README

### CODE REVIEW

**Comment by pd0wm** [comment]
Ironically, I won't be merging this. I don't think this is a useful metric, quality is more important than quantity.

**Comment by geohot** [comment]
Hmm, I liked this metric. It shows it's worth your time to contribute to openpilot.

**Comment by pd0wm** [comment]
We recently started getting more low effort PRs (just fixing up some whitespace, or change single word in the readme) which I think are just noise. Don't want to encourage those people looking for random repos to add to their profile.

If you think it's a good way to attract more good contributors I'm fine if adding it. We could always remove it if the spam increases.

**Comment by geohot** [comment]
Nah, I agree with you, I don't think it'll attract good contributors, just low effort stuff. Won't merge.

**Pull request closed without merging**
