### PR TITLE
Update Car/Subaru values.py to support 2022 Crosstrek

### PR DESCRIPTION
**Pull request by spawahh**
This has already been tested via SP, I'm just adding a fingerprint for my 2022 Subaru Crosstrek.

Route with stock system: 4272b50e35d5475f|2023-07-28--07-48-43--0

### CODE REVIEW

**Comment by jnewb1** [comment]
Do you have a route where openpilot performed the fingerprinting?

**Comment by spawahh** [comment]
Not yet- when I tried to load the fork onto my comma3 it froze and wouldn't start again. I was going to try again tonight and test it out tomorrow afternoon.

**Review by spawahh — COMMENTED** [review]
what's duplicated?

250      b'\xa2 !i\ **0**00',
253      b'\xa2  **`**\x00',
New 254      b'\xa2 **!i**\x00',

258      b'\n\xc0\004\ **0** 00',
260      b'\n\xc0\x04\x0 **1** ',
New 261      b'\n\xc0\x04\x0 **0** ',

I found some similarities but currently it doesn't identify my car so i wasn't sure which tag was causing it to not fingerprint correctly.

**Comment by jnewb1** [comment]
> what's duplicated?
> 
> 250 b'\xa2 !i\ **0**00', 253 b'\xa2 **`**\x00', New 254 b'\xa2 **!i**\x00',
> 
> 258 b'\n\xc0\004\ **0** 00', 260 b'\n\xc0\x04\x0 **1** ', New 261 b'\n\xc0\x04\x0 **0** ',
> 
> I found some similarities but currently it doesn't identify my car so i wasn't sure which tag was causing it to not fingerprint correctly.

under abs and eps, you had duplicated fw versions:
```
b'\xa2 !i\x00',
b'\n\xc0\x04\x00',
```

**Comment by spawahh** [comment]
I got the information from this route; 4272b50e35d5475f|2023-07-28--07-48-43--0
I'm trying to load my fork for testing right now but it stalls at 0%

**Comment by spawahh** [comment]
Alright!
Here is a successful drive without any issues.
4272b50e35d5475f|2023-07-30--07-55-35--0

**Pull request merged**
