### PR TITLE
CAR PORT: 2019 Lexus LS 500

### PR DESCRIPTION
**Pull request by EpiJunkie**
**Checklist**
- [X] added to README
- [ ] test route added to [test_routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/test/test_routes.py)
- [ ] route with openpilot:
- [X] route with stock system: [e256d7cf3a3f07c3|2021-09-17--19-33-31](https://my.comma.ai/useradmin/?onebox=e256d7cf3a3f07c3%7C2021-09-17--19-33-31)

This is my first attempt to port a car. I likely need to redo the routes after the modifications to the files. And make them public?

Values in `interface.py` were copied and modified from `LEXUS_ES_TSS2`.
* `wheelbase` was calculated from the press release value for the base LS 500 (123 inches).
* `tire_stiffness_factor` likely needs to be increased due to the stock tires being run flats.
* `mass` is from the press release value for the base LS 500 RWD with air suspension.

Currently I am getting a "_CAN Error: Check Connections_" error. So I wanted to push this PR in a draft state and get a second opinion. I am leaning toward cable replacement as the next step but am not sure about the DBC generation process (how-to or if that could cause the error message). I have disconnected each wire and firmly reconnected. It seems OP would only recognize the car in one USB-C cable configuration (port orientation).

This particular Lexus LS has LSS+ (2.0) Advance, so I am not sure if that is complicating things or needs to be noted in the `README.md` as a note.

Press release:
> Already equipped with one of the most technologically advanced safety systems in the industry, the 2019 LS adds the
Lexus Safety System 2.0 as standard equipment. LSS+ 2.0 adds daytime bicyclist detection and low-light pedestrian
detection along with Road Sign Assist (RSA) and Lane Tracing Assist (LTA) to further expand the scenarios in which the
LS is designed to provide additional safety to the driver and passengers. 
>
>Advanced Safety Features and Driver Support
>The Lexus Safety System+ 2.0 comes standard on every LS for 2019. The Lexus Safety System+ A offers additional
equipment and is available as an option. Both systems, in addition to other technologies, help to support more secure
driving in a broad range of situations, providing the driver with information ranging from support status notifications to
information on vehicle behavior during safety feature operation via the multi-information display and, when equipped, the
large color head-up display (HUD). 

Brochure:
> Available Lexus Safety System+ A is the most progressive suite of Lexus driver assistance systems yet.27 It includes our most advanced lane assistance technologies,31 as well as a way for the LS to scan the road ahead and alert you if a vehicle or pedestrian is on a trajectory to make an impact with the vehicle.25 Also, the LS can help brake34 or steer away if it detects an impending collision, while still remaining in its lane. Now with Lane Change Assist,35 the LS can even help automatically change lanes for you when it’s safe to do so. It’s our vision of an accident-free world, one step closer to being realized.

Sources:
* https://pressroom.lexus.com/vehicle/2019-lexus-ls/
* https://www.lexus.com/documents/safety/Lexus-Safety-System-Plus-2_0-20181024.pdf
* https://www.lexus.com/documents/brochures/2019/MY19-Lexus-LS-Brochure.pdf

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
The CAN error you're seeing isn't the physical connections. carState.canValid is false which means the some of the checks are wrong for your car. Here's the list of checks - https://github.com/commaai/openpilot/blob/master/selfdrive/car/toyota/carstate.py#L154.

**Comment by ErichMoraga** [comment]
Provided additional pointers starting at...
https://discord.com/channels/469524606043160576/524327905937850394/882772054745702421
[@EpiJunkie is aware.]

Keep up the good work, and good luck smashing that CAN error.

**Comment by EpiJunkie** [comment]
Thanks @adeebshihadeh, I will try to understand and resolve the issue with `carState.canValid`.

Thanks @ErichMoraga for the feedback.

**Comment by EpiJunkie** [comment]
# Update:
- I suspect an optional package on this specific vehicle is contributing to the issues I am having porting it. As indicated above, it is equipped with the LSS+ (2.0) Advance package. This package adds additional safety features (see below).
  - This package adds two additional buses that are directly connected to the DSU.
  - No other Lexus has this package (per Lexus).
  - No other supported Lexus or Toyota (to my knowledge) has these two additional buses directly connected from the Forward Recognition Cameras to the DSU.
- I have connected two additional wires (pins 3 and 9) that were missing from the harness. These pins are populated on the factory connector but missing with the Comma.AI supplied harness. These wires are directly connected to each connector and by-pass the harness box. The harness box does not have additional pass-through ports available.
  - This again, seems to be unique to this model when equipped with the LSS+ (2.0) Advance package.
  - This reduced the amount of errors displayed on the car's instrument cluster.
- Rebased off master-ci branch which now has the tag v0.8.10.

# Current status
- Car works in dashcam mode and correctly identifies the car with FPv2.
- Enabling the OpenPilot toggle and rebooting works until the car is started, then:
  - The Comma displays "CAN Error: Check Connections"
  - The car indicates on the instrument cluster:
    - "Front Camera Unavailable" message.
    - "Headlight System Malfunction" message.
    - The Pre-Collision System unavailable light is illuminated.
  - Techstream shows the following diagnostic trouble codes (DTC):
    - U023A - Main Body - Lost Communication With Image Process Module "A"
    - U023A87 - Combination Meter - Lost Communication With Image Process Module "A" Missing Message
    - U023A87 - Heads Up Display - Lost Communication With Image Process Module "A" Missing Message
  - Techstream communication bus check shows:
    - 1 communication error:
        - System: Front Camera Module
        - Bus: Bus 1
        - Junction / Connector: No 7 CAN Junction Connector
        - Status: Lost Communication

# LSS+ (2.0) Advance package

Additional features over the standard equipped LSS+ (2.0):
- Pedestrian Alert
- Active Steering Assist
- Front Lateral Side Pre-Collision System
- Front Cross Traffic Alert (FCTA)
- Lane Tracing Assist (LTA) with Lane Departure Alert (LDA) with Steering Assist
- Lane Change Assist
- Curve Speed Reduction

This package can be visually identified by standing in-front of the car and looking below where the rear view camera is located. There will be two cameras (and triangles) with this package. Without this package, there is only one camera (and triangle).

This package is listed as an accessory "*AP: Lexus Safety System+ A: Pre-Collision w/Active*" in Techinfo.

I believe this port would be complete and working if this car did not have the LSS+ (2.0) Advance package.

# Support for other Lexus LS models
I believe that without the LSS+ (2.0) Advance package, it would be easy to add support for the following Lexus LS models:
- 2018 Lexus LS 500
  - This is a TSSP system and would rely on the factory ACC.
- 2019 - 2021 Lexus LS 500
- 2019 - 2021 Lexus LS 500H
  - It is interesting to note, the 2021 LS 500H has ECU Security but not for/from the Forward Recognition Camera. This is similar to the supported 2021 Toyota Mirai.

**Pull request closed without merging**
