### PR TITLE
HKG: Add FW versions for Genesis G70 2023

### PR DESCRIPTION
**Pull request by sunnyhaibin**
Add firmware versions for the 2023 Genesis G70. Expand supported model-year range up to 2023.

Dongle ID: `a9b72ac20ef04438`

Thanks to the community 2023 Genesis G70 owner skelliwar (Discord).

### CODE REVIEW

**Comment by sshane** [comment]
@sunnyhaibin can you check that there's no issues with this fingerprint?

**Comment by sshane** [comment]
@sunnyhaibin want me to check?

**Comment by sunnyhaibin** [comment]
Bump

**Comment by sshane** [comment]
## ✅ Updating FW version database with FW from 1 dongles (1 platforms) in last 90.0 days:
<details open><summary>View table</summary><br>

| Dongle, platform, VIN                                                                                                       | Name from VIN 🆚 CarInfo                                                           | Segments                | Bad seg tags   | Good seg tags                                                                        |
|:----------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------|:------------------------|:---------------|:-------------------------------------------------------------------------------------|
| [a9b72ac20ef04438](https://useradmin.comma.ai/?onebox=a9b72ac20ef04438)<br><sub>GENESIS G70 2020<br>KMTG54TE2........</sub> | GENESIS G70 2023 🆚<br>Genesis G70 2020<br><sub>🎉 <b>New model year!</b> 🎉</sub> | 48 routes, 821 segments |                | - all lat active: 136<br>- no input all lat active: 43<br>- valid torque params: 116 |

Dongles to re-run category: `a9b72ac20ef04438`

**Pull request merged**
