### PR TITLE
Fix grinding with Honda pedal + Civic specific pedal tuning

### PR DESCRIPTION
**Pull request by VirtuallyChris**
This pull request solves 3 issues relating to the Honda Pedal.

### 1. Pedal fix discovered by @runchman
This change improves brake pump logic for Honda vehicles allowing for reduced stress on the brake pump. It also fixes the grinding noise found in many cars such as the Odyssey and Civic while using a Honda pedal during low speed braking. (under 15mph)

[Here's an example of the sound that is now fixed in my Civic.](https://www.youtube.com/watch?v=CrcZB59LmAc)

### 2. Gas breakpoints
The Toyota interface.py has code that greatly improves the pedal feel and greatly reduces the ability for the pedal to jerk the car unexpectedly at low speeds. This wasn't present in the Honda file, I've added this.

### 3. Civic specific tuning
The Civic needed pedal tuning more than any car due to the very high kpV compared to all other Honda cars. The stock values would make the car constantly floor the gas and slam the brakes until around ~20mph. The new values reduced that issue greatly.

I still do believe pedal tuning will still need some work in the future. It never seems to be as smooth as lets say a Toyota with full stop and go controlled by openpilot. I believe it may need the decoupling of gas and braking into two PI loops. Trying to tune the pedal to accel slower from 0 causes the brakes to be affected and for the car to not stop in time.
Another potential solution would be to allow tuning over the accel_max at low speeds. It seems no matter how low I make the PI loop, the pedal still finds a way to quickly rise to gasMaxV.

With that being said, this pull request turns the Civic pedal experience from being awful and dangerous to slightly jerky at low speeds but still a decent experience. I think for now this is the best we're going to get.

-VC 😀

### CODE REVIEW

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Comment by rinterdonato** [comment]
Please add the comma pedal pump fix to master.  On the 2018 RDX the pump goes CRAZY without it.

**Comment by cdrage** [comment]
@VirtuallyChris any way you can reopen this PR and possibly get this merged?

**Comment by rinterdonato** [comment]
Please please please please please please please please please do this! Runchman's fix for comma pedal a necessity for stop and go.  It is in Kegman's fork too. PLEASE ADD IT TO MASTER!

Thanks for bringing it up again.

R

Rich Interdonato
(801) 987-0606
________________________________

**Comment by VirtuallyChris** [comment]
I will work on a better implementation of the pedal fix so we can add it for 0.7.10.

**Comment by rinterdonato** [comment]
Thanks Chris! Just please make it work for the 2018 RDX too. I cannot wait!

Rich Interdonato
________________________________

**Pull request closed without merging**
