### PR TITLE
laikad: use non-conflating socket for gnss msgs

### PR DESCRIPTION
**Pull request by gijskoning**

### CODE REVIEW

**Comment by pd0wm** [comment]
Let's add to process replay first with the submaster. Subsockets need some special care in process replay.

**Comment by adeebshihadeh** [comment]
@HaraldSchafer want to keep this open?

**Comment by HaraldSchafer** [comment]
Don't understand this change, so closing. @adeebshihadeh Feel free to merge if you want to.

**Comment by pd0wm** [comment]
Using a submaster can drop messages if the main loop takes too long to process. Specifically dropping a nav message would be annoying. Not sure if this is a problem in practice.

**Comment by adeebshihadeh** [comment]
Yeah, we shouldn't really not do this because it's not convenient to test in process replay. I'll reopen and handle making it work in process replay.

**Pull request merged**
