### PR TITLE
Toyota Highlander/Highlander_H longitudinal tune

### PR DESCRIPTION
**Pull request by briskspirit**
As requested by users on Discord submitting PR for Toyota Highlander/Highlander_H (TSS1 and TSS2) longitudinal tune.

### CODE REVIEW

**Comment by kkimelman** [comment]
This long tune has been a gamechanger on my Highlander. Would love to see it incorporated in stock.

**Comment by pd0wm** [comment]
Can you make a list of cars that use the new tuning, and assign only once? Now there is a lot of repetition between the PRs.

**Comment by briskspirit** [comment]
Ok sure, seems I misunderstood you when we were discussing Corolla tune. Should I do initial PR where I move Corolla long tune to custom tune section and later add other models there?

**Comment by pd0wm** [comment]
That sounds good!

**Comment by davetapley** [comment]
@briskspirit did this get merged elsewhere? 🤔

**Comment by briskspirit** [comment]
@davetapley Was very busy these weeks... and haven't got enough feedback. DM me on Discord if you tried my tune or want to try on Highlander and if everything will be fine - will upstream.

**Pull request closed without merging**
