### PR TITLE
angles instead of vp

### PR DESCRIPTION
**Pull request by haraschax**

### CODE REVIEW

**Comment by pd0wm** [comment]
Do you want to handle migrating from existing calibration file?

**Comment by HaraldSchafer** [comment]
Is that worth it? Only takes 2 minutes to re calibrate, seems ok to me.

**Comment by pd0wm** [comment]
Let's do it cleanly. We can remove the code the release after.

**Comment by HaraldSchafer** [comment]
No don't want that. I will just handle the migration then.

**Pull request merged**
