### PR TITLE
Adding fingerprint for Jeep Grand Cherokee 2019 Trailhawk

### PR DESCRIPTION
**Pull request by BOOOOOOOOTH**

### CODE REVIEW

**Comment by adhintz** [comment]
This adds the following messages that aren't in the existing fingerprint:
`{168: 8, 656: 4, 785: 8, 840: 8, 976: 8, 1543: 8, 2015: 8, 2016: 8, 2024: 8}`

@donlbooth does OpenPilot only work for you with this fingerprint added?

**Comment by donlbooth** [comment]
@adhintz By only do you mean that was all that was needed to get my car recognized? or has it only been tested on my model? that answer to both is yes. It wasn't working before those were added and I didn't have access to another 2019 to test against.

**Comment by pd0wm** [comment]
Can you merge those messages into the existing fingerprint?

**Comment by donlbooth** [comment]
Sure, can they just be added to the end or is there some format the need to be sorted by?

**Comment by pd0wm** [comment]
They are sorted in ascending order by address.

**Comment by donlbooth** [comment]
Ok, I have merged them into the existing line

**Pull request merged**
