### PR TITLE
Add a 2019 G70 fingerprint, remove it from LEGACY_SAFETY_MODE_CAR, an…

### PR DESCRIPTION
**Pull request by alexh76**
…d add radar tracks

**Description**
This change adds a 2019 G70 fingerprint (3.3T Sport), removes it from the LEGACY_SAFETY_MODE_CAR list (enabling the use of OP long), and adds the radar points to enable the use of radar tracks.

**Route**
OP Long Route: 84e17df2f7936cd4|2023-03-09--19-40-19--2
Radar Tracks Route: 84e17df2f7936cd4|2023-03-09--19-47-18--0

### CODE REVIEW

**Comment by sshane** [comment]
I also don't see any routes with your FW versions added, since you hard code your fingerprint. Can you get a route without hard coding your fingerprints or skipping the FW query?

**Comment by sshane** [comment]
Any updates @alexh76?

**Comment by sshane** [comment]
@alexh76 I still don't see any routes with fingerprints, can you drive on master and upload a route?

**Comment by adeebshihadeh** [comment]
Closing due to inactivity

**Pull request closed without merging**
