### PR TITLE
Stop tss2_cars from creeping

### PR DESCRIPTION
**Pull request by arne182**
This needs to be tested but it looks like it could fix.
https://github.com/commaai/openpilot/issues/1270

### CODE REVIEW

**Comment by pd0wm** [comment]
Does this require a button press to resume?

**Comment by arne182** [comment]
Yes. But we could always just fix it with increasing the brake power to 75%

**Comment by pd0wm** [comment]
I think the brake power to 75% might be a better solution then. We would need to parametrize the stopping brake, rate up and rate down in the carParams so we can keep the behavior on other cars the same.

**Comment by arne182** [comment]
Agreed. I at least know that this works. I wonder if this is why my car is going into waiting mode.

**Pull request closed without merging**
