### PR TITLE
Cabana:  Added support for undo & redo 

### PR DESCRIPTION
**Pull request by deanlee**
Screenshot 2022-11-10 13:07:41

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Very cool! If it's easy, would be nice to show a description of each entry in the history stack like a lot of CAD software does.

**Comment by deanlee** [comment]
added command list to rolling the state backwards or forward like CAD software does.
Screenshot 2022-11-10 22:53:29

**Comment by deanlee** [comment]
lgtm. I am quite satisfied with this feature. :see_no_evil:

**Comment by adeebshihadeh** [comment]
> lgtm. I am quite satisfied with this feature. see_no_evil

Me too :)

**Pull request merged**
