### PR TITLE
Update README.md w/ HRV in Supported Car List

### PR DESCRIPTION
**Pull request by cowanhm**
Adding Honda HRV to Supported Car List in root of openpilot (README.md)

### CODE REVIEW

**Comment by pd0wm** [comment]
The official spelling is HR-V. Can you add the dash?

**Comment by cowanhm** [comment]
Changes made per request.  Expanded to 2017-29 for vehicles with Honda Sensing, which based on literature will include LKAS & ACC

**Comment by pd0wm** [comment]
As far I can tell sensing was only an option form 2019 and onwards. Can you change the years back to 2019.

**Comment by cowanhm** [comment]
Per request, updated to narrow scope to model year 2019- equipped with Honda Sensing

**Pull request merged**
