### PR TITLE
Ford: don't fingerprint on engine

### LINKED ISSUE #25750: [$200 bounty] Ford: fingerprint without the OBD port
- [ ] Remove the engine ECU and verify all the current platforms continue to fingerprint exactly (if not exactly, it should fuzzy fingerprint, note this in the verification)

### PR DESCRIPTION
**Pull request by incognitojam**
**Description**
Removes all ECUs except radar and camera from Ford fingerprinting. May close #25750.

**Verification**
I used commaCarSegments to test the changes, and from 14 dongles: 11 fingerprinted successfully and 3 lost their fingerprint. I could run it against more dongles but it was taking a while.

`real_*` columns are values from log
```
                  vin  has_radar              real_fingerprint  real_fuzzy        determined_fingerprint  determined_fuzzy  changed
0   3FMCR9B69NRXXXXXX       True     FORD BRONCO SPORT 1ST GEN       False     FORD BRONCO SPORT 1ST GEN             False    False
1   1FMCU9J94MUXXXXXX       True           FORD ESCAPE 4TH GEN       False           FORD ESCAPE 4TH GEN             False    False
2   5LM5J7XC1LGXXXXXX       True         FORD EXPLORER 6TH GEN       False                          mock             False     True
3   5LM5J7XC9LGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
4   1FM5K8HC7MGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
5   1FMSK8DHXNGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
6   00000000000XXXXXX      False           FORD F-150 14TH GEN       False                          mock             False     True
7   WF0NXXGCHNJXXXXXX       True            FORD FOCUS 4TH GEN       False            FORD FOCUS 4TH GEN             False    False
8   3FTTW8E3XPRXXXXXX      False         FORD MAVERICK 1ST GEN        True                          mock             False     True
9   3FTTW8E33PRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
10  3FTTW8E99NRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
11  3FTTW8F97NRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
12  1FTVW1EL4NWXXXXXX       True  FORD F-150 LIGHTNING 1ST GEN       False  FORD F-150 LIGHTNING 1ST GEN             False    False
13  3FMTK3SU0MMXXXXXX       True   FORD MUSTANG MACH-E 1ST GEN       False   FORD MUSTANG MACH-E 1ST GEN             False    False
```

This Explorer was using a fixed fingerprint, and their camera FW is not in the database, so fingerprinting failed. I've included the FW in this PR.
```
vin='5LM5J7XC1LGXXXXXX'  real_fingerprint=FORD EXPLORER 6TH GEN         source=fixed  determined_fingerprint=mock                         (exact_match=True)
  addr=0x706 fw={b'LC5T-14F397-AE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x764 fw={b'LB5T-14D049-AB\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
```

It appears the F-150 had no FW responses and was using a fixed fingerprint.
```
vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock                         (exact_match=True)
```

This Maverick didn't have a radar so it shouldn't have fingerprinted.
```
vin='3FTTW8E3XPRXXXXXX'  real_fingerprint=FORD MAVERICK 1ST GEN         source=fw  determined_fingerprint=mock                         (exact_match=True)
  addr=0x706 fw={b'NZ6T-14F397-AC\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
```

### CODE REVIEW

**Comment by jnewb1** [comment]
> I could run it against more dongles but it was taking a while.

I think we need something like this: https://github.com/commaai/openpilot/issues/31192

**Comment by sshane** [comment]
Oh I don't want to remove them, I meant to use a tuple like we do for Toyota (PLATFORM_CODE_ECUS)

**Comment by sshane** [comment]
@incognitojam you can re-do this with just removing engine to satisfy https://github.com/commaai/openpilot/issues/25750 and then I can close https://github.com/commaai/openpilot/pull/31204

**Comment by incognitojam** [comment]
I've updated this to only remove the engine FW, and updated the notebook to run against all the ford segments in commaCarSegments (only finding 76 with unique/unknown VINs) and got the same results as the original test.

> Oh I don't want to remove them, [...]. I meant to use a tuple like we do for Toyota (PLATFORM_CODE_ECUS) for your fuzzy fingerprinting function

So I'll continue this in https://github.com/commaai/openpilot/pull/31124 instead? Otherwise it seems simpler to comment out the engine FWs instead of writing a fuzzy matcher for this

**Comment by sshane** [comment]
Can you post here a short few sentences about how removing the engine affects things? All the now failed fingerprints are legit, none gained, rest are unchanged, correct?

**Comment by incognitojam** [comment]
Ford hasn't seen any major differences in the API between models except the large generational change between the "Q3" and "Q4" (CAN FD) cars in lateral control. It's easy to identify whether you are in a Q3 or Q4 car since the physical camera part number is different, which we see a reference to in the FW response (Q3 = `14F397`, Q4 = `14H102`).

As Ford longitudinal is still immature we may find some differences between platforms, but so far we have not discovered anything which would require differentiating on the engine FW.

The engine (actually the PCM) software is important for lots of the car state we are interested in as well as long actuation, but while it would be ideal to have the engine FW, since the stock camera would have to accomodate those differences too, we should be able to find ways (either using the camera FW response or other data in its configuration) to handle it ourselves.

---

Running `match_fw_to_car` against the full set of segments (Ford cars) shows 3 unique cases of failing fingerprints.

<details>
<summary>Show table</summary>
<pre>
vin='5LM5J7XC1LGXXXXXX'  real_fingerprint=FORD EXPLORER 6TH GEN         source=fixed  determined_fingerprint=mock                         (exact_match=True)
  addr=0x7e0 fw={b'LB5A-14C204-AZJ\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x730 fw={b'L1MC-14D003-AJ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x706 fw={b'LC5T-14F397-AE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x760 fw={b'L1MC-2D053-AJ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x764 fw={b'LB5T-14D049-AB\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}

vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock                         (exact_match=True)

vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock                         (exact_match=True)

vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock                         (exact_match=True)

vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock                         (exact_match=True)

vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock                         (exact_match=True)

vin='3FTTW8E3XPRXXXXXX'  real_fingerprint=FORD MAVERICK 1ST GEN         source=fw  determined_fingerprint=mock                         (exact_match=True)
  addr=0x7e0 fw={b'PZ6A-14C204-JE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x730 fw={b'NZ6C-14D003-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x760 fw={b'PZ6C-2D053-ED\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x706 fw={b'NZ6T-14F397-AC\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}

 ..                vin  has_radar              real_fingerprint  real_fuzzy        determined_fingerprint  determined_fuzzy  changed
0   3FMCR9B69NRXXXXXX       True     FORD BRONCO SPORT 1ST GEN       False     FORD BRONCO SPORT 1ST GEN             False    False
1   00000000000XXXXXX       True           FORD ESCAPE 4TH GEN       False           FORD ESCAPE 4TH GEN             False    False
2   00000000000XXXXXX       True           FORD ESCAPE 4TH GEN       False           FORD ESCAPE 4TH GEN             False    False
3   00000000000XXXXXX       True           FORD ESCAPE 4TH GEN       False           FORD ESCAPE 4TH GEN             False    False
4   1FMCU9J94MUXXXXXX       True           FORD ESCAPE 4TH GEN       False           FORD ESCAPE 4TH GEN             False    False
5   1FM5K7LC0MGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
6   5LM5J7XC9LGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
7   1FM5K8GC7LGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
8   1FM5K8GC7NGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
9   1FM5K8HC7MGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
10  5LM5J7XC8MGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
11  5LM5J7XC1LGXXXXXX       True         FORD EXPLORER 6TH GEN       False                          mock             False     True
12  1FM5K8HC2LGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
13  1FMSK8DHXNGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
14  1FMSK8DH0NGXXXXXX       True         FORD EXPLORER 6TH GEN       False         FORD EXPLORER 6TH GEN             False    False
15  00000000000XXXXXX      False           FORD F-150 14TH GEN       False                          mock             False     True
16  00000000000XXXXXX      False           FORD F-150 14TH GEN       False                          mock             False     True
17  00000000000XXXXXX      False           FORD F-150 14TH GEN       False                          mock             False     True
18  00000000000XXXXXX      False           FORD F-150 14TH GEN       False                          mock             False     True
19  00000000000XXXXXX      False           FORD F-150 14TH GEN       False                          mock             False     True
20  WF0NXXGCHNJXXXXXX       True            FORD FOCUS 4TH GEN       False            FORD FOCUS 4TH GEN             False    False
21  3FTTW8E31PRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
22  3FTTW8E99NRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
23  3FTTW8E33NRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
24  3FTTW8F98NRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
25  3FTTW8E3XPRXXXXXX      False         FORD MAVERICK 1ST GEN        True                          mock             False     True
26  3FTTW8F97NRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
27  3FTTW8E34PRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
28  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
29  3FTTW8E33PRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
30  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
31  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
32  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
33  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
34  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
35  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
36  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
37  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
38  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
39  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
40  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
41  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
42  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
43  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
44  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
45  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
46  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
47  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
48  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
49  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
50  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
51  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
52  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
53  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
54  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
55  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
56  3FTTW8E36PRXXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
57  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
58  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
59  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
60  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
61  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
62  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
63  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
64  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
65  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
66  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
67  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
68  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
69  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
70  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
71  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
72  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
73  00000000000XXXXXX       True         FORD MAVERICK 1ST GEN       False         FORD MAVERICK 1ST GEN             False    False
74  1FTVW1EL4NWXXXXXX       True  FORD F-150 LIGHTNING 1ST GEN       False  FORD F-150 LIGHTNING 1ST GEN             False    False
75  3FMTK3SU0MMXXXXXX       True   FORD MUSTANG MACH-E 1ST GEN       False   FORD MUSTANG MACH-E 1ST GEN             False    False
</pre>
</details>

The first is this Explorer which was using a fixed fingerprint. Their camera FW is not in the database, so fingerprinting failed. I've included the FW in this PR.

The fuzzy matching in https://github.com/commaai/openpilot/pull/31124 would not have helped here as there is only one other FW in the database with the same "platform code", and since we require at least two versions to create a range of "known good" versions, it would not have matched.

```
vin='5LM5J7XC1LGXXXXXX'  real_fingerprint=FORD EXPLORER 6TH GEN         source=fixed  determined_fingerprint=mock                         (exact_match=True)
  addr=0x7e0 fw={b'LB5A-14C204-AZJ\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x730 fw={b'L1MC-14D003-AJ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x706 fw={b'LC5T-14F397-AE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x760 fw={b'L1MC-2D053-AJ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x764 fw={b'LB5T-14D049-AB\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
```

The second is an F-150 with no FW responses, so it must fail.

```
vin='00000000000XXXXXX'  real_fingerprint=FORD F-150 14TH GEN           source=fixed  determined_fingerprint=mock   
```

The third is a Maverick with responses from all ECUs except the radar. Presumably, it does not have a radar and should never have been fingerprinted in the first place as we cannot have adaptive cruise without it (at least right now). It will no longer be able to fuzzy fingerprint because it cannot match the engine and ABS FW (fuzzy requires two matches excluding eps/camera/radar).

```
vin='3FTTW8E3XPRXXXXXX'  real_fingerprint=FORD MAVERICK 1ST GEN         source=fw  determined_fingerprint=mock                         (exact_match=True)
  addr=0x7e0 fw={b'PZ6A-14C204-JE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x730 fw={b'NZ6C-14D003-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x760 fw={b'PZ6C-2D053-ED\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
  addr=0x706 fw={b'NZ6T-14F397-AC\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
```

---

I also ran the tests against external data (VINs from for sale Ford Explorers) to try to estimate how many would get an instant FP. Of the 44 cars, I found only 19 of these had a radar and lane centering enabled. However, all 19 fingerprinted successfully after this change. Before removing the engine FW, only 4 would correctly fingerprint, and an additional 4 fingerprinted despite not having a radar, due to the false fuzzy fingerprint match from the engine and ABS FW.

<details>
<summary>Show table</summary>
<pre>
                   VIN                         Comment            Fingerprint  Fuzzy      FactoryACC FactoryTJA
11  1FMSK8FH7NGAXXXXXX      2022 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
12  1FMSK7FHXPGAXXXXXX  2023 Ford Explorer Limited RWD  FORD EXPLORER 6TH GEN  False     RadarFusion         On
15  1FMSK8DH9LGBXXXXXX      2020 Ford Explorer XLT 4WD  FORD EXPLORER 6TH GEN  False     RadarFusion         On
20  1FMSK8FH9MGAXXXXXX  2021 Ford Explorer Limited 4WD  FORD EXPLORER 6TH GEN  False     RadarFusion         On
21  1FMSK8DH1LGBXXXXXX          2020 Ford Explorer XLT  FORD EXPLORER 6TH GEN  False     RadarFusion         On
22  1FMSK8DH1LGDXXXXXX          2020 Ford Explorer XLT  FORD EXPLORER 6TH GEN  False     RadarFusion         On
23  1FMSK8DHXLGBXXXXXX          2020 Ford Explorer XLT  FORD EXPLORER 6TH GEN  False     RadarFusion         On
24  1FMSK8DHXLGAXXXXXX          2020 Ford Explorer XLT  FORD EXPLORER 6TH GEN  False     RadarFusion         On
25  1FM5K8GC0LGAXXXXXX           2020 Ford Explorer ST  FORD EXPLORER 6TH GEN  False     RadarFusion         On
26  1FMSK8FH2MGBXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
27  1FMSK8FHXMGBXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
28  1FMSK8FH2MGBXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
29  1FMSK8FH8MGBXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
31  1FMSK8FH5MGAXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
32  1FMSK8FH4MGBXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
33  1FMSK8FH5MGAXXXXXX      2021 Ford Explorer Limited  FORD EXPLORER 6TH GEN  False     RadarFusion         On
38  1FMSK8DH5MGAXXXXXX          2021 Ford Explorer XLT  FORD EXPLORER 6TH GEN  False     RadarFusion         On
39  1FM5K8GC3LGAXXXXXX           2020 Ford Explorer ST  FORD EXPLORER 6TH GEN  False     RadarFusion         On
41  1FMSK8DH0NGBXXXXXX      2022 Ford Explorer XLT 4WD  FORD EXPLORER 6TH GEN  False     RadarFusion         On
0   1FMSK8DH1NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
1   1FMSK8DH7MGCXXXXXX          2021 Ford Explorer XLT                   mock  False  Off (no radar)        Off
2   1FMSK8DH9MGBXXXXXX          2021 Ford Explorer XLT                   mock  False  Off (no radar)        Off
3   1FMSK8DH4NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
4   1FMSK8DH8MGAXXXXXX          2021 Ford Explorer XLT                   mock  False  Off (no radar)        Off
5   1FMSK8DH3NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
6   1FMSK8DH1LGBXXXXXX          2020 Ford Explorer XLT                   mock  False  Off (no radar)        Off
7   1FMSK8DH8NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
8   1FMSK8DH7NGBXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
9   1FMSK8DH9LGBXXXXXX          2020 Ford Explorer XLT                   mock  False  Off (no radar)        Off
10  1FMSK8DH6NGBXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
13  1FMSK8DH0NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
14  1FMSK8DH9LGCXXXXXX          2020 Ford Explorer XLT                   mock  False  Off (no radar)        Off
16  1FMSK8DH6NGBXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
17  1FMSK8DH9NGBXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
18  1FMSK8DH0NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
19  1FM5K8D83KGAXXXXXX          2019 Ford Explorer XLT                   mock  False       no camera  no camera
30  1FMSK8DH1LGCXXXXXX          2020 Ford Explorer XLT                   mock  False  Off (no radar)        Off
34  1FMSK7DH5LGAXXXXXX          2020 Ford Explorer XLT                   mock  False  Off (no radar)        Off
35  1FM5K8D8XHGCXXXXXX      2017 Ford Explorer XLT 4WD                   mock  False       no camera  no camera
36  1FMSK8DH0LGBXXXXXX          2020 Ford Explorer XLT                   mock  False  Off (no radar)        Off
37  1FMSK8DH4MGAXXXXXX              2021 Ford Explorer                   mock  False  Off (no radar)        Off
40  1FM5K8GT6HGDXXXXXX        2017 Ford Explorer Sport                   mock  False       no camera  no camera
42  1FMSK8DH1NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
43  1FMSK8DH5NGAXXXXXX          2022 Ford Explorer XLT                   mock  False  Off (no radar)        Off
</pre>
</details>

**Comment by sshane** [comment]
LGTM!

**Comment by sshane** [comment]
thanks!

**Pull request merged**
