### PR TITLE
Rotate the steering wheel on the ui.

### PR DESCRIPTION
**Pull request by rav4kumar**
small details matters!

### CODE REVIEW

**Comment by VirtuallyChris** [comment]
I've always thought this should be in the UI, it would be an extra troubleshooting method for people to know if their car fingerprinted correctly while also looking extremely cool and clean.

**Comment by mchonan1996** [comment]
Love this detail, nice PR.

**Comment by jyoung8607** [comment]
It's a pretty nice "polish" feature to have, and would match the Explorer behavior. I'd love to see it. That said, if this is integrated, be prepared to get some questions or problem reports about the displayed steering wheel not matching up with the real steering wheel.

The EON wheel is too small to visually spot fine differences like alignment and torsion/flex and straight-ahead tracking learned corrections, but you could absolutely see differences from folks with variable ratio steering racks. I can tell you right now you'll see it on VW MQB, because we drive on a signal from the car that is corrected for the above factors.

**Steering wheel angle vs true rack angle:**
Mfr specification: variable ratio 14.1 (center) to 9.5:1 (outside)
Steering from 0 to 45, 90, 180, full lock (340-ish)

lwi-vs-eps

**Comment by dibble9012** [comment]
I'd love this feature, but for some reason when I apply it, all my UI goes blank with the exception of the green border.

**Comment by arne182** [comment]
https://github.com/commaai/openpilot/pull/659
Let us see if @geohot has a change of heart

**Comment by valish** [comment]
Hi @rav4kumar, this is a fun enhancement to the UI for playful reasons. Thanks for taking the openpilot UI and making it more fun to use in your car. However, I don't believe this feature should be merged into openpilot master as this confuses the original intent of the openpilot status icon and may increase unneeded attention to the device screen. The openpilot icon serves as a way to communicate the state of the openpilot system as either engaged or disengaged. Rotating the icon with the steering wheel is novel and can be fun, but the motive with the openpilot UI is to communicate critical operating states and relevant road features that may impact the performance of openpilot.

**Comment by mchonan1996** [comment]
Maybe the real solution here is to have a different icon or something to what Explorer has. Like maybe a Comma logo in the circle instead?

**Pull request closed without merging**
