### PR TITLE
wifimanager: use asyncCall to avoid timeout when adding connections

### LINKED ISSUE #34271: 3X doesn't connect to first-time connections until rebooted
This is because the time to add the connection takes ~2s, so our dbus `call` method times out in 0.1s and doesn't save it as a connection. We can fix this by first saving it to memory `save no`, then write it out later by using the `Save` method. This does take 0.2s though, so we'll want to raise the dbus timeout a bit.

@deanlee this should be a pretty simple fix if you want to do it!

### PR DESCRIPTION
**Pull request by deanlee**
resolve: https://github.com/commaai/openpilot/issues/34271

### CODE REVIEW

**Comment by sshane** [comment]
We also need this for the hotspot connection

**Comment by deanlee** [comment]
The same approach has been applied to the hotspot

**Comment by sshane** [comment]
This won't work for the hotspot, as in `setTetheringEnabled`, we'll end up calling `activateWifiConnection` with the tethering connection not yet in the knownConnections

**Comment by sshane** [comment]
merging the asyncCall change, all it will do is silence the timeout warning as this function is already practically async anyway already

**Pull request merged**
