### PR TITLE
thermald: move dbus and other slow calls into thread

### LINKED ISSUE #23516: Fix dbus related deviceState lags

### PR DESCRIPTION
**Pull request by pd0wm**
TODO:

- [x] Verify exceptions in threads still go to sentry

### CODE REVIEW

**Comment by deanlee** [comment]
how about subscribing to the network event pushed by ui/wifimanager?   we can modify wifimanager to use d-bus's signals  to update the network state when it changes instead of current polling.

**Comment by pd0wm** [comment]
We would still need to request some things using AT commands over dbus, so it wouldn't remove the need for the thread. Interesting idea though.

**Comment by deanlee** [comment]
the following functions are also slow. it it possible to consider putting some of them into the thread ?:

get_available_percent
psutil.virtual_memory().percent
read_thermal

**Comment by pd0wm** [comment]
think everything besides read_thermal will eventually move to this thread. This PR is to fix cases were the dbus calls are extremely slow, sometimes they seem to take more than 5 seconds even though all timeouts are set shorter.

**Pull request merged**
