### PR TITLE
Ford: detect auxiliary panda

### PR DESCRIPTION
**Pull request by incognitojam**
depends on https://github.com/commaai/openpilot/pull/28489

### CODE REVIEW

**Review by sshane — CHANGES_REQUESTED** [review]
Use the helper adeeb wrote for hkg

**Comment by incognitojam** [comment]
@sshane It's quite Hyundai specific with ACAN and ECAN... will make a simple version

**Comment by incognitojam** [comment]
actually I don't think the helper is useful in this case

**Comment by incognitojam** [comment]
Running `./test_models.py TestCarModel_96_KIA_EV6_2022` doesn't work, but if I add `print("CANBUS", self._a, self._e, self._cam)` to `CanBus` it works...

**Pull request closed without merging**
