### PR TITLE
cabana: colored line between MSB and LSB

### PR DESCRIPTION
**Pull request by gregjhogan**
image

### CODE REVIEW

**Comment by gregjhogan** [comment]
Would probably look even better with a gray border around the MSB/LSB and colored line with rounded corners.  @deanlee maybe you can do that in a separate PR?

**Comment by gregjhogan** [comment]
The border around this color bar is really needed for when the signal is changing at the max frequency since then the entire cell is the same color as the color bar.

**Comment by gregjhogan** [comment]
I added a color line for single bit fields, I think this makes them easier to read (and the MSB/LSB doesn't really apply anyway)
image

**Comment by gregjhogan** [comment]
I thought it would look best replacing MSB/LSB with the colored line being an arrow the appropriate direction, but I can't seem to get the border to draw nicely at a diagonal.
image

**Comment by deanlee** [comment]
much better after apply style line.

**Comment by gregjhogan** [comment]
Updated with the best I could come up with since the arrow thing looked like garbage.  We can always improve it more in the future (more padding between signals, something indicating endianness for signals not spanning two rows, etc...).
image

**Comment by adeebshihadeh** [comment]
Merged the border, which I think looks pretty good. Do you still prefer this?

**Pull request closed without merging**
