### PR TITLE
ui: increase toggle confirmation font size

### PR DESCRIPTION
**Pull request by incognitojam**
|New|Old|
|---|---|
|Screenshot from 2022-11-09 00-15-21|Screenshot from 2022-11-09 00-08-29|

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Title should probably be a different font weight.

**Comment by incognitojam** [comment]
Screenshot from 2022-11-08 12-56-55
The toggle description is bold - could remove that or make the title really bold?

**Comment by incognitojam** [comment]
I think this looks a lot better
Screenshot from 2022-11-08 13-28-28
Screenshot from 2022-11-08 13-28-31

**Comment by incognitojam** [comment]
Rebased on master
Screenshot from 2022-11-09 00-06-08

**Pull request merged**
