### PR TITLE
2019 Lexus UX 250h

### PR DESCRIPTION
**Pull request by brianhaugen2**
- Added fingerprint for 2019Lexus UX 250h 
- DBC files are 'toyota_nodsu_hybrid_pt_generated', 'toyota_tss2_adas'
- Haven't completed any tuning, copied Corolla values

### CODE REVIEW

**Comment by pd0wm** [comment]
Can you share a cabana route?

Let us know when you finished the tuning, then we can merge it.

**Comment by granadaxronos** [comment]
I am a new user who is about buy the comma 2.0 kit. My car is UX250h AWD 2019. What are the order list from COMMA.AI? Just the kit? I am learning it all by myself. I am good at modification and testing any electronics stuffs.

**Comment by eFiniLan** [comment]
> I am a new user who is about buy the comma 2.0 kit. My car is UX250h AWD 2019. What is the order list from COMMA.AI? Just the kit? I am learning it all by myself. I am good at modification and testing any electronics stuffs.
@granadaxronos 
you will need a comma two + a toyota harness :)

**Comment by brianhaugen2** [comment]
3 hr Cabana drive
https://my.comma.ai/cabana/?route=907cf58d143face6%7C2020-01-27--10-33-46&exp=1611837674&sig=HlAlgQiY13NaLXww93E59GLIh6U9kFhPEWsgIqzVjx4%3D&max=207&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F907cf58d143face6%2F62ad26f28f61f5653868762ee12bbb73_2020-01-27--10-33-46

**Comment by alexatie** [comment]
@brianhaugen2 are you still working on this? I would love to get OpenPilot working with my 2019 UX 250H.

**Comment by VirtuallyChris** [comment]
@brianhaugen2 rebase from master and update the pull request to not be deleting everything and I'm sure this can be merged

**Comment by adeebshihadeh** [comment]
Closing due to inactivity, feel free to re-open after rebasing and tuning is finished.

**Comment by brianhaugen2** [comment]
How to reopen a pull request?

**Comment by brianhaugen2** [comment]
@pd0wm @adeebshihadeh is it possible to reopen this pull request?

**Pull request closed without merging**
