### PR TITLE
Faster compute_path_pinv

### PR DESCRIPTION
**Pull request by dek3rr**
thanks to @zorrobyte for pointing this out

### CODE REVIEW

**Comment by rbiasini** [comment]
Thanks . Did you benchmark the change?

**Comment by dekerr** [comment]
Not a huge difference. Function runs about 10% faster.

**Comment by zorrobyte** [comment]
The function returns the same exact array at 100Hz. Just hardcoding the output and returning it would be even faster. This function has had no input at least since 0.3.8.

**Comment by pd0wm** [comment]
The next version of openpilot will have the polyfit done in c++ by visiond, so this function will no longer be used.

Thanks for looking into it anyway!

**Pull request closed without merging**
