### PR TITLE
e2e long yellow path

### PR DESCRIPTION
**Pull request by incognitojam**
Screenshot from 2022-09-05 23-10-41
Screenshot from 2022-09-05 23-10-16

### CODE REVIEW

**Comment by HaraldSchafer** [comment]
Can you test the live toggling and make sure it works? And then let's merge after I enabled live toggling in the long planner.

**Comment by HaraldSchafer** [comment]
Should we try doing hue based on acceleration plan for e2e_long?

**Comment by incognitojam** [comment]
Screenshot from 2022-09-06 13-23-01
Screenshot from 2022-09-06 13-23-20

**Comment by HaraldSchafer** [comment]
Yellow at start seems good to me

**Comment by incognitojam** [comment]
I think this looks okay, tried to increase the saturation/lightness of the yellow a bit
Screenshot from 2022-09-06 21-47-17
Screenshot from 2022-09-06 21-47-48
Screenshot from 2022-09-06 21-48-22

**Pull request merged**
