### PR TITLE
camerad: abstract cameras

### LINKED ISSUE #25718: camerad: cleanup camera sensor abstractions
About to merge https://github.com/commaai/openpilot/pull/25161/, which has a lot of stuff that looks like "a if AR0231 else b". @deanlee want to try cleaning up the abstractions here?

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/issues/25718

### CODE REVIEW

**Comment by deanlee** [comment]
Need to merge https://github.com/commaai/openpilot/pull/25720 first to Initialize and open camera in AbstractCamera

**Comment by deanlee** [comment]
All camera-related parameters and functions have been moved to separate files. there is no `if CAMERA_ID_AR0231 else` in qcom2 anymore

**Comment by adeebshihadeh** [comment]
Nice, this looks pretty good. Now that VisionIPC has been abstracted out of camerad, we've decided that camerad should just be a highly optimized camera driver for the comma three, so feel free to do any relevant cleanups. I'd also like to better separate the 845-releated code and the image sensor related code (AR0321 and OX03C10).

**Comment by deanlee** [comment]
ok, i will split it into small PRs and do it incrementally

**Comment by adeebshihadeh** [comment]
Nice, I like breaking things up like this! Want to take over "refactor sensor parameters to struct"?

**Comment by adeebshihadeh** [comment]
Already looking a lot nicer!

**Comment by adeebshihadeh** [comment]
@deanlee good to close this? I'm pretty happy with all the sensor abstractions now

**Comment by deanlee** [comment]
y

**Pull request closed without merging**
