### PR TITLE
Updated RAV4 Hybrid TSS2 Port

### PR DESCRIPTION
**Pull request by illumiN8i**
# Car support
This pull requests adds support for Toyota - RAV4 Hybrid - 2019 and 2020 - XSE and XLE.

This is an updated version of PR #740   
test_fingerprints.py passes successfully and it is confirmed working without any fingerprint conflict.

This is an explorer link to a drive with the stock system enabled: https://my.comma.ai/cabana/?route=7e34a988419b5307%7C2019-12-18--19-08-35&exp=1608234300&sig=CnXpUDRQj326t%2B1IRQxJyI8y%2B2UXtDYtSTRrwTsE88g%3D&max=4&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F7e34a988419b5307%2Ff4a4b1d3d01394de94069262c70f2996_2019-12-18--19-08-35

This is an explorer link to a drive with openpilot system enabled: https://my.comma.ai/cabana/?route=7e34a988419b5307%7C2019-12-18--19-13-30&exp=1608234361&sig=ijJbjI0Hohe5lXLsCMZdjhIkgC0ZWWejJFsHjTxmssI%3D&max=4&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F7e34a988419b5307%2F264bd7952ade031f4318a13b4de87227_2019-12-18--19-13-30

The drives above were from discord user david (.ghost) on a 2020 RAV4 Hybrid XLE.  The fingerprint was taken from discord user sideplugmike on a 2019 RAV4 Hybrid XSE.
Stock drive: https://my.comma.ai/cabana/?route=689f254b15632b32%7C2019-12-18--17-16-45&exp=1608309192&sig=ab%2FQM3baV9GMWf00M6Ov5kkPl%2BkzkR%2BnraMU14dANtM%3D&max=21&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F689f254b15632b32%2Ff1eb650f3f355dd869ee9e3c345373e5_2019-12-18--17-16-45

### CODE REVIEW

**Comment by illumiN8i** [comment]
Any idea why Travis CI check failed?

**Comment by illumiN8i** [comment]
Updated fingerprint to support Limited trim. XSE and XLE fingerprints are fully contained within the new longer Limited fingerprint.

Stock drive: https://my.comma.ai/cabana/?route=37a1ee26e697b2f5%7C2020-01-02--17-02-35&exp=1609539781&sig=27Sw59xBx4gNpEZVjYJvJcCb1duIyL8q6HZwBtMn5r0%3D&max=8&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F37a1ee26e697b2f5%2F6cda466a54bfd3d23b993080d8d0e04e_2020-01-02--17-02-35

**Comment by illumiN8i** [comment]
Stock drive from discord user RDuke to confirm the addition of 913:8 to support Swiss 2019 RAV4 Hybrid XLE: https://my.comma.ai/cabana/?route=192a598e34926b1e%7C2020-01-11--08-19-10&exp=1610294691&sig=245p84BFx9ym4yvcbPWaY8Pqnw9EtBKY4g9aNCHViUw%3D&max=2&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F192a598e34926b1e%2Fb39e89b8bef01a01d0de71122fb613ca_2020-01-11--08-19-10

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
