### PR TITLE
replay: add flag REPLAY_FLAG_FULL_SPEED to play at full speed

### PR DESCRIPTION
**Pull request by deanlee**
press `x` to play at full speed
press `x` again to play at normal speed.

https://user-images.githubusercontent.com/27770/147486315-ef37a566-f276-412d-a21b-9fbf3d2ad43d.mp4

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Cool, but what's the use case for this?

**Comment by deanlee** [comment]
I think we can add this capability to ui replay. let use choose a fast speed

**Comment by pd0wm** [comment]
Does it makes sense to play at something like 5x the speed (or slower if your computer can't handle it)? This would make playback a bit more stable.

**Comment by deanlee** [comment]
Currently, the speed is automatically adjusted according to the decoding speed of the video. I think this is more reasonable than specifying a speed.

**Comment by deanlee** [comment]
We may not be able to reach 5x speed at all, especially on c2/c3

**Comment by deanlee** [comment]
We may not be able to reach 5x speed at all, especially on c2/c3

**Pull request merged**
