### PR TITLE
WIP: Shorten openpilot CI Setup Time to <40s

### LINKED ISSUE #30706: [$100 bounty] Speedup CI setup to <40s
The best case time of the `setup-with-retry` stage that runs in most of our CI jobs is ~1m4s. All it does is setup the openpilot environment, and most of that time is pulling an already built docker image. This puts a hard limit on how fast our jobs can finish; a job that finishes in 1m is 10x better than one that finishes in 2-3m CI.

Some possible strategies:
* make the docker image smaller
* move the docker cache somewhere faster
* ditch docker, install directly on the 20.04 runner, and cache the apt and pip packages

Requirements for the bounty:
* all `setup-with-retry` on the final PR commit must finish in less than <40s

https://github.com/commaai/openpilot/blob/master/.github/workflows/setup-with-retry/action.yaml

### PR DESCRIPTION
**Pull request by BBBmau**
Fixes #30706

Based off of comments from the issue the best approach is removing dependencies after they're used with the help of poetry

### CODE REVIEW

**Comment by BBBmau** [comment]
25 seconds to restore apt-packages from cache. Gonna spend some time to see what exactly we don't need from here. [run](https://github.com/commaai/openpilot/actions/runs/8244982267/job/22548120168?pr=31836)

**Comment by BBBmau** [comment]
I'm still working on this. After some research there really is no way to remove enough dependencies so that it's <20s

Caching is an issue due to needing to restore for every runner that's created when it's called. Having the ability to share runners across each job where `setup-with-retry` is mentioned _would be really nice._

Which leads to what looks like is the best (and IMO only solution from what I've looked into) for getting it to <20s and that's setting up self-hosted runners with the openpilot image + dependencies. With comma using azure, I'll look into setting up runners that are hosted there. Regular docker containers work also where each container acts as a runner.

pinging since bounty hasn't been set to locked @adeebshihadeh

**Comment by gregjhogan** [comment]
FYI, if the goal is to get the build time on PRs from forks under these time constraints, github says you should not use self-hosted runners in this scenario:
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security

**Comment by BBBmau** [comment]
> FYI, if the goal is to get the build time on PRs from forks under these time constraints, github says you should not use self-hosted runners in this scenario: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security

My first thought to this is adding in permissions where self-runners are used on PRs from public forks only when approved or some kind of condition is met for contributors (contributors that have a long history in comma.ai repos or organization members)

Might be another hoop for maintainers to take in new contributors.

@gregjhogan thoughts? Just initial thoughts on how to get <20s possible.

https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-required-approval-for-workflows-from-public-forks

**Comment by BBBmau** [comment]
> We do not want to maintain self hosted runners and do not want any more hoops.

back to the drawing board then.

**Comment by adeebshihadeh** [comment]
Closing this since it's way too complicated. Feel free to open a new one if you come up with something simple

**Comment by BBBmau** [comment]
> Closing this since it's way too complicated. Feel free to open a new one if you come up with something simple

Yep, working on something right now that's much simpler. I'll make a draft PR soon.

**Pull request closed without merging**
