### PR TITLE
Flux Capacitor Model

### PR DESCRIPTION
**Pull request by haraschax**

### CODE REVIEW

**Comment by commaci-public** [comment]
ref for commit ca9d8225b9d417f34d57319ac233a447372cc272: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_ca9d8225b9d417f34d57319ac233a447372cc272.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit b63edb5c62925c11655f92146208ade7d1e3a332: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_b63edb5c62925c11655f92146208ade7d1e3a332.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 83476c501d426f4817cc8fd4f2c35e6f2647531a: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_83476c501d426f4817cc8fd4f2c35e6f2647531a.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 83476c501d426f4817cc8fd4f2c35e6f2647531a: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_83476c501d426f4817cc8fd4f2c35e6f2647531a.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 710f85099cbd5ce2800e82f93c9e37311ed9aa7f: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_710f85099cbd5ce2800e82f93c9e37311ed9aa7f.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 50c4ddcf4aeaf8f4f536d38ab0dbd3754b3b453c: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_50c4ddcf4aeaf8f4f536d38ab0dbd3754b3b453c.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by gomtings** [comment]
I think this is a very crazy model. It's like drunk driving

**Comment by commaci-public** [comment]
ref for commit dbf9b94afe02d694ba773296925257807a53949a: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_dbf9b94afe02d694ba773296925257807a53949a.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 7b013da161fe0143e85b8e20e090f12b19844585: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_7b013da161fe0143e85b8e20e090f12b19844585.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 6f00ca847d64004acd4a1a0b2a99e63feedc1a15: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_fc_model/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_6f00ca847d64004acd4a1a0b2a99e63feedc1a15.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Pull request closed without merging**
