### PR TITLE
2023 Ford Explorer Platinum Update fingerprints.py

### PR DESCRIPTION
**Pull request by richardkaplan**
Ford 2023 Explorer Platinum Fingerprint Update

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What's your dongle ID?

**Comment by richardkaplan** [comment]
Dongle ID is
a1c474db2493d38e

**Comment by sshane** [comment]
@incognitojam this car had a route where the camera didn't respond to the Ford query, but it did the Mazda query:

```
                         {'address': 1798,
                          'brand': 'mazda',
                          'bus': 0,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'LB5T-14F397-AF\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
                          'logging': True,
                          'obdMultiplexing': True,
                          'request': [b'"\xf1\x88'],
                          'responseAddress': 1806,
                          'subAddress': 0},
```

**Comment by richardkaplan** [comment]
If you tell me which route I can tell you if there was anything different about that trip.  Is it only one route that is different or are there multiple ones?

In the past week or so I switched from Openpilot to Frogpilot; might that result in what you are observing?

**Comment by incognitojam** [comment]
I'm not sure. The Mazda query is the same as the Ford query, just without the tester present message. I believe the CAN FD Fords see the same thing (although the cause is probably not the same there).

**Pull request closed without merging**
