### PR TITLE
replay: fix visionbuf alignment on device

### LINKED ISSUE #26810: replay: make it work on device
An error in cameraview.cc is thrown on this line: https://github.com/commaai/openpilot/blob/08b4cff484940b394fa64d89dad65330bcb51a4a/selfdrive/ui/qt/widgets/cameraview.cc#L328

### PR DESCRIPTION
**Pull request by deanlee**
eglCreateImageKHR only works with multiples of 32.  

use the same `align/stride/size` as camerad to fix this issue.

### CODE REVIEW

**Comment by deanlee** [comment]
@sshane Can you help me to test if it works on the device? my c3 is broken and cannot be used.

**Comment by sshane** [comment]
@deanlee what is wrong with your C3? would you like us to check it out or replace it?

**Comment by sshane** [comment]
But yes, it's working on device for me!

**Comment by adeebshihadeh** [comment]
@deanlee any reason this is a draft?

**Comment by deanlee** [comment]
I haven't tested it on the device yet. Also, I'm worried about the performance of video decoding on device.

**Comment by adeebshihadeh** [comment]
It's still good to get this fix in even if the whole thing isn't performant yet.

**Comment by deanlee** [comment]
ready for review

**Review by adeebshihadeh — APPROVED** [review]
LGTM, @sshane can you give this a quick test and merge?

**Comment by sshane** [comment]
Not too performant, but works!

https://github.com/commaai/openpilot/assets/25857203/71455231-20da-482e-a535-e883c5494e1f

**Pull request merged**
