### PR TITLE
Ram Long/S0/CruiseFix

### PR DESCRIPTION
**Pull request by realfast**
@adeebshihadeh suggested I submit this as a dirty PR. 

Included is an initial step towards long control for Ram trucks which should roll over to all Chryslers. Chryslers use m/s2 for deceleration, but torque for acceleration. I have left live tuning in to allow quick adjustments while we work towards something acceptable. 

A steer to 0 fix for all Ram DT trucks. If a truck does not allow true steer to 0, we can turn the control bit on over 32mph and leave it on. The only drawback is we have to turn the bit off if the truck ever shifts out of drive. 

The last fix includes eliminating the cruise resume/cancel spamming for Rams. I block the messages to the DASM from the cruise buttons and send them with car controller instead.

### CODE REVIEW

**Comment by stephenkelzer** [comment]
Is there anything that I can do to help move this across the finish line? I am new to OpenPilot (installed my Comma3 last week!)..  But I do have a Ram 1500 and I am willing to test/debug if someone can help describe to me the proper process for doing so. I may be new to OP, but I am a programmer by trade, so hoping I can contribute as needed!

**Comment by encyphered** [comment]
@stephenkelzer This PR is stale but there are other branches on @realfast 's fork including this change. You can discuss or contribute to the fork and branch in RAM OP user Discord.

**Comment by sshane** [comment]
@realfast Do you want to split out your fixes into separate, smaller, mergeable pull requests?

**Comment by adeebshihadeh** [comment]
Thanks for getting this started @realfast! @gregjhogan is working on this now (see #30460), so I'm gonna close this.

**Pull request closed without merging**
