### PR TITLE
Honda: clean up CarInterface.apply and CarController

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
@sshane Can you rebase and merge this?

**Comment by adeebshihadeh** [comment]
@sshane Can you rebase and merge this?

**Comment by royjr** [comment]
This commit gives me a "Controls Unresponsive, Reboot Device" on a 22civic. All LKAS related errors show up on dashboard. Reverting fixes it.

**Comment by sshane** [comment]
Do you have a route with the error?

**Comment by royjr** [comment]
Yes, sorry.
78cf0d966dfab08e|2022-03-19--10-33-53

**Comment by adeebshihadeh** [comment]
Here's the crash. This isn't exactly what's in master. Are you sure you pulled properly and there are no diffs? Perhaps try `git fetch && git reset --hard origin/master`.
```
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/manager/process.py", line 42, in launcher
    getattr(mod, 'main')()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 757, in main
    controls.controlsd_thread()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 751, in controlsd_thread
    self.step()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 743, in step
    self.publish_logs(CS, start_time, CC, lac_log)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 633, in publish_logs
    self.last_actuators, can_sends = self.CI.apply(CC)
  File "/data/openpilot/selfdrive/car/honda/interface.py", line 424, in apply
    ret = self.CC.update(c, self.CS)
  File "/data/openpilot/selfdrive/car/honda/carcontroller.py", line 257, in update
    can_sends.extend(hondacan.create_ui_commands(self.packer, self.CP, pcm_speed, hud, CS.is_metric, idx, CS.stock_hud, frame))
NameError: name 'frame' is not defined
```

**Comment by royjr** [comment]
Wasn't aware of the errorLogMessage dropdown. All good, thanks!

**Pull request merged**
