### PR TITLE
C2: add button to launch wifi settings in text window

### PR DESCRIPTION
**Pull request by deanlee**
If there is a startup error and the Wifi is not automatically connected, the only way to ssh to the C2 is re-flash the device, and run setup again

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
It would be cool to add the wifi settings as a button in the power menu in NEOS, though I'm not sure if we're doing another NEOS yet.

**Comment by pd0wm** [comment]
I assume this needs the event filtering, otherwise touches will also be handled by the Qt app and you can accidentally click Reboot/Exit. https://github.com/commaai/openpilot/blob/master/selfdrive/ui/qt/window.cc#L88

**Comment by deanlee** [comment]
tested on c2,lgtm

**Comment by adeebshihadeh** [comment]
We'll likely ship a new NEOS for 0.8.13, so I'll look into adding this into the power menu.

**Comment by adeebshihadeh** [comment]
NEOS 19 will have a settings button in the power menu.

**Pull request closed without merging**
