### PR TITLE
Increase Volt's steering limit

### PR DESCRIPTION
**Pull request by vntarasov**
Requires https://github.com/commaai/panda/pull/136.

Anything more than 300 will generate SCM faults, meaning steering would be lost for a split second. 300 can be applied without a fault (see screenshot).

### CODE REVIEW

**Comment by vntarasov** [comment]
Requires https://github.com/commaai/panda/pull/136.

When the drive uploads, I will attach a cabana screenshot from taking a sharp turn with this, using steering to this limit, and not causing SCM fault.

**Comment by rbiasini** [comment]
my worries is that increasing the allowed steering torque would violate safety limits. Looking at the turn that requires max torque might help to understand if the increased torque is still within the safe zone.
Also, have you tried to see if it faults at high speeds? in the Cadillac the limit seems speed dependent.

**Comment by vntarasov** [comment]
Going through a turn with steering 300, at about 53 mph:
300-ok

**Comment by vntarasov** [comment]
Going through a turn with steering 300, at about 53 mph:
300-ok-vego

**Comment by rbiasini** [comment]
@vntarasov , still happy with 300?

**Comment by vntarasov** [comment]
@rbiasini, 300 works great!
One quirk is that on GM, panda won't stay in DFU if there is a GMLAN traffic. Car needs to stay off for a few minutes for flashing to work.  With old firmware & limits in panda, people will lose steering in sharp turns :/

**Comment by rbiasini** [comment]
@TheMutley would be hard to develop with that I think. let me think about it.

**Comment by rbiasini** [comment]
@vntarasov this PR also need the panda FW change btw, with version bump so the FW reflash happens.

**Comment by vntarasov** [comment]
@rbiasini Thanks, done!

**Pull request merged**
