### PR TITLE
cabana: Copy log history selection to clipboard

### PR DESCRIPTION
**Pull request by jakethesnake420**
Allows you to copy the selection from the log history view.

image

```
37570, 47587
33474, 47587
29378, 47587
25282, 47587
21186, 47587
17090, 47587
12994, 47587
8898, 47587
4802, 47587
706, 47587
62146, 47587
58050, 47587
53954, 47587
49858, 47587
45762, 47587
41666, 47587
37570, 47587
33474, 47587
29378, 47587
```

### CODE REVIEW

**Comment by jakethesnake420** [comment]
I think its better to just install an event filter in the LogsWidget instead

**Comment by deanlee** [comment]
Not sure it's worth it to implement this with 35 lines of code. The output also doesn't quite match the semantics of `ctrl+c`, but is more like an export. Adding a button to export to a csv file might be better if the results are to be processed and searched in text.
@sshane what do you think?

**Comment by adeebshihadeh** [comment]
Agree with @deanlee

**Comment by jakethesnake420** [comment]
ok well i hope you provide an alternative implementation. I feel like the way i implemented it is pretty simple intuitive from a users prospective. Not sure how to do it with less code though.

**Comment by deanlee** [comment]
@jakethesnake420 I think you can use QShortcut&action, which avoids installing event filter on self and saves code as well.

**Comment by deanlee** [comment]
https://github.com/commaai/openpilot/pull/30800

**Pull request closed without merging**
