### PR TITLE
Add Fingerprint for 2024 Kia Sorento Hybrid

### PR DESCRIPTION
**Pull request by yojomapa**
***** Fingerprint *****

**Car**
Kia Sorento HEV 2024

**Route**
`61625dc4f9dfee19|2023-12-10--20-06-18`
This route doesn't have a carFw key, but instead I found the FP searching for clues: `MQ4` and  `MQhe` to find these 2 entries

`'xf1\x00MQhe SCC FHCUP      1.00 1.07 99110-P4000         '`
`'xf1\x00MQ4HMFC  AT USA LHD 1.00 1.13 99210-P2000 230619'`

Tested the branch with this subsequent route and it fixed the `Car Unrecognized` message
Test Route:
`61625dc4f9dfee19|2023-12-11--02-21-38`

### CODE REVIEW

**Comment by sshane** [comment]
Can you drive on openpilot for a little longer to gather data? Want to check what torqued learns for your params, they look quite lower than what we have at 2.5 m/s^2 for this car, while I saw your car max out at 1 m/s^2 on one turn.

**Comment by yojomapa** [comment]
> Can you drive on openpilot for a little longer to gather data? Want to check what torqued learns for your params, they look quite lower than what we have at 2.5 m/s^2 for this car, while I saw your car max out at 1 m/s^2 on one turn.

Indeed I was going to ask about torque sooner or later, it is very weak, seen the Take Control in Curve several times now because of weak torque, that was disappointing TBH.

At the moment I have no longer routes but shorter, I haven't even engaged OP on those... will update when I get a longer one! 

Thank you!

**Comment by yojomapa** [comment]
@sshane Latest route, with a CX3 Crash included
61625dc4f9dfee19|2023-12-12--08-08-42

**Comment by sshane** [comment]
We still need a bit more driving from you, preferably at higher speeds with some curves, torqued hasn't gathered any data so far.

Looks like it could be an OBD C cable issue, can you try another one, or reseat it?

**Comment by yojomapa** [comment]
> We still need a bit more driving from you, preferably at higher speeds with some curves, torqued hasn't gathered any data so far.
> 
> Looks like it could be an OBD C cable issue, can you try another one, or reseat it? If there are no errors on startup, it should be working.

Ok, I will I just haven't got out of town these days. I don't have another OBD C cable, just realized that it is not the same as USB-C, I would reseat it but if this doesn't improve I guess I would have to bought/request another one from the comma shop

**Comment by yojomapa** [comment]
@sshane here are my longest 2 routes to date, please take a look!
Took the highway to the Safeway next town:
-`61625dc4f9dfee19|2023-12-12--22-08-13`
and back home: 
-`61625dc4f9dfee19|2023-12-12--22-43-40`

Unfortunately, I got the same `faulty cable error message`, on both routes, roughly 7 minutes later after engaging OP... I am not sure about it because I enter the Safeway and 20 minutes later came out and jump in the car, and when I turn it on, the issue with the cable was gone, the error messages from my car also were gone. Until 7 minutes later when it happened again when returning home. So frustrating, I cannot get more data because I am not sure how to fix it while driving.

I hope it is useful this time

**Comment by sshane** [comment]
Strange, your car's steering response looks extremely non-linear.

Here you're at ~1 m/s^2 and torque is ~50% (61625dc4f9dfee19|2023-12-12--22-43-40)

image

But then it also seems to bottom out quickly at 1 m/s^2 here (61625dc4f9dfee19|2023-12-12--22-08-13):

image

---
@nuwandavek seen any Hyundai that acts like this?

**Comment by yojomapa** [comment]
@sshane What should I do about the `can bus disconnected: likely faulty cable` I was trying to contact support at `https://www.comma.ai/support` but there is not form to fill there, just a self link to `https://www.comma.ai/support` in the section `How do I contact support?`. Should I request a new cable? Where? Is it a software issue?

**Comment by yojomapa** [comment]
> @sshane What should I do about the `can bus disconnected: likely faulty cable` I was trying to contact support at `https://www.comma.ai/support` but there is not form to fill there, just a self link to `https://www.comma.ai/support` in the section `How do I contact support?`. Should I request a new cable? Where? Is it a software issue? image

Just got a surprising response in discord mentioning the problem is fingerprint related issues
https://discord.com/channels/469524606043160576/871838269405556736/1184615427486265366

**Comment by sshane** [comment]
Select one of these options on that page:

image

**Comment by yojomapa** [comment]
Thank you @sshane
I reseat all cables again and leave the cover on the windshield open, and this time I didn't got the `Can bus disconnected` so got this route, longest one with OP engaged: `61625dc4f9dfee19|2023-12-14--22-22-00`

The lack of torque was very notable on that one, got lots of Warning to take control because curve exceeded torque, please take a look!

**Comment by sshane** [comment]
Thanks, that's a good route to look at. Can you now disable openpilot in the settings, and get route with the stock LFA system handling curves and straightaways? I want to see what it does generally.

**Comment by yojomapa** [comment]
> Thanks, that's a good route to look at. Can you now disable openpilot in the settings, and get route with the stock LFA system handling curves and straightaways? I want to see what it does generally.

HI @sshane this is the route with OP disabled: `61625dc4f9dfee19|2023-12-15--21-53-45`
It was scary at some points, with OP at least it tells you to take control, stock LKA just disconnects with no warning in the middle of a curve 😬

**Comment by sshane** [comment]
I bumped up the openpilot steering limits, your car is achieving significantly different lateral accel for the torque we apply, unlike other CAN FD cars. It's more similar to CAN cars.

**Comment by yojomapa** [comment]
Thank you @sshane, I tried it today: I couldn't just update the branch, I had to uninstall and reinstall. Did I did something wrong?

Anyway, I wanted to do the same route as before but got bugged by the "CAN Bus Disconnected Likely Faulty Cable" and couldn't do it properly so this is what I got.

It feels better, but I still managed to hit the Steer Limit several times, you can see it in these 2 routes

61625dc4f9dfee19|2023-12-21--23-00-05
61625dc4f9dfee19|2023-12-21--23-06-21

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
