### PR TITLE
GM: Trax 2024 support

### PR DESCRIPTION
**Pull request by aabc88**
This pull request is for porting Trax.

**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [ ] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [ ] route with openpilot:
- [ ] route with stock system:

unable to add route file. because I use eon, please review and support so that other users can participate.

### CODE REVIEW

**Comment by sshane** [comment]
Unfortunately we strongly prefer a route from each unique platform we add. Also, it should probably not be matching to the Silverado, we'll need a route to see what's going on.

**Comment by MisterBamboozle** [comment]
I've got the 2024 Trax, and Comma 3x. What do I have to do to help?

**Comment by aabc88** [comment]
> I've got the 2024 Trax, and Comma 3x. What do I have to do to help?
Have you inserted the Trax footprint? If so, please share the route name in comma connect.

**Comment by aabc88** [comment]
190: 6, 193: 8, 197: 8, 201: 8, 209: 7, 211: 2, 241: 6, 249: 8, 288: 5, 298: 8, 304: 3, 309: 8, 311: 8, 313: 8, 320: 4, 322: 7, 328: 1, 352: 5, 381: 8, 384: 4, 386: 8, 388: 8, 413: 8, 451: 8, 452: 8, 453: 6, 455: 7, 479: 3, 481: 7, 485: 8, 489: 8, 497: 8, 500: 6, 501: 8, 532: 6, 560: 8, 562: 8,563: 5, 565: 5, 608: 8, 609: 6, 610: 6, 611: 6, 612: 8, 613: 8, 707: 8, 715:8, 717: 5, 761: 7, 789: 5, 800: 6, 810: 8, 840: 5, 842: 5, 844: 8, 869: 4, 880: 6, 977: 8, 1001: 8, 1011: 6, 1017: 8, 1020: 8, 1217: 8, 1221: 5, 1233: 8,
1249: 8, 1259: 8, 1261: 7, 1263: 4, 1265: 8, 1267: 1, 1271: 8, 1280: 4, 1296: 4, 1300: 8, 1930: 7

this is the footprint

**Comment by aabc88** [comment]
I closed it by mistake. I will pull request after testing with trax users.

**Comment by sshane** [comment]
@MisterBamboozle what is your dongle ID? We just need a test route from you!

**Comment by MisterBamboozle** [comment]
> @MisterBamboozle what is your dongle ID? We just need a test route from you!

Where do I locate the dongle ID?

**Comment by MisterBamboozle** [comment]
d5b72a0baffc2b0b

**Comment by sshane** [comment]
@MisterBamboozle looks like yours is already working, fingerprinting as the very similarly-sized Chevy Trailblazer 2021-22. All we need from you is a test route on **stock openpilot**, just drive from parking lot to parking lot, 10 minutes max, with some enabled time. Then just let me know when done and it's on Wi-Fi to upload the logs.

**Comment by MisterBamboozle** [comment]
@sshane I currently have it on Sunny Pilot and selected the vehicle as a trailblazer due to a recommendation. So I would reset the device and just install stock open pilot?

**Comment by sshane** [comment]
Yes please try stock/master to see what it fingerprints as, if at all. You can message me on Discord if you'd like: sshane_

**Comment by MisterBamboozle** [comment]
I believe I did as requested, logs uploaded. I drove on stock, but open pilot wasn't controlling anything like on Sunny

**Comment by sshane** [comment]
@MisterBamboozle please drive on master so we can get your updated vehicle fingerprints, we added GM FW query recently, so this will be good data for that.

**Pull request closed without merging**
