### PR TITLE
loggerd: refactor LoggerHandle & LoggerState

### PR DESCRIPTION
**Pull request by deanlee**
1. use `std::shared_ptr` to  greatly simplify `LoggerHandle` & `LoggerState`
2. rewrite test case

### CODE REVIEW

**Comment by deanlee** [comment]
test_logger.py:

```
selfdrive/loggerd/loggerd.cc: camera 0 rotate encoder to /data/media/0/realdata/2021-11-03--02-07-01--5
selfdrive/loggerd/loggerd.cc: camera 1 rotate encoder to /data/media/0/realdata/2021-11-03--02-07-01--5
selfdrive/loggerd/loggerd.cc: rotated to /data/media/0/realdata/2021-11-03--02-07-01--6
selfdrive/loggerd/loggerd.cc: camera 0 rotate encoder to /data/media/0/realdata/2021-11-03--02-07-01--6
selfdrive/loggerd/loggerd.cc: camera 1 rotate encoder to /data/media/0/realdata/2021-11-03--02-07-01--6
selfdrive/loggerd/loggerd.cc: rotated to /data/media/0/realdata/2021-11-03--02-07-01--7
selfdrive/loggerd/loggerd.cc: camera 0 rotate encoder to /data/media/0/realdata/2021-11-03--02-07-01--7
selfdrive/loggerd/loggerd.cc: camera 1 rotate encoder to /data/media/0/realdata/2021-11-03--02-07-01--7
killing loggerd
sending signal 2 to loggerd
selfdrive/loggerd/loggerd.cc: closing encoders
selfdrive/loggerd/loggerd.cc: closing logger
loggerd is dead with 0
killing camerad
sending signal 2 to camerad
Stopping listener for: camerad
camerad is dead with 0
.
----------------------------------------------------------------------
Ran 5 tests in 160.838s
```

**Comment by adeebshihadeh** [comment]
What's the goal of this refactor? Does this help make loggerd more testable?

**Comment by deanlee** [comment]
It's easier to read and maintain.  there are only 30 lines of code to implement the `LoggerState` excluding the header file.
I think this implementation is also more robust, thread-safe(e.g, we did not protect the access of segment_path before), and efficient (Only one lock is needed to write the log while the previous `logger_log` requires two locks) than the current implementation.

**Comment by adeebshihadeh** [comment]
Sounds good, but I'd like to get tests written to cover all of the log requirements (#22095) for training before merging any more loggerd changes.

**Pull request closed without merging**
