### PR TITLE
carla sim: fix missing camera

### PR DESCRIPTION
**Pull request by ebadi**
Passing ` --high_quality --dual_camera` to `bridge.py` solved the camera issue for me. 

image

Closes:
#26503 #26595

### CODE REVIEW

**Comment by incognitojam** [comment]
is --high_quality required for this to work?

**Comment by ebadi** [comment]
@incognitojam  `--high_quality` is *not* needed, but I think `UI` should run in `--high_quality` . 

Reducing simulator quality is introduced for CI purpose ([Simulator: Fix CI and set low_quality default](https://github.com/commaai/openpilot/commit/ee433dfa57a60364423a222a7f18dc137b77f532)). 

For CI, OP still run in low quality by default:
https://github.com/commaai/openpilot/blob/master/tools/sim/tests/test_carla_integration.py#L45

**Comment by jeroenlammersma** [comment]
@ebadi correct, `--high_quality` is indeed not needed. Just now I tried for myself and passing the `--dual_camera` flag does the trick.

But unfortunately, there is currently an issue with steering as well.

**Comment by ebadi** [comment]
> @ebadi correct, `--high_quality` is indeed not needed. Just now I tried for myself and passing the `--dual_camera` flag does the trick.
> 
> But unfortunately, there seems to be an issue with steering currently as well.

@jeroenlammersma  Great that it works for you.   Here (#26829) I am also working on refactoring `bridge.py` . You might be interested to try it out. If this one also doesn't work, please open a separate issue.

**Comment by jeroenlammersma** [comment]
> @jeroenlammersma Great that it works for you. Here (#26829) I am also working on refactoring `bridge.py` . You might be interested to try it out. If this one also doesn't work, please open a separate issue.

Looks good, great addition! Currently, I have a vacation, but when I am back I will try it out ;-).

Furthermore, perhaps interesting for you, at the moment I am supervising two student groups at the Hanze University of Applied Sciences that are improving driving with openpilot using the (CARLA) simulator as well. Their assignments are:
- Improve manual driving by implementing [manual_control.py](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py) (and if time allows, [manual_control_steeringwheel.py](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control_steeringwheel.py)) from CARLA in the bridge. This allows multiple key presses at once, as well as more controls (like blinkers, lights, etc). 
- Make Driving Monitoring (DM) (optionally) available in the bridge and make use of a connected webcam.

Because openpilot is (currently) illegal to use in the Netherlands, our aim is to experiment in the simulator. Next to that, we want to see if we can use the comma three and openpilot as base for the development of a virtual driving coach. So, that's why we need DM to work in a simulated environment.

If you want, I can keep you updated when their projects have some working protoypes.

Cheers, Jeroen

**Comment by ebadi** [comment]
> > @jeroenlammersma Great that it works for you. Here (#26829) I am also working on refactoring `bridge.py` . You might be interested to try it out. If this one also doesn't work, please open a separate issue.
> 
> Looks good, great addition! Currently, I have a vacation, but when I am back I will try it out ;-).
> 
> Furthermore, perhaps interesting for you, at the moment I am supervising two student groups at the Hanze University of Applied Sciences that are improving driving with openpilot using the (CARLA) simulator as well. Their assignments are:
> - Improve manual driving by implementing [manual_control.py](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control.py) (and if time allows, [manual_control_steeringwheel.py](https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control_steeringwheel.py)) from CARLA in the bridge. This allows multiple key presses at once, as well as more controls (like blinkers, lights, etc). 
> - Make Driving Monitoring (DM) (optionally) available in the bridge and make use of a connected webcam.
> 
> Because openpilot is (currently) illegal to use in the Netherlands, our aim is to experiment in the simulator. Next to that, we want to see if we can use the comma three and openpilot as base for the development of a virtual driving coach. So, that's why we need DM to work in a simulated environment.
> 
> If you want, I can keep you updated when their projects have some working protoypes.
> 
> Cheers, Jeroen
> 

Interesting 🤔. I am on vacation until 4-5th January and until then i have no access to my laptop (using mobile phone now).  When I am back i will share interesting resources/pointers with you.

**Comment by adeebshihadeh** [comment]
Both flags, `--high_quality --dual_camera`, were added since the CARLA system requirements are much higher than openpilot's. Closing since I think leaving both off is still the best default. #24689 describes the real fix.

> But unfortunately, there seems to be an issue with steering currently as well.

We have a CI test to ensure we don't entirely break the simulator, and eventually we want to have a test for the driving quality.

**Comment by zeroyang0809** [comment]
hello i meet the problem "openpilot unavailable waiting for controls to start"
this problem is familiar with your problem
do you know how to fix it ?
thx

**Pull request closed without merging**
