### PR TITLE
Add 2016 Optima Print

### PR DESCRIPTION
**Pull request by TK211X**
Did I do this right?

### CODE REVIEW

**Comment by elektroquake** [comment]
I can confirm this is working for my Kia Optima (this is my fingerprint)

2016 Kia Optima (EU) Sense Version / Spirit Version

**Comment by pd0wm** [comment]
There is overlap between two optima fingerprints. Can you merge them into one big fingerprint?

**Comment by TK211X** [comment]
The new print only has two additional messages. So removing the neighboring one should suffice. Right? @pd0wm

**Comment by TK211X** [comment]
image

**Comment by GeneralZyonix** [comment]
One thing to note, for my Kia Optima there are some changes to be made for steering values and to recognize turning signals, me and emu @discord are working on it, so I don't know if it is an issue? The fingerprint itself works and allows my car to be seen by openpilot.

**Comment by TK211X** [comment]
@GeneralZyonix Params learner will adjust the steering ratio regardless. Turning signal fix needs to be added into Master. Not sure why it wasn't in original PR.

**Comment by sshane** [comment]
Your car is now under the `KIA OPTIMA 2016` fingerprint. If you're able to try master, let us know how it goes!

**Pull request merged**
