### PR TITLE
Only print keyboard help on poll start and unknown command

### PR DESCRIPTION
**Pull request by mimi89999**
Avoids spamming the bridge output every 25 frames

### CODE REVIEW

**Comment by jnewb1** [comment]
nice, do you also want to look at fixing the keyboard control? just add a bit of hysteresis so that holding down a key gives constant manual control rather than flickering on and off

**Comment by mimi89999** [comment]
> nice, do you also want to look at fixing the keyboard control? just add a bit of hysteresis so that holding down a key gives constant manual control rather than flickering on and off

Well, not much can be done here. The keyboard controls are just reading stdin. To improve the controls, we would have to capture keyboard events and that can only be done in a focussed window, not in the terminal.

**Comment by jnewb1** [comment]
>  Well, not much can be done here. The keyboard controls are just reading stdin. To improve the controls, we would have to capture keyboard events and that can only be done in a focussed window, not in the terminal.

we can add some hysteresis, so it doesn't do the keyup until maybe 100ms of not receiving the keystroke. or perhaps we can make a simple pyqt window for controlling the simulator

**Comment by mimi89999** [comment]
The bigger issue is that we can't really handle multiple key presses. Let's say that you want to turn left and accelerate. It would be natural to hold w and a, but that is not really possible.

**Pull request merged**
