### PR TITLE
athenad: test connection timeout

### PR DESCRIPTION
**Pull request by incognitojam**
- test athena disconnects in a reasonable time after connection is lost (due to network change)
- test recovery and receives a ping after connection resumes

Findings:
- websocket takes 60 seconds before notifying that the connection is closed. I'm not sure what the mechanism is for this.

Related:
- https://github.com/commaai/openpilot/pull/26141

### CODE REVIEW

**Comment by incognitojam** [comment]
Will start a new PR for the changes to athenad and related tests

**Comment by sshane** [comment]
> websocket takes 60 seconds before notifying that the connection is closed. I'm not sure what the mechanism is for this.

is this still true?

**Comment by incognitojam** [comment]
> > websocket takes 60 seconds before notifying that the connection is closed. I'm not sure what the mechanism is for this.
> 
> is this still true?

It can be as low as 25s when onroad since https://github.com/commaai/openpilot/pull/29017

**Comment by sshane** [comment]
Ah I see, nice that must've been around the default timeout

**Comment by sshane** [comment]
Do we test this any where? It fails on my machine. Trying to see why it takes a while to reconnect and we lose some pings to fix the athena_connected dashboard:

```python
======================================================================
ERROR: test_offroad (__main__.TestAthenadPing.test_offroad) [LTE: attempt reconnect]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/athena/tests/./test_athenad_ping.py", line 91, in assertTimeout
    time.sleep(0.1)
  File "/data/pythonpath/common/timeout.py", line 20, in handle_timeout
    raise TimeoutException(self.error_msg)
common.timeout.TimeoutException: no reconnect attempt

======================================================================
ERROR: test_offroad (__main__.TestAthenadPing.test_offroad) [LTE: receives ping]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/athena/tests/./test_athenad_ping.py", line 99, in assertTimeout
    time.sleep(0.1)
  File "/data/pythonpath/common/timeout.py", line 20, in handle_timeout
    raise TimeoutException(self.error_msg)
common.timeout.TimeoutException: no ping received

======================================================================
ERROR: test_onroad (__main__.TestAthenadPing.test_onroad) [LTE: attempt reconnect]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/athena/tests/./test_athenad_ping.py", line 91, in assertTimeout
    time.sleep(0.1)
  File "/data/pythonpath/common/timeout.py", line 20, in handle_timeout
    raise TimeoutException(self.error_msg)
common.timeout.TimeoutException: no reconnect attempt

----------------------------------------------------------------------
Ran 2 tests in 299.444s

FAILED (errors=3)
```

**Pull request merged**
