### PR TITLE
ubuntu_setup.sh: support 22.04 LTS

### PR DESCRIPTION
**Pull request by MoreTore**
- Removed python-dev from install_ubuntu_common_requirements()
- Added case ubuntu 22.04
- Added install_ubuntu_21.10_requirements()
- Modified install_ubuntu_latest_requirements() to include python3-dev instead of python-dev

### CODE REVIEW

**Comment by MoreTore** [comment]
I understand you don't want to support 22.04 because of all the other compatibility issues but this at least allows those of us with newer PC's to get up and running faster.

**Comment by JasonJShuler** [comment]
@adeebshihadeh Does this mean it is ok to use 22.04 and submit PRs for any issues? You asked me to stop submitting fixes for 21.10 so I rolled back.

Are you interested in fixes for any issues encountered using 22.04 LTS?

Thanks!

**Comment by adeebshihadeh** [comment]
Use whatever you want on your machine. I just recommended 20.04 using if you're looking for the best experience. We're interested in legitimate fixes, but we're not interested in hacks, particularly for a platform we don't target.

**Comment by JasonJShuler** [comment]
> Use whatever you want on your machine. I just recommended using 20.04 if you're looking for the best experience. We're interested in legitimate fixes, but we're not interested in hacks, particularly for a platform we don't target.

Cool, thanks for the clarification. I didn't meant to be submitting hacks!

**Pull request merged**
