### PR TITLE
VW MLB: Audi A4/S4

### PR DESCRIPTION
**Pull request by jyoung8607**
**Checklist**

- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [ ] route with openpilot:
- [ ] route with stock system:
- [x] car harness used (if comma doesn't sell it, put N/A): VW J533

**Additional Tasks**

- [ ] commaai/opendbc#793
- [ ] commaai/panda#1289
- [ ] #27624
- [ ] upcoming PR to handle EPS timer resets
- [ ] Clean up abstractions, don't love the current structure
- [x] Migrate to lateral accel torque controller
- [ ] Find a TSK main switch signal
- [ ] Solve issue with door-open signals
- [ ] Solve issue with gearshift position signals
- [x] Verify BSM blocks lane changes
- [ ] Verify blinker comfort vs instantaneous

### CODE REVIEW

**Comment by jyoung8607** [comment]
General update: This port runs and drives quite well, it's being used by several people.

To qualify for dashcam-tier upstream support, opendbc CRC support needs to be finished and some abstractions need to be cleaned up in all three projects (opendbc, panda, openpilot). The CRC algorithm is substantially identical to MQB, but needs the usual per-message/counter data ID values calculated and added, with some MQB overlap and conflict to be resolved.

To quality for full upstream support, the remaining TODOs in this PR need to be resolved. Most notably there needs to be a mitigation for the six-minute lockout. I have agreement in principle with the openpilot team on how to do it.

The main holdup for this work is now lack of a supportable test car with supported hardware. For whatever reason, everyone that's shown up with a MLB with Adaptive Cruise has been using third-party or unsupported hardware. There are people driving with this code on C3/C3X, but none with Adaptive Cruise, so they need some mods that won't be eligible for upstream.

Anyone who has a [supportable MLB](https://github.com/commaai/openpilot/wiki/Volkswagen-Supported-Cars#mlb) with Adaptive Cruise Control, and is using a supported comma device, is welcome to contact me on Discord and I'll work with them to complete the port. This includes Porsche Macan, which *should* be supportable with a variant of this port.

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Comment by JackZhang12123** [comment]
I have Volkswagen the MLB based Phideon（380）， have one of these vehicles, with Adaptive Cruise Control，Therefore，one can be a volunteer To Test!

**Comment by dparring** [comment]
@JackZhang12123  Come to the VW channel on the comma discord - we have some working MLB vehicles

**Comment by FOREVERZAX1988** [comment]
I have Porsche Macan（2015）. Has it been verified that this model can support OpenPilot?

**Comment by dparring** [comment]
We have a working 2017, it should work on 15 but we don't know for sure.  LKAS and ACC needed

**Comment by FOREVERZAX1988** [comment]
> We have a working 2017, it should work on 15 but we don't know for sure.  LKAS and ACC needed

My car has ACC but not LKAS, though it has EPS. Can I still use it?

**Comment by dparring** [comment]
It may be possible to get your EPS recoded to respond to LKAS commands, but no one has confirmed this yet for Macan so we don't know for sure.  Come to the VW channel on the official discord and we can point you in the right direction.  This is still an early port and is not officially supported yet, but we have working Macans running OP on forks.

**Pull request closed without merging**
