### PR TITLE
UI: single-threaded CameraView

### LINKED ISSUE #27353: UI: draw model on matching frame

### PR DESCRIPTION
**Pull request by deanlee**
The main purpose of the original multi-threaded version is to upload textures in `vipcThread`, which is no longer needed. Converting it to non-blocking, single-threaded version  can simplify the code and does not result in a loss of performance.

The single-threaded version also makes it easier to synchronize the video and uiPlan (call `CameraView::receive(uint64_t preferred_frame_id)` with  the frame_id of uiPlan, ~It will be implemented in another pr if this one can be merged~ already implemented in this pr).

resolve: https://github.com/commaai/openpilot/issues/27353

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Oops, didn't mean to close. Nice catch that this is no longer necessary. This will need to be tested very thoroughly though since most of the onroad ui is driven by this widget.

**Comment by adeebshihadeh** [comment]
Ready for review?

**Comment by deanlee** [comment]
Not yet, need to clean up the code and do more testing.

**Comment by deanlee** [comment]
@adeebshihadeh reday for review

**Comment by adeebshihadeh** [comment]
@deanlee UI FPS appears to have regressed with this. Can you check it out? I'll wait a little bit to revert it in case it's a quick fix.

**Comment by deanlee** [comment]
@adeebshihadeh It's a bit odd. The time required for calling `cameraview::receiveFrame` in paintGL is less than even 0.05ms; theoretically, it shouldn't have any impact on the FPS. Moreover, since the waiting lock between threads has been removed, the overall performance of paintGL should be better. 
Did you run the replay first and then run the UI to test the value returned by fps_filter.update(1. / dt * 1000)?

**Pull request merged**
