### PR TITLE
Refactor image texture stuff into class

### PR DESCRIPTION
**Pull request by deanlee**
1.improved current implementation
2.fix texture memory leak

### CODE REVIEW

**Comment by pd0wm** [comment]
I'm going to merge in https://github.com/commaai/openpilot/pull/2023 soon, the linux.cc hacks are moved into qt/window.cc

**Comment by deanlee** [comment]
ok i got it

**Comment by pd0wm** [comment]
Let me know if you have any issues with running the new ui on your computer! Just fixed an issue when running on intel graphics.

**Comment by pd0wm** [comment]
I assume the cereal submodule shouldn't have been touched in this PR?

**Comment by deanlee** [comment]
Sorry it's my fault! fixed.

**Pull request closed without merging**
