### PR TITLE
Volkswagen Golf: add missing FW

### PR DESCRIPTION
**Pull request by nicakp**

### CODE REVIEW

**Comment by sshane** [comment]
What is your dongle id?

**Comment by nicakp** [comment]
Here it is do you need more info?

Nic

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicakp** [comment]
[image]()

**Comment by nicakp** [comment]
Hi Shane my comma3 still give the error of car unrecognized:(

**Pull request merged**
