### PR TITLE
fuzzy_generation.py: improve performance

### PR DESCRIPTION
**Pull request by deanlee**
1. Caching of native type strategies, the `generate_native_type()`  now retrieves strategies from a pre-defined map. This ensures efficient type generation and reduces the overhead of redundant checks. significantly improving performance.
2. Direct Attribute Check with `hasattr`: Instead of converting the capnp proto object to a dictionary and checking for the 'slot' key with `'slot' in field.proto.to_dict()`, use` hasattr(field.proto, 'slot')`. This avoids the expensive and repetitive dictionary conversion, significantly improving performance.
3. Skip creating strategies for **DEPRECATED** fields.
4. Replaced repeated calls to field_type.which() with the `type_which` variable.
5. Avoided unnecessary list creation: Directly used schema.non_union_fields which is a tuple.

This PR enhances the performance of `test_car_interface`, for example, the execution time of 

> 3.07s call     selfdrive/car/tests/test_car_interfaces.py::TestCarInterfaces::test_car_interfaces_170_TOYOTA_ALPHARD_TSS2

has been reduced to:

> 1.50s call     selfdrive/car/tests/test_car_interfaces.py::TestCarInterfaces::test_car_interfaces_170_TOYOTA_ALPHARD_TSS2

### CODE REVIEW

**Comment by sshane** [comment]
```
@given(data=st.data())
def test_car_interfaces(data):
  print('hi')
  print(FuzzyGenerator.get_random_event_msg(data.draw, ['carParams']))
test_car_interfaces()
hi
Falsifying example: test_car_interfaces(
    data=data(...),
)
hi
Traceback (most recent call last):
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-8683c029945e>", line 6, in <module>
    test_car_interfaces()
  File "<ipython-input-6-8683c029945e>", line 2, in test_car_interfaces
    def test_car_interfaces(data):
                   ^^^
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/hypothesis/core.py", line 1237, in wrapped_test
    raise the_error_hypothesis_found
  File "<ipython-input-6-8683c029945e>", line 4, in test_car_interfaces
    print(FuzzyGenerator.get_random_event_msg(data.draw, ['carParams']))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 78, in get_random_event_msg
    return [draw(fg.generate_struct(log.Event.schema, e)) for e in sorted(events)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 78, in <listcomp>
    return [draw(fg.generate_struct(log.Event.schema, e)) for e in sorted(events)]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in generate_struct
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in <dictcomp>
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 40, in generate_field
    return rec(slot_type)
           ^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 28, in rec
    return self.generate_struct(field.schema.elementType if base_type == 'list' else field.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in generate_struct
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in <dictcomp>
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 37, in generate_field
    if hasattr(field.proto, 'slot'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "capnp/lib/capnp.pyx", line 1159, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1157, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1153, in capnp.lib.capnp._DynamicStructReader._get
capnp.lib.capnp.KjException: capnp/dynamic.c++:141: failed: expected isSetInUnion(field); Tried to get() a union member which is not currently initialized.; field.getProto().getName() = slot; schema.getProto().getDisplayName() = capnp/schema.capnp:Field
stack: 7f926a179ba9 7f926a17d31a 7f926a17e0ff 7f926a04261d 7f9269fbbc5a 7f926ea61e7a 7f926eb0e4bd 7f926e9a8982 7f926eb14468 7f926ea079e8 7f926e9a8857 7f926eb14468 7f926ea07a43 7f926e9a8857 7f926eb142f4 7f926eb1005f 7f926e9a9498 7f926ea20fa4 7f926e9eefb4 7f926e9b0500 7f926ea20fa4 7f926e9eefb4 7f926e9b0500 7f926ea21fe4 7f926ea1487b 7f926ea082e7 7f926e9a96cd 7f926eb142f4 7f926eb60193 7f926eb61a11 7f926eb61f8e

```

**Comment by sshane** [comment]
Same with this, after enough runs:

```
@given(data=st.data())
def test_car_interfaces(data):
  print('hi')
  print(FuzzyGenerator.get_random_msg(data.draw, log.Event))

test_car_interfaces()


Falsifying example: test_car_interfaces(
    data=data(...),
)
hi
Draw 1: 'controlsState'
Traceback (most recent call last):
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-cb3d4d835f05>", line 6, in <module>
    test_car_interfaces()
  File "<ipython-input-9-cb3d4d835f05>", line 2, in test_car_interfaces
    def test_car_interfaces(data):
                   ^^^
  File "/home/batman/.pyenv/versions/3.11.4/lib/python3.11/site-packages/hypothesis/core.py", line 1237, in wrapped_test
    raise the_error_hypothesis_found
  File "<ipython-input-9-cb3d4d835f05>", line 4, in test_car_interfaces
    print(FuzzyGenerator.get_random_msg(data.draw, log.Event))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 72, in get_random_msg
    data: dict[str, Any] = draw(fg.generate_struct(struct.schema))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in generate_struct
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in <dictcomp>
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 40, in generate_field
    return rec(slot_type)
           ^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 28, in rec
    return self.generate_struct(field.schema.elementType if base_type == 'list' else field.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in generate_struct
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 47, in <dictcomp>
    return st.fixed_dictionaries({field: self.generate_field(schema.fields[field]) for field in fields_to_generate if not field.endswith('DEPRECATED')})
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/batman/openpilot/selfdrive/test/fuzzy_generation.py", line 37, in generate_field
    if hasattr(field.proto, 'slot'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "capnp/lib/capnp.pyx", line 1159, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1157, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1153, in capnp.lib.capnp._DynamicStructReader._get
capnp.lib.capnp.KjException: capnp/dynamic.c++:141: failed: expected isSetInUnion(field); Tried to get() a union member which is not currently initialized.; field.getProto().getName() = slot; schema.getProto().getDisplayName() = capnp/schema.capnp:Field
stack: 7f926a179ba9 7f926a17d31a 7f926a17e0ff 7f926a04261d 7f9269fbbc5a 7f926ea61e7a 7f926eb0e4bd 7f926e9a8982 7f926eb14468 7f926ea079e8 7f926e9a8857 7f926eb14468 7f926ea07a43 7f926e9a8857 7f926eb142f4 7f926eb1005f 7f926e9a9498 7f926ea20fa4 7f926e9eefb4 7f926e9b0500 7f926ea20fa4 7f926e9eefb4 7f926e9b0500 7f926ea21fe4 7f926e9a8df3 7f926eb142f4 7f926eb60193 7f926eb61a11 7f926eb61f8e 7f926eb82c42 7f926eb831b9

```

**Comment by deanlee** [comment]
I haven't tested this function. Let me check the issue.

**Comment by deanlee** [comment]
fixed ,need catch KjException for hasattr

**Pull request merged**
