### PR TITLE
Added pre-commit hooks to improve code quality.

### PR DESCRIPTION
**Pull request by dapperfu**
pre-commit: A framework for managing and maintaining multi-language pre-commit hooks.

Added code quality hooks for:

White space code:

-   id: trailing-whitespace
-   id: end-of-file-fixer

http://www.dinduks.com/why-are-trailing-whitespaces-bad/

Added pre-commit hooks to check that files are valid before committing:

- id: check-ast
- id: check-json
- id: check-xml
- id: check-yaml

Python code cleanup hooks:

- id: reorder-python-imports

Tool for automatically reordering python imports. Similar to isort but uses static analysis more.

> ## why this style?
> The style chosen by reorder-python-imports has a single aim: reduce merge conflicts.
> By having a single import per line, multiple contributors can add / remove imports from a single module without resulting in a conflict.
> - https://github.com/asottile/reorder_python_imports

### CODE REVIEW

**Comment by pd0wm** [comment]
See my comment on https://github.com/commaai/openpilot/pull/1575. Even more so for a 9000 line PR.

**Comment by dapperfu** [comment]
Did you even bother to look at the changes? It fixes whitespace. 

It passes all tests. It improves code quality and makes future merges easier.  This is a band-aid every code base needs sooner or later.

Do you have a better suggested way to make these changes? 9000 PR requests with one line change?

**Comment by pd0wm** [comment]
Yes, I looked at the PR.

Removing training whitespace is something that I support. However, this PR also includes the stuff that I didn't like, like the import reordering.

About adding support for this I would submit a PR with just the changes to the `.pre-commit-config.yaml`. Someone from comma can then make the commit that actually removes the whitespace. The PR is too big to review, and it's too much of a security risk to merge unseen.

Let me get https://github.com/commaai/openpilot/pull/1580 merged, and then you can submit a PR to add the whitespace stuff to the config.

**Comment by pd0wm** [comment]
Oh, and make sure you exclude `phonelibs`, `external` and `pyextra` those are considered libraries

**Pull request closed without merging**
