### PR TITLE
TICI default for PC

### PR DESCRIPTION
**Pull request by haraschax**

### CODE REVIEW

**Comment by pd0wm** [comment]
If you change this you also need to fix the CARLA side

**Comment by HaraldSchafer** [comment]
What needs to change in the CARLA side and where is that?

**Comment by pd0wm** [comment]
That code is here: https://github.com/commaai/openpilot/blob/master/tools/sim/bridge.py#L64

We'd need to add a second camera and make sure the vof/resolution match the tici cams.

**Comment by pd0wm** [comment]
This is the proper fix: https://github.com/commaai/openpilot/issues/22574

**Pull request closed without merging**
