### PR TITLE
cabana: highlight bit in binaryView when value changed

### PR DESCRIPTION
**Pull request by deanlee**
[Kazam_screencast_00051.webm](https://user-images.githubusercontent.com/27770/212670291-e527d45c-ff2b-4fec-bc5d-4d0949403921.webm)

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Cool!

**Comment by pd0wm** [comment]
Very nice!

If you have some indication of the change frequency per bit you can quickly see the boundary between two signals (the LSB will change much more than the MSB). Maybe some kind of gradient in the background or font?

**Comment by pd0wm** [comment]
Still WIP, but to show what I'm talking about:
Screenshot 2023-01-18 at 16 06 19
Screenshot 2023-01-18 at 16 06 14

**Comment by deanlee** [comment]
looks great!!!

**Pull request closed without merging**
