### PR TITLE
ui/onroad: remove unused imports

### PR DESCRIPTION
**Pull request by sunnyhaibin**
Cleanup few unused imports from https://github.com/commaai/openpilot/pull/32059

### CODE REVIEW

**Comment by deanlee** [comment]
This violates the include-what-you-use principle. These source files all need QPainter.h. The reason it still compiles after removing QPainter.h is that it is indirectly included through utils.h or other headers. Additionally, cpplint's includes-what-you-need check cannot detect missing Qt headers.

**Comment by devtekve** [comment]
> This violates the include-what-you-use principle. These source files all need QPainter.h. The reason it still compiles after removing QPainter.h is that it is indirectly included through utils.h or other headers. Additionally, cpplint's includes-what-you-need check cannot detect missing Qt headers.

Would it be better if the import were on `annotated_camera.h` ? or even if it is there, it's still recommended to have it on `annotated_camera.cc` ?

**Comment by deanlee** [comment]
> Would it be better if the import were on `annotated_camera.h` ? or even if it is there, it's still recommended to have it on `annotated_camera.cc` ?

It's not considered good practice in Qt to include unnecessary headers in your header files. Instead, Qt often uses forward declarations to improve compile times and reduce dependencies.

For example, the QWidget header might use forward declarations as follows:

> 
> class QPainter;
> class QPaintEvent;
> 
> class QWidget {
>   // ...
> };
> 

you can only include QWidget in your header file to inherit from it:

> 
> #include &lt;QWidget&gt;
> 
> class MyWidget : public QWidget {
>   void paintEvent(QPaintEvent*) override;
>   // ...
> };
> 
> 

Then, include the specific headers like &lt;QPainter&gt; and &lt;QPaintEvent&gt; in your source file to avoid compile errors:

> 
> #include "MyWidget.h"
> #include &lt;QPainter&gt;
> #include &lt;QPaintEvent&gt;
> 
> void MyWidget::paintEvent(QPaintEvent* event) {
>   QPainter painter(this);
>   // ...
> }

By doing this, you optimize your compile times and reduce unnecessary dependencies in your header files.

**Comment by sunnyhaibin** [comment]
Closing per @deanlee 's feedback.

**Pull request closed without merging**
