### PR TITLE
Add better Camry Hybrid fingerprint detection

### PR DESCRIPTION
**Pull request by arne182**
From sentry logs the Toyota Camry Hybrid creates unsupported car exceptions because 865:8 is missing

### CODE REVIEW

**Comment by legonigel** [comment]
Have you confirmed with the owner of this EON and this vehicle that this message is indeed present when the EON is installed and the vehicle is in stock mode or EON code were made?

**Comment by bugsy924** [comment]
That's on the private radar bus

**Comment by energee** [comment]
If a msg is on radar bus, shouldn't need to be in fingerprint.

**Comment by arne182** [comment]
@DoubleCapCrimpin can confirm this

**Pull request closed without merging**
