### PR TITLE
Params refactor

### PR DESCRIPTION
**Pull request by whowe444**
This PR addresses issue #1041 . I've basically done what @pd0wm suggested. 

1) I first built the C++ implementation and replicated the tests in openpilot/common/tests/test_params.py within the main method of openpilot/common/params_helper.cpp . I then built the cython wrapper using the new C++ params implementation and was able to pass all the python unittests. 

2) I symlinked my C++ implementation into selfdrive/common/params.cc and redid the implementation of params.cc using the new underlying implementation. This passes all tests as far as I can tell. I'm not sure if the test_params.cc file is used currently though...

Some sketchy things I had to do
------------------------------------------
1) the pylint checks fail on cython-derived extensions (as far as I can tell this is a bug in pylint) so I had to ignore these checks anytime anyone imports Params `# pylint: disable=no-name-in-module, import-error`

2) In order to pass the blocking unittest in common/tests/test_params.py which starts a thread, I have to release the GIL in the cython wrapper params.get blocking function. This allows the blocking variant of the get function to work while the non-blocking version does not with a delayed thread.  

3) I hope someone can more closely review DBWriter::exit() in params_helper.cpp. I tried to make the implementation fairly similar to the python in structure, but the params.py file had some weird exception handling in its exit() function. 

So, I'm passing the tests, but I worry that they are a low bar...

### CODE REVIEW

**Comment by ahowe444** [comment]
The first check fails only because there is no longer a params.py file, the extension is built in SConscript with cython.

**Comment by pd0wm** [comment]
Thanks for doing the refactor! This quite a big PR, so will take some time to review. Stay tuned!

**Comment by adeebshihadeh** [comment]
This is in the milestones for 0.7.10. Can you rebase on master?

**Comment by ahowe444** [comment]
> This is in the milestones for 0.7.10. Can you rebase on master?

yes, will do.

**Comment by pd0wm** [comment]
@ahowe444 Did you receive our email regarding the bounty?

**Pull request closed without merging**
