### PR TITLE
builds on M1 mac

### PR DESCRIPTION
**Pull request by geohot**
Should be okay to merge

### CODE REVIEW

**Comment by geohot** [comment]
The paren thing seems to be an issue

**Comment by geohot** [comment]
The web downloads from replay are coming up all 0s

**Comment by geohot** [comment]
Working to replay in UI

**Comment by pd0wm** [comment]
https://github.com/commaai/openpilot/blob/master/tools/mac_setup.sh works correctly on M1?

**Comment by deanlee** [comment]
is there any special reason for removed the support downloading to a file?

**Comment by geohot** [comment]
The stringstream doesn't work on mac for some reason, the returned string was all 0s. I looked for a bit and couldn't find the bug, so I switched it to this and it worked.

**Comment by geohot** [comment]
> https://github.com/commaai/openpilot/blob/master/tools/mac_setup.sh works correctly on M1?

I ran that in pieces. The brew stuff works correctly. For pipenv I installed into my system Python of 3.9.9

**Comment by deanlee** [comment]
> The stringstream doesn't work on mac for some reason, the returned string was all 0s. I looked for a bit and couldn't find the bug, so I switched it to this and it worked.

fixed this issue in https://github.com/commaai/openpilot/pull/23052

**Comment by khoi** [comment]
I ran `./tools/mac_setup.sh` in a fresh M1 machine. Got an error when installing `scipy `

```
  Error: 'pybind11' must be installed before running the build.
```

**Comment by adeebshihadeh** [comment]
M1 phonelibs are under `mac_arm64`, but we should probably move those to `Darwin` and move the x86 stuff to `mac_x86`.

**Comment by geohot** [comment]
Rebased, the new changes are a lot simpler.

**Comment by adeebshihadeh** [comment]
LGTM. I’ll clean up the phonelibs convention for Intel and M1 after this is merged.

**Pull request merged**
