### PR TITLE
c docs to docs.comma.ai

### PR DESCRIPTION
**Pull request by tecandrew**
# Overview 
redo of PR #22751 
rel: #22732

## Features 

* add c docs to https://docs.comma.ai 
  * doxygen-based documentation using `sphinx` and `breathe`
* adds some SEO stuff
* make it look prettier

image

### Misc
* uses `cmake` instead of `Makefile`
  * initially used to auto-generate _all_ C code using traditional `doxygen/cmake` template, but `sphinx-breathe` doesn't like some code (selfdrive/ui/qt, selfdrive/ui/widgets)
    * now only documents explicitly listed files in `docs/sphinx/c_docs.rst.in` 
* regenerates `Pipfile.lock`, adding `breathe` module

### CODE REVIEW

**Comment by pd0wm** [comment]
Nice!

Same comments as on the previous PR:
1. Can you convert the cmake build file into scons instead of introducing another build system? If you can't figure it out I can take a look as well.
2. Can we only check in the parts of the `Doxyfile.in` that are not the default settings?

**Comment by tecandrew** [comment]
I'll take a stab at scons. Might take a while to convert since i've never dev'd with it before

> 2. Can we only check in the parts of the `Doxyfile.in` that are not the default settings?

Not sure what you meant by this. 😅

**Comment by pd0wm** [comment]
You added a 2600 line that only contains the default settings. Does it also work if only add the options that we actually change?

**Comment by tecandrew** [comment]
I should take that out: sphinx is doing the XML creation, not doxygen Doxyfile explicitly: it's generating docs based off found .h and .c pairs. docs/sphinx/conf.py.in

**Comment by adeebshihadeh** [comment]
Can you split out all the listed features into their own PR?

**Comment by tecandrew** [comment]
> Can you split out all the listed features into their own PR?

yeah, i could do that, but it'll be based off `cmake` in it's current state.

**Pull request closed without merging**
