### PR TITLE
2016 RX350 F Sport corrections

### PR DESCRIPTION
**Pull request by ErichMoraga**
This fixes the botched PR I did yesterday...
https://github.com/commaai/openpilot/pull/1671
Accidentally used CAR.LEXUS_RXH_TSS2 firmware from my clipboard yesterday, instead of @gweedor#9653's...  Today I was extra careful ;-)

@gweedor#9653 DongleID 28f8c941d8b28743

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Confirmed working!

**Comment by rx3123** [comment]
Hi. I just installed my Comma2 today on my 2017 Lexus RX 350 F Sport, paired the app on my phone, and did a few test drives.  The screen shows the forward camera view well and depicts the white lane lines, white path, and multi-color lead car triangles, but there is no white steering wheel icon and the upper left always shows MAX N/A.  Vehicle speed is correct.  When I engage cruise control, the car's adaptive cruise control engages instead of OP.  Curiously, there was **no "calibration period" during the initial drive like I observed on some YouTube videos.**  OpenPilot software is installed and not dashcam; 2) Physically reseating all connections to ensure a tight fit; 3) Rebooting the device; 4) Checking for error messages on car and device (none); 5) Toggling "Enable Openpilot" and re-acknowledging disclaimers and completing training again; 6) Trying various car settings options for Lane Keep and Adaptive Cruise to see if that made a difference (it didn't).  Not sure what to try next.  I read you post on Discord for Ottopilot and it seemed like you solved his issue. Would you be abe to help with mine? Thank you kindly in advance.

**Comment by ErichMoraga** [comment]
Post FPv2 output in Discord, as seen in all the other situations.

**Comment by rx3123** [comment]
Thank you for your response, but what does that mean? I am not an engineer.

**Comment by ErichMoraga** [comment]
FPv2 cmd. is pinned in the Comma Discord #toyota-lexus channel.

**Comment by rx3123** [comment]
Actually...I do not know what FPv2 means

**Comment by ErichMoraga** [comment]
https://github.com/commaai/openpilot/wiki/Fingerprinting

**Comment by rx3123** [comment]
OK. Thank you. I will try. I may have to return the Comma 2 it because the bottom part of the Fingerprint seems a bit over my head. But I will upload my drive and try. Thank you again. Have a good weekend. Donald

**Comment by rx3123** [comment]
Just out of curiosity, why does the C2 need to be fingerprinted for a 2017 Lexus RX350 when the Comma 2 website states it is compatible with Lexus RX 2016-2017?

**Comment by ErichMoraga** [comment]
Various firmwares.

**Comment by rx3123** [comment]
OK. Thank you

**Pull request merged**
