### PR TITLE
tools/replay: reduce test running time

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
This was causing CI to fail randomly: https://github.com/commaai/openpilot/actions/runs/3269874259/jobs/5377882110

**Comment by deanlee** [comment]
It's  not related to this change. it's in another test section,looks like a a network issue. I'll check it again.
```
tools/replay/tests/test_replay.cc:120: FAILED:
  REQUIRE( remote_route.load() )
with expansion:
  false
```

**Comment by adeebshihadeh** [comment]
Ok, reopen if you confirm it's not related and I'll merge it again.

**Comment by deanlee** [comment]
ok,I'll reopen after confirmed

**Pull request merged**
