### PR TITLE
simplified diff for PRs

### LINKED ISSUE #32690: Car docs bot: diff on generated readme file
We have a bot that uses the car docs Python data structures and prints a pretty diff to each PR, if it changes any car docs. That could be vehicle name, supported trim, minimum steering speed, parts, or detail sentence for the website.

Current bot output: https://github.com/commaai/openpilot/pull/31888#issuecomment-2000768679

Our current solution requires checkouts and pickling, which is fragile: [print_docs_diff.py](https://github.com/commaai/openpilot/blob/master/selfdrive/debug/print_docs_diff.py) and [selfdrive_tests.yaml#L256-L308](https://github.com/commaai/openpilot/blob/c514ee7212f7ef43c7451d6e638dd54ec0643dcc/.github/workflows/selfdrive_tests.yaml#L256-L308).

Solution
---

Just use the base and head commit CARS.md files in the PR, for example:

```
wget -O master_table.md https://raw.githubusercontent.com/commaai/openpilot/master/docs/CARS.md
diff master_table.md docs/CARS.md
```

See the generated CARS.md README file: https://github.com/commaai/openpilot/blob/master/docs/CARS.md

Diffing behavior:
- [ ] Should be agnostic to the columns and other changes (you can add or remove without issues)
- [ ] Minimal understanding of the file, which makes this small, simple, and robust. You may need special handling of the detail sentence however, which is fine.
- [ ] Changes to column values should be picked up as a column change, not addition and removal. GitHub already does that for us!

### PR DESCRIPTION
**Pull request by agniv-the-marker**
**Description**

Should resolve [#32690](https://github.com/commaai/openpilot/issues/32690). Uses the ideas from [#32720](https://github.com/commaai/openpilot/pull/32720). 

The workflow now pulls the main CARS.md file with `wget` and passes it to the doc printer. The doc printer now uses `diff` which simplifies most columns. For detail sentence handling, updated docs_defns so that detail sentence was writable from the data in the row. Also simplified a function in docs.py (thought I could use it to generate the detail sentence) and updated the testing within dump car docs to get the main CARS.md as well.

**Verification**

Manually edited CARS.md on my machine, got expected results.

### CODE REVIEW

**Comment by agniv-the-marker** [comment]
Hopefully the workflow issues go away. That's embarrassing. 

Anyway, @sshane mentioned hoverable tooltips, which looks like [its possible](https://github.com/BoostIO/BoostNote-Legacy/issues/3579#issuecomment-855449583). It would require changing it to format the template into something like `[make](## detail_sentence)`.

**Comment by agniv-the-marker** [comment]
Ok, so the PR workflow should be working now. I don't really understand what exactly is going on and why you can't just do something like:


```yaml
- name: Get info
  run: | 
    mkdir -p /path/
    wget -O /path/CARS.md link
- name: Save diff
  id: save_diff
  run: |
    output=$(${{ env.RUN }} "python selfdrive/debug/print_docs_diff.py --path /tmp/openpilot_cache/base_car_docs")
    output="${output//$'\n'/'%0A'}"
    echo "::set-output name=diff::$output"
```

Otherwise it takes a bit of time on the `- uses: ./.github/workflows/setup-with-retry` step. Any advice greatly appriciated.

**Comment by agniv-the-marker** [comment]
All right. @sshane please let me know how this looks. Sorry it took so long (and so many checks!).

**Comment by sshane** [comment]
Can you show a few example comments it might leave, testing a few diffs (column value change, adding/removing row, and detail sentence)? You might need to open a PR to your own repo to allow the workflow to run and comment

**Comment by agniv-the-marker** [comment]
@sshane , should be fully done now. Updated it so that commons wasn't imported. Also updated the handling of the file so that icons were appropriately shown. The issue with displaying an example is that they're often just too long lol. Here's a short one linked below.

https://github.com/agniv-the-marker/openpilot/pull/4#issuecomment-2273606740

**Comment by agniv-the-marker** [comment]
dislike how this is a little longer and could definitely be faster. would love advice on how to do that, though now with the new import restriction i think you have to build openpilot to get access to the detail sentence builder/relevant Enums, so I think this is ok. 

in terms of shorter code, there are probably nicer more pythonic ways of dealing with the stars/videos than how i did it. definetly gets the job done (and i like using the same function twice in a cute way).

**Comment by adeebshihadeh** [comment]
Closing, responded on Discord

**Pull request closed without merging**
