### PR TITLE
Honda Pilot tuning / lane centering fixes

### PR DESCRIPTION
**Pull request by ghost**
Tuned kP and kI and Tire Stiffness Factor settings.
Fixes lane centering issues in the following situations:
1.  Hugging of left lane line during fast left curving roads
2.  Hugging of right lane line during fast right curving roads
3.  Left bias in fast lane on crowned roads (sloping down to the left)
4.  Right bias in slow lane on crowned roads (sloping down to the right)
Works well with lane_width = 2.85 in pathplanner.py

### CODE REVIEW

**Comment by vikovo** [comment]
I’m driving a Honda Pilot 2019 ex-l. Noted noticeable improvement on fast lane curves especially against the barricade. Car remain centered and steady. Did not require manual interference.

**Comment by vikovo** [comment]
I didn’t note any wobble

**Comment by jfrux** [comment]
Going to test this...

**Comment by jfrux** [comment]
Just tested this on my morning commute.
It seemed okay, I didn't notice anything significant or profound in this.
A lot of these minor changes are hard to really gauge their benefit.

I definitely don't see any negative side-effects thus far.

Let me test on my commute home as that is always a bit more vigorous and I'm generally paying more attention to its behavior.

**Comment by kegman** [comment]
The changes are subtle, especially if you don't have heavily crowned roads where the slope is steep on the fast / slow lanes.  It "sticks" to the center more strongly, especially around fast curves where you are hitting the steering limit due to the stronger gain.  If you are driving on straight flat, center lanes you probably won't notice the difference.

**Comment by rbiasini** [comment]
ok, there is enough consensus. Will merge.

**Comment by jfrux** [comment]
Brake noise issue is good, this one I'm not sure its good for 2017.
My pilot is getting lots of steering warnings and shake... weather isn't the best so it could be a fluke...
I'll leave this one up to Riccardo...

**Comment by kegman** [comment]
Did the shake happen this morning?

**Comment by rbiasini** [comment]
well, it's just tuning, so it's your call guys. I just need to make sure it does not introduce weird behaviors for anybody.
:-1:  I'll revert, :+1: I'll keep

**Comment by jfrux** [comment]
I'm not sure I can get behind this change at this time...
I don't see any improvements, I do see some places where it is actually worse in the most simplest of straights and basic turns I get way more alerts and random steering shakes on expressways.

I'm not saying we don't need some adjustments but at this time I don't know if this one is it...

Although it may improve in certain situations like backroads or state routes, I think I'd rather have it back the way it was and just wait it out for HD Maps.

Or maybe we need some sort of config file system built soon that accepts a YAML file so people can make their tweaks without forking and modifying the code.

**Comment by kegman** [comment]
Perhaps you're right it only improves for 2018/2019 model.  Or perhaps my particular car has some variances that most cars don't.    Im fine with a reversion to the way it was before... Its gotta work well for the majority, not just for me.

**Comment by rbiasini** [comment]
allright. I'll revert. Proper solution seem to differentiate between 2017 and 2018+ models

**Pull request merged**
