### PR TITLE
Subaru Impreza 2018 tuning

### PR DESCRIPTION
**Pull request by michaelhonan**
## Tuning
This pull request modifies the Subaru Impreza tuning values that were presumably placeholder values since Subaru support was added. The original values caused a lot of overshooting on bends, and unstable steering wobble at low speeds. For the most part (outside of some extreme edge cases), these issues have been solved with the tuning values specified.

## Description
An update to Subaru Impreza 2017-2019 (2020?) tuning that provide a smoother lateral control experience.

## Testing
Been monitoring and modifying these values through trial and error over the past few months and I've stuck with these values for the past month or so. Very happy with the results, as OP no longer overshoots on easy turns, and is a lot more stable when taking off from standstill, and steering at low speeds.

### CODE REVIEW

**Comment by rbiasini** [comment]
@mchonan1996 , I see why this tuning might be better. I'll wait for a couple of other users to confirm the tuning is indeed an improvement before merging. Thanks.

**Comment by kfatehi** [comment]
New user here w/ a 2019 Impreza. My devkit arrives Monday. I am planning to test this PR.

**Comment by mchonan1996** [comment]
@rbiasini are there any plans to get rid of ParamsLearner with steer ratio? I've found that you get much better results when ParamsLearner is disabled, and steer ratio is set to 13.0:1 as per Impreza's spec. Is there scope for disabling PL for certain cars?

**Comment by afreepenguin** [comment]
> @rbiasini are there any plans to get rid of ParamsLearner with steer ratio? I've found that you get much better results when ParamsLearner is disabled, and steer ratio is set to 13.0:1 as per Impreza's spec. Is there scope for disabling PL for certain cars?

Does this PR have that steer ratio set to 13:0:1? I can't really tell. I have tested this PR for 150ish miles and it seems pretty good. Need to test against stock OP more. Have ou tricked stock OP with ParamsLearner disabled?

**Comment by mchonan1996** [comment]
@afreepenguin Nah. This pull request simply has the tuning. For more accurate steering though I've disabled the learner on my personal branch.

**Comment by kfatehi** [comment]
I've driven around 300 miles with this tuning, and probably 300 miles without. I can't really tell the difference, but also I am not sure what I'm looking for. I'm too busy being amazed by the device itself to be able to discriminate about the tuning.

Slightly off topic, but important to me and other newbies hoping to get involved: could someone point me to documentation or at least some kind of best-effort learning path to understand tunings as a concept within OP, so I may eventually be able to help test and feedback more effectively, and understand what you guys are talking about, speaking as a hobbyist w/ maybe only 5 hours / week to dedicate to going deeper w/ OP? Thanks

**Comment by mchonan1996** [comment]
@kfatehi Check pinned messages in #tuning channel in Discord. [Discord Link if you don't already have it](discord.comma.ai)

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
