### PR TITLE
new class QParams, used to gain access to the params in Qt

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by deanlee** [comment]
qParams will be initialized before default_path&persistent_path.put  default_path&persistent_path in ctor to make sure paths get initialized before it is used

**Comment by adeebshihadeh** [comment]
What's the point of this class?

**Comment by deanlee** [comment]
no need to convert between qstring and std::string every time, and vice versa.

**Comment by adeebshihadeh** [comment]
I don't think this is cleaner than the std::string and QString conversions. Willem opened #21229 to address the possibility of failing to create one of the Params instances.

**Pull request closed without merging**
