### PR TITLE
plotjuggler takes cabana shared links

### PR DESCRIPTION
**Pull request by hewers**
**Description** `./juggle.py "https://my.comma.ai/cabana/?..."`

**Verification** Plotjuggled all the things. Seems to only work with recent cabana shared links.

### CODE REVIEW

**Comment by pd0wm** [comment]
Why do you need a token from `auth_config`? In this case you can call `api_get` directly and skip the token part.

**Comment by qadmus** [comment]
@pd0wm , I'm unable to get it to work without a token:

```
    query = parse_qs(urlparse(route_name).query)
    logs = CommaApi().get(f'v1/route/{query["route"][0]}/log_urls?sig={query["sig"][0]}&exp={query["exp"][0]}')
  ```

```> ./juggle.py "https://my.comma.ai/cabana/?route=72597da3b82d1dc6%7C2020-08-29--20-04-10&exp=1659157547&sig=9Qoh1lpzDG5RezA9tTwa4cm0mQiR6f4DkeKWjvBtlbg%3D&max=6&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2F72597da3b82d1dc6%2F9922b76b6772c057e4dbcaca00715bdb_2020-08-29--20-04-10"
Traceback (most recent call last):
  File "./juggle.py", line 119, in <module>
    juggle_route(args.route_name, args.segment_number, args.segment_count, args.qlog, args.can, args.layout)
  File "./juggle.py", line 52, in juggle_route
    logs = api.get(f'v1/route/{query["route"][0]}/log_urls?sig={query["sig"][0]}&exp={query["exp"][0]}')
  File "/home/user/openpilot/tools/lib/api.py", line 27, in get
    return self.request('GET', endpoint, **kwargs)
  File "/home/user/openpilot/tools/lib/api.py", line 19, in request
    raise UnauthorizedError('Unauthorized. Authenticate with tools/lib/auth.py')
tools.lib.api.UnauthorizedError: Unauthorized. Authenticate with tools/lib/auth.py```

**Comment by pd0wm** [comment]
Try using `api_get`: https://github.com/commaai/openpilot/blob/master/common/api/__init__.py#L39

**Comment by qadmus** [comment]
Trying `api_get` in `juggle.py`: 
```
    query = parse_qs(urlparse(route_name).query)
    logs = api_get(f'v1/route/{query["route"][0]}/log_urls', sig=query['sig'][0], exp=query['exp'][0])
    print(logs)
```

and printing endpoint and params in `api/__init__.py`:

```
  print(endpoint)
  print(params)
```

Gives a 401 error code. I have so little idea about how to form an HTTP request.

```
v1/route/72597da3b82d1dc6|2020-08-29--20-04-10/log_urls
{'sig': '9Qoh1lpzDG5RezA9tTwa4cm0mQiR6f4DkeKWjvBtlbg=', 'exp': '1659157547'}
<Response [401]>
Loading b'{"error": 1, "status_code": 401, "description": "The server could not verify that you are authorized to access the URL requested'
Loading b". You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credenti"
Loading b'als required."}'
```

**Comment by qadmus** [comment]
@pd0wm , got `api_get()` working, but still require an auth token for the request. I assumed that JWT token is required for any request?

**Comment by pd0wm** [comment]
Cabana manages to show the route without logging in, so it should be possible!

**Comment by pd0wm** [comment]
Oh, you're right. It still expects a JWT, but it can be from any user

**Pull request merged**
