### PR TITLE
Add Taiwanese RAV4 fingerprint

### PR DESCRIPTION
**Pull request by protonchang**
Credit goes to @maxduan123

https://my.comma.ai/20b4d3621d22f87b/1570387424836/1570393068407

https://my.comma.ai/cabana/?route=20b4d3621d22f87b%7C2019-10-06--18-44-46&exp=1601981446&sig=SnY2iib0JjWnqlxONjitPJQqfIKEAxG7WNhHL86XAQI%3D&max=93&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F20b4d3621d22f87b%2Faab1a53e29d4c32bdcda41fc3440cc08_2019-10-06--18-44-46

### CODE REVIEW

**Comment by ErichMoraga** [comment]
I was literally about to submit this.  Next time, ping me on Discord so we don't duplicate efforts.

**Comment by protonchang** [comment]
I see, sorry about that.

**Comment by rbiasini** [comment]
@protonchang , it seems like the DSU was unplugged. I would need a stock drive to verify the fingerprint (giraffe switches to 1001). thanks!

**Comment by maxduan123** [comment]
> @protonchang , it seems like the DSU was unplugged. I would need a stock drive to verify the fingerprint (giraffe switches to 1001). thanks!

no DSU in rav4 2019, stock means stock Openpilot?

**Comment by rbiasini** [comment]
wait... this is a 2019 Rav4 hybrid with TSS2? If so, it seems that you added the fingerprint to the wrong spot, as RAV4H refers to pre-TSS2 cars.  Unfortunately, due to fingerprint incompatibilities, we don;t support the Rav4 TSS2 Hybrid yet.

Also, with stock I mean openpilot disabled (giraffe switches to 1001).

**Comment by ErichMoraga** [comment]
@rbiasini Reallly need "VINPrinting" ASAP, or some commentary on it with the Black Panda reveal.

**Comment by maxduan123** [comment]
> wait... this is a 2019 Rav4 hybrid with TSS2? If so, it seems that you added the fingerprint to the wrong spot, as RAV4H refers to pre-TSS2 cars. Unfortunately, due to fingerprint incompatibilities, we don;t support the Rav4 TSS2 Hybrid yet.
> 
> Also, with stock I mean openpilot disabled (giraffe switches to 1001).

but it worked on my rav4 hybrid with Tss2, cannot comprehend why it is incompatible ?
so for now it can be done via forks but cannot add this fingerprint into stock openpilot?

**Comment by protonchang** [comment]
> wait... this is a 2019 Rav4 hybrid with TSS2? If so, it seems that you added the fingerprint to the wrong spot, as RAV4H refers to pre-TSS2 cars. 
Well, I'm not aware of that 2019 RAV4 in Taiwan is using TSS2, that was my bad.

So, does that mean currently openpilot won't merge any TSS2 fingerprints into devel branch?

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
