### PR TITLE
Santa Fe 2019 Ultimate 2.0

### PR DESCRIPTION
**Pull request by emmertex**
FIngerprint and so on for said SantaFe
User is 'Nate' from Slack
Ported this car a fair while back.
Port is fine, but tuning is not.

### CODE REVIEW

**Comment by rbiasini** [comment]
same as https://github.com/commaai/openpilot/pull/502: do we really need a new car variant or we can simply extend the fingerprint options in the existing `SANTA_FE`?

**Comment by emmertex** [comment]
Can you test that tuning on your Santa Fe?
If it works for you, may as well extend fingerprint.
Your tuning on that particular vehicle results in wild oscillations and corner cutting, it's even more wrong.

**Comment by rbiasini** [comment]
Ok. I propose this common tuning:
```
ret.steerKiBP, ret.steerKpBP = [[9., 22.], [9., 22.]]
ret.steerKpV, ret.steerKiV = [[0.2, 0.35], [0.05, 0.09]]
```

**Comment by emmertex** [comment]
Well, low speed oscillations are the largest issue with your tuning for him, so that will be a much better starting point!
May as well go ahead with that.

But the long reply below....

I think the reason you can get away with the error gain being so high is both yours and the other santa_fe have the wrong steering ratio.  As such you are accounting for this error by having a more aggressive tuning.
Unless SantaFe is different, hyundai/kia don't have variable steering ratio, they do vary the level of torque amplification from driver input at different speeds and angles though, which results in a similar feel.
you don't notice the inflection point when turning at a standstill because its not there.

This doesn't mean this tuning does not work, it does!  But how its working is very questionable.
I can't tune these vehicles or do the tests needed as I don't have access to them, but I have been in the process of retuning a lot of other cars.
Every Hyundai/Kia has the same MDPS, but they do have different Racks, and Vehicle Dynamics.
Using the exact steering ratio with other cars, as derived from specifications from the manuacturer, the tuning between models appears to be identical.  
In fact with the new Lateral Control that gernby has in the PR, they are identical.
This means the only model I can't get tested, being the santaFe, unless it is unique, likely also has the wrong vehicle data to begin with, which results in the vastly different tuning.
The Sorento I have is practically the identical vehicle, yet the tuning is vastly different for what seems to be a very similar drive on the road.

**Comment by rbiasini** [comment]
@emmertex cool, if you are ok with it, let's just add the new santa fe fingerprint to the existing one and we can ship the new common tuning.

Re: variable steering ratio. You are right but the steering ratio does not significantly change between +-10 deg, which is where OP behaves, so a constant one is ok IMO. I also agree that the steering ratio we should consider is not the one advertised in the vehicle specs (which usually refers to end-to-end).

**Pull request closed without merging**
