### PR TITLE
map panel: show map on interactive timeout

### PR DESCRIPTION
**Pull request by sshane**
shows map if interaction times out in map settings

### CODE REVIEW

**Comment by sshane** [comment]
not sure if there's a standard way of signaling down to child widgets in QT, does this look good to you @incognitojam?

**Comment by incognitojam** [comment]
I feel like just subscribing to the signal in `map_panel.cc` would be better than passing it down

**Comment by sshane** [comment]
made `Device` a singleton. @deanlee is this how you would do this, or should we start putting this method inside the class (`Device::instance()`)

**Comment by deanlee** [comment]
Yes, I think it's better to singleton it. otherwise you often run into the problem of not being able to access the device class.  I've had many headaches over this:D

**Comment by deanlee** [comment]
Think we can remove the redundant `awake` from uistate now

**Comment by sshane** [comment]
done!

**Pull request merged**
