### PR TITLE
VW MQB: Add FW for 2023 Karoq

### PR DESCRIPTION
**Pull request by Saber422**
route name：9c3d97394a78e872|2023-12-12--14-39-47--6

### CODE REVIEW

**Comment by sshane** [comment]
@jyoung8607 this doesn't pass our fingerprint checker bot because a lot of the FW returned comes from Hyundai queries which aren't used in VW fingerprinting. Are you aware of this? Can we add similar queries to get them, or do you want to remove those ECUs?

image

**Comment by jyoung8607** [comment]
Can't say if it's universal, but I can say it's extremely common for engine and transmission firmware. I see it (and ignore it) all the time when adding fingerprints.

Since this PR came from @Saber422, who is an expert user, it's possible we're onroad and driving via `fingerprintSource: fixed` and therefore the UDS brand-query filtering logic may not have been run. I don't have permissions to this particular device to look.

**Comment by Saber422** [comment]
Sorry for late replying. I ask the owner to upload logs.
You can check new route now. 9c3d97394a78e872|2024-02-15--15-51-54--0
@jyoung8607 The owner add your id, you can also double check the car params to see if it's all right.

**Comment by sshane** [comment]
Looks like there's a lot of UDS communication going on with at least the engine not by us, throughout the first segment of that route. Is there an OBD debugging dongle plugged in?

**Comment by Saber422** [comment]
The owner used OBD device, Lufi XS 3rd, so I ask him unplug it and make two routes.
S__176095242

9c3d97394a78e872/2024-02-29--17-08-52/0
9c3d97394a78e872/2024-02-29--14-30-55/0

**Pull request merged**
