### PR TITLE
Fingerprint brazilian Corolla hybrid

### PR DESCRIPTION
**Pull request by AlexandreSato**

### CODE REVIEW

**Comment by AlexandreSato** [comment]
Brazilian Corolla Hybrid TSS2.0 Fingerprint

**Comment by AlexandreSato** [comment]
Brazilian Corolla Hybrid Fingerprint

**Comment by AlexandreSato** [comment]
Brazilian version of Corolla Hybrid 2020

**Comment by pd0wm** [comment]
What's your dongle id? Can you remove the comments?

**Comment by AlexandreSato** [comment]
﻿
﻿7d5fbee9d4476ca3  ,

I'm kind of wrapped up here in the service, I think I can only get the comment out in about 4 or 5 days, if you want to take it out, feel free.  Even to work fully in the Brazilian Corollas you need to find a way to identify in carstate.py that this Finger Print is of the Brazilian model and play LOW_SPEED_LOCKOUT = False, otherwise it won't work and I don't know how to do it: /


https://github.com/AlexandreSato/openpilot_VirtuallyChris/commit/ef42b0cb0e41d430a9d9dc7c94334ca891671ca3

Att
Alexandre Nobuharu Sato

Enviado do meu iPhone

Em 3 de mar. de 2021, à(s) 07:50, Willem Melching <notifications@github.com> escreveu:

﻿

What's your dongle id? Can you remove the comments?

**Comment by pd0wm** [comment]
Changing this PR to draft then. No point in merging the FW version if it doesn't work.

**Comment by AlexandreSato** [comment]
It would be one less thing for us Brazilians to have to modify to make our Corollas work:, (

Att
Alexandre Nobuharu Sato

Enviado do meu iPhone

> Em 3 de mar. de 2021, à(s) 08:14, Willem Melching <notifications@github.com> escreveu:
> 
> Changing this PR to draft then. No point in merging the FW version if it doesn't work.

**Comment by anotabien** [comment]
One thing to add that it happens to my Brazil made Corolla 2021 non-hybrid.
With original parameter, most of the time will get ¨CRUISE FAULT: Restart your car¨ (80/90% of the time) and problem will not be solve by restarting the car. When it starts with out the ¨CRUISE FAULT: Restart your car¨, OP will work fine with Stop&Go and can be engage in any speed.
With ¨LOW_SPEED_LOCKOUT = False¨, ¨CRUISE FAULT: Restart your car¨ won´t came out, but looses Stop&Go feature, only can be engage over 22km/h.

**Comment by adeebshihadeh** [comment]
Closing until #20703 is fixed.

**Pull request closed without merging**
