### PR TITLE
ESP f/w F152642521 for CAR.RAV4H_TSS2

### PR DESCRIPTION
**Pull request by ErichMoraga**
DongleID 08ae2ec6875e165c

### CODE REVIEW

**Comment by pd0wm** [comment]
I see three mismatches. 
```
(0x700, None) - b'\x018966342X6000\x00\x00\x00\x00'
(0x7b0, None) - b'F152642521\x00\x00\x00\x00\x00\x00'
(0x7a1, None) - b'8965B42181\x00\x00\x00\x00\x00\x00'
```

**Comment by ErichMoraga** [comment]
I only see the 1 missing firmware for ESP, which is what I added in my original PR.  That was based on this FPv2 output...
```    carFw = [
      ( ecu = engine,
        fwVersion = "\x018966342X6000\x00\x00\x00\x00",
        address = 1792,
        subAddress = 0 ),
      ( ecu = esp,
        fwVersion = "F152642521\x00\x00\x00\x00\x00\x00",
        address = 1968,
        subAddress = 0 ),
      ( ecu = eps,
        fwVersion = "8965B42181\x00\x00\x00\x00\x00\x00",
        address = 1953,
        subAddress = 0 ),
      ( ecu = fwdRadar,
        fwVersion = "\x018821F3301400\x00\x00\x00\x00",
        address = 1872,
        subAddress = 15 ),
      ( ecu = fwdCamera,
        fwVersion = "\x028646F4203500\x00\x00\x00\x008646G2601200\x00\x00\x00\x00",
        address = 1872,
        subAddress = 109 ) ],

**Comment by directedbit** [comment]
For reference, this change worked  for me (on the dongle mentioned in the commit). The car was recognized and open pilot worked.

**Comment by geohot** [comment]
Hmm, I don't exactly understand the mismatches, but I don't see how this hurts to merge.

**Pull request merged**
