### PR TITLE
Update values.py

### PR DESCRIPTION
**Pull request by chanhojung**
Add finger for CAR.GRANDEUR_IG, CAR.GRANDEUR_IG, GRANDEUR_IG_FL, CAR.GRANDEUR_IG_FL

### CODE REVIEW

**Comment by ErichMoraga** [comment]
You should really be submitting FPv2 whenever possible, instead of FPv1.

**Comment by pd0wm** [comment]
Can you fix the syntax errors?

Do you also have routes for these 4 cars?

**Comment by adeebshihadeh** [comment]
Converting to a draft, this is also missing any configuration in interface.py

**Comment by adeebshihadeh** [comment]
Closing due to inactivity

**Pull request closed without merging**
