### PR TITLE
QuectelGPS: add supl server

### PR DESCRIPTION
**Pull request by gast04**
improve gps time to first fix by presetting a supl server

### CODE REVIEW

**Review by adeebshihadeh — APPROVED** [review]
LGTM if you tested this well.

**Comment by gast04** [comment]
the only thing noticeable is, when used without sim card it sometimes takes a while until it gets a fix, ~2-4min

**Comment by gregjhogan** [comment]
what is the slowest you have observed the time to first fix (from cold start) when you do have internet via prime sim with this change?

**Comment by gast04** [comment]
a fix after a full (forced) reset with `QGPSDEL`, will still take about 5-10min, it strongly depends on the location, a device with assistance data in warm start will deliver measurements < 10s

**Comment by gast04** [comment]
quickly tested in the stress test rack, and always got a fix in max 1min

**Pull request merged**
