### PR TITLE
Subaru: Add FW for 2020 Subaru Forester

### PR DESCRIPTION
**Pull request by jyoung8607**
**Car**

2019 Subaru Forester, thanks to Puttputt7!

**Route**

`7120a7c40c69302b/2024-03-06--04-49-59`

### CODE REVIEW

**Comment by sshane** [comment]
Can you check with the bot?

**Comment by jnewb1** [comment]
only 2 segments uploaded


| Dongle, platform, VIN                                                                                                           | Name from VIN 🆚 CarInfo   | Segments             | Bad seg tags   | Good seg tags       |
|:--------------------------------------------------------------------------------------------------------------------------------|:---------------------------|:---------------------|:---------------|:--------------------|
| [7120a7c40c69302b](https://useradmin.comma.ai/?onebox=7120a7c40c69302b)<br><sub>SUBARU FORESTER 2019<br>JF2SKADC9........</sub> | None 🆚<br>None            | 1 routes, 2 segments |                | - all lat active: 0 |

Dongles to re-run category: `7120a7c40c69302b`

**Comment by sshane** [comment]
@jyoung8607 can you get the user to drive a bit more? The lateral accel factor is 3.0 instead of our offline 2.0

**Comment by jyoung8607** [comment]
image

**Pull request merged**
