### PR TITLE
edit: Change Bolt required hardware

### PR DESCRIPTION
**Pull request by notAreYouScared**
Comma power & RJ45 cable's are not needed as the power is provided from the camera connector and harness box.

### CODE REVIEW

**Comment by sshane** [comment]
You need to edit the car docs directly, not the generated file.

**Comment by sshane** [comment]
@adeebshihadeh I don't think there's any reason to keep shipping these parts, fine to remove?

**Comment by adeebshihadeh** [comment]
If we're not sure, let's keep it for now.

**Comment by sshane** [comment]
Sounds good.

**Pull request closed without merging**
