### PR TITLE
Std cargo refactor

### PR DESCRIPTION
**Pull request by dek3rr**
remove mass unit ambiguities

### CODE REVIEW

**Comment by rbiasini** [comment]
Nice. What about moving `STD_CARGO_KG` to `selfdrive/car/__init__.py`?

**Comment by dekerr** [comment]
what do you think about moving hardcoded civic parameters into a class and adding functions for scaling tirestiffness and rotational inertia?

**Comment by rbiasini** [comment]
yep, that would make sense, as long as such class has no dependencies, goes in __init__ and it's super simple.

Thanks for the STD_CARGO refactor

**Comment by rbiasini** [comment]
merged internally due to conflicts. Will be in next release!

**Pull request closed without merging**
