### PR TITLE
Hongqi HS5

### PR DESCRIPTION
**Pull request by jyoung8607**
Today we bring to you the glorious [Hongqi HS5](http://www.faw.com/fawen/xwzt/xwbd/3292599/index.html) from the FAW Car Company in China. Minimal port, work in progress.

TODO:

- [x] commaai/cereal#261
- [ ] commaai/opendbc#580
- [ ] commaai/panda#882
- [ ] verify ABS wheel speed signal scaling, current value is a best estimate
- [ ] need to identify more signals
  - [x] turn signals
  - [ ] BSM (not sure if available on the test vehicle)
  - [ ] cruise control buttons
  - [ ] ACC speed setpoint
  - [ ] yaw rate, if available
  - [x] EPS temp/perm fault states
  - [ ] parking brake
  - [ ] gearshift lever position
  - [x] door open states
  - [ ] driver's seatbelt
  - [ ] stability control enabled
- [ ] cancel spam on disengage
- [ ] send LKAS HUD messages to instrument cluster
- [x] UDS fingerprinting (this should be easy based on tests from last year)
- [ ] harness / wiring diagram docs (not really part of this PR, but needs to be done)
- [ ] replay route

### CODE REVIEW

**Comment by GregorKikelj** [comment]
This should probably get closed: https://github.com/commaai/openpilot/pull/23630

**Comment by AdamSBlack** [comment]
glorious?

**Comment by jyoung8607** [comment]
Working FPv2 based on the part number consistently returned from VEHICLE_MANUFACTURER_SPARE_PART_NUMBER. VIN query already worked fine. Have confirmed the engine, transmission, EPS, and fwdCamera. There is no fwdRadar; all FCW/AEB and adaptive cruise duties are handled by the fwdCamera on this vehicle.

**Full scan of the vehicle with engine running:** https://termbin.com/2n59

**Test route:** `7d3307665954222a|2022-10-17--22-17-18`

**Output:**
```
               'carFingerprint': 'HONGQI HS5 1ST GEN',
               'carFw': [{'address': 2016,
                          'brand': 'hongqi',
                          'bus': 1,
                          'ecu': 'engine',
                          'fwVersion': b'3601015-DD21    ',
                          'request': [b'"\xf1\x87'],
                          'responseAddress': 2024,
                          'subAddress': 0},
                         {'address': 2017,
                          'brand': 'hongqi',
                          'bus': 1,
                          'ecu': 'transmission',
                          'fwVersion': b'3611015-DD01\x00\x00\x00\x00',
                          'request': [b'"\xf1\x87'],
                          'responseAddress': 2025,
                          'subAddress': 0},
                         {'address': 1826,
                          'brand': 'hongqi',
                          'bus': 1,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'3616215-DD03-B  ',
                          'request': [b'"\xf1\x87'],
                          'responseAddress': 1834,
                          'subAddress': 0},
                         {'address': 1954,
                          'brand': 'hongqi',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'3418310-DD01\x00\x00\x00\x00',
                          'request': [b'"\xf1\x87'],
                          'responseAddress': 1962,
                          'subAddress': 0}],
               'carName': 'hongqi',
               'carVin': 'LFB1E6079N1Y00406',
```

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
