### PR TITLE
GM: LKA dashboard icon support

### PR DESCRIPTION
**Pull request by vntarasov**
Shows LKA icon on the dashboard when Openpilot is actively steering:
- No icon when steering unavailable (under 7 MPH on Volt) or EPS is not accepting commands (e.g. if bugs are introduced in future).
- Green icon when EPS acknowledges LKA is active
- Yellow icon when LKA command is at 90% of the torque limit

Also takes care of "Service Front Camera" message, with LKA status serving as a keep-alive message for the camera.

pr lka

### CODE REVIEW

**Review by pd0wm — COMMENTED** [review]
Looks good!

When tested by a few people I will merge it.

**Comment by CryptoKylan** [comment]
Tested. Works well for 2018 gm acadia. No service camera msg

**Comment by kishkaru** [comment]
Tested on 2018 Volt: 1) No service front cam message, 2) Green LKA icon active when OP engaged above 7mph, 3) LKA icon slowly blink orange when steering limit exceeded.

However:
1) Once I got a "Take control immediately - SOLUTION PLANNING ERROR" message, along with OP disengaged while going around a sharp corner. 
2) LKA light doesn't blink orange when changing lanes, even though OP shows the "steering limit exceeded" message.
3) Occasionally OP also doesn't chime when disengaging when the driver applies throttle.

**Comment by Aryeh95** [comment]
Drove about 4 hours with this today and it seems to work well.
I like the orange icon as a warning for torque limit (I get it also when switching lanes, so hopefully that's fixed soon)

**Comment by MiDe84** [comment]
Currently using this PR. It’s working great! Got rid of the annoying service camera message and being able to have the lkas light let me know what’s going on has been very helpful.

**Comment by tylergets** [comment]
Working on 2017 Malibu

**Comment by rbiasini** [comment]
seems good to go. @kishkaru, worth digging more into 2) and 3), while 1) should have nothing to do with this change.

**Pull request merged**
