### PR TITLE
Kia: add missing Korean EV6 fwdCamera FW version 1.05

### PR DESCRIPTION
**Pull request by jazzbearz**
carFw = [
      ( ecu = abs,
        fwVersion = "\xf1\000CV  IEB \006 100!\0051 58520-CV000",
        address = 2001,
        subAddress = 0,
        responseAddress = 2009,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 1,
        logging = false ),
      ( ecu = eps,
        fwVersion = "\xf1\000CV1 MDPS R 1.00 1.02 57700-CV000 1629",
        address = 2004,
        subAddress = 0,
        responseAddress = 2012,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 1,
        logging = false ),
      ( ecu = fwdCamera,
        fwVersion = "\xf1\000CV1 MFC  AT KOR LHD 1.00 1.05 99210-CV000 211027",
        address = 1988,
        subAddress = 0,
        responseAddress = 1996,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 1,
        logging = false ),
      ( ecu = abs,
        fwVersion = "\xf1\x8758520CV000\xf1\000CV  IEB \006 100!\0051 58520-CV000",
        address = 2001,
        subAddress = 0,
        responseAddress = 2009,
        request = ["\"\xf1\x87\xf1\x81\xf1\000"],
        brand = "hyundai",
        bus = 1,
        logging = false ),
      ( ecu = fwdRadar,
        fwVersion = "\xf1\000CV1_ RDR -----      1.00 1.01 99110-CV000         ",
        address = 2000,
        subAddress = 0,
        responseAddress = 2008,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 4,
        logging = false ),
      ( ecu = adas,
        fwVersion = "\xf1\000CV1 ADRV 1.00 1.03 210715",
        address = 1840,
        subAddress = 0,
        responseAddress = 1848,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 5,
        logging = true ),
      ( ecu = cornerRadar,
        fwVersion = "\xf1\000CV  BCW RR 1.00 , 1.01 (ur !\002&\0057",
        address = 1975,
        subAddress = 0,
        responseAddress = 1983,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 5,
        logging = true ),
      ( ecu = fwdCamera,
        fwVersion = "\xf1\000CV1 MFC  AT KOR LHD 1.00 1.05 99210-CV000 211027",
        address = 1988,
        subAddress = 0,
        responseAddress = 1996,
        request = ["\"\xf1\000"],
        brand = "hyundai",
        bus = 5,
        logging = false ) ],

### CODE REVIEW

**Comment by incognitojam** [comment]
Please share your dongle ID

**Comment by jazzbearz** [comment]
Dongleid: 98b95fc30d5c3e27

**Comment by sshane** [comment]
@jazzbearz can you tell me which harness you used? Was it Hyundai P or Hyundai L? Thanks!

**Comment by jazzbearz** [comment]
@sshane it's Hyundai P.  However, I was trying to get the comma three working when the official harness came out, so, I made the harness. The problem is... it doesn't recognize the car turning off. I might have to purchase the official harness after few tries.

**Pull request merged**
