### PR TITLE
Hyundai: Car Port for Tucson Hybrid 2022

### PR DESCRIPTION
**Pull request by sunnyhaibin**
**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: `36e10531feea61a4|2022-07-25--13-37-42`
- [x] harness type: [Hyundai N](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)

**Physical setup**
- Top port behind comma three
  - comma Power <-> First Harness Box <-> comma three USB C/Right-Angle C <-> comma three
- Bottom port behind comma three
  - Camera Harness <-> Second Harness Box <-> USB C/C 3.1 <-> Red Panda <-> USB A/A <-> USB A to C **OTG Adapter** <-> comma three

**Requires**
- https://github.com/commaai/panda/pull/999
- https://github.com/commaai/opendbc/pull/673

### CODE REVIEW

**Comment by sunnyhaibin** [comment]
@adeebshihadeh continuing our conversation from Discord, here are the route IDs with the remaining problems of this port:
- Panda faulted with the current panda safety
  - `36e10531feea61a4|2022-07-24--22-46-58`
- `CRUISE_BUTTONS|CRUISE_BUTTONS` bit `1` seems to send, but car does not resume; set speed went from 40 MPH to 64 MPH when bit `1` was sent
  - `36e10531feea61a4|2022-07-25--13-37-42`
image

**Comment by sunnyhaibin** [comment]
Here's the FW query from the script, it's very inconsistent and had to ran multiple times with car restarts, etc.:
```
Found FW versions
{
  Brand: hyundai, bus: 1 - (Ecu.eps, 0x7d4, None): [b'\xf1\x00NX4 MDPS C 1.00 1.01 56300-P0100 2228']
  Brand: hyundai, bus: 1 - (Ecu.transmission, 0x7e1, None): [b'\xf1\x00PSBG2441  G19_Rev\x00\x00\x00SNX4T16XXHS01NS2lS\xdfa']
  Brand: hyundai, bus: 1 - (Ecu.engine, 0x7e0, None): [b'\xf1\x87391312MND0']
}
```
```
Found FW versions
{
  Brand: hyundai, bus: 1 - (Ecu.fwdCamera, 0x7c4, None): [b'\xf1\x00NX4 FR_CMR AT USA LHD 1.00 1.00 99211-N9240 14Q']
  Brand: hyundai, bus: 1 - (Ecu.transmission, 0x7e1, None): [b'\xf1\x00PSBG2441  G19_Rev\x00\x00\x00SNX4T16XXHS01NS2lS\xdfa']
  Brand: hyundai, bus: 1 - (Ecu.engine, 0x7e0, None): [b'\xf1\x87391312MND0']
}
```

**Comment by sunnyhaibin** [comment]
The car still did not resume from stop after the last commit: `36e10531feea61a4|2022-07-26--20-22-43`

**Comment by adeebshihadeh** [comment]
Can you rebase this on master?

**Comment by sunnyhaibin** [comment]
> Can you rebase this on master?

Rebased and added disengage with 0x1a0 in openpilot and panda safety.

**Comment by sunnyhaibin** [comment]
The LFA and HDA icons on the car's dashboard shows as follows:

**openpilot disengaged:**
- LFA: grey
- HDA: off

**openpilot engaged:**
- LFA: green
- HDA: green

image

**Comment by sshane** [comment]
@sunnyhaibin do you know why we opted to send SCC_CONTROL here to cancel instead of CRUISE_BUTTONS_ALT?

**Comment by sunnyhaibin** [comment]
> @sunnyhaibin do you know why we opted to send SCC_CONTROL here to cancel instead of CRUISE_BUTTONS_ALT to both cancel and resume? I know you said CRUISE_BUTTONS didn't work, but did you try the ALT message?

At the time of testing this port, `CRUISE_BUTTONS_ALT` did not work (`CRUISE_BUTTONS` does not exist for this car). I've tried to send on different busses and different frequencies/intervals, all attempts failed with `CRUISE_BUTTONS_ALT`.

**Pull request merged**
