### PR TITLE
Subaru: use latActive for steer request bit

### PR DESCRIPTION
**Pull request by sshane**
Old logic made the bit rapidly cycle on/off when desired torque is near 0

image

### CODE REVIEW

**Comment by sshane** [comment]
@martinl want to check one your stock routes to make sure the stock system keeps the bit high when torque is zero but it's still steering?

**Comment by martinl** [comment]
yes, I will test

**Comment by sshane** [comment]
Expected on gen 2 Outback:
image

**Comment by sshane** [comment]
Looks good!

image

image

image

image

image

**Comment by sshane** [comment]
Expected diff 
image

**Pull request merged**
