### PR TITLE
metadrive: fix wasd steer signs

### PR DESCRIPTION
**Pull request by fredyshox**
It appears that steer values in AD of WASD control have swapped signs.

### CODE REVIEW

**Comment by jnewb1** [comment]
did you check if this is metadrive-only or also in carla? also, the user_torque is correct for doing lane changes, so i think we will have to flip it in two places

**Comment by fredyshox** [comment]
will check in carla

**Comment by adeebshihadeh** [comment]
Let's just delete CARLA if MetaDrive is working well. It's too janky, even outside the openpilot implementation.

**Comment by fredyshox** [comment]
right now I'm getting commIssue on both metadrive and carla when trying to engage. wasd doesn't seem to work with carla @jnewb1 can you check it out?

**Comment by jnewb1** [comment]
we killed carla so we dont need to worry about that. fixed the user torque so lane changes work

**Comment by fredyshox** [comment]
confirming lane changes work now!

**Comment by jnewb1** [comment]
ill look at fixing the keyboard control too

**Pull request merged**
