### PR TITLE
Honda: add FW for Civic Sport 2023

### PR DESCRIPTION
**Pull request by Madnevil**

### CODE REVIEW

**Review by thegauravgiri — APPROVED** [review]
Looks good to me

**Comment by vanillagorillaa** [comment]
Please provide the dongleID of the device this firmware version was gathered from

**Comment by Madnevil** [comment]
Here you go:
9e0c91a4b8171233

**Comment by sshane** [comment]
Removed the FW from the radar, that seemed to be from:

```python
    # The only other ECU on PT bus accessible by camera on radarless Civic
    (Ecu.unknown, 0x18DAB3F1, None),
```

**Pull request merged**
