### PR TITLE
add travis badges for build status

### PR DESCRIPTION
**Pull request by joostaafjes**
Feature
This pull requests adds add travis badges for build status

Description
Add markdown code for travis badge of devel and release2 branch. Unfortunately the branch names have to be static. Also adding the (release) version would be a nice feature, but this can only be static text so needs to be updated manually when updating the RELEASES.MD

### CODE REVIEW

**Comment by energee** [comment]
There are other changes in this PR

**Comment by ShaneSmiskol** [comment]
trying to sneak in ALC i see 😏

**Comment by joostaafjes** [comment]
sorry, removed it 🙈

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
