### PR TITLE
adaptive cruise can no longer be bypassed on toyota

### LINKED ISSUE #1085: ACC can be bypassed on Toyota by holding down cruise on/off button
**Describe the bug**
ACC can by bypassed on Toyota. Openpilot allows engagement when ACC is disabled. This bug was already fixed on Honda https://github.com/commaai/openpilot/pull/770 

**How to reproduce or log data**
Press and hold down the cruise on/off button. ACC will be disabled and the car will switch to non-adaptive cruise control. Press set to engage. Openpilot will control steering, but ACC will not function.

**Expected behavior**
Openpilot should not be allowed to be engaged without ACC.

**Device/Version information:**
 - Device: EON Gold
 - Version: 0.7.2
 - Car make/model: 2018 Toyota Prius Prime

**Additional context**
This loophole has been tested on the three major types of Toyota: DSU connected and disconnected, Nodsu, and TSS 2.0

I suspect that this signal could be used to detect when non-adaptive cruise control is enabled:
image

I believe CRUISE_CONTROL_STATE 1.0 is non-adaptive cruise control. This could be used to detect that state.

I have demonstrated using the loophole in this drive https://my.comma.ai/cabana/?route=b29e3bc918751697%7C2020-02-12--12-04-27&exp=1613076855&sig=Z3uBeA6LE4ovlWgKaSEomaR6j8KdcUViZ8176dMW6Jk%3D&max=13&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fb29e3bc918751697%2F1fadd736273c29c679b40bab0ff87058_2020-02-12--12-04-27

### PR DESCRIPTION
**Pull request by cydia2020**
**Description**
This PR aims to fix #1085
**Verification**
Went on a drive, held down the cruise button to enter non-adaptive cruise mode on my Prius 2018. openpilot as expected will not enable after this fix is applied.
**Route**
Route: 399b1cca765e80b4|2020-12-07--01-11-46

### CODE REVIEW

**Comment by cydia2020** [comment]
please see 399b1cca765e80b4|2020-12-07--00-25-27 for how I got these values. Please note how SET_SPEED in PCM_CRUISE_2 and CRUISE_STATE in PCM_CRUISE are related.

**Comment by pd0wm** [comment]
What are the signals values for click/down when ACC is engaged?

**Comment by cydia2020** [comment]
click up when ACC engaged (engaging as well) = 9
image
click down when ACC engaged = 10
image

**Comment by cydia2020** [comment]
Hello.

Can we get this merged? I've been using it since opening this PR and no problems have emerged.

Cheers

**Comment by pd0wm** [comment]
Also updating the DBC file here: https://github.com/commaai/opendbc/pulls

We're still missing a few values. Are there also values for adaptive hold up and hold down? 11 & 12?

**Comment by cydia2020** [comment]
I think there are values for hold up and down since with the stock system we can have 5km/h increments by holding down the buttons, I will have a look tomorrow.

**Comment by cydia2020** [comment]
OK seems like there isn't a signal for hold up/down when acc is engaged, at least not with openpilot. I will disable OP and do another drive
image

**Comment by cydia2020** [comment]
OK nah, there is no hold up / down when ACC is ON. I've went on a drive with OP disabled.

As seen from the screenshot below, when adaptive cruise is engaged, cruise_state doesn't change despite set_speed has started to increase by 5km/h.

image

**Comment by pd0wm** [comment]
Ok, good to know. I'll merge that opendbc PR then

**Pull request merged**
