### PR TITLE
nextra docs

### PR DESCRIPTION
**Pull request by tecandrew**
Screenshot 2024-07-08 at 10 03 02 PM

https://openpilot-docs.netlify.app/

**Description**

Use [Nextra](https://nextra.site/) for docs site. Can likely be built alongside the `mkdocs` build?

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
These docs look and feel really great, but I'm concerned about introducing a bunch of complexity here just for some theming. This is a new language, build system, etc. 

Ultimately, we want to keep the build system and theme pretty light. Can we port most of this look and feel to mkdocs or something else simple?

**Comment by tecandrew** [comment]
@adeebshihadeh I agree it looks fairly complex. no worries on not accepting the PR 😄 

the current PR about as light as I could get it without introducing custom web development components (too complex even for me, a non-web developer). the major differences from the current docs tool set are

- python `pip` -> `bun` (faster than npm, yarn, etc...)
- mkdocs `/site/` build output -> NextJS build `.next/standalone/` output
- `index.md`, etc... -> `_meta.json` files

all other aspects are basically Nextra-specific configurations
- theme.config.jsx <-> mkdocs.yml
- `pages/` <-> `docs/` directory

**Comment by adeebshihadeh** [comment]
Any way we can make this work with JS disabled? I'd consider it if we could.

Alternatively, we can try to make an mkdocs theme that looks like this.

**Comment by tecandrew** [comment]
without some custom NextJS work, seems like this isn't easily doable using this framework

responded [in the discord chat](https://discord.com/channels/469524606043160576/1254506387841482812) about this

**Comment by tecandrew** [comment]
now developing in https://github.com/commaai/openpilot/pull/33174

**Pull request closed without merging**
