### PR TITLE
Updated values.py for honda civic 

### PR DESCRIPTION
**Pull request by DreZee669**
**Description** [Dashcam Mode: Car Unrecognized]

**Verification** [Added new ecu fw versions and now able to engage openpilot]
VAlues from my car's recorded drive:
ecu = programmedFuelInjection = 416944369 = 18da10f1 - 37805-5AG-Q710\x00\x00
ecu = transmission = 416947953 = 18da1ef1 - 28101-5CG-A320\x00\x00
ecu = fwdRadar = 416985329 = 18daB0F1 = 36161-TED-Q320\x00\x00
ecu = vsa = 416950513 = 18da28F1 = 57114-TEA-Q220\x00\x00
ecu = eps = 416952561 = 18da30F1 = 39990-TEA-T020\x00\x00
ecu = srs = 416961521 = 18da53F1 = 77959-TEA-Q820\x00\x00
ecu = combinationMeter = 416964849 = 18da60F1 = 78109-TED-Q510\x00\x00
ecu = gateway = 417001457 = 18daeff1 = 38897-TBA-A020\x00\x00

### CODE REVIEW

**Comment by pd0wm** [comment]
What is your dongle id? I'd like to quickly verify the values.

**Comment by DreZee669** [comment]
Hi Willem,
I’m just hoping not to have to redo the fingerprinting to make it work every time there’s an update, or even an update check.

https://my.comma.ai/useradmin/?onebox=2a45f5d64e24ea1f%7C2020-12-12--02-12-55--0

Dongle id: 2a45f5d64e24ea1f

    carFw = [
      ( ecu = programmedFuelInjection,
        fwVersion = "37805-5AG-Q710\x00\x00",
        address = 416944369,
        subAddress = 0 ),
      ( ecu = transmission,
        fwVersion = "28101-5CG-A320\x00\x00",
        address = 416947953,
        subAddress = 0 ),
      ( ecu = eps,
        fwVersion = "39990-TEA-T020\x00\x00",
        address = 416952561,
        subAddress = 0 ),
      ( ecu = fwdRadar,
        fwVersion = "36161-TED-Q320\x00\x00",
        address = 416985329,
        subAddress = 0 ),
      ( ecu = gateway,
        fwVersion = "38897-TBA-A020\x00\x00",
        address = 417001457,
        subAddress = 0 ),
      ( ecu = vsa,
        fwVersion = "57114-TEA-Q220\x00\x00",
        address = 416950513,
        subAddress = 0 ),
      ( ecu = srs,
        fwVersion = "77959-TEA-Q820\x00\x00",
        address = 416961521,
        subAddress = 0 ),
      ( ecu = combinationMeter,
        fwVersion = "78109-TED-Q510\x00\x00",
        address = 416964849,
        subAddress = 0 ) ],

Cheers,

Andre
Discord:UltraNub

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pd0wm** [comment]
Merged the PR. Will be shipped with v0.8.1, or you can switch to the nightly build on the `master-ci` branch

**Comment by DreZee669** [comment]
Awesome!
Not sure how to do that so I guess I'll just wait for 8.1?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
