### PR TITLE
replay: add download progress bar

### PR DESCRIPTION
**Pull request by deanlee**
<pre>
Downloading [====>                                         ]  6% 71.53 MB
</pre>

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can we implement the rest of the terminal UI I mentioned [here](https://github.com/commaai/openpilot/pull/23289#issuecomment-1000585908)? Perhaps it would be easier if we also introduced a new library like ncurses, no reason to do the terminal UI stuff from scratch.

**Comment by deanlee** [comment]
Do we need to use replay in an environment without qt?  If not, I think it may be better to implement it with qt instead of importing a new library, installing it on all devices, and writing bunch of code to implement a console ui.
we can reuse qt controls (such as timeline, progressbar...)  between replay and qt/ui  to save a lot of code. @adeebshihadeh what do you think?

**Comment by adeebshihadeh** [comment]
Hmm, I like the idea of the terminal UI right now. Also, I’m thinking the replay UI is only for controls, since we use the normal UI for the video. @pd0wm what do you think, terminal UI or GUI?

**Comment by adeebshihadeh** [comment]
I thought about this a bit more, and I'm really open to both. I still slightly prefer a terminal UI, mostly to avoid a second window, but a GUI would be super easy to do with Qt.

**Comment by pd0wm** [comment]
I like a terminal UI since you can use it on a device over SSH, but don't think it's worth it over a Qt ui if it adds more than ~100 lines.

 @adeebshihadeh do we have ncurses on NEOS/AGNOS?

**Comment by adeebshihadeh** [comment]
> I like a terminal UI since you can use it on a device over SSH, but don't think it's worth it over a Qt ui if it adds more than ~100 lines.

I'm willing to spend a few more lines (500?) if everything's nicely contained in its own file and doesn't really need to touch replay.

> @adeebshihadeh do we have ncurses on NEOS/AGNOS?

Yes, both have ncurses.

**Pull request closed without merging**
