### PR TITLE
Qt: update ui in a separate thread

### PR DESCRIPTION
**Pull request by deanlee**
based on QT example: threadedqopenglwidget https://code.woboq.org/qt5/qtbase/examples/opengl/threadedqopenglwidget/
related document: https://doc.qt.io/qt-5/qopenglwidget.html#threading
QOpenGLWidget source code: https://code.woboq.org/qt5/qtbase/src/widgets/kernel/qopenglwidget.cpp.html
```

glwindow thread:   | swap |           | swap |             | swap |
UIUpdate thread:            | update |         |  update |  
```

### CODE REVIEW

**Comment by deanlee** [comment]
performance looks good, "grab + return context + invoke update" only takes about 5~6ms

**Comment by adeebshihadeh** [comment]
How's the CPU usage? Currently, it's around 15% onroad.

**Comment by deanlee** [comment]
Reduce cpu usage by 3~4% and do not block the UI main thread. I think it's worth continuing to optimize this PR

**Comment by adeebshihadeh** [comment]
Can we split out the class to wrap our current event loop? It should have similar behavior where we block on visionipc with a timeout and update sockets, then it should emit a signal with an update. Then this PR will be for scheduling the GL stuff once the other PR is merged.

**Comment by deanlee** [comment]
@adeebshihadeh  how about this one?

**Pull request closed without merging**
