### PR TITLE
Laikad: cache ephem status

### LINKED ISSUE #29710: CI: Fix slow unittests
Here's the shortlist for slow unittests, this list is about 10 minutes of the 15-18 total

- [x] Loggerd
- [ ] Manuvers - improved but following_distance is still pretty slow
- [ ] Laika - improved but still not great

```
42.32s call     selfdrive/controls/tests/test_following_distance.py::TestFollowingDistance::test_following_distance
34.05s call     selfdrive/locationd/test/test_locationd.py::TestLocationdProc::test_params_gps
30.40s call     selfdrive/car/tests/test_fw_fingerprint.py::TestFwFingerprintTiming::test_fw_query_timing
29.99s call     system/ubloxd/tests/test_ublox_processing.py::TestUbloxProcessing::test_ublox_gps_cutover
28.35s call     selfdrive/locationd/test/test_laikad.py::TestLaikad::test_laika_online
27.37s call     selfdrive/locationd/test/test_laikad.py::TestLaikad::test_laika_online_nav_only
26.18s call     selfdrive/locationd/test/test_laikad.py::TestLaikad::test_get_navs_in_process
13.21s call     system/ubloxd/tests/test_ublox_processing.py::TestUbloxProcessing::test_get_fix
```

once we fix these, we should enforce a default timeout of 10 seconds in pytest

### PR DESCRIPTION
**Pull request by jnewb1**
took about 1/3 of the time of the laika tests making these ephem status messages

before:
image

after
image

TODO:
- ~~proper hash, right now it just uses the class instance as the hash, so if we change a value in the underlying class it won't recreate the cache~~

### CODE REVIEW

**Comment by haraschax** [comment]
Is this just slow because it's slow to make capnp messages?

**Comment by jnewb1** [comment]
yep I think so, and it has to build them 5000 times for the tests. I removed the laika tests until we actually use it, but we should find a solution for this before re-adding the tests

**Comment by adeebshihadeh** [comment]
Still relevant or can we close?

**Comment by jnewb1** [comment]
will close until we reenable laika tests

**Pull request closed without merging**
