### PR TITLE
adding --local-partial-types mypy opt

### PR DESCRIPTION
**Pull request by LoganxDev**
Added in '--local-partial-types' option for mypy

Fixed up the errors it reported.

### CODE REVIEW

**Comment by LoganxDev** [comment]
starter commit for #29458

**Comment by adeebshihadeh** [comment]
Not a fan of these particular annotation additions for tools/ stuff, but merging anyway for the extra coverage.

**Comment by LoganxDev** [comment]
Would you prefer I exclude these dirs?

**Comment by LoganxDev** [comment]
I'm a bit confused on what #29458 is asking for then. Isn't mypy all about typing annotations? I was planning on opening more prs split up by a submodule or a few at a time with more flags.

**Pull request merged**
