### PR TITLE
System: use paths for download folders too

### PR DESCRIPTION
**Pull request by jnewb1**

### CODE REVIEW

**Comment by deanlee** [comment]
@jnewb1 this pr disabled the caching capability of replay & cabana.

**Comment by jnewb1** [comment]
> @jnewb1 this pr disabled the caching capability of replay & cabana.

hmm, do you know why? if openpilot_prefix isn't set it should be the same folder (/tmp/comma_download_cache/)

**Comment by deanlee** [comment]
I see.. cabana set the openpilot_prefix on startup to support multiple instances.Looks like replay should use its own download cache path now.

**Comment by jnewb1** [comment]
What part conflicts between two cabana instances? Is using the prefix required?

**Comment by deanlee** [comment]
the msgq

**Pull request merged**
