### PR TITLE
Added FW for VW Passat B8 2018

### PR DESCRIPTION
**Pull request by lachezartodorov**

### CODE REVIEW

**Comment by incognitojam** [comment]
Can you please share your dongle/route ID?

**Comment by sshane** [comment]
Any updates @lachezartodorov?

**Comment by lachezartodorov** [comment]
Sorry for the delay.
Dongle ID: 01bd35c7d64d3601

The device is not in my car and they guy was on a long trip, so there are no recent routes that I can see in `connect`.
If you need it I can ask him to connect the device to the wifi?

**Comment by lachezartodorov** [comment]
This is the ECU Export:
```
{'address': 2017,
'bus': 0,
'ecu': 'transmission',
'fwVersion': b'\xf1\x870GC300043  \xf1\x892301',
'logging': False,
'obdMultiplexing': False,
'responseAddress': 0,
'subAddress': 0},
{'address': 2016,
'bus': 0,
'ecu': 'engine',
'fwVersion': b'\xf1\x8704L906026KD\xf1\x894798',
'logging': False,
'obdMultiplexing': False,
'responseAddress': 0,
'subAddress': 0},
{'address': 1810,
'bus': 0,
'ecu': 'eps',
'fwVersion': b'\xf1\x875Q0910143C \xf1\x892211\xf1\x82\x0567B0020600',
'logging': False,
'obdMultiplexing': False,
'responseAddress': 0,
'subAddress': 0},
{'address': 1879,
'bus': 0,
'ecu': 'fwdRadar',
'fwVersion': b'\xf1\x873Q0907572C \xf1\x890196',
'logging': False,
'obdMultiplexing': False,
'responseAddress': 0,
'subAddress': 0},
{'address': 1813,
'bus': 0,
'ecu': 'srs',
'fwVersion': b'\xf1\x873Q0959655BG\xf1\x890712\xf1\x82\x0e5915005914001305701311052900',
'logging': False,
'obdMultiplexing': False,
'responseAddress': 0,
'subAddress': 0}
```

**Pull request merged**
