### PR TITLE
loggerd: scale qcamera with omx

### PR DESCRIPTION
**Pull request by deanlee**
May save  >8% cpu usage

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Cool. Can you post a breakdown of where all the loggerd CPU is going in #23269?

**Comment by adeebshihadeh** [comment]
loggerd tests failed on C3
```
======================================================================

FAIL: test_rotation (__main__.TestLoggerd)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "selfdrive/loggerd/tests/test_loggerd.py", line 149, in test_rotation

    self.assertEqual(len(diff), 0, f"didn't get all expected files. run={_} seg={n} {route_path=}, {diff=}\n{logged=} {expected_files=}")

AssertionError: 2 != 0 : didn't get all expected files. run=0 seg=0 route_path='/data/media/0/realdata/2022-01-22--13-59-11', diff={'qcamera.ts.lock', 'rlog.bz2.lock'}

logged={'qlog.bz2', 'qcamera.ts', 'fcamera.hevc', 'ecamera.hevc', 'qcamera.ts.lock', 'dcamera.hevc', 'rlog.bz2', 'rlog.bz2.lock'} expected_files={'qlog.bz2', 'qcamera.ts', 'fcamera.hevc', 'ecamera.hevc', 'dcamera.hevc', 'rlog.bz2'}



----------------------------------------------------------------------
```

**Comment by deanlee** [comment]
Found another problem while running test_loggerd.py:
`cereal/visionipc/visionipc_client.cc: Failed to free buffer 0`

`HANDLE_EINTR(ioctl(ion_fd, ION_IOC_FREE, &handle_data))` return -1 with errno 22(EAGAIN)

**Comment by adeebshihadeh** [comment]
Moving away from OMX in #24293.

**Pull request closed without merging**
