### PR TITLE
Cleaned up TSS2 Prius entry a bit, added correct safetyParam

### PR DESCRIPTION
**Pull request by zorrobyte**
As it says on the tin. Also, factory sR is 13.4.

safetyParam of 66 is correct (from "old" Prius), they didn't update the EPS, rack, etc.

Screen Shot 2020-11-10 at 1 22 33 AM
66 safetyParam

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can you verify the EPS factor with `selfdrive/debug/toyota_eps_factor.py`? If it needs to be changed, the DBC also needs to be updated.

**Comment by zorrobyte** [comment]
@rav4kumar reports safetyparam of 55 is most accurate

Screenshot_114

Let me do some work and I'll verify the EPS factor with the script on both years

**Comment by zorrobyte** [comment]
This may not be needed, pending https://github.com/commaai/openpilot/issues/2514

**Comment by adeebshihadeh** [comment]
I'd like to verify all the toyota safety params and test them in CI, so this will get done at that point.

**Pull request closed without merging**
