### PR TITLE
Update values.py for VW Passat MK8

### PR DESCRIPTION
**Pull request by Sparkguys**
Added FW for Passat MK8 in Japan

### CODE REVIEW

**Comment by Sparkguys** [comment]
all checks have passed.

**Comment by Sparkguys** [comment]
sorry. wrong operation. let me reopen pull

**Comment by sshane** [comment]
What is your dongle id?

**Comment by Sparkguys** [comment]
> What is your dongle id?

Hi,  sorry for late reply.   
this is  bbe9808191ca5422

**Pull request merged**
