### PR TITLE
`raylib`: update `spinner.cc` to use `RAYLIB_` prefix

### PR DESCRIPTION
**Pull request by BBBmau**
This is necessary since when I was attempting to use `hw.h` in initial setup PR I ran into errors where they both had defined COLORS with the same name. spinner still works and is just to resolve the duplicate naming between hw.h and raylib.h

### CODE REVIEW

**Comment by maxime-desroches** [comment]
That's not how you want to do it. You will have to modify it on our fork [here](https://github.com/commaai/raylib/blob/master/src/raylib.h#L175) first and then bump the commit [here](https://github.com/commaai/openpilot/blob/master/third_party/raylib/setup.sh#L33)

**Comment by maxime-desroches** [comment]
This might also conflict with colors from `ncurses` that already use the `COLOR_...` nomenclature (see [here](https://github.com/commaai/openpilot/blob/master/tools/replay/consoleui.cc#L74))

**Comment by BBBmau** [comment]
> That's not how you want to do it. You will have to modify it on our fork [here](https://github.com/commaai/raylib/blob/master/src/raylib.h#L175) first and then bump the commit [here](https://github.com/commaai/openpilot/blob/master/third_party/raylib/setup.sh#L33)

was actually thinking of whether I needed to make the change on the raylib repo or not. Was gonna go back to check but this confirms it. Thanks!



> This might also conflict with colors from `ncurses` that already use the `COLOR_...` nomenclature (see [here](https://github.com/commaai/openpilot/blob/master/tools/replay/consoleui.cc#L74))

I don't see how it would conflict since what you linked is specifically being called for the consoleUI, i don't think we'll ever include both `consoleui` and `raylib.h` in one at any point in the future.

**Comment by maxime-desroches** [comment]
It's just confusing to have 2 objects with the same name but not the same origin and definition (when grepping for stuff)

**Comment by BBBmau** [comment]
> It's just confusing to have 2 objects with the same name but not the same origin and definition (when grepping for stuff)

yeah I agree, we can have the prefix be `RAYLIB_` just so it's obvious where its being used. I'll make the changes on the raylib repo and change this PR to just be the commit update later today.

**Comment by BBBmau** [comment]
I'll mark it as ready for review once the PR in raylib gets merged, then i can push the commit onto here.

**Comment by maxime-desroches** [comment]
You should be good to include `hw.h` now

**Pull request closed without merging**
