### PR TITLE
cabana: extend color palette, make chart colors match signal view

### PR DESCRIPTION
**Pull request by pd0wm**
Generate "random" but nice looking colors. I'm open to a different color generation function, but this seems to produce acceptable results and is deterministic based on signal properties.

2023-02-08-123824_493x800_scrot
2023-02-08-123804_814x715_scrot

### CODE REVIEW

**Comment by deanlee** [comment]
Wooooooow! awesome!

**Comment by deanlee** [comment]
found some ui issues in your screenshot (not related to this PR). but the cell spacing and button size looks good on my laptop.

**Comment by pd0wm** [comment]
I'm using i3, which probably has a very minimal theme with no extra spacing/padding.

**Comment by deanlee** [comment]
> the most notable thing is the lack of border to resize the messages/graph window. There only some very minimal dots to show where to drag.

yes i was bothered by it too. I can't even see the dots.

**Comment by adeebshihadeh** [comment]
Looks great!

Side note: @pd0wm anything you're still missing from web cabana? I'd like to deprecate web cabana soon.

**Comment by pd0wm** [comment]
Think usability is way past web cabana :)

My whish list:
- A nice list of drives pulled from the API if you don't start with a command line argument would be nice. I've been experimenting with a startup wizard to choose a source.
- A prebuilt (single statically linked binary) cabana built by github actions that you can just download and run.

**Pull request merged**
