### PR TITLE
GM: GMC Acadia: Almost perfect custom lateral tune

### PR DESCRIPTION
**Pull request by Verylukyguy**
An almost perfect GMC Acadia tune with data-based, custom FeedForward. 

Comma 3

Comma Master 0.8.17 @ e3268d8

2018 GMC Acadia

df51b2195de66a9b|2022-10-16--15-55-34--0

df51b2195de66a9b|2022-10-08--22-59-55--0  -  This route with lots of highway driving was on an identical fork before I cloned it to my repo

Many months of testing and adjustments with @twilsonco have generated this tuning that allows for nearly handsfree interstate driving.

### CODE REVIEW

**Comment by Verylukyguy** [comment]
The current custom tuning in stock OpenPilot was based on very little data, about 8-10 miles of driving, and is incomplete.   This tuning is based on several hundred miles of driving.

**Comment by Verylukyguy** [comment]
Long Drive 001
Long Drive 002
Here are a couple 450 mile drives with few interventions and interactions.

**Comment by Verylukyguy** [comment]
Acadia FeedForward

**Comment by Verylukyguy** [comment]
Is it because this tuning is for the PID Controller and not the Torque Controller that this is not being merged, discussed, or even commented on?

If so, @twilsonco also has data and tuning for the Torque Controller on this vehicle.

Are there other plans for GM port as a whole that might affect this vehicle port?

I will be going on another cross-country trip in five weeks and could have another 2000 miles of data.

**Comment by adeebshihadeh** [comment]
Discussed this with @nuwandavek, and we're going to close this. I can believe that this may be an improvement for you, but this tune is likely hypter-optimized for your car. It's not scalable to merge 50+ lines tuning PRs for individual car models. We're working on this problem more generally, and will hopefully ship something soon. In the meantime, this should be simple enough to maintain in a fork if you're inclined to.

**Comment by Verylukyguy** [comment]
I made a mistake when I opened this PR.  @twilsonco rewrote the tuning on a clean commit for review and merge.

https://github.com/commaai/openpilot/commit/149a18095a3c0e043aae2512439dbd35f2513b27

Would you reconsider merging this tuning, because it is basically just correcting the custom tuning that was already merged that was only based on 6-8 miles of driving?

**Pull request closed without merging**
