### PR TITLE
Added 2019 Highlander XLE Fingerprint 

### PR DESCRIPTION
**Pull request by ghost**
Added fingerprint for 2019 Highlander XLE

### CODE REVIEW

**Comment by rbiasini** [comment]
looks good. Can you please post here (or DM me on discord) the cabana route you used to collect this fingerprint? Tnx!

**Comment by CAmaninacan1** [comment]
I am waiting for all my drives to upload and will share a link.

**Comment by rbiasini** [comment]
@CAmaninacan1 , if you can confirm soon, I'll squeeze this in the next release :)

**Comment by CAmaninacan1** [comment]
Here you go, I am pretty sure this is it. 

https://community.comma.ai/cabana/?route=a28bd06508564a39%7C2019-06-03--23-33-57&max=4&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Fa28bd06508564a39%2F617c209e6f83bf599e35cc2bdac3b990_2019-06-03--23-33-57

**Comment by rbiasini** [comment]
confirmed

**Pull request merged**
