### PR TITLE
simulator: add_bridge_test

### PR DESCRIPTION
**Pull request by StefanLekanic-SYRMIA**

### CODE REVIEW

**Comment by StefanLekanic-SYRMIA** [comment]
#31759

**Comment by StefanLekanic-SYRMIA** [comment]
Navd is crashing all the time...

**Comment by mimi89999** [comment]
What framerate are you getting in MetaDrive on GH Actions?

**Comment by StefanLekanic-SYRMIA** [comment]
https://github.com/commaai/openpilot/actions/runs/8552729312/job/23434461222?pr=32102
@michaelhonan I can't see frame rate... i get message "vipc_client_main no frame"...

**Comment by StefanLekanic-SYRMIA** [comment]
When i run it locally, it has the same behaviour, but i can see the frame rate. It starts from 14.88, and falling to the 8.40, at the end... 
Screenshot from 2024-04-09 12-00-05

**Comment by mimi89999** [comment]
Run `export BLOCK="mapsd,navd"` before launching `./tools/sim/launch_openpilot.sh`. Then OP should start.

**Comment by mimi89999** [comment]
Have you tried running the test from https://github.com/commaai/openpilot/issues/30693#issuecomment-2044604518 ?

**Comment by StefanLekanic-SYRMIA** [comment]
@mimi89999 it works definitely, i blocked just that in [86edf77](https://github.com/commaai/openpilot/pull/32102/commits/86edf778d38bf4e0d6bd06d0f27d8a5c71c596ac), and it was working smoothly... but in #31125 is mentioned that no proccesses can be blocked...

**Comment by StefanLekanic-SYRMIA** [comment]
> Have you tried running the test from [#30693 (comment)](https://github.com/commaai/openpilot/issues/30693#issuecomment-2044604518) ?

No i didn't... i will try

**Comment by StefanLekanic-SYRMIA** [comment]
Hi @jnewb1 , is there any possible problem again in simulator, with navd... Before simulator repair it was working.

**Pull request closed without merging**
