### PR TITLE
Ford: add missing Mach-E fw

### PR DESCRIPTION
**Pull request by incognitojam**
**Car**
Ford Mustang Mach-E

**Route**
`83a4e056c7072678/2023-11-13--16-51-33` (which is already in selfdrive/car/tests/routes.py, added in #30691)

### CODE REVIEW

**Comment by SurferSD** [comment]
83a4e056c7072678|2024-01-23--08-20-28 

Same dongle, current, preserved/public route with detected firmware.

**Comment by sshane** [comment]
Both FW in those routes are already in the DB: `b'MJ98-14C204-BBS\x00\x00\x00\x00\x00\x00\x00\x00\x00',`

**Comment by incognitojam** [comment]
```
$ ./selfdrive/debug/test_fw_query_on_routes.py "83a4e056c7072678/2023-11-13--16-51-33"
  0%|                                                                                 | 0/1 [00:00<?, ?it/sOld style: FORD MUSTANG MACH-E 1ST GEN Vin 3FMTK3SU0MMA25827
New style (exact): set()
New style (fuzzy): set()
  Brand: ford, bus: 1 - (Ecu.eps, 0x730, None): [b'LJ9C-14D003-AM\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 1 - (Ecu.fwdCamera, 0x706, None): [b'ML3T-14H102-ABS\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 1 - (Ecu.abs, 0x760, None): [b'LK9C-2D053-CK\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 1 - (Ecu.fwdRadar, 0x764, None): [b'ML3T-14D049-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 1 - (Ecu.engine, 0x7e0, None): [b'MJ98-14C204-BBP\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 0 - (Ecu.eps, 0x730, None): [b'LJ9C-14D003-AM\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 0 - (Ecu.fwdCamera, 0x706, None): [b'ML3T-14H102-ABS\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 0 - (Ecu.abs, 0x760, None): [b'LK9C-2D053-CK\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 0 - (Ecu.fwdRadar, 0x764, None): [b'ML3T-14D049-AL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
  Brand: ford, bus: 0 - (Ecu.engine, 0x7e0, None): [b'MJ98-14C204-BBP\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
Mismatches
(0x7e0, None) - b'MJ98-14C204-BBP\x00\x00\x00\x00\x00\x00\x00\x00\x00'
(0x7e0, None) - b'MJ98-14C204-BBP\x00\x00\x00\x00\x00\x00\x00\x00\x00'

100%|█████████████████████████████████████████████████████████████████████████| 1/1 [00:17<00:00, 17.06s/it]

FORD MUSTANG MACH-E 1ST GEN
  (0x7e0, None): [
    b'MJ98-14C204-BBP\x00\x00\x00\x00\x00\x00\x00\x00\x00',
  ]


Number of dongle ids checked: 1
Fingerprinted:                0
Not fingerprinted:            1
  of which had a fuzzy match: 0

Correct fuzzy matches:        0
Wrong fuzzy matches:          0
```

**Comment by sshane** [comment]
I see after 2023-12-11 it switched to the new FW, maybe the user went in for a recall or some other work. All the more reason we should ignore the engine and other non-essential ECUs to the openpilot API with better fuzzy FP!

**Comment by incognitojam** [comment]
I think the Mach-E gets OTAs

**Pull request merged**
