### PR TITLE
Add "Accept-Encoding: gzip" header to mapd.py to reduce data consumption

### PR DESCRIPTION
**Pull request by eFiniLan**
after a few tests, I noticed that overpass.kumi.systems server does not support any kind of response data compression.

The response data size greatly reduced when we use overpass-api.de server with "Accept-Encoding: gzip" header added.

With the same request, overpass-api.de: 271k vs overpass.kumi.systems: 2227k

image

We can potentially increase the radius to 9000 on overpass-api.de and consume around the same amount of data on overpass.kumi.systems with radius of 3000

image

### CODE REVIEW

**Comment by pd0wm** [comment]
I really like the idea of using compression to reduce the download size. Unfortunately all the openpilot users combined generate quite a large number of requests, which this endpoint might not be able to handle.

Currently we have permission by the owners of the current endpoint to hit the endpoint as much as we like. I'll contact them and ask if they can support gzip support. Otherwise we will host our own endpoint.

**Comment by eFiniLan** [comment]
> I really like the idea of using compression to reduce the download size. Unfortunately all the openpilot users combined generate quite a large number of requests, which this endpoint might not be able to handle.
> 
> Currently we have permission by the owners of the current endpoint to hit the endpoint as much as we like. I'll contact them and ask if they can support gzip support. Otherwise we will host our own endpoint.

no worries that's understandable 👍 hopefully kumi system will support gzip soon. :)

**Comment by arne182** [comment]
@pd0wm 
What about downloading the open street maps statewise and run the server locally on the eon?

**Comment by pd0wm** [comment]
@eFiniLan according to Kumi Systems they have enabled gzip. Can you verify that this is the case?

@arne182, that would be nice, but that would require a nice UI to select and sync selected areas. We definitely want to switch to that in the future.

**Comment by eFiniLan** [comment]
> @eFiniLan according to Kumi Systems they have enabled gzip. Can you verify that this is the case?

@pd0wm looks like it's working now, I've changed the server back to kumi :)
image

**Pull request merged**
