### PR TITLE
UI Refactor: move vision releated code into class UIVision

### PR DESCRIPTION
**Pull request by deanlee**
1. move vision releated code into class `UIVision`
2. create and delete `UIVision` on demand.

### CODE REVIEW

**Comment by pd0wm** [comment]
Sorry I left this unreviewed for so long. Merged your PR with moving the intrinsics matrix to modeldata, so we'd need to integrate that here.

Would be possible to make the ui adapt to different intrinsics matrices on the fly? Currently they are hardcoded by QCOM/QCOM2 ifdefs, but that makes it impossible to review data on the computer. You should be able to use the image size reported by VisionIPC to choose the correct one. This would also require delaying some of the init code until the first frame comes in.

**Comment by deanlee** [comment]
ok I'll try

**Comment by deanlee** [comment]
Put the code of UIVision in paint.cc to make it easier for review. can be moved to ui.cc next time.

only inited `road_view_transform` from `VisionBuf`. I can't figure out a clear way to init driver_view_transform now. it might be better to do it next time.

**Comment by adeebshihadeh** [comment]
I'm not sure this refactor makes much sense with the new UI. I think it makes more sense to move the onroad UI to Qt from NVG and make a nice camera view widget. @pd0wm what do you think?

**Comment by adeebshihadeh** [comment]
So we want to move the onroad UI to Qt, but I think #20516 is a necessary pre-requisite. We'll get that merged then we can slowly migrate all the NanoVG stuff to Qt. As for this PR, I think it's best to refactor it a bit to make it a generic camera view widget.

**Pull request closed without merging**
