### PR TITLE
Bounty: FlexRay adapter

### PR DESCRIPTION
**Pull request by nanamiwang**
FlexRay adapter based on MPC5748G chip, passed basic FlexRay communication tests between two MPC5748G DEVKIT boards. 
For more information, please refer to the README doc:
[https://github.com/nanamiwang/openpilot/blob/flexray_bounty/flexray_adapter/README.md](https://github.com/nanamiwang/openpilot/blob/flexray_bounty/flexray_adapter/README.md)

### CODE REVIEW

**Comment by rbiasini** [comment]
@nanamiwang this looks amazing work. It will take a while to go through it. Thanks!

**Comment by TheMutley** [comment]
I have actual Flexray log from a car and the hardware to read/write to the FR bus. Let me know if you need any help.

**Comment by nanamiwang** [comment]
> I have actual Flexray log from a car and the hardware to read/write to the FR bus. Let me know if you need any help.
@TheMutley The Flexray log is definitely helpful, can you send the log to me or share it on slack? I'd like to do some analysis and share the result.

**Comment by ghostriding** [comment]
nice work:)

**Comment by TheMutley** [comment]
@nanamiwang sorry for the delay, here's a Flexray log from an i3 driving on ACC with a FR channel and the powetrain CAN. 

image

[BMWi3ACCHighwayDrive.zip](https://github.com/commaai/openpilot/files/2717319/BMWi3ACCHighwayDrive.zip)

**Comment by nanamiwang** [comment]
@TheMutley thanks.

**Comment by rbiasini** [comment]
@nanamiwang , in 2-3 months we will do a openpilot port to a car that uses FlexRay (we have a nice Cadillac CT6 :)), possibly by leveraging this work. So that would be a way to verify this PR and unlock the bounty. Alternatively, any verification from the community would also be ok.

**Comment by nanamiwang** [comment]
@rbiasini this is ok for me, take your time. I am trying AUDI A4 porting to verify my work.
BTW, a question, why the official AUDI A4 porting bounty is removed? Bounty will encourage me to work more time on this.

**Comment by rbiasini** [comment]
Ah, yes, we removed it 8 months ago. It was probably removed because we bought the CT6 and we plan to do the port ourselves. I can put a bounty back, specific for Audi.

**Comment by nanamiwang** [comment]
Wow, it will be great.

**Comment by skycocker** [comment]
This would be so useful. Does anybody have a clue where to look for a flexray socket in a car? I believe I have 2 cars which should have one, I just have no idea where.

**Comment by cryptedx** [comment]
> This would be so useful. Does anybody have a clue where to look for a flexray socket in a car? I believe I have 2 cars which should have one, I just have no idea where.

There is no standard flexray socket in a car. You have to look at wiring diagrams at your car. 

Anyway, I don't think that this place is the right one to speak about such things (offtopic). Please join us at discord. Thank you.

**Comment by cryptedx** [comment]
> @nanamiwang , in 2-3 months we will do a openpilot port to a car that uses FlexRay (we have a nice Cadillac CT6 :)), possibly by leveraging this work. So that would be a way to verify this PR and unlock the bounty. Alternatively, any verification from the community would also be ok.

Verification will be done with my A4 :-D

**Comment by BrackoNe** [comment]
Can I provide some data, I have F34 (2015) and my car has lane assist, Park Distance Control PDC, Automatic Transmission, blind spot sensor and adaptive cruise control. Can I provide some of data to help this development?

**Comment by triscb82** [comment]
I live in Harrisburg, PA and have a 2018 BMW 540d xdrive fully loaded with all driving assist packages that I would be willing to allow use of as a guinea pig in exchange for making it work!

**Comment by nanamiwang** [comment]
@triscb82 Great, feel free to join #topic-flexray channel on comma discord server.

**Comment by zizo1111** [comment]
@nanamiwang Nice work, I have been trying to test the Adapter on a Vehicle, but it seems that there is a problem as i am not able to read all the frames. I can read only the frames with an even slot (cycle) Also I can't get the debugger to send readable messagges in oder to track the problem. I have writen you an email and i was hoping that you can help.
Thanks

**Comment by cryptedx** [comment]
@zizo1111 We are currently in alpha status. Please don't expect it to work. The development is going on every day, but it takes time. It is an extremely complicated topic!

What's you car?

**Comment by triscb82** [comment]
I have a 2018 BMW five series. I just completed an install on a Toyota RAV4 hybrid successfully. If you would like I would more than happy to pick up a development board and grab some captures off of the bus.  Anything I can do to be of help let me know.

**Comment by zizo1111** [comment]
> @zizo1111 We are currently in alpha status. Please don't expect it to work. The development is going on every day, but it takes time. It is an extremely complicated topic!
> 
> What's you car?

I totally understand.
I have a 2017 Audi Q5

**Comment by zizo1111** [comment]
> I have a 2018 BMW five series. I just completed an install on a Toyota RAV4 hybrid successfully. If you would like I would more than happy to pick up a development board and grab some captures off of the bus. Anything I can do to be of help let me know.
> […](#)
> On Jul 23, 2019, at 11:53 AM, crypted ***@***.***> wrote: @zizo1111 We are currently in alpha status. Please don't expect it to work. The development is going on every day, but it takes time. It is an extremely complicated topic! What's you car? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Thanks for your reply, did you manage to read all the frames using the adapter?

**Comment by cryptedx** [comment]
Please join the flexray channel on discord to discuss this. Thanks.

**Comment by danielehrhardt** [comment]
This is Insane!! :O

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Comment by emaba** [comment]
Is it still under development? Will there ever be a FlexRay integration?

**Comment by triscb82** [comment]
I would not count on it.  The guy who was helping me dropped off the
project.

**Comment by emaba** [comment]
> I would not count on it. The guy who was helping me dropped off the project.

It's unfortunate.
I hope that someone will try to integrate FlexRay into Openpilot again.

**Comment by zm0612** [comment]
I also hope that someone will try to integrate FlexRay into Openpilot again.

**Comment by thewhisperinyourears** [comment]
Alright!! I am willing to try it. I need some pattern support though. This seems to be fairly complicated and will take me some time.

**Pull request closed without merging**
