### PR TITLE
Ford: move to PlatformConfig

### PR DESCRIPTION
**Pull request by incognitojam**
Moved CarInfo and CarSpecs to PlatformConfig

### CODE REVIEW

**Comment by incognitojam** [comment]
probably not ready to move this yet

**Comment by jnewb1** [comment]
> probably not ready to move this yet

how come?

**Comment by incognitojam** [comment]
I just meant because it looked like it was in flux with adding CarSpecs

**Comment by jnewb1** [comment]
thanks!

**Pull request merged**
