### PR TITLE
Minor README.md update.

### PR DESCRIPTION
**Pull request by jfrux**
Loving the way this adds some realism and cleans things up a bit on the image.
Let's do this! xD <3

Thanks for the AMAZING and EXCITING update.  Driving on it first thing in the morning.
Congratulations Comma Team!

### CODE REVIEW

**Comment by valish** [comment]
Thanks for all your contributions @jfrux!

A few requests before we merge:
- Use the comma and openpilot branded top banner from the existing photo
- Use the actual chffr_wheel asset located at `/selfdrive/assets/img_chffr_wheel.png`
- Enlarge and reposition your speed typography to match what is drawn on the UI
- Ensure the left and right margins of the max speed and chffr_wheel are equal and match the UI
- Capitalize EON in context footer, try to match font with Maison Neue  

For pixel-perfect reference, here is the actual screenshot used in the original photo:
https://drive.google.com/file/d/17befVq8EFa2blvO43TP2K1GwnmeaWGXD

**Comment by jfrux** [comment]
Alright, I think I got it cleaned up.  Let me know if you see anything that isn't fitting.

**Comment by valish** [comment]
Awesome! Looks great!

Excited to get this merged. Thanks, @jfrux!

**Comment by jfrux** [comment]
@valish Thanks, all set! Let me know if you need anything else.

**Pull request merged**
