### PR TITLE
refactor loggerd

### PR DESCRIPTION
**Pull request by deanlee**
- [x] convert struct LoggerdState to class
- [x] split main into  functions to reduces the overall complexity

### CODE REVIEW

**Comment by deanlee** [comment]
split the main function into  member functions of LoggerdState. the logic is exactly the same as before.

**Comment by deanlee** [comment]
reverted "fix msgs from the first poll getting dropped".keep the functions consistent with the original version.

**Comment by adeebshihadeh** [comment]
I agree loggerd is in need of some refactoring, but let's keep it small. I think a good first step is to break bootlog off from loggerd.

**Comment by deanlee** [comment]
I'll split them to small PRS

**Pull request closed without merging**
