### PR TITLE
camerad: c++ sensorInfo

### PR DESCRIPTION
**Pull request by deanlee**
1. move remaining sensor parameters to SensorInfo
2. member functions.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
`camera_qcom2.cc` is almost under 1k lines now!

**Comment by deanlee** [comment]
yeah. It looks a lot more comfortable now. :D

**Comment by adeebshihadeh** [comment]
This segfaults on device. Can you test the camerad PRs on device?

**Comment by deanlee** [comment]
looks like a same bug as https://github.com/commaai/openpilot/pull/30642.

the sensor_init called before ci initialized cause this issue.

**Comment by adeebshihadeh** [comment]
Wanna remove the last two CAMERA_ID references? Then, I can begin bringing up a new sensor.

**Comment by deanlee** [comment]
sure

**Pull request merged**
