### PR TITLE
Bump tinygrad to master (0.7)

### PR DESCRIPTION
**Pull request by geohot**
Speed should be mostly the same, this is just to update to the latest.

This will be the last commit with `openpilot/compile.py` before `openpilot/compile2.py`

Should the CI fail for model speed?

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
> NOTE: still have to add NOLOCALS. Should the CI fail for model speed?

Yes,`test_onroad.py` has a bunch of generic checks on all services and will also fail if there are any system events that block engagement (e.g. model lagging). It's also got a check on the model execution times: https://github.com/commaai/openpilot/blob/f616dd77a18197e8d1d25bf8afbfc01c1ab2562b/selfdrive/test/test_onroad.py#L327

For a change like this, I'd still run it in the testing closet for a bit. I can set that up when it's ready for that.

**Comment by geohot** [comment]
Replay isn't matching because the fusions are slightly different. I might be able to fix this in tinygrad, we have a PR to bring 2/3 of them back.

**Comment by geohot** [comment]
`DATA_ENDPOINT=https://commadataci.blob.core.windows.net/openpilotci/ python release_tests/driving/compare_runtime.py vision_model=87eaea40-0a51-49f8-bc5c-be899cadb580/449 policy_model=baab2a46-f0c3-46eb-8756-00c55354945b/700 tici_commit=b02ed679ded88f314579af2cc2038738947b11be`
Screenshot 2023-10-15 at 9 20 21 PM

**Comment by geohot** [comment]
Will fix that missing file in tinygrad, it shouldn't need that one.

**Comment by geohot** [comment]
Fixed a bug and it now improves speed. 19.06 ms -> 17.89 ms (with no optimization!)

**Comment by geohot** [comment]
Screenshot 2023-10-16 at 8 58 02 PM

Should be good

**Comment by geohot** [comment]
Does it show the model speed diff anywhere?

**Comment by adeebshihadeh** [comment]
> Does it show the model speed diff anywhere?

Here's the test_onroad output:
```
------------------------------------------------
----------------- Model Timing -----------------
------------------------------------------------
'modelV2' execution time: min  0.02203s
'modelV2' execution time: max 0.03543s
'modelV2' execution time: mean 0.02326s
'driverStateV2' execution time: min  0.02175s
'driverStateV2' execution time: max 0.02724s
'driverStateV2' execution time: mean 0.02324s
------------------------------------------------
```

**Comment by geohot** [comment]
From master:
```
'modelV2' execution time: min  0.02275s
'modelV2' execution time: max 0.02708s
'modelV2' execution time: mean 0.02409s
```

So
```
min: 0.02275s -> 0.02203s
max: 0.02708s -> 0.03543s
mean: 0.02409s -> 0.02326s
```

Mean is 3.6% lower in this PR.

**Comment by adeebshihadeh** [comment]
The test is fairly noise since it's running the whole stack. Feel free to merge now if you don't expect any issues, otherwise I'll run in the testing closet tomorrow and merge if it looks good there.

**Comment by geohot** [comment]
Trusting the tests. It should be good from the tinygrad side.

**Pull request merged**
