### PR TITLE
paramsd: Sort messages in each update iteration before processing

### PR DESCRIPTION
**Pull request by nuwandavek**
Currently, `liveLocationKalman` messages are processed first, and the `carState` messages are processed later, even through the `carState` message was earlier. This leads the filter to ignore some `carState` messages as it is too old. The fix is to sort the messages on logMonoTime first before processing them.

Img below shows the difference in process replay, which is confirmed to be correct by liveParamsD.

image

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Looks like there's still a diff from process replay. Do you have uncommitted local changes?

**Comment by HaraldSchafer** [comment]
Yes it is, we were just talking about how to add logging for this stuff

**Comment by HaraldSchafer** [comment]
https://github.com/commaai/openpilot/issues/22254

**Comment by pd0wm** [comment]
@adeebshihadeh Should we add something to SubMaster instead? SubMaster.update() can return a list of socket names that are sorted by message arrival time for example.

**Comment by adeebshihadeh** [comment]
I don't think it makes sense for SubMaster to do the sorting. The sorting is really only important for the filter, so think it makes sense to enforce as close to the filter as possible.

**Comment by pd0wm** [comment]
I don't say we always enforce it, but by allowing you to loop over the result of `sm.update()` it makes it as easy as possible when you want it and hides some of the implementation details.

**Comment by nuwandavek** [comment]
Do we want to put this in `sm.update()`?

**Comment by adeebshihadeh** [comment]
I think this is fine to merge as-is, but if we do want to add it to sm.update, it should be an optional argument that defaults to False.

**Comment by pd0wm** [comment]
@adeebshihadeh `sm.update()` currently doesn't return anything, so there is not backwards compatibility needed.

@nuwandavek feel free to merge this now, we can always come back later and refactor

**Pull request merged**
