### PR TITLE
HKG: Add FW versions for Genesis GV70 2024

### PR DESCRIPTION
**Pull request by sunnyhaibin**
Add firmware versions for the 2024 Genesis G70 2.5T. Expand supported model-year range up to 2024.

Dongle ID: `3d0b679833560fa7`

Thanks to the community 2024 Genesis GV70 2.5T owner scullionw (Discord).

### CODE REVIEW

**Comment by scullionw** [comment]
first route: 

3d0b679833560fa7|2023-12-19--21-49-33--0

**Comment by scullionw** [comment]
slow speed / torque limits

3d0b679833560fa7|2023-12-19--22-00-40--0

**Comment by sshane** [comment]
Unfortunately your car is one that is also exhibiting some abnormalities, along with others I have documented here: https://github.com/commaai/openpilot/discussions/30810

**Comment by scullionw** [comment]
new routes with the bumped limit:

1. `3d0b679833560fa7|2023-12-20--11-54-06--0`
2. `3d0b679833560fa7|2023-12-20--13-32-05--0`
3. `3d0b679833560fa7|2023-12-20--13-50-13--0`

definitely a lot better. was actually surprised on that 3rd route i felt like i pushed it quite a bit and didn't hit the limit. but there were also times (mostly lower speed) where i hit the limit and didn't feel the torque was that much.

i'll try to also get some stock routes later

**Comment by scullionw** [comment]
lmk if you need anything to help move this forward!

**Comment by sshane** [comment]
It would be useful if you could get a drive with openpilot disabled (toggled off in settings), where you use the stock LFA lane centering taking as many curves as possible. If you only have LKAS (where it nudges you back into the lane), then many examples of that activating will do.

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
