### PR TITLE
Kia: add K8 Hybrid 2024 FW

### PR DESCRIPTION
**Pull request by thftgr**
Dongle ID : 1ba061d9a8a28ac7

RouteName : 1ba061d9a8a28ac7/00000001--b047385ab6

KIA_K8_HEV_1ST_GEN finger need to be added

Thanks.

### CODE REVIEW

**Comment by sshane** [comment]
Can you drive on the highway to gather some torque data?

**Comment by thftgr** [comment]
> Can you drive on the highway to gather some torque data?

I ride daily on roads with speed limits around 70-90km/h.
However, I've only had my c3x for a week and I'm using a fork customized for Korea, so I'm not using the official breech.
How do I set it up and drive it on the highway?

**Comment by sshane** [comment]
You can just drive as you would and connect to internet to upload the routes.

**Comment by thftgr** [comment]
> You can just drive as you would and connect to internet to upload the routes.

not upload started in my fork branch so i update py file use ssh
drive highway on this route 1ba061d9a8a28ac7/00000001--b047385ab6
https://useradmin.comma.ai/?onebox=1ba061d9a8a28ac7%7C00000001--b047385ab6

**Comment by sshane** [comment]
Waiting for a US car to bump the MY

**Pull request merged**
