### PR TITLE
Brazillian Corolla Hybrid needs Lockout  = False

### PR DESCRIPTION
**Pull request by AlexandreSato**
i dont kown how identify if the corolla is brazilian or not :/

### CODE REVIEW

**Comment by Namek** [comment]
I'm just curious, can you describe why?

**Comment by AlexandreSato** [comment]
When the fingerprint changed to v2 for some reason I don't know, it only works if you set low_speed_lockout to false, Virtually Chris discovered it

https://github.com/AlexandreSato/openpilot_VirtuallyChris/commit/ef42b0cb0e41d430a9d9dc7c94334ca891671ca3


Att
Alexandre Nobuharu Sato

Enviado do meu iPhone

Em 1 de mar. de 2021, à(s) 19:15, Kamil Dąbrowski <notifications@github.com> escreveu:

﻿

I'm just curious, can you describe why?

**Comment by pd0wm** [comment]
Can you provide some more information in this PR?

**Comment by AlexandreSato** [comment]
﻿it is better to talk directly with Virtually Chris


When the fingerprint changed to v2 for some reason I don't know, it only works if you set low_speed_lockout to false, Virtually Chris discovered it

https://github.com/AlexandreSato/openpilot_VirtuallyChris/commit/ef42b0cb0e41d430a9d9dc7c94334ca891671ca3



Att
Alexandre Nobuharu Sato

Enviado do meu iPhone

Em 3 de mar. de 2021, à(s) 08:12, Willem Melching <notifications@github.com> escreveu:

﻿

Can you provide some more information in this PR?

**Comment by Namek** [comment]
@VirtuallyChris ?

**Comment by anotabien** [comment]
Hi! Writting from Argentina!
Same thing happens to my Brazil made Corolla 2021 non-hybrid. dongleId = "1e9d51d3eb083940"
If self.low_speed_lockout is not set on False, C2 will show ¨Cruise Fault¨ error 90% of the time if not 100%, restart the car doesn´t fix it.
Also after setting up self.low_speed_lockout = False, OP won´t engage below 30km/h, so it loosed standstill feature.
This same thing happend to other users:
- Discord tomascw Argentina Rav4 Hybrid 2019
- Discord tape Thailand Corolla Cross

**Comment by adeebshihadeh** [comment]
Closing this PR, should be done in #20207.

**Pull request closed without merging**
