### PR TITLE
Added fingerprint from Sienna XLE AWD

### PR DESCRIPTION
**Pull request by xBJx**
Choose one of the templates below:

# Fingerprint
This pull requests adds a fingerprint for <Toyota - Sienna - 2018 - AWD XLE>.

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Don't forget to include a Cabana share link w/ the DSU connected, and Giraffe DIP configured to 1001.

**Comment by rbiasini** [comment]
@xBJx , thanks. Let me know if you have a cabana or explorer link you can share. We'll need it to very the correctness of the fingerprint.

**Comment by xBJx** [comment]
Not exactly certain how to do this.  I just had my Eon force update to 0.6.5 and now workbench is denied access (did key change?)  here is the URL to today
https://my.comma.ai/307249a92f279059/1571356952071/1571357071895
Also, Eon once again says my vehicle is unsupported.  I modified my local file through ssh to get it going last Sunday
URL to a drive sunday when it was working
https://my.comma.ai/307249a92f279059/1571009085503/1571010173232

**Comment by ErichMoraga** [comment]
Ensure you didn't accidentally disable SSH in the Settings menu.

**Comment by xBJx** [comment]
Link to drive after successful fingerprinting
Giraffe settings 1001  DSU Connected
https://my.comma.ai/307249a92f279059/1571456557680/1571456697902

**Comment by xBJx** [comment]
Cabana link from drive giraffe 1001 and DSU connected 

https://my.comma.ai/cabana/?route=307249a92f279059%7C2019-10-19--03-42-38&exp=1602995222&sig=6JqnQNAeHKpa5M9arLjBmI3WFKlzq2Fnf3hccuGyvQU%3D&max=2&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F307249a92f279059%2Fb6fa93cb64e0a3f4b1c1f7208ac2d165_2019-10-19--03-42-38

**Comment by rbiasini** [comment]
Looks good. Thanks!

**Pull request merged**
