### PR TITLE
Speed up YAML parsing with CSafeLoader

### PR DESCRIPTION
**Pull request by sshane**
yaml.FullLoader is quite slow and not safe by default (can execute code), use CSafeLoader (which uses a C parser, CLoader is equivalent in parsing time)

Time to create docs before: 14 seconds
TIme to create docs after: 2 seconds

Loading a single torque tune takes ~80 ms before this change (on PC), now it's ~10 ms

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Looks good, but a better title would be something like "Speed up YAML parsing with CSafeLoader"

**Comment by adeebshihadeh** [comment]
We can also just as easily make this python code instead of yaml.

**Comment by sshane** [comment]
I think it might be easier to export yaml than it is to automatically build valid Python, but up to @HaraldSchafer

**Comment by HaraldSchafer** [comment]
Doesn't matter to me

**Pull request merged**
