### PR TITLE
Portuguese: grammar and semantic corrections

### PR DESCRIPTION
**Pull request by guilhermicas**
reply for questions or changes

### CODE REVIEW

**Comment by sshane** [comment]
@AlexandreSato Does this look good?

**Comment by sshane** [comment]
I know this isn't part of your PR, but do you know a shorter phrase for Finish Setup? `Terminar Configuração` goes off the UI.

**Comment by AlexandreSato** [comment]
> I know this isn't part of your PR, but do you know a shorter phrase for Finish Setup? `Terminar Configuração` goes off the UI.

Some things in this pull request improve pt-BR but most do not match Brazilian Portuguese, it would be the case to create a new pt-PT Portuguese of Portugal translation  (it must be because of "file" in pt-PT is "ficheiro" and in pt-BR is "arquivo" , a Brazilian doesn't even know what a "ficheiro" is) .  "Finish Setup" sounds good!  I will review and use this PR to improve pt-BR

**Comment by sshane** [comment]
@guilhermicas If this is Portugal Portuguese, then want to make a new PR for it?

**Pull request merged**
