### PR TITLE
Hyundai: add fingerprint for 2020 IONIQ PHEV

### PR DESCRIPTION
**Pull request by 0h41**
**Car**
Hyundai IONIQ PHEV 2020

**Route**
3c7a58d85af72323/2024-02-05--18-59-45

### CODE REVIEW

**Comment by sshane** [comment]
Need to fix that MY detection \/

| Dongle, platform, VIN                                                                                                                 | Name from VIN 🆚 CarInfo                                                                            | Segments                | Bad seg tags   | Good seg tags                                         |
|:--------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------|:------------------------|:---------------|:------------------------------------------------------|
| [3c7a58d85af72323](https://useradmin.comma.ai/?onebox=3c7a58d85af72323)<br><sub>HYUNDAI IONIQ PHEV 2020<br>KMHC651DG........</sub>    | HYUNDAI  1990 🆚<br>Hyundai Ioniq Plug-in Hybrid 2020-22<br><sub>🎉 <b>New model year!</b> 🎉</sub> | 16 routes, 203 segments |                | - all lat active: 21<br>- no input all lat active: 12 |

**Comment by sshane** [comment]
Just wondering, can you try removing your car from this line in this list and drive around? Do you see any faults on the instrument cluster?

https://github.com/commaai/openpilot/blob/595406be67d43512f3a6c72d1cf17631262c5981/selfdrive/car/hyundai/hyundaican.py#L37

**Comment by sshane** [comment]
@0h41 were you able to try the change out?

**Comment by 0h41** [comment]
I will test it _eventually_, just need to find a moment to toy around with stuff.

**Comment by sshane** [comment]
@0h41 ever try it?

**Pull request merged**
