### PR TITLE
Remove Chevrolet Equinox 2019-22 from dashcam

### PR DESCRIPTION
**Pull request by sshane**
waiting on a test route

### CODE REVIEW

**Comment by nan0AI** [comment]
Test route as requested: 

https://connect.comma.ai/e746f59bc96fd789/1706735070366/1706735679162

**Comment by nan0AI** [comment]
It’s also possible to resume from start with this vehicle

**Comment by Verylukyguy** [comment]
> Test route as requested: This is using the frogpilot fork
> 
> https://connect.comma.ai/e746f59bc96fd789/1706735070366/1706735679162

Test routes usually need to be on Master or a Dev branch.  Shane had one for this PR. 
https://github.com/commaai/openpilot/tree/enable-equinox

**Comment by sshane** [comment]
This user's Equinox is more different than I expected, the moving backward bits are not used and always one. @nworb-cire is taking this over, you can open a new PR if you'd like!

**Comment by sshane** [comment]
Done in https://github.com/commaai/openpilot/pull/31257

**Pull request closed without merging**
