### PR TITLE
UI: show finish registration widget if not paired

### LINKED ISSUE #26262: No barcode two pair a new device
### Describe the bug

Hi everyone I'm having problem with my comma , too is not showing barcode in order to pair the device. Any help or advice would be much appreciated

### Provide a route where the issue occurs

When trying to install

### openpilot version

0.8.13.1

### Additional info

Hi everyone I'm having problem with my comma , too is not showing barcode in order to pair the device. Any help or advice would be much appreciated

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/issues/26262

### CODE REVIEW

**Comment by incognitojam** [comment]
what case did that user hit where the registration didn't show?

**Comment by deanlee** [comment]
> do you know how to reproduce the case where the registration didn't show?

no network or "NOT FOUND" returned from url '/v1/devices/dongleid/owner'

**Comment by Jameselectronis** [comment]
I have bought it used from ebay.  Don't know anything about previous owners  registration

**Comment by Jameselectronis** [comment]
> resolve #26262

I am not about how to do that. Any tips or instructions would much appreciated

**Comment by Jameselectronis** [comment]
> 

I have connected to my wifi if that's the case. but still showing that only. no bar code!!

**Comment by incognitojam** [comment]
I think if we did set a param for `DevicePaired` it wouldn't have helped in the no network scenario as the device would just remember that it used to be paired. Closing this now though as it seems it was user error not a bug.

**Pull request closed without merging**
