### PR TITLE
add Lexus UX Hybrid 2023 FW

### LINKED ISSUE #28767: Lexus UX250H Hybrid 2023 - Dashcam Mode Car Unrecognized
### Describe the bug

Lexus UX250H Hybrid 2023 - Dashcam Mode Car Unrecognized 

### Which car does this affect?

Lexus UX250H Hybrid 2023 - Dashcam Mode Car Unrecognized 

### Provide a route where the issue occurs

279e4980fb308469|2023-06-30--21-10-27

### openpilot version

0.9.4

### Additional info

Car not in repository and need this car added

### PR DESCRIPTION
**Pull request by bashiromar1795**

### CODE REVIEW

**Comment by incognitojam** [comment]
Does your car already work with openpilot? If it does there is no need to create a new platform and you can add the firmware to an existing platform.

**Comment by sshane** [comment]
Likely https://github.com/commaai/openpilot/pull/28752, was on the dashboard

**Comment by sshane** [comment]
@bashiromar1795 can you try this branch out and engage on a highway? Factory reset and use this URL below

Installer URL: https://installer.comma.ai/commaai/uxh-2023

**Comment by bashiromar1795** [comment]
It is working fine I really appreciate the help

**Pull request merged**
