### PR TITLE
Support Ioniq PHEV 2020

### LINKED ISSUE #21114: Support for Hyundai PHEVs

### PR DESCRIPTION
**Pull request by sshane**
Prerequisite PR: https://github.com/commaai/openpilot/pull/21147

Todo:
- [ ] Ioniq 2020 can use elect gears or cluster gears, the state is correctly propagated on both

### CODE REVIEW

**Comment by ShaneSmiskol** [comment]
@YawWashout I saw you have this car? Can you give a route name so I can try to find the gas pedal signal needed for this PR?

**Comment by YawWashout** [comment]
@ShaneSmiskol 

https://my.comma.ai/useradmin/?onebox=fa8db5869167f821%7C2021-06-02--06-40-43

**Comment by YawWashout** [comment]
Happy to test anything for you as well or if you need me to do a custom route, happy to help there too.

**Comment by ShaneSmiskol** [comment]
@YawWashout Make sure upload raw logs is enabled in settings. Also I have another PR to unify the gas pedal signal, so I'll let you know when it's ready to test!

**Comment by YawWashout** [comment]
@ShaneSmiskol awesome, really. I do 500 miles / week minimum and so this platform is life changing. 

I enabled the raw logs upload but might need to reconnect the device to wifi first. Will investigate in the am.

**Comment by ShaneSmiskol** [comment]
@YawWashout Can you message me on Discord? Shane#6175. It's not uploading your logs for some reason

**Pull request closed without merging**
