### PR TITLE
camerad: dont queue buffer if frame is dropped

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Is this still relevant?

**Comment by deanlee** [comment]
Yes, I think it's better to do a check on error before queue the buffer.

**Comment by adeebshihadeh** [comment]
Is it clear that the dropped frame is still queued up? Did you find some issue on device or is this a hypothetical?

**Comment by deanlee** [comment]
not very sure now. closed

**Pull request closed without merging**
