### PR TITLE
Dissolved Oxygen Model

### PR DESCRIPTION
**Pull request by haraschax**

### CODE REVIEW

**Comment by commaci-public** [comment]
ref for commit bfc1f06940f8542e35a148e0d2b2b9d040e577e6: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_dropout/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_bfc1f06940f8542e35a148e0d2b2b9d040e577e6.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by AlexandreSato** [comment]
Today 10/25/2024 i put 10h in this model dongleID: ```075b133b6181e058``` very good!

**Comment by ntegan1** [comment]
Seems to be better at not going over double yellow during curves, compared to mlsim v3/4

9b84658caefee71a/000000e8--2ec160cbe6

**Comment by commaci-public** [comment]
ref for commit 49b3d05a5f405ed84a99f60da3b3040682aae71a: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_dropout/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_49b3d05a5f405ed84a99f60da3b3040682aae71a.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by AlexandreSato** [comment]
today 30/10 just drove 12 hours on a1c495fe-78c2-44f7-8851-000eaf13e838/400   dongleID: 075b133b6181e058

**Pull request closed without merging**
