### PR TITLE
ci: parallel model_replay

### PR DESCRIPTION
**Pull request by maxime-desroches**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Do we need parallel? We won't be able to benchmark the timings if it's parallel.

**Comment by commaci-public** [comment]
ref for commit c7105b2e4f9e81bb192ad3fc1b0703e968346610: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_mr_fast/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_c7105b2e4f9e81bb192ad3fc1b0703e968346610.bz2<details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by maxime-desroches** [comment]
It brings down the actual process replay runtime from ~3 minutes to ~2 minutes

**Comment by maxime-desroches** [comment]
Closing since not enough memory on device to do caching for all 3 camera streams at the same time

**Pull request closed without merging**
