### PR TITLE
GM: steering pressed filtering

### PR DESCRIPTION
**Pull request by sshane**
This is actually quite bad, it activates all the time on minor bumps

### CODE REVIEW

**Comment by twilsonco** [comment]
FWIW, gm driver torque data doesn't look noisy except when OP has the wheel.

Driver only torque: 
Screen Shot 2023-05-19 at 8 05 34 AM
Screen Shot 2023-05-19 at 8 08 28 AM


And now while OP is steering:
Screen Shot 2023-05-19 at 8 09 23 AM
Screen Shot 2023-05-19 at 8 09 57 AM

The driver torque oscillations are identical to those in the delivered LKA torque. 

If planned steer torque could be smoother with respect to time, so too would the driver torque that registers.

**Comment by sshane** [comment]
The plots you compared are on two different scales (both x axis and y axis), so you can expect to see some more noise.

**Comment by twilsonco** [comment]
Oh I see what you mean. Different from what I had in mind. Thanks.

**Comment by sshane** [comment]
not ready yet

**Pull request closed without merging**
