### PR TITLE
Hyundai CAN: log nonAdaptive cruise state

### LINKED ISSUE #29810: HKG: log nonAdaptive
### Describe the bug

Hardware C3X
CANFD HKG HDA2 

Install master-ci or devel and enable experimental mode via toggle

[main cruise button](https://cdn.discordapp.com/attachments/734633317969952769/1149226910585462854/IMG_20230907_021531102.jpg)

[video](https://youtube.com/shorts/12vhf4qpQHg)

Short pressing main cruise on enables openpilot as expected. 
Long pressing main cruise button enable stock longitudinal and can even override calibration mode locked out.

### Which car does this affect?

Ioniq 5 2023 limited (probably all CANDFD HKG cars)

### Provide a route where the issue occurs

11c1f1909ca37bca|2023-09-07--02-11-17--0, 11c1f1909ca37bca|2023-09-07--06-04-09--0

### openpilot version

master-ci

### Additional info

this was already reported to shane via discord DM earlier in the night

### PR DESCRIPTION
**Pull request by sshane**
We currently allow engaging with normal non-adaptive cruise control. OP long does not matter as we send SCC messages in that state.

opendbc PR: https://github.com/commaai/opendbc/pull/949

### CODE REVIEW

**Comment by sshane** [comment]
@jnewb1 why did the bot remove my labels? It also seems wrong?

**Comment by sshane** [comment]
It's not even checking the first or latest commit, it's just broken.

**Comment by jnewb1** [comment]
I believe it should be fixed now, want to try merging master?

**Comment by sshane** [comment]
Out of 312491 segments checked last 2 years, there were only 4 examples where this signal was 1 or 2, and they look like legitimate cases where user entered this 'Cruise Control' mode.

Distribution checked: `Checked segments: 312491, dongles: 767 platforms: 41`

```
# SCCInfoDisplay values
85be60338117aab2|2022-01-13--12-43-04--3 HYUNDAI KONA ELECTRIC 2019 {0, 1, 2}
40812bc457628b70|2023-02-01--06-36-20--35 HYUNDAI SONATA 2020 {2}
85be60338117aab2|2022-01-13--12-43-04--2 HYUNDAI KONA ELECTRIC 2019 {0, 1, 2}
d015f0d097b9e23a|2022-06-19--15-01-57--5 HYUNDAI SONATA 2020 {0, 1, 2}
```

**Pull request merged**
