### PR TITLE
mpc_lib: fix dependencies

### PR DESCRIPTION
**Pull request by fredyshox**
This fixes issues causing mpc solvers being needlessly rebuilt in subsequent builds.

### CODE REVIEW

**Comment by fredyshox** [comment]
This improves macos CI build time, since it was recompiling these libs in scons cleanup step. Before merging this I want to test if it breaks multi-threaded builds (these dependencies were introduced for that purpose)

**Comment by adeebshihadeh** [comment]
Something still isn't right here. It requires two SCons runs on my machine before it stops rebuilding.

**Comment by adeebshihadeh** [comment]
Multithreaded build also doesn't work
```
Traceback (most recent call last):
  File "/home/batman/threepilot/selfdrive/controls/lib/longitudinal_mpc_lib/long_mpc.py", line 10, in <module>
    from openpilot.selfdrive.car.interfaces import ACCEL_MIN
  File "/home/batman/threepilot/openpilot/selfdrive/car/interfaces.py", line 15, in <module>
    from openpilot.selfdrive.controls.lib.events import Events
  File "/home/batman/threepilot/openpilot/selfdrive/controls/lib/events.py", line 7, in <module>
    import cereal.messaging as messaging
  File "/home/batman/threepilot/cereal/messaging/__init__.py", line 2, in <module>
    from .messaging_pyx import Context, Poller, SubSocket, PubSocket, SocketEventHandle, toggle_fake_events, \
ModuleNotFoundError: No module named 'cereal.messaging.messaging_pyx'
```

**Comment by fredyshox** [comment]
Ok seems like `lenv.Depends(generated_long, cereal)` makes it only depend on `libcereal.a`.

**Comment by fredyshox** [comment]
Made it to depend on `messaging_pyx.so`. Thats some really weird scons bug, that makes it detect non-existing changes in generated files only if `cereal/` directory is specified as a dependency...

**Comment by adeebshihadeh** [comment]
Multithreaded builds still seem broken
```
clang++ -o system/clocksd/clocksd -Wl,--as-needed -Wl,--no-undefined -Wl,-rpath=/var/jenkins_home/workspace/openpilot_master/third_party/acados/x86_64/lib -Wl,-rpath=/var/jenkins_home/workspace/openpilot_master/cereal -Wl,-rpath=/var/jenkins_home/workspace/openpilot_master/common -Wl,-rpath=/var/jenkins_home/workspace/openpilot_master/third_party/snpe/x86_64 system/clocksd/clocksd.o -Lthird_party/acados/x86_64/lib -Lthird_party/libyuv/x86_64/lib -Lthird_party/mapbox-gl-native-qt/x86_64 -Lcereal -Lcommon -L/usr/lib -L/usr/local/lib -Lthird_party/snpe/x86_64 -Lcereal -Lthird_party -Lopendbc/can -Lselfdrive/boardd -Lcommon common/libcommon.a -ljson11 cereal/libcereal.a cereal/libmessaging.a -lcapnp -lzmq -lkj

Traceback (most recent call last):

  File "/var/jenkins_home/workspace/openpilot_master/selfdrive/controls/lib/longitudinal_mpc_lib/long_mpc.py", line 10, in <module>

    from openpilot.selfdrive.car.interfaces import ACCEL_MIN

  File "/var/jenkins_home/workspace/openpilot_master/openpilot/selfdrive/car/interfaces.py", line 11, in <module>

    from openpilot.common.kalman.simple_kalman import KF1D, get_kalman_gain

  File "/var/jenkins_home/workspace/openpilot_master/openpilot/common/kalman/simple_kalman.py", line 1, in <module>

    from openpilot.common.kalman.simple_kalman_impl import KF1D as KF1D

ModuleNotFoundError: No module named 'openpilot.common.kalman.simple_kalman_impl'


```

**Pull request merged**
