### PR TITLE
PC: fix onnxruntime excessive CPU

### LINKED ISSUE #22736: 100% CPU on onnxruntime threads caused by spin-waits
### Describe the bug

I observed onnx_runner.py threads consuming nearly 100% of 4 CPU cores on my 8 core PC when running Openpilot simulations with Carla. Basically, one thread seems to consume less than a full core, while the others are at a solid 100%. I then tried different values for "options.intra_op_num_threads" in onnxrunner.py. The following results are from the System Monitor utility, where 100% means all 8 cores are busy. 

11% with CPUExecutionProvider  (1 thread)
21% with CPUExecutionProvider  (2 threads)
35% with CPUExecutionProvider  (3 threads)
44% with CPUExecutionProvider  (4 threads)
63% with CPUExecutionProvider  (6 threads)
 3% with CUDAExecutionProvider (4 threads)

### OS Version

Ubuntu 20.04LTS

### openpilot version or commit

e178bed3016957ae09228a91f793c8d5c00d5573

### Additional info

I was not able to get a "pip install onnxruntime-gpu" configuration working with my RTX2070 CUDA/CUDNN setup. I then built onnxruntime from source to see if it would help- it gave the same results for CPU operation, but now I got the CUDA/GPU working, with dramatic reduction of CPU time (after minor mods to onnx_runner.py to select CUDA execution). After a good deal of investigation it seems that onnxruntime CPU operation defaults to spin-waits on the input queues, which fully accounts for the measured results. Great for benchmarking, but not all that practical in this case. Given the low execution rate of the supercombo model, spin waits are major overkill; the operating system's scheduling should be entirely adequate.

Unfortunately, the latest onnxruntime APIs only support changing the allow_spinning option from C++; it isn't supported in the Python API. While the CUDAExecutionProvider solves my immediate simulation problems, it should be possible to rewrite the Python code for C++ disabling of the spinning. 

There are probably broader issues than just my Carla simulation on a PC- the Comma2 and Comma3 (and other) devices may suffer from the spinning, resulting in higher power dissipation than necessary, along with loss of available processing capability. At the very least, it would be a good idea to allow tuning the "options.intra_op_num_threads" value from an environment variable, to better match hardware capability with processing load.

### PR DESCRIPTION
**Pull request by jwolffe**
Excessive CPU was observed in simulations with Carla #22736. This PR  fixes it by supporting additional Execution Providers for onnxruntime. Apparently the basic onnxruntime package from PyPi has spin-waits that cannot be disabled. Several alternatives were explored, using pip installs of onnxruntime-gpu, onnruntime-openmp, and onnxruntime built from source to support GPU operation with CUDA on the RTX2070 test platform. Attempts to get the "stock" PyPi onnxruntime-gpu package to work with CUDA were unsuccessful, with the onnxruntime defaulting to CPU operation. Based on the measurements of CPU load and execution time of the model, I have tentatively chosen to set onnxruntime-openmp to be installed automatically from the pipfile, using PASSIVE wait policy. This PR supports users changing to other execution providers without modification of code, by installing alternative packages with pip. The following measurements were made with the changes in PR #23046 incorporated.

Performance measurements (100% CPU = 8 cores fully busy):
onnxruntime-openmp  PASSIVE policy	.019 sec	11% CPU
onnxruntime-openmp  ACTIVE policy 	.018 sec 	23% CPU
onnxruntime-gpu (cuda,  compiled source)  	.012 sec	 3% CPU
onnxruntime-gpu (no cuda, CPU 2 threads)	.038 sec 	20% CPU
onnxruntime (CPU spin-wait, 4 threads)	.018 sec 	41% CPU

### CODE REVIEW

**Comment by pd0wm** [comment]
Looks like the openmp version is no longer published since version 1.8.0 (https://github.com/microsoft/onnxruntime/releases/tag/v1.8.0). Any reason this was deprecated?

**Comment by jwolffe** [comment]
My understanding is that openvino is intended to provide GPU acceleration with Intel graphics hardware. Onnxruntime-gpu gives acceleration for Nvidia/CUDA hardware. I assume (perhaps incorrectly) that more users trying to run Carla/openpilot would have Nvidia.  My understanding is that most Intel GPU hardware is too "lightweight" to be of much help running Carla. CPU-only, with the help of threading on multicore processors, seems entirely reasonable for running the model in openpilot, though.

A version of CPU threading is now incorporated in the basic onnxruntime package, and as far as I can tell, they dropped ongoing support  for openmp threading because it became functionally redundant.  The only reason I recommended the stale onnxruntime-openmp package over basic onnxruntime is because it doesn't have the unavoidable spin-waits. When/if onnxruntime allows disabling spin waits I would recommend using it over the onnxruntime-openmp.

**Comment by pd0wm** [comment]
OpenVINO also has a CPU only mode, which we use extensively in our data processing pipeline (uses Intel MKL).

**Comment by jwolffe** [comment]
> OpenVINO also has a CPU only mode, which we use extensively in our data processing pipeline (uses Intel MKL).

I never tried openvino.  If you are comfortable with the threading support it offers, I would go along with making it the default choice in the Pipfile.

**Comment by pd0wm** [comment]
Let me know if it works well for you. Not sure if we can add it the Pipfile by default, might give issues with installing on MacOS.

**Comment by jwolffe** [comment]
I have been trying to get openvino working with onnxruntime,  no success so far. Have you made it work?

**Comment by pd0wm** [comment]
Apparently we already moved away from it again internally. @gregjhogan just mentioned that the onnxrutime-gpu also includes the cpu runtime. If that's the case installing that package by default might make the most sense.

**Comment by jwolffe** [comment]
> Apparently we already moved away from it again internally. @gregjhogan just mentioned that the onnxrutime-gpu also includes the cpu runtime. If that's the case installing that package by default might make the most sense.

Unfortunately, the onnxruntime-gpu also has the unwanted spin waits when defaulting to CPU. Perhaps a "good enough" solution might be to just reduce the intra-op threads. I suggest 2 might be a reasonable choice, and just keep the plain onnxruntime in the Pipfile as the default.  The mods to onnx_runner.py would then allow further tailoring by the user in a wide variety of ways.

**Comment by pd0wm** [comment]
Wouldn't most people be able to use the cuda version though? We can change the intra-op threads to 2 as a fallback. 

What would be the reason to put the plain onxxruntime in the pipfile over the gpu one?

**Comment by jwolffe** [comment]
> Wouldn't most people be able to use the cuda version though? We can change the intra-op threads to 2 as a fallback.
> 
> What would be the reason to put the plain onxxruntime in the pipfile over the gpu one?

There is no particular advantage to the plain one. My experience was that I couldn't get the pypi onnxruntime-gpu to work with my Nvidia CUDA setup, I had to build it from source.  Others may find the magic combination to make the stock onnxruntime-gpu version work. So, perhaps we can converge on a solution here- onnxruntime-gpu in the Pipfile,  and intra-op threads set to 2 for CPU provider. Does that sound good to you? At least there will be only 2 threads running at ~100% in the absence of a working CUDA config.

**Comment by jwolffe** [comment]
I did some investigation into why my CUDA setup didn't work with the stock Pypi version of onnxruntime-gpu. It appears that there is a cuda bug in the stock Pypi package. When I ran "ldd /home/wolffja/.local/lib/python3.8/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so" I got the following:
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

I then ran "LD_DEBUG=all ldd /home/wolffja/.local/lib/python3.8/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so" and the rather lengthy output included the following lines:
...
      5839:	
      5839:	checking for version `GCC_3.0' in file /lib/x86_64-linux-gnu/libgcc_s.so.1 [0] required by file /home/wolffja/.local/lib/python3.8/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so [0]
      5839:	checking for version `GLIBC_2.3' in file /lib64/ld-linux-x86-64.so.2 [0] required by file /home/wolffja/.local/lib/python3.8/site-packages/onnxruntime/capi/libonnxruntime_providers_cuda.so [0]
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!
...

A solution to this is not obvious to me. Hopefully, a future update from 1.9.0 may fix this. Until then, it appears that openpilot users will have to build their own onnxruntime from source to get CUDA support.

**Pull request merged**
