### PR TITLE
Cabana: show MSB/LSB of signals in the BinaryView

### PR DESCRIPTION
**Pull request by deanlee**
Use a custom delegate to draw cells

abc1

### CODE REVIEW

**Comment by deanlee** [comment]
a custom SelectionModel has beed added to https://github.com/commaai/openpilot/pull/26097.  I recommend merging 26097 first. so that this PR can be done better base on 26097.

**Comment by adeebshihadeh** [comment]
Can we also give the vertical header the same padding as the cells? Looks a bit weird with the no padding.

**Comment by deanlee** [comment]
almost done.may need to add some bounds checks for array
cc3

**Comment by deanlee** [comment]
Fixed a crash caused  by different data size for the same address from different bus

**Pull request merged**
