### PR TITLE
cabana: remove dependence on opendbc

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Why aren't we relying on opendbc anymore?

**Comment by deanlee** [comment]
Cabana currently parses DBC by itself,  the only dependency on opendbc is that it needs to read the DBC file list from the  opendbc directory. 
this dbc file list can be obtained through `car_fingerprint_to_dbc.json`. so  looks like there is no need to link to the static library of OpenDBC anymore.

**Comment by sshane** [comment]
This removes a lot of DBCs from the list like radar DBCs and reference DBCs, really useful

image

image

**Comment by sshane** [comment]
Also, this removes radar DBCs from the list. Can we revert or at least add the remaining DBCs a better way? @deanlee

**Comment by deanlee** [comment]
> This removes a lot of DBCs from the list like radar DBCs and reference DBCs, used to be really useful.
> 
@sshane :Just saw this message, the github notifications didn't alert me that I had this unread:(. 

I'll fix this issue

**Pull request merged**
