### PR TITLE
VW MQB: Škoda Karoq Mk1

### PR DESCRIPTION
**Pull request by jyoung8607**
**Škoda Karoq Mk1**

Covers all variants of the first generation Karoq (2017-present).

- [x] added to README
- [x] test route added to [test_models.py](https://github.com/commaai/openpilot/blob/master/selfdrive/test/test_models.py)
- [x] route with openpilot: 12d6ae3057c04b0d|2021-09-04--21-21-21

Thanks again to community Škoda owner Saber422, who has a lot of Škoda friends!

image

### CODE REVIEW

**Comment by jyoung8607** [comment]
Side note: the selfdrive / car models CI test shouldn't be passing until the test route is cached to the CI bucket. 😕

**Comment by adeebshihadeh** [comment]
Hmm, fails on my PC as expected but not in CI.

**Comment by adeebshihadeh** [comment]
Merged before the tests passed, and they ended up failing. Reverted for now.
```
FAIL: test_car_interface (__main__.TestCarModel_77_SKODA_KAROQ_1ST_GEN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "selfdrive/test/test_models.py", line 113, in test_car_interface
    self.assertLess(can_invalid_cnt, 50)
AssertionError: 5799 not less than 50
```

**Comment by jyoung8607** [comment]
Note for future use: tests failed because this car doesn't have a factory Lane Assist camera, which is something we support in the community fork but not yet in upstream openpilot. I intend to add that support at a later date, and will then resubmit this PR.

**Pull request merged**
