### PR TITLE
deleter: improve performance

### PR DESCRIPTION
**Pull request by deanlee**
`listdir_by_creation`&`get_preserved_segments` is very resource consuming if there are a lot of segments on disk.
calling these two functions every time before deleting a directory will impact performance,  especially when `deleter` needs to delete old files continuously after `loggerd` is started when the disk is full.

This pr cache the sorted segments to variable `dirs`. only repopulate it after it becomes empty.

### CODE REVIEW

**Comment by incognitojam** [comment]
It's possible that a segment currently being written could be marked as preserved after the initial check/cache. We could either:
- check again if the segment is preserved immediately before deleting it
- when listing files for deletion, always ignore the most recent? though this might not be the segment we are currently writing if the timestamp is wrong.
any other ideas?

**Comment by incognitojam** [comment]
I think that works as long as the timestamps are correct, which they should be now since thermald will block going onroad with a bad date/time set

**Comment by deanlee** [comment]
updated. 
Check if there is a *.lock file in the directory to exclude the folder that are being written by loggerd. the downside is that building the cache will be slower.

**Comment by incognitojam** [comment]
want to add a test for this?

**Comment by adeebshihadeh** [comment]
We need a test before we can merge this.

**Comment by adeebshihadeh** [comment]
@deanlee thanks for the PR, but gonna close for now. This makes deleter more "bursty" and generally we want to keep the load of our services consistent.

**Pull request closed without merging**
