### PR TITLE
ui: disable longitudinal personality settings when using stock long

### LINKED ISSUE #28438: Gray out longitudinal personality setting when using stock long.
Longitudinal personality setting doesn't make sense for cars with stock long. Should be grayed out for those cars. @deanlee you want do this :D?

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/issues/28438

Screenshot from 2023-06-08 02-29-50

### CODE REVIEW

**Review by adeebshihadeh — COMMENTED** [review]
Can you make all buttons grey if it's disabled?

**Comment by deanlee** [comment]
disable title button:
Screenshot from 2023-06-09 05-24-29

**Comment by adeebshihadeh** [comment]
Oh, I just meant the selected green style shouldn't be used when it's disabled.

**Comment by deanlee** [comment]
Screenshot from 2023-06-09 05-38-59

**Comment by sshane** [comment]
@deanlee experimental mode is not greyed out, but driving personality is when you first boot openpilot without carparams. I think we want to do what experimental mode does?

**Pull request merged**
