### PR TITLE
Synchronize controls with the CAN bus

### PR DESCRIPTION
**Pull request by Gernby**
This enhancement works way better than I hoped, and actually reduces the CPU utilization of boardd.  The primary goal was to ensure that steering sensor data from the vehicle was neither skipped OR reused by controls due to mismatches in sample timing.  

The current logic uses a static 5 ms sleep time between the end of one CAN sample and the start of the next CAN sample in boardd.  This results in very irregular sample resolution due to varying traffic loads and USB thread contention.  For cars with heavy CAN traffic, the sample period of a particular 100Hz CAN frame can be deteriorated to an _effective_ alternating 50Hz / 200Hz rate.  This irregularity causes a direct deterioration of controls.

non-syncid

The proposed logic has 2 synchronization modes.  Both modes require the cp.update() method to wait for a packet from boardd.  The difference is in the way boardd determines when to send the packet.  If the new "syncID" value is set in interface for a vehicle, then boardd will synchronize itself on the receipt of that CAN frame.  This ensures that controls will never outpace the CAN bus (even if it runs below 100Hz).

syncid

The second mode is the default mode, when there isn't a syncID defined in interface.  In this mode, boardd will precisely synchronize on time.  It will drain the Panda 3 times per 0.01 seconds, but it will only send the data 1 time per 0.01 seconds.  To ensure precision, the first 2 calls to the Panda will occur at a "soft" 4.5 ms, with the sleep occurring outside of the USB lock.  However, the 3rd call to the Panda will occur inside the USB lock, so that USB contention doesn't disrupt timing.  

In order to prevent irregularity in control processing after the packet is received from boardd, the existing rate keeper is used to stage the data that will be sent back to the vehicle.  However, there can be only 1 absolute rate keeper, so an optional offset was added to the rk.keep_time() method.  This allows for occasional disruptions in the system without overrunning the secondary rate keeper.

### CODE REVIEW

**Comment by Gernby** [comment]
FYI... I just fixed some [embarrassing] mistakes I made while cleaning up the code for this PR.  I apparently cleaned too deep ,and broke a couple things.  I just finished retesting both sync modes, and have a cabana drive to share from each.

[Here](https://community.comma.ai/cabana/?route=ddd3e089e7bbe0fc%7C2019-03-04--14-55-36&max=7&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Fddd3e089e7bbe0fc%2F6ccb119b639cfbd28feebdb75a46565b_2019-03-04--14-55-36) is a drive using the default time-based synchronization, and [here](https://community.comma.ai/cabana/?route=ddd3e089e7bbe0fc%7C2019-03-04--15-04-30&max=7&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Fddd3e089e7bbe0fc%2F7bd25fcdbecad5dc0bb6d13832af3565_2019-03-04--15-04-30) is one using the STEERING_SENSORS frame as the syncID.

**Comment by geohot** [comment]
This functionality will be in 0.5.13!

**Comment by Gernby** [comment]
Awesome!  I need to review the code, and make sure that it contains my "learnings"!

**Comment by Gernby** [comment]
I found that synchronizing on CAN ID was too problematic without significant changes to the Panda logic, AND found that time synchronization alone provided almost all of the benefit.  The code was also simplified.

**Pull request closed without merging**
