### PR TITLE
Cabana: add save DBC dialog

### PR DESCRIPTION
**Pull request by deanlee**
Screenshot from 2022-10-30 14-31-28

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
I think adding a "copy to clipboard" button and a "save as" button to this dialog popup can complete the save DBC feature.

**Comment by deanlee** [comment]
updated:
Screenshot from 2022-10-30 15-26-13

**Comment by deanlee** [comment]
need test case for this function

**Comment by deanlee** [comment]
fixed precision problem:
> tools/cabana/tests/test_cabana.cc:30: FAILED:
  REQUIRE( sig[j].factor == new_sig[j].factor )
with expansion:
  0.0049015947 == 0.004901595

**Pull request merged**
