### PR TITLE
submaster: optimize pycapnp reader

### PR DESCRIPTION
**Pull request by deanlee**
https://github.com/commaai/cereal/pull/240

### CODE REVIEW

**Comment by pd0wm** [comment]
Are there any measurable performance increases from this?

Besides carParams, are we really reading the same value often enough this becomes worth it?

**Comment by deanlee** [comment]
the SubMaster will be read multiple times in many place (event not updated). 
this PR can also speed up the access speed of child elements even if read only after update:

> sm["abc"].a.x //  first read, pycapnp performance
> sm["abc"].a.b // native performance
> sm["abc"].a.c // native performance
> 
> sm["abc"].a.b[0] // first read. pycapnp performance
> sm["abc"].a.b[1] // native performance

**Comment by pd0wm** [comment]
How many percent of CPU does this save in practice?

**Comment by deanlee** [comment]
it depends.  it may save 1~2% cpu  of controlsd on my laptop (I am not very sure at the moment, I did not systematically test it) 
I have not tested on devices yet

**Pull request closed without merging**
