### PR TITLE
Hyundai: Car Port for AZERA Hybrid 6TH Generation

### PR DESCRIPTION
**Pull request by chanhojung**
Migrated from https://github.com/commaai/openpilot/pull/29946

### CODE REVIEW

**Comment by sshane** [comment]
Are you still having problems with the ignition only with 3/3X?

**Comment by sshane** [comment]
Tests should be fine now. On the ignition button, does it say ACC instead of the light going off?

**Comment by sshane** [comment]
@chanhojung which harness type (letter) did you use?

**Comment by haram-KONA** [comment]
> @chanhojung which harness type (letter) did you use?

Hyundai type K

**Comment by sshane** [comment]
Thanks!

**Pull request merged**
