### PR TITLE
Add Korean translations

### PR DESCRIPTION
**Pull request by crwusiz**
Add Korean translations

add main_ko
translate from main_zh

### CODE REVIEW

**Comment by sshane** [comment]
Make sure to run `selfdrive/ui/update_translations.py --release`, looks like there's a couple differences

**Comment by crwusiz** [comment]
> Make sure to run `selfdrive/ui/update_translations.py --release`, looks like there's a couple differences. You can delete that vanished string and move the translation to the new one.
> 
> Actually I'm not sure why I can't remove the vanished string manually, but just run update_translations, use linguist to copy the translation to the new string, save, then close and update the QM file. That should work

        <source>Get turn-by-turn directions displayed and more with a comma``` ``` 
        <source>Get turn-by-turn directions displayed and more with a comma

**Comment by sshane** [comment]
@crwusiz does my last commit look good?

**Comment by crwusiz** [comment]
> 
Good...!

**Comment by crwusiz** [comment]
> @crwusiz does my last commit look good?



> @crwusiz does my last commit look good?

Good..!!

**Comment by sshane** [comment]
You're missing `NO PANDA`, `Dongle ID`, and `Serial`. Or are those fine in English?

**Comment by crwusiz** [comment]
> You're missing `NO PANDA`, `Dongle ID`, and `Serial`. Or are those fine in English?

I thought it looked better in English.

**Comment by sshane** [comment]
Thanks for the PR!

**Pull request merged**
