### PR TITLE
VW MQB: Update steering angle and actuator delay

### PR DESCRIPTION
**Pull request by jyoung8607**
**Description**

Make two changes to the VW port as a prerequisite for further tuning work:

1. Increase our actuator delay a little, from 0.05 to 0.1. This is more in line with other ports, and seems to help temporally drag the actual curvature in closer toward the lateral plan curvature as measured with @qadmus's PlotJuggler layout. I might increase this again slightly, in a later round of tuning work.
2. Go back to our other steering angle signal, essentially reverting #20247. In the past, I thought it helped with lane changes, but that was largely a butt-dyno perception. It has better precision and it's meant for this sort of application. More importantly, to make effective use of feedforward (which we're not doing today) we need the steering angle centerline to also be the effective center of force. LWI_01 reflects the EPS straight-line driving compensation.

Further rounds of tuning will build on these changes.

**Verification**

1. I drove a route on `master` with ~45mph variably banked road and ~65mph freeway.
2. I drove that same route again with this PR.
3. I scienced the shit out of this with #23583.

The "after" route shows consistent reductions in average angle error and average path deviation.

**Route**

Before: `3cfdec54aa035f3f|2022-01-18--15-18-00`

```
speed group: fast                                                 25 - 35 m/s  //  90 - 126 km/h  //  56 - 78 mph
  ---------------------------------------------------------------------------------------------------------------
   0 | actuator: 10% | error: 0.15 | =: 15% | +:  42% | -: 41% | sat cnt:    0 | dpathpoints: 0.03 | total:  2621
   1 | actuator: 13% | error: 0.12 | =: 31% | +:  30% | -: 38% | sat cnt:    0 | dpathpoints: 0.03 | total:  5430
   2 | actuator: 27% | error: 0.12 | =: 27% | +:  25% | -: 47% | sat cnt:    0 | dpathpoints: 0.04 | total:  3002
   3 | actuator: 40% | error: 0.18 | =: 15% | +:  16% | -: 68% | sat cnt:    0 | dpathpoints: 0.08 | total:   430
   4 | actuator: 48% | error: 0.27 | =:  4% | +:   0% | -: 95% | sat cnt:    0 | dpathpoints: 0.06 | total:   105

speed group: medium                                                15 - 25 m/s  //  54 - 90 km/h  //  34 - 56 mph
  ---------------------------------------------------------------------------------------------------------------
   0 | actuator:  8% | error: 0.16 | =: 19% | +:  33% | -: 47% | sat cnt:    0 | dpathpoints: 0.03 | total:  7517
   1 | actuator: 17% | error: 0.21 | =: 14% | +:  22% | -: 62% | sat cnt:    0 | dpathpoints: 0.04 | total:  5496
   2 | actuator: 30% | error: 0.33 | =:  9% | +:   5% | -: 85% | sat cnt:    0 | dpathpoints: 0.08 | total:  1899
   3 | actuator: 42% | error: 0.45 | =:  2% | +:  16% | -: 80% | sat cnt:    0 | dpathpoints: 0.10 | total:   183
   4 | actuator: 51% | error: 0.59 | =:  0% | +:  29% | -: 70% | sat cnt:    0 | dpathpoints: 0.10 | total:   131
   5 | actuator: 56% | error: 0.74 | =:  6% | +:  30% | -: 62% | sat cnt:    0 | dpathpoints: 0.06 | total:    75
   6 | actuator: 70% | error: 0.60 | =:  7% | +:   7% | -: 85% | sat cnt:    0 | dpathpoints: 0.05 | total:   141
   7 | actuator: 73% | error: 0.84 | =:  0% | +:   9% | -: 90% | sat cnt:    0 | dpathpoints: 0.08 | total:   179
   8 | actuator: 84% | error: 0.75 | =:  0% | +:   0% | -:100% | sat cnt:    0 | dpathpoints: 0.07 | total:   145
   9 | actuator: 83% | error: 0.87 | =:  0% | +:   0% | -:100% | sat cnt:    0 | dpathpoints: 0.05 | total:    20
```

After: `3cfdec54aa035f3f|2022-01-18--15-37-40`

```
speed group: fast                                                 25 - 35 m/s  //  90 - 126 km/h  //  56 - 78 mph
  ---------------------------------------------------------------------------------------------------------------
   0 | actuator: 11% | error: 0.15 | =: 20% | +:  43% | -: 36% | sat cnt:    0 | dpathpoints: 0.03 | total:  1672
   1 | actuator: 12% | error: 0.10 | =: 32% | +:  40% | -: 26% | sat cnt:    0 | dpathpoints: 0.02 | total:  4960
   2 | actuator: 26% | error: 0.11 | =: 24% | +:  22% | -: 53% | sat cnt:    0 | dpathpoints: 0.03 | total:  3647
   3 | actuator: 35% | error: 0.14 | =: 26% | +:  18% | -: 55% | sat cnt:    0 | dpathpoints: 0.05 | total:   679
   4 | actuator: 50% | error: 0.23 | =: 15% | +:   0% | -: 84% | sat cnt:    0 | dpathpoints: 0.07 | total:   240

speed group: medium                                                15 - 25 m/s  //  54 - 90 km/h  //  34 - 56 mph
  ---------------------------------------------------------------------------------------------------------------
   0 | actuator:  7% | error: 0.14 | =: 24% | +:  39% | -: 36% | sat cnt:    0 | dpathpoints: 0.02 | total:  3709
   1 | actuator: 14% | error: 0.19 | =: 18% | +:  19% | -: 62% | sat cnt:    0 | dpathpoints: 0.04 | total:  3451
   2 | actuator: 26% | error: 0.29 | =: 13% | +:   9% | -: 77% | sat cnt:    0 | dpathpoints: 0.06 | total:  1377
   3 | actuator: 38% | error: 0.44 | =:  1% | +:   9% | -: 89% | sat cnt:    0 | dpathpoints: 0.11 | total:   275
   4 | actuator: 58% | error: 0.79 | =:  2% | +:  30% | -: 67% | sat cnt:    0 | dpathpoints: 0.11 | total:    49
   5 | actuator: 41% | error: 0.57 | =:  0% | +:  60% | -: 39% | sat cnt:    0 | dpathpoints: 0.21 | total:    23
   6 | actuator: 74% | error: 1.40 | =: 10% | +:  10% | -: 78% | sat cnt:    0 | dpathpoints: 0.11 | total:    46
   7 | actuator: 69% | error: 0.79 | =:  9% | +:   0% | -: 90% | sat cnt:    0 | dpathpoints: 0.08 | total:    65
   8 | actuator: 77% | error: 0.69 | =:  0% | +:   0% | -:100% | sat cnt:    0 | dpathpoints: 0.09 | total:   175
```

### CODE REVIEW

**Comment by jyoung8607** [comment]
Side note: for the medium speed range, you'll see a burst of increased error in the 3-6 degree range. It's there in both tests. It's a 45mph S-curve near my house for which I'm riding the ramp-rate limit, not my torque limit. I don't like it either. Any time you guys feel like giving back some of my [factory ramp rate](https://github.com/commaai/openpilot/blob/f85a75cf542bbb05b929b959cb566d3f941410ea/selfdrive/car/volkswagen/values.py#L20-L25), I'll be very happy to take it.

**Comment by HaraldSchafer** [comment]
Results look solid, is this still a draft?

**Comment by jyoung8607** [comment]
I decided I wanted to go ahead and test some more +/- actuator delays, just to make sure I've converged on the best value. If I don't find something better in the next day or so, I'll take it out of draft as-is.

**Comment by jyoung8607** [comment]
Can't do much better than this without tune adjustments, ready for consideration.

**Comment by adeebshihadeh** [comment]
@HaraldSchafer process replay refs need to be updated after this change

**Comment by HaraldSchafer** [comment]
Fixing

**Pull request merged**
