### PR TITLE
fast clone instructions

### PR DESCRIPTION
**Pull request by gregjhogan**
This is a blobless clone (full tree/history, but files not attached to master HEAD pulled on demand)
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

```
$ time git clone --filter=blob:none --recurse-submodules --also-filter-submodules https://github.com/commaai/openpilot.git
Cloning into 'openpilot'...
remote: Enumerating objects: 64512, done.
remote: Counting objects: 100% (498/498), done.
remote: Compressing objects: 100% (248/248), done.
remote: Total 64512 (delta 313), reused 389 (delta 228), pack-reused 64014
Receiving objects: 100% (64512/64512), 13.83 MiB | 27.88 MiB/s, done.
Resolving deltas: 100% (41397/41397), done.
remote: Enumerating objects: 1620, done.
remote: Counting objects: 100% (442/442), done.
remote: Compressing objects: 100% (413/413), done.
remote: Total 1620 (delta 36), reused 43 (delta 28), pack-reused 1178
Receiving objects: 100% (1620/1620), 72.12 MiB | 20.40 MiB/s, done.
Resolving deltas: 100% (230/230), done.
Updating files: 100% (1746/1746), done.
Filtering content: 100% (6/6), 82.08 MiB | 47.35 MiB/s, done.
Submodule 'body' (https://github.com/commaai/body.git) registered for path 'body'
Submodule 'cereal' (https://github.com/commaai/cereal.git) registered for path 'cereal'
Submodule 'laika_repo' (https://github.com/commaai/laika.git) registered for path 'laika_repo'
Submodule 'opendbc' (https://github.com/commaai/opendbc.git) registered for path 'opendbc'
Submodule 'panda' (https://github.com/commaai/panda.git) registered for path 'panda'
Submodule 'rednose_repo' (https://github.com/commaai/rednose.git) registered for path 'rednose_repo'
Submodule 'tinygrad' (https://github.com/geohot/tinygrad.git) registered for path 'tinygrad_repo'
Cloning into '/tmp/openpilot/body'...
remote: Enumerating objects: 301, done.        
remote: Counting objects: 100% (167/167), done.        
remote: Compressing objects: 100% (71/71), done.        
remote: Total 301 (delta 110), reused 123 (delta 94), pack-reused 134        
Receiving objects: 100% (301/301), 44.03 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (182/182), done.
Cloning into '/tmp/openpilot/cereal'...
remote: Enumerating objects: 2224, done.        
remote: Counting objects: 100% (301/301), done.        
remote: Compressing objects: 100% (153/153), done.        
remote: Total 2224 (delta 157), reused 277 (delta 141), pack-reused 1923        
Receiving objects: 100% (2224/2224), 430.02 KiB | 2.81 MiB/s, done.
Resolving deltas: 100% (1173/1173), done.
Cloning into '/tmp/openpilot/laika_repo'...
remote: Enumerating objects: 1080, done.        
remote: Counting objects: 100% (220/220), done.        
remote: Compressing objects: 100% (99/99), done.        
remote: Total 1080 (delta 164), reused 144 (delta 115), pack-reused 860        
Receiving objects: 100% (1080/1080), 175.41 KiB | 2.28 MiB/s, done.
Resolving deltas: 100% (635/635), done.
Cloning into '/tmp/openpilot/opendbc'...
remote: Enumerating objects: 3507, done.        
remote: Counting objects: 100% (1448/1448), done.        
remote: Compressing objects: 100% (87/87), done.        
remote: Total 3507 (delta 1398), reused 1376 (delta 1361), pack-reused 2059        
Receiving objects: 100% (3507/3507), 822.68 KiB | 4.52 MiB/s, done.
Resolving deltas: 100% (2064/2064), done.
Cloning into '/tmp/openpilot/panda'...
remote: Enumerating objects: 11884, done.        
remote: Counting objects: 100% (80/80), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 11884 (delta 57), reused 51 (delta 36), pack-reused 11804        
Receiving objects: 100% (11884/11884), 1.78 MiB | 8.34 MiB/s, done.
Resolving deltas: 100% (8194/8194), done.
Cloning into '/tmp/openpilot/rednose_repo'...
remote: Enumerating objects: 216, done.        
remote: Counting objects: 100% (95/95), done.        
remote: Compressing objects: 100% (48/48), done.        
remote: Total 216 (delta 70), reused 61 (delta 47), pack-reused 121        
Receiving objects: 100% (216/216), 34.40 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (94/94), done.
Cloning into '/tmp/openpilot/tinygrad_repo'...
remote: Enumerating objects: 10209, done.        
remote: Counting objects: 100% (10209/10209), done.        
remote: Compressing objects: 100% (3677/3677), done.        
remote: Total 10209 (delta 6194), reused 10177 (delta 6176), pack-reused 0        
Receiving objects: 100% (10209/10209), 1.37 MiB | 7.02 MiB/s, done.
Resolving deltas: 100% (6194/6194), done.
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 277 (delta 2), reused 14 (delta 0), pack-reused 242
Receiving objects: 100% (277/277), 1.81 MiB | 7.55 MiB/s, done.
Resolving deltas: 100% (44/44), done.
Submodule path 'body': checked out '396fa7b923099640d6843f338950ed41300793ec'
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 71 (delta 0), reused 10 (delta 0), pack-reused 17
Receiving objects: 100% (71/71), 79.88 KiB | 1.86 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Submodule path 'cereal': checked out '2077dd1a1b0054713102aee8197434f8cfa07de7'
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 73 (delta 0), reused 11 (delta 0), pack-reused 23
Receiving objects: 100% (73/73), 4.93 MiB | 18.84 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Submodule path 'laika_repo': checked out 'ef21c612f4b0d68c790b4b1a6d637cd5fce7732e'
remote: Enumerating objects: 167, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 167 (delta 58), reused 38 (delta 37), pack-reused 27
Receiving objects: 100% (167/167), 499.24 KiB | 2.84 MiB/s, done.
Resolving deltas: 100% (60/60), done.
Submodule path 'opendbc': checked out 'a1582f5e28fe0df23b6821c907188be477aac11c'
remote: Enumerating objects: 452, done.
remote: Counting objects: 100% (284/284), done.
remote: Compressing objects: 100% (269/269), done.
remote: Total 452 (delta 45), reused 16 (delta 15), pack-reused 168
Receiving objects: 100% (452/452), 4.82 MiB | 17.39 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'panda': checked out '1f475a8affc5270227af18e9c418b5fcd12575b9'
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 38 (delta 1), reused 7 (delta 0), pack-reused 10
Receiving objects: 100% (38/38), 358.76 KiB | 1.87 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Submodule path 'rednose_repo': checked out '22f02dd650361e091f09f1ae94c5c96a9419c2d4'
remote: Enumerating objects: 211, done.
remote: Counting objects: 100% (211/211), done.
remote: Compressing objects: 100% (187/187), done.
remote: Total 211 (delta 24), reused 96 (delta 13), pack-reused 0
Receiving objects: 100% (211/211), 14.24 MiB | 12.68 MiB/s, done.
Resolving deltas: 100% (24/24), done.
Submodule path 'tinygrad_repo': checked out 'd8dda2af3afcef0bb772fff580cfa8b3eabf7f69'

real    0m20.032s
user    0m5.618s
sys     0m2.584s

$ du -sh openpilot/
535M    openpilot/
```

### CODE REVIEW

**Comment by AlexandreSato** [comment]
image

**Comment by haraschax** [comment]
merge?

**Comment by adeebshihadeh** [comment]
We can't merge this as the default for the reason above.

**Comment by haraschax** [comment]
`
batman@workstation-harald:~$` time git clone --filter=blob:none --recurse-submodules https://github.com/commaai/openpilot.git
Cloning into 'openpilot'...
remote: Enumerating objects: 64153, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 64153 (delta 21), reused 44 (delta 9), pack-reused 64088
Receiving objects: 100% (64153/64153), 13.84 MiB | 19.04 MiB/s, done.
Resolving deltas: 100% (41163/41163), done.
remote: Enumerating objects: 1622, done.
remote: Counting objects: 100% (455/455), done.
remote: Compressing objects: 100% (418/418), done.
remote: Total 1622 (delta 46), reused 41 (delta 36), pack-reused 1167
Receiving objects: 100% (1622/1622), 72.12 MiB | 17.77 MiB/s, done.
Resolving deltas: 100% (236/236), done.
Updating files: 100% (1748/1748), done.
Filtering content: 100% (6/6), 82.08 MiB | 59.91 MiB/s, done.
Submodule 'body' (https://github.com/commaai/body.git) registered for path 'body'
Submodule 'cereal' (https://github.com/commaai/cereal.git) registered for path 'cereal'
Submodule 'laika_repo' (https://github.com/commaai/laika.git) registered for path 'laika_repo'
Submodule 'opendbc' (https://github.com/commaai/opendbc.git) registered for path 'opendbc'
Submodule 'panda' (https://github.com/commaai/panda.git) registered for path 'panda'
Submodule 'rednose_repo' (https://github.com/commaai/rednose.git) registered for path 'rednose_repo'
Submodule 'tinygrad' (https://github.com/geohot/tinygrad.git) registered for path 'tinygrad_repo'
Cloning into '/home/batman/openpilot/body'...
remote: Enumerating objects: 776, done.        
remote: Counting objects: 100% (223/223), done.        
remote: Compressing objects: 100% (96/96), done.        
remote: Total 776 (delta 138), reused 175 (delta 121), pack-reused 553        
Receiving objects: 100% (776/776), 1.93 MiB | 7.41 MiB/s, done.
Resolving deltas: 100% (400/400), done.
Cloning into '/home/batman/openpilot/cereal'...
remote: Enumerating objects: 3603, done.        
remote: Counting objects: 100% (491/491), done.        
remote: Compressing objects: 100% (229/229), done.        
remote: Total 3603 (delta 304), reused 409 (delta 255), pack-reused 3112        
Receiving objects: 100% (3603/3603), 1.03 MiB | 6.98 MiB/s, done.
Resolving deltas: 100% (2377/2377), done.
Cloning into '/home/batman/openpilot/laika_repo'...
remote: Enumerating objects: 1722, done.        
remote: Counting objects: 100% (472/472), done.        
remote: Compressing objects: 100% (191/191), done.        
remote: Total 1722 (delta 360), reused 322 (delta 275), pack-reused 1250        
Receiving objects: 100% (1722/1722), 10.47 MiB | 24.37 MiB/s, done.
Resolving deltas: 100% (1140/1140), done.
Cloning into '/home/batman/openpilot/opendbc'...
remote: Enumerating objects: 7944, done.        
remote: Counting objects: 100% (5364/5364), done.        
remote: Compressing objects: 100% (229/229), done.        
remote: Total 7944 (delta 5217), reused 5156 (delta 5134), pack-reused 2580        
Receiving objects: 100% (7944/7944), 2.62 MiB | 14.07 MiB/s, done.
Resolving deltas: 100% (6317/6317), done.
Cloning into '/home/batman/openpilot/panda'...
remote: Enumerating objects: 19791, done.        
remote: Counting objects: 100% (145/145), done.        
remote: Compressing objects: 100% (65/65), done.        
remote: Total 19791 (delta 97), reused 115 (delta 80), pack-reused 19646        
Receiving objects: 100% (19791/19791), 10.11 MiB | 34.61 MiB/s, done.
Resolving deltas: 100% (15087/15087), done.
Cloning into '/home/batman/openpilot/rednose_repo'...
remote: Enumerating objects: 375, done.        
remote: Counting objects: 100% (190/190), done.        
remote: Compressing objects: 100% (92/92), done.        
remote: Total 375 (delta 143), reused 122 (delta 98), pack-reused 185        
Receiving objects: 100% (375/375), 413.69 KiB | 2.78 MiB/s, done.
Resolving deltas: 100% (205/205), done.
Cloning into '/home/batman/openpilot/tinygrad_repo'...
remote: Enumerating objects: 16396, done.        
remote: Counting objects: 100% (1165/1165), done.        
remote: Compressing objects: 100% (175/175), done.        
remote: Total 16396 (delta 1063), reused 1013 (delta 988), pack-reused 15231        
Receiving objects: 100% (16396/16396), 18.97 MiB | 29.98 MiB/s, done.
Resolving deltas: 100% (11658/11658), done.
Submodule path 'body': checked out '396fa7b923099640d6843f338950ed41300793ec'
Submodule path 'cereal': checked out '1ee48e0110a46fbdd9db50ed89a38bb5a748cfcb'
Submodule path 'laika_repo': checked out 'ef21c612f4b0d68c790b4b1a6d637cd5fce7732e'
Submodule path 'opendbc': checked out 'a1582f5e28fe0df23b6821c907188be477aac11c'
Submodule path 'panda': checked out 'aed103d5372d1e5b3fb686d2aa8f111081b37fd0'
Submodule path 'rednose_repo': checked out '22f02dd650361e091f09f1ae94c5c96a9419c2d4'
Submodule path 'tinygrad_repo': checked out 'd8dda2af3afcef0bb772fff580cfa8b3eabf7f69'

real    0m17.467s
user    0m4.473s
sys     0m1.482s
batman@workstation-harald:~$ du -sh openpilot/
549M    openpilot/
`

**Pull request merged**
