### PR TITLE
Add instructions for running `ui` replays on environments with non-working hardware rendering setups such as WSL2

### PR DESCRIPTION
**Pull request by nelsonjchen**

### CODE REVIEW

**Comment by nelsonjchen** [comment]
ez link to the strange flap:

https://github.com/commaai/openpilot/runs/7681467587?check_suite_focus=true

**Comment by adeebshihadeh** [comment]
This doesn't seem openpilot related at all? Is this just a WSL2 thing?

**Comment by nelsonjchen** [comment]
Always happy to make instructions that enable a greater pool of users to run openpilot tooling. But alas, this is closed. Anyway, hopefully someone can find this on Google then.

**Comment by sshane** [comment]
Nice find! This works perfectly on my WSL2 Windows 11

**Pull request closed without merging**
