### PR TITLE
Qt: use the AbstractControl for multiple types of controls

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Nice work. Can we do this in the following order: get this merged as a minimal refactor with no functional changes (visual changes are fine), then we can rebase #20393 to get scrolling and descriptions?

**Comment by adeebshihadeh** [comment]
Hmm, maybe we can clean this up by using a Qt table or form layout?

**Comment by deanlee** [comment]
still working on the margins & paddings

**Comment by adeebshihadeh** [comment]
It doesn't really make sense for the line to be part of individual "control" widget. Ideally, a nice settings panel or layout class would handle that and the scroll area for us.

**Pull request merged**
