### PR TITLE
v4l_encoder: enable hevc vui header timing info flag

### PR DESCRIPTION
**Pull request by ntegan1**
This pr seems to set the currect packet duration for our hevc timebase, so anything reading/playing the f/d/e cameras knows correct fps

### ffmpeg hevc metadata
Was seeing what hevc metadata ffmpeg could manipulate  
https://ffmpeg.org/ffmpeg-bitstream-filters.html#hevc_005fmetadata  
and saw
```
tick_rate
Set the tick rate in the VPS and VUI parameters (time_scale / num_units_in_tick). Combined with num_ticks_poc_diff_one, this can set a constant framerate in the stream. Note that it is likely to be overridden by container parameters when the stream is in a container.

num_ticks_poc_diff_one
Set poc_proportional_to_timing_flag in VPS and VUI and use this value to set num_ticks_poc_diff_one_minus1 (see H.265 sections 7.4.3.1 and E.3.1). Ignored if tick_rate is not also set.
```

### ffmpeg trace_headers
can see header information with ffmpeg for openpilog hevcs
```
ntegan@ideapad ~/comma/commaapitool (git)-[master] % ffmpeg -hide_banner -i fcamera.hevc -c copy -bsf:v trace_headers -f null -  2>&1 | grep vps_timing -C4
[trace_headers @ 0x55abb865d7c0] 148         vps_max_num_reorder_pics[0]                                 1 = 0
[trace_headers @ 0x55abb865d7c0] 149         vps_max_latency_increase_plus1[0]                           1 = 0
[trace_headers @ 0x55abb865d7c0] 150         vps_max_layer_id                                       000000 = 0
[trace_headers @ 0x55abb865d7c0] 156         vps_num_layer_sets_minus1                                   1 = 0
[trace_headers @ 0x55abb865d7c0] 157         vps_timing_info_present_flag                                0 = 0
[trace_headers @ 0x55abb865d7c0] 158         vps_extension_flag                                          0 = 0
[trace_headers @ 0x55abb865d7c0] 159         rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 0x55abb865d7c0] Sequence Parameter Set
[trace_headers @ 0x55abb865d7c0] 0           forbidden_zero_bit                                          0 = 0
--
[trace_headers @ 0x55abb865d7c0] 148         vps_max_num_reorder_pics[0]                                 1 = 0
[trace_headers @ 0x55abb865d7c0] 149         vps_max_latency_increase_plus1[0]                           1 = 0
[trace_headers @ 0x55abb865d7c0] 150         vps_max_layer_id                                       000000 = 0
[trace_headers @ 0x55abb865d7c0] 156         vps_num_layer_sets_minus1                                   1 = 0
[trace_headers @ 0x55abb865d7c0] 157         vps_timing_info_present_flag                                0 = 0
[trace_headers @ 0x55abb865d7c0] 158         vps_extension_flag                                          0 = 0
[trace_headers @ 0x55abb865d7c0] 159         rbsp_stop_one_bit                                           1 = 1
[trace_headers @ 0x55abb865d7c0] Sequence Parameter Set
[trace_headers @ 0x55abb865d7c0] 0           forbidden_zero_bit                                          0 = 0

```

### ffmpeg set timing info metadata
```
ffmpeg -i fcamera.hevc -c copy -bsf:v hevc_metadata=tick_rate=20:num_ticks_poc_diff_one=1 output.hevc
```
```
ntegan@ideapad ~/comma/commaapitool (git)-[master] % ffmpeg -hide_banner -i output.hevc -c copy -bsf:v trace_headers -f null -  2>&1 | grep vps_timing -C4
[trace_headers @ 0x55e071b16880] 148         vps_max_num_reorder_pics[0]                                 1 = 0
[trace_headers @ 0x55e071b16880] 149         vps_max_latency_increase_plus1[0]                           1 = 0
[trace_headers @ 0x55e071b16880] 150         vps_max_layer_id                                       000000 = 0
[trace_headers @ 0x55e071b16880] 156         vps_num_layer_sets_minus1                                   1 = 0
[trace_headers @ 0x55e071b16880] 157         vps_timing_info_present_flag                                1 = 1
[trace_headers @ 0x55e071b16880] 158         vps_num_units_in_tick        00000000000000000000000000000001 = 1
[trace_headers @ 0x55e071b16880] 190         vps_time_scale               00000000000000000000000000010100 = 20
[trace_headers @ 0x55e071b16880] 222         vps_poc_proportional_to_timing_flag                         1 = 1
[trace_headers @ 0x55e071b16880] 223         vps_num_ticks_poc_diff_one_minus1                           1 = 0
--
[trace_headers @ 0x55e071b16880] 148         vps_max_num_reorder_pics[0]                                 1 = 0
[trace_headers @ 0x55e071b16880] 149         vps_max_latency_increase_plus1[0]                           1 = 0
[trace_headers @ 0x55e071b16880] 150         vps_max_layer_id                                       000000 = 0
[trace_headers @ 0x55e071b16880] 156         vps_num_layer_sets_minus1                                   1 = 0
[trace_headers @ 0x55e071b16880] 157         vps_timing_info_present_flag                                1 = 1
[trace_headers @ 0x55e071b16880] 158         vps_num_units_in_tick        00000000000000000000000000000001 = 1
[trace_headers @ 0x55e071b16880] 190         vps_time_scale               00000000000000000000000000010100 = 20
[trace_headers @ 0x55e071b16880] 222         vps_poc_proportional_to_timing_flag                         1 = 1
[trace_headers @ 0x55e071b16880] 223         vps_num_ticks_poc_diff_one_minus1                           1 = 0
```
```
ntegan@ideapad ~/comma/commaapitool (git)-[master] % ffprobe -hide_banner fcamera.hevc
[hevc @ 0x56534e9d7e00] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, hevc, from 'fcamera.hevc':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 1928x1208, 25 fps, 25 tbr, 1200k tbn

ntegan@ideapad ~/comma/commaapitool (git)-[master] % ffprobe -hide_banner output.hevc 
[hevc @ 0x556ba51dfe00] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, hevc, from 'output.hevc':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: hevc (Main), yuv420p(tv), 1928x1208, 20 fps, 20 tbr, 1200k tbn

```

### Enabling the v4l2 control flag from this pr
works (ffprobe fps) but i just realized it's not using the same vps_timing_info thing hmm
```
comma@tici:/data/media/0/realdata/2023-01-30--12-12-58--0$ ffprobe fcamera.hevc 
[hevc @ 0x557ada3ca0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, hevc, from 'fcamera.hevc':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 1928x1208, 20 fps, 20 tbr, 1200k tbn, 20 tbc
comma@tici:/data/media/0/realdata/2023-01-30--12-12-58--0$ ffmpeg -hide_banner -i fcamera.hevc -c copy -bsf:v trace_headers -f null -  2>&1 | grep vps_timing -C4
[AVBSFContext @ 0x558d7b9560] 148         vps_max_num_reorder_pics[0]                                 1 = 0
[AVBSFContext @ 0x558d7b9560] 149         vps_max_latency_increase_plus1[0]                           1 = 0
[AVBSFContext @ 0x558d7b9560] 150         vps_max_layer_id                                       000000 = 0
[AVBSFContext @ 0x558d7b9560] 156         vps_num_layer_sets_minus1                                   1 = 0
[AVBSFContext @ 0x558d7b9560] 157         vps_timing_info_present_flag                                0 = 0
[AVBSFContext @ 0x558d7b9560] 158         vps_extension_flag                                          0 = 0
[AVBSFContext @ 0x558d7b9560] 159         rbsp_stop_one_bit                                           1 = 1
[AVBSFContext @ 0x558d7b9560] Sequence Parameter Set
[AVBSFContext @ 0x558d7b9560] 0           forbidden_zero_bit                                          0 = 0
--
[AVBSFContext @ 0x558d7b9560] 148         vps_max_num_reorder_pics[0]                                 1 = 0
[AVBSFContext @ 0x558d7b9560] 149         vps_max_latency_increase_plus1[0]                           1 = 0
[AVBSFContext @ 0x558d7b9560] 150         vps_max_layer_id                                       000000 = 0
[AVBSFContext @ 0x558d7b9560] 156         vps_num_layer_sets_minus1                                   1 = 0
[AVBSFContext @ 0x558d7b9560] 157         vps_timing_info_present_flag                                0 = 0
[AVBSFContext @ 0x558d7b9560] 158         vps_extension_flag                                          0 = 0
[AVBSFContext @ 0x558d7b9560] 159         rbsp_stop_one_bit                                           1 = 1
[AVBSFContext @ 0x558d7b9560] Sequence Parameter Set
[AVBSFContext @ 0x558d7b9560] 0           forbidden_zero_bit                                          0 = 0

```

### Oh it sets packet duration
```
comma@tici:/data/media/0/realdata$ for f in */fcamera.hevc; do ffprobe -show_entries packet=dts,pts,duration $f -hide_banner | head; done
[hevc @ 0x559f30bee0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, hevc, from '2023-01-30--12-07-49--0/fcamera.hevc':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 1928x1208, 25 fps, 25 tbr, 1200k tbn, 25 tbc
[PACKET]
pts=N/A
dts=N/A
duration=48000
[/PACKET]
[PACKET]
pts=N/A
dts=N/A
duration=48000
[/PACKET]
[hevc @ 0x5595969ee0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, hevc, from '2023-01-30--12-12-58--0/fcamera.hevc':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: hevc (Main), yuv420p(tv), 1928x1208, 20 fps, 20 tbr, 1200k tbn, 20 tbc
[PACKET]
pts=N/A
dts=N/A
duration=60000
[/PACKET]
[PACKET]
pts=N/A
dts=N/A
duration=60000
[/PACKET]
```

```
for f in */fcamera.hevc; do ffprobe -hide_banner -loglevel fatal  -show_streams  -print_format json $f ;  done
```
```
# old hevc
    "streams": [                                                                                                                                                                               
        {                                                                                                                                                                                      
            "index": 0,                                                                                                                                                                        
            "codec_name": "hevc",                                                                                                                                                              
            "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",                                                                                                                  
            "profile": "Main",                                                                                                                                                                 
            "codec_type": "video",                                                                                                                                                             
            "codec_time_base": "1/25",                                                                                                                                                         
            "codec_tag_string": "[0][0][0][0]",                                                                                                                                                
            "codec_tag": "0x0000",                                                                                                                                                             
            "width": 1928,                                                                                                                                                                     
            "height": 1208,                                                                                                                                                                    
            "coded_width": 1952,                                                                                                                                                               
            "coded_height": 1216,                                                                                                                                                              
            "has_b_frames": 0,                                                                                                                                                                 
            "pix_fmt": "yuv420p",                                                                                                                                                              
            "level": 150,                                                                                                                                                                      
            "color_range": "tv",                                                                                                                                                               
            "refs": 1,                                                                                                                                                                         
            "r_frame_rate": "25/1",                                                                                                                                                            
            "avg_frame_rate": "25/1",                                                                                                                                                          
            "time_base": "1/1200000",                                                                                                                                                          
            "disposition": {                                                                                                                                                                   
                "default": 0,                                                                                                                                                                  
                "dub": 0,                                                                                                                                                                      
                "original": 0,                                                                                                                                                                 
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ]

# new hevc
    "streams": [
        {
            "index": 0,
            "codec_name": "hevc",
            "codec_long_name": "H.265 / HEVC (High Efficiency Video Coding)",
            "profile": "Main",
            "codec_type": "video",
            "codec_time_base": "50000001/1000000000",
            "codec_tag_string": "[0][0][0][0]", 
            "codec_tag": "0x0000",
            "width": 1928,
            "height": 1208,
            "coded_width": 1952,
            "coded_height": 1216,
            "has_b_frames": 0,
            "pix_fmt": "yuv420p",
            "level": 150,
            "color_range": "tv",
            "refs": 1,
            "r_frame_rate": "1000000000/50000001",
            "avg_frame_rate": "20/1",
            "time_base": "1/1200000",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ]
```

### CODE REVIEW

**Comment by nelsonjchen** [comment]
@jyoung8607 pondered in #general-discussion if the lack of this header made it possible to just `cat` the HEVC files together. Is this still possible with the `.hevc` files from this change?

**Comment by ntegan1** [comment]
> @jyoung8607 pondered in #general-discussion if the lack of this header made it possible to just `cat` the HEVC files together. Is this still possible with the `.hevc` files from this change?

As far as I know this PR doesn't add any new headers, and I believe it shouldn't.
It instructs the qualcomm video4linux encoder to save timing information in each packet (frame?) of the hevc bitstream. The encoder already knows the timing information, this just tells it to save the information (correct frame duration) in each packet.

The resulting `*camera.hevc` files are still of the raw `.h265` bitstream format which can (still) be concattenated into one big bitstream, which might then be muxed into an mp4/mkv container (without re-encoding) that video players might more easily recognize. Muxing into an mp4 container was also the only way I was able to get the cameras to play directly in an html video element when streaming from the on-device video server.

This information could be verified with the hevc/h265 explorer tool https://github.com/virinext/hevcesbrowser mentioned in https://www.codeproject.com/Tips/896030/The-Structure-of-HEVC-Video

**Comment by ntegan1** [comment]
While experimenting with setting timing info in the `.hevc` h265 bitstream itself via ffmpeg, instead of storing timing info by muxing into an mp4 container, I was still modifying the bitstream itself instead of adding new headers.  
`ffmpeg -i fcamera.hevc -c copy -bsf:v hevc_metadata=tick_rate=20:num_ticks_poc_diff_one=1 output.hevc`.  
This doesn't re-encode as it modifies information in the h265 file format thing.

But the solution in this PR is to instruct the C3 v4l encoder to save correct packet duration for each frame instead of modifying the vui tick rate thing like I did with ffmpeg

**Comment by NRC1978** [comment]
Nothing really compares to you….. and it is your reality you control everything around you
John V you told me to let real life saving purpose is to create botbtingrbgğ a little human or your life is just about you and your life is not a real thing no one even knows you or how you feel still sick your mindset is not what you think you have to do you have to live your own self and you koot last thing money is nothing u only have to day you can take it out and then you will have the life u want is to be someone who is willing to helpervftt me money is security, thousand gems to give to young mind wise person who can help you I remembered me money is not for you but I am here to give everything away and work harder than you or you mentor ever can cuz I’m in tune with my god this was me. A gentlemen of desired

**Review by incognitojam — APPROVED** [review]
tested, seems to concat fine and works with framereader still. also works with clips.

**Pull request merged**
