### PR TITLE
Lexus LC 2024

### PR DESCRIPTION
**Pull request by nelsonjchen**
**Checklist**

- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [X] route with openpilot: `4765fbbf59e3cd88/2024-02-04--20-20-03`
- [x] route with stock system: `4765fbbf59e3cd88|2024-01-30--14-31-23`
- [X] car harness used (if comma doesn't sell it, put N/A): Toyota A

### CODE REVIEW

**Comment by nelsonjchen** [comment]
Need to add a more anonymous route that can be fully public

**Comment by sshane** [comment]
> Need to add a more anonymous route that can be fully public

@jnewb1 do we strip new routes.py routes yet?

**Comment by nelsonjchen** [comment]
In the meantime, I've asked the owner to purposefully make an anonymousey route:

https://discord.com/channels/469524606043160576/1194100053879558225/1204160481883979887

**Comment by nelsonjchen** [comment]
OK, we produced a good public-able route. Please copy `4765fbbf59e3cd88/2024-02-06--17-45-32` to the bucket.

**Pull request merged**
