### PR TITLE
Fingerprint for Hyundai Santa Fe 2019 Europe

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

**Comment by sshane** [comment]
@evdoks are you still around? can you connect your device to WiFi to upload some logs? Your engine is missing, preventing exact fingerprint matching

**Comment by evdoks** [comment]
@sshane I've shared a few more drives:
* [092ef1cc055c6354|2023-01-05--17-49-21](https://useradmin.comma.ai/?onebox=092ef1cc055c6354%7C2023-01-05--17-49-21)
* [092ef1cc055c6354|2023-01-04--15-57-07](https://useradmin.comma.ai/?onebox=092ef1cc055c6354%7C2023-01-04--15-57-07)

The thing with the engine is that I do not see any entries for the engine that have `brand: hyundai`. It is either `volkswagen` or `subaru` by some reason in all of the drives I've done:
```
{'address': 2016,
 'brand': 'subaru',
 'bus': 1,
 'ecu': 'engine',
 'fwVersion': b'71TMC4NAICEIR203',
 'request': [b'>\x00', b'"\xf1\x82'],
 'responseAddress': 2024,
 'subAddress': 0},
```
```
 {'address': 2016,
 'brand': 'volkswagen',
 'bus': 1,
 'ecu': 'engine',
 'fwVersion': b'\xf1\x8971TMC4NAICEIR203\xf1\x8271TMC4NAICEIR203',
 'request': [b'"\xf1\x87\xf1\x89\xf1\x82'],
 'responseAddress': 2024,
 'subAddress': 0},
```

**Comment by evdoks** [comment]
@sshane may I ask you why did you remove one of the transmission entries in 250544214f7aa58efbd59ac9fa796a4b901370d8? Is one enough?

**Comment by sshane** [comment]
> @sshane may I ask you why did you remove one of the transmission entries in [2505442](https://github.com/commaai/openpilot/commit/250544214f7aa58efbd59ac9fa796a4b901370d8)? Is one enough?

Yep, we have two queries which return the same information effectively

**Comment by sshane** [comment]
Can you connect your device to WiFi to let the logs upload?

**Comment by evdoks** [comment]
@sshane it is connected. There is a bunch of logs for dongle id `092ef1cc055c6354`

**Comment by sshane** [comment]
@evdoks can you drive on master and upload logs?

**Comment by evdoks** [comment]
@sshane Here is a short drive on master: `092ef1cc055c6354|2023-02-05--19-06-24--0` with logs uploaded (in dashcam mode).

**Comment by evdoks** [comment]
@sshane anything else you need for this PR? Would be nice to have the new fingerprint in 0.9.1.

**Comment by sshane** [comment]
Your car is still fuzzy fingerprinting due to it not supporting our engine query, but with the improvements to fuzzy FP coming soon, that should be fine to merge now and get you in 0.9.1.

**Pull request merged**
