### PR TITLE
Lexus rx 350

### PR DESCRIPTION
**Pull request by wocsor**
i can never do it in just one commit. at least it works nicely though! @hellojakefromstatefarm on Discord has the car, but i do not yet have a drive because he does not have his device paired and can't send me a Cabana.

### CODE REVIEW

**Comment by rbiasini** [comment]
thanks @wocsor . I would like to merge this in. Any chance to share a route?

**Comment by ooitsme** [comment]
I have a 2017 RX350 with all the Openpilot hardware. How can I help?

**Comment by ErichMoraga** [comment]
@ooitsme Meet us in Discord.

**Comment by hkowald** [comment]
Located in Cali and have a 2016 rx350. Willing to help in anyway possible.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Pull request closed without merging**
