### PR TITLE
Car Port: 2020 Kia Niro EV

### PR DESCRIPTION
**Pull request by nickn17**
***** Template: Car port Kia Niro EV *****

**Checklist**
- [x] added to README
- [x] test route added to [test_car_models](../../selfdrive/test/test_car_models.py)
- [x] route with openpilot: 50c6c9b85fd1ff03|2020-10-26--17-56-06
- [x] route with stock system: 50c6c9b85fd1ff03|2020-10-25--11-25-27

### CODE REVIEW

**Comment by nickn17** [comment]
Pls where could be a problem. Check test car models failed because blob not found. 
https://commadataci.blob.core.windows.net/openpilotci/50c6c9b85fd1ff03/2020-10-26--17-56-06/0/rlog.bz2
But it's available under my.comma.ai profile.

**Comment by adeebshihadeh** [comment]
The test was failing because it needs to be manually moved into a special bucket. Thanks for the PR!

**Comment by VirtuallyChris** [comment]
What harness do you use? @nickn17

**Comment by nickn17** [comment]
> What harness do you use? @nickn17

I have older custom made. Mdemin ordered wrong Hyundai E for his 2020 Niro EV, so he must to move 2 pins to make Hyundai F.  It seems Hyundai F is right for 2020 Kia Niro EV.

**Comment by gnarf0815** [comment]
I bought the Hyundai F for my e-Niro - it's the right one.

**Pull request merged**
