### PR TITLE
Update values.py in honda and toyota

### PR DESCRIPTION
**Pull request by ucolchen**
add fingerprint for 2019 TOYOTA Highlander XLE

### CODE REVIEW

**Comment by legonigel** [comment]
Can you please provide a link for a drive with the car in stock mode? Feel free to PM me on discord with the links.

**Comment by legonigel** [comment]
Can you please rebase this PR on devel? This will allow the new fingerprint tests to run.

**Comment by ucolchen** [comment]
Hi, @legonigel, i think this PR is base on devel. i saw:
Update values.py in honda and toyota #571
 Open	ucolchen wants to merge 2 commits into commaai:devel from ucolchen:devel
is it right? sorry that i'm totally newbie in github
thanks,

2019 honda ody exl fingerprint
57: 3, 148: 8, 228: 5, 229: 4, 316: 8, 342: 6, 344: 8, 380: 8, 399: 7, 411: 5, 419: 8, 420: 8, 427: 3, 432: 7, 450: 8, 463: 8, 464: 8, 476: 4, 490: 8, 506: 8, 542: 7, 545: 6, 597: 8, 662: 4, 773: 7, 777: 8, 780: 8, 795: 8, 800: 8, 804: 8, 806: 8, 808: 8, 817: 4, 819: 7, 821: 5, 825: 4, 829: 5, 837: 5, 856: 7, 862: 8, 871: 8, 881: 8, 882: 4, 884: 8, 891: 8, 892: 8, 905: 8, 923: 2, 927: 8, 929: 8, 963: 8, 965: 8, 966: 8, 967: 8, 983: 8, 985: 3, 1029: 8, 1036: 8, 1052: 8, 1064: 7, 1088: 8, 1089: 8, 1092: 1, 1108: 8, 1110: 8, 1125: 8, 1296: 8, 1302: 8, 1445: 8, 1600: 5, 1601: 8, 1612: 5, 1613: 5, 1614: 5, 1615: 8, 1616: 5, 1619: 5, 1623: 5, 1668: 5

log w/ stock on:
https://community.comma.ai/cabana/?route=0c0b9b01c32d72da%7C2019-03-31--00-02-48&max=2&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2F0c0b9b01c32d72da%2F2640c81c7c528ba7da0cfb4a042e0532_2019-03-31--00-02-48

**Comment by rbiasini** [comment]
@ucolchen do you still have fingerprint issues? looked into the drive you posted and it seems to not contain the can messages I expect. Probably panda wasn't connected properly. If you tell me your dongle ID, I can get the fingerprint from there as well.

**Comment by oremax** [comment]
I am a user of a Toyota Prius 2017 car in Japan.
It uses gray pandas and giraffes, and even with OpenPilot0.6.5, 
it could be used comfortably with plug and play without acquiring FingerPrint.

After purchasing and installing a black panda
It becomes dash cam mode and dashcam mode with unsupported car is displayed from EON
Plug and Play is no longer available.
Did BlackPanda and GrayPanda change the interpretation of FingerPrint specific processing,

Enable openpilot switchoff with the black panda connected
I got FingerPrint in DSUON state. valuesCAR.PRIUS # with ipas in values.py modified to the following
Even if DSUOFF was enabled, OpenPilot could be operated without any problem if 
Enable Communty Features was ON.

It may just be caused by Prius-specific equipment.
Even with the same Prius, it may or may not occur due to changes in the specifications at the time of car equipment creation.
It is good that you don't need to edit values.py after updating by merging with the existing fingerPrint. This may be a problem solved by 
FingerPrint2.0, but I will report it.

DSUON　
number of messages 102:
fingerprint 36: 8, 37: 8, 166: 8, 170: 8, 180: 8, 295: 8, 296: 8, 426: 6, 452: 8, 466: 8, 467: 8, 550: 8, 552: 4, 560: 7, 562: 6, 581: 5, 608: 8, 610: 8, 614: 8, 643: 7, 658: 8, 713: 8, 740: 5, 742: 8, 743: 8, 800: 8, 810: 2, 814: 8, 825: 8, 829: 2, 830: 7, 835: 8, 836: 8, 845: 5, 861: 8, 863: 8, 869: 7, 870: 7, 871: 2, 875: 8, 898: 8, 913: 8, 918: 8, 921: 8, 933: 8, 944: 8, 945: 8, 950: 8, 951: 8, 953: 8, 955: 8, 956: 8, 971: 7, 975: 5, 993: 8, 999: 7, 1000: 8, 1001: 8, 1017: 8, 1020: 8, 1041: 8, 1042: 8, 1044: 8, 1056: 8, 1057: 8, 1059: 1, 1071: 8, 1082: 8, 1083: 8, 1084: 8, 1085: 8, 1086: 8, 1114: 8, 1130: 8, 1132: 8, 1161: 8, 1162: 8, 1163: 8, 1175: 8, 1227: 8, 1228: 8, 1235: 8, 1279: 8, 1552: 8, 1553: 8, 1556: 8, 1557: 8, 1568: 8, 1570: 8, 1571: 8, 1572: 8, 1595: 8, 1681: 8, 1777: 8,1779: 8, 1904: 8, 1912: 8, 1990: 8, 1998: 8, 2015: 8, 2016: 8, 2024: 8

Cabanalink running OpenPilot with BlackPanda DSUOFF

https://my.comma.ai/cabana/?route=a42e558b3f03ed35%7C2019-12-24--11-15-09&exp=1608770190&sig=0rX5%2BXnfguXY7mM5svWM6GtBoZwvca%2BOXBtj6YrqVMY%3D&max=48&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fa42e558b3f03ed35%2F59e14b769e6c31e96fc9a094f2f54e6f_2019-12-24--11-15-09

Device: EON Gold
OpenPilotVersion: 0.7 devel 
Car make/model Toyota prius 2017 Japanese version

**Comment by ErichMoraga** [comment]
You'll need to submit a Cabana share link of it driven with the DSU connected.

**Comment by oremax** [comment]
Test drive log with DSU connected.
please confirm.

https://my.comma.ai/cabana/?route=a42e558b3f03ed35%7C2019-12-25--10-58-33&exp=1608855118&sig=T3nAqtRYuELffNvUJ4aThbInKaJH2szZ0YeMCcjX25M%3D&max=44&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fa42e558b3f03ed35%2Fa80da24afd496e47b6854820fbc02ab0_2019-12-25--10-58-33

**Comment by ErichMoraga** [comment]
Confirmed 343 present.

**Comment by ErichMoraga** [comment]
343 present on more busses, so yeah, DSU connected now.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Pull request closed without merging**
