### PR TITLE
qt/util: new function getDongleId

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
Think it makes more sense to return an `std::optional<QString>`. Now you still have to check if it's empty, so there is not much benefit to calling the `is_valid_dongle_id` function.

**Comment by pd0wm** [comment]
Looks much better. Think this is an improvement over the old code since it forces us to think about the case where there is no dongle id.

**Comment by pd0wm** [comment]
I'm removing the static caching. Will cause some unexpected behavior if you're debugging/testing stuff around dongleIds.

**Comment by deanlee** [comment]
OK. cache is really not necessary

**Pull request merged**
