### PR TITLE
fix micd input device

### LINKED ISSUE #26935: micd sometimes crashes on startup

### PR DESCRIPTION
**Pull request by incognitojam**
closes #26935

- removed "sysdefault" and got a different error
- seems related: https://github.com/spatialaudio/python-sounddevice/issues/147
- removing import from top level seems to fix

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
> * removing import from top level seems to fix

let's make sure we understand why this fixes it. are you sure it's not just another race condition?

**Comment by incognitojam** [comment]
I can't reproduce the second error anymore

**Comment by incognitojam** [comment]
nvm, it happens when manager starts micd

**Comment by adeebshihadeh** [comment]
> nvm, it happens when manager starts micd
> 
> Theory is that sounddevice/portaudio is initialised (when micd is "pre imported") in a different ~thread~ process(?) to the one where micd runs. I'm not sure why that didn't cause issues when the device was "sysdefault" though.

Read the issues on their repo; your fix makes the most sense. Just make sure to leave a good comment about why it's there.

**Comment by incognitojam** [comment]
Also minimal reproduction outside openpilot:
```python3
comma@tici:/data/openpilot$ python3
Python 3.8.10 (default, Nov 10 2022, 06:12:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ^C
KeyboardInterrupt
>>> import sounddevice as sd
from multiprocessing import Process

def micd_thread():
  with sd.InputStream(channels=1, samplerate=44100):
    print("micd stream started")

p = Process(target=micd_thread)
p.start()
>>> >>> >>> ... ... ... >>> >>> >>> Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2839
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "<stdin>", line 2, in micd_thread
  File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Illegal combination of I/O devices [PaErrorCode -9993]
```

**Pull request merged**
