### PR TITLE
cabana: fix y axis precision

### PR DESCRIPTION
**Pull request by deanlee**
| Before  | After |
| ------------- | ------------- |
| Screenshot from 2023-02-11 05-34-50  | Screenshot from 2023-02-11 05-34-08  |

### CODE REVIEW

**Comment by pd0wm** [comment]
@deanlee Removing this broke plotting constants and signals that change between 0 and 1. Those always show ellipsis on the y axis now.

**Comment by deanlee** [comment]
@pd0wm, I haven't been able to reproduce the problem, can you give me a min and max values ​​that might be causing the problem?

**Comment by deanlee** [comment]
@pd0wm Is your qt version 6.0+?

**Comment by pd0wm** [comment]
My Qt version is 5.15.8, running on i3 on arch. But I'm seeing the same problems on MacOS.

Screenshot from demo route on latest master build.
2023-02-17-103425_581x929_scrot

**Comment by deanlee** [comment]
I'm still not sure how to fix this bug after doing a lot of checking since I can't reproduce it :(

**Comment by deanlee** [comment]
can it be fixed by call `axis_y->setLabelFormat(QString("%.%1f").arg(n));` after line 572 ?:

https://github.com/deanlee/openpilot/blob/11e073c1e96e08331675b804d8fbfd9370695200/tools/cabana/chartswidget.cc#L592

>    y_label_width = qMax(fm.width(QString::number(min_y, 'f', n)), fm.width(QString::number(max_y, 'f', n))) + 20;  // left margin 20
    axis_y->setLabelFormat(QString("%.%1f").arg(n));

**Comment by deanlee** [comment]
I’m glad it worked out :D

**Pull request merged**
