### PR TITLE
soundd/micd: increase stream buffer size

### PR DESCRIPTION
**Pull request by jnewb1**
audio distortion issues seem to be related to a sample underflow:
```[94.655242] sounddevice.py:2687 - : soundd stream over/underflow: output underflow```
```[548.570647] sounddevice.py:2687 - : soundd stream over/underflow: output underflow```
```[71004.600648] sounddevice.py:2687 - : soundd stream over/underflow: output underflow```

4096 = ~100ms of buffer (4096/48100), which should help to stabilize the output (default was 416)

also significantly reduces cpu usage for mic and soundd

instances of distortion:
```
2dc88074614b9774|2023-12-08--09-09-46
5e75f47a17ee2815|2023-12-10--12-55-21
1d990e156bd30fe3|2023-12-11--10-19-45
```

### CODE REVIEW

**Comment by jnewb1** [comment]
```1d990e156bd30fe3|2023-12-11--10-19-45```

```
[71003.493715] MAIN 3736 ModemManager - <dbg> [1702320076.598118] [modem0] RSSI (LTE): -46 dBm
[71003.493824] MAIN 3736 ModemManager - <dbg> [1702320076.598160] [modem0] RSSI: -46 dBm --> 100%
[71003.493930] MAIN 3736 ModemManager - <dbg> [1702320076.598353] [modem0] signal quality updated (100)
[71003.494037] MAIN 3736 ModemManager - <dbg> [1702320076.598435] [modem0] skipping extended signal information
...
[71004.600648] sounddevice.py:2687 - : soundd stream over/underflow: output underflow
```

```5e75f47a17ee2815|2023-12-10--12-55-21```
```
[92.473416] MAIN 3683 ModemManager - <dbg> [1702234574.378839] [modem0] not yet registered in a 3GPP network... will recheck soon
...
[94.655242] sounddevice.py:2687 - : soundd stream over/underflow: output underflow
```

```2dc88074614b9774|2023-12-08--09-09-46```

```
[548.062164] MAIN 3067 ModemManager - <dbg> [1702055846.302547] [modem0] 3GPP cell id updated: '055D9C02->055D9C03'
[548.062269] MAIN 3067 ModemManager - <dbg> [1702055846.302593] [modem0] 3GPP location updated (MCCMNC: '310260', location area code: '0000', tracking area code: '002F12', cell ID: '055D9C03')
...
[548.570647] sounddevice.py:2687 - : soundd stream over/underflow: output underflow
```

also seem to correspond to modemmanager updates. you also get camera errors near these modemmanager updates too

```
kernel - CAM_ERR: CAM-CDM: cam_hw_cdm_submit_gen_irq: 364 cdm test remove bl tag 16 old ctx ffffff83e1187958 cookie 9155 new ctx ffffff83e117e8d8 cookie 9167
```

```
kernel - CAM_ERR: CAM-CDM: cam_hw_cdm_submit_gen_irq: 364 cdm test remove bl tag 61 old ctx ffffff8fd3d87958 cookie 1038 new ctx ffffff8fd3d83118 cookie 1051
```

```
[71003.992710] MAIN 0 kernel - CAM_ERR: CAM-CDM: cam_hw_cdm_submit_gen_irq: 364 cdm test remove bl tag 23 old ctx ffffff905097e8d8 cookie 25792 new ctx ffffff905099e298 cookie 25805
[71004.492722] MAIN 0 kernel - CAM_ERR: CAM-CDM: cam_hw_cdm_submit_gen_irq: 364 cdm test remove bl tag 59 old ctx ffffff905099e298 cookie 25799 new ctx ffffff9050999a58 cookie 25811
```

perhaps something with interrupts?

**Comment by adeebshihadeh** [comment]
That makes sense. Is there a relevant IRQ we can affine away from core 0? core 0 is the default for IRQs on ARM, and we tend to affine things to either a specific core that a corresponding process runs on or core 1 for everything else we care about.

**Comment by jnewb1** [comment]
I'm assuming we'd probably want the modem off cpu0 (qcom,glink-smem-native-xprt-modem?)
image

seems like sensord is on cpu0 when it looks like its supposed to be scheduled on cpu1?
image

https://github.com/commaai/openpilot/blob/3a707082286cec9c93280c202ebbf5d5b89aac94/system/sensord/sensors_qcom2.cc#L134-L137

cdsp and wlan are also cpu0
image

**Comment by jnewb1** [comment]
going to merge this because we want a larger buffer anyway, but I will continue looking at the interrupt stuff

**Pull request merged**
