### PR TITLE
Updated FW for Skoda Superb III 2016

### PR DESCRIPTION
**Pull request by tivvit**
I have added my FW fingerprints for Skoda Superb III 2016 and tested that it works for my car.

### CODE REVIEW

**Comment by sshane** [comment]
Can you add your dongle id?

**Comment by sshane** [comment]
Any updates @tivvit?

**Comment by tivvit** [comment]
Hi, sorry for the delay. The dongle id is: fad463f1498cfb3f

**Comment by sshane** [comment]
Thanks!

**Pull request merged**
