### PR TITLE
ui: set dialog confirm button text

### PR DESCRIPTION
**Pull request by incognitojam**
|Dialog|New|
|---|---|
|Training guide|Screenshot from 2022-11-04 16-18-10|
|Reset calibration|Screenshot from 2022-11-04 16-18-06|
|Reboot|Screenshot from 2022-11-04 16-19-12|
|Power off|Screenshot from 2022-11-04 17-00-38|
|Forget wifi network|Screenshot from 2022-11-04 16-19-31|
|Regulatory|Screenshot from 2022-11-04 17-01-04|

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Let's keep these short - "Review Training" -> "Review". Let's also make the action button the same blue we use in places like the branch switcher.

**Comment by incognitojam** [comment]
Want the Power Off confirm to be red?

**Comment by adeebshihadeh** [comment]
Nah, we don't have a clean way to do that right now. Let's keep it simple for now.

**Comment by incognitojam** [comment]
Should the confirm button remain grey for the single button dialogs or is blue good here too?
Screenshot from 2022-11-04 17-01-04

**Comment by adeebshihadeh** [comment]
LGTM

**Pull request merged**
