### PR TITLE
Tesla AP2 port

### PR DESCRIPTION
**Pull request by robbederks**
Port for AP2 model S

Works well, but will be merged as dashcam only due to not having user steer torque blending.

**Checklist**
- [x] added to README
- [x] test route added to [test_routes](../../selfdrive/test/test_routes.py)

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Should we get this in as dashcam only for now?

**Comment by robbederks** [comment]
> Should we get this in as dashcam only for now?

Yes, it's pretty stable now. I very rarely still fault my cruise control with disengage on gas (like once every 100+ times, pretty rare), haven't figured out why that happens yet.
For a dashcam port, do we also need the routes for in CI?

**Comment by adeebshihadeh** [comment]
I usually get them to make sure we have a preserved route for the car as a reference, but not necessary in this case.

**Comment by robbederks** [comment]
Ok, will get this cleaned up and merged.

**Pull request merged**
