### PR TITLE
Update fingerprints.py

### PR DESCRIPTION
**Pull request by arne182**
Consolidated my fingerprint and removed duplicates and ordered the fingerprint for the RAV4H. Double Checked.

### CODE REVIEW

**Comment by rbiasini** [comment]
yeah, looks good. Nice cleanup, no substantial changes.

**Comment by energee** [comment]
@rbiasini The new fingerprint should longer, not shorter.

**Comment by rbiasini** [comment]
@energee , they are exactly the same, but in the older one there were duplicates. Wondering why the linter did not see this before.

**Comment by energee** [comment]
Ok, that makes sense!

**Pull request merged**
