### PR TITLE
replace nvgFontFace with nvgFontFaceId

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by geohot** [comment]
Why is this better?

**Comment by deanlee** [comment]
> Why is this better?
small performance boost.
nvgFontFace call fonsGetFontByName to get the font id which we already have.
int fonsGetFontByName(FONScontext* s, const char* name)
{
	int i;
	for (i = 0; i < s->nfonts; i++) {
		if (strcmp(s->fonts[i]->name, name) == 0)
			return i;
	}
	return FONS_INVALID;
}

**Comment by deanlee** [comment]
small performance boost.
nvgFontFace call fonsGetFontByName to get the font id which we already have.
int fonsGetFontByName(FONScontext* s, const char* name)
{
int i;
for (i = 0; i < s->nfonts; i++) {
if (strcmp(s->fonts[i]->name, name) == 0)
return i;
}
return FONS_INVALID;
}

**Comment by deanlee** [comment]
small performance boost.
nvgFontFace call fonsGetFontByName to get the font id which we already have.
int fonsGetFontByName(FONScontext* s, const char* name)
{
	int i;
	for (i = 0; i < s->nfonts; i++) {
		if (strcmp(s->fonts[i]->name, name) == 0)
			return i;
	}
	return FONS_INVALID;
}

**Comment by deanlee** [comment]
Removed unnecessary function call. 

nvgFontFace call fonsGetFontByName to get the font id which we already have.

`int fonsGetFontByName(FONScontext* s, const char* name)
{
	int i;
	for (i = 0; i < s->nfonts; i++) {
		if (strcmp(s->fonts[i]->name, name) == 0)
			return i;
	}
	return FONS_INVALID;
}`

**Comment by deanlee** [comment]
dd
`https://github.com/memononen/nanovg/blob/2bead03bea43b2418060aaa154f972829995e663/src/fontstash.h#L981`

**Comment by deanlee** [comment]
Remove unnecessary function call. 
nvgFontFace call fonsGetFontByName to get the font id which we already have.
https://github.com/commaai/openpilot/blob/54f34abdb36cbf7a43b3de1ba8765a972413179d/phonelibs/nanovg/nanovg.c#L2328-L2332
https://github.com/commaai/openpilot/blob/54f34abdb36cbf7a43b3de1ba8765a972413179d/phonelibs/nanovg/fontstash.h#L942-L950

**Pull request merged**
