### PR TITLE
VW: 2018 Audi RS3 FW

### PR DESCRIPTION
**Pull request by tanotaru**
Added 2018 Audi RS3 ECU Firmwares to values.py file.  

Tested fork and car is now recognized.  OpenPilot works normally now.

### CODE REVIEW

**Comment by sshane** [comment]
Can you add your dongle id? It will be in device settings.

**Comment by sshane** [comment]
Any updates @tanotaru

**Comment by tanotaru** [comment]
Where do you need it added at?

**Comment by sshane** [comment]
Just leave a comment here is fine.

**Comment by sshane** [comment]
@tanotaru can you get that posted?

**Comment by jyoung8607** [comment]
image

**Pull request merged**
