### PR TITLE
more car info -> car docs

### PR DESCRIPTION
**Pull request by jnewb1**

### CODE REVIEW

**Comment by sshane** [comment]
what about when referring to one `CarDocs`  instance we call it `car_doc` and `CarDoc`?

**Comment by sshane** [comment]
CarDocs is fine if that looks to awkward. Let's rename singular car_docs to car_doc though (expanded car_documentation makes sense)

**Comment by adeebshihadeh** [comment]
Singular "Doc" doesn't make sense to me. "Docs" generally means "documentation".

**Comment by sshane** [comment]
@jnewb1 again we need to check for references carefully, this broke the website car doc generation. We should also surface that better, but I recall it's not straightforward to alert on GitHub red check marks?

**Pull request merged**
