### PR TITLE
Add fingerprint for 2017 VW Tiguan

### PR DESCRIPTION
**Pull request by ghost**
Cannot yet confirm openpilot works on the car, but it is from the same generation as the 2020 Tiguan that is already supported, so I don't see any reason it shouldn't work.
Route: 
650b1e4383a9baf2|2021-04-16--09-16-00

### CODE REVIEW

**Comment by jyoung8607** [comment]
It should, those SW part numbers match known MQB vehicles.

If this is merged, use caution if/when adding to the README, and don't add it to the comma compatibility checker. They are both US-market-centric, and 2016-2018 Tiguans are vehicles where market matters.

- Everywhere but USA got the openpilot-supported MQB Mk2 Tiguan starting with MY2016.
- USA got the MQB Mk2 Tiguan starting with MY2018 *except for the special carryover 2018-only Tiguan Limited*.
- The USA 2016-2017 Tiguan and 2018 Tiguan Limited are still PQ Mk1. Untested, but they probably work with commaai/openpilot#20674.

This is exactly as strange and confusing as it sounds.
https://en.wikipedia.org/wiki/Volkswagen_Tiguan

**Comment by grekiki** [comment]
Looks like adding PQ simplifies things :) Yeah this is an EU Tiguan with 2.0 TDI DSG configuration.

**Comment by pd0wm** [comment]
Let me know when you can confirm openpilot support so we can merge it!

**Comment by adeebshihadeh** [comment]
If this won't be tested anytime soon, let's close the PR until it's been tested.

**Comment by DoskJS** [comment]
I have a 2018 VW Tiguan SE 4motion, would my car be useful for testing this? @jyoung8607

**Comment by jyoung8607** [comment]
2018+ Tiguan is already fully supported by stock openpilot, provided it has factory Lane Assist. Unfortunately, for Tiguan I think that's bundled with SEL and above. Your 2018 SE can still be made to work, but needs a community built harness (due to no factory camera) and a community-supported fork of openpilot.

**Pull request closed without merging**
