### PR TITLE
Add missing RAV4H_TSS2_2022 engine f/w

### PR DESCRIPTION
**Pull request by ErichMoraga**
`@Rocks#8913` 2021 RAV4 Hybrid (Italy)  DongleID/route 081a1d5f242294c0|2022-07-10--18-37-26

Continental camera p/n 8646C-0R090...
https://discord.com/channels/469524606043160576/524327905937850394/995781101903679558

### CODE REVIEW

**Comment by sshane** [comment]
Are we sure it's a 2021? I can't decode the VIN on most sites

**Comment by ErichMoraga** [comment]
Right, I mentioned that to him in the Discord... 6-th digit issue w/ VIN...
https://discord.com/channels/469524606043160576/524327905937850394/995778928650235944

In another recent firmware submission, I also had to really poke the fellow to verify his car was actually a 2022, instead of a 2021.  Anyway, don't forget the car in question is in Italy, where the cars could be more unusual in general.

**Comment by sshane** [comment]
Same thing with an Austrailian car. Owner swore up and down it was a 2021 but when looking at the VIN, it conformed to 2022 some regulations in AUS, along with it being identical to a 2022. So it was likely a 2022.

Can we get this user to upload rlogs for a driving route? Want to make sure it has the radar sending ACC and has the new radar track message.

**Comment by ErichMoraga** [comment]
> Can we get this user to upload rlogs for a driving route? Want to make sure it has the radar sending ACC and has the new radar track message.

His C3 is inside his home on WiFi, but I'm unable to get the rlogs to upload via Connect request (and there's no raw log toggle anymore).

**Comment by sshane** [comment]
I'm uploading them now

**Comment by ErichMoraga** [comment]
Confirmed rlogs uploaded for `081a1d5f242294c0|2022-07-12--18-02-25` (and possibly other routes).

**Comment by sshane** [comment]
Oh yeah, the 2022 classification is definitely correct.

Screenshot from 2022-07-12 13-43-15
Screenshot from 2022-07-12 13-43-06

**Pull request merged**
