### PR TITLE
cabana: choose camera type in open route dialog

### PR DESCRIPTION
**Pull request by deanlee**
added a combobox to choose camera type:

fallback to `->roadCamera->qCamera` If the specified video is not found in route.

Screenshot from 2023-04-14 15-05-48
Screenshot from 2023-04-14 15-05-26

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can we make this a live dropdown?

**Comment by adeebshihadeh** [comment]
I was thinking around the video player somewhere so you can switch at any time.

**Comment by deanlee** [comment]
reverted changes.

> I was thinking around the video player somewhere so you can switch at any time.

It is not easy for the current implementation to support live switch. 
replay does not support dynamic video switching. we can only load all videos and push theme in replay to allow the cameraview  switch between different videos. this will causes high cpu usage. maybe we can implement this feature later after we have a better solution?

**Comment by adeebshihadeh** [comment]
Sounds good!

**Pull request merged**
