### PR TITLE
Longitudinal tune for Corolla TSS2

### PR DESCRIPTION
**Pull request by briskspirit**
Better and smoother longitudinal tune for Corolla TSS2(hybrid and non-hybrid) and Highlander(hybrid and non-hybrid)

Was tested on: 
4 TSS2 Corollas(2 non-hybrid, 2 hybrid)
1 2020 Highlander

Needs more testing, would appreciate if it could be tried by others on Prius

### CODE REVIEW

**Comment by pd0wm** [comment]
Is the tuning also good without the changes to max gas?

As discussed on discord, we shouldn't use max gas to limit acceleration to keep it in hybrid mode. If that's what we you want you should lower the acceleration in plannerd.

**Comment by briskspirit** [comment]
Yes, it is definitely better than stock without changing the gas, but I still need more time. I remember our discussion about plannerd, reading the code and trying to understand how the whole longitudinal part is working.

**Comment by udiram** [comment]
I have a 2018 prius prime on this fork, and I quite like the acceleration/deceleration profiles, much smoother!

**Comment by C0mpl3t3N00b** [comment]
Tested this long tune on a 2020 Rav4 Hybrid, and it is better than the stock long control found in OpenPilot. Much smoother.

Moving forward, I would appreciate an investigation on Hybrid systems when stopped while OpenPilot is engaged; electric power to wheels is still evident while stopped.

**Comment by RICKYMAMA1** [comment]
Tested briskspirit on my 2020 Rav4 hybrid. Very smooth drive,better than stock!

**Comment by kkimelman** [comment]
I have driven ~2400 miles (2020 Toyota Highlander Gas) on BriskSpirit’s long tune. Found it much better and smoother than stock!

**Comment by scottrcarlson** [comment]
'19 corolla hatchback, these long tunes are really nice,  big improvement.

**Comment by pd0wm** [comment]
Merging this PR as is. If you'd like to add your car model to the list of tunes please submit one PR per car model.

**Pull request merged**
