### PR TITLE
simulator: add bridge test

### PR DESCRIPTION
**Pull request by StefanLekanic-SYRMIA**

### CODE REVIEW

**Comment by jnewb1** [comment]
https://github.com/commaai/openpilot/actions/runs/8189680276/job/22394958743?pr=31759#step:7:474

looks like this succeeded but just timed out, probably a process was left running somehow?

**Comment by StefanLekanic-SYRMIA** [comment]
> https://github.com/commaai/openpilot/actions/runs/8189680276/job/22394958743?pr=31759#step:7:474
> 
> looks like this succeeded but just timed out, probably a process was left running somehow?

@jnewb1  It looks llike that to me too. I will try to repeat test, and try few more things...

**Comment by StefanLekanic-SYRMIA** [comment]
@jnewb1  I figured out that the problem with failing tests makes sm['controlsState'].active "flag" in if statement in line 67, of test_sim_bridge file. Without this condition it works fine for 30, or 50 times.

**Comment by StefanLekanic-SYRMIA** [comment]
It passed 20 times.

**Comment by StefanLekanic-SYRMIA** [comment]
Something went wrong in the repo since friday, now all the tests are crashing all time.

**Comment by jnewb1** [comment]
> Something went wrong in the repo since friday, now all the tests are crashing all time.

https://github.com/commaai/openpilot/issues/31919

due to pedal removal

**Pull request closed without merging**
