### PR TITLE
Add Elantra to legacy safety model

### PR DESCRIPTION
**Pull request by sshane**
Getting @archlyg to test this

### CODE REVIEW

**Comment by archlyg** [comment]
Sure! I can test it tomorrow. Do I have to do anything through workbench or can I just go and drive?

**Comment by ShaneSmiskol** [comment]
@archlyg You can check it out whichever way is easiest; ssh, or installing using the fork installer: https://smiskol.com/fork/commaai/legacy-elantra

**Comment by ShaneSmiskol** [comment]
@archlyg Hi, were you able to test this branch to see if it fixes your issues?

**Comment by archlyg** [comment]
I'll try to test it tonight! Just got off work. Hope it works :)

**Comment by archlyg** [comment]
I just went on a drive and the comma 2 is not detecting the panda now...

**Comment by ShaneSmiskol** [comment]
Do you have a Discord account? Try rebooting the device a few times to let it flash

**Comment by archlyg** [comment]
Yeah my discord account is garyly#7747. Ok I'll try it a few more times rebooting it!

**Pull request merged**
