### PR TITLE
move selfdrive daemons into system

### PR DESCRIPTION
**Pull request by geohot**
Moving:
* camerad
* clocksd
* logcatd
* loggerd
* proclogd
* sensord

### CODE REVIEW

**Comment by geohot** [comment]
As long as locationd has calibration, it should live in selfdrive. thermald is a mess that does several things.

Still going to move a few more

**Comment by geohot** [comment]
Leaving hardware as a symlink due to the updater issue

**Comment by geohot** [comment]
Both rednose and cereal include "selfdrive/common/swaglog.h". I propose

"-DSWAGLOG=system/common/swaglog.h"

but added a symlink for now

**Comment by geohot** [comment]
@adeebshihadeh I'm happy with this for now. Subset of CI passing, but I'm sure I'm missing some stuff

**Comment by adeebshihadeh** [comment]
This PR is big enough as is, but I think the top level common belongs with system/common. I'll go through and cleanup the remaining selfdrive/ references in system/
```
batman:twopilot$ rg selfdrive system/
system/README.md
10:Relationship with selfdrive
13:While selfdrive can import from system, system can't import from selfdrive. selfdrive is an application that uses system.

system/tombstoned.py
155:      if "at selfdrive/" in line:

system/updated.py
42:from selfdrive.controls.lib.alertmanager import set_offroad_alert

system/camerad/SConscript
24:      env.Object('camera-util', '#/selfdrive/ui/replay/util.cc'),
25:      env.Object('camera-framereader', '#/selfdrive/ui/replay/framereader.cc'),
26:      env.Object('camera-filereader', '#/selfdrive/ui/replay/filereader.cc')]

system/loggerd/SConscript
33:  env.Program('tests/test_logger', ['tests/test_runner.cc', 'tests/test_loggerd.cc', 'tests/test_logger.cc', env.Object('logger_util', '#/selfdrive/ui/replay/util.cc')], LIBS=libs + ['curl', 'crypto'])

system/athena/registration.py
12:from selfdrive.controls.lib.alertmanager import set_offroad_alert

system/camerad/snapshot/snapshot.py
14:from selfdrive.controls.lib.alertmanager import set_offroad_alert
15:from selfdrive.manager.process_config import managed_processes

system/athena/manage_athenad.py
7:from selfdrive.manager.process import launcher

system/camerad/test/test_exposure.py
6:from selfdrive.test.helpers import with_processes

system/camerad/cameras/camera_replay.h
4:#include "selfdrive/ui/replay/framereader.h"

system/camerad/test/test_camerad.py
7:from selfdrive.test.helpers import with_processes

system/logcatd/tests/test_logcatd_android.py
10:from selfdrive.test.helpers import with_processes

system/loggerd/tests/test_encoder.py
18:from selfdrive.manager.process_config import managed_processes

system/loggerd/tests/test_logger.cc
12:#include "selfdrive/ui/replay/util.h"

system/loggerd/tests/test_loggerd.py
20:from selfdrive.manager.process_config import managed_processes
```

Before merging, I'd like to do some more testing. I suspect some things will subtly break as a result of this, e.g. https://github.com/commaai/openpilot/blob/4f4f18a648f8b5ec1fa63c60f69da1a32e60d9a5/selfdrive/tombstoned.py#L155 Also would like to explicitly test the hardware symlink for the NEOS/AGNOS manifests.

**Comment by pd0wm** [comment]
Thought about it a bit more, and like to propose the following structure. There will be a support folder (lib), a folder for system daemons, and a folder for openpilot daemons. A deamon can only import from things inside it's own folder, and from lib.

 - lib. This contains support code for daemons (e.g. common, hardware)
 - third_party, like lib but for other peoples code
 - system. This contains all the system daemons (e.g. updater, loggerd, camerad, sensord)
 - selfdrive. This contains all the driving related code (e.g. controlsd, radard, boardd, locationd, ui)
 - tools. This contains current tools, but also selfdrive/debug, and selfdrive/ui/replay.
 
It might also make sense to move helpers/submodules into to the daemon files if they are only used there. E.g. rednose should live inside the locationd folder, unless it's also use by other daemons, then it can be in lib. opendbc can live in controlsd. Panda can live in pandad.

manager.py + build.py can live in the top level directory, and automatically scans for daemons. Adding a new daemon is as simple as creating a new folder. Ideally the messages that a daemon broadcast also live inside that folder.

The folder structure would look something like:
```
lib/
  cereal/
  params/
  kalman/
  transformations/
  math/
  hardware/
  logging/

system/
  loggerd/
  camerad/
  sensord/
  thermald/
  updated/

selfdrive/
  modeld/
    models/
  controlsd/
    opendbc
  pandad/
   boardd/
   panda/
  locationd/
    laika
    rednose
  navd/
```

**Comment by geohot** [comment]
I like the dir structure, but keep the controlsd name!

**Comment by pd0wm** [comment]
We could also make a `first_party` folder with all our submodules? I'd like to keep the root folder clean. If somebody forks openpilot it should be clear what folders they can throw away to start their own (non-car related) project.

**Comment by geohot** [comment]
I like `lib` a lot more than `first_party` import first_party.xxx is terrible.

One of the issues with this is laika and rednose are pip installable. You want it to be import lib.rednose?

**Comment by pd0wm** [comment]
Do you think that's a dealbreaker? The imports are currently already slightly different for some of the python helpers in panda, `panda.python.uds` vs `panda.uds` if it's pip installed or not.

**Comment by geohot** [comment]
I guess not really. Maybe we leave `cereal` in the top level since that's a core part of openpilot, and rednose and laika can have the lib prefix.

**Pull request closed without merging**
