### PR TITLE
cabana: support choosing color for signal

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/discussions/26091#discussioncomment-6860946

1. choose color dialog:
Screenshot 2023-09-07 19:32:41

2. chat view. click `Choose colors` to choose color for signals in chart

3.signal view. click palette button to choose color for signals in message:

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Is this worth 100 lines? cabana is already ~8k lines

**Comment by deanlee** [comment]
I've tried to keep the code as concise as possible. @sshane  any thought? feel free to close it if it's not worth.

**Comment by sshane** [comment]
This feels like a useless menu, you can't choose any signals from here? 
image

**Comment by sshane** [comment]
Pressing the button doesn't affect CANCEL_REQ, it affects the first(?) modified signal from the signals pane.

image

**Comment by deanlee** [comment]
> This feels like a useless menu, you can't choose any signals from here? image

it's not a menu, it's used to choose color for selected signal on the left side, not quite sure why the color picker is missing on the right side in your screenshot. it should be something lie this:(my screenshot)

Screenshot 2023-09-07 19:32:41

**Comment by sshane** [comment]
Oh it's a separate popup for me 
image

**Comment by deanlee** [comment]
how about know? added option `QColorDialog::DontUseNativeDialog`

**Comment by jnewb1** [comment]
Can we also remove yellow as one of the default color choices in light mode? I can't see it at all

**Comment by deanlee** [comment]
> Honestly if you just remove all the light colors from light mode then a color chooser probably isn't required

Think the color selector is still useful. Especially if multiple signals with similar colors are displayed in  one chart. Here's an example:

264264410-9e884226-3508-4c3f-aba6-bea5efce61b6

**Comment by sshane** [comment]
Is it better to just adjust the colors depending on the others when plotted on other signals?

**Pull request closed without merging**
