### PR TITLE
Bring back linux aarch64 in CI

### PR DESCRIPTION
**Pull request by ghost**
Resolves issue https://github.com/commaai/openpilot/issues/32882
Reason to drop aarch64 from CI during upgrade to ubuntu24.04/python3.12 was Casadi not building. Casadi has not provided bulid wheel for python 3.12. I have built wheel for casadi for aarch64 and provided the wheel (whl/casadi-3.6.5-cp312-cp312-linux_aarch64.whl)

The goal:

1)    install all python/ubuntu dependencies and build openpilot on a linux aarch64 machine. (You don't need an aarch64 linux machine for doing this bounty since everything will be validated by our CI runner.)

I have tested installing python and ubuntu dependencies using docker image for aarch64 machine.

2)  add back aarch64 in the build matrix such that it runs on our namespace runner (see [here](https://github.com/commaai/openpilot/pull/32715/files#diff-38aca91846a892e562f5343cde335a052609352cd50edb16d2905db04944a47eL76) for how it was done)

I have added back aarch64 in the build matrix.

3) add back the docker_push_multiarch step (see [here](https://github.com/commaai/openpilot/pull/32715/files#diff-38aca91846a892e562f5343cde335a052609352cd50edb16d2905db04944a47eL93) )

I have added back docker_push_multiarch step.

4) make the test pass
The current github workflow selfdrive_tests.yaml is setup to use master branch, the selfdrive_tests needs to be tested. Locally I had no errors building casadi wheel using python 3.12 for aarch64 and also installing openpilot/python3.12 dependencies so I am curious to find out if the provided casadi wheel helps with the issue.

### CODE REVIEW

**Comment by maxime-desroches** [comment]
Can you provide the script you used to build the wheel?

**Comment by andiradulescu** [comment]
@maxime-desroches - the script is [create_wheel_local.py](https://github.com/casadi/casadi/blob/main/misc/create_wheel_local.py). it's being built in [casadi's CI](https://github.com/casadi/casadi/blob/72764dc73eab7b935db7e302278508855815883b/.github/workflows/binaries.yml#L716) and pushed to a nightly release. my casadi fork/branch already does [this](https://github.com/andiradulescu/casadi/releases/tag/nightly-ci-build-aarch64-py312).

create_wheel_local.py params from the above CI run are:
```
python misc/create_wheel_local.py 3.6.5.dev+ci-build-aarch64-py312 312 linux 64 manylinux2014-aarch64 install/
```

didn't tested it locally, but in CI built [successfully](https://github.com/andiradulescu/casadi/actions/runs/9888443900/job/27313156267).

**Comment by coder351** [comment]
@maxime-desroches I have added the script in tools/install_python_dependencies.sh, please check commit https://github.com/commaai/openpilot/pull/32968/commits/eb9f46c50f7387291ab71fb4b8f271e9d73adcf7
I have reverted the uv.lock file and also removed the built wheel from the PR because the script would generate the wheel and add entries for aarch64 wheel to the uv.lock as necessary. I have tested locally and casadi built successfully and also openpilot python and ubuntu dependencies installed without errors. The https://github.com/commaai/openpilot/pull/32708#discussion_r1635604873 should no longer be the blocker.

**Comment by maxime-desroches** [comment]
I'm going to close this up since this needs our own wheels and we can't just put them in the repo. I will push them to pypi instead.

**Comment by coder351** [comment]
@maxime-desroches The issue https://github.com/commaai/openpilot/pull/32708#discussion_r1635604873 is because of bug in UV which does not include the header files for python. I have outlined alternate solution which does not require building the wheel and no need to push wheel to pypi. The symbolic link is needed because UV does not have the include dir in virtual env. I have tested and openpilot builds without errors.

```
+uv venv
+ln -s /usr/include/python3.12/ .venv/include
+uvx pip --python .venv/bin/python3 install casadi==3.6.5 -v

```

**Comment by maxime-desroches** [comment]
@coder351 We still want a wheel because we don't want to rebuilt casadi every time.

**Pull request closed without merging**
