### PR TITLE
[bot] Fingerprints: add missing FW versions from new users

### PR DESCRIPTION
**Pull request by sshane**
## ✅ Updating FW version database with FW from 2 dongles (2 platforms) in last 30 days:
<details open><summary>View table</summary><br>

| Dongle, platform, VIN                                                                                                               | Name from VIN 🆚 CarDocs                                                             | Segments                                     | Bad seg tags                                                                          | Good seg tags                                                                          |
|:------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------|:---------------------------------------------|:--------------------------------------------------------------------------------------|:---------------------------------------------------------------------------------------|
| [0649d406184b7131](https://useradmin.comma.ai/?onebox=0649d406184b7131)<br><sub>VOLKSWAGEN JETTA 7TH GEN<br>3VWEB7BUX........</sub> | VOLKSWAGEN Jetta 2019 🆚<br>Volkswagen Jetta 2018-24                                 | 120 routes,<br>1936 segments<br>(32.3 hours) |                                                                                       | - valid torque params: 1935<br>- all lat active: 234<br>- no input all lat active: 208 |
| [71dbab52cfb46611](https://useradmin.comma.ai/?onebox=71dbab52cfb46611)<br><sub>VOLKSWAGEN ATLAS 1ST GEN<br>1V2BC2CA3........</sub> | VOLKSWAGEN Atlas Cross Sport 4Motion 2021 🆚<br>Volkswagen Atlas Cross Sport 2020-22 | 126 routes,<br>2347 segments<br>(39.1 hours) | - [VIN model mismatch (info): 1](https://useradmin.comma.ai/?onebox=71dbab52cfb46611) | - valid torque params: 2347<br>- all lat active: 805<br>- no input all lat active: 711 |

Dongles to re-run category: `0649d406184b7131 71dbab52cfb46611`
</details>

## ⏳️ 5 dongles (3 platforms) do not yet have enough data to be added:
<details ><summary>View table</summary><br>

| Dongle, platform, VIN                                                                                                                | Name from VIN 🆚 CarDocs                                                | Segments                                    | Bad seg tags                                                                          | Good seg tags                                                                     |
|:-------------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------|:--------------------------------------------|:--------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------|
| [77db91ca5676dfd9](https://useradmin.comma.ai/?onebox=77db91ca5676dfd9)<br><sub>VOLKSWAGEN GOLF 7TH GEN<br>3VW6T7AUX........</sub>   | VOLKSWAGEN Golf GTI Hatchback 2021 🆚<br>Volkswagen Golf GTI 2015-21    | 79 routes,<br>1132 segments<br>(18.9 hours) | - [VIN model mismatch (info): 1](https://useradmin.comma.ai/?onebox=77db91ca5676dfd9) | - valid torque params: 1132<br>- all lat active: 8                                |
| [1b1b0ae707af0f5f](https://useradmin.comma.ai/?onebox=1b1b0ae707af0f5f)<br><sub>VOLKSWAGEN GOLF 7TH GEN<br>3VWC17AU6........</sub>   | VOLKSWAGEN Golf SportWagen 2016 🆚<br>Volkswagen Golf SportsVan 2015-20 | 3 routes,<br>19 segments<br>(0.3 hours)     | - [VIN model mismatch (info): 1](https://useradmin.comma.ai/?onebox=1b1b0ae707af0f5f) | - valid torque params: 6<br>- all lat active: 1                                   |
| [af3a81d36a847fda](https://useradmin.comma.ai/?onebox=af3a81d36a847fda)<br><sub>VOLKSWAGEN PASSAT 8TH GEN<br>WVWZZZ3CZ........</sub> | VOLKSWAGEN  1986 🆚<br>Volkswagen Passat 2015-22                        | 9 routes,<br>99 segments<br>(1.6 hours)     |                                                                                       | - valid torque params: 67<br>- all lat active: 12<br>- no input all lat active: 1 |
| [3e57c316782406b5](https://useradmin.comma.ai/?onebox=3e57c316782406b5)<br><sub>VOLKSWAGEN GOLF 7TH GEN<br>3VWH17AU7........</sub>   | VOLKSWAGEN Golf Alltrack 2019 🆚<br>Volkswagen Golf Alltrack 2015-19    | 4 routes,<br>83 segments<br>(1.4 hours)     |                                                                                       | - all lat active: 0                                                               |
| [a97d27ce2a78958a](https://useradmin.comma.ai/?onebox=a97d27ce2a78958a)<br><sub>VOLKSWAGEN JETTA 7TH GEN<br>3VWG57BUX........</sub>  | VOLKSWAGEN Jetta 2019 🆚<br>Volkswagen Jetta 2018-24                    | 21 routes,<br>547 segments<br>(9.1 hours)   |                                                                                       | - valid torque params: 547<br>- all lat active: 3<br>- no input all lat active: 2 |

Dongles to re-run category: `1b1b0ae707af0f5f 77db91ca5676dfd9 af3a81d36a847fda 3e57c316782406b5 a97d27ce2a78958a`
</details>

## ⚠️ 2 dongles (2 platforms) have issues that need to be resolved before adding:
<details ><summary>View table</summary><br>

| Dongle, platform, VIN                                                                                                              | Name from VIN 🆚 CarDocs                                                                                          | Segments                                    | Bad seg tags                                                                                                                                                                                                                                                                                                                                                                                   | Good seg tags                                                                        |
|:-----------------------------------------------------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------------------------|:--------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------|
| [23daff6c438612d2](https://useradmin.comma.ai/?onebox=23daff6c438612d2)<br><sub>AUDI A3 3RD GEN<br>3VWCA7AU3........</sub>         | VOLKSWAGEN Golf SportWagen 2015 🆚<br>Audi A3 Sportback e-tron 2017-18<br><sub>🎉 <b>New model year!</b> 🎉</sub> | 44 routes,<br>2339 segments<br>(39.0 hours) | - [car faulted: 171](https://useradmin.comma.ai/?onebox=23daff6c438612d2%7C2024-03-08--16-32-29)<br>- [VIN model mismatch (info): 1](https://useradmin.comma.ai/?onebox=23daff6c438612d2)<br>- [VIN make mismatch (info): 1](https://useradmin.comma.ai/?onebox=23daff6c438612d2)                                                                                                              | - valid torque params: 2339<br>- all lat active: 81<br>- no input all lat active: 67 |
| [6e6e342fad47dd29](https://useradmin.comma.ai/?onebox=6e6e342fad47dd29)<br><sub>VOLKSWAGEN GOLF 7TH GEN<br>WVWVF7AU2........</sub> | VOLKSWAGEN Golf R Hatchback 2018 🆚<br>Volkswagen Golf Alltrack 2015-19                                           | 48 routes,<br>218 segments<br>(3.6 hours)   | - [missing ECU FW: 10](https://useradmin.comma.ai/?onebox=6e6e342fad47dd29%7C2024-02-24--09-10-38)<br>- [spotty FW: 10](https://useradmin.comma.ai/?onebox=6e6e342fad47dd29%7C2024-02-24--09-10-38)<br>- [car faulted: 9](https://useradmin.comma.ai/?onebox=6e6e342fad47dd29%7C2024-03-13--19-55-24)<br>- [VIN model mismatch (info): 1](https://useradmin.comma.ai/?onebox=6e6e342fad47dd29) | - valid torque params: 218<br>- all lat active: 4                                    |

Dongles to re-run category: `6e6e342fad47dd29 23daff6c438612d2`
</details>

### CODE REVIEW

**Comment by sshane** [comment]
@jyoung8607 should we add this name to the CarInfo?

**Comment by sshane** [comment]
Ugh, VPIC says this is the full model name: `Model: Atlas Cross Sport 4Motion`

**Comment by jyoung8607** [comment]
I mean, I'm not here to say we CAN'T pop a couple more Volkswagen entries Into the supported cars list.

If you want to do it, add 4Motion variants to both Atlas and Atlas Cross Sport.

**Comment by sshane** [comment]
If you think most people would assume their 4Motion works when not specified, we have just have the bot strip it.

**Pull request merged**
