### PR TITLE
Toyota: Add missing FW versions for RAV4 Hybrid 2022

### PR DESCRIPTION
**Pull request by sshane**
from dongle 79b178eb4317ab05

### CODE REVIEW

**Comment by sshane** [comment]
@ls1z28chris can you try this?

**Comment by ls1z28chris** [comment]
> @ls1z28chris can you try this?

I can. I'm pretty new to this, so still reading through the wiki entry on fingerprinting.

So I'm not sure what you mean by trying this out. I'm going through the wiki on fingerprinting, and all the way up to step 4. Not sure how to SSH into the device at this point.

**Comment by sshane** [comment]
If you don't know how to ssh yet, uninstall openpilot and enter this URL when installing custom software: https://installer.comma.ai/commaai/2022-rav4h-fp2

**Comment by ls1z28chris** [comment]
Thanks for clarifying. I was appending /2022-rav4h-fp2 to the https://smiskol.com/fork/sshane url I'd used initially. This time the install is running on the device.

I'm on CST so it is evening over here. I'll give it a shot in the morning. Thanks again.

**Comment by ls1z28chris** [comment]
@sshane Everything worked this morning. Thanks for the help. Did you essentially perform the [fingerprinting ](https://github.com/commaai/openpilot/wiki/Fingerprinting )for me?

Are there any spaces besides the discord I should follow for advances/progress on my specific platform and with the tech as a whole?

**Comment by sshane** [comment]
Yes, I just plugged your car into https://github.com/commaai/openpilot/blob/master/selfdrive/debug/test_fw_query_on_routes.py and it tells you what fw versions are missing/mismatched

**Comment by ls1z28chris** [comment]
@sshane So if you've added my vehicle to the master and removed this branch, how will this work going forward as your fork is updated and revised? Does the comma3 device pull at the fork level and ignore the now deleted branch that you created? Or do I need to reload the master?

**Comment by sshane** [comment]
No, you'll want to reload master or master-ci for a prebuilt version

**Pull request merged**
