### PR TITLE
camerad: cleanups, support running only one camera

### PR DESCRIPTION
**Pull request by geohot**

### CODE REVIEW

**Comment by pd0wm** [comment]
If any of the asserts in camera bringup or AE fails, can we disable that camera and continue with the rest?

**Comment by geohot** [comment]
Yes, but from an application perspective, why would you want that?

**Comment by pd0wm** [comment]
> Yes, but from an application perspective, why would you want that?
> 
> (and actually, sort of not with the strobe conflict)

 - For startup failures it makes it easier for controlsd to alert properly, and to do other debugging
 - I a camera fails while driving we want to soft-disable but keep driving for as long as possible. Our driving models should be robust to a camera dropping out.

**Comment by geohot** [comment]
Hmm actually being robust to the failure we've seen in the field is easy, and will also work for an unplugged sensor.

**Comment by pd0wm** [comment]
There are a few more asserts I think. At least one in the i2c code that's called by auto exposure.

**Comment by geohot** [comment]
Done. Confirmed both:
* starting without sensor attached
* unplugging sensor while running

**Comment by geohot** [comment]
Tried a few more sensor unplugs, you can also sometimes get a kernel panic...but 80% of the time it's i2c

**Comment by geohot** [comment]
Should be good.

**Comment by geohot** [comment]
Hmm, handle_camera_event has some sketchy looking code to handle failure cases. I wonder how it was tested. I added logging to it.

**Pull request merged**
