### PR TITLE
Have Wheel Rotate

### PR DESCRIPTION
**Pull request by arne182**
Take the steering wheel angle and have the wheel in the top right rotate in that direction.

### CODE REVIEW

**Comment by icmma** [comment]
Love bro 💙

**Comment by geohot** [comment]
Hehe, cute. On the table for 0.6

**Comment by geohot** [comment]
Deciding against this for upstream. In explorer it makes sense because you don't have a real steering wheel to look at, but in the car, you not only have a wheel to look at, you should have your hands on it!

**Comment by arne182** [comment]
Selavi

**Comment by arne182** [comment]
Should have upstreamed it with my face. Maybe that would have made the difference

**Pull request closed without merging**
