### PR TITLE
VW MQB: Update to Audi A3 Mk3

### PR DESCRIPTION
**Pull request by jyoung8607**
**Audi A3 Mk3 (updating existing FPv1)**

Covers all variants of the third generation A3 (2013-2019), including the A3 Cabrio, A3 Sportback, g-tron (CNG), e-tron (PHEV), S3, and RS3.

- [x] brand sorting, added A3 generation to naming
- [x] updated README with new model-year support
- [x] test route already exists in [test_car_models](../../selfdrive/test/test_car_models.py)
- [x] route with openpilot: 4634226ed41b59ea|2021-03-26--14-14-18

Thanks to community A3 owners bankster (2014), fastzeek (2017 e-tron sportback), and Ambroos (2018 e-tron sportback), and also to Comma for adding a 2017 A3 to their fleet!

**Merge Review**

Wheelbase and mass have been corrected, which will probably attract attention from process_replay.

This CAR has existing FPv1 users, so it can't be added to IGNORED_FINGERPRINTS just yet.

### CODE REVIEW

**Comment by jyoung8607** [comment]
The name-change ticks off process_replay, I'll have to collect a fresh test drive.

**Comment by pd0wm** [comment]
Normally we don't include years in the readme that aren't tested, but feel like it should be ok in this case since we support models from before and after 2016. If you don't see any reason why it wouldn't work, feel free to add it.

**Comment by godoppl** [comment]
I have ordered a comma two with intentions to use it on my 2017 A3 Sportback e-tron. I will do some testing to assure compatibilty with the 2017 model when it arrives. If you have a specific test routine you want me to go through, I will be happy to do so.

**Comment by jyoung8607** [comment]
The mismatches in process_replay are expected since we're now supplying a correct mass and wheelbase for the A3.

I reverted the model-generation naming alignment for now. It needs a new test route to pass CI, my community A3 owners aren't available to provide one today, and I think the comma team is otherwise engaged. Will clean it up post-0.8.3.

This should be G2G for review and ref commit bump at your convenience.

**Comment by jyoung8607** [comment]
> I have ordered a comma two with intentions to use it on my 2017 A3 Sportback e-tron. I will do some testing to assure compatibilty with the 2017 model when it arrives. If you have a specific test routine you want me to go through, I will be happy to do so.

Feel free to stop by comma's Discord, channel #volkswagen-audi, when you're ready to come on board.

**Comment by jyoung8607** [comment]
Based on my discussion with @VirtuallyChris, I've expanded the README to include distinct models (not just A3 trim levels) that were marketed separately by Audi and appear in various model-selection utilities like [comma's compatibility checker](https://comma.ai/vehicles).

I've also changed the Supported Package. Driver Assistance is most correct. It happens to come standard with Prestige (highest trim), but it's available as an option with Premium Plus (midlevel trim).

Also, since this didn't make the 0.8.3 cut, reverting to draft until I get an updated test route with the naming cleanup.

**Comment by adeebshihadeh** [comment]
Once we confirm we have @keeleysam's FW (since he did the original PR), I think we're fine to move the A3 to ignored fingerprints. Looks like VW will be the first FP2.0-only make!

**Comment by adeebshihadeh** [comment]
Any specific reason for updating the test routes? We just need to re-generate the refs.

**Comment by jyoung8607** [comment]
> Once we confirm we have @keeleysam's FW (since he did the original PR), I think we're fine to move the A3 to ignored fingerprints. Looks like VW will be the first FP2.0-only make!

I feel like there were one or two more running around, but you'd have the best view of current user uploads.

> Any specific reason for updating the test routes? We just need to re-generate the refs.

The name change AUDI_A3 -> AUDI_A3_MK3 made process_replay fail bigly, looked like you would need a new one to me. Maybe you don't, up to you.

**Comment by adeebshihadeh** [comment]
You're right, process replay needs a new route due to how we fingerprint for the test.

**Pull request merged**
