### PR TITLE
Allow uploader.py to compress rlog without upload permission

### PR DESCRIPTION
**Pull request by eFiniLan**
rlog does not compress to rlog.bzip2 until upload is allowed, which means users like me who only upload logs with WIFI will waste quite a bit of space.

rlog2

OP generates a folder each minute with at least 2 files in it:
rlog

after compression, rlog size is reduced to 7mb (vs 25.5mb)

1 hr drive will save roughly around 1G of space.

### CODE REVIEW

**Comment by emmertex** [comment]
Can I suggest you also add this.
That way it uploads in the correct order, starting with those compressed already.

127     # try to upload compressed log files first
128     for name, key, fn in self.gen_upload_files():
129       if name == "rlog.bz2":
130         return (key, fn, 0)
131 
132     # then do those which are yet to be compressed
133     for name, key, fn in self.gen_upload_files():
134       if name == "rlog":
135         return (key, fn, 0)

**Comment by eFiniLan** [comment]
@emmertex I have changed it back, if we return rlog.bzip2 files first that means none of the rlog will be compressed until all the rlog.bzip2 are uploaded.

**Comment by emmertex** [comment]
I seen that, after I tested a long drive.
Obvious now I look at it.
I'll attack it again later, but having said that, it only takes 5 seconds to compress 1 minn of data, maybe it's pointless anyway?

**Comment by rbiasini** [comment]
looks like a good change, thanks. Is it good to go? @emmertex or anybody else had a chance to test it?

**Comment by emmertex** [comment]
I need to retest, I'll review in a day or 2

**Comment by emmertex** [comment]
So sorry I forgot about this..
All worked fine for me..

**Pull request merged**
