### PR TITLE
GM: disengage on radar fault

### PR DESCRIPTION
**Pull request by vntarasov**
GM radar is notorious for getting into some sort of miscalibrated state (a.k,a. "alignment fault"). Without handling the fault, openpilot thinks the path is clear while it should disengage.

Tested there are no false-positives on stop and go and highway driving, on 2017 Volt.

Driving for about half an hour with stock ASCM on highway speeds is known to fix that radar fault. I haven't looked into how ASCM does it or how openpilot can replicate the behavior.

### CODE REVIEW

**Comment by rbiasini** [comment]
ah... the opendbc changes needs to be done together with these op changes (otherwise radard would crash). 
@vntarasov I can put back the opendbc changes as soon as this is ready to go. Can someone test it?

**Comment by srpape** [comment]
I've been testing it on my 2018 Volt with no issues.

**Comment by Jamezz** [comment]
Verified. :shipit:

**Comment by vntarasov** [comment]
Also needs https://github.com/commaai/opendbc/pull/116 to be re-added to opendbc repo.

**Pull request merged**
