### PR TITLE
Show loading progress

### PR DESCRIPTION
**Pull request by dek3rr**
This simply displays, for example, "loading openpilot: 3/21 plannerd"
I feel like we used to have something like this years ago.. could be dreaming

Also, if this implementation is ok, I'd be happy to replace this with a gui loading bar if I had a makefile for spinner

### CODE REVIEW

**Comment by energee** [comment]
This is a nice idea

**Comment by pd0wm** [comment]
Not sure why the Makefile is not open source. Here it is: https://gist.github.com/pd0wm/6c4c716ea14b5afeb0ec171f8c9e25c0

Does this reset the spinner position every time we restart it? Isn't it cleaner to have spinner (optionally) listen to a socket where we can send it new text while we keep it running?

**Comment by dekerr** [comment]
Awesome, thanks. This is a little hacked together so it does reset (opens a new pipe every update). Not ideal in any sense. 
I don't know much about using sockets, but we do need a solution to update the argument, so I'll look into this.

**Comment by pd0wm** [comment]
It might not need a zmq socket. We can also keep sending it stuff over stdin. The spinner can show the new text every time we send a newline.

**Comment by dekerr** [comment]
closing for now while I work out some finer details. Writing to stdin works well now.

**Pull request closed without merging**
