### PR TITLE
UI: refactor vision

### PR DESCRIPTION
**Pull request by deanlee**
using a single VisionStream instance for both rear and front camera.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Does this have the same CPU savings as #1983? Any improvement with the GPU?

**Comment by deanlee** [comment]
I think it does.this PR does not subscribe and process front camera data when on-roading. the performance might be better if combine with these PR: https://github.com/commaai/openpilot/pull/2025 https://github.com/commaai/openpilot/pull/2037 .but I need more testing to confirm that

**Comment by adeebshihadeh** [comment]
Did a quick check, and this seems to have the same CPU savings. Can you rebase and I'll review tomorrow?

**Comment by deanlee** [comment]
Ok i'll do it in a while

**Comment by adeebshihadeh** [comment]
Thanks for the PR, fixed up some bugs and did some more refactoring in #2115.

**Pull request closed without merging**
