### PR TITLE
Škoda: add missing FW versions for 2019 Kodiaq

### PR DESCRIPTION
**Pull request by huifan0114**

### CODE REVIEW

**Comment by sshane** [comment]
Can you add your dongle id from this device? It's in settings

**Comment by huifan0114** [comment]
> Can you add your dongle id from this device? It's in settings

where can i add dongle id？

**Comment by sshane** [comment]
You can add it here. You can find it on your device in settings.

**Comment by huifan0114** [comment]
> 
dongle id: 01ef793d1ce60efb

thank you

**Comment by huifan0114** [comment]
> You can add it here. You can find it on your device in settings.

Is there anything else I need to provide?

**Comment by sshane** [comment]
Nope that's it, just wanted to check your logs to make sure. Thanks for the PR!

**Comment by huifan0114** [comment]
> 
thanks for your help

**Pull request merged**
