### PR TITLE
Mazda: silence hands off warning in cars with no lockout

### PR DESCRIPTION
**Pull request by Jafaral**
block eps lkas state from getting to the camera

Depends on: https://github.com/commaai/panda/pull/741

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
We shouldn't really fake things like this. Why don't we just take over sending the alert message? We can start by copying the message from the camera and only filtering out the alert.

**Comment by adeebshihadeh** [comment]
Regardless of this PR, we want to show HUD alerts ourselves anyway, and it looks like this is missing from the Mazda port. [These](https://github.com/commaai/cereal/blob/a0850ebef69c5a3c43c875fb730528b049bad2e1/car.capnp#L335) are the alerts that should be implemented, but just implementing steerRequired and fcw gets you most of the way there.

**Comment by Jafaral** [comment]
Not sure I follow @adeebshihadeh , do you mean showing alerts on OP screen?  plus we already have things like  gear info and seatbelt. Can you please clarify ?

**Comment by Jafaral** [comment]
Also, let me know if this PR is OK or if you want things done differently.

**Comment by adeebshihadeh** [comment]
Fixed in #22730

**Pull request closed without merging**
