### PR TITLE
athena: persist upload queue to disk

### PR DESCRIPTION
**Pull request by DevinLeamy**
**Description**
- Addresses https://github.com/commaai/openpilot/issues/21921

**Verification**
- Added relevant test to test suite.

**Also**
- Made `athenad.cancelled_uploads` reset between tests.
- Made `MockParams` persist data (like `common.params`) during a test, and reset between tests.

### CODE REVIEW

**Comment by pd0wm** [comment]
LGTM. Need to update some stuff in the backend to make sure URLs are valid for 30 days, and can only be used once. Will merge once that is done.

**Review by pd0wm — APPROVED** [review]

**Comment by pd0wm** [comment]
The backend now generates URLs with longer validity, so that change is merged. However, we currently have no way in useradmin/connect to cancel pending uploads, which is probably something you want as well if the queue persists. So we'll get that in as well before merging this.

**Comment by adeebshihadeh** [comment]
@pd0wm are we ready to merge this now?

**Comment by pd0wm** [comment]
Yes! Will merge it once 0.8.12 is in `devel-staging`.

**Pull request merged**
