### PR TITLE
(New) Lemon Pie Model 🍋

### PR DESCRIPTION
**Pull request by YassineYousfi**

### CODE REVIEW

**Comment by YassineYousfi** [comment]
This is gated on refactoring modeld to fix the TODO in `selfdrive/modeld/modeld.py`

**Comment by YassineYousfi** [comment]
should be good to merge after https://github.com/commaai/openpilot/pull/30273

**Comment by YassineYousfi** [comment]
This is pending another fix to be able to regen the logs for process replay.

**Comment by devtekve** [comment]
I've been playing with this model and it's much better with european (spanish) roads! love it ! great work!

**Review by thegauravgiri — APPROVED** [review]
LGTM

**Pull request merged**
