### PR TITLE
Added fingerprint for 2020 Nissan Leaf SV Plus

### PR DESCRIPTION
**Pull request by mkfischer**
Added fingerprint for 2020 Nissan Leaf SV Plus

### CODE REVIEW

**Comment by pd0wm** [comment]
Can you merge it into the existing fingerprint?

**Comment by mkfischer** [comment]
It's not clear what you're asking.

**Comment by pd0wm** [comment]
There are now two dictionaries with fingerprints for the LEAF. Can you merge them into one dictionary that contains the values of both of them?

**Comment by mkfischer** [comment]
That's not the convention I see in other files.  I am going to keep them separate for clarity.

**Comment by pd0wm** [comment]
Not all cars do this properly, but merging them creates a fingerprint that is compatible with more different cars. Please combine the two fingerprints and I'll merge the PR.

**Comment by adeebshihadeh** [comment]
Can you also add the 2020 leaf to the readme?

**Comment by VirtuallyChris** [comment]
Did all requested changes in https://github.com/commaai/openpilot/pull/2311. Closing this pull request.

**Pull request closed without merging**
