### PR TITLE
op tool helper

### PR DESCRIPTION
**Pull request by maxime-desroches**
~can use it by adding `alias op='source <YOUR OPENPILOT DIR>/tools/op.sh "$@"'` to your .bashrc~

- ~need to check for git submodules~

Install it by running `tools/op.sh --install` then open a new shell and use `op`

### CODE REVIEW

**Comment by sshane** [comment]
I have pyenv install set up to be my global python, is this expected to not work?

Can we also add cabana?

```
batman@workstation-shane:~/openpilot$ op build
bash: /home/batman/openpilot/.venv/bin/activate: No such file or directory

Can't activate venv. Have you ran 'op install' ?
```

**Comment by maxime-desroches** [comment]
@sshane I will add cabana. 

For the venv, I think we should follow the standard of one .venv per python project. Running `install_python_dependencies.sh` creates that .venv for you.

Also, `uv` offers almost the same things as `pyenv` but 100000x faster. You can just run `uv python install 3.12.4`

**Comment by adeebshihadeh** [comment]
I think we can support skipping the venv sourcing if `.venv` doesn't exist? You're on your own though if things aren't setup properly.

**Comment by sshane** [comment]
A warning at worst is fine with me, my setup may be weird, but I prefer a global install as I use it for notebooks, in various Pycharm projects, etc.

**Comment by adeebshihadeh** [comment]
Let's take this to the Discord thread.

**Pull request merged**
