### PR TITLE
script: update PlatformConfig programmatically

### PR DESCRIPTION
**Pull request by incognitojam**
Adds code to help write PlatformConfig changes back to `values.py`. Supports updating `CarSpecs` and `flags`.

Closes https://github.com/commaai/openpilot/issues/31713

### CODE REVIEW

**Comment by jnewb1** [comment]
looks cool, but is there a way to do this slightly more generically? don't want to have to update this every time we add a field

**Comment by jnewb1** [comment]
I suppose `dataclass_to_string` will also work for carinfo right?

**Comment by incognitojam** [comment]
I found some problems:
- any dataclass which modifies itself in init means they get updated unecessarily, not sure how to fix this yet
- need to handle converting nested objects to strings (`str(x)` or `repr(x)` doesn't produce the right value in car info with the enums), working on this

**Comment by incognitojam** [comment]
I can't think of a way to solve things like `CarParts.common` (and there are probably others I haven't noticed yet) without writing code to test whether `CarParts.common(...)` generates the same parts list.

I might be taking the wrong approach here. If someone else wants to take this over I'm happy to unclaim the bounty, otherwise I'll see if I think of something else

**Comment by jnewb1** [comment]
hmm, i think we will have to use something like AST directly. i.e. modifying the python code rather than the dataclass later

**Pull request closed without merging**
