### PR TITLE
Add Fingerprint from 2018 Toyota Sienna XLE

### PR DESCRIPTION
**Pull request by autolock**
Toyota Sienna 2018 XLE
#Fingerprint
This pull requests adds a fingerprint for <Make - Model - Year - Trim>.
#fingerprint <toyota-sienna-2018-XLE>

# Feature
This pull requests adds feature X fingerprint

## Description
Explain what the feature does
Fixes unsupported issue with sienna especially with dsu unplugged. Before making the change with dsu unplugged. It would say cruise fault error. 

## Testing
Read fingerprint, Made modification. No more cruise fault error restart car when dsu unplugged, stop and go now working.
Quick acceleration problem noticed.

### CODE REVIEW

**Comment by autolock** [comment]
https://my.comma.ai/91b2d713c6532166/1571781762700/1571782648504
Drive with dsu unplugged stop and go working
Fingerprint below
number of messages 129:
fingerprint 36: 8, 37: 8, 114: 5, 119: 6, 120: 4, 170: 8, 180: 8, 186: 4, 238: 4, 426: 6, 452: 8, 464: 8, 466: 8, 467: 8, 544: 4, 545: 5, 548: 8, 550: 8, 552: 4, 562: 4, 608: 8, 610: 5, 643: 7, 705: 8, 725: 2, 740: 5, 764: 8, 800: 8, 824: 8, 835: 8, 836: 8, 849: 4, 869: 7, 870: 7, 871: 2, 888: 8, 896: 8, 900: 6, 902: 6, 905: 8, 911: 8, 916: 1, 918: 7, 921: 8, 933: 8, 944: 6, 945: 8, 951: 8, 955: 8, 956: 8, 979: 2, 992: 8, 998: 5, 999: 7, 1000: 8, 1001: 8, 1002: 8, 1008: 2, 1014: 8, 1017: 8, 1041: 8, 1042: 8, 1043: 8, 1056: 8, 1059: 1, 1076: 8, 1077: 8, 1114: 8, 1160: 8, 1161: 8, 1162: 8, 1163: 8, 1164: 8, 1165: 8, 1166: 8, 1167: 8, 1176: 8, 1177: 8, 1178: 8, 1179: 8, 1180: 8, 1181: 8, 1182: 8, 1183: 8, 1191: 8, 1192: 8, 1196: 8, 1197: 8, 1198: 8, 1199: 8, 1200: 8, 1201: 8, 1202: 8, 1203: 8, 1212: 8, 1227: 8, 1228: 8, 1235: 8, 1237: 8, 1279: 8, 1552: 8, 1553: 8, 1555: 8, 1556: 8, 1557: 8, 1561: 8, 1562: 8, 1568: 8, 1569: 8, 1570: 8, 1571: 8, 1572: 8, 1584: 8, 1589: 8, 1592: 8, 1593: 8, 1595: 8, 1656: 8, 1664: 8, 1728: 8, 1745: 8, 1779: 8, 1904: 8, 1912: 8, 1990: 8, 1998: 8, 2015: 8, 2016: 8, 2024: 8

**Comment by rbiasini** [comment]
@autolock , do you have a drive with DSU plugged in? We need it to fully verify your fingerprint.
Thanks.

**Comment by autolock** [comment]
@rbiasini 

https://my.comma.ai/91b2d713c6532166/1572829312599/1572829878014

**Comment by rbiasini** [comment]
@autolock you should add the fingerprint to the list, instead of deleting the existing one.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
