### PR TITLE
CI: Add GH Actions workflow Bot to check for a PR template

### LINKED ISSUE #30715: [$100 bounty] Setup a PR review bot
To start, I'm thinking the bot's review just consists of checking that a template is filled out in the PR body. 
* keep PRs as drafts until the bot is done with its "review"
* also add a special `bot-review` label while a PR is in the bot review phase
* must run in GitHub Actions

Set this up on your own fork of openpilot, then make a PR here.

### PR DESCRIPTION
**Pull request by mowoe**
This PR adds a very simple Bot which checks all opened PRs for the usage of templates.
It uses the [github-script](https://github.com/actions/github-script) action, which runs JS code inside of GH Actions. This ensures this Bot is low maintenance and immune to sudden API changes on the GH side.

The list of available templates is dynamically loaded every time (all files in `.github/PULL_REQUESTS_TEMPLATE`).
Templates are identified via their `name` and `about` tag and this also gets compared to the PR description to determine if it matches.

If the PR does not use a template, the Bot adds a comment asking the contributor to do so. If the contributor changes the PR description, the Bot runs again and deletes the prior comment if a template is now used.

At the start of the GitHub Action Run, the Bot adds the `in-bot-review` label, which it removes as soon as its done.

Unfortunately, the GitHub Api does not support converting PRs to Drafts: https://github.com/orgs/community/discussions/45174#discussioncomment-5510542, so this is a missing feature from the bot.

The code got a bit longer than i would have liked, but i think it is still relatively manageable.

It is tested in my fork.
Example of a PR not using a template: [PR 2](https://github.com/mowoe/openpilot/pull/2)
Example of a PR using a template: [PR 1](https://github.com/mowoe/openpilot/pull/1)

### CODE REVIEW

**Comment by mowoe** [comment]
For #30715

**Comment by adeebshihadeh** [comment]
@jnewb1 can you review and merge this if it's good?

**Comment by jnewb1** [comment]
this top part in the pull request template is just metadata for github, we don't want to require this in the PR, 
```
---
name: Car Bug fix
about: For vehicle/brand specific bug fixes
title: ''
labels: 'car bug fix'
assignees: ''
---
```

does it handle this correctly?

**Comment by mowoe** [comment]
@jnewb1 Okay, i see, but then im not 100% sure what a PR should look like when it is using a template.
Is it sufficient if the PR has the right headings? E.g. [the bugfix template](https://raw.githubusercontent.com/commaai/openpilot/master/.github/PULL_REQUEST_TEMPLATE/bugfix.md) basically just consists of two headings, should a PR that uses these two headings in the description be considered as using a template?
If so, i can update the existing logic a bit, but if not, i think it will get a bit more complex.

**Comment by jnewb1** [comment]
Having the headings and checkboxes is sufficient

**Comment by jnewb1** [comment]
- can we keep the in-bot-review if it doesn't pass? The goal would be that we only look at PR's that have passed the bot's review
- can we move it to the auto_pr_review action?

**Comment by mowoe** [comment]
Sure! I moved the workflow over (however i needed to add another trigger there because the 'edit' one isn't included by default: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) and also moved the label removal part to only run when the check has passed.

**Comment by jnewb1** [comment]
thank you for the PR!

**Comment by jnewb1** [comment]
hey @mowoe , looks like this fails when there is text added after the checkbox, can you make it so it just has to include the text rather then be an exact match?

https://github.com/commaai/openpilot/pull/31257

**Comment by mowoe** [comment]
Hi @jnewb1, sure, PR is here: #31262 
Sorry for the oversight.

**Pull request merged**
