### PR TITLE
Add Rav4 Prime Fingerprint F/W versions

### PR DESCRIPTION
**Pull request by nelsonjchen**
https://discordapp.com/channels/469524606043160576/524327905937850394/742873694036295763

matty#8553

197bedf171765156|2020-08-11--16-59-52

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can you add the RAV4 prime to the README?

**Comment by nelsonjchen** [comment]
Added. Though I want to noted that testing of Rav4 Prime won't come until matty#8553 gets a C2 setup going. matty#8553 temporarily hooked up an EON that will be on sale to get the FPv2 in a bit early.

**Comment by nelsonjchen** [comment]
Changed to draft per @VirtuallyChris

**Comment by nelsonjchen** [comment]
matty#8553 now has a C2 and is now on this branch but doesn't have a usable USB-C cable 😅 to test with. 

https://discordapp.com/channels/469524606043160576/524327905937850394/747673503976783963

When matty#8553 gets the cable, we'll provide an update.

**Comment by nelsonjchen** [comment]
Matty got comma's cable plugged in, but a CAN error pops up.

https://discordapp.com/channels/469524606043160576/524327905937850394/748711516663971901



The car firmwares are still the same and the prime is running OP that identifies this vehicle as a Rav 4 2019 Hybrid. 

Also, the new C2 and the route I looked at the log on is: 54bb533aec9ff844|2020-08-27--17-33-33

**Comment by ErichMoraga** [comment]
`    alertText1 = "CAN Error: Check Connections",` per logs.

**Comment by nelsonjchen** [comment]
matty will try his setup on another toyota sometime and see if the issue is hardware. 

If he can't find someone, I'll be in ~LA next next week.

**Comment by nelsonjchen** [comment]
today's log:

https://discordapp.com/channels/469524606043160576/524327905937850394/749378031411527781

We tried Matty's setup on another Rav4. Things seem to work fine.

54bb533aec9ff844|2020-08-29--14-12-21 btw, for the other Rav 4. VIN ends in KD524915

We moved it back to the Rav4 Prime. The CAN Error came up again.

Matty set me up for sshing into his Comma 2. I saw this in tmux.



I found this post from vanillagorilla talking about a similar issue in discord: https://discordapp.com/channels/469524606043160576/524327905937850394/610127435698143270

We'll look into what might be up with the DBC and checksum stuff next Saturday when I'm in LA.

___

gah, this was supposed to be a simple fingerprint but getting it to work on the fastest real toyota is gonna be awesome!

**Comment by nelsonjchen** [comment]
The `CHECKSUM FAIL` ECUs are the `STEERING_LKA` and `PRE_COLLISION` ECUs. Is it possible that they may have changed the checksum algorithm? 

https://github.com/commaai/opendbc/blob/b875f970fc6ddad5befe2f6831f4bcda354d8bea/can/common.cc#L16

**Comment by nelsonjchen** [comment]
image

The checksum area doesn't seem to be a single byte now.

Ick, I think this is going beyond a fingerprint worthy of opening an issue up by itself.

**Comment by nelsonjchen** [comment]
#2103 seems to show a new checksum for Toyota steering and pre collision that is currently unknown and there is much more work than a simple fingerprint. The 2021 Rav4 Prime also definitely *does not talk steering and pre-collision like a Rav4 Hybrid* so categorizing it as a Rav4 Hybrid also is incorrect. 

Perhaps a future version of OP may support the new Toyota checksum and a future PR for Rav4 Primes may reference the firmware versions mentioned here. Until then, I will close this PR to remove an unactionable PR from the list of open PRs.

**Comment by nelsonjchen** [comment]
> Anyone tried this with the C3?

I did with a C3 far later, like a year later. No, it doesn't magically solve the security key / can message signing issue.

https://github.com/commaai/openpilot/discussions/19932

**Comment by petermhuber** [comment]
I just purchased a RAV4 Prime and purchased a Comma 3 in the hopes of improving its lane keeping ability.  Is there any hope that the Comma 3 will work in a 2023 RAV4 Prime?

**Comment by nelsonjchen** [comment]
> I just purchased a RAV4 Prime and purchased a Comma 3 in the hopes of improving its lane keeping ability. Is there any hope that the Comma 3 will work in a 2023 RAV4 Prime?

The status summary is here: 

https://github.com/commaai/openpilot/discussions/19932#:~:text=has%20been%20done.-,Status,-%3A%20There%20is%20currently

**Pull request closed without merging**
