### PR TITLE
Refactor modeld

### PR DESCRIPTION
**Pull request by deanlee**
use opencl c++ bindings : http://github.khronos.org/OpenCL-CLHPP/

- [ ] move loadyuv and tranform into class ModelFrame
- [ ] fewer buffer copies

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
@deanlee can you add the appropriate labels?

**Comment by deanlee** [comment]
Labels for what? PR? only you guys have write access can assign labels

**Comment by adeebshihadeh** [comment]
Yeah, I guess that's the case. I'll get the PR templates setup which should let you assign them when you open the PR.

**Comment by pd0wm** [comment]
I'm a little reluctant with this PR. It's a lot of changes for code that is working perfectly fine, with the risk of a lot of subtle bugs.

Is this fixing any concrete bugs/issues?

**Pull request closed without merging**
