### PR TITLE
GM: Car Port for XT4 2023

### PR DESCRIPTION
**Pull request by garrettpall**
**Car**
Cadillac XT4 2023

**Route**
162796f1469f2f1b/00000005--6f334eda14

**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: 162796f1469f2f1b/00000005--6f334eda14
- [x] route with stock system: 162796f1469f2f1b/00000003--79f5d5854f (old harness design)
- [x] car harness used (if comma doesn't sell it, put N/A): N/A

### CODE REVIEW

**Comment by garrettpall** [comment]
Panda and Openpilot PR rebased 12/21. Have not tested yet, but will once requested. This Car Port requires a new harness to be made.

XT4_Wiring
image
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/garrettpall/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/garrettpall/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


Mouser #: | Mfr. #: | Desc.: | Order Qty.
-- | -- | -- | --
571-2272196-2 | 2272196-2 | Automotive Connectors Automotive Connectors GEN 50,TERMINAL | 20
571-2309644-4 | 2309644-4 | Automotive Connectors Automotive Connectors 30P NANOMQS/US050 LL CONN,   W/CPA, KEY D | 1
571-1-2236905-1 | 1-2236905-1 | Automotive Connectors Automotive Connectors NANO TAB 0.5X0.4,TERMINAL | 20



</body>

</html>

**Comment by garrettpall** [comment]
This PR would also support adding the 2019 Chevy Volt as a supported car.

**Comment by garrettpall** [comment]
https://github.com/garrettpall/GMSDGMConnector/blob/main/Connector.stl

**Comment by adeebshihadeh** [comment]
How does the harness work on this car? Does it require unplugging the ASCM like the currently supported Volts or is this a normal setup (i.e. does it completely fall back to the stock system if the C3X is unplugged)?

**Comment by garrettpall** [comment]
@adeebshihadeh The ASCM does not get unplugged/bypassed and AEB is retained. This means longitudinal support is with the stock ACC system. The harness only intercepts the powertrain bus at the SDGM (serial data gateway module) under the dash above the obd port as the camera only has the object bus.

**Comment by garrettpall** [comment]
This port is confirmed working on a 2022 Buick Envision too with fingerprint forced to XT4.

**Comment by garrettpall** [comment]
So far only the XT4 has a steering cutoff of 30 mph. Every other SDGM car has been 6 mph

**Comment by garrettpall** [comment]
I think I found a way to make the SDGM port almost identical to the CAM car port. Just need a harness wiring change that I will test this weekend.

**Comment by garrettpall** [comment]
I have tested the new harness design and updated this PR. I currently have chassis hooked up to bus 1 in my car to gather data on brake messages, but will be switching to object soon. I recommend object be connected to bus 1 for future use (ie. possibility of corner radar points and front radar point to support a SDSU type hardware to get op longitudinal support).

Not only does this new harness slim down the port even more, but it also removes the comma from the middle of the main PT bus.

Harness can be seen here: https://github.com/garrettpall/GMSDGMConnector

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
