### PR TITLE
CI: enable virtual audio sink for soundd

### LINKED ISSUE #31100: [100$ bounty] virtual sound card in openpilot docker image
Setup a virtual sound card in the docker image with a bash script, similar to setup_xvfb.sh (which is for X11), with the purpose of being able to run soundd for a full e2e test of openpilot.

Requirements:
- soundd must run within the docker image, sound does not need to be audible (i.e. it can go to a null sink)
- single setup script

### PR DESCRIPTION
**Pull request by bongbui321**
**Description**
I enable virtual audio sink for soundd to be used in CI

**Verification**

I tested by running the script `./selfdrive/test/setup_vsound.sh && python3 selfdrive/ui/soundd.py` in docker container. Before it would not be able to find an output device. If there is more testing you want me to do lmk

### CODE REVIEW

**Comment by jnewb1** [comment]
getting this error over here: https://github.com/commaai/openpilot/pull/31121, seems like it might have to do with running as root?

```
docker run  --gpus=all -v ~:/root -v /tmp/.X11-unix -e DISPLAY -it -e PYTHONPATH=/tmp/openpilot -w /tmp/openpilot -v $(pwd):/tmp/openpilot 4ece08cb0042 bash -c "source selfdrive/test/setup_xvfb.sh && source selfdrive/test/setup_vsound.sh && pytest -m "slow" -Wignore tools/sim/tests/test_metadrive_bridge.py"
```

```
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [pulseaudio] main.c: Daemon startup failed.
```

**Comment by jnewb1** [comment]
ah, nvm it was because I mounted the home directory

**Comment by bongbui321** [comment]
@jnewb1 hmm I think this is a problem with starting pulseaudio -D. I'll look into it

**Comment by jnewb1** [comment]
it works fine now, it was because I mounted the home folder and it couldn't write to it

**Pull request merged**
