### PR TITLE
wifiManager: fix for lteConnectionPath not set on boot

### LINKED ISSUE #29205: APN disappears on reboot.
### Describe the bug

Comma 3 APN vanishes when powered off at next boot, to re establish network APN must be entered again.
This is not with a comma SIM, in Canada, have prime light.

Release 3 branch.

Route before shutdown with LTE working fine:

72c8dc9054796c61|2023-08-01--06-27-36

Route where APN disappears at boot and has to entered again:

72c8dc9054796c61|2023-08-01--15-44-13

### Provide a route where the issue occurs

72c8dc9054796c61|2023-08-01--15-44-13

### openpilot version

0.9.4

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by andiradulescu**
Fixes https://github.com/commaai/openpilot/issues/29205. This was pretty hard to catch because I could only reproduce it on release builds, so for every change I tried, I had to use `build_release.sh` to rebuild a release version. Unfortunately, I couldn't understand why it happens only on release builds.

The logic behind this fix is that `lteConnectionPath` needs to be set before `updateGsmSettings` is called. Otherwise `updateGsmSettings` will not do anything. I moved `initConnections()` from `setup()` since `setup()` is called conditionally. Ideally I would see a refactor where a separate `LteManager` exists besides `WifiManager`.

On non-release builds on boot:
- selfdrive/ui/qt/offroad/settings.cc: Networking is instantiated
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::setup
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::initConnections
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::updateGsmSettings
- selfdrive/ui/qt/network/wifi_manager.cc: Changing gsm.auto-config to false
- selfdrive/ui/qt/network/wifi_manager.cc: Changing gsm.apn to "net"
- selfdrive/ui/qt/network/wifi_manager.cc: Changing gsm.home-only to true
- selfdrive/ui/qt/network/wifi_manager.cc: Changing connection.metered to 2
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::activateModemConnection

On release builds on boot:
- selfdrive/ui/qt/offroad/settings.cc: Networking is instantiated
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager QDBusConnection::systemBus().connect(...) is called
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::updateGsmSetting is called but lteConnectionPath is empty
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::deviceAdded
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::setup
- selfdrive/ui/qt/network/wifi_manager.cc: WifiManager::initConnections
- WifiManager::updateGsmSettings is not called anymore, so lte remains unconnected and without apn and other settings

Separately, only on release builds this error is thrown, even with the fix applied - on non-release builds this is not thrown:
```
Error getting hardware state
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/thermald/thermald.py", line 156, in hw_state_thread
    if not modem_configured and len(HARDWARE.get_sim_info().get('sim_id', '')) > 0:
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/hardware/tici/hardware.py", line 183, in get_sim_info
    modem = self.get_modem()
            ^^^^^^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/hardware/tici/hardware.py", line 171, in get_modem
    modem_path = list(objects.keys())[0]
                 ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
`configuring modem`comes a couple of lines later and this time it works. I could also fix this, so it's not thrown anymore.

I tested everything using:
- A branch with multiple logs - https://github.com/andiradulescu/openpilot/tree/fix-apn-disappears-on-boot-dev
- My own release3 - https://github.com/andiradulescu/openpilot/tree/release3 - currently has this fix applied
- `tmux a` usually started it immediately after boot to check the logs

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Thanks for looking into this. I haven't looked closely at your write up yet, but I'd bet the root cause (of both the APN issue and the thermald error) is the faster boot times in recent releases. Release builds launch openpilot much more quickly; you can test this by adding/removing the `prebuilt` file in the root.

**Comment by andiradulescu** [comment]
Thanks for telling me about `prebuilt`, now I know what `release` builds have different.

But, with `touch prebuilt` the thermald fails also the second time:
```
Error getting hardware state
Traceback (most recent call last):
  File "/data/openpilot/selfdrive/thermald/thermald.py", line 158, in hw_state_thread
    HARDWARE.configure_modem()
  File "/data/openpilot/openpilot/system/hardware/tici/hardware.py", line 521, in configure_modem
    sim_id = self.get_sim_info().get('sim_id', '')
             ^^^^^^^^^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/hardware/tici/hardware.py", line 183, in get_sim_info
    modem = self.get_modem()
            ^^^^^^^^^^^^^^^^
  File "/data/openpilot/openpilot/system/hardware/tici/hardware.py", line 170, in get_modem
    objects = self.mm.GetManagedObjects(dbus_interface="org.freedesktop.DBus.ObjectManager", timeout=TIMEOUT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expi
red, or the network connection was broken.
```

`configuring modem` comes the third time and now is succesful.

Of course, with `prebuilt` APN is not set on boot, as with `release` builds.

**Comment by andiradulescu** [comment]
As for `WifiManager`, this happens:

wifi_manager

On `prebuilt` it goes on `else`, and `setup()` is called when `deviceAdded` is called (too late).

But, `initConnections()` should be called in the constructor so that it sets `lteConnectionPath` upfront. Not sure about `knownConnections`, but I don't see why would it be bad for `knownConnections` to also be set in the constructor.

Also, `setup()` should only do `wifi` related things (e.g. `setupWifi`), since `adapter = getAdapter();` is actually `adapter = getAdapter(NM_DEVICE_TYPE_WIFI);`.

**Comment by adeebshihadeh** [comment]
We just need to do some validation on this. I'll add it to the 0.9.6 milestone so it gets some attention before pushing the next release.

The linked changes are somewhat unrelated; this PR just reminded me of them.

**Pull request merged**
