### PR TITLE
Missing Fingerprint values for 2020 Chrysler Pacifica

### PR DESCRIPTION
**Pull request by TheWizard1328**
Missing Fingerprint values for 2020 Chrysler Pacifica

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can you rebase? What's your dongle ID?

**Comment by TheWizard1328** [comment]
Just did rebase.
Dongle ID: 8a84e5027e568485

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542<tel:(780)%20236-1542>
www.Facebook.com/WizardWorxx13<http://www.Facebook.com/WizardWorxx13>

**Comment by adeebshihadeh** [comment]
There's still a conflict.

**Comment by adeebshihadeh** [comment]
Added your values in c736b7e5bb928b42c22a9acf0fb33ff43ae3c0cc.

**Pull request closed without merging**
