### PR TITLE
athenad: fix memory leak in `_do_upload()`

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Nice fix! @sshane can you test this?

**Comment by sunnyhaibin** [comment]
Nice!

**Review by thegauravgiri — APPROVED** [review]
Looks good to me

**Comment by sunnyhaibin** [comment]
> Looks good to me

Please stop spamming every PR with the same message.

**Comment by adeebshihadeh** [comment]
Banned from the org for spam.

**Comment by sshane** [comment]
With athenad.py checked out on master:

```python
======================================================================
FAIL: test_do_upload_0 (__main__.TestAthenadMethods.test_do_upload_0) (_type='_io.BytesIO')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/batman/openpilot/selfdrive/athena/tests/./test_athenad.py", line 164, in test_do_upload
    self.assertLess(total_size / 1024, 10, f'Object {_type} ({num_objects=}) grew larger than 10 kB while uploading file')
AssertionError: 10043.361328125 not less than 10 : Object _io.BytesIO (num_objects=1) grew larger than 10 kB while uploading file

----------------------------------------------------------------------
Ran 24 tests in 14.808s

FAILED (failures=1)
```

**Pull request merged**
