### PR TITLE
Add support for minimum steer speed alerts for Honda and Acura

### PR DESCRIPTION
**Pull request by annabarnes1138**
Currently only Chrysler and Hyundai models alert the driver if the speed drops below the minimum steer speed. This PR is to add this alert to Honda models

### CODE REVIEW

**Comment by geohot** [comment]
Why is CI failing?

And is it audible, or only visual?

**Comment by stecky** [comment]
Sorry... been out of town for a few days... I'll take a look at why CI is failing. Yes, it is both audible and visual

**Comment by stecky** [comment]
Looks like my code is generating `belowSteerSpeed` events that are unexpected when comparing the output to the reference segments found at https://commadataci.blob.core.windows.net/openpilotci. I'm guessing I would need azure credentials to update those?

**Comment by rbiasini** [comment]
the lower the speed, the less relevant is the loss of steering. I would like to avoid bothering the driver for a very repeatable behavior. Maybe only a visual alert with no sound if minSteerSpeed is < 15 mph? Otherwise both sound and visual alert sounds fine.

**Comment by berno22** [comment]
Totally agree with @rbiasini, just visual is enough!

**Comment by stecky** [comment]
I can deal with visual only, but I did want to stress that I don't agree with your assessment that lower speed is less relevant. If you drift over into opposing traffic that is traveling at 70mph it's going to be bad whether you are going 55 or 5

**Comment by VirtuallyChris** [comment]
Is there a way to have an alert based on not only the EPS cutting out, but also the car being X amount of feet drifted away from the planned path? I feel this could be good if on a curve in traffic where the car is under 12mph for a sustained amount of time and ends up drifting into another lane - but would also not alert the driver unless openpilot believed it was far off from center.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Pull request closed without merging**
