### PR TITLE
ui: ignore tap to wake device 

### LINKED ISSUE #28655: ui: ignore tap to wake device
Now that we have nav entry on home screen, you often press a random destination every time you tap to wake. @deanlee intetested in this?

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/openpilot/issues/28655

### CODE REVIEW

**Comment by sshane** [comment]
What happens if you cause a `TouchBegin` while the screen is off, then release causing a `TouchEnd` while the screen is on? Would it click the button under it or does it need both `TouchBegin` and `TouchEnd`?

**Comment by deanlee** [comment]
This is indeed a problem. Especially the handling of mouse press/release events.

**Comment by sshane** [comment]
the sidebar uses manual touch events it looks like

**Comment by deanlee** [comment]
reverted to the first vision: "ignore events before wake up", looks like it's the right solution.

> What happens if you cause a TouchBegin while the screen is off, then release causing a TouchEnd while the screen is on? Would it click the button under it or does it need both TouchBegin and TouchEnd?

After reading the qt source code, I'm sure that the widget will not receive  `TouchEnd` or `MouseButtonRelease` events if `TouchBegin`/`MouseButtonPressed` is filtered.


[qt_button_down](https://codebrowser.dev/qt5/qtbase/src/widgets/kernel/qwidgetwindow.cpp.html#qt_button_down) will be nullptr if `TouchBegin`/`MouseButtonPressed` is filtered. this will prevent subsequent touch/mouse events from being sent to any window:
https://codebrowser.dev/qt5/qtbase/src/widgets/kernel/qwidgetwindow.cpp.html#_ZN13QWidgetWindow16handleMouseEventEP11QMouseEvent

**Comment by sshane** [comment]
works on PC, thanks!

**Pull request merged**
