### PR TITLE
Toyota: 2021+ RAV4 Prime

### PR DESCRIPTION
**Pull request by pd0wm**
> [!IMPORTANT]  
> Before trying this PR, ensure the `SecOCKey` param is set with the correct key for your vehicle.
> `echo -n "ffffffffffffffffffffffffffffffff" > /data/params/d/SecOCKey`

FW versions from `20ba9ade056a8c7b`. Example route: `20ba9ade056a8c7b|2021-02-08--21-57-35`. 

TODO:

- [x] Read key from param. Added to carParams, otherwise route wouldn't be reproducible without fetching the key from initData.
- [x] Doesn't show up as a supported car
- [ ] Figure out if layout of `PRE_COLLISION` changed for stock AEB detection. (not a blocked for the port)
- [x] Replace missing `GEAR_PACKET`
  - [x] Check if weird `GEAR_PACKET_HYBRID.COUNTER` is Rav4 specific.
- [ ] Replace missing `PCM_CRUISE`
  - [ ] Implement gas pressed from new `GAS_PEDAL` message. (Still missing in panda) 
  - [ ] Find new cruise state signal (e.g. nonAdaptive)
- [x] Replace missing `BRAKE_MODULE`
- [ ] Add proper alerts for missing/wrong `SecOCKey`
- [ ] Add flags for panda safety mode for alternate Brake/Gas messages
  - [ ] Ensure tests between panda and CarState match
- [x] Test if ACC Cancel spam works. Looks like the `ACCEL_CMD` was moved to a message with SecOC, but the `CANCEL_REQ` is still in the old message without MAC.

## Missing `PCM_CRUISE`.
There seems to be a new message on `0x1a2` that has a bit that corresponds to `ACCEL_CMD_ALT != 0`. `0x1a2` seems to be a different message than other TSS2 cars.

## Missing `GEAR_PACKET`/ `GEAR_PACKET_HYBRID`
There is no `GEAR_PACKET`, but `GEAR_PACKET_HYBRID` seems a good replacement. The `COUNTER` doesn't seem to be a real counter. ~Removed it, but check if this is a Rav4 Prime specific quirk.~ Counter is also fake on a Corolla Hybrid route.

I'm switching to the new message automatically when `GEAR_PACKET` is missing, but `GEAR_PACKET_HYBRID` is present. I need to check if this doesn't break any other cars.

## Missing `BRAKE_MODULE`

There seem to be two new messages related to the brakes `0xfc` and `0x101`. Unfortunately they are not present on other models, so they can't be compared directly. I was only able to reference against `PCM_CRUISE_2.BRAKE_PRESSED`.

I put the new messages in the SecOC dbc for now. Let's see if all SecOC cars switched to this new message, or if this is a quirk for the RAV4 Prime specifically.

2024-01-29-133018_811x834_scrot

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
I added a TODO to make sure this doesn't show up in the docs as supported.

> * [ ]  Figure out if layout of `PRE_COLLISION` changed for stock AEB detection.

No need to block the port on this.

**Comment by adeebshihadeh** [comment]
> What do I need to check to make sure it's not showing up as supported? It's not in the `CAR_INFO` list, and rerunning `docs.py` seems to cause no changes.

I think you'll need to set it to None in CarInfo. cc @sshane

**Comment by sshane** [comment]
Yes None should work. It won't have its fingerprints auto updated with our bot though

**Comment by spawahh** [comment]
Let me know if you want a route from the bZ4X.

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Comment by nelsonjchen** [comment]
[Willem: "If somebody wants to finish the rav4 prime port, feel free to take my code and reopen the PR"](https://discord.com/channels/469524606043160576/905950538816978974/1283870817393971322)

**Pull request closed without merging**
