### PR TITLE
attempt revert

### PR DESCRIPTION
**Pull request by BBBmau**

### CODE REVIEW

**Comment by sshane** [comment]
What is this for?

**Comment by BBBmau** [comment]
> What is this for?

this is just looking into why CI is failing suddenly. I noticed fails from a PR i opened yesterday but thought that it was a one time thing.

**Comment by sshane** [comment]
selfdrive/modeld/tests/test_modeld.py::TestModeld::test_dropped_frames does seem to be taking longer, it failed on master as well. I don't see how this causes it though

**Comment by BBBmau** [comment]
I'll close this since a rerun of the commit resulted in CI passing, although I'm not sure why other PRs are failing?

**Comment by BBBmau** [comment]
I was more referring to this failure:
```
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/sqldata.py", line 294, in _read_db
INTERNALERROR>     assert row is not None
INTERNALERROR>            ^^^^^^^^^^^^^^^
INTERNALERROR> AssertionError
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/data.py", line 169, in combine_parallel_data
INTERNALERROR>     new_data.read()
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/sqldata.py", line 844, in read
INTERNALERROR>     with self._connect():
INTERNALERROR>          ^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/sqldata.py", line 344, in _connect
INTERNALERROR>     self._open_db()
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/sqldata.py", line 287, in _open_db
INTERNALERROR>     self._read_db()
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/sqldata.py", line 299, in _read_db
INTERNALERROR>     raise DataError(
INTERNALERROR> coverage.exceptions.DataError: Data file '/tmp/openpilot/.coverage.4124688dc3be.153.XCtiVTdx' doesn't seem to be a coverage data file: 
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pluggy/_callers.py", line 156, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pytest_cov/plugin.py", line 339, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pytest_cov/engine.py", line 46, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pytest_cov/engine.py", line 355, in finish
INTERNALERROR>     self.cov.combine()
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/control.py", line 837, in combine
INTERNALERROR>     combine_parallel_data(
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/data.py", line 174, in combine_parallel_data
INTERNALERROR>     data._warn(str(exc))
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/coverage/control.py", line 438, in _warn
INTERNALERROR>     warnings.warn(msg, category=CoverageWarning, stacklevel=2)
INTERNALERROR> coverage.exceptions.CoverageWarning: Data file '/tmp/openpilot/.coverage.4124688dc3be.153.XCtiVTdx' doesn't seem to be a coverage data file: 
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/_pytest/main.py", line 285, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/_pytest/main.py", line 339, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pluggy/_callers.py", line 160, in _multicall
INTERNALERROR>     _warn_teardown_exception(hook_name, teardown[1], e)
INTERNALERROR>   File "/home/batman/pyenv/versions/3.11.4/lib/python3.11/site-packages/pluggy/_callers.py", line 50, in _warn_teardown_exception
INTERNALERROR>     warnings.warn(PluggyTeardownRaisedWarning(msg), stacklevel=5)
INTERNALERROR> pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
INTERNALERROR> Plugin: _cov, Hook: pytest_runtestloop
INTERNALERROR> CoverageWarning: Data file '/tmp/openpilot/.coverage.4124688dc3be.153.XCtiVTdx' doesn't seem to be a coverage data file: 
INTERNALERROR> For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
```

**Pull request closed without merging**
