### PR TITLE
replace unlogger.py with c++ replay

### PR DESCRIPTION
**Pull request by pd0wm**
Thanks to @deanlee!

rqplot is replaced by plotjuggler

### CODE REVIEW

**Comment by doktorsleepelss** [comment]
It would be nice to keep unlogger around for use with WSL because the new replay doesn't work with it.

**Comment by pd0wm** [comment]
Is this because OpenCL is not supported?

**Comment by grekiki** [comment]
Seems like it. UI works fine here on WSL, but replay gives
```
seeking to 0
downloading segment 0 ...
downloading segment 1 ...
downloading segment 2 ...
replay: selfdrive/common/clutil.cc:63: cl_device_id cl_get_device_id(cl_device_type): Assertion `CL_SUCCESS == (clGetPlatformIDs(0, __null, &num_platforms))' failed.
```

**Comment by pd0wm** [comment]
@grekiki Does https://github.com/commaai/openpilot/pull/22431 work?

**Comment by grekiki** [comment]
@pd0wm  Works nicely :)
image

**Pull request merged**
