### PR TITLE
Hyundai: add fwdCamera FW for Ioniq 5 2024 (EUR)

### PR DESCRIPTION
**Pull request by MAkcanca**
Adding FW fingerprints for Ioniq 5 2024 EU, non-HDA, fwd camera

**Car**
Hyundai Ioniq 5 2024, EU, Non-HDA version. 
Hyundai K connector

**Route**
4e0550a3bf377740/2024-06-06--12-32-47/0

### CODE REVIEW

**Comment by sshane** [comment]
Can you fingerprint and engage with openpilot so we can gather some data?

**Comment by MAkcanca** [comment]
@sshane A longer trip with lots of data
4e0550a3bf377740/2024-06-08--20-57-36/0

**Comment by MAkcanca** [comment]
@sshane Sorry! I missed the part where I needed to run my own branch. Here is the route 4e0550a3bf377740/00000001--684b000631/0

**Comment by sshane** [comment]
Hyundai Q makes sense as you have the ADAS ECU which usually comes with HDA2 vehicles.

**Comment by sshane** [comment]
Starting to look good (still gathering data)

image

**Comment by MAkcanca** [comment]
@sshane Thank you for investigating :) I really appreciate it. That route 4e0550a3bf377740/00000000--d5143d6c59/0 for me only has a single problem that happens in segment 21. It gets close to road rails while taking a sharp turn in slow speeds. I also uploaded camera data for that segment. 

Today I will try to do more driving with different routes.

**Comment by sshane** [comment]
| Dongle, platform, VIN                                                                                                      | Name from VIN 🆚 CarDocs                                  | Segments                                  | Bad seg tags                                                                                                                                                                                                                                                                                                                                                                                                           | Good seg tags                                                                        |
|:---------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------|:------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------|
| [4e0550a3bf377740](https://useradmin.comma.ai/?onebox=4e0550a3bf377740)<br><sub>HYUNDAI_IONIQ_5<br>KMHKR81BF........</sub> | HYUNDAI  1994 🆚<br>Hyundai Ioniq 5 (with HDA II) 2022-24 | 23 routes,<br>448 segments<br>(7.5 hours) | - [spotty FW: 2](https://useradmin.comma.ai/?onebox=4e0550a3bf377740%7C00000000--b929ec580f)<br>- [VIN spotty (info): 1](https://useradmin.comma.ai/?onebox=4e0550a3bf377740%7C00000000--b929ec580f)<br>- [CAN invalid: 1](https://useradmin.comma.ai/?onebox=4e0550a3bf377740%7C00000000--b929ec580f)<br>- [high lateral accel factor: 5](https://useradmin.comma.ai/?onebox=4e0550a3bf377740%7C00000000--d5143d6c59) | - valid torque params: 419<br>- all lat active: 190<br>- no input all lat active: 51 |

![image](https://github.com/commaai/openpilot/assets/25857203/3ee688cc-a0af-430d-85c7-682ce50159f3)

**Pull request merged**
