### PR TITLE
ui/android/text: convert text.c to text.cc

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Unless there's a reason for this, I don't want to merge changes to any of the android UI stuff as we'll be moving to Qt soon.

**Comment by deanlee** [comment]
just want to convert touch.c into class TouchState. If it is not necessary, I will close these two PRs

**Comment by adeebshihadeh** [comment]
Once we’re using Qt, we shouldn’t need to handle touch events ourselves.

**Comment by deanlee** [comment]
OIC

**Pull request closed without merging**
