### PR TITLE
Multilang: th translation update

### PR DESCRIPTION
**Pull request by Iamz**
Update Thai translations

### CODE REVIEW

**Comment by sshane** [comment]
Btw if you want to get this language in release, look into fixing the Thai fonts in AGNOS. Or let me know if they work already

**Comment by Iamz** [comment]
> Btw if you want to get this language in release, look into fixing the Thai fonts in AGNOS. Or let me know if they work already

It seems fine to me. Is there anything specific I should look for?

**Comment by sshane** [comment]
just checked, it looks good to me now! when we first added thai, the font was blocky. I guess it was fixed in an AGNOS update since then

**Comment by sshane** [comment]
https://github.com/commaai/openpilot/pull/29447

**Pull request merged**
