### PR TITLE
logreader: support reading from corrupt log

### PR DESCRIPTION
**Pull request by deanlee**
1. logreader: support reading from corrupt log
2. logreader&framereader: support reading from buffer.

### CODE REVIEW

**Comment by pd0wm** [comment]
Does this fix the replay getting stuck if the last log is corrupt?

**Comment by deanlee** [comment]
no, I think it can’t. where is it stuck ?  Is it in decompressbz2 or FlatArrayMessageReader?

**Comment by pd0wm** [comment]
Will do some more investigation the next time it happens.

**Comment by deanlee** [comment]
@pd0wm  It's stuck in decompressbz2 if log is corrupt

**Pull request merged**
