### PR TITLE
Hyundai: remove Kona EV and Ioniq 6 from radar-ACC set

### PR DESCRIPTION
**Pull request by sshane**
All dongles have ADAS ECU in carFw, not sure why it was added

### CODE REVIEW

**Comment by haram-KONA** [comment]
KONA_EV_2ND_GEN also has "ADAS ECU" in the car firmware.
Is this different from Ioniq 6 ?

**Comment by sshane** [comment]
@sunnyhaibin any issues with the ADAS ECU disable? or should we add to unsupported long for now?

**Comment by haram-KONA** [comment]
> All dongles have ADAS ECU in carFw, not sure why it was added

I drove the KONA_EV_2ND_GEN vehicle excluding the "CANFD_RADAR_SCC_CARC" list and it operates very well without any abnormalities. 
However, I would appreciate it if you could check the status.
drive route is " 1618132d68afc876|2023-10-12--13-05-32--16 " 

All routes (1618132d68afc876|2023-10-12--13-05-32) have the same conditions. (excluded CANFD_RADAR_SCC_CAR list)

**Comment by sshane** [comment]
@haram-KONA Can you try OP long? If it doesn't work we'll need to add to the unsupported long list

**Comment by haram-KONA** [comment]
> @haram-KONA Can you try OP long? If it doesn't work we'll need to add to the unsupported long list

Setting OP long will result in a "Hardware Fault" warning.

**Comment by sshane** [comment]
Do you have a route?

**Comment by haram-KONA** [comment]
> Do you have a route?

1618132d68afc876|2023-10-13--13-42-36--0

**Comment by sshane** [comment]
@haram-KONA try the branch now with your car removed

**Comment by sshane** [comment]
Changed this to be a simple refactor. Splits some diff from https://github.com/commaai/openpilot/pull/30033

**Pull request merged**
