### PR TITLE
simulator: Only print sim state on state change

### PR DESCRIPTION
**Pull request by mimi89999**
Stops the spam in the terminal

### CODE REVIEW

**Comment by mimi89999** [comment]
I could also do that in setters in SimulatorState if that would be preferred.

**Comment by jnewb1** [comment]
can we just print the status on any keystroke so we don't have to add a bunch of conditions for things that might change later?

**Review by jnewb1 — COMMENTED** [review]
can we just print the status on any keystroke so we don't have to add a bunch of conditions for things that might change later?

**Comment by mimi89999** [comment]
> can we just print the status on any keystroke so we don't have to add a bunch of conditions for things that might change later?

Not really as I would prefer the bridge to inform when the status changes.

I updated the PR and now I'm using setters in `SimulatorState`. Now if somebody changes the logic, they won't need to update the logging code.

**Pull request closed without merging**
