### PR TITLE
Slightly more compatible Highlander fingerprints

### PR DESCRIPTION
**Pull request by ErichMoraga**
As discussed with Daehyuk, Arne, and HskrOP on Discord in #help...
https://discordapp.com/channels/469524606043160576/524592892627517450/576451670268051480

PR change is the same as seen in @arne182's fork...
https://github.com/arne182/openpilot/blob/release2/selfdrive/car/toyota/values.py

Additional modification(s) may be required later, but this is apparently a step in the right direction.

### CODE REVIEW

**Comment by arne182** [comment]
I thought I clearly said that comma wants to keep trims seperate.

**Comment by ErichMoraga** [comment]
...and I agreed with that, yet the groups seemed to agree there's a compatibility issue with the current values.  Feel free to propose change(s).

**Comment by rbiasini** [comment]
If you guys can give us the dongleID of users who had fingerprint issue, we'll handle the rest. How is that?
I'm really tempted to merge this PR and https://github.com/commaai/openpilot/pull/631, but then it will be hard to keep adding new models in the future.

**Comment by ErichMoraga** [comment]
Sent IDs to you via Discord.

**Pull request closed without merging**
