### PR TITLE
cabana: dynamically switch between OpenGL

### PR DESCRIPTION
**Pull request by pd0wm**
Continuation of https://github.com/commaai/openpilot/pull/27145

Actually, it looks like this whole points feature doesn't work if you have OpenGL enabled.

https://doc.qt.io/qt-6.2/qabstractseries.html#useOpenGL-prop

> The OpenGL acceleration of series drawing is meant for use cases that need fast drawing of large numbers of points. It is optimized for efficiency, and therefore the series using it lack support for many features available to non-accelerated series:
> 
>  - Pen styles, marker shapes and light markers are ignored for accelerated series. Only solid lines and plain scatter dots are supported. The scatter dots may be circular or rectangular, depending on the underlying graphics hardware and drivers.

Switching dynamically between OpenGL enabled/disabled seems to work decent, as long as you multiply the pen width by the device pixel ratio when OpenGL is enabled.

@deanlee any thoughts?

### CODE REVIEW

**Comment by deanlee** [comment]
lgtm

**Comment by pd0wm** [comment]
I also noticed that dragging over a signal to zoom doesn't work while in OpenGL mode. I assume that has always been broken?

**Comment by deanlee** [comment]
It looks like we only need to update them when the x-axis changes. how about  putting them in 

`if (min != axis_x->min() || max != axis_x->max())`

**Comment by deanlee** [comment]
> I also noticed that dragging over a signal to zoom doesn't work while in OpenGL mode. I assume that has always been broken?

that's one of the qchart's opengl limitation too

**Comment by deanlee** [comment]
@pd0wm I improved this function slightly, paint points in drawForeground instead of swithing between opengl.  https://github.com/commaai/openpilot/pull/27239

**Pull request merged**
