### PR TITLE
camerad: ensure proper cleanup of OpenCL context on exit

### PR DESCRIPTION
**Pull request by deanlee**
Added `camerad_run` to ensure the OpenCL context is released after all dependent objects are destructed.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Don't see any reason to add another intermediate function here? Just add `clReleaseContext(ctx);` to camerad_thread?

**Comment by deanlee** [comment]
The `CameraBuf` and `VisionIpcServer` classes rely on `VisionBuf::free` in their destructors to clean up resources, which requires access to OpenCL functions. If clReleaseContext(ctx) is called at the end of `camerad_thread()`, the OpenCL context would be released before CameraBuf and VisionIpcServer are destructed, preventing proper cleanup in the destructors and potentially causing issues.

https://github.com/commaai/openpilot/blob/62d044c794f8e000ab1410333e6ffe99a58bbabd/system/camerad/cameras/camera_common.cc#L98-L103

https://github.com/commaai/msgq/blob/cdcf84f44a4edd40f7aa4d06eb95550ac64b3b37/msgq/visionipc/visionipc_server.cc#L202

**Comment by adeebshihadeh** [comment]
This isn't obvious reading the code. We should make this more explicit.

**Comment by deanlee** [comment]
how about Use std::unique_ptr for cl_context Management?

**Pull request closed without merging**
