### PR TITLE
cabana: set the COMMA_CACHE environment variable

### PR DESCRIPTION
**Pull request by deanlee**
related discussions : https://github.com/commaai/openpilot/pull/29818#issuecomment-1712196683

[update]
add function `setDownloadCachePath` to replay

### CODE REVIEW

**Comment by jnewb1** [comment]
Does replay use OpenpilotPrefix? I'm not seeing where it does

**Comment by deanlee** [comment]
cabana will use OpenpilotPrefix before replay started. 
it should be better to add a function to replay to change the default download cache path. let cabana call it to set the path.

**Comment by jnewb1** [comment]
can we instead just set the ```COMMA_CACHE``` environment variable within cabana to /tmp/comma_download_cache?

**Comment by deanlee** [comment]
done

**Comment by jnewb1** [comment]
Thank you!

**Pull request merged**
