### PR TITLE
New car docs

### PR DESCRIPTION
**Pull request by adeebshihadeh**
- [ ] Add dashcam exception

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
> It might be interesting to utilize the "silver" designation as a "grey zone" where cars that would be bronze in stock form, could be promoted via modifications (eg. SDSU, Pedal, ZSS, EPS f/w hack, etc.)... or perhaps have a separate page entirely like `docs/CARS_modded.md` that incorporates a more flexible interpretation.

The plan right now is to categorize each car based on the "stock" install and perhaps add a column indicating that it can achieve a gold-level experience with modifications. I kind of like your second README idea though.

**Comment by sshane** [comment]
- [ ] Add dashcam exception

**Review by vibhusapra — COMMENTED** [review]
The No ALC below column seems to be have been copied wrong. For example, looking at the first two cars, the ILX should have no ALC below 25mph and the RDX below 12mph.

**Comment by sshane** [comment]
@vibhusapra That's because these values aren't in the CarInterface. Feel free to submit PRs for missing metadata like `CP.minSteerSpeed` and `CP.minEnableSpeed`

**Comment by geohot** [comment]
I propose doing this sorting manually. I posted a "score sheet" on discord.

All cars start with 3 points. You lose one for:
* low torque (honda accord, nidec civic)
* no radar, likely inaccessible without reflash (vw, honda bosch)
* non mainline software support (chrysler)

3 = gold, 2 = silver, 0-1 = bronze

Toyota Corolla = Gold
Honda Civic (nidec) = Silver
Honda Accord = Bronze

**Pull request closed without merging**
