### PR TITLE
Radar tracks for Santa Fe

### PR DESCRIPTION
**Pull request by CruiseBrantley**
**Description** It looks like 2020 Santa Fe works with the radar tracks change.

**Verification** Took a route and scanned for radar points with cabana with the mando dbc.

**Route**
c66fe4bb6baaa968|2021-09-19--12-09-33

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
That route doesn't have any other cars on the road. Can you post one with other cars and ensure it's fully uploaded?

**Comment by CruiseBrantley** [comment]
Maybe this one will help more: c66fe4bb6baaa968|2021-09-19--12-09-33

**Comment by CruiseBrantley** [comment]
> That route doesn't have any other cars on the road. Can you post one with other cars and ensure it's fully uploaded?

Maybe this one will help more: c66fe4bb6baaa968|2021-09-19--12-09-33

**Comment by pd0wm** [comment]
The tracks were there, but the dbc list wasn't updated so they were not parsed.

**Pull request merged**
