### PR TITLE
Expanded the previously added Chinese RAV4

### PR DESCRIPTION
**Pull request by ErichMoraga**
This came after testing a different trim level.  This fingerprint is confirmed working on both.

### CODE REVIEW

**Comment by jfrux** [comment]
It did?

**Comment by ErichMoraga** [comment]
Yes.

**Comment by jfrux** [comment]
Okay just wanted to make sure.

**Comment by rbiasini** [comment]
Thanks @ErichMoraga . 
Was the new fingerprint strictly including the other? If not, they should be kept as 2 different fingerprints in the array.

**Comment by ErichMoraga** [comment]
This one includes all the other's msgs.,  adds an extra 11, and works for both trims.  No need to keep the previous fingerprint, which is why I replaced it.

**Pull request merged**
