### PR TITLE
work on acados lateral MPC

### PR DESCRIPTION
**Pull request by FreyJo**
**Description** Change lateral MPC formulation to be more efficient:
- Use parameters instead of states for v_ego, rotation_radius.
- Use partial condensing horizon 1 https://github.com/commaai/openpilot/commit/6729aa4e7e14f5c615b1a25d5263e4245d01e4b3

**Verification**
Comparing the output of `./profiler.py plannerd` before and after these changes:
On my workstation the time spent in acados lateral MPC goes down from 8% to 7%, which is a 12 % speedup.

However, looking at the Jenkins timings there was no significant difference.
Timings on comma 2, latest Jenkins build `master`:
```
lateralPlan                             : [ 50.00937767 111.367656    23.552135  ]
                                          2.2273531199999996 0.13557882688246065
```

Run of this PR:
```
lateralPlan                             : [49.98976999 64.204296   39.126515  ]
                                          1.2840859199999999 0.0655169759648268
```

The `diff.txt` from `test_process` mostly contains very small differences (in the range of the precision of the solver).
Only surprise is that the exact zeros in the first call are not there anymore.
I thought f7df6ed460cde52e7d34bd1184e1f25c8898d3e8 would fix this, but didn't.

### CODE REVIEW

**Comment by pd0wm** [comment]
We should not forget to ensure our fork (https://github.com/commaai/acados/tree/cython2) is updated when this PR is merged so they don't go out of sync.

**Comment by FreyJo** [comment]
Rebased on `master` after https://github.com/commaai/openpilot/pull/23566 was merged to get better timings on Comma devices.
Comparing min exec. time with(out) the PR. On both comma 2 and 3 is > 10 % speedup similar to my machine.

Details:
Timings on `master`:

Comma 2
```
'lateralPlan' execution time: 0.000724896090105176
'lateralPlan' avg execution time: 0.000856667530121437
'longitudinalPlan' execution time: 0.0011812500888481736
'longitudinalPlan' avg execution time: 0.0014819912988847743
```
Comma 3
```
'lateralPlan' execution time: 0.0005737399915233254
'lateralPlan' avg execution time: 0.0010374531550278532
'longitudinalPlan' execution time: 0.0007265500025823712
'longitudinalPlan' avg execution time: 0.0008706675279843586
```

On latest run:

Comma 2
```
'lateralPlan' execution time: 0.0006229679565876722
'lateralPlan' avg execution time: 0.0007458280741043371
'longitudinalPlan' execution time: 0.0011680210009217262
'longitudinalPlan' avg execution time: 0.0014990311948101696
```

Comma 3
```
'lateralPlan' execution time: 0.0004948360146954656
'lateralPlan' avg execution time: 0.0008972105476771829
'longitudinalPlan' execution time: 0.0007240519626066089
'longitudinalPlan' avg execution time: 0.0008799307918372122
```

**Comment by FreyJo** [comment]
> We should not forget to ensure our fork (https://github.com/commaai/acados/tree/cython2) is updated when this PR is merged so it doesn't go out of sync with the copy in pyextra.

Done here https://github.com/commaai/acados/commit/b1d46bd5bc134ada90a20a863aee3bed2bcd525b

**Comment by pd0wm** [comment]
@HaraldSchafer Are there any batch tests you want to run before merging?

**Comment by adeebshihadeh** [comment]
If the timings are more consistent now, let's tighten the thresholds in `selfdrive/test/test_onroad.py`.

**Comment by HaraldSchafer** [comment]
Not yet. The biggest inconsistency is from long, which is unchanged

**Comment by adeebshihadeh** [comment]
I see, perhaps it would be nice to also have specific checks on the solver execution times for both lat and long.

**Comment by pd0wm** [comment]
I added those to CI today, but we still need to choose correct thresholds.

**Pull request merged**
