### PR TITLE
Hyundai Ioniq EV port

### PR DESCRIPTION
**Pull request by baldwalker**
revised pull request to separate different model to IONIQ_EV_LTD

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can you add a route to test_car_models and add this to the README?

**Comment by baldwalker** [comment]
sorry don't know how to do what you are asking for?

**Comment by baldwalker** [comment]
https://my.comma.ai/cabana/?route=2c5cf2dd6102e5da%7C2020-06-26--16-00-08&exp=1624721695&sig=wgJ8I2EFBF8ySmX1F6dDeMZ2aX618f%2B2QI12C9a6ATk%3D&max=8&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F2c5cf2dd6102e5da%2Fb482166c0329095314176808fb120341_2020-06-26--16-00-08

**Comment by adeebshihadeh** [comment]
fixed up in #1786

**Pull request closed without merging**
