### PR TITLE
Update carstate.py

### PR DESCRIPTION
**Pull request by wocsor**
Added values 3 and 11 for 2018 Corolla EPS. Was getting "Steering Unavailable" before.

### CODE REVIEW

**Comment by geohot** [comment]
Ahh, interesting. We'll discuss this tomorrow.

**Comment by rbiasini** [comment]
@geohot , discussed this with @wocsor on Slack: I think we should disregard the least important bit (always 1 in corolla, 0 in other models) which seems unrelated to the EPS state. If we make this dbc change we, can still use the same code for all Toyota models.

**Comment by csouers** [comment]
@billy2kool previous gen accord is difficult and uses custom serial communication. Wait for it to be ported or try to do it yourself. Don't expect someone to jump at the port with no incentive.

**Comment by billy2kool** [comment]
Thanks for your reply I wish I could've done it myself. But I could give
someone $300 to get it going for me.... Not trying to insult anyone but if
I can't get it going just going to get a new car..  Remember I am a noob
don't even know how to SSH into the device.  Please let me know what can be
done

**Comment by geohot** [comment]
@billy2kool, post about that again in an off topic thread and I'll ban you from our github

**Comment by billy2kool** [comment]
Sorry just need some help, don't know what I am doing.   Bought this thing
and need some help to get it up and running.

**Comment by rbiasini** [comment]
fixed in 0.4.3.2 by changing the dbc file.

**Pull request closed without merging**
