### PR TITLE
Toyota: match dash set speed

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

**Comment by sshane** [comment]
```
total dongles: 243
TOYOTA COROLLA 2017, is_metric=False, n_segments=202
TOYOTA RAV4 HYBRID 2019, is_metric=False, n_segments=2638
TOYOTA HIGHLANDER HYBRID 2018, is_metric=False, n_segments=104
TOYOTA CAMRY 2018, is_metric=False, n_segments=849
TOYOTA AVALON 2019, is_metric=False, n_segments=25
TOYOTA PRIUS 2017, is_metric=False, n_segments=2516
TOYOTA HIGHLANDER 2017, is_metric=False, n_segments=778
LEXUS RX 2016, is_metric=False, n_segments=564
TOYOTA COROLLA HYBRID TSS2 2019, is_metric=False, n_segments=921
TOYOTA SIENNA 2018, is_metric=False, n_segments=425
TOYOTA COROLLA TSS2 2019, is_metric=False, n_segments=1374
TOYOTA CAMRY HYBRID 2018, is_metric=False, n_segments=135
TOYOTA HIGHLANDER 2020, is_metric=False, n_segments=632
TOYOTA CAMRY HYBRID 2021, is_metric=False, n_segments=187
TOYOTA RAV4 HYBRID 2017, is_metric=False, n_segments=396
TOYOTA ALPHARD 2020, is_metric=True, n_segments=4
TOYOTA PRIUS TSS2 2021, is_metric=False, n_segments=1149
TOYOTA RAV4 2017, is_metric=False, n_segments=265
LEXUS RX 2020, is_metric=True, n_segments=413
TOYOTA RAV4 2019, is_metric=False, n_segments=2025
TOYOTA HIGHLANDER HYBRID 2020, is_metric=False, n_segments=852
TOYOTA AVALON 2022, is_metric=False, n_segments=2
LEXUS NX 2020, is_metric=False, n_segments=169
LEXUS NX 2018, is_metric=False, n_segments=34
TOYOTA RAV4 2022, is_metric=False, n_segments=217
TOYOTA AVALON HYBRID 2019, is_metric=False, n_segments=14
LEXUS NX HYBRID 2018, is_metric=False, n_segments=933
TOYOTA RAV4 HYBRID 2022, is_metric=False, n_segments=387
```

**Comment by sshane** [comment]
Out of the same segments checked, there's no cases on the `UI_SET_SPEED` being 0 while the current `SET_SPEED` was non-zero. Also checked for closeness of the two signals, which look good.

**Review by adeebshihadeh — APPROVED** [review]
Next time ensure the tests are passing before requesting a review. There was a process replay diff that wasn't immediately obvious.

**Comment by sshane** [comment]
I didn't want to have to end up updating refs twice, as a refs conflict could have prevented a merge. I'll make it more clear when there's a process replay diff though!

**Pull request merged**
