### PR TITLE
Delete lateral tuning for HYUNDAI

### PR DESCRIPTION
**Pull request by haraschax**

### CODE REVIEW

**Comment by haram-KONA** [comment]
For the Kona Hybrid 2020, it feels incredibly good. 
Oscillation has also been significantly reduced, and it seems that driving at high speed is quite stable. 
Oscillation that occurred in the curve seems to have almost disappeared. 
To be very precise, when changing lanes at speeds above 110 km/h, it feels like there is a very, very slightly oscillation, but it doesn't seem like a big problem. 
This driving route-id is " 0665dbbc79ef999e|2022-06-12--12-05-39 " . Please check it. 
Always thank you for your hard work.

**Comment by HaraldSchafer** [comment]
@haram-KONA Thanks! You have timestamp of when there was oscillation in that route?

**Comment by haram-KONA** [comment]
> @haram-KONA Thanks! You have timestamp of when there was oscillation in that route?

The route id " 0665dbbc79ef999e|2022-06-12--12-05-39-31 " is the part where the speed is reduced little by little in the tunnel and the lane changes, it seems that i felt very little oscillation in this part.

**Comment by haram-KONA** [comment]
> @haram-KONA Thanks! You have timestamp of when there was oscillation in that route?



> @haram-KONA Thanks! You have timestamp of when there was oscillation in that route?

The route id " 0665dbbc79ef999e|2022-06-12--12-05-39-31 " is the part where the speed is reduced little by little in the tunnel and the lane changes, it seems that i felt very little oscillation in this part.

**Comment by haram-KONA** [comment]
> @haram-KONA Thanks! You have timestamp of when there was oscillation in that route?

https://user-images.githubusercontent.com/88036668/173226794-3664d5bf-92f8-4b56-ab8a-34fe02a33f5e.mp4

**Comment by NikitaNekrasov** [comment]
Hyundai Ioniq Electric 2019: Still seeing similar oscillations to the PID controller, also seeing more aggressive corrections on curves than previously experienced. `8e221cf40bc9c78a|2022-06-15--12-45-58`

**Comment by sshane** [comment]
@HaraldSchafer want to re-open this when we're ready to make the full transition?

**Comment by HaraldSchafer** [comment]
Vivek can make a new PR with live torque once it's ready

**Pull request closed without merging**
