### PR TITLE
Micro bounty: visiond PC version

### PR DESCRIPTION
**Pull request by nanamiwang**
A visiond version for linux, tested on ubuntu 16.04.

### Features
**camera_eon_stream.cc:**
- Connect to Eon streaming server (loggerd --stream), decode the hevc  YUV420 frames using libavcodec API.
- Emulate a rear camera,  dispatch YUV420 frames to the visiond_pc.cc processing thread.

**visiond_pc.cc**
- A clone of visiond.cc
- Launch the emulated  camera, run driving model and posnet model, so that all the rear camera vision pipeline can work as normal.
- Removed dependencies on  android ion, visionbuf and visionimg.
- Removed streaming server support.
- Removed front camera and drive monitoring features.

**Other changes**
- Add some missing header inclusions in model.cc, snpemodel.cc and monitor.cc.
- Use CPU mode for x86_64 in snpemodel.cc.
- Fixed a memory leak in model.cc.
Have tested the code on Eon, so that all the changes will not affect the android version of visiond.

### Build Prerequisites
- Install SNPE and set SNPE_ROOT env.
- Build and install zmq & czmq.
- Install libavcodec-dev.

### How to use
**On Eon**
Launch loggerd and visiond
```bash
loggerd --stream
visiond
```

**On ubuntu**
Launch visiond, set the target Eon IP address using  env EON_IP:
```bash
EON_IP=192.168.1.105 ./visiond
```
Launch calibration daemon to handle posnet inference result and do live calibration:
```bash
python calibrationd.py
```
Launch openpilot-tools replay UI to see the decode frames and model inference result:
```bash
python openpilot-tools/replay/.py
```
### How to verify the model inference result
- Play a recorded drive video on PC, like this:
https://github.com/commaai/comma2k19/blob/master/Example_1/b0c9d2329ad1606b%7C2018-08-02--08-34-47/40/video.hevc
- Point the Eon at the screen, make sure the lanes is within the blue box on openpilot-tools replay UI.
- Check the model output window, will see that the lanes is detected correctly by driving model.

### CODE REVIEW

**Comment by icmma** [comment]
@nanamiwang you have done it again bro hats off.

**Comment by arne182** [comment]
Am busy loading up 16.04 to test this. Great job.

**Comment by rbiasini** [comment]
@nanamiwang , this looks great!
Quick questions: 
- why not using https://github.com/commaai/openpilot-tools/blob/master/streamer/streamerd.py instead of `camera_eon_stream`
- it would be nice if `visiond_pc` could live in `openpilot-tools`repo.

We still have to test it. Tnx!

**Comment by nanamiwang** [comment]
@rbiasini 

- I was thinking a bit of performance gain if doing stream reception and hevc decoding in visiond directly instead of going through PyAv and zmq queue. I can update the PR, remove camera_eon_stream.cc and remove frame publishing stuff in visiond_pc.cc.

- Do you mean moving visiond_pc.cc to openpilot-tools repo? visiond_pc.cc shares model inference and OpenCL code with visiond.cc, seems not be easy to be moved out.
BTW, A suggestion on code structure, currently the posenet code is duplicated in the two visiond cc files, should be refactored out to a dedicate file.

**Comment by geohot** [comment]
Can you resolve this merge conflict? Then it looks good to merge.

**Comment by geohot** [comment]
Hmm, actually, it won't build on my PC.

./camera_fake.h:8:10: fatal error: 'buffering.h' file not found
#include "buffering.h"

Shouldn't it be #include "common/buffering.h"?

**Comment by nanamiwang** [comment]
No problem. I found this issue when I working this PR, so I add "CXXFLAGS += -I../common" to build_from_src.mk

**Comment by geohot** [comment]
So I've merged it in, and with a few changes it's up and running!

Though the model seems really slow...

**Comment by nanamiwang** [comment]
I tried running the drive model using tensorflow c++ API, it is pretty fast,  < 1ms inferrence time on an old GTX1050 GPU. Can share the code if we need it.

**Comment by geohot** [comment]
Yea, it's super fast in tensorflow,

**Comment by nanamiwang** [comment]
Great, I need a EON for my Corolla 2020.

**Comment by geohot** [comment]
Nice car :)

E-mail support@comma.ai with the codeword "visiondfish" and your address, and they shall send it

**Comment by geohot** [comment]
Hmm, actually how did you convert DLC to tensorflow? Everything is for going the other way...

**Comment by nanamiwang** [comment]
Run snpe-dlc-view to view the dlc file, clone the model in keras, transfer the weights from dlc file, then export the model to tensorflow graph.
---Original---

**Comment by enienws** [comment]
> I tried running the drive model using tensorflow c++ API, it is pretty fast, < 1ms inferrence time on an old GTX1050 GPU. Can share the code if we need it.
@nanamiwang Could you please share the code and the model?

**Comment by kaishijeng** [comment]
@nanamiwang 
 Could you please share the code and the model? I am interested too.

Thanks

**Pull request closed without merging**
