### PR TITLE
Honda Civic & CR-V Bosch: allow fingerprinting without comma power

### PR DESCRIPTION
**Pull request by sshane**
https://github.com/commaai/openpilot/issues/31244 hasn't plugged in their comma power. I checked a few VINs with different first character prefixes (different regions) and they all return `fwdRadar`, `fwdCamera`, `eps`, `srs` on bus 1, non-OBD multiplexed

Civic Bosch checked:
- f1109d8294ea80ac|2024-01-30--10-44-56
- f5392228324cda8d|2024-01-13--17-01-57
- dd8aedf56faa8661|2024-01-31--18-02-17
- f99ab12043ad3219|2024-01-29--14-04-34
- fa1dc48cb5a31191|2024-01-31--14-37-42

CR-V Bosch checked:
- ffa76986ec8e871e|2024-01-31--07-53-40
- fd114cff219d3bb8|2024-01-05--06-24-31

### CODE REVIEW

**Comment by sshane** [comment]
Checking mock routes last 90 days: `Checked routes: 7287, dongles: 311 platforms: {'mock': 7287}`

Found 16 dongles that had mock routes that now fingerprint to one of these platforms! They likely didn't have the comma power plugged in at the time.

**Comment by sshane** [comment]
The lost ECUs could have a substantial amount of info relevant for fuzzy FP in the future, leaving them in database for now in case it helps.

Instead we will add the cars/ECUs to the `non_essential_ecus` dict in the config which won't change fingerprinting behavior for comma power cars. Despite the fact I found only [one case](https://github.com/commaai/openpilot/pull/31388) where a dongle failed to fingerprint after this change due to missing versions (not ECUs), it could still impact fingerprinting for future users, so going to take this approach first. We can always remove the FWs in the future when the majority of users aren't using a power and there's no point in keeping them.

**Comment by adeebshihadeh** [comment]
Why only for two cars? Do we expect this to scale to other models?

**Comment by sshane** [comment]
Yes, I just did the verification for the user's car in that issue to look out for issues on a smaller sample. Next is to verify each model (not sure if we get different ECUs per architecture, platform, or even by MY yet).

**Pull request merged**
