### PR TITLE
Added the 2024 Ram 3500 FW

### PR DESCRIPTION
**Pull request by vincentw56**
**Car**
2024 Ram 3500

**Route**
632ceb5cc1d7e3f3/2024-03-13--16-17-07

**Dongle ID**
632ceb5cc1d7e3f3

### CODE REVIEW

**Comment by incognitojam** [comment]
You should remove the FW for `Ecu.transmission`, it isn't necessary
https://github.com/commaai/openpilot/actions/runs/8283733359/job/22667622454?pr=31866#step:5:156

**Comment by vincentw56** [comment]
> You should remove the FW for `Ecu.transmission`, it isn't necessary https://github.com/commaai/openpilot/actions/runs/8283733359/job/22667622454?pr=31866#step:5:156

I removed it. I saw it listed in FW now and didn't know since almost every other FCA FW has it.

**Comment by sshane** [comment]
Thanks, but I believe this has the same issue that https://github.com/commaai/openpilot/pull/30264 has. Once we support the HD trucks (@nuwandavek is working on this when he gets time), we can merge that and then we can re-open this.

| Dongle, platform, VIN                                                                                                     | Name from VIN 🆚 CarInfo                                                        | Segments                                  | Bad seg tags                                                                                     | Good seg tags       |
|:--------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------|:------------------------------------------|:-------------------------------------------------------------------------------------------------|:--------------------|
| [632ceb5cc1d7e3f3](https://useradmin.comma.ai/?onebox=632ceb5cc1d7e3f3)<br><sub>RAM HD 5TH GEN<br>3C63RRJL6........</sub> | RAM 3500 2024 🆚<br>Ram 3500 2019-22<br><sub>🎉 <b>New model year!</b> 🎉</sub> | 42 routes,<br>427 segments<br>(7.1 hours) | - [CAN invalid: 370](https://useradmin.comma.ai/?onebox=632ceb5cc1d7e3f3%7C2024-03-12--14-19-30) | - all lat active: 0 |

**Comment by vincentw56** [comment]
> Thanks, but I believe this has the same issue that #30264 has. Once we support the HD trucks (@nuwandavek is working on this when he gets time), we can merge that and then we can re-open this.
> 
> Dongle, platform, VIN	Name from VIN 🆚 CarInfo	Segments	Bad seg tags	Good seg tags
> [632ceb5cc1d7e3f3](https://useradmin.comma.ai/?onebox=632ceb5cc1d7e3f3)
> RAM HD 5TH GEN
> 3C63RRJL6........	RAM 3500 2024 🆚
> Ram 3500 2019-22
> 🎉 New model year! 🎉	42 routes,
> 427 segments
> (7.1 hours)	- [CAN invalid: 370](https://useradmin.comma.ai/?onebox=632ceb5cc1d7e3f3%7C2024-03-12--14-19-30)	- all lat active: 0

Although I agree about you not supporting HD trucks yet specially the 2024s, it would still be good to get validated FWs instead of waiting. Our fork and SunnyPilot both support the HD trucks and having the FWs upstreamed just makes it better for everyone regardless of you supporting them or not. You haven't supported them in the past, yet you still merged in FW that Realfast and I have provided before. I don't see this being any different. Official OP will still only run in dashcam mode on the HDs. But the forks that support them won't have to add them in downstream.

**Comment by sshane** [comment]
The problem is that these 2024 models actually require a different message and need an update of panda and opendbc, it's not just a bump of the model year.

**Pull request closed without merging**
