### PR TITLE
2019 Camry hybrid verified working with redsinr

### PR DESCRIPTION
**Pull request by icmma**

### CODE REVIEW

**Comment by icmma** [comment]
pending full port.

was able to get calibrate but not engage

**Comment by bugsy924** [comment]
Why no engage? Port works

**Comment by icmma** [comment]
Seems like user error

**Comment by legonigel** [comment]
This PR is failing the fingerprint test. There are two inconsistent fingerprints. Check out the results from Travis to see what fingerprints cause the problem. Please resolve this issue.

**Comment by vanillagorillaa** [comment]
@icmma any update on this?

**Comment by rbiasini** [comment]
exact same fingerprint as the one added in: https://github.com/commaai/openpilot/pull/622
Nice job at taking it correctly.

**Comment by icmma** [comment]
well i just added fingerprints lol it's cool

**Pull request closed without merging**
