### PR TITLE
HKG: Car Port for Genesis G70 2024

### PR DESCRIPTION
**Pull request by sunnyhaibin**
**Checklist**

- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: `a6310918f9699ef5/2024-02-28--14-55-10`
- [x] route with stock system: `a6310918f9699ef5/2024-02-27--20-17-09`
- [x] car harness used (if comma doesn't sell it, put N/A): Harness F

Thanks to the community 2024 Genesis G70 owner mayday4968 (Discord).

### CODE REVIEW

**Comment by sshane** [comment]
Have you checked if any of the issues in https://github.com/commaai/openpilot/discussions/30810 apply here?

**Comment by sunnyhaibin** [comment]
> Have you checked if any of the issues in #30810 apply here?

We have not yet, still need a test route from the user first.

**Comment by jnewb1** [comment]
I think ideally this car port looks like:

```python

CAR.GENESIS_G70_1ST_GEN_FL=HyundaiPlatformConfig(
  "GENESIS G70 1ST GEN FACELIFT",
  HyundaiCarInfo("Genesis G70 2024", "All", car_parts=CarParts.common([CarHarness.hyundai_l])),
  specs=CarSpecs(mass=1769,wheelbase=2.83,steerRatio=12.9), # guesstimate from G70 1st Gen platform
  dbc_dict=dbc_dict('hyundai_kia_generic', None),
  flags=HyundaiFlags.CAMERA_SCC | HyundaiFlags.CRC8_CHECKSUM
)
```

**Comment by MarcoTheDingo** [comment]
Generally good, but still it oversteers and overcorrects. Likely will need to tune further.

Also some fault routes:
- Random faults (keep hands on wheel, etc): a6310918f9699ef5/2024-03-01--20-10-47
- Drivers grip not detected, speed reduced: a6310918f9699ef5/2024-03-04--16-22-33 & a6310918f9699ef5/2024-03-05--05-40-31

**Comment by MaydayDragal** [comment]
Hello! Is there anything I can add or contribute to get the progress of this port moving again?

**Comment by sshane** [comment]
@sunnyhaibin any updates?

**Comment by MarcoTheDingo** [comment]
> @sunnyhaibin what's the state of this?

This is pending the fixes for the same issues adeeb is working on for the ioniq 5 (https://github.com/commaai/openpilot/issues/32286#issuecomment-2116535524) as well as some more tuning.

I actually have been working on this in my own branch (https://github.com/MarcoTheDingo/openpilot/tree/g70-2024-test).

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
