### PR TITLE
fingerprinting: bump CAN fingerprinting time and drain socket

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

**Comment by sshane** [comment]
Times to fingerprint the radar start message on a Hyundai Sonata:

```python
Seen first radar message at 290938.149397 ms
Started CAN fingerprinting at 290911.32897 ms
Difference of 26.82 ms (3 frames)

Seen first radar message at 307220.847198 ms
Started CAN fingerprinting at 307169.741698 ms
Difference of 51.11 ms (5 frames)

Seen first radar message at 281193.165079 ms
Started CAN fingerprinting at 281176.526134 ms
Difference of 16.64 ms (2 frames)

Seen first radar message at 264582.602829 ms
Started CAN fingerprinting at 264521.916087 ms
Difference of 60.69 ms (6 frames)

Seen first radar message at 59781.790494999994 ms
Started CAN fingerprinting at 59701.293152 ms
Difference of 80.5 ms (8 frames)

Seen first radar message at 349817.794001 ms
Started CAN fingerprinting at 349770.289496 ms
Difference of 47.5 ms (5 frames)

Seen first radar message at 225594.420219 ms
Started CAN fingerprinting at 225534.10707099998 ms
Difference of 60.31 ms (6 frames)

Seen first radar message at 78585.94970699999 ms
Started CAN fingerprinting at 78505.828249 ms
Difference of 80.12 ms (8 frames)

Seen first radar message at 164581.769901 ms
Started CAN fingerprinting at 164540.99499399998 ms
Difference of 40.77 ms (4 frames)

Seen first radar message at 247125.238177 ms
Started CAN fingerprinting at 247067.97928899998 ms
Difference of 57.26 ms (6 frames)
```

**Comment by ErichMoraga** [comment]
FWIW - The frame_fingerprint value used to be 1s, until this PR...
https://github.com/commaai/openpilot/pull/22803

Reducing it to anything much lower apparently messes w/ some recognizing some people's C-SDSUs.

**Comment by sshane** [comment]
Is it possible to have the SDSU send its fingerprint message much sooner?

**Comment by ErichMoraga** [comment]
> Is it possible to have the SDSU send its fingerprint message much sooner?

The SDSUs I make don't have the problem, though I use official Panda hardware, and the 0x2ff is pretty early in code execution...
https://github.com/wocsor/panda/blob/smart_dsu/board/main.c#L98

It's the C-SDSU (Chinese clones) that have the problem, from what I've heard.  Anyway, just making sure you were aware of `frame_fingerprint`'s sordid history...

**Pull request merged**
