### PR TITLE
VW MQB: Audi Q3 Mk2

### PR DESCRIPTION
**Pull request by jyoung8607**
**Audi Q3 Mk2**

Covers all variants of the second generation Q3 subcompact SUV (2018-current), including the RS Q3 and Sportback variants.
- [x] added to README
- [ ] test route added to [test_routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/test/test_models.py)
- [ ] route with openpilot: 7aae592fc08e895f|2021-06-15--18-47-33

Thanks to community Q3 owner alig (2020).

### CODE REVIEW

**Comment by jyoung8607** [comment]
Test drive may take a little while to procure. The user I'm working with is a long-time user of the community port, but recently his C2 mainboard died (non-recoverably) and he performed his own out-of-warranty mainboard swap, and he therefore cannot re-register for comma cloud services.

**Comment by jyoung8607** [comment]
Test drive from alig is up, thanks to some creative lateral thinking from @adeebshihadeh. Ready for review.

**Comment by adeebshihadeh** [comment]
Tests are failing
```
FAIL: test_car_interface (selfdrive.test.test_models.TestCarModel_12_AUDI_Q3_2ND_GEN)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/openpilot/selfdrive/test/test_models.py", line 113, in test_car_interface
    self.assertLess(can_invalid_cnt, 50)
AssertionError: 5797 not less than 50
```

**Comment by jyoung8607** [comment]
Note for future use: tests failed for this vehicle because he's using one of my old gateway harnesses that doesn't have bus 1 wired up to anything, so automatic network location detection won't work for him. An older version of my community port supports forcing the network location manually. When someone else shows up with a working Q3, this firmware should be added as well.

**Pull request closed without merging**
