### PR TITLE
Update Ionic Hybrid fingerprint

### PR DESCRIPTION
**Pull request by s70160**
CAR.IONIQ_EV_LTD: [{
68: 8, 127: 8, 304: 8, 320: 8, 339: 8, 352: 8, 356: 4, 544: 8, 576:8, 593: 8, 688: 5, 832: 8, 881: 8, 882: 8, 897: 8, 902: 8, 903: 8, 916: 8, 1040: 8, 1056: 8, 1057: 8, 1078: 4, 1136: 6, 1173: 8, 1225: 8, 1265: 4, 1280: 1, 1287: 4, 1290: 8, 1291: 8, 1292: 8, 1294: 8, 1322: 8, 1342: 6, 1345: 8, 1348: 8, 1355: 8, 1363: 8, 1369: 8, 1407: 8, 1427: 6, 1429: 8, 1430: 8, 1448: 8, 1456: 4, 1470: 8, 1476: 8, 1535: 8
}],

### CODE REVIEW

**Comment by s70160** [comment]
Can add IONIQ HYBRID 
https://my.comma.ai/cabana/?route=5399c75340359d11%7C2020-07-03--09-53-43&exp=1625506238&sig=lSNHGBwGoOmx5CpbHOV40bqSwqDlHI1r9zx3ZICD7HM%3D&max=16&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F5399c75340359d11%2F2c87a60ab8a806222322713fbf7e665f_2020-07-03--09-53-43

**Comment by pd0wm** [comment]
Can you merge them into one fingerprint?

**Comment by adeebshihadeh** [comment]
They can't be merged since 544 has a different length. It adds the byte with the checksum and counter.

**Comment by adeebshihadeh** [comment]
Reverted this since it's conflicting the other fingerprint you added for the other Ioniq model in #1863.

**Pull request merged**
