### PR TITLE
2021 Lexus RX350 FW versions

### PR DESCRIPTION
**Pull request by jmoratti**
Add values for 2021 Lexus ES350

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What's your dongle ID?

**Comment by pd0wm** [comment]
You added the value to the Lexus RX. Are you sure you didn't want to add it to the LEXUS_ES_TSS2 section?

**Comment by jmoratti** [comment]
> You added the value to the Lexus RX. Are you sure you didn't want to add it to the LEXUS_ES_TSS2 section?

it was actually for the rx i dont know why i said es

**Comment by adeebshihadeh** [comment]
I assume this is working on your RX? We'll still need your Dongle ID too.

**Comment by pd0wm** [comment]
Tested on `5e6b6cb332f2cf8e|2021-05-02--21-45-26`

**Pull request merged**
