### PR TITLE
ui/alert: add blinking back

### PR DESCRIPTION
**Pull request by deanlee**
fill rect in NvgWindow is much more faster than in OnroadAlerts(0.05ms, full screen). the CPU usage almost will not increase while blinking

https://user-images.githubusercontent.com/27770/141195181-1ada9b05-c47d-49e4-8d57-cda5aec9602e.mp4

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
The way alerts is now split between NvgWindow and OnroadAlerts is pretty dirty. Why is it faster to draw the background in NvgWindow? Can we just optimize OnroadAlerts?

**Comment by deanlee** [comment]
do blinking in onroadAlerts is very slow which is basically impossible.
It is difficult to optimize OnroadAlerts, there is no way to stack two openglwidgets together. OnroadAlerts is suitable for drawing some content that does not change much

**Comment by adeebshihadeh** [comment]
I'd rather not do this, but maybe we should merge OnroadAlerts into NvgWindow. Though I'm not sure blinking is worth it.

**Comment by deanlee** [comment]
OnroadAlerts is still useful, we can draw other information on it, for example, maxspeed, speed... :   https://github.com/commaai/openpilot/pull/22173 . I renamed it to OnroadHud in that pr

**Comment by adeebshihadeh** [comment]
I was thinking that the HUD overlays would be their own widget. Does stacking have a big perf hit for normal QWidgets?

**Comment by deanlee** [comment]
stacking multiple small qwidgets is expensive. QGraphicsScene is a better choice

**Comment by deanlee** [comment]
I'll try to do blinking in OnroadAlerts after https://github.com/commaai/openpilot/pull/22843

**Comment by adeebshihadeh** [comment]
We've decided to just cut alert blinking.

**Pull request closed without merging**
