### PR TITLE
bigmodel

### PR DESCRIPTION
**Pull request by pd0wm**

### CODE REVIEW

**Comment by zorrobyte** [comment]
Went for a spin on this, seems to work well!
```4aa5d874f367adbc|2022-02-02--16-34-59```

**Comment by HaraldSchafer** [comment]
> 4aa5d874f367adbc|2022-02-16--14-26-4

What do you mean by pretty wonky? Do you have a specific example?

**Comment by HaraldSchafer** [comment]
> Longitudinal control is pretty wonky by this commit 4aa5d874f367adbc|2022-02-16--14-26-49--0
> 
> Not sure if it's lag related, or some other weirdness

What do you mean by pretty wonky? Do you have a specific example?

**Comment by zorrobyte** [comment]
I’ll need to re-test, but OP didn’t seem to want to accelerate when following a lead on the interstate. Could be unrelated, I’ll attempt to duplicate

**Comment by zorrobyte** [comment]
> > Longitudinal control is pretty wonky by this commit 4aa5d874f367adbc|2022-02-16--14-26-49--0
> > Not sure if it's lag related, or some other weirdness
> 
> What do you mean by pretty wonky? Do you have a specific example?

@HaraldSchafer replicated. Check `4aa5d874f367adbc|2022-02-16--18-50-12--5`

Had to mash brakes due to OP not slowing for lead. Feels like long lag.

Let me know and I can stop providing feedback on WIP branches as this isn't on master, yet

**Comment by HaraldSchafer** [comment]
Model looks mostly fine in first case, controls just super lagg
lag
y

**Comment by zorrobyte** [comment]
Still getting the phantom braking issue @HaraldSchafer
See https://github.com/commaai/openpilot/issues/23804

**Pull request merged**
