### PR TITLE
sensord:  improve sensor frequency stability and timestamp accuracy

### PR DESCRIPTION
**Pull request by deanlee**
This PR addresses sensor frequency instability and improves timestamp accuracy by introducing the `get_latest_event_time` function.

**Key Changes:**
1. **Improved Frequency Stability:** `get_latest_event_time` continuously reads from the GPIO file descriptor until all available events are retrieved. By clearing the event queue, it prevents poll() from returning immediately in the next loop, avoiding duplicate sensor data reads and ensuring a stable message frequency.
 2. **Enhanced Timestamp Accuracy:** Provides precise timestamps for sensor events by reading all pending events and calculating the latest timestamp.
 3. **Improved Error Handling:**  Manages EINTR for `read` operations to ensure robustness and stability, preventing interruptions from disrupting the event reading process.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
trigger-jenkins

**Comment by adeebshihadeh** [comment]
@Quantizr can you run this in the testing closet for a bit and post the results?

**Comment by Quantizr** [comment]
image
disengagement was for posenetInvalid, can be ignored

**Comment by adeebshihadeh** [comment]
There's no accelerometer or gyro in that screenshot?

**Comment by Quantizr** [comment]
Reran on the testing closet looking at `gyroscope.timestamp` and `accelerometer.timestamp`, there is no significant difference in either max or relative standard deviation of timings between this PR and master (shown in the attached picture). Nor is there a significant difference in p5, p25, median, p75, p95, or avg (coming to testing closet soon).

The service timings for accelerometer and gyroscope are calculated by taking the diff of the `timestamp` attribute of the  messages corresponding to the sensors in the order in which they appear in the logs. Interestingly, in both this PR and in master, a **few of those diffs are negative**, indicating that some of the messages are out of order, which would then be affecting both max and RSD.

Logs are already sorted by `logMonoTime` prior to calculations. Not sure if the correct behavior of the testing closet would be to sort by `timestamp` before calculating diffs or to throw an event that timestamps are out of order.

image

**Comment by adeebshihadeh** [comment]
@deanlee the timings are the same. Any other reason to merge this?

**Comment by deanlee** [comment]
Although the test results show no difference, this is still a more robust way to read events.

**Comment by deanlee** [comment]
Since I don't have the device with me right now, I need to clarify something: Is the ts in gpioevent_data measured in nanoseconds since boot or nanoseconds since the epoch? We are currently treating it as nanoseconds since the epoch, but it seems that most GPIO returns use nanoseconds since boot.

Furthermore, instead of using poll, we might be able to use RateKeep to periodically read eventdata, clear the queue, and then send the sensor data. If this approach works, it could help stabilize the frequency.

**Comment by maxime-desroches** [comment]
This PR was closed because of a git history rewrite.
Please read https://github.com/commaai/openpilot/issues/33399 for what to do with your fork and your PRs.

**Pull request closed without merging**
