### PR TITLE
Update Toyota C-HR Hybrid fingerprint

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Hmmm, @justaviet was looking into this too.  Be sure to post a Cabana share link of a drive in stock ADAS mode.

**Comment by vanillagorillaa** [comment]
This pull request should be made against devel, not release2

**Comment by ErichMoraga** [comment]
Damn shame since other C-HR hybrid folk are left hanging, waiting in "VINPrinting" w/ ETA *whenever*...

**Comment by ErichMoraga** [comment]
Damn shame since other C-HR hybrid folk are left hanging, waiting on "VINPrinting" w/ ETA *whenever*...

**Pull request closed without merging**
