### PR TITLE
Subaru: use torque controller

### PR DESCRIPTION
**Pull request by adeebshihadeh**
- [ ] CAR.ASCENT
- [ ] CAR.IMPREZA
- [ ] CAR.IMPREZA_2020
- [ ] CAR.FORESTER

### CODE REVIEW

**Comment by sshane** [comment]
@michaelhonan Hey, do you have an Impreza to test?

**Comment by michaelhonan** [comment]
> @michaelhonan Hey, do you have an Impreza to test this?

Yep! Will do 👍

**Comment by michaelhonan** [comment]
> @michaelhonan Hey, do you have an Impreza to test this?

Works well. Much more stable than current upstreamed pid.

dc30ef2ad294a732|2022-08-02--12-20-29

Commit used:
https://github.com/michaelhonan/openpilot/commits/subaru-torque

**Comment by CruelSenpai** [comment]
Tested on a 2018 Crosstrek Limited: 6f35adacf2529520|2022-08-03--04-07-46--0

As Michael mentioned above, works well and definitely an improvement over the previous controller. However, I am still having issues turning on many freeway curves and hitting the max steer limit, which I believe is a known issue for 2017-2019 Impreza/Crosstrek models. Here's a sample: 6f35adacf2529520|2022-08-03--04-07-46--13

**Comment by adeebshihadeh** [comment]
Holding off until we can really make the experience great with #25456

**Pull request closed without merging**
