### PR TITLE
ui: Raylib CameraView Demo Application

### PR DESCRIPTION
**Pull request by deanlee**
Screenshot from 2024-08-19 20-59-08

### CODE REVIEW

**Comment by deanlee** [comment]
Here is the draft version of the Raylib implementation for the spinner:
```
#include <raylib.h>
#include <algorithm>
#include <cmath>
#include <iostream>

Texture2D LoadTextureResized(const char* fileName, int size) {
  Image img = LoadImage(fileName);
  ImageResize(&img, size, size);
  Texture2D texture = LoadTextureFromImage(img);
  UnloadImage(img);
  return texture;
}

int main() {
  const int screenWidth = 1280, screenHeight = 1024;
  const int textureSize = 360, progressBarWidth = 1000, progressBarHeight = 20;
  const float rotationSpeed = 12.0f;
  const int fontSize = 80, textYOffset = 200;

  InitWindow(screenWidth, screenHeight, "");
  SetTargetFPS(20);

  Texture2D commaTexture = LoadTextureResized("../assets/img_spinner_comma.png", textureSize);
  Texture2D spinnerTexture = LoadTextureResized("../assets/img_spinner_track.png", textureSize);

  Vector2 screenCenter = {screenWidth / 2.0f, screenHeight / 2.0f};
  Vector2 spinnerOrigin = {spinnerTexture.width / 2.0f, spinnerTexture.height / 2.0f};
  Vector2 commaPosition = {screenCenter.x - commaTexture.width / 2.0f, screenCenter.y - commaTexture.height / 2.0f};

  float rotationAngle = 0.0f;

  while (!WindowShouldClose()) {
    rotationAngle = fmod(rotationAngle + rotationSpeed, 360.0f);

    BeginDrawing();
    ClearBackground(BLACK);

    DrawTexturePro(spinnerTexture, {0, 0, (float)spinnerTexture.width, (float)spinnerTexture.height},
                   {screenCenter.x, screenCenter.y, (float)spinnerTexture.width, (float)spinnerTexture.height},
                   spinnerOrigin, rotationAngle, WHITE);
    DrawTexture(commaTexture, commaPosition.x, commaPosition.y, WHITE);

    float textY = screenHeight - textYOffset - progressBarHeight;
    if (std::cin.rdbuf()->in_avail() > 0) {
      std::string userInput;
      if (std::getline(std::cin, userInput)) {
        if (std::all_of(userInput.begin(), userInput.end(), ::isdigit)) {
          int progressValue = std::clamp(std::stoi(userInput), 0, 100);
          Rectangle progressBar = {screenCenter.x - progressBarWidth / 2.0f, textY, progressBarWidth, progressBarHeight};
          DrawRectangleRounded(progressBar, 0.3f, 10, GRAY);
          DrawRectangleRounded({progressBar.x, progressBar.y, progressBar.width * (progressValue / 100.0f), progressBar.height}, 0.3f, 10, RAYWHITE);
          DrawRectangleRoundedLines(progressBar, 0.3f, 4, GRAY);
        } else {
          int textWidth = MeasureText(userInput.c_str(), fontSize);
          DrawText(userInput.c_str(), screenCenter.x - textWidth / 2, textY, fontSize, WHITE);
        }
      }
    }

    EndDrawing();
  }

  CloseWindow();
  return 0;
}
```

**Comment by adeebshihadeh** [comment]
How do you like raylib so far?

Going back to nanovg is an option too https://github.com/memononen/nanovg

**Comment by deanlee** [comment]
@adeebshihadeh : It's quite fun to use Raylib; it's even enjoyable!  I prefer Raylib over NanoVG for several reasons. First, the code written with Raylib is much more concise, and the logic is clearer. Its design makes it easier for developers to separate the display layer from the logic layer, allowing for modular implementations. Additionally, Raylib can handle user input, which NanoVG cannot. It also has many auxiliary libraries, such as raylib-ui, making it easy to extend.

**Comment by adeebshihadeh** [comment]
Can we do the move incrementally like we did with NanoVG -> Qt? https://github.com/commaai/openpilot/pull/23133/

I'm thinking we start with the onroad ui.

**Comment by deanlee** [comment]
Okey, here's my initial plan:

    1. Step One: Embed the Raylib window into the AnnotatedCameraWidget to handle all its rendering tasks.
    2. Step Two: Embed the Raylib window into the parent of AnnotatedCameraWidget, taking over rendering and user input for all its child windows.
    3. Continue embedding Raylib into higher-level parent windows until it becomes the sole window managing the entire UI.

I will need some time to plan and test, especially for the first step. During this period, could you add Raylib to the thirdparty directory when you have a chance? This will allow us to compile and run the tests directly with future submissions.

**Comment by adeebshihadeh** [comment]
Sounds good. Setting up in #33367.

**Comment by deanlee** [comment]
Figured out a way to embed the raylib window in Qt. step-by-step migration should be manageable.

Screenshot from 2024-08-24 13-08-29

**Comment by maxime-desroches** [comment]
This PR was closed because of a git history rewrite.
Please read https://github.com/commaai/openpilot/issues/33399 for what to do with your fork and your PRs.

**Pull request closed without merging**
