### PR TITLE
Body UI: Show battery percentage in bottom-right corner

### PR DESCRIPTION
**Pull request by kfatehi**
Added battery percentage to the carState which required https://github.com/commaai/cereal/pull/290 

I did not retarget the cereal git submodule in this PR.

I did however implement a battery monitor as per the attached image.

IMG_1449

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Consider using a 🔋 instead of a ❤️...

**Comment by kfatehi** [comment]
@ErichMoraga I agree with you. Changed it. Thank you

**Comment by adeebshihadeh** [comment]
Nice, I was going to do this soon! Here's the design we have (ignore the arrow). The whole body UI is on a grid system, but I started with GIFs for the face at first for simplicity. Let's break this up into two PR's:
* implementing the grid system in the UI (with both faces)
* adding the battery indicator from this design

image

**Comment by geohot** [comment]
See my comment on cereal, if we are going to add this to carState it should apply to cars also. Don't privilege the body!

**Comment by kfatehi** [comment]
> Nice, I was going to do this soon! Here's the design we have (ignore the arrow). The whole body UI is on a grid system, but I started with GIFs for the face at first for simplicity. Let's break this up into two PR's:
> 
> * implementing the grid system in the UI (with both faces)
> * adding the battery indicator from this design

@adeebshihadeh thank you. I don't have a lot of time (I go back to work on monday and can't really code on side stuff that much when getting drained during the day coding for my job) nor the knowledge/talent in Qt so I would say since you were already planning to work on it maybe it's best to just close this one out. But maybe tomorrow just for fun and learning I will follow your guidance by opening two new PRs -- I have so many questions though so I think the quality will suck compared to what you had in mind, this is what I have in mind at this moment should I attempt to split this into the 2 PRs:

1. Branching off master, changing the body UI to use QGridLayout with both faces loaded. I didn't quite understand if you are trying to move away from using the GIFs or not, but I'll try something out
2. Branching off [the carstate PR](https://github.com/commaai/openpilot/pull/24386) to bring in the battery value into the QGridLayout per the design that you provided. My naive thought is to try and use color styling in combination with the [UTF-8 center dot character](https://www.compart.com/en/unicode/U+00B7), · · · · ·, if it will look like the design or not I do not know yet. If it doesn't then I guess I could use QPainter and make circles with it.

**Pull request closed without merging**
