### PR TITLE
low upload / default upload / full upload toggle for cellular

### PR DESCRIPTION
**Pull request by yuzisee**
**Description** 

Attempts to implement a toggle on cell:
```
▸ full upload -- i have unlimited, upload whatever (we will grab your segments over cell, not available for full prime)
▸ prime upload -- current prime policy (default)
▸ low upload -- prime policy without qlog/qcam
```

Original discussion https://discord.com/channels/469524606043160576/954493346250887168/1161103504761434182

**Verification**

I'm completely new to the openpilot codebase, so any pointers on how I can test this would be super helpful!

I used #24742 as a reference for how we make three-choice toggles, and used #23734 as a reference for how the upload policy is implemented.

Thanks!

### CODE REVIEW

**Comment by wired4sound** [comment]
Would like to see something more along the lines of an option that when you request a file upload via connect, it doesnt have to wait for wifi.   Or a "force" option in the connect uploads interface to tell comma not to wait for wifi on that particular file?

**Comment by jakethesnake420** [comment]
Seems like a no brainer to have this feature but as it stands this code is not up to par to be merged.

**Comment by yuzisee** [comment]
> this code is not up to par to be merged

Yeah, happy to make improvements!

> modify the dispatcher with a bool param to allow uploads over cellular when requested explicitly by the user

Cool, like this https://github.com/commaai/openpilot/pull/30500/commits/01f1fa18fcdde80d44422edcf6a38ac0fae1c63d you mean?

**Comment by jakethesnake420** [comment]
Keep it simple, this is stock openpilot. All you need to do is use the GsmMetered param in athenad and add a toggle to stop uploader when on a metered connection. Then update the tests.

**Comment by yuzisee** [comment]
> Keep it simple, this is stock openpilot. All you need to do is use the GsmMetered param in athenad and add a toggle to stop uploader when on a metered connection.

Thanks! I put a simplified version here https://github.com/commaai/openpilot/pull/30569 that [doesn't implement the entire original description](https://discord.com/channels/469524606043160576/954493346250887168/1161103504761434182) but is much simpler and follows the approach you suggest. It's lighterweight and easier to work with for sure!

> Then update the tests. Oh and try testing your code and you will see it doesn't stop q uploads

Yes! As I mentioned above https://github.com/commaai/openpilot/pull/30500#issue-2001325396 I'm completely new to the openpilot codebase, so any pointers on how I can test this would be super helpful!

**Pull request closed without merging**
