### PR TITLE
Lexus GS 300h port + modifications to ACC detection for Toyotas

### PR DESCRIPTION
**Pull request by wocsor**
- ACC_ACTIVE added to _toyota.dbc. Lexus GS and IS don't report ACC status through CRUISE_STATE (always 0000) so this was necessary for Lexus GS. It also work on other Toyotas (tested Corolla)
- Panda controls allowed detection changed to ACC_ACTIVE. Same reason as above. Also tested with Corolla. There are 3 other bits that can be checked for redundancy.
- Added Lexus GS 300h DBC

The ACC_ACTIVE signal was found inside the "leaked toyota dbc" and listed as XACCACT.

### CODE REVIEW

**Comment by vanillagorillaa** [comment]
Looks like a lot of stuff not related to port, can we clean this up a bit?

**Comment by wocsor** [comment]
can do, should I open different PRs in opendbc and panda and open a new PR with only the OP related stuff here?

**Comment by vanillagorillaa** [comment]
Yes, that's usually preferred

**Comment by quillford** [comment]
@wocsor seems like you merged my lexus_is branch in here. I'd prefer my IS port not be upstreamed yet

**Comment by wocsor** [comment]
I used some stuff from the IS port, but the IS is not included in this PR

**Comment by rbiasini** [comment]
made obsolete by https://github.com/commaai/openpilot/pull/620

**Pull request closed without merging**
