### PR TITLE
Optimize Honda Accord stop and go resume too slow issue.

### PR DESCRIPTION
**Pull request by javenzy**
When the leader car is stopped and gone, Honda Accord will take a long time to start to go.Sync vEgoStarting and startAccel parameters from Hyundai to let the car resume quickly.

### CODE REVIEW

**Comment by royjr** [comment]
I think `startAccel` is only used when `long_control_state == LongCtrlState.starting` which is only if `startingState` is set

**Comment by sshane** [comment]
Can you post a route with the poor acceleration, then with this PR showing the differences?

**Comment by javenzy** [comment]
> Can you post a route with the poor acceleration, then with this PR showing the differences?

OK, I will post the route to check soon.Thanks!

**Comment by javenzy** [comment]
> I think `startAccel` is only used when `long_control_state == LongCtrlState.starting` which is only if `startingState` is set

yes, I think when my car stop and go following leader car, system will run into the LongCtrlState.starting state.

**Comment by sshane** [comment]
Closing for inactivity.

**Pull request closed without merging**
