### PR TITLE
Add --warn-redundant-casts to mypy checks

### PR DESCRIPTION
**Pull request by herman5**
**Description**

Part of #24277

Note: Pylint started failing `no-member` and `import-error` checks when enabling `--warn-redundant-casts`. I addressed the error checks but wasn't expecting new mypy behavior to affect pylint.

**Verification**

`$ pre-commit run --all`

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
> Note: Pylint started failing `no-member` and `import-error` checks when enabling `--warn-redundant-casts`. I addressed the error checks but wasn't expecting new mypy behavior to affect pylint.

Are you sure pylint didn't silently update? These should be completely isolated.

**Comment by herman5** [comment]
> Are you sure pylint didn't silently update? These should be completely isolated.

Just pulled from upstream master and tested mypy, pylint, and pre-commit checks locally. I was mistaken; the added mypy checks don't affect pylint's behavior - the lint checks are just broken on master:

```
$ git status
On branch master
nothing to commit, working tree clean

$ pre-commit run --all
Check hooks apply to the repository......................................Passed
Check for useless excludes...............................................Passed
check python ast.........................................................Passed
check json...............................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
check for added large files..............................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

common/realtime.py:43: error: Module has no attribute "sched_setaffinity"
Found 1 error in 1 file (checked 427 source files)

flake8...................................................................Passed
pylint...................................................................Failed
- hook id: pylint
- exit code: 2

************* Module scripts.waste
scripts/waste.py:9:2: E1101: Module 'os' has no 'sched_setaffinity' member (no-member)
************* Module common.realtime
common/realtime.py:38:4: E1101: Module 'os' has no 'sched_setscheduler' member (no-member)
common/realtime.py:38:44: E1101: Module 'os' has no 'sched_param' member (no-member)
common/realtime.py:43:4: E1101: Module 'os' has no 'sched_setaffinity' member (no-member)

-------------------------------------------------------------------
Your code has been rated at 9.96/10 (previous run: 10.00/10, -0.04)


--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)


--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

************* Module selfdrive.car.docs
selfdrive/car/docs.py:6:0: E0401: Unable to import 'natsort' (import-error)
************* Module latency_logger
tools/latencylogger/latency_logger.py:5:0: E0401: Unable to import 'mpld3' (import-error)

-------------------------------------------------------------------
Your code has been rated at 9.99/10 (previous run: 10.00/10, -0.01)

cppcheck.................................................................Passed
```

This PR should fix that as well as account for the `--warn-redundant-casts` check:

```
$ git status
On branch mypy_checks
Your branch is up to date with 'origin/mypy_checks'.
nothing to commit, working tree clean

$ pre-commit run --all
Check hooks apply to the repository......................................Passed
Check for useless excludes...............................................Passed
check python ast.........................................................Passed
check json...............................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks................................................Passed
check for added large files..............................................Passed
mypy.....................................................................Passed
flake8...................................................................Passed
pylint...................................................................Passed
cppcheck.................................................................Passed
```

**Comment by herman5** [comment]
@adeebshihadeh Did you want to move forward with this? I've got another PR queued up for additional checks.

**Comment by adeebshihadeh** [comment]
I reverted the other changes since it passed on my machine without them.

**Pull request merged**
