### PR TITLE
Refactor c++ replay

### PR DESCRIPTION
**Pull request by deanlee**
- [x]  fix leaks
- [x] lthread-safe
- [x] search encodeIdx in adjacent segments.
- [x]  pub messages directly from buffer, without  deep copy
- [x] send frames for all cameras
- [x] falls back to qlogs + qcameras
- [x] replay from local/remote route
- [x] deal with missing segments or files
- [x] memory usage is about 1GB
- [x] fix segment fault

It has been split into small PRs for easier review:

- Refactor framereader  #21141
- Refactor logreader #21152
- CameraServer #21155

Usage/Test:

1. run `selfdrive/ui/replay/replay dongle_id\|YYYY-MM-DD--HH-MM-SS` to start the replay
Replay will first try to load segments from LOG_ROOT, if it fails, it will be loaded from the server.
2. run `selfdrive/ui/_ui `to watch the replay

test

### CODE REVIEW

**Comment by deanlee** [comment]
The prerequisite PRs for this are :
- https://github.com/commaai/openpilot/pull/21002
- https://github.com/commaai/openpilot/pull/21000

**Comment by deanlee** [comment]
There are still many things that can be improved, which can be done in the future.

**Comment by zorrobyte** [comment]
Unfortunately, I've never been able to get video working. My ffmpeg version is `ffmpeg version 4.2.4-1ubuntu0.1`

image

**Comment by deanlee** [comment]
The console does not look like the output of this PR, is it tested on the master?

> Unfortunately, I've never been able to get video working. My ffmpeg version is `ffmpeg version 4.2.4-1ubuntu0.1` and I'm on a fresh install of 20.04

**Comment by zorrobyte** [comment]
That was on master, sorry about that. I went ahead and pulled your latest commit `314949bfd064d4bdbf4edbb454e92726cfe3e60d` and still don't have any video output

Screenshot from 2021-06-05 10-07-36
Screenshot from 2021-06-05 10-09-08

unlogger.py does, however
Screenshot from 2021-06-05 10-12-25
Screenshot from 2021-06-05 10-12-01

I could be mistaken here, though. Is `/selfdrive/ui/replay` supposed to work with video? It was my understanding that unlogger.py was going to be depreciated.

**Comment by deanlee** [comment]
It looks like still on the master branch, have you recompiled?

**Comment by zorrobyte** [comment]
Well.. it may help if I switch to the proper branch, eh?

Done, compiled clean and...
***@***.***ThinkPad-L13-Yoga-Gen-2:~/danop/selfdrive/ui/replay$ git commit
On branch refactor_replay
Your branch is up to date with 'origin/refactor_replay'.

nothing to commit, working tree clean
***@***.***ThinkPad-L13-Yoga-Gen-2:~/danop/selfdrive/ui/replay$ git branch
  master
  refactor_frame_reader
* refactor_replay

~/danop/selfdrive/ui/replay$ ./replay
"bdad50b8a1f9fa8e|2021-06-04--19-54-00"
replay: selfdrive/common/clutil.cc:64: cl_device_id
cl_get_device_id(cl_device_type): Assertion `CL_SUCCESS ==
clGetPlatformIDs(0, __null, &num_platforms)' failed.
Aborted (core dumped)

**Comment by adeebshihadeh** [comment]
Can you rebase?

**Comment by deanlee** [comment]
merged

**Comment by deanlee** [comment]
need to resolve conflicts with master

**Comment by adeebshihadeh** [comment]
Do we still want to merge this or is it being split up?

**Comment by deanlee** [comment]
closed.this is obsolete.it is being split up

**Pull request closed without merging**
