### PR TITLE
loggerd: fixed the message queue growing infinitely when the incoming encoders less than max_waiting.

### LINKED ISSUE #27512: PC: loggerd memory leak
### Describe the bug

running loggerd the amount of memory used keeps going up until it runs out

### OS Version

Ubuntu 20.04

### openpilot version or commit

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by deanlee**
Issue: `offset_segment_num > s->rotate_segment` will be always true if the incoming encoder types less than the `max_waiting`:

https://github.com/commaai/openpilot/blob/ebd25b8a7de29542be7c6a213c578bc363999857/selfdrive/loggerd/loggerd.cc#L155-L165

Set the max_waiting according to the incoming encoders to fix this issue, resolve #27512

### CODE REVIEW

**Comment by bleufa** [comment]
idk if this fixes the issue, I can still see the memory usage increasing in top

**Comment by deanlee** [comment]
That's weird. I ran it for an hour and it's lgtm.

**Comment by deanlee** [comment]
Probably a small memory leak caused by another issue

**Comment by bleufa** [comment]
i'm not running encoderd at all, just in offroad I can see the memory usage increasing after running for a few minutes. also see possibly lost bytes in valgrind

**Comment by bleufa** [comment]
can you see the memory usage increasing?

**Comment by deanlee** [comment]
Not yet. I can't see any place where memory leaks may occur If the encoderd is not running.

**Pull request closed without merging**
