### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Fixing https://github.com/commaai/openpilot/issues/2154

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can we add two lines to copy/paste that run the start scripts without having to clone the repo? Ideally, someone should be able to stumble across openpilot, copy and paste two lines from the README, and see openpilot running on their computer.

**Comment by grekiki** [comment]
> Can we add two lines to copy/paste that run the start scripts without having to clone the repo? Ideally, someone should be able to stumble across openpilot, copy and paste two lines from the README, and see openpilot running on their computer.

Hm like a docker container that would have the repository already preinstalled? User then just has to start the container

**Comment by adeebshihadeh** [comment]
We already have that. We just need two lines that curl each script and run them instead of needing to clone openpilot.

**Comment by grekiki** [comment]
I think that should work

**Pull request merged**
