### PR TITLE
tinygrad: bump to 0.5

### PR DESCRIPTION
**Pull request by geohot**
22.8 ms -> 20.3 ms, 12.3% faster thanks to your friendly neighborhood tiny corp!

Also comes with a free 0.22W of power savings.

- [x] Update release files
- [x] Confirm model output is correct and update replay cache
- [x] Fix and test the transformer weight regression (tinygrad)
- [x] Remove OPTWG (tinygrad)

Before:
```
    modelExecutionTime = 0.022863757,
    modelExecutionTime = 0.022615636,
    modelExecutionTime = 0.022860788,
```

After:
```
    modelExecutionTime = 0.020108858,
    modelExecutionTime = 0.020799421,
    modelExecutionTime = 0.020336615,
  ```

### CODE REVIEW

**Comment by geohot** [comment]
I assume that's within what's allowed on the plan y?

**Comment by geohot** [comment]
Wait so is the power used on the left or right?

```
-----------------------------------
Baseline 1.80W
camerad              2.15W  2.17W
modeld               1.15W  0.93W
dmonitoringmodeld    0.40W  0.39W
encoderd             0.23W  0.30W
-----------------------------------
FAIL: test_camera_procs (__main__.TestPowerDraw) (proc='modeld')
```

**Comment by adeebshihadeh** [comment]
> Wait so is the power used on the left or right?

It's on the right. I'll add a header.

**Comment by adeebshihadeh** [comment]
> Flaky test?
> 
> `common.timeout.TimeoutException: timed out testing process 'locationd'`

Yes, locationd has been a little flaky recently in replay.

> Also, is there low hanging fruit to increase the speed of CI? Some guy added multithreading to the tinygrad tests and free 2x

Largely it's the 1.5 minutes for the docker pull, plus the slow GitHub runners.

**Comment by wumaolin** [comment]
nice man!!!!  i m is very like                        thx you

**Pull request merged**
