### PR TITLE
Mazda:  CX-5 22 FW FP

### PR DESCRIPTION
**Pull request by Jafaral**

### CODE REVIEW

**Comment by sshane** [comment]
Are these all from 661621a8442f0688?

**Comment by Jafaral** [comment]
@sshane , no, only one of them. I  can ask the users to provide ids, but that is what I got from them.

**Comment by adeebshihadeh** [comment]
Yes, we'd like to confirm these values with their routes.

**Comment by Jafaral** [comment]
@sshane I dropped the ones I couldn't get dongle  id for.

**Pull request merged**
