### PR TITLE
cabana: more advanced DBC management features

### PR DESCRIPTION
**Pull request by pd0wm**
Improve menu to open/close/assign buses for individual DBCs

Screenshot 2023-04-19 at 11 59 29

### CODE REVIEW

**Comment by deanlee** [comment]
It feels difficult to operate with too many levels of menus. Is it possible to merge the last two levels of menus into one?

**Comment by deanlee** [comment]
>  I could add a separator between every DBC?

not sure if it's better or not

**Comment by pd0wm** [comment]
This is what a merged menu would look like.

Screenshot 2023-04-19 at 12 51 59

**Comment by deanlee** [comment]
Would it be better to have consistent formats between the title bar and menu bar?  think（..） looks more clear than [...],what do you think?

**Pull request merged**
