### PR TITLE
Replace ThneedModel with TinygradModel

### PR DESCRIPTION
**Pull request by mitchellgoffpc**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Started a #current-projects for this in Discord: https://discord.com/channels/469524606043160576/1283171724719951904

**Comment by commaci-public** [comment]
ref for commit 1a2414d3175b8469546b640e4e630e5c34cae106: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_1a2414d3175b8469546b640e4e630e5c34cae106.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 0f2cf7d57d10ea53443b297da01401e57f40892a: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_0f2cf7d57d10ea53443b297da01401e57f40892a.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 3b49daff7f1ed5e30b4d193db0bd613a0e4725d2: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_3b49daff7f1ed5e30b4d193db0bd613a0e4725d2.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit a3254f20dd989561b8d3cb83c25c41a1a74dffc5: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_a3254f20dd989561b8d3cb83c25c41a1a74dffc5.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 877b8b3ea0d6a7b786558545dd0178d7541415e9: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_877b8b3ea0d6a7b786558545dd0178d7541415e9.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 2e1236737c9e5ec139627c2ee8aac085f9141ed5: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_2e1236737c9e5ec139627c2ee8aac085f9141ed5.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit afb708e062de2814be0bea34acee3360d942f9b9: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_afb708e062de2814be0bea34acee3360d942f9b9.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 386f98e8c50ab5db2b0c6ee9d8da0b23d29aa18b: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_386f98e8c50ab5db2b0c6ee9d8da0b23d29aa18b.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit c460fc6213698cb75b510ad1d7afefe0e4c98966: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_c460fc6213698cb75b510ad1d7afefe0e4c98966.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 72be18b528464967bb4f002d2d2ffe4fef7832dd: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_72be18b528464967bb4f002d2d2ffe4fef7832dd.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 40beac83f13b1d32f9b3617389e6a7e390ab91d3: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_40beac83f13b1d32f9b3617389e6a7e390ab91d3.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 0e4ab61b45ad103a52e4b57507f88de46a446e52: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_0e4ab61b45ad103a52e4b57507f88de46a446e52.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 3a3f10c62a186eb919099ebc5832b2b3dc8e1ff2: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_3a3f10c62a186eb919099ebc5832b2b3dc8e1ff2.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 0a5938d7829b4e65121ab228cfad93d679a792a0: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_0a5938d7829b4e65121ab228cfad93d679a792a0.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit c4e7423270e0bf0a20efa16472bfaee1b5e7d315: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_c4e7423270e0bf0a20efa16472bfaee1b5e7d315.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 6cb218ffc6ececbd6dce9168986aa6d399814dd9: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_6cb218ffc6ececbd6dce9168986aa6d399814dd9.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 0921974b02574807041f23283ab0142468fae39a: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_0921974b02574807041f23283ab0142468fae39a.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 29ff1799d2b324aa67edb2883515fa27e81be715: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_29ff1799d2b324aa67edb2883515fa27e81be715.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit d23d017604f47e0744edbe659808b8ee14bd34b6: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_d23d017604f47e0744edbe659808b8ee14bd34b6.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 48007501eb57a35dbd669edfb45b6d208ce40993: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_48007501eb57a35dbd669edfb45b6d208ce40993.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit b27a22d2cf0833c0cdad1b74fea42269abe9f745: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_b27a22d2cf0833c0cdad1b74fea42269abe9f745.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 12345e0649295604c0491007f4fe81c2b5004029: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_12345e0649295604c0491007f4fe81c2b5004029.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 9e7660e86872c7ac36b3feebf3ee60544ac4d73e: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_9e7660e86872c7ac36b3feebf3ee60544ac4d73e.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit bbae017e16a876eb4eddc90130aec3407a0fc47e: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_bbae017e16a876eb4eddc90130aec3407a0fc47e.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 12345e0649295604c0491007f4fe81c2b5004029: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_12345e0649295604c0491007f4fe81c2b5004029.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit a0caa7c7801e4ddec69bc70e80a7e23bd4ec804b: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_a0caa7c7801e4ddec69bc70e80a7e23bd4ec804b.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 6c438049779098d03f59afc4cdef020cf16f9427: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_tinygrad-runner/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_6c438049779098d03f59afc4cdef020cf16f9427.bz2<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Pull request merged**
