### PR TITLE
Create vdbc_acura_ilx_2016_nidec.dbc

### PR DESCRIPTION
**Pull request by TheMutley**
The file now follow the Vector dbc format. 
Byte order is now correctly set in the big endian format (motorola). 
IDs are now in decimal. 
Added the node list that was missing.
Added the NEO node (which is follow some of the ADAS behavior).
Mapped all signals to a receiver node.

### CODE REVIEW

**Comment by geohot** [comment]
Can you merge these into one pull request?

What is the NEO node?

Also, do these DBCs work with openpilot? If so, can we overwrite the ones in there? I like the idea of using the proper standard.

**Comment by TheMutley** [comment]
I will merge everything in one pull. 

The NEO is the Comma NEO :) When the ADAS is no longer there, he's being promoted as the transmitter and receiver for some messages in place of the ADAS. So for some messages, you have two transmitters right now, but we could remove the ADAS since it's not supposed to be there when the NEO is installed. 

Those DBC won't probably work with the openpilot , since I made changes that could affect the behavior (mostly the byte ordering). I've put them in a separate directory for this reason. I could check the code and make the changes to make them work. I just didn't know if it was something you were already working on. Let me know if you want me to do it. 

Then we could get rid of the previous dbcs and use only these new files.Everything will then be with the proper standard as these dbc files can be used in wide variety of software as it's the most popular CAN database format. The editor, CANdb++, is free also .

**Comment by geohot** [comment]
Would love to have openpilot read the standard, let me know if it doesn't for some reason and we'll fix that bug.

**Comment by TheMutley** [comment]
I will work on it then!

**Pull request closed without merging**
