### PR TITLE
Update fingerprints.py

### PR DESCRIPTION
**Pull request by arne182**
Added Fingerprint for RAV4 2018 Style Selection

### CODE REVIEW

**Comment by energee** [comment]
This fingerprint should really be merged with the "TOYOTA RAV4 2017 HYBRID"

**Comment by arne182** [comment]
I agree. Can that be done? I am new here and did not know that you can merge the fingerprints

**Comment by energee** [comment]
Yes, find the additional ID's in your fingerprint and put them in RAV4 hybrid array, the first few examples I see are: 

`296L: 8, 550L: 8, 560L: 7, 581L: 5, 713L: 8, 953L: 3, 1184L: 8,`

It shouldn't matter that the current RAV4 has other ID's that are not in your fingerprint. Openpilot just searches these arrays for one that has all of your IDs and when it does, it matches and identifies your car.

**Comment by arne182** [comment]
Excellent. I will submit a new pull request

**Pull request closed without merging**
