### PR TITLE
Adding additional IP range for android hotspot

### PR DESCRIPTION
**Pull request by icmma**
Please see original PR for full logs although i did update code same day but wasn't sure which method was right later found out there was no wrong method at all but couldn't do much since PR was closed before i could do anything. https://github.com/commaai/openpilot/pull/530

### CODE REVIEW

**Comment by eFiniLan** [comment]
@icmma would it be better to use [ANDROID_METERED](https://www.lorier.net/docs/android-metered) to check if you are on a metered network? sorry I don't have the environment to test proxy but that's what I'm getting when I tether from another android phone:
```bash
$ dumpsys wifi | grep mDhcpResults
mDhcpResults IP address 192.168.7.241/24 Gateway 192.168.7.1  DNS servers: [ 192.168.4.2 8.8.8.8 ] Domainssimprogroup.com DHCP server /192.168.7.1 Vendor info ANDROID_METERED lease 36000 seconds
```

**Comment by pd0wm** [comment]
That is pretty interesting. Didn't know about that DHCP option.

@icmma, your PR is breaking functionality for android and iOS users in the default IP ranges.

**Comment by icmma** [comment]
@eFiniLan DHCP is always better.

**Comment by icmma** [comment]
@pd0wm  will test it.oir again but I like the DHCP method however need testing to see if it works for proxy as well. @eFiniLan  I do use another Android phone where I'm tethering from it's kind of tricky since I don't have tethering plan since it's Android you can always find alternatives one is rooting other is without . I like to make things simple for users in general where they don't have to root phones to get tethering you can find some apps that does it but they use proxy there is another option which is ADB but I found it more user friendly so anyone can do it in general.

**Comment by rbiasini** [comment]
@pd0wm @icmma : merge or close?

**Comment by pd0wm** [comment]
I'll close the PR for now. You can reopen it when it doesn't break functionality for regular Android and iOS users.

**Pull request closed without merging**
