### PR TITLE
ui: refactor draw model

### PR DESCRIPTION
**Pull request by deanlee**
1. refactor model drawing.
2.  remove unused "liveMpc" related funtions.(I'll restore them if you think it's necessary)

### CODE REVIEW

**Comment by pd0wm** [comment]
Removing live MPC stuff is fine!

**Comment by deanlee** [comment]
rebased(twice), can you help me review the code when you have time? @adeebshihadeh .thank you vevry much

**Comment by adeebshihadeh** [comment]
Thanks @deanlee! I’ll review this tomorrow

**Comment by HaraldSchafer** [comment]
Thanks @deanlee I rebased my new model PR on this. https://github.com/commaai/openpilot/pull/2123 It will be merged whenever that is merged.

**Comment by deanlee** [comment]
OK

**Pull request closed without merging**
