### PR TITLE
Corolla TSS2 Hybrid fp

### PR DESCRIPTION
**Pull request by rav4kumar**

### CODE REVIEW

**Comment by VirtuallyChris** [comment]
What route is this from?

**Comment by rav4kumar** [comment]
I’ll get the route from the person. BRB

**Comment by vanillagorillaa** [comment]
Also, the versions are out of order. Not a huge deal, but for consistency sake.

**Comment by rav4kumar** [comment]
actually i cannot get the route. if you need route in order to be upstream then feel free to close this pr. 
Thank you

**Pull request closed without merging**
