### PR TITLE
Fingerprint: 2023 Tucson Limited ICE fwdCamera

### PR DESCRIPTION
**Pull request by foodbandlt**
**Car**
2023 Tucson Limited ICE

**Route**
dac7d5a181018bf9/00000000--843a60153a
df7a592086642093/00000000--81f087a111

Coincidentally two people rolled in with the same new FW! 

Doesn't seem like it got picked up in the latest auto-fingerprint PR or fuzzy fp on master-ci.  Maybe because the fwdCamera firmware is shared with HYUNDAI_SANTA_CRUZ_1ST_GEN, so there were two options? @sshane

### CODE REVIEW

**Comment by sshane** [comment]
Can't be merged as the camera has the Santa Cruz physical part number, which means that the tuning is likely different than other Tucsons :/ https://github.com/commaai/openpilot/issues/27206

We'll fix this when we have time to get to it. For now you can try the branch in that issue

**Comment by sshane** [comment]
That said, can you let me know when the users drive on openpilot a lot more? I want to check their lateral accel factors to see if this is still a real problem.

**Comment by foodbandlt** [comment]
> That said, can you let me know when the users drive on openpilot a lot more? I want to check their lateral accel factors to see if this is still a real problem.

dac7d5a181018bf9 has several drives logged on it, and has complained about jerky steering performance :(  See https://discord.com/channels/469524606043160576/1223290858468540557

**Comment by foodbandlt** [comment]
The end of this segment he said is a good example, logs uploaded: `dac7d5a181018bf9/00000002--c33fc8c9be/17` 

Looks like the live torque params might never be valid, though they've been driving on it for quite a while.  Could that contribute, like the issue said?

**Pull request closed without merging**
