### PR TITLE
cabana: fix chart high-dpi issues

### PR DESCRIPTION
**Pull request by deanlee**
related discussions: 
https://github.com/commaai/openpilot/pull/27896#issuecomment-1507262606

### CODE REVIEW

**Comment by pd0wm** [comment]
Looks good on my macbook with hi-dpi now! Thanks for looking into it.

I noticed you didn't bring over the changes to invalidate the cache when dragging to a different monitor (in case you have a hi-dpi and non hi-dpi) monitor. When testing that I had a crash once, but wasn't able to reproduce it. Do you think we need a lock around the pixmap?

**Comment by deanlee** [comment]
does this line fixed the mixed hi-dpi, non hi-dpi monitors issue?  https://github.com/commaai/openpilot/pull/27896/files#diff-75828cd93d8908bdfa27fe5ee42a91043738815e9945fc73fdf83b9f943b9321R45 :

`QObject::connect(window()->windowHandle(), &QWindow::screenChanged, [this]() { resetChartCache(); });`

**Comment by pd0wm** [comment]
Yes &QWindow::screenChanged is emitted when dragging to a new monitor.

**Comment by deanlee** [comment]
> edit: I also noticed now the button pixmaps are not hi-dpi, but this has always been the case. Maybe something we want to address as well?

I'll fix it in another pr.

**Pull request merged**
