### PR TITLE
add two new CX-5 2018 fw

### PR DESCRIPTION
**Pull request by Jafaral**
Two new variations of CX-5 fw. 
Fix a misplaced mazda3 fw. 

Signed-off-by: Jafar Al-Gharaibeh <to.jafar@gmail.com>

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
dongle IDs?

**Comment by Jafaral** [comment]
I don't have them. I can ask the owners if IDs are needed.

**Comment by adeebshihadeh** [comment]
Yes, we'll need them to verify the fingerprints

**Comment by Jafaral** [comment]
Ok, I will ping them.

**Pull request merged**
