### PR TITLE
cabana: add `Node` column to message table

### PR DESCRIPTION
**Pull request by deanlee**
1. add `Node` column to message table
2. add menu to title bar to customize the columns displayed.
3. cleanup code

### CODE REVIEW

**Review by thegauravgiri — APPROVED** [review]
Looks good to me

**Review by thegauravgiri — APPROVED** [review]
Looks good to me

**Comment by adeebshihadeh** [comment]
Replay test is failing
```
(4378 durations < 5s hidden.  Use -vv to show these durations.)
=========================== short test summary info ============================
FAILED tools/replay/tests/test_replay::Replay
=========== 1 failed, 1196 passed, 348 skipped in 436.53s (0:07:16) ============
```

**Comment by deanlee** [comment]
@adeebshihadeh it's a issue in replay test. 
The test code is quite outdated compared to the current code. I'll fix it in another pr.

**Comment by sshane** [comment]
was thinking of requesting this! super useful, will try later

**Pull request merged**
