### PR TITLE
Showcase prototype implementation of enhancement #20075 to get paths from configuration file

### PR DESCRIPTION
**Pull request by wolterhv**
**Description** 

This PR is merely for showcasing what I mean with the enhancement request #20075, it is not meant to be actually merged to master.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What problem does this solve? It’s adding 170 lines for something that’s more brittle.

**Comment by wolterhv** [comment]
Well, to be fair, it's not 170 lines of new brittle code. 70 of them belong to a hurriedly coded, with much room for improvement, config file reading class, and 86 to a heavily-commented config file.

What problem does it solve? Mainly it just centralizes location definitions. Currently, paths to relevant files are spread all around the code. In my opinion, this could become a problem in the future, specially since some of the paths to a single object are defined in multiple places. I guess this is where my opinion of that not being clean and yours of it being better than what I propose diverge.

Secondarily, it allows defining locations for data which are separate from the application source code. I tend to think that keeping logic, configuration and generated data separate is a good idea.

I understand if you think this is not necessarily or really helpful at the current state of things, but just wanted to share the idea. Thanks for looking at it anyway!

**Comment by adeebshihadeh** [comment]
> What problem does it solve? Mainly it just centralizes location definitions.

For many of these, the definition is __file__. This really isn't cleaner.

If you'd like to contribute, I'd suggest looking at issues tagged "enhancement" or "good first issue".

**Comment by wolterhv** [comment]
Fair enough. Thanks for your suggestion about contributing. 

How do you currently define paths in CPP sources, where in python you would use the `__file__` attribute? From what I could scan, mostly absolute paths are defined, either pointing to the user's comma config at `~/.comma` or at locations like `/data/` and `/persist/`.

**Pull request closed without merging**
