### PR TITLE
Block LCA if trailer is connected to vehicle. 

### PR DESCRIPTION
**Pull request by roxasthenobody98**
Referencing cereal#65

LCA should be blocked if a trailer is connected. LCA could potentially cause the trailer to sway if the change is too abrupt, and the driver may lose control of the vehicle in that instance. The driver should manually make the lane change. 

Not all vehicles will have a can message for the 4/7 pin Trailer connector, but those that do should automatically block LCA when connected. 

Code fails test due to unmerged cereal pr.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
This is a fairly unusual use case. Can't you just disable lane changes via the settings toggle?

**Comment by roxasthenobody98** [comment]
I mean, yes. But if we have the ability to do so automatically, we should.

**Comment by roxasthenobody98** [comment]
SUV's like the Highlander, Pilot, Ascent, Palisade, etc should have a can message that would be for trailer connected.

**Comment by adeebshihadeh** [comment]
Closing as this is a fairly unusual use case, but it sounds like a nice feature for a fork!

**Pull request closed without merging**
