### PR TITLE
HKG: simplify Kia K5 compatibility

### PR DESCRIPTION
**Pull request by adeebshihadeh**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
@sshane I only checked the K5, so let's double check this, but it seems LKAS/LFA is standard on all. SCC isn't standard on the K5 though.

**Comment by sshane** [comment]
The default is SCC, but sounds good, I'll double check everything

**Comment by sshane** [comment]
This is a 17 Elantra, the owner's manual says "if equipped" by LKAS. Will try to find a better source for trims and availability.

Screenshot from 2022-06-13 23-23-19

**Comment by adeebshihadeh** [comment]
Let's just do this incrementally as we find things out. Want to merge this for just the K5?

**Pull request merged**
