### PR TITLE
Add 2018 LE ECO Fingerprint

### PR DESCRIPTION
**Pull request by vanillagorillaa**

### CODE REVIEW

**Review by rbiasini — COMMENTED** [review]
@vanillagorilla, if one fingerprint includes the other and there are no mismatches in message lengths, then we can keep only one. Is this the case?

**Comment by vanillagorillaa** [comment]
Comma's Corolla fingerprint has everything in this LE ECO fingerprint plus a few more. Will check that using regular fingerprint will work and will close PR if that's the case

**Comment by energee** [comment]
@rbiasini This is good point, so why the need for multiple fingerprints on Toyotas? Looks like the taiwanese prius is inclusive of the other models... Do some messages have conflicting packet sizes that I didn't see when comparing?

**Comment by rbiasini** [comment]
Oh, I did not check that. If that's the case then yes, we should remove the fingerprints that are included in others.

**Pull request closed without merging**
