### PR TITLE
ui: render markdown in release notes

### PR DESCRIPTION
**Pull request by deanlee**
md2

### CODE REVIEW

**Comment by deanlee** [comment]
add support for multiple levels
```
 * New driving model
   * Trained on one million minutes!!!
   * Fixed lead training making lead predictions significantly more accurate
    * Fixed several localizer dataset bugs and loss function bugs, overall improved accuracy
    * Fixed several localizer dataset bugs and loss function bugs, overall improved accuracy
      * Fixed several localizer dataset bugs and loss function bugs, overall improved accuracy
```
md3

**Comment by pd0wm** [comment]
@deanlee @mayfieldiv 

We decided that it's easiest to roll our own implementation of `markdown`. We want to do it in python however. This way we can easily unittest it against the existing `markdown` package and make sure the output is the same when we run our release notes through it.

**Comment by deanlee** [comment]
so much the better

**Comment by mayfieldiv** [comment]
oh yeah I like that idea. @deanlee are you doing it in python or should I?

**Comment by deanlee** [comment]
@mayfieldiv no, i'm not.:P

**Pull request closed without merging**
