### PR TITLE
Add GM steering rate and EPS torque to CarState

### PR DESCRIPTION
**Pull request by hewers**
**Description** 

Add steering rate, and EPS torque, to GM vehicles like Chevrolet Volt Premier 2017.

Sub-fix for https://github.com/commaai/openpilot/issues/20232 , adding torque and steering rates to multiple vehicles.

**Verification**

- ~~Deploy and drive route~~
- ~~Verify by plotting CarState fields~~

angle
torque

**Route**

4283e5cdbb717eff|2021-03-11--16-47-49

### CODE REVIEW

**Comment by qadmus** [comment]
- Rebased
- Removed opendbc bump (steer rate scale can come later)
- Updated refcommit (not sure why, AUDI A3 was failing?)

**Comment by qadmus** [comment]
Reverted refcommit. process replay still fails. I don't know what I'm doing.

**Comment by jyoung8607** [comment]
Looked at this since I tweaked VW steering signals very recently... reading the log can be a little confusing. Audi A3 happens to be mentioned last because it's the last replay segment to be tested, but the segment that fails replay is actually for the GM Volt.

https://github.com/commaai/openpilot/blob/d023397ba94cd1b2a47acf0e8b900cd8d53eb360/selfdrive/test/process_replay/test_processes.py#L14-L24

```
***** results for segment ae3ed0eb20960a20|2021-01-15--15-04-06--8 *****
	controlsd
		carState.steeringRateDeg: 1044
		carState.steeringTorqueEps: 5909
		controlsState.lateralControlState.pidState.steeringRateDeg: 1044
	radard
	plannerd
	calibrationd
	dmonitoringd
	locationd
	paramsd
	ubloxd
```

Replay mismatch is actually expected and desired for what you're doing, so should just be a matter of bumping the replay ref once you're sure you're happy with it.

**Comment by qadmus** [comment]
@jyoung8607 First time updating the ref, is there a guide (or I'll write one)?

- Anything special required about the route?
- I've preserved the example route, should that always be preserved or is it automatically preserved?
- Replace Volt route in test_processes.py : segments = []
- Run update_ref.py, commit ref_commit

**Comment by jyoung8607** [comment]
I'm not sure you need to replace the current CI route for this purpose. I believe a Comma staffer has to do the actual replay ref bump for you, because to actually use the new replay data in CI, `update_refs` has to send the new baseline logs to an Azure bucket only they can write to.

**Comment by adeebshihadeh** [comment]
Thanks for the PR!

**Pull request merged**
