### PR TITLE
CI: MetaDrive in ga

### PR DESCRIPTION
**Pull request by maxime-desroches**
For https://github.com/commaai/openpilot/issues/30693

Succeed 10 times in a row, will do more testing.

### CODE REVIEW

**Comment by jnewb1** [comment]
Nice! It engaged but I'm curious about the FPS from the sim. We can disable the UI since that will take quite a bit of CPU to software render.

'''selfdrive/ui/qt/onroad.cc: slow frame rate: 5.79 fps'''

**Comment by maxime-desroches** [comment]
@jnewb1 Yeah, seems run better with the ui blocked

**Comment by adeebshihadeh** [comment]
The idea is to replicate the [test_onroad](selfdrive/test/test_onroad.py) coverage both in GitHub Actions and in the simulator, so we don't want to start turning things off. Can we make the UI run nicely during the test? Is that the only thing that lags here?

**Comment by maxime-desroches** [comment]
@adeebshihadeh From my tests it seem to only be the ui lagging and soundd crashing. Do we want the ui running above 15 fps?

**Comment by adeebshihadeh** [comment]
Yes, we want to run the full stack. Does soundd crash consistently or intermittently?

**Comment by jnewb1** [comment]
soundd is crashing because there is no sound device to connect to, we will just have to add a virtual sound card or something

**Comment by adeebshihadeh** [comment]
Closing due to no activity, feel free to reopen if you pick it back up.

**Pull request closed without merging**
