### PR TITLE
Honda Odyssey fingerprint and PID tuning

### PR DESCRIPTION
**Pull request by xuchongang**
This pull requests adds a fingerprint for <Honda- Odyssey - 2020 - EXL>. This is an explorer link to a drive with the stock system enabled: https://my.comma.ai/cabana/?route=6484765a32a70156%7C2019-12-16--16-44-13&exp=1608077685&sig=HYSXqYEA3g%2B4Ic4gmPbxbf2tLMJCzgnd%2BHcdWPpnjMY%3D&max=-1&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F6484765a32a70156%2F1aa0ce8b5f9de26d567834b145e4fb64_2019-12-16--16-44-13.  This is a result of v0.7 that has more strict fingerprint check (without the finger print, my car is added as a mock car), while v0.6.6 can recognize it without problem.

I have also updated the PID parameters for Odyssey as the current default parameters caused ping-ponging on straight roads reported by myself and a few other odyssey users. The tuning increased the Ki value to increase stability. The Kp value was also increased to compenstate the turnability.

## Testing
I have been evaluating the tuned parameter on v0.7. So far, these parameters gave a stable steering on straight roads and good turnability on curvatures.

### CODE REVIEW

**Comment by xuchongang** [comment]
Please hold on this pull request as I would like to do more tests on different road conditions.

**Comment by xuchongang** [comment]
I did some more testing on the road with speed between 60-75. The tuned parameters are relative stable for 40-55; however, if >60, the wobbling become quite obvious. Some furhter testing is definely needed.

**Comment by xuchongang** [comment]
Reduced the PID parameters to reduce the wobbling at high speeds. I have tested about 600 miles at speed up to 60 mph.  I would appreciate if others can test as well.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
