### PR TITLE
[Honda Civic Hatchback 2019 FW] Add missing value for combinationMeter and programmedFuelInjection

### PR DESCRIPTION
**Pull request by pviolette3**
Comma 2 often fails to recognize my Honda Civic Hatchback 2019 on the first car start (reverts to Dashcam mode). After 2-4 restarts of the car, C2 does recognize the car, and drives it well. Therefore, the "Unrecognized mode" does seem like a "fingerprinting" issue, since once C2 recognizes the car it works well.

Here is one attempt at fixing the issue: add the missing value for combinationMeter (78109-TGG-A220\x00\x00), as suggested in [Discord](https://discordapp.com/channels/469524606043160576/621451618122072123/705094577165697054).

However, I'm not sure this will work, because:

1. I notice that this value for Combination Meter appears for both `carFingerprint = 'mock'` ([output](https://pastebin.com/ZYQQzf8L)) and `carFingerprint = 'HONDA CIVIC HATCHBACK 2017 SEDAN/COUPE 2019'` ([output](https://pastebin.com/V8mZwGcv))  - so I suspect there are some other issues.
2. I cannot confirm that a unit test that fails to recognize my car, now passes with this change (see attempt: https://github.com/pviolette3/openpilot/commit/2a1367fa6137ba9fbc637c209f85212e18159fa2)

One other value that stands out to me is, my `gateway` value (`38897-TBA-A020\x00\x00`) shows up in both [Ecu.unknown](https://github.com/commaai/openpilot/blob/master/selfdrive/car/honda/values.py#L441) and [Ecu.gateway](https://github.com/commaai/openpilot/blob/master/selfdrive/car/honda/values.py#L445). Is it possible this issue comes from OP incorrectly recognizing the "gateway" as Unknown in the unrecognized case?

### CODE REVIEW

**Comment by pviolette3** [comment]
An appendix (notes for me)

### Part 1: Set up openpilot
(My setup is, Linux Mint)
1. Fork openpilot, clone fork into `$HOME/openpilot` (do not put subdir).
2. Run `tools/ubuntu_setup.sh` - fix various failure points
-> Need to install pyenv, and ensure it's on $PATH (something went wrong here the first time).
-> Pygames fails to install, I had to add these libraries: https://stackoverflow.com/questions/7652385/where-can-i-find-and-install-the-dependencies-for-pygame
-> Ensure that `pip install -r tools/requirements.txt` has worked correctly.

### Part 2: Demonstrate failing test (this step is not achieved!)

1. Run `python selfdrive/test/test_car_models.py` - Ensure it passes with no changes. (A lot of Cython compiling happens on the first run)
Here was the output of a passing test:

```
(True, [])
.. 25 more lines
(True, [])
TEST SUCCESSFUL
```

2. Download the route file, on a run where the car was unrecognize. I downloaded: `5d02a73998def520_2020-05-03--16-09-07--0--rlog.bz2` from my.comma.ai (--0.rlog.bz2).
3. Hack the test to insert testdata (a/ Copy the routelog to /tmp/, b/ add to test_car_models.py , c/ run the test). Show that it fails. <- This step PASSES for me, so I'm unsure change will do anything. Please see my attempt here: https://github.com/pviolette3/openpilot/commit/2a1367fa6137ba9fbc637c209f85212e18159fa2

### Part 3: Compare carParams for both working & not-working case.
1. Set up ssh.comma.ai (a/ upload github ssh keys, b/ add my user name in the Comma 2 UI as the user for SSH)
2. Find dongle ID (can find with my.comma.ai , or api.commadotai.com) (mine is: 5d02a73998def520)
3. a/ ensure comma2 is on (e.g. by turning on the car) b/ Run command suggested in ssh.comma.ai: `ssh -i ~/.ssh/id_rsa -o ProxyCommand="ssh -i ~/.ssh/id_rsa -W %h:%p -p %p %h@ssh.comma.ai" 5d02a73998def520`
4. Once ssh is working, dump the car params. `PYTHONPATH=/data/openpilot python /data/openpilot/selfdrive/debug/dump.py carParams` (it takes 1 min).
-> For my case, save the output when it's recognized (https://pastebin.com/V8mZwGcv) and unrecognized (https://pastebin.com/ZYQQzf8L)
-> Inspect the diff, to try to find the correct value.


What I did NOT need to do: Did not need to follow ["Comma EON: Getting Connected With SSH"](https://medium.com/@jfrux/comma-eon-getting-connected-with-ssh-3ed6136e4a75), (No need to connect via Wifi, find the device IP address (such as with an IP scanner, or www.routerlogin.net))

**Comment by pviolette3** [comment]
Some more links:
1. Dongle ID: 5d02a73998def520
2. Route ID: 5d02a73998def520|2020-04-28--21-26-18--0
3. my.comma.ai link: https://my.comma.ai/5d02a73998def520/1588134378279/1588135263997
4. [Canban link](https://my.comma.ai/cabana/?route=5d02a73998def520%7C2020-04-28--21-26-34&exp=1620095035&sig=hlNLiHP5AsdfG5hg9Bk3WqL876wN1Zk0BgcvE6HNQAU%3D&max=0&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F5d02a73998def520%2F4ced236db760d44fa25f3422b41b9393_2020-04-28--21-26-34)

**Comment by pviolette3** [comment]
Here is another example from last night (1st restart failed to recognize the car, 2nd restart successfully recognized the car). Note first segment did fail, and all subsequent segments did pass
1. Dongle ID: 5d02a73998def520
2. Route ID: 5d02a73998def520|2020-05-03--22-31-12--0
3. my.comma.ai link: https://my.comma.ai/5d02a73998def520/1588570271494/1588571087887#
4. [Canban link](https://my.comma.ai/cabana/?route=5d02a73998def520%7C2020-05-03--22-31-12&exp=1620144092&sig=2ZZqWjEBQGw1PkubPkUmTFP3jSmElphHBMIywFYny%2B8%3D&max=0&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F5d02a73998def520%2F9f8512583abd7f3a19e6ee62b8a26f91_2020-05-03--22-31-12)

In the course of debugging, please feel free to find any of my drives' segments that are at the beginning of the drive, and have duration less than the expected 1m chunk. All of these will be examples of the "turn it off and turn it back on again" workaround.

Thanks for bearing with me; I'm being extra verbose because I have no idea what this code is doing :) I really appreciate the work from the Comma team!

**Comment by pd0wm** [comment]
Looking at the data I see two mismatches. Can you also add: `b'37805-5AN-LF20\x00\x00'` to `Ecu.programmedFuelInjection`. It shouldn't match for fingerprinting, but let's add if for completeness.

**Comment by pviolette3** [comment]
Good eye. Thank you. I have added the missing value for `Ecu.programmedFuelInjection`; ready for another look.

**Review by pd0wm — APPROVED** [review]

**Comment by pviolette3** [comment]
Good morning, Willem - I have confirmed this commit fixes my issue anecdotally, by cherry-picking this change onto 0.7.4 (see: https://github.com/pviolette3/openpilot/tree/release2), following instructions [here](https://medium.com/@jfrux/installing-a-fork-of-openpilot-with-workbench-de35e9388021).

After installing the CP'ed release, Open Pilot now recognizes my 2019 Honda Civic Hatchback on the first start (e.g. 5d02a73998def520|2020-05-06--09-35-51--0, [CANBAN](https://my.comma.ai/cabana/?route=5d02a73998def520%7C2020-05-06--09-35-51&exp=1620320190&sig=igwldYZ2BIPIM1V4kLaEwdoZxJgs8jV6Kwd4kpBKc8Y%3D&max=7&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F5d02a73998def520%2Fcefa2ed1ee4a73f0a15a5165218db912_2020-05-06--09-35-51)). Thanks for all the help! I will continue to let this bake on my vehicle, and report any issues (if any) here.

What is the process for upstreaming the change?

**Pull request merged**
