### PR TITLE
Add RAV4_TSS2 and RAV4H_TSS2 to Improved long tune

### PR DESCRIPTION
**Pull request by briskspirit**
Add RAV4_TSS2 and RAV4H_TSS2 to Improved long tune

P.S. those who tried my long tune on non-TSS2 cars - please DM me your experience on Discord.

### CODE REVIEW

**Comment by pd0wm** [comment]
People with good experience please also comment on the PR.

**Comment by C0mpl3t3N00b** [comment]
I hope it's not too late, but @briskspirit longitudinal tune is very good, and I would use it.

**Comment by pd0wm** [comment]
@C0mpl3t3N00b Are you driving a Rav4/Rav4 hybrid with TSS2?

**Comment by grekiki** [comment]
Looks like it https://github.com/commaai/openpilot/issues/20054

**Comment by C0mpl3t3N00b** [comment]
> @C0mpl3t3N00b Are you driving a Rav4/Rav4 hybrid with TSS2?

I guess I need to increase the amount of issues I post, but yes 2020 Rav4 Hybrid. :)

**Pull request merged**
