### PR TITLE
Kia: Optima Hybrid 2019 car port

### LINKED ISSUE #29911: Is support available for “Kia Optima Hybrid 2019”?
### Describe the bug

Is support available for “Kia Optima Hybrid 2019”?
At comma 3x, the vehicle is not recognized and starts in dashcam mode.
So I tried extracting my car's fingerprint and firmware information and adding them to value.py, but it still goes into dashcam mode.
I am sharing the fingerprint and firmware information I extracted for reference, and if you have any information you need, please let me know.

### Which car does this affect?

Kia Optima Hybrid 2019

### Provide a route where the issue occurs

6a42c1197b2a8179|2023-09-14--12-12-02

### openpilot version

0.9.5

### Additional info

- Fingerprint information
68: 8, 127: 8, 304: 8, 320: 8, 339: 8, 352: 8, 356: 4, 544: 8, 546: 8, 548: 8, 549: 8, 576: 8, 593: 8, 688: 5, 832: 8, 881: 8, 882: 8, 897: 8, 902: 8, 903: 8, 909: 8, 916: 8, 1040: 8, 1056: 8, 1057: 8, 1078: 4, 1136: 6, 1151: 6, 1157: 4, 1168: 7, 1173: 8, 1180: 8, 1186: 2, 1191: 2, 1236: 2, 1265: 4, 1280: 1, 1287: 4, 1290: 8, 1291: 8, 1292: 8, 1294: 8, 1322: 8, 1342: 6, 1345: 8, 1348: 8, 1355: 8, 1363: 8, 1369: 8, 1371: 8, 1397: 8, 1407: 8, 1419: 8, 1427: 6, 1429: 8, 1430: 8, 1448: 8, 1456: 4, 1470: 8, 1476: 8, 1535: 8, 2000: 8, 2004: 8, 2005: 8, 2008: 8, 2012: 8, 2013: 8

- Vehicle firmware information
                'carFw': [{'address': 2000,
                           'brand': 'hyundai',
                           'bus': 1,
                           'ecu': 'fwdRadar',
                           'fwVersion': b'\xf1\x00JFhe SCC FHCUP 1.00 1.01 99110-A8500 ',
                           'logging': False,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x00'],
                           'responseAddress': 2008,
                           'subAddress': 0},
                          {'address': 1988,
                           'brand': 'hyundai',
                           'bus': 1,
                           'ecu': 'fwdCamera',
                           'fwVersion': b'\xf1\x00JFH MFC AT KOR LHD 1.00 1.01 95895-A8200 180323',
                           'logging': False,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x00'],
                           'responseAddress': 1996;
                           'subAddress': 0},
                          {'address': 2016,
                           'brand': 'hyundai',
                           'bus': 1,
                           'ecu': 'engine',
                           'fwVersion': b'\xf1\x816H6D1051\x00\x00\x00\x00\x00\x00\x00\x00',
                           'logging': False,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                           'responseAddress': 2024;
                           'subAddress': 0},
                          {'address': 2000,
                           'brand': 'hyundai',
                           'bus': 1,
                           'ecu': 'fwdRadar',
                           'fwVersion': b'\xf1\x00JFhe SCC FHCUP 1.00 1.01 99110-A8500 ',
                           'logging': False,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                           'responseAddress': 2008,
                           'subAddress': 0},
                          {'address': 1975,
                           'brand': 'hyundai',
                           'bus': 0,
                           'ecu': 'cornerRadar',
                           'fwVersion': b'\xf1\x00\xff\x00',
                           'logging': True,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x00'],
                           'responseAddress': 1983,
                           'subAddress': 0},
                          {'address': 2000,
                           'brand': 'hyundai',
                           'bus': 0,
                           'ecu': 'fwdRadar',
                           'fwVersion': b'\xf1\x00JFhe SCC FHCUP 1.00 1.01 99110-A8500 ',
                           'logging': False,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x00'],
                           'responseAddress': 2008,
                           'subAddress': 0},
                          {'address': 1988,
                           'brand': 'hyundai',
                           'bus': 0,
                           'ecu': 'fwdCamera',
                           'fwVersion': b'\xf1\x00JFH MFC AT KOR LHD 1.00 1.01 95895-A8200 180323',
                           'logging': False,
                           'obdMultiplexing': True,
                           'request': [b'"\xf1\x00'],
                           'responseAddress': 1996;
                           'subAddress': 0},

### PR DESCRIPTION
**Pull request by sshane**
Closes https://github.com/commaai/openpilot/issues/29911

Needs to be split from the 2017-18 because those have a different SCC checksum that doesn't work even behind legacy mode: https://github.com/commaai/openpilot/pull/29520. The hybrids also match the non-hybrids perfectly with missing "lane keeping" language from the 2017-18 brochures

### CODE REVIEW

**Comment by sshane** [comment]
@rockimjh can you get a new route on this branch, preferably 10 minutes and starting and ending in a public area? Then upload full logs and post the route here so we can get you merged!

**Comment by rockimjh** [comment]
As requested, I am posting my driving record from September 16th using the new branch. Please let me know if you need a more recent driving record and if there is anything else I need to do.

6a42c1197b2a8179|2023-09-16--18-59-44

**Comment by sshane** [comment]
We need all the rlogs uploaded, do you have a more recent route?

**Comment by rockimjh** [comment]
All right. I will drive again within the next 6 hours and post a log.

**Comment by rockimjh** [comment]
I just drove the car for over 10 minutes and am posting the results, including rlog. If there is anything else you need, please let me know.

results: 6a42c1197b2a8179|2023-09-21--10-23-44

**Comment by sshane** [comment]
Thanks!

**Pull request merged**
