### PR TITLE
Add skoda octavia 2016 fingerprint

### PR DESCRIPTION
**Pull request by fleetingbytes**
Add firmware for the 2016 Skoda Octavia Mk3 (and sort values). Add 2016 as year for Octavia in CARS.md.

Dongle ID: 44379c05b64fd7e3

Thanks to the VW community on Discord for support

### CODE REVIEW

**Comment by incognitojam** [comment]
What country is this Octavia from?

@jyoung8607 This car was built in late 2016.. would expanding the model year in the docs to 2016 cause confusion for the US market?

From erWin:
|Basic data||
|-|-|
|Make | C 
|VIN | TMBJJ9NE9H0126251 
|Year of manufacture | 2017 
|Description | OCT.COM AMB TD110/2.0A6F 
|Sales type |5E538C 
|Delivery date |12 Dec 2016  
|Production date|22 Nov 2016  
|MKB|CRMB 
|GKB|SGG

**Comment by fleetingbytes** [comment]
> EDIT
> 
> never mind, didn't realise we have 2015 in the docs already

Ok, is the label "awaiting info" still relevant now?

**Comment by fleetingbytes** [comment]
> EDIT
> 
> never mind, didn't realise we have 2015 in the docs already

Ok, is the label "awaiting info" still relevant now?

**Comment by jyoung8607** [comment]
We should be able to extend to the [full Mk3 model-year range](https://en.wikipedia.org/wiki/%C5%A0koda_Octavia#Third_generation_(Typ_5E;_2012)), 2013-2019. We've done that for most other MQB but there's some overseas models I hadn't done yet.

No issues with USA market confusion as it doesn't exist in the USA market. We don't have any Škoda or SEAT, nor do we have several of the listed VW models. Off the top of my head, the only ones we have to be careful with are Golf and Passat.

**Comment by fleetingbytes** [comment]
> What country is this Octavia from?

I bought it new, in Germany. Produced in Mlada Boleslav, Czechia.

**Comment by incognitojam** [comment]
thanks for the PR!

**Pull request merged**
