### PR TITLE
Mazda: CX5 2021 FW

### PR DESCRIPTION
**Pull request by Jafaral**
dongle-id: 82c6d952da5e2122

### CODE REVIEW

**Comment by sshane** [comment]
It looks like routes from this dongle are missing the esp FW, causing it to always fuzzy match. Have any idea why it's not getting the esp?

**Comment by Jafaral** [comment]
That is weird. This car is in Taiwan,  and the fw sent to me had 

```
ecu = esp
fwVersion = KBJ5-437K2-B\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
address = 1888
subAddress = 0
```

which we already have.

**Comment by sshane** [comment]
Hmm, it seems pretty inconsistent. This route has esp: 82c6d952da5e2122|2022-07-30--20-15-01, but the rest after that do not: `82c6d952da5e2122|2022-08-06--14-38-49` for example

**Comment by Jafaral** [comment]
I will let them know. I also don't have access to the routes so can't really tell.

**Comment by chaly77714** [comment]
@sshane 
Hi, I'm the requester for the CX5 2021 fingerprint.
I turned on my wifi for long time, can you see the logs from my device?

**Comment by sshane** [comment]
@chaly77714 can you get a route on master? We added some new logging and would like to see if I can find the issue with your ABS ECU not responding

**Comment by chaly77714** [comment]
> @chaly77714 can you get a route on master? Make sure not to skip FW query. We added some new logging and would like to see if I can find the issue with your ABS ECU not responding

**Comment by chaly77714** [comment]
> @chaly77714 can you get a route on master? Make sure not to skip FW query. We added some new logging and would like to see if I can find the issue with your ABS ECU not responding

Do you mean using the official Openpilot in master branch? because I use dragonpilot  currently.

**Comment by sshane** [comment]
Yes

**Comment by sshane** [comment]
Let me know when you get a route on master @chaly77714

**Comment by adeebshihadeh** [comment]
Any update on this?

**Comment by chaly77714** [comment]
> Any update on this?

Sorry for late reply. I just install master branch and connect to router.
But I don't change anything, so it run on dashmode.

**Comment by sshane** [comment]
Thanks! It appears your abs is responding without any errors the last two attempts on master. I'll go ahead a merge. Please let us know if your car ever fails to fingerprint!

**Pull request merged**
