### PR TITLE
Hyundai: common CAN-FD brake pressed signal

### PR DESCRIPTION
**Pull request by adeebshihadeh**
Prep for supporting ICE CAN-FD cars in #25434, seems similar to TCS13 / DriverBraking from the reference DBC for the CAN Hyundai platform

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Matched the old signal exactly (visually) on the couple EV6 routes I checked. @sshane can you check this with your notebook on all the supported cars and a few ICE routes from that PR?

**Comment by sshane** [comment]
Looks like a good change:

```python
Platform:        KIA EV6 2022
Total:           6 unique dongles, 150 unique routes
Checked:         6 unique dongles, 85 unique routes, and 150 segments
Mismatches:      310 frames total, 39 segments (any frame)
Mismatches > 10: 28 frames total, 2 segments (any frame)
Segments with brake pressed:   46 segments (above 2 seconds of brake)
Segments with mismatches > 10: {'b186d6fbc83b99a8|2022-09-27--12-54-20--0', 'b186d6fbc83b99a8|2022-09-23--10-29-51--5'}
---
Platform:        HYUNDAI TUCSON HYBRID 4TH GEN
Total:           1 unique dongles, 8 unique routes
Checked:         1 unique dongles, 1 unique routes, and 8 segments
Mismatches:      6 frames total, 2 segments (any frame)
Mismatches > 10: 0 frames total, 0 segments (any frame)
Segments with brake pressed:   3 segments (above 2 seconds of brake)
Segments with mismatches > 10: set()
---
Platform:        HYUNDAI IONIQ 5 2022
Total:           4 unique dongles, 164 unique routes
Checked:         4 unique dongles, 83 unique routes, and 162 segments
Mismatches:      106 frames total, 28 segments (any frame)
Mismatches > 10: 0 frames total, 0 segments (any frame)
Segments with brake pressed:   42 segments (above 2 seconds of brake)
Segments with mismatches > 10: set()
```

I sampled the mismatches on update of the TCS message (since it's lower frequency), however the two segments with high mismatches had a lot of brake pressed events, so this is expected: https://imgur.com/a/DkCe9dP

**Comment by sshane** [comment]
This also looks good on the ICE cars, except the GV70 which doesn't set the bit: 
Screenshot from 2022-10-20 00-52-53

**Comment by sshane** [comment]
Looks like BRAKE_RELATED on the ICE cars is good to use: https://imgur.com/a/HpnaOy2

The brake pressure signal in ESP_STATUS is oddly more noisy at the bottom end than our EV6, where it goes to 1 on occasion without BRAKE_RELATED rising (whereas on our EV6, if the pressure signal went to 1, BRAKE_RELATED would definitely rise). Each car must do their own filtering on the brake pressure signal in ESP_STATUS, which is good for us, as we can just use BRAKE_RELATED (which cancels cruise on the EV6).

**Comment by sshane** [comment]
This is the Kia Sportage cancelling on BRAKE_RELATED/DriverBraking (again, brake pressure threshold is above 1 vs. our EV6 which is 1): https://user-images.githubusercontent.com/25857203/197062825-a41cf508-71fc-4ae6-9719-dcd8a0746281.png

**Comment by sshane** [comment]
Checked to make sure that `TCS->BRAKE_RELATED` always at least captures what the previous signal did (`BRAKE->BRAKE_PRESSED`:

```python
Platform:        HYUNDAI IONIQ 5 2022
Total:           4 unique dongles, 164 unique routes
Checked:         3 unique dongles, 40 unique routes, and 47 segments
Mismatches:      0 frames total, 0 segments (any frame)
Mismatches > 10: 0 frames total, 0 segments (any frame)
Segments with brake pressed:   42 segments (above 2 seconds of brake)
Segments with mismatches > 10: set()
---
Platform:        KIA EV6 2022
Total:           6 unique dongles, 150 unique routes
Checked:         4 unique dongles, 35 unique routes, and 54 segments
Mismatches:      0 frames total, 0 segments (any frame)
Mismatches > 10: 0 frames total, 0 segments (any frame)
Segments with brake pressed:   46 segments (above 2 seconds of brake)
Segments with mismatches > 10: set()
---
Platform:        HYUNDAI TUCSON HYBRID 4TH GEN
Total:           1 unique dongles, 8 unique routes
Checked:         1 unique dongles, 1 unique routes, and 3 segments
Mismatches:      2 frames total, 1 segments (any frame)
Mismatches > 10: 0 frames total, 0 segments (any frame)
Segments with brake pressed:   3 segments (above 2 seconds of brake)
Segments with mismatches > 10: set()
```

**Comment by sshane** [comment]
Final plots with high mismatches.

I was wrong about the `BRAKE_PRESSURE` != 0 condition (it's actually `BRAKE_POSITION`, but it often lines up with `BRAKE_PRESSURE` going non-zero), but nonetheless, this `TCS->BRAKE_RELATED` signal is just a more sensitive `BRAKE->BRAKE_PRESSED` for the EVs, and it's what the stock ACC uses to cancel and enable at a stop.

EV6: https://imgur.com/a/ZHZGBXM
IONIQ 5: https://imgur.com/a/cJdoKeB
Tucscon Hybrid (no mismatches, behaves similarly to ICE cars): https://imgur.com/a/xEcIkRq

**Pull request merged**
