### PR TITLE
onroad/alerts: replace magic numbers with named constants

### PR DESCRIPTION
**Pull request by deanlee**
The `alert_heights` map was also removed because it didn't adapt to changes in window height, causing resizing issues. It was also non-constant, which was not ideal.

### CODE REVIEW

**Review by adeebshihadeh — COMMENTED** [review]
Can you add one of each alert to the UI report?

We'll be touching this code a lot more soon, and it would be nice if the UI report showed the changes.

**Comment by deanlee** [comment]
https://github.com/commaai/openpilot/pull/33394

done, but not sure why the ui report is still displaying the old information.

**Comment by maxime-desroches** [comment]
@deanlee Yes, the `ui_preview.yaml` workflow is always taken from master since it has access to some Github Secrets.
The best way to test your new ui preview is to merge the new `ui_preview.yaml` in the master branch of your fork and then to do a PR againt the master branch of your fork.

**Comment by adeebshihadeh** [comment]
I don't actually think this is better. The locality of all these numbers makes the `paintEvent` readable. If anything's duplicated, let's pull it into a constant, but otherwise I think this is fine.

**Pull request closed without merging**
