### PR TITLE
Corolla 2019 GX New Zealand Update values.py

### PR DESCRIPTION
**Pull request by ajith339**
Added Missing FW

### CODE REVIEW

**Comment by sshane** [comment]
Can you provide the dongle id this came from? Does your vehicle support full stop and go?

**Comment by ajith339** [comment]
> Can you provide the dongle id this came from? Does your vehicle support full stop and go?

dongle id: c4feb7e2d79eda5b
Yes, my car supports full stop and go.
Thanks and Regards
Ajith

**Comment by sshane** [comment]
Thanks for the PR!

**Comment by ajith339** [comment]
> Thanks for the PR!

Thanks for your quick action and support for merging to master !!

**Pull request merged**
