### PR TITLE
VW: OBD-less fingerprinting

### PR DESCRIPTION
**Pull request by sshane**
While combining the platforms that were too similar without the eps and srs ECUs, I realized that we could possibly satisfy keeping accurate car specs while simultaneously investing in make-specific feature detection, and avoiding maintaining another fingerprinting stack which might not be around forever (FW, CAN, VIN).

We can then switch the source for the specs as we learn to detect them via UDS queries or listening to CAN data very easily. The mass for example is broadcast on CAN according to @jyoung8607. How do you feel about this? We still need to combine platforms.

- [ ] Ateca and Leon chassis code is the same. Ateca is at 1900 kg, is that right?

### CODE REVIEW

**Comment by sshane** [comment]
We're missing some chassis codes:

```python
NEW CHASSIS CODE
('4e144f64a2535890', 'VOLKSWAGEN_TIGUAN_MK2', 'Tiguan 4Motion', '3VV4B7AX0LM175500', 'AX')

NEW CHASSIS CODE
('753c8af46b4de2de', 'VOLKSWAGEN_TIGUAN_MK2', 'unknown', 'WVGZZZ5N1PW504596', '5N')

NEW CHASSIS CODE
('5405cac0c9d58c3d', 'VOLKSWAGEN_PASSAT_MK8', 'unknown', 'WVWZZZ3CZGE100626', '3C')

NEW CHASSIS CODE
('0662797832aac2eb', 'VOLKSWAGEN_ARTEON_MK1', 'unknown', 'WVWZZZ3HZJE518146', '3H')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('23daff6c438612d2', 'AUDI_A3_MK3', 'Golf SportWagen', '3VWCA7AU3FM515369', 'AU')

NEW CHASSIS CODE
('f785057bee19059b', 'SKODA_SUPERB_MK3', 'unknown', '00000000000000000', '00')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('1a944f1463d214d5', 'VOLKSWAGEN_TIGUAN_MK2', 'Golf R', 'WVWVF7AU4JW278008', 'AU')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('dafb0cb9e28e0249', 'SKODA_KODIAQ_MK1', 'unknown', 'WVWZZZAWZKU019808', 'AW')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('0bbe367c98fa1538', 'SKODA_KODIAQ_MK1', 'unknown', '00000000000000000', '00')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('1a944f1463d214d5', 'VOLKSWAGEN_TIGUAN_MK2', 'unknown', '00000000000000000', '00')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('5405cac0c9d58c3d', 'VOLKSWAGEN_PASSAT_MK8', 'unknown', '00000000000000000', '00')

NEW CHASSIS CODE
('8c05142673569f44', 'VOLKSWAGEN_TOURAN_MK2', 'unknown', 'LSV6K80R4MN010392', '0R')

NEW CHASSIS CODE
CHASSIS CODE IN ANOTHER PLATFORM
('0bbe367c98fa1538', 'SKODA_KODIAQ_MK1', 'unknown', 'WVGZZZ5NZJM103723', '5N')

NEW CHASSIS CODE
('0bbe367c98fa1538', 'SKODA_KODIAQ_MK1', 'unknown', 'WAUZZZGB6RR010627', 'GB')
```

**Comment by jyoung8607** [comment]
Per our Discord conversation, some suggestions for CAR combinations.

These probably should have been merged all along, as they share a chassis code:
* SEAT Leon and SEAT Ateca share chassis code 5F
* Skoda Scala and Kamiq share chassis code NW

These *may* perform similarly enough to merge but I would want to see up-to-date lateral accel factor data:
* Volkswagen Golf and Audi A3
* Volkswagen Atlas and Skoda Kodiaq
* Volkswagen Passat and Skoda Superb
* Volkswagen Jetta and Skoda Octavia
* Volkswagen Tiguan and Audi Q3
* (very maybe) Volkswagen Taos, Volkswagen T-Roc, Audi Q2
* (very maybe) All the MQB-A0s: Polo, T-Cross, Fabia, Scala/Kamiq

**Comment by sshane** [comment]
Superseded by https://github.com/commaai/openpilot/pull/32148

**Comment by sshane** [comment]
As context, with only the radar FW, we'd need to combine all platforms into one. Camera may provide a couple arbitrary support groups, not worth it. Superseded by fingerprinting with the VIN: https://github.com/commaai/openpilot/pull/32148

**Pull request closed without merging**
