### PR TITLE
adding pr format check bot

### PR DESCRIPTION
**Pull request by LoganxDev**
### Template: Refactor
PR template check bot

**Description**
Probably need to add a new template for added features or something like that, or CI enhancements. This adds the new PR format review bot.

**Verification**
Testing it on this PR.

### CODE REVIEW

**Comment by LoganxDev** [comment]
for #30715

**Comment by LoganxDev** [comment]
Hi @adeebshihadeh do workflows have write permissions under Actions > General > Workflow permissions?

**Comment by jnewb1** [comment]
> Hi @adeebshihadeh do workflows have write permissions under Actions > General > Workflow permissions? Looks like that will be needed for adding labels in workflow.

You should test this on your fork (setting up proper permissions, etc), and create a PR once it works

**Comment by LoganxDev** [comment]
Sounds good, will do

**Pull request closed without merging**
