### PR TITLE
remove devcontainer

### PR DESCRIPTION
**Pull request by andiradulescu**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
I'm supportive, but let's poll the Discord before doing this

**Comment by maxime-desroches** [comment]
I asked on Discord last month, no one manifested any interest in keeping it.

**Comment by epchris** [comment]
I would love to see this remain in the repo, I've relied heavily on it, even if my work is sporadic.

**Comment by andiradulescu** [comment]
Let's see if we can make this good, so people on other distros can use it without bugs.

But still excluding using it on macOS - unless magically this also gets fixed.

**Pull request closed without merging**
