### PR TITLE
cameraview: fix frameskip

### PR DESCRIPTION
**Pull request by deanlee**
use repaint to fix the frameskip when there are too many events in the queue (e.g.  watch3)

### CODE REVIEW

**Comment by pd0wm** [comment]
Doesn't it make more sense to skip frames so we can keep up realtime?

**Comment by adeebshihadeh** [comment]
What events are dominating the queue? Perhaps we're spamming the queue with nonsense timer events or something else?

**Comment by deanlee** [comment]
We can easily implement an OffroadTimer like this if  use singleton uistate  https://github.com/commaai/openpilot/pull/22789

```
OffroadTimer(QObject *parent) : QTimer(parent) {
  QObject::connect(uiState(), &UIState::offroadTransition, [=](bool offroad) {
    offroad ? start() : stop();
  });
}
```

**Comment by deanlee** [comment]
> What events are dominating the queue? Perhaps we're spamming the queue with nonsense timer events or something else?

At present, this drawing problem is only in wath3,  it is mainly caused by a large number of  update events from the three cameras.

**Comment by deanlee** [comment]
Think we don't need this hack if use YUV vipc stream.

**Comment by pd0wm** [comment]
Can we ensure the texture is not being modified while Qt is actually drawing the ui? Even with YUV that might still be an issue, right?

**Comment by deanlee** [comment]
Fixed, the uploaded and render have been synchronized.

**Comment by deanlee** [comment]
> Can we ensure the texture is not being modified while Qt is actually drawing the ui? Even with YUV that might still be an issue, right?

YUV https://github.com/commaai/openpilot/pull/22905 does not has this issue,  the performance looks good enough , so I did not do asynchronous upload for it

**Pull request merged**
