### PR TITLE
Add comment about vEgoStarting to interfaces

### PR DESCRIPTION
**Pull request by sshane**
Do we want an assert after `CarInterface.get_params()` in car_helpers.py too or is this good?

### CODE REVIEW

**Comment by jyoung8607** [comment]
> Do we want an assert after `CarInterface.get_params()` in car_helpers.py too or is this good?

For so long as those conditions interact the way they do, I think an assert would be a good idea. I tripped over the oscillation condition while working on #22963. It shouldn't be permitted to happen and it's not obvious what's happening when it does.

**Comment by sshane** [comment]
Yeah it can be confusing, but when `vEgoStarting` is less than stopping, it's possible for both the starting condition and stopping condition to be true in longcontrol.py, so it oscillates between them both.

For example if `v_target_future = 0.75`, then `v_target_future < (CP.vEgoStopping := 1.0)` for stopping and `v_target_future > (CP.vEgoStarting := 0.5)` for starting are both true for this future target speed (logic in `long_control_state_trans` function`).

**Comment by pd0wm** [comment]
Can we fix the state machine so this oscillation doesn't happen?

**Comment by sshane** [comment]
I believe it would still oscillate, just between stopping and PID, rather than starting. I'll try testing a fix in #23333

**Comment by pd0wm** [comment]
Merging this now. Once we fix the oscillation we should remove the comment again.

**Comment by sshane** [comment]
Sounds good!

**Pull request merged**
