### PR TITLE
Update Chrysler Pacifica fingerprint values

### PR DESCRIPTION
**Pull request by adhintz**
add a few more values based on work by @arne182
Combine fingerprints for Pacifica 2019 Hybrid.

### CODE REVIEW

**Comment by rbiasini** [comment]
@adhintz are there cars with those fingerprints or they are just a superset (union) of different models?

**Comment by adhintz** [comment]
@rbiasini They're from Arne's message reporting of people running his fork.

We had a new person today that was unable to get the main repo to work for their 2019 Pacifica Hybrid, but Arne's fork worked fine. Unsure if it's due to a fingerprint issue or a Panda issue, but figured I'd add in the values from his fork that the main repo does not have.

**Comment by rbiasini** [comment]
mmm... I see. The best solution would be to add a new fingerprint for this new car. Is there a cabana drive?
The problem with expanding existing fingerprints is that at certain point we won't be able to distinguish new car models because their fingerprints risk to be included in the existing giant fingerprints we are making.
At that point, trying to correct the issue would be very hard.

On the other hand, I understand this is a simple way to fix fingeprinting issues. Let's keep this pr open.

**Comment by mwilliams** [comment]
@rbiasini I'm the user in question Re: this fingerprint.  Here's a gist of a small snapshot from the fingerprint dump from my vehicle.

https://gist.github.com/mwilliams/bd12e3e589c86cb83096e0116d73724b

That said - once added, I was up and running with ease, so seeing it upstream in some capacity would be nice.  Thank you @adhintz for beating me here!

**Comment by rbiasini** [comment]
@mwilliams , great, we'll upstream it. To confirm, you have a '19 pacifica hybrid, correct? Could you please PM your dongle ID on Discord? Or post it here. Thanks.

**Comment by mwilliams** [comment]
@rbiasini What's your handle on the Discord?

**Comment by rbiasini** [comment]
@mwilliams ,. Riccardo

**Comment by mwilliams** [comment]
@rbiasini Still not seeing you on Discord, the ID however is `3c7ce223e3571b54`.

And correct, it's a 2019 Pacifica Hybrid (Plug-in).

**Comment by rbiasini** [comment]
@mwilliams , looking at your routes I'm actually getting the following:
```
168: 8, 257: 5, 258: 8, 264: 8, 268: 8, 270: 8, 274: 2, 280: 8, 284: 8, 288: 7, 290: 6, 291: 8, 292: 8, 294: 8, 300: 8, 308: 8, 320: 8, 324: 8, 331: 8, 332: 8, 344: 8, 368: 8, 376: 3, 384: 8, 388: 4, 448: 6, 456: 4, 464: 8, 469: 8, 480: 8, 500: 8, 501: 8, 512: 8, 514: 8, 520: 8, 528: 8, 532: 8, 544: 8, 557: 8, 559: 8, 560: 8, 564: 8, 571: 3, 579: 8, 584: 8, 608: 8, 624: 8, 625: 8, 632: 8, 639: 8, 653: 8, 654: 8, 655: 8, 658: 6, 660: 8, 669: 3, 671: 8, 672: 8, 678: 8, 680: 8, 701: 8, 703: 8, 704: 8, 705: 8, 706: 8, 709: 8, 710: 8, 719: 8, 720: 6, 729: 5, 736: 8, 737: 8, 746: 5, 752: 2, 754: 8, 760: 8, 764: 8, 766: 8, 770: 8, 773: 8, 779: 8, 782: 8, 784: 8, 792: 8, 799: 8, 800: 8, 804: 8, 808: 8, 816: 8, 817: 8, 820: 8, 825: 2, 826: 8, 832: 8, 838: 2, 848: 8, 853: 8, 856: 4, 860: 6, 863: 8, 878: 8, 882: 8, 897: 8, 906: 8, 908: 8, 924: 8, 926: 3, 929: 8, 937: 8, 938: 8, 939: 8, 940: 8, 941: 8, 942: 8, 943: 8, 947: 8, 948: 8, 958: 8, 959: 8, 962: 8, 969: 4, 973: 8, 974: 5, 979: 8, 980: 8, 981: 8, 982: 8, 983: 8, 984: 8, 992: 8, 993: 7, 995: 8, 996: 8, 1000: 8, 1001: 8, 1002: 8, 1003: 8, 1008: 8, 1009: 8, 1010: 8, 1011: 8, 1012: 8, 1013: 8, 1014: 8, 1015: 8, 1024: 8, 1025: 8, 1026: 8, 1031: 8, 1033: 8, 1050: 8, 1059: 8, 1082: 8, 1083: 8, 1098: 8, 1100: 8, 1562: 8, 1570: 8
```

Not sure how you obtained the one you posted

**Comment by mwilliams** [comment]
@rbiasini Hmmm I followed [https://community.comma.ai/wiki/index.php/Creating_Fingerprints](https://community.comma.ai/wiki/index.php/Creating_Fingerprints) to collect it.  And my `values.py` entry below is straight from my EON right now, I pulled out the other fingerprints and this is what's there now and is what seemingly got my OP install working vs faulting every attempt.

image

**Comment by arne182** [comment]
@rbiasini looks like those values come from my fork. The cumulative effort to merge all values from all cars using my fork to reduce Sentry unsupported car faults to 0.

**Comment by mwilliams** [comment]
@rbiasini Any direction you'd prefer to see this PR go to get it merged upstream?  Would like to get support for my vehicle in master to prevent any unnecessary hackery every time there's a release (and the Pacifica Hybrid is on the supported vehicle list).

Happy to do cleanup wherever necessary if that helps it move.  First introduction to the codebase, pardon any oversight if I'm missing any preferred PR guidelines etc etc.

**Comment by rbiasini** [comment]
went over these changes again:
* 2018 Pacifica change: it has been merged internally. It will be in next release.
* 2018 Pacifica Hybrid change: the extended fingerprint is already in master.
* 2019 Pacifica Hybrid change: rejected. @mwilliams , I've looked again at some of your recent drives and the fingerprint in master should solve for your car. Doesn't it?

thanks!

**Comment by mwilliams** [comment]
@rbiasini My '19 Pacifica Hybrid has been in the shop for 87 days awaiting a new battery pack, I got the vehicle back today and everything ran smoothly on 0.6.1, no fingerprint issues.  Issue resolved and nice to be running stock OP :+1:

**Comment by ErichMoraga** [comment]
87 days in the shop for a battery pack?!
Sell Chrysler > buy Toyota

**Comment by mwilliams** [comment]
Chrysler is buying it back, total 🍋, and I've got 4 kids, so I need a family hauler.  Pacifica plug-in Hybrid was awesome, pretty much drive it as an EV and use gas on weekend trips, but all week long is purely EV mode with in town driving trips and I have a Level 2 charger at home.

**Comment by ErichMoraga** [comment]
Sell kids > buy Prius Prime?

**Pull request closed without merging**
