### PR TITLE
Support for OLD_CAR

### PR DESCRIPTION
**Pull request by Lukilink**

### CODE REVIEW

**Comment by rbiasini** [comment]
@Lukilink , did you intentionally open this PR? If so, can you describe what it does?
Thanks.

**Comment by Lukilink** [comment]
It adds support for old_cars retrofitted with Toyota actuators. Like my VW Vanagon from 88

**Comment by ErichMoraga** [comment]
@Lukilink It seems like you haven't finalized what you want to submit, strange since I know you've had your setup working for several months.  Normally you'll want to figure things out on your own fork first, then once everything is finalized, submit a PR to Comma (even though it's already a strange submission that might get rejected).

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Pull request closed without merging**
