### PR TITLE
Adding 2018 Lexus NX 300  Non Hybrid to supported cars list

### PR DESCRIPTION
**Pull request by matt12eagles**
**Checklist**
- [X] added to README
- [X] test route added to [test_car_models](../../selfdrive/test/test_car_models.py)
- [X] route with openpilot: 964c09eb11ca8089|2020-10-25--15-33-52
- [X] route with stock system: 964c09eb11ca8089|2020-10-25--18-27-54

Co contribtors: Arnie Schwark, Erich, Cfranhonda

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
If you rebase, the opendbc that's in master will have your dbc. Why does your test route report that it's from release2?

**Comment by matt12eagles** [comment]
Hi @adeebshihadeh any specific drivers you are looking for? Can add you to my device as an admin if you like. Version running on my freeon is only slightly different since I had to merge in a few new firmwares that had been put into master post fork. I fear if I re do the videos, it will be out of sync again :( thanks!

**Comment by adeebshihadeh** [comment]
I don't see any routes from your device on this branch, they're all from a fork with many other changes. We need a route that's from this branch to use for the tests.

**Comment by matt12eagles** [comment]
Hi @adeebshihadeh , I have been trying today to get my openpilot up and running... but everytime I pull from my fork I get "an update to NEOS is required" after i update... i go into a bootloop of it constantly trying to update and failing to pull recovery. I have just pulled the latest NEOS I believe (from here using the download.py) https://github.com/commaai/eon-neos.

I pulled via: renaming openpilot folder, doing a git clone on my branch.. and rebooting.

Any advice? Happy to get you new test / example drives when I can get my fork up and running w/o an update prompt and loop.

Thanks,

**Comment by matt12eagles** [comment]
Alright lol this is what I did... clean install and clean fork from openpilot. Updated just two files. (values.py and interface.py) and am now running second -j4 so I can get my DBC file (it didn't come with the latest pull using openpilot.comma.ai).

Will do some more drives tomorrow and upload them :) idk what it will say I'm running (maybe a modified original openpilot?) so I hope that will suffice for a merge so I don't have to worry about my car showing up with unsupported dash can mode randomly lol

**Pull request closed without merging**
