### PR TITLE
Update UI to make text more readable in all conditions as requested by community

### PR DESCRIPTION
**Pull request by pjlao307**

### CODE REVIEW

**Comment by geohot** [comment]
Got a picture of this new ui?

**Comment by pjlao307** [comment]
Here's the current look:

https://i.imgur.com/bhc4unx.jpg

Someone suggesting changing it to this:

https:////i.imgur.com/X1VT9xt.jpg

**Comment by geohot** [comment]
Looking good, we will test and merge with the next release!

**Comment by pjlao307** [comment]
Updated UI some more... added background to lead car text also.

https://i.imgur.com/yyiCQGi.jpg

**Comment by geohot** [comment]
This good to merge? Will test tomorrow if so?

**Comment by pjlao307** [comment]
Yep!

**Pull request merged**
