### PR TITLE
Honda: move common minSteerSpeeds to interface

### PR DESCRIPTION
**Pull request by abesisu**
This change utilizes interface.py for Honda cars better. Common concrete minSteerSpeed values in values.py are moved into the interface.

These changes are part of what @sshane describes in [this comment](https://github.com/commaai/openpilot/issues/24121#issuecomment-1265925494) on #24121

### CODE REVIEW

**Comment by sshane** [comment]
I merged https://github.com/commaai/openpilot/pull/26138 so you can move the speeds into the interface. Can you rebase?

**Comment by abesisu** [comment]
@sshane, @ incognitojam is there anything I should change or add to this PR?

**Comment by adeebshihadeh** [comment]
We added the docs override field since we needed to verify that the minimum steer speeds are real and don't vary within a platform. It was a temporary addition to get the docs building programmatically without changing any behavior in case the information was incorrect. Do you actually know that these are correct and don't vary within a platform?

**Comment by abesisu** [comment]
> We added the docs override field since we needed to verify that the minimum steer speeds are real and don't vary within a platform. It was a temporary addition to get the docs building programmatically without changing any behavior in case the information was incorrect. Do you actually know that these are correct and don't vary within a platform?

The changes in this PR are simply a refactor. None of the values change for the specific cars. Whatever values were there before are still used.

**Pull request closed without merging**
