### PR TITLE
Mazda: use torque controller

### PR DESCRIPTION
**Pull request by adeebshihadeh**
Need to test on CX5 and CX9, rest are dashcam only.

### CODE REVIEW

**Comment by alancyau** [comment]
Here’s a log from a 2022 Mazda CX-5 running this branch. 

a4af1602d8e668ac|2022-07-23--23-17-42--0

**Comment by Jafaral** [comment]
CX-9 2021 : 8c521516df3527d8|2022-07-24--18-57-08

**Comment by adeebshihadeh** [comment]
Both of your plots look pretty good. How does it feel compared to the current tuning on master?

**Comment by Jafaral** [comment]
The drive was smooth overall. I did not test current master to make a direct comparison.

**Comment by alancyau** [comment]
Smooth overall. Pretty similar to master. It seems like lane change might be a bit jerky though.

**Pull request merged**
