### PR TITLE
Kia: add missing fwdCamea FW for Sorento PHEV 4th gen

### PR DESCRIPTION
**Pull request by DriftedPrism**
**Car**
2022 Kia Sorento

**Route**
0b6e3a5ec849ddf7\|2023-11-25--11-55-44

### CODE REVIEW

**Comment by sunnyhaibin** [comment]
We only add `fwdRadar` and `fwdCamera` for all HKG CAN-FD platforms, so the other ECUs should be removed.

**Comment by DriftedPrism** [comment]
@sshane Thanks!

**Comment by sshane** [comment]
Looks like everything is working for you, any issues with openpilot so far?

**Comment by DriftedPrism** [comment]
None so far. Only had a few little tests with it so far, but will be taking a long drive this weekend to really test it out

**Pull request merged**
