### PR TITLE
c++ replay: more robust seek

### PR DESCRIPTION
**Pull request by deanlee**
- [x] more robust seek .
- [x] skip invalid segments
- [x] faster merge events
- [x] test cases
- [x] reduce cpu usage ~20%

### CODE REVIEW

**Comment by pd0wm** [comment]
Does this also handle seeking past the end of the route?

**Comment by deanlee** [comment]
It should be handled, I need to write some test cases int this PR to ensure the stability of seek

**Comment by deanlee** [comment]
should use std::ceil(seconds/60.0) to get the  segment num

**Comment by pd0wm** [comment]
How much faster is the merge by doing things in parallel. I'm worried that depending on `tbb` is going to give us issues when we try to run on device.

**Comment by deanlee** [comment]
not too much, merge 5 segments, from ~9ms-> ~0.5 ms.
Do I need to remove it now?

**Comment by pd0wm** [comment]
Yeah, let's remove it. It's not installed on AGNOS.

**Pull request merged**
