### PR TITLE
add fingerprint for 2017 civic sport touring hatchback

### PR DESCRIPTION
**Pull request by eschmidbauer**

### CODE REVIEW

**Comment by geohot** [comment]
Does this work? I though there was a radar issue.

**Comment by eschmidbauer** [comment]
There is still an issue with the radar but this at least adds the fingerprint so the mph and rear camera work

**Comment by geohot** [comment]
My concern here is that it's sending messages out on the CAN bus that the car isn't listening for. Modify it to disable sending unused messages and we can upstream.

**Comment by energee** [comment]
This code is definitely still sending commands. Would it make sense to officially add read-only support to openpilot?

I have read-only code for some other cars without ACC/LKAS.

**Comment by geohot** [comment]
Yea, read only fingerprinting is good, just disable sends if we can't control the car.

**Comment by geohot** [comment]
If you disable sends when the fingerprint matches the hatchback, I'll merge this in.

**Comment by Raycomma** [comment]
Sorry how  do I disable sends,?

**Comment by geohot** [comment]
Check for fingerprint match in CarController and return early.

**Pull request closed without merging**
