### PR TITLE
boardd:   wait for safety_setter_thread to finish while quitting panda_state_thread

### PR DESCRIPTION
**Pull request by deanlee**
use std::future to wait for `safety_setter_thread` to finish before quitting.

`safety_setter_thread` should not run after `panda_state_thread`,  or the `panda ` could be set to nullptr

### CODE REVIEW

**Comment by pd0wm** [comment]
Any reason the safety setter thread needs to be global like this? Can we make the `panda_state_thread` "own" the thread and join it on disconnect?

**Comment by deanlee** [comment]
> Any reason the safety setter thread needs to be global like this? Can we make the `panda_state_thread` "own" the thread and join it on disconnect?

`std::future<bool> safety_future` is used for this purpose.it's owned by panda_state_thread and will "join" the `safety_setter_thread` in destructor before the `panda_state_thread` return.

**Comment by pd0wm** [comment]
Thanks for rebasing!

**Comment by pd0wm** [comment]
While testing I noticed the thread never finishes if you go offroad before the fingerprinting finishes. The panda state threat then puts you back in noOutput and you're stuck. The safety setter thread should also exit when ignition goes low.

**Comment by pd0wm** [comment]
https://github.com/commaai/openpilot/pull/22426

**Comment by deanlee** [comment]
Just realized this is my 500th PR:)

**Pull request merged**
