### PR TITLE
Mazda CX-5 2024 Fingerprint

### LINKED ISSUE #30872: Mazda 2024 CX5 Dashcam Mode , Car Unrecognized
### Describe the bug

After installing the release branch with all the wiring connected on my 2024 Mazda CX-5 Select, I am getting the issue Dashcam Mode Car Unrecognized.  I have tried uninstalling and trying again with the Master-CI branch but am still running into the same issue.  

### Provide a route where the issue occurs

https://connect.comma.ai/ad9d38124d3a3ef5/1703955559407/1703956202678

### openpilot version

0.9.5

### Additional info

Dongle ID:  ad9d38124d3a3ef5
Serial: f0014f8d

### PR DESCRIPTION
**Pull request by MarcoTheDingo**
Added Discord user aaaa_51443's Fingerprints

**Car**
Mazda CX-5 2024

**Route**
ad9d38124d3a3ef5|2024-01-02--06-14-08

### CODE REVIEW

**Comment by MarcoTheDingo** [comment]
Bump

Anything else needed to merge @sshane ?

**Comment by sshane** [comment]
| Dongle, platform, VIN                                                                                                      | Name from VIN 🆚 CarInfo                 | Segments                  | Bad seg tags                                                                                                                                                                                                                                                                                              | Good seg tags                                                                           |
|:---------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------|:--------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------|
| [ad9d38124d3a3ef5](https://useradmin.comma.ai/?onebox=ad9d38124d3a3ef5)<br><sub>MAZDA CX-5 2022<br>JM3KFBBM8........</sub> | MAZDA CX-5 2024 🆚<br>Mazda CX-5 2022-24 | 108 routes, 3450 segments | - [spotty FW: 896](https://useradmin.comma.ai/?onebox=ad9d38124d3a3ef5%7C2024-03-09--15-08-12)<br>- [missing ECU FW: 105](https://useradmin.comma.ai/?onebox=ad9d38124d3a3ef5%7C2024-03-07--19-16-00)<br>- [car faulted: 144](https://useradmin.comma.ai/?onebox=ad9d38124d3a3ef5%7C2024-02-14--08-42-21) | - valid torque params: 3382<br>- all lat active: 1758<br>- no input all lat active: 988 |

**Comment by sshane** [comment]
Do we know why the user's car is having so many steering faulted segments?

**Comment by sshane** [comment]
Potentially related to https://github.com/commaai/openpilot/issues/23984

**Pull request merged**
