### PR TITLE
Toyota: add test route for 2023 RAV4

### PR DESCRIPTION
**Pull request by sshane**
This route has been stripped with a custom script to remove all personal info, soon to be the default/automatic for test_models to make it easier to add routes.

---

commadataci/commadataci (a private container) was added here but is no longer active/used anywhere as far as I can tell: https://github.com/commaai/openpilot/commit/a25acaae0770a32aa54abd4d41dc0f5ab5077f9a

but was replaced (by accident?) with the public destination account and bucket here, so it doesn't do anything: https://github.com/commaai/openpilot/pull/29411/commits/bc9d0b302d608ae46b8628e515d0bc305ec916c6 in https://github.com/commaai/openpilot/pull/29411

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
`initData` will need to be stripped as well for things like nav destinations. what do we need in there?

**Comment by sshane** [comment]
Only to know if the relay is open in the route, but we can just check the safety mode to know for sure.

**Comment by sshane** [comment]
Found a related bug: https://github.com/commaai/openpilot/issues/30472

**Comment by sshane** [comment]
I think the plan here is to copy the files from the production bucket into the private `commadataci/commadataci` bucket in case we ever need the original full logs, and then a separate step that copies the stripped routes into the public `commadataci/openpilotci` bucket (no cameras for test_models, only stripped rlog). This is just different than how it's set up currently, so will work on this change if this sounds good to you @adeebshihadeh.

**Comment by sshane** [comment]
Moved to https://github.com/commaai/openpilot/pull/30545

**Pull request merged**
