### PR TITLE
Full French UI Localization

### PR DESCRIPTION
**Pull request by Korben00**
Hi,

After a failed attempt, I finally translated the Openpilot UI into French to improve accessibility for French-speaking users. The translation covers all UI elements to ensure a fully localized user experience. I've also incorporated @maxime-desroches and @nworb-cire 's comments and completed the missing translations since then.

### Verification

I've thoroughly tested the translated software by running it in the test scripts and cross-checking all translated texts with their English counterparts. No issues with character encoding or text overflow in the UI were found. Furthermore, I'm a native French-speaking and regular user of openpilot, so I can confirm the appropriateness of the translations. However, to err is human, so you're welcome to correct any mistakes.

### Additional remarks

During my translation and testing, I noticed that some interface elements were not localized, such as the guide, certain messages in the "software" section like "checking," "downloading," "finalizing update," as well as all messages that appear during driving like "Experimental Branch," "Reverse Gear," etc.

K.

### CODE REVIEW

**Comment by sshane** [comment]
did you apply @maxime-desroches's suggestions in https://github.com/commaai/openpilot/pull/28606?

**Comment by Korben00** [comment]
Yes. I manually added all suggestions of @maxime-desroches

**Comment by sshane** [comment]
Nice, look good to you then @maxime-desroches?

**Comment by adeebshihadeh** [comment]
If you can get another French user to review and sign off on this, we can merge.

**Comment by maxime-desroches** [comment]
LGTM!

**Comment by adeebshihadeh** [comment]
Thanks @maxime-desroches!

**Comment by Korben00** [comment]
Thanks @maxime-desroches !

**Pull request merged**
