### PR TITLE
UI: new set speed design and add speed limits

### LINKED ISSUE #24735: new max speed & speed limits design
Updated Variant 2 based on today's call – [Figma](https://www.figma.com/file/kPvxp4UcTTU9RLLOY7R2b9/openpilot?node-id=367%3A2058)
- MAX
  - updated layout
  - engaged: updated color on "MAX" word (V1 green seems to fit better)
- Speed Limit
  - US
  - EU - enclosing box - bottom right & left have full corner radius for better visual appeal

**Needs decision:** Going over Speed Limit
- Going +10 over speed limit → Max turns orange 🟠
- Going +20 over speed limit → Max turns red 🔴

+10/+20 limits are good enough, or should be made lower? For instance +5/+15?

------

PREVIEW:

Speed Limit - Preview

Speed Limit - States

_Originally posted by @jozef-simo in https://github.com/commaai/openpilot/issues/24681#issuecomment-1145306572_

### PR DESCRIPTION
**Pull request by pd0wm**
resolves #24735

### CODE REVIEW

**Comment by pd0wm** [comment]
2022-06-03-163603_1913x1078_scrot

**Comment by pd0wm** [comment]
No Speed limit
2022-06-14-130801_1915x1072_scrot

US Speed Limit
2022-06-14-130932_1916x1081_scrot

Canada (US sign, but metric)
2022-06-14-130907_1919x1078_scrot


Europe:
2022-06-14-130717_1908x1070_scrot

**Comment by KyleGreenlaw** [comment]
Not sure if it’s just my eyes but is the set speed+max a few pixels to high within the box

**Comment by KyleGreenlaw** [comment]
Also not sure if its been fixed but the "max" text is not the same colour as the set speed

**Comment by pd0wm** [comment]
@KyleGreenlaw You're right. I read off the wrong number for the "MAX" placement. The colors are as designed.
2022-06-15-113335_436x406_scrot
2022-06-15-113241_1915x1080_scrot

**Comment by pd0wm** [comment]
Final version with larger border implemented:
2022-06-15-114950_1914x1076_scrot

**Pull request merged**
