### PR TITLE
Update OpenPilot UI - add skins

### PR DESCRIPTION
**Pull request by pjlao307**
Preserves current UI (set as default) but can switch between UIs by setting value in /data/params/d/UISkin (set to 1 for default, 2 for new skin - uses default skin if file doesn't exist).  This can be added to baseui for users to choose a skin if this functionality is desired.

New UI looks like this: https://www.youtube.com/watch?v=BSBcZIh9U7k

- Moved UI elements to the bottom (except for radar info)
- Added arial.ttf font for use by new UI skin for easier readability
- Added analog speed gauges
- Made awareness bar horizontal
- Added timer text to awareness bar
- Added animation to UI ACC elements + Bar

### CODE REVIEW

**Comment by geohot** [comment]
The 7 million png files scare me. Can you tar them up or something and pull from the tarball in ui when you need access? (speed_assets.tar is much less scary)

**Comment by pjlao307** [comment]
Hmm... I'm not sure how to do that (read contents of the tar into memory) in C.  

I tried "slicing" a single image into pieces (using it like an image map) using nvgImagePattern, but that doesn't work because when you draw the sliced image the position of the slice is still relative to where it's located on the image map so I couldn't position it in the right place.

**Comment by pjlao307** [comment]
@geohot Would it be acceptable to untar the files into temp storage (i.e. /data/local/tmp), read the files into memory, then delete them from temp storage?

**Comment by pjlao307** [comment]
Figured out how to extract from tar.gz file so you don't have the gazillion PNG files anymore.

**Comment by energee** [comment]
RTBC?

**Comment by pjlao307** [comment]
Not sure what RTBC means.  If you're asking why I reverted it's because when I merged the 3.6.1 code from commaai/devel the CI test didn't pass.

**Comment by energee** [comment]
ready to be committed?

**Comment by energee** [comment]
I've been using this on mine, a major improvement. Did you look into trying to ease the slide-in transition vs the linear animation transition as it is currently?

**Comment by pjlao307** [comment]
I played around with easing but it didn't look that great, not sure if it's a framerate limit or what.

**Comment by energee** [comment]
Another bug i found was that KPH seems to stay on screen when in metric

**Comment by pjlao307** [comment]
When does it stay on screen?  When openpilot is off and it slides the circles out?

**Comment by energee** [comment]
Yes, lmk if you see it, I only turned on kpm on once by accident, I'll check next ride i do to see if it is consistent

**Comment by pjlao307** [comment]
The KPH issue should be fixed now.

**Pull request closed without merging**
