### PR TITLE
HKG Longitudinal Control

### PR DESCRIPTION
**Pull request by AskAlice**
I believe discussion and collaboration about how long control will be implemented will be quite helpful. this is the very bare bones... rough start. I expect this PR to evolve

So.. this is more of my scratchpad for this but let's get started by getting the functions we need to send these messages.

opendbc may need to be updated with TK's DBC for these messages to be properly enumerated

For vehicles with SCC, once we can make requests that are being honored, instead of pulling the fuse, we can just disable the SCC ECU similar to what was done in #1459 
goes with https://github.com/commaai/panda/pull/543

by sending these messages on my vehicle, that doesn't have SCC ( at the right frequency ofc ) i was able to get this menu to pop up

### CODE REVIEW

**Comment by TK211X** [comment]
I'll type up a checklist for proper message Idle. Once we kill OEM SCC ECU message Tx we need to immediately take over and send the SCC messages within an acceptable time frame to prevent a hard fault from dependent listening ECU's. (SCC11, SCC12, SCC13, SCC14, 4A2SCC and FCA11)

**Comment by TK211X** [comment]
**This is based on the current WIPV2 .dbc**

Condition Idle

SCC11 - 0x420 - 50/Sec

`MainMode_ACC` "1"

`SCCInfoDisplay` "0"

`AliveCounterACC` (Counter loop 0 to 15)

`VSetDis` "0"

`ObjValid` "0"

`DriverAlertDisplay` "0"

`TauGapSet` "4"

`ACC_ObjStatus` "0"

`ACC_ObjLatPos` "0"

`ACC_ObjDist` "204.6"

`ACC_ObjRelSpd` "0"

`Navi_SCC_Curve_Status` "0"

`Navi_SCC_Curve_Act` "0"

`Navi_SCC_Camera_Act` "0"

`Navi_SCC_Camera_Status` "0"


SCC12 - 0x421 - 50/Sec

`CF_VSM_Prefill` "0"

`CF_VSM_DecCmdAct` "0"

`CF_VSM_HBACmd` "0"

`CF_VSM_Warn` "0"

`CF_VSM_Stat` "0"

`CF_VSM_BeltCmd` "0"

`ACCFailInfo` "0"

`ACCMode` "0"

`StopReq` "0"

`CR_VSM_DecCmd` "0"

`aReqMax` "0"

`TakeOverReq` "0"

`PreFill` "0"

`aReqMin` "0"

`CF_VSM_ConfMode` "0"

`AEB_Failinfo` "0"

`AEB_Status` "0"

`AEB_CmdAct` "0"

`AEB_StopReq` "0"

`CR_VSM_Alive` (Counter loop 0 to 14)

`CR_VSM_ChkSum` (Checksum)

SCC13 - 0x50 - 5/sec

`SCCDrvModeRValue` "2"

`SCC_Equip` "1"

`AebDrvSetStatus` "0"

`Lead_Veh_Dep_Alert_USM` (IGNORE THIS)


SCC14 - 0x389 - 50/sec

`ComfortBandUpper` "-4.14"

`ComfortBandLower` "-4.14"

`JerkUpperLimit` "0"

`JerkLowerLimit` "0"

`SCCMode2` "0"

`ColRiskF` "0"


FCA11 - 0x38D - 50/sec

`CF_VSM_Prefill` "0"

`CF_VSM_HBACmd` "0"

`CF_VSM_Warn` "0"

`CF_VSM_BeltCmd` "0"

`CR_VSM_DecCmd` "0"

`RESERVED` (Not yet in DBC / Skip for Now)

`FCA_Status` "2"

`FCA_CmdAct` "0"

`FCA_StopReq` "0"

`FCA_DrvSetStatus` "1"

`CF_VSM_DecCmdAct` "0"

`FCA_Failinfo` "0"

`Supplemental_Counter` (Counter loop 0 to 14)

`FCA_RelativeVelocity` "0"

`FCA_TimetoCollision` "2540"

`CR_FCA_Alive` (Irregular pattern see Cabana Example)

`CR_FCA_ChkSum` (Checksum)


4A2SCC - 0x4A2 - 2/sec

`Paint_1` "1"

**Comment by TK211X** [comment]
There are two or three specific changes related to the 2020 Sonata SCC message logic. This pertains to the SCC14 jerk limits and comfort bands as well as FCA11 addition of a status message and addition of counter w/ a special change to the alive counter. It's not too bad given that this will be seen in future vehicles but the exclusion based on the presence of the 4A2SCC message will have to apply to pre-2019 vehicles.

**Comment by TK211X** [comment]
For request profile we will be working exclusively with:

`VSetDis`

`ACCMode`

`aReqMax`

`aReqMin`

`StopReq`

`ComfortBandUpper`

`ComfortBandLower`

`JerkUpperLimit`

`JerkLowerLimit`

`SCCMode2`

`ColRiskF`

**Comment by pd0wm** [comment]
Should we start with an opendbc PR that merges that updates the SCC messages into the current DBC?

**Comment by TK211X** [comment]
Standby...

**Comment by TK211X** [comment]
https://github.com/commaai/opendbc/pull/267/commits/dd030d31e190d1620ab7797890bd1d4437b3538b

**Comment by pd0wm** [comment]
Merged! You can rebase the branch.

Looking at the DBC AEB is controlled by the SCC module, and not by the camera? So if we kill the SCC module we lose AEB?

**Comment by TK211X** [comment]
> 
> 
> Merged! You can rebase the branch.
> 
> Looking at the DBC AEB is controlled by the SCC module, and not by the camera? So if we kill the SCC module we lose AEB?

https://github.com/commaai/openpilot/pull/1572#issuecomment-634635385

AEB = FCA

Either MFC or SCC ECU can create the FCA messages.

**Comment by TK211X** [comment]
https://github.com/commaai/openpilot/pull/1572#issuecomment-634678067

Has been updated.

**Comment by AskAlice** [comment]
@pd0wm status on this?

**Comment by AskAlice** [comment]
This is coming together.

xps was able to get OP long control working on an scc-equipped car with a giraffe intercepting the radar.. then a couple days later
xx979xx was able to get OP long working on scc-equipped vehicles
and just today I got my non-scc equipped vehicle emulating scc to the point where the EMS accepted the requests

**Comment by adeebshihadeh** [comment]
Closing due to inacivity

**Pull request closed without merging**
