### PR TITLE
Sonata Hybrid 2020 Support

### PR DESCRIPTION
**Pull request by TK211X**
Do not merge. Test in progress.

### CODE REVIEW

**Comment by scottadair** [comment]
Doesn't interface.py also need to be updated to include attribute for this model or car?

or add something like this at line 40

elif candidate in [CAR.SONATA, CAR.SONATA_H]:

**Comment by TK211X** [comment]
Yea you’re right. I was helping someone and made this so they have a reference.

**Comment by adeebshihadeh** [comment]
Any update on this? If it's good to merge, add a route to test_car_models.py

**Comment by adeebshihadeh** [comment]
Closing due to inactivity, feel free to reopen after adding a route to test_car_models.

**Pull request closed without merging**
