### PR TITLE
CARS.md: sort cars in lowercase

### PR DESCRIPTION
**Pull request by sshane**
locked with `pipenv lock --keep-outdated`

### CODE REVIEW

**Comment by jyoung8607** [comment]
Škoda is still at the bottom of the Silver list, should be higher.

In case it comes up again, Š does fall after S. We checked the Czech orthography with some native speakers when Subaru got moved above it in an earlier version of this doc.

**Comment by sshane** [comment]
That's difficult to do as python is just sorting by the unicode values of the characters which is correct. We can either hard code it, or include the natsort library which does this nicely for us

**Comment by jyoung8607** [comment]
Škoda gang appreciates your support!

**Review by adeebshihadeh — APPROVED** [review]
Next time add the dependency in its own PR

**Pull request merged**
