### PR TITLE
safetyparam is incorrect causing 42.86% less torque on Prius Prime

### PR DESCRIPTION
**Pull request by zorrobyte**
Screenshot 2019-07-30 20 51 03
.55

unknown-7

safetyparam of .66 with a safety limit of STEER_ERROR_MAX = 350  (# max delta between torque cmd and torque motor) results in 42.86% less available torque for Prius Prime

Segment
edfe2e22d60f83f1|2019-07-30--14-31-34--3

You should check regular Prius (non Prime) and determine if the vehicles are both incorrect, or need split in interface & DBC
https://github.com/commaai/openpilot/pull/294

This value is important. Corolla has it set to 100. It makes me wonder what other cars are incorrect?

### CODE REVIEW

**Comment by rbiasini** [comment]
@zorrobyte : having the safety param overestimated is ok. It does not result in less available torque. Rather, it allows to command a bit more torque than expected when the driver is slightly  overriding.

**Comment by zorrobyte** [comment]
@rbiasini could it cause the integral to unwind more frequently as mentioned here?
https://github.com/commaai/openpilot/pull/731

I'm getting less Take Control driver override messages now with the scale set properly.

**Comment by zorrobyte** [comment]
image

**Comment by rbiasini** [comment]
not sure where you get 42.86%. The most common case we want to cover for is when the driver applies a torque against the OP desire. In this case, the important thing is that OP torque gets limited to 350 (since EPS torque has opposite sign)

**Comment by zorrobyte** [comment]
42.86% is the difference between the torque command - torque sensor at .66 scale, and the STEER_ERROR_MAX of 350 in safety of this cabana edfe2e22d60f83f1|2019-07-30--14-31-34--3

image

So the `dist_to_meas_check` function in safety not only compares the max down and up rate, but also the MAX_ERROR when determining if a violation has occurred. https://github.com/commaai/openpilot/blob/94053536b4bfa7a8c4760db99063093aae69374d/panda/board/safety.h#L137

```
The most common case we want to cover for is when the driver applies a torque against the OP desire.
```

I think that this case is separately checked for in the `driver_limit_check` function here: https://github.com/commaai/openpilot/blob/94053536b4bfa7a8c4760db99063093aae69374d/panda/board/safety.h#L153

It even has a `DRIVER_FACTOR` variable and a `val_driver` which I assume is driver torque.

If the EPS torque sensor isn't properly scaled, then the torque command may be limited artificially by up to 42.86% in some cases, or at least my assessment of such, which led to this PR.

Not related to the Prius, but the Camry has a noisy torque sensor which can also cause issues if my assumptions are correct:


I checked Rav and it looks fine.

**Comment by zorrobyte** [comment]
I'm going to continue testing this, I'm getting mixed results from other community members.

**Pull request closed without merging**
