### PR TITLE
sending to master. interface support kfBP and kfV

### PR DESCRIPTION
**Pull request by birdman6450**
i accidentally PRed to release2 and i am i trying to send it to master

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
I closed your other two PRs as it should be one PR.

**Comment by xps-genesis** [comment]
this is a big change. every selfdrive/car/xxx/interface.py should switch to List[] Kf. This change error will fault out every other car variant that doesn't provide kfBp and KfV values.

**Comment by majorwolf** [comment]
> 
> 
> this is a big change. every selfdrive/car/xxx/interface.py should switch to List[] Kf. This change will fault out every other car variant that doesn't provide kfBp and KfV values.

Should someone put in the work and go through and change all the interface files to match?

**Comment by xps-genesis** [comment]
I am not sure who decides that? what if you put in all the work and comma decides having Kf speed dependent doesn't make sense and reject he PR? I have Hyundai interface.py ready on my fork and I can copy paste and create a PR. but what about other brands? If someone from comma agrees to this change, some of us can contribute to this change.

**Comment by pd0wm** [comment]
What is the benefit of this change?

It doesn't really make sense, kF is already scaled with the square of the speed (https://github.com/commaai/openpilot/blob/master/selfdrive/controls/lib/latcontrol_pid.py#L36).

**Comment by adeebshihadeh** [comment]
Closing due to inactivity. Feel free to re-open.

**Pull request closed without merging**
