### PR TITLE
2023 Hyundai Sonata Hybrid Fingerprint

### PR DESCRIPTION
**Pull request by pianogineer**
Limited trim.

### CODE REVIEW

**Comment by incognitojam** [comment]
What is your dongle ID?

**Comment by joshslater** [comment]
dongle id: 608d4270264eb0d8

**Comment by incognitojam** [comment]
can I just double check which harness did you buy?

**Comment by joshslater** [comment]
using harness Hyundai A

**Comment by incognitojam** [comment]
thanks!

**Pull request merged**
