### PR TITLE
Params: use a multiple-reader / single-writer flock to improve concurrency

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
Is it necessary to take the lock before reading? The python implementation of the params doesn't do this (only when reading all the values, I assume to get a consistent view).

**Comment by deanlee** [comment]
yes,we should prevent reading of the file while it's being modified or deleted. I'll update this PR to fix that too.

**Comment by deanlee** [comment]
My bad, I did not read the code carefully.the current implementation does not require locks for reading

**Comment by pd0wm** [comment]
I think the lock on line 288 in params.cc can be removed completely. The rest looks fine!

**Pull request merged**
