### PR TITLE
CI: prevent moc from running in cache population step

### PR DESCRIPTION
**Pull request by fredyshox**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What's this for?

**Comment by fredyshox** [comment]
QT moc sources are stored inside `/tmp/scons_cache/moc_files`. scons_cache is deleted in cache repopulation steps (`build_all` and `build_mac` jobs), so they are regenerated/recompiled again, which adds on avg. 1-2 minutes of build time.

**Comment by adeebshihadeh** [comment]
Good catch, but we still need to manage the old ones somehow. This cleanup step is done so we're not caching old build products.

**Comment by fredyshox** [comment]
Added cleanup script, which looks at scons task-trace to determine which moc files are currently in use. It's based on a simple regex path matching, but should be enough to delete outdated build products.

**Pull request merged**
