### PR TITLE
Toyota: Add Lexus GS F 2016

### PR DESCRIPTION
**Pull request by calvinchui382025**
**Checklist**
- [ ] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: ab9b64a5e5960cba|2023-10-17--18-59-12
- [x] route with stock system: ab9b64a5e5960cba|2023-10-14--00-38-19

### CODE REVIEW

**Comment by snyperifle** [comment]
Stuck with a "CAN Error: Check Connections". Been messing around but not sure what else I can do.

**Comment by snyperifle** [comment]
It's working properly with the Lexus GSF now. Mine is a 2016, it will likely work with the 2017.

Most likely won't work with the 2018-2020's since they have a different ACC system.

**Comment by snyperifle** [comment]
I'm not sure if I did the first step correctly (running selfdrive/car/docs.py bugs out on my computer).

Can someone verify?

**Comment by sshane** [comment]
Thanks for the port! Can you provide a new route for the tests? That one seems to be missing all the logs.

**Comment by sshane** [comment]
Thanks for the port! It looks like that the route is too old or doesn't have full logs uploaded (rlogs). Can you get another route that will be public we can use for tests? Thanks!

Any issues you noticed with the car and openpilot so far?

**Comment by snyperifle** [comment]
> Any update on the route? Any issues you noticed with the car and openpilot so far?

Hi Shane, sorry I have been out of town for a funeral but I get back tonight.

**Comment by snyperifle** [comment]
> Any update on the route? Any issues you noticed with the car and openpilot so far?

ab9b64a5e5960cba|2023-10-17--18-59-12 I uploaded all the files within Connect and I made the route public in useradmin

**Review by thegauravgiri — APPROVED** [review]
Looks good to me

**Comment by sshane** [comment]
If you end up getting a new test route, let me know. Looks like encoderd crashed there any didn't capture any qcams. Not a dealbreaker if you can't get a new one though, just a nice to have to view the videos while exploring the routes

**Comment by sshane** [comment]
Can I use https://connect.comma.ai/ab9b64a5e5960cba/1698186728072/1698187358620?

**Comment by snyperifle** [comment]
> Can I use https://connect.comma.ai/ab9b64a5e5960cba/1698186728072/1698187358620 ?

Yes that's fine, I made it public in useradmin. I'll upload the Connect files tomorrow

**Comment by gsf2016** [comment]
i would like to try this on my 2016 GS F.  i have a comma 3.  what url should i use to load into my comma 3?  thanks!

**Comment by snyperifle** [comment]
> i would like to try this on my 2016 GS F. i have a comma 3. what url should i use to load into my comma 3? thanks!

Try this

https://smiskol.com/fork/snyperifle
or
https://smiskol.com/fork/snyperifle/master

We may need to add your car's computer fingerprints but see if that works

**Comment by gsf2016** [comment]
Just came back from a quick drive.  Happy to report it works perfect!!

**Pull request merged**
