### PR TITLE
Fingerprints: add missing FW versions from users

### PR DESCRIPTION
**Pull request by sshane**
```python
Updating FW version database with FW from 1 dongles (1 platforms):
('2141be049915fb7e', ('TOYOTA CAMRY 2018', 'XXX'))
```

### CODE REVIEW

**Comment by sshane** [comment]
@jnewb1 can we have it add Honda and Toyota labels, or does that break some other assumptions about the file logic?

**Comment by adeebshihadeh** [comment]
Do we ever really use the brand labels? I personally don't use them at all

**Comment by jnewb1** [comment]
> @jnewb1 can we have it add Honda and Toyota labels, or does that break some other assumptions about the file logic?

a refactor that touches all car's would have all the car's label applied

**Comment by sshane** [comment]
> Do we ever really use the brand labels? I personally don't use them at all

I use the labels to find specific changes for the release blog post, plus look back on recent changes for brands.

**Comment by adeebshihadeh** [comment]
Ah, I use the git log for that, e.g. `git log selfdrive/car/honda`.

**Pull request merged**
