### PR TITLE
Enable Auto High Beams and more

### PR DESCRIPTION
**Pull request by arne182**
A reflash of panda is required. 
kill OP
exceute make in /panda/board while in main OBD2 port
This will forward all signals and therefore a 120ohm resistor is required between pins 12 and 13

### CODE REVIEW

**Comment by arne182** [comment]
ECU.CAM values not needed

With forwarding enabled and the giraffe on "proxy stock adas w/ panda" 0101

**Comment by rbiasini** [comment]
yeah, I wanted to do this for a while. Only issue is the missing 120Ohm resistor on old Toyota giraffe (and the need of changing the giraffe switches). Probably solvable by issuing an alert if camera is not connected to panda bus 2.

**Comment by arne182** [comment]
Good then do that. So you did forget the 120 ohm resistor. Took me months to figure out why the forwarding was not working. You could of just told us who bought defective giraffes

**Comment by arne182** [comment]
How do we check if camera is not connected to panda bus 2?

**Comment by misterkoll** [comment]
@rbiasini, @arne182 asked me to test this on my 2017 Toyota RAV4 XLE (non-hybrid). It appears to forward the 0x414 message for AHB just fine. My only concern is that shoving the 120ohm resistor into the giraffe obd connector for parallel pins 12-13 is not always reliable. My solution was to make an opening on the front of giraffe and solder directly to the pin 12 and 13 pads.

**Comment by rbiasini** [comment]
Ok, made this change internally and it will be in next release, without breaking OP for users without the 120Ohm resistor on giraffe CAN3

**Comment by mtourangeau** [comment]
Working for me on Prius Prime with 120 ohm resistor.

**Comment by mtourangeau** [comment]
Tested on Prius Prime with 120 ohm resistor.

**Comment by CaptBlind** [comment]
With much patience and assistance from Arne, I have finally got the 120-ohm resistor soldered in and installed, I have flashed the Panda before sticking it to the giraffe. We have one happy zoo here and the AHB work beautifully. HINT: Tou can't really test the AHB in the daytime. WHo would have thought?

Excellent work by Arne on this and other parts of his branch. Thanks a million for your dedication to the cause. 

2017 Toyota Rav-4, LeEon, grey panda, a toryta giarafffe and two pesky parrots.

**Pull request closed without merging**
