### PR TITLE
Fingerprint Sienna LE 2018

### PR DESCRIPTION
**Pull request by abdulrahman004**
Although I was able to use OP before adding fingerprint, i did notice that the car would go into dashcam mode after i turned off-on my car
Also had issues when disengaging OP by accelerating/braking that the car would beep momentarily alerting the front camera had issues.

Both of the problems seem to have resolved since I added fingerprint. Do I need a cabana drive with this change for the approval ?

### CODE REVIEW

**Comment by abdulrahman004** [comment]
Here's the cabana drive with OP disabled. 1001 
https://my.comma.ai/cabana/?route=dacf41c92ea47d87%7C2019-09-20--03-17-55&exp=1600545278&sig=gYiocjMlvhpEoJm%2FRvLHln1ziosM6XRPv30NTl4d%2BoU%3D&max=7&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fdacf41c92ea47d87%2Fd131ccf4b8521e81e1b47e2dc8268584_2019-09-20--03-17-55

**Comment by abdulrahman004** [comment]
Here's one with OP enabled 0101; if you need one
https://my.comma.ai/cabana/?route=dacf41c92ea47d87%7C2019-09-19--22-47-30&exp=1600545554&sig=nN50qw2G34geWiChIddTn2CGz%2BNdSJtdsJFqIvEj024%3D&max=32&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fdacf41c92ea47d87%2F81935aff1ac8a40d82c986e67a381351_2019-09-19--22-47-30

**Comment by rbiasini** [comment]
@abdulrahman004 , I'm confused. The route you sent me with giraffe on 1001 seems to have the following fingerprint:
```
36: 8, 37: 8, 114: 5, 119: 6, 120: 4, 170: 8, 180: 8, 186: 4, 426: 6, 452: 8, 464: 8, 466: 8, 467: 8, 544: 4, 545: 5, 548: 8, 550: 8, 552: 4, 562: 4, 608: 8, 610: 5, 643: 7, 705: 8, 725: 2, 740: 5, 764: 8, 800: 8, 824: 8, 835: 8, 836: 8, 849: 4, 869: 7, 870: 7, 871: 2, 896: 8, 900: 6, 902: 6, 905: 8, 911: 8, 916: 1, 921: 8, 933: 8, 944: 6, 945: 8, 951: 8, 955: 8, 956: 8, 979: 2, 992: 8, 998: 5, 999: 7, 1000: 8, 1001: 8, 1002: 8, 1008: 2, 1017: 8, 1041: 8, 1042: 8, 1043: 8, 1056: 8, 1059: 1, 1076: 8, 1077: 8, 1114: 8, 1160: 8, 1161: 8, 1162: 8, 1163: 8, 1164: 8, 1165: 8, 1166: 8, 1167: 8, 1176: 8, 1177: 8, 1178: 8, 1179: 8, 1180: 8, 1181: 8, 1182: 8, 1183: 8, 1191: 8, 1192: 8, 1196: 8, 1197: 8, 1198: 8, 1199: 8, 1200: 8, 1201: 8, 1202: 8, 1203: 8, 1212: 8, 1227: 8, 1235: 8, 1279: 8, 1552: 8, 1553: 8, 1555: 8, 1556: 8, 1557: 8, 1561: 8, 1562: 8, 1568: 8, 1569: 8, 1570: 8, 1571: 8, 1572: 8, 1592: 8, 1593: 8, 1595: 8, 1664: 8, 1666: 8, 1667: 8, 1745: 8, 1779: 8, 1904: 8, 1912: 8, 1990: 8, 1998: 8
```
which is fully included into the already existing one. how did you obtain your fingerprint?

**Comment by abdulrahman004** [comment]
@rbiasini not quite sure why that is. Running `get_fingerprint` script gave me the fingerprint thats in this PR after multiple restarts as suggested. Also the fact that my EON use to go in dashcam mode after I restart the car. 

here's another cabana drive after I restarted the car a few times in mode 1001. May be this one has the fingerprint in the PR ?

https://my.comma.ai/cabana/?route=dacf41c92ea47d87%7C2019-09-26--16-19-17&exp=1601362694&sig=OOZtMChpGayE1I1%2BWECIALk9YpDNm0IbJOTDtSkwwHM%3D&max=11&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fdacf41c92ea47d87%2Fee2f0b8dbf0ab7b3ed78f2f079e7e1ef_2019-09-26--16-19-17

**Comment by rbiasini** [comment]
mmm.. I checked again, and I confirm the fingerprint I posted above: looking into it more, your fingerprint has message 238 which I don't see in any of the routes posted.

Based on what I see, I really don't think you need a new fingerprint.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Comment by abdulrahman004** [comment]
This was already merged on a different PR and releases in 0.6.7 i think. So we are good

**Pull request closed without merging**
