### PR TITLE
ui: remove QtQml and related dependencies

### PR DESCRIPTION
**Pull request by deanlee**
This PR refactors the `TermsPage` to use standard Qt Widgets instead of QtQml components. 

This change removes QtQml and its related modules (QtQuick, QuickWidgets, Qml, QtQmlModels, ...), which are quite large. The primary goals are to reduce project dependencies, improve build performance, and simplify the dependency graph. additionally, since QtQml components are more resource-intensive, this change will also save some UI resources.

The UI appearance remains consistent with previous designs, with the only difference being that the scrollbar is hidden, leading to slight changes in padding.

Also the UI may eventually move to another framework, but since that could take a while, I think it's still worth removing QtQml now.

**After:**
Screenshot 2024-08-23 02:36:16

**Before:**

Screenshot 2024-08-23 02:17:06

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
How’s the scrolling on device? I think this is why we did it originally.

**Comment by deanlee** [comment]
It behaves consistently with other UI components using ScrollView, which do not display scrollbars by default on the device.

**Comment by deanlee** [comment]
It’s possible that the TermsPage was one of the earliest widgets implemented, and the ScrollView component at that time had many bugs.

**Comment by adeebshihadeh** [comment]
FYI @deanlee, we plan on removing terms + training from device and just putting them on a webpage. So no need to rewrite these.

**Comment by deanlee** [comment]
got it

**Pull request merged**
