### PR TITLE
Correct Hyundai Steering Torque sensor

### PR DESCRIPTION
**Pull request by oricalworks**
Fixed by using the sensor between steering wheel and steering column!

### CODE REVIEW

**Comment by pd0wm** [comment]
Is this value signed correctly? Or is it always positive?

**Comment by oricalworks** [comment]
> Is this value signed correctly? Or is it always positive?

https://api.retropilot.org/cabana/index.html?retropilotIdentifier=de647b2e|662b29cc0cd29d6959b61565247f3a361f680c2fd3ed3aa0faf281841085b98e|2021-07-15--19-01-57|e26245a402dd5e4044ea054896cdeca1f602abd278293e39584791b988ba12e5&retropilotHost=https%3A%2F%2Fapi.retropilot.org%2F&demo=1

look at MDPS11 CR_Mdps_DrvTq

**Comment by oricalworks** [comment]
fixed missing check

**Comment by oricalworks** [comment]
The failed check is because of HONDA ACCORD 2018 which is weird bc I didn't touch master and only made changes to  Hyundai.

**Comment by pd0wm** [comment]
Oh my bad, it's the angle rate that's not correctly signed on HKG.

What's the benefit of this signal over the existing one?

**Comment by oricalworks** [comment]
> Oh my bad, it's the angle rate that's not correctly signed on HKG.
> 
> What's the benefit of this signal over the existing one? Is this driver torque instead of total torque? 
YES exactly its driver applied torque and not total.

**Comment by pd0wm** [comment]
Seems like there was some discussion about this already:
 - https://github.com/commaai/openpilot/pull/970#discussion_r368311619
 - https://github.com/commaai/panda/pull/427

From those discussions it seems like not all cars have this signal and it's better to use the current one.

**Comment by oricalworks** [comment]
> Seems like there was some discussion about this already:
> 
> * [Hyundai-Kia-Genesis (HKG) #970 (comment)](https://github.com/commaai/openpilot/pull/970#discussion_r368311619)
> * [Hyundai-Kia-Genesis (HKG) panda#427](https://github.com/commaai/panda/pull/427)
> 
> From those discussions it seems like not all cars have this signal and it's better to use the current one.

Thank you

**Pull request closed without merging**
