### PR TITLE
Add missing FW versions for 2019 Honda Passport

### PR DESCRIPTION
**Pull request by lucentheart**

### CODE REVIEW

**Comment by sshane** [comment]
Can you provide a dongle id?

**Comment by sshane** [comment]
Any updates @lucentheart?

**Comment by lucentheart** [comment]
Sorry for the late reply. The dongle id is
aadbd1a661fb4da3

Thanks,

lucentheart

**Comment by lucentheart** [comment]
Sorry. I missed one number. It should be

aadbd1a661fb4da3

Thanks,

lucentheart

**Pull request merged**
