### PR TITLE
fixed max torque, for more actual torque

### PR DESCRIPTION
**Pull request by Gernby**
The stock torque command doesn't exceed 3840 (0xF00), and exceeding that value actually results in less torque.

### CODE REVIEW

**Comment by Gernby** [comment]
This explains several observations I've had over the thousands of miles I've been working with OP.  The most confusing observation was that the car would sometimes make a corner, and sometimes not come close.  Also, when I increased the max value to 32K, I did experience some increase in response, since it allowed more "wrap around" of the bits that are used.

**Comment by rbiasini** [comment]
How do you know this is true? did you use cabana to compare cmd torque VS electrical EPS torque?
If this is true, I'm ok merging it, but I would remove MAX_SCALE and simply adjust Kp, Ki and Kf tuning according to the new max (linear scaling would keep the control behavior roughly unchanged).

**Comment by Gernby** [comment]
I haven't reviewed it in cabana yet, but I observed it with my real-time dashboard while doing a test drive on one of my standard test routes.  While the response is still lacking, it's far better than I've ever experienced with this car.  I was able to take corners at higher speeds with less lane wandering.
screenshot 2019-01-09 22 58 06

**Comment by Gernby** [comment]
Regarding the STEER_SCALE, I agree it would be preferrable to adjust all of the other Honda's K values to eliminate the need for STEER_SCALE.  I actually did something like that at first, but the response wasn't the same.  Without actually calculating the values, I assumed that all of the [0.6,], [0.18,] values would "nicely" convert to the [0.8,], [0.24,] values that the CRV's and Civics use, but those values didn't work well for my Accord.  Also, the standard value for all Honda's Kf is 0.00006, so it seems less desirable to split the Honda's into 2 more tuning groups:
Existing tuning groups:
`Kf = 0.00006, Kp = 0.6, and Ki = 0.18`
`Kf = 0.00006, Kp = 0.8, and Ki = 0.24`

New tuning groups:
`Kf = 0.00005625, Kp = 0.5625, and Ki = 0.16875`
`Kf = 0.00005625, Kp = 0.75, and Ki = 0.225`

**Comment by Gernby** [comment]
Here is the cabana drive from the screenshot above.  The screenshot was at 2.550
https://community.comma.ai/cabana/?route=ddd3e089e7bbe0fc%7C2019-01-09--19-35-54&max=50&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Fddd3e089e7bbe0fc%2F3e1590a1d11a0c9867bc6953422b1e0d_2019-01-09--19-35-54

**Comment by Gernby** [comment]
I should mention the[ issue](https://github.com/commaai/openpilot/issues/474) I raised a few weeks ago about some "episodes" I experienced relating to the stock RDM system, which prompted me to do some testing with OP in passive mode to observe the stock RDM values.  The max values for RDM were 3840.
image

**Comment by Gernby** [comment]
After more testing, I don't think there is a max torque value, just a max response (per time).  Here are some test results while steering with a keyboard to command values multiple times higher than 0x1000.  Note that the EPS responded almost identically in each direction, with 2 steering "bursts" about 5-6 seconds apart.

I'm going to close this PR, since it seems unnecessary.
screenshot 2019-01-28 16 16 45
screenshot 2019-01-28 16 48 22

**Pull request closed without merging**
