### PR TITLE
Update Highlander Tuning

### PR DESCRIPTION
**Pull request by zeeexsixare**
Experimentally derived by P Lee (zeeexsixare)

### CODE REVIEW

**Comment by rbiasini** [comment]
Do you have some trace (e.g. cabana plots) to show the behavior before VS after the tuning?

**Comment by zeeexsixare** [comment]
> Do you have some trace (e.g. cabana plots) to show the behavior before VS after the tuning?

Sure, will acquire some over the next few days.

**Comment by zeeexsixare** [comment]
Note to myself: Jan 15 2019 mid-day drives

**Comment by zeeexsixare** [comment]
@rbiasini I whipped up a presentation of results.  Let me know what you think:

[Highlander Tuning PR #464.pdf](https://github.com/commaai/openpilot/files/2798606/Highlander.Tuning.PR.464.pdf)


Link to Cabana with Stock Values (slow speed, then high speed, then medium speed curve):
https://community.comma.ai/cabana/?route=aa659debdd1a7b54%7C2019-01-07--11-58-03&max=11&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Faa659debdd1a7b54%2F73643eabc5970c8ae3e993f8b931dd1e_2019-01-07--11-58-03

Link to Cabana with P Lee Values (slow speed, then high speed, then medium speed curve):
https://community.comma.ai/cabana/?route=aa659debdd1a7b54%7C2019-01-07--11-46-20&max=8&url=https%3A%2F%2Fchffrprivate.blob.core.windows.net%2Fchffrprivate3%2Fv2%2Faa659debdd1a7b54%2Fea8599649c60fd7303bdb77e8c11c88e_2019-01-07--11-46-20

**Comment by rbiasini** [comment]
@zeeexsixare , awesome documentation. I would be fine with the Kp and Ki change. What I'm very unsure about is the change to kf. 0.0003 means full steer torque command at 4 deg steering angle and 65 mph (0.0003*30*30*4 ~= 1).
what if you go with 0.00015?

Next week we can test this setting on our cars.

**Comment by zeeexsixare** [comment]
kf = 0.00015 continues to work very well.  Do you need a re-test of the test scenario in my presentation with this new kf?  Or will you guys test it out and push if acceptable?

**Comment by rbiasini** [comment]
Thanks, It's acceptable without redoing the ppt. Other users tested it too?

**Comment by zeeexsixare** [comment]
I haven't had others try it out, good idea. I'll forward on to other Highlander users on Discord and report back once we have consensus.

**Comment by zeeexsixare** [comment]
Riccardo, I've confirmed through a month of varied driving that we are good to push the latest parameters with the lower Kf at 0.0015.  The lower value fixed some hugging issues.  Others agree and are ready to push!

**Comment by rbiasini** [comment]
Fixed in Highlander Tuning #690

**Pull request closed without merging**
