### PR TITLE
Enable Toyota AEB

### PR DESCRIPTION
**Pull request by arne182**
With no major modification allow open pilot to brake like stock AEB. A panda PR is attached to this PR
https://github.com/commaai/panda/pull/272

### CODE REVIEW

**Comment by rbiasini** [comment]
Mmm.. what does max accel have to do AEB?

**Comment by arne182** [comment]
If you brake hard enough and fast enough at a high speed. The Toyota will enable the hazard lights for you automatically.

**Comment by ErichMoraga** [comment]
I looked at the code, and think he's bumping Panda safety to to max acceleration of 3.0 m/s/s to allow Toyota's AEB threshold to kick in.  As Arne says, Toyota will do things like flash the hazard lights automatically in extreme deceleration/braking situations.  That said, I feel this is a dangerous PR, am am not even sure Comma will want Arne playing with that in his own fork.

**Comment by ErichMoraga** [comment]
I looked at the code, and think he's bumping Panda safety to to max acceleration of 3.0 m/s/s to allow Toyota's AEB threshold to kick in.  As Arne says, Toyota will do things like flash the hazard lights automatically in extreme deceleration/braking situations.  That said, I feel this is a dangerous PR, and am unsure Comma will want Arne playing with that in his own fork.

**Pull request closed without merging**
