### PR TITLE
Ford: FPv2 firmware request

### PR DESCRIPTION
**Pull request by incognitojam**
This gets us responses from eps, esp, fwdRadar, fwdCamera and engine ECUs on my Focus, but we may need to verify that we get a response from the transmission too on a vehicle with an automatic transmission... This would be useful for transmission type detection.

### CODE REVIEW

**Comment by incognitojam** [comment]
When we use `bus=1` like other brands (current behaviour) we only get the engine ECU: `85ad625d9a86b88d|2022-04-15--13-08-09--0`

**Comment by incognitojam** [comment]
Segment with this PR `86d00e12925f4df7|2022-04-21--13-41-18--0`

```
'carFw': [{'address': 2016, 'ecu': 'engine', 'fwVersion': b'JX6A-14C204-BPL\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'subAddress': 0},
          {'address': 1840, 'ecu': 'eps', 'fwVersion': b'JX6C-14D003-AH\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'subAddress': 0},
          {'address': 1888, 'ecu': 'esp', 'fwVersion': b'JX61-2D053-CJ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'subAddress': 0},
          {'address': 1798, 'ecu': 'fwdCamera', 'fwVersion': b'JX7T-14F397-AH\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'subAddress': 0},
          {'address': 1892, 'ecu': 'fwdRadar', 'fwVersion': b'JX7T-14D049-AC\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'subAddress': 0}]
```

**Comment by adeebshihadeh** [comment]
Can you rebase this? We can merge this now, since it won't affect other cars with the recent FW query changes.

**Comment by incognitojam** [comment]
Sorry I didn't get time to do this, glad it got merged!

**Comment by incognitojam** [comment]
Somehow the engine ECU looks to be resolving to mazda
Route: `86d00e12925f4df7|2022-07-16--16-34-38`

**Comment by sshane** [comment]
Looks like your engine was never responding to your Ford request then, but it does successfully respond to the Mazda request

**Comment by incognitojam** [comment]
Yes I have confirmed that it only responds on bus 1, with or without the tester present message.

**Comment by sshane** [comment]
Want to open a PR to add this request?

**Pull request merged**
