### PR TITLE
process_replay: drain sockets instead recv_one

### PR DESCRIPTION
**Pull request by fredyshox**
Attempt to replicate the behavior of https://github.com/commaai/openpilot/pull/28115, while using the existing replay mechanism

### CODE REVIEW

**Comment by fredyshox** [comment]
@adeebshihadeh the only processes that will not pass the process_replay are ubloxd and locationd. turns out the controlsd is fine, the `should_recv_callback` was invalid, but the new implementation will not use them.

**Comment by fredyshox** [comment]
It does not match it yet, but it produces the new outputs, which I will attempt to match in the refactor

**Comment by fredyshox** [comment]
BTW if you take a look at logs, the `locationd` and `torqued` fail even of on segments where the log lengths are the same. As for locationd it's because, I've added `carParams` to pubs as it seems it listens to it too. And as for `torqued` I've replaced `controlsState` with `carControl` messages, for the same reason. Now everything gets whatever it listens too.

**Review by adeebshihadeh — COMMENTED** [review]
Can you post the diff and a quick explanation for each service's diff?

**Comment by fredyshox** [comment]
The only processes which do not pass, are: `locationd`, `ubloxd`, `torqued`.
 
 ```
 ***** results for segment regenFA002A80700|2022-09-27--15-37-02--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenFA002A80700|2022-09-27--15-37-02--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenFA002A80700|2022-09-27--15-37-02--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 1205 VS 6047
		Counter({'liveLocationKalman': 1205})
		Counter({'liveLocationKalman': 6047})
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenFA002A80700|2022-09-27--15-37-02--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenFA002A80700|2022-09-27--15-37-02--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 604 VS 1313
		Counter({'ubloxGnss': 604})
		Counter({'ubloxGnss': 719, 'gpsLocationExternal': 594})
    laikad
    torqued
```
*locationd*
New `locationd_rcv_callback` for locationd, which changes receive frequency for non-cars. It's not exactly 5 times more messages, because the `locationd` is responding at 20Hz until it gets carParams with nonCar flag set to false.
 
*ubloxd*
ubloxd can send multiple messages based on single ubloxRaw, the existing process_replay expected only one

```
***** results for segment regenBE53A59065B|2022-09-27--16-52-03--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenBE53A59065B|2022-09-27--16-52-03--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenBE53A59065B|2022-09-27--16-52-03--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeSinceReset: 704
        liveLocationKalman.timeToFirstFix: 471
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenBE53A59065B|2022-09-27--16-52-03--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenBE53A59065B|2022-09-27--16-52-03--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 608 VS 1165
		Counter({'ubloxGnss': 608})
		Counter({'ubloxGnss': 612, 'gpsLocationExternal': 553})
    laikad
    torqued
```

*locationd*
Added carParams to the subs.

*ubloxd* 
Same as above

```
***** results for segment d545129f3ca90f28|2022-11-07--20-43-08--3 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
    laikad
    torqued
```

-


```
***** results for segment regen929C5790007|2022-09-27--16-27-47--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen929C5790007|2022-09-27--16-27-47--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen929C5790007|2022-09-27--16-27-47--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 617 VS 1191
		Counter({'ubloxGnss': 617})
		Counter({'ubloxGnss': 633, 'gpsLocationExternal': 558})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen929C5790007|2022-09-27--16-27-47--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen929C5790007|2022-09-27--16-27-47--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 19
```

*torqued*
Removed controlsState from subs and added carControl. Without this change `totalBucketPoints` is zero all the time.

```
***** results for segment regenEA3950D7F22|2022-09-27--15-43-24--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenEA3950D7F22|2022-09-27--15-43-24--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenEA3950D7F22|2022-09-27--15-43-24--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 612 VS 1174
		Counter({'ubloxGnss': 612})
		Counter({'ubloxGnss': 618, 'gpsLocationExternal': 556})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenEA3950D7F22|2022-09-27--15-43-24--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenEA3950D7F22|2022-09-27--15-43-24--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 215
```

All the other ones are caused by the same things as above. Without the changes to subs of `torqued` and `locationd`, these have matching output.

```
***** results for segment regen89026F6BD8D|2022-09-27--15-45-37--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen89026F6BD8D|2022-09-27--15-45-37--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen89026F6BD8D|2022-09-27--15-45-37--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 595 VS 1303
		Counter({'ubloxGnss': 595})
		Counter({'ubloxGnss': 717, 'gpsLocationExternal': 586})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen89026F6BD8D|2022-09-27--15-45-37--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen89026F6BD8D|2022-09-27--15-45-37--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 182
***** results for segment regenC7D5645EB17|2022-09-27--15-47-29--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenC7D5645EB17|2022-09-27--15-47-29--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenC7D5645EB17|2022-09-27--15-47-29--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeSinceReset: 2
        liveLocationKalman.timeToFirstFix: 1174
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenC7D5645EB17|2022-09-27--15-47-29--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenC7D5645EB17|2022-09-27--15-47-29--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 594 VS 1230
		Counter({'ubloxGnss': 594})
		Counter({'ubloxGnss': 677, 'gpsLocationExternal': 553})
    laikad
    torqued
***** results for segment regenCC2ECCE5742|2022-09-27--16-18-01--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenCC2ECCE5742|2022-09-27--16-18-01--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenCC2ECCE5742|2022-09-27--16-18-01--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeToFirstFix: 1176
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenCC2ECCE5742|2022-09-27--16-18-01--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenCC2ECCE5742|2022-09-27--16-18-01--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 599 VS 1236
		Counter({'ubloxGnss': 599})
		Counter({'ubloxGnss': 680, 'gpsLocationExternal': 556})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenCC2ECCE5742|2022-09-27--16-18-01--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenCC2ECCE5742|2022-09-27--16-18-01--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 84
***** results for segment regenC253C4DAC90|2022-09-27--15-51-03--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenC253C4DAC90|2022-09-27--15-51-03--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenC253C4DAC90|2022-09-27--15-51-03--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 590 VS 1186
		Counter({'ubloxGnss': 590})
		Counter({'ubloxGnss': 631, 'gpsLocationExternal': 555})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenC253C4DAC90|2022-09-27--15-51-03--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenC253C4DAC90|2022-09-27--15-51-03--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 213
***** results for segment 17fc16d840fe9d21|2023-04-26--13-28-44--5 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/17fc16d840fe9d21|2023-04-26--13-28-44--5_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/17fc16d840fe9d21|2023-04-26--13-28-44--5_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 644 VS 1329
		Counter({'ubloxGnss': 644})
		Counter({'ubloxGnss': 729, 'gpsLocationExternal': 600})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/17fc16d840fe9d21|2023-04-26--13-28-44--5_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/17fc16d840fe9d21|2023-04-26--13-28-44--5_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 221
***** results for segment regen1E72BBDCED5|2022-09-27--15-55-31--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen1E72BBDCED5|2022-09-27--15-55-31--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen1E72BBDCED5|2022-09-27--15-55-31--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeSinceReset: 1
        liveLocationKalman.timeToFirstFix: 1175
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen1E72BBDCED5|2022-09-27--15-55-31--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen1E72BBDCED5|2022-09-27--15-55-31--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 566 VS 1135
		Counter({'ubloxGnss': 566})
		Counter({'ubloxGnss': 620, 'gpsLocationExternal': 515})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen1E72BBDCED5|2022-09-27--15-55-31--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen1E72BBDCED5|2022-09-27--15-55-31--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 216
***** results for segment regen45B05A80EF6|2022-09-27--15-57-22--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen45B05A80EF6|2022-09-27--15-57-22--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen45B05A80EF6|2022-09-27--15-57-22--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeSinceReset: 1
        liveLocationKalman.timeToFirstFix: 1175
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regen45B05A80EF6|2022-09-27--15-57-22--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regen45B05A80EF6|2022-09-27--15-57-22--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 598 VS 1171
		Counter({'ubloxGnss': 598})
		Counter({'ubloxGnss': 617, 'gpsLocationExternal': 554})
    laikad
    torqued
***** results for segment 376bf99325883932|2022-10-27--13-41-22--1 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/376bf99325883932|2022-10-27--13-41-22--1_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/376bf99325883932|2022-10-27--13-41-22--1_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 654 VS 1322
		Counter({'ubloxGnss': 654})
		Counter({'ubloxGnss': 723, 'gpsLocationExternal': 599})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/376bf99325883932|2022-10-27--13-41-22--1_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/376bf99325883932|2022-10-27--13-41-22--1_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 50
***** results for segment regenC19D899B46D|2022-09-27--15-59-13--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenC19D899B46D|2022-09-27--15-59-13--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenC19D899B46D|2022-09-27--15-59-13--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeSinceReset: 2
        liveLocationKalman.timeToFirstFix: 1174
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenC19D899B46D|2022-09-27--15-59-13--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenC19D899B46D|2022-09-27--15-59-13--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 655 VS 1093
		Counter({'ubloxGnss': 655})
		Counter({'ubloxGnss': 765, 'gpsLocationExternal': 328})
    laikad
    torqued
***** results for segment regenD8F7AC4BD0D|2022-09-27--16-41-45--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenD8F7AC4BD0D|2022-09-27--16-41-45--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenD8F7AC4BD0D|2022-09-27--16-41-45--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 624 VS 1258
		Counter({'ubloxGnss': 624})
		Counter({'ubloxGnss': 689, 'gpsLocationExternal': 569})
    laikad
    torqued
***** results for segment regenFC3F9ECBB64|2022-09-27--16-03-09--0 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenFC3F9ECBB64|2022-09-27--16-03-09--0_locationd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenFC3F9ECBB64|2022-09-27--16-03-09--0_locationd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveLocationKalman.timeSinceReset: 1
        liveLocationKalman.timeToFirstFix: 1152
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenFC3F9ECBB64|2022-09-27--16-03-09--0_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenFC3F9ECBB64|2022-09-27--16-03-09--0_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 587 VS 1282
		Counter({'ubloxGnss': 587})
		Counter({'ubloxGnss': 708, 'gpsLocationExternal': 574})
    laikad
    torqued
        ref: https://commadataci.blob.core.windows.net/openpilotci/regenFC3F9ECBB64|2022-09-27--16-03-09--0_torqued_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/regenFC3F9ECBB64|2022-09-27--16-03-09--0_torqued_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        liveTorqueParameters.totalBucketPoints: 211
***** results for segment 54827bf84c38b14f|2023-01-26--21-59-07--4 *****
    controlsd
    radard
    plannerd
    calibrationd
    dmonitoringd
    locationd
    paramsd
    ubloxd
        ref: https://commadataci.blob.core.windows.net/openpilotci/54827bf84c38b14f|2023-01-26--21-59-07--4_ubloxd_b4a208cb84a99eb15116d2a445c278b00275fdd5.bz2
        new: /tmp/openpilot/selfdrive/test/process_replay/fakedata/54827bf84c38b14f|2023-01-26--21-59-07--4_ubloxd_1c4366ca0ba6b75f4d61a7fc0daf92cb4f9e9354.bz2

        logs are not same length: 611 VS 1332
		Counter({'ubloxGnss': 611})
		Counter({'ubloxGnss': 732, 'gpsLocationExternal': 600})
    laikad
    torqued
```

**Pull request merged**
