### PR TITLE
Static 0xe5 on Honda Bosch

### PR DESCRIPTION
**Pull request by csouers**
Block 0xe5 (Bosch only) and send only static values. Wheel wobble functionality is disabled on vehicles that support it. This important safety change is crucial for Bosch cars because the wobble overrides any torque command on 0xe4 sent by OP (or stock LKAS).

Panda PR for safety. 0xe5 controls wheel wobble on Bosch and also has a bit for braking request during RDM. https://github.com/commaai/panda/pull/515

Opendbc changes are a requirement too https://github.com/commaai/opendbc/pull/250

Has been tested on Civic Hatch and Insight. Waiting for Accord.

### CODE REVIEW

**Comment by csouers** [comment]
Failing replay test because the needed opendbc changes in https://github.com/commaai/opendbc/pull/250

**Comment by pd0wm** [comment]
Can you rebase with master? I merged the opendbc PR.

**Comment by csouers** [comment]
@pd0wm Looks like the panda pr is ready to go too. Just waiting for the merge.

**Comment by csouers** [comment]
Test failing for something unrelated to this PR?

**Comment by pd0wm** [comment]
The test is actually failing for the correct reason. There are unexpected can messaged.

If you change `selfdrive/test/process_replay/ref_commit` with `b33259e2dae9852c58b0507dbb98fb01d8b884b8` it will pass again.

**Comment by csouers** [comment]
> The test is actually failing for the correct reason. There are unexpected can messages being sent out.
> 
> If you change `selfdrive/test/process_replay/ref_commit` with `b33259e2dae9852c58b0507dbb98fb01d8b884b8` it will pass again.

Done!

**Pull request merged**
