### PR TITLE
Honda: add Chinese Odyssey FW versions

### PR DESCRIPTION
**Pull request by MaloneFan**
add a carFW of odyssey_chn

### CODE REVIEW

**Comment by sshane** [comment]
Can you provide a dongle ID for this car?

**Comment by MaloneFan** [comment]
It’s 3261da310f2a657b

**Comment by sshane** [comment]
What year Odyssey is this?

**Comment by MaloneFan** [comment]
> What year Odyssey is this?

It’s 2020.

**Comment by sshane** [comment]
Updated the base branch for you, you were trying to merge into a development branch for the 2022 Odyssey

**Comment by sshane** [comment]
@MaloneFan Can you get a route on this branch with rlogs uploaded?

**Comment by MaloneFan** [comment]
> @MaloneFan Can you get a route on this branch with rlogs uploaded? We need to update the old test route

I don't know how to do and I don't know what's rlogs. Can you give me a reference? Another, I had try the patch-3 at C3 on my car. But, C3 will show "CAN error: check connections".

**Comment by sshane** [comment]
All you need to do is install this branch: https://installer.comma.ai/MaloneFan/patch-3, then drive around to get a route. Put your device on WiFi and let me know when this is done. Then we can add your FW versions!

**Comment by MaloneFan** [comment]
> All you need to do is install this branch: https://installer.comma.ai/MaloneFan/patch-3, then drive around to get a route. Put your device on WiFi and let me know when this is done. Then we can add your FW versions!
> 
> The route will be public, so try to find a parking lot to drive from and end up at.

I got it, thanks. I installed the path-3 and drove my car today morning( 10/30).  The route path is https://useradmin.comma.ai/?onebox=3261da310f2a657b%7C2022-10-30--02-25-28

**Comment by sshane** [comment]
Unfortunately the log files are gone already, so I can't upload them

**Pull request merged**
