### PR TITLE
GMC Acadia: Add lateral feedforward function

### PR DESCRIPTION
**Pull request by Verylukyguy**
This is a duplicate lateral steering tuning improvement for a different model vehicle.

This sigmoidal FeedForward function was previously merged for the GM Volt on PR: https://github.com/commaai/openpilot/pull/22621

OpenPilot v0.8.11-Master, Lanefull 

Route:  e38a02cae1ef1e0c|2021-11-10--17-18-10

### CODE REVIEW

**Comment by Verylukyguy** [comment]
solution

**Comment by qadmus** [comment]
I support this PR, tested by @Verylukyguy , but haven't had time for the proper before/after plots.

**Comment by Verylukyguy** [comment]
Here is another, longer route with fewer interventions:

e38a02cae1ef1e0c|2021-11-13--23-14-13

There is a seemingly random "Steering Temporarily Unavailable" error in the middle, but it recovered immediately.

**Comment by Verylukyguy** [comment]
I was really hoping that this would be approved so it would make it into the next release.   Please

**Comment by adeebshihadeh** [comment]
We haven't reviewed this since it's missing the verification criteria, and it's too late to get this into 0.8.11. Here's the verification criteria:
```
<!-- To verify tuning, capture the following scenarios (broadly, not exactly), with current tune and this tune.
Use the PlotJuggler tuning layout to compare planned versus actual behavior.

Run ./juggle.py <route> --layout layouts/tuning.xml , screenshot the full tab of interest, and paste into this PR.

Longitudinal:
* Maintaining speed at 25, 40, 65mph
* Driving up and down hills
* Accelerating from a stop
* Decelerating to a stop
* Following large changes in set speed
* Coming to a stop behind a lead car

Lateral:
* Straight driving at ~25, ~45 and ~65mph
* Turns driving at ~25, ~45 and ~65mph
-->
```

**Comment by Verylukyguy** [comment]
I tried to help, but I can’t fulfill your requirements and your verification criteria.  Sorry.  I wish that I could help more.  I’ll keep checking back to see when your product can better fulfill its expectations.

**Pull request merged**
