### PR TITLE
Add missing Highlander Hybrid TSS2 fw

### PR DESCRIPTION
**Pull request by kadupitiya**
<!--- ***** Template: Car port *****

Adding a new firmware version for Ecu.esp for the CAR.HIGHLANDERH_TSS2.

The dealership updated the car's firmware due to a recent recall. 

Then I got "Car Unrecognized: Dashcam Mode" error.

After adding the new firmware version (esp: 'fwVersion': b'\x01F152648J4000\x00\x00\x00\x00') to the CAR.HIGHLANDERH_TSS2 dictionary in the values.py, open
is working well again. I tested with master-ci branch.

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Please provide the relevant DongleID/route.

**Comment by kadupitiya** [comment]
Dongle id: 5f040438a009d6cb.
I just tested this on this routeID: 5f040438a009d6cb|2022-04-21--17-01-36.

**Comment by howardlan3** [comment]
Thank you Shane for directing me to this shred. However, I am an average guy with no programming experience. Can anyone walk me through what I need to do to get a working software on my Comma2 for my 2020 Highlander Hybrid? Truly appreciated!

**Comment by ErichMoraga** [comment]
> Thank you Shane for directing me to this shred. However, I am an average guy with no programming experience. Can anyone walk me through what I need to do to get a working software on my Comma2 for my 2020 Highlander Hybrid? Truly appreciated!

Just run the cmds. I have pinned in the #toyota-lexus Discord channel, or see the conversations from Sunday morning where I helped resolve this for multiple people.

**Comment by howardlan3** [comment]
> > Thank you Shane for directing me to this shred. However, I am an average guy with no programming experience. Can anyone walk me through what I need to do to get a working software on my Comma2 for my 2020 Highlander Hybrid? Truly appreciated!
> 
> Just run the cmds. I have pinned in the #toyota-lexus Discord channel, or see the conversations from Sunday morning where I helped resolve this for multiple people.

Is this the page, I couldn't find the response. Thank you in advance. https://discord.com/channels/771493367246094347/771495215570747403

**Comment by ErichMoraga** [comment]
> Is this the page, I couldn't find the response. Thank you in advance. https://discord.com/channels/771493367246094347/771495215570747403

Perhaps you aren't understanding where the pinned messages are, or how to find the #toyota-lexus channel.  It's past 1am here, so this is my final post for now, as it's pretty self-explanatory...
image

**Comment by ElonVampire** [comment]
收到！

**Pull request merged**
