### PR TITLE
Prevent OP engagement when in "Cruise Mode"

### PR DESCRIPTION
**Pull request by Gernby**
This is a fix for a safety issue that I discovered by accident in my 2018 Honda Accord.  If I press and hold the ACC following distance button for a number of seconds, the adaptive component of ACC becomes disabled, so the radar is no longer used to control speed.  However, OP works as usual, which seems very dangerous.  This PR fixes that by ensuring that ACC is fully enabled.

### CODE REVIEW

**Comment by rbiasini** [comment]
nice finding. Makes sense applying this change

**Comment by rbiasini** [comment]
nice finding. Makes sense applying this change. Since it's not 100% sure that it will be an ok change on all cars, I'll merge this internally first.

**Comment by illumiN8i** [comment]
Toyota has this problem too.

**Comment by rbiasini** [comment]
@illumiN8i it's only a problem if the DSU is plugged I assume, right?

**Comment by illumiN8i** [comment]
No, with DSU unplugged this trick can be used to bypass cruise fault and engage anyway without ACC.

**Comment by rbiasini** [comment]
ah, then i needs to be fixed. Good catch.

**Comment by Gernby** [comment]
Why was this closed?

**Comment by rbiasini** [comment]
Because it's merged internally and it will go through the standard release process instead of directly into devel. See my comment ^^

**Comment by Gernby** [comment]
I saw that comment, but wasn't aware of a standard practice to close PR's instead of merging them.  It really kills the fun of contribution if there's no credit for it.

**Comment by rbiasini** [comment]
Well, either it gets merged directly and/or you get credited in the release notes.
What else can we do? For some changes, a deeper validation is required before it goes out to hundreds of users.

**Comment by illumiN8i** [comment]
@rbiasini Not sure how to fix it, but here's a segment showing the press and hold trick being used to bypass cruise fault and engage anyway without ACC on 2018 Toyota Prius Prime b29e3bc918751697|2019-08-04--12-53-50--9

**Comment by Gernby** [comment]
@rbiasini - I see that this fix is in 0.6.3, but not mentioned in the release notes.

**Pull request closed without merging**
