### PR TITLE
CANPacker: assert no undefined signals

### PR DESCRIPTION
**Pull request by sshane**
https://github.com/commaai/opendbc/pull/891

catches https://github.com/commaai/openpilot/pull/28762

### CODE REVIEW

**Comment by sshane** [comment]
```python
.............................................................................................................................................................................................................F.F.                                                                                       [100%]
================================================================================================================================================== FAILURES ===================================================================================================================================================
___________________________________________________________________________________________________________________________ TestCarInterfaces.test_car_interfaces_120_LEXUS_RC_2020 ___________________________________________________________________________________________________________________________
[gw13] linux -- Python 3.8.10 /home/batman/.pyenv/versions/3.8.10/bin/python3.8

a = (<selfdrive.car.tests.test_car_interfaces.TestCarInterfaces testMethod=test_car_interfaces_120_LEXUS_RC_2020>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

../../../../.pyenv/versions/3.8.10/lib/python3.8/site-packages/parameterized/parameterized.py:533: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_car_interfaces.py:19: in test_car_interfaces
    @settings(max_examples=5)
test_car_interfaces.py:70: in test_car_interfaces
    car_interface.apply(CC, 0)
../toyota/interface.py:306: in apply
    return self.CC.update(c, self.CS, now_nanos)
../toyota/carcontroller.py:137: in update
    can_sends.append(create_acc_cancel_command(self.packer))
../toyota/toyotacan.py:54: in create_acc_cancel_command
    return packer.make_can_msg("PCM_CRUISE", 0, values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeError: CANPacker::pack(): undefined signal STANDSTILL_ON in PCM_CRUISE

opendbc/can/packer_pyx.pyx:32: RuntimeError
------------------------------------------------------------------------------------------------------------------------------------------------- Hypothesis --------------------------------------------------------------------------------------------------------------------------------------------------
Falsifying example: test_car_interfaces(
    data=data(...),
    self=<selfdrive.car.tests.test_car_interfaces.TestCarInterfaces testMethod=test_car_interfaces_120_LEXUS_RC_2020>,
    car_name='LEXUS RC 2020',
)
Draw 1: False
Draw 2: {'enabled': False, 'gasDEPRECATED': 0.0, 'brakeDEPRECATED': 0.0, 'steeringTorqueDEPRECATED': 0.0, 'cruiseControl': {'cancel': True, 'resume': False, 'speedOverrideDEPRECATED': 0.0, 'accelOverrideDEPRECATED': 0.0, 'override': False}, 'hudControl': {'speedVisible': False, 'setSpeed': 0.0, 'lanesVisible': False, 'leadVisible': False, 'visualAlert': 'none', 'audibleAlert': 'none', 'rightLaneVisible': False, 'leftLaneVisible': False, 'rightLaneDepart': False, 'leftLaneDepart': False}, 'actuators': {'gas': 0.0, 'brake': 0.0, 'steer': 0.0, 'steeringAngleDeg': 0.0, 'accel': 0.0, 'longControlState': 'off', 'speed': 0.0, 'curvature': 0.0, 'steerOutputCan': 0.0}, 'activeDEPRECATED': False, 'rollDEPRECATED': 0.0, 'pitchDEPRECATED': 0.0, 'actuatorsOutput': {'gas': 0.0, 'brake': 0.0, 'steer': 0.0, 'steeringAngleDeg': 0.0, 'accel': 0.0, 'longControlState': 'off', 'speed': 0.0, 'curvature': 0.0, 'steerOutputCan': 0.0}, 'latActive': False, 'longActive': False, 'orientationNED': [], 'angularVelocity': [], 'leftBlinker': False, 'rightBlinker': False}
___________________________________________________________________________________________________________________________ TestCarInterfaces.test_car_interfaces_115_LEXUS_IS_2018 ___________________________________________________________________________________________________________________________
[gw7] linux -- Python 3.8.10 /home/batman/.pyenv/versions/3.8.10/bin/python3.8

a = (<selfdrive.car.tests.test_car_interfaces.TestCarInterfaces testMethod=test_car_interfaces_115_LEXUS_IS_2018>,)

    @wraps(func)
    def standalone_func(*a):
>       return func(*(a + p.args), **p.kwargs)

../../../../.pyenv/versions/3.8.10/lib/python3.8/site-packages/parameterized/parameterized.py:533: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_car_interfaces.py:19: in test_car_interfaces
    @settings(max_examples=5)
test_car_interfaces.py:70: in test_car_interfaces
    car_interface.apply(CC, 0)
../toyota/interface.py:306: in apply
    return self.CC.update(c, self.CS, now_nanos)
../toyota/carcontroller.py:137: in update
    can_sends.append(create_acc_cancel_command(self.packer))
../toyota/toyotacan.py:54: in create_acc_cancel_command
    return packer.make_can_msg("PCM_CRUISE", 0, values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeError: CANPacker::pack(): undefined signal STANDSTILL_ON in PCM_CRUISE

opendbc/can/packer_pyx.pyx:32: RuntimeError
------------------------------------------------------------------------------------------------------------------------------------------------- Hypothesis --------------------------------------------------------------------------------------------------------------------------------------------------
Falsifying example: test_car_interfaces(
    data=data(...),
    self=<selfdrive.car.tests.test_car_interfaces.TestCarInterfaces testMethod=test_car_interfaces_115_LEXUS_IS_2018>,
    car_name='LEXUS IS 2018',
)
Draw 1: False
Draw 2: {'enabled': False, 'gasDEPRECATED': 0.0, 'brakeDEPRECATED': 0.0, 'steeringTorqueDEPRECATED': 0.0, 'cruiseControl': {'cancel': True, 'resume': False, 'speedOverrideDEPRECATED': 0.0, 'accelOverrideDEPRECATED': 0.0, 'override': False}, 'hudControl': {'speedVisible': False, 'setSpeed': 0.0, 'lanesVisible': False, 'leadVisible': False, 'visualAlert': 'none', 'audibleAlert': 'none', 'rightLaneVisible': False, 'leftLaneVisible': False, 'rightLaneDepart': False, 'leftLaneDepart': False}, 'actuators': {'gas': 0.0, 'brake': 0.0, 'steer': 0.0, 'steeringAngleDeg': 0.0, 'accel': 0.0, 'longControlState': 'off', 'speed': 0.0, 'curvature': 0.0, 'steerOutputCan': 0.0}, 'activeDEPRECATED': False, 'rollDEPRECATED': 0.0, 'pitchDEPRECATED': 0.0, 'actuatorsOutput': {'gas': 0.0, 'brake': 0.0, 'steer': 0.0, 'steeringAngleDeg': 0.0, 'accel': 0.0, 'longControlState': 'off', 'speed': 0.0, 'curvature': 0.0, 'steerOutputCan': 0.0}, 'latActive': False, 'longActive': False, 'orientationNED': [], 'angularVelocity': [], 'leftBlinker': False, 'rightBlinker': False}
=========================================================================================================================================== short test summary info ===========================================================================================================================================
FAILED test_car_interfaces.py::TestCarInterfaces::test_car_interfaces_120_LEXUS_RC_2020 - RuntimeError: CANPacker::pack(): undefined signal STANDSTILL_ON in PCM_CRUISE
FAILED test_car_interfaces.py::TestCarInterfaces::test_car_interfaces_115_LEXUS_IS_2018 - RuntimeError: CANPacker::pack(): undefined signal STANDSTILL_ON in PCM_CRUISE
======================================================================================================================================= 2 failed, 207 passed in 18.90s ========================================================================================================================================
batman@workstation-shane:~/openpilot/selfdrive/car/tests$
```

**Comment by sshane** [comment]
@adeebshihadeh should we revert this since it throws an exception, and there's a non-zero chance our fuzzy tests won't catch something in the future.

**Comment by adeebshihadeh** [comment]
Yeah let's revert for now, but I'd like really good testing around this soon.

**Comment by sshane** [comment]
Reverted https://github.com/commaai/openpilot/pull/29013

**Pull request merged**
