### PR TITLE
camerad: remove webcam + replay cameras

### PR DESCRIPTION
**Pull request by adeebshihadeh**

### CODE REVIEW

**Comment by geohot** [comment]
Can we also remove the rgb_to_yuv transform?

**Comment by adeebshihadeh** [comment]
Yes, I'm gonna do a big camerad cleanup. I just don't want to remove webcam support without a replacement.

**Comment by geohot** [comment]
Oh I'm fine with just removing it. If people are using it, they can fork or write the simple python one.

**Comment by JasonJShuler** [comment]
Just to clarify - is this breaking the ability to run OP on PCs?

**Comment by MikeBusuttil** [comment]
Hey @adeebshihadeh (or anyone that knows)
- what was the motivation behind removing the webcam?
- where can I find the existing simple Python one that @geohot referenced above?

Context: I plan on tackling #24590 as my first issue

**Pull request merged**
