### PR TITLE
cleanup .gitattributes

### PR DESCRIPTION
**Pull request by gregjhogan**
should be fine to remove all of these?

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
LGTM, maybe we should block certain file types with pre commit hooks? It is somewhat easy to check a big file into master and get it stuck in the history if it's not caught quickly.

**Comment by adeebshihadeh** [comment]
Added a precommit for large files: #23505

**Comment by gregjhogan** [comment]
check out partial clone, super useful as the history grows (even without accidental large files slipping in)
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

`git clone --filter=blob:none git@github.com:commaai/openpilot.git` gives you
```
$ du -sh ~/tmp/openpilot/.git/objects/
93M	/home/greg/tmp/openpilot/.git/objects/
```
vs a non-partial clone
```
$ du -sh ~/openpilot/.git/objects/
1.7G	/home/greg/openpilot/.git/objects/
```
with partial clone you still have access to the full history, it just pulls objects  on-demand

**Comment by adeebshihadeh** [comment]
Shall we put this in the instructions in tools/?

**Pull request merged**
