### PR TITLE
refactor sensors_qcom

### PR DESCRIPTION
**Pull request by deanlee**
1. new struct `SensorState`
2. remove hardcoded value of sensor handles,  get them from `get_sensors_list`.
3. call `setDeay` after reactivate sensors
4. ~try to solve the following problem(sensor.which() will return 0(ACCELERATION) if the message is empty):~
https://github.com/commaai/openpilot/blob/59698344a2c1f6557b06485de1dcf296ec5eb542/selfdrive/ui/ui.cc#L216-L217
4. use callback function to build sensor message.

### CODE REVIEW

**Comment by pd0wm** [comment]
regarding 4. That happened while running sensors_qcom2. Also pretty sure it's on the receiving end, I can run multiple instances of ui at the same time, and only one will crash.

**Comment by deanlee** [comment]
oic

**Comment by adeebshihadeh** [comment]
I hesitate to merge these refactor PRs that don't solve any problems for daemons that are stable, small, and self-contained. The QCOM sensor daemon is ~230 lines and works well. What's the benefit of merging this? Does it use less CPU?

**Comment by deanlee** [comment]
@pd0wm The reason that `sensorEvents` reads an empty list may be that the number of read connections exceeds the limit (NUM_READERS) :
https://github.com/commaai/cereal/blob/97bfe99980a3ef58e07eb8006ac5e59bf83ad986/messaging/msgq.hpp#L27-L29

**Comment by deanlee** [comment]
> regarding 4. That happened while running sensors_qcom2. Also pretty sure it's on the receiving end, I can run multiple instances of ui at the same time, and only one will crash.

it's fixed in #21427

**Pull request closed without merging**
