### PR TITLE
Hyundai: Kona 2nd Gen Port

### PR DESCRIPTION
**Pull request by royjr**
> [!NOTE]
> The 2024 Kona may be similar to [2024 Elantra](https://github.com/commaai/openpilot/pull/30219), [~~2024 Sonata~~](https://github.com/commaai/openpilot/pull/30561), [2024 Sonata](https://github.com/commaai/openpilot/pull/31992), [2024 Sorento](https://github.com/commaai/openpilot/pull/32793)

**Checklist**
- [x] add to `RELEASES.md`
- [x] generate `DOCS.md`
- [x] add specs to `interface.py`
- [x] add fingerprint to `values.py`
- [x] add default values to `override.yaml`
- [ ] route (stock)
- [ ] route (openpilot)
- [ ] add test route to `routes.py`
- [x] harness: [Hyundai L](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)
- [x] architecture: CAN-FD

**Confirm**
- [x] Hyundai L is the right harness, rule out Hyundai P (HDA vs non-HDA2)
- [x] radar/camera scc
- [x] _LAMP_ALT signals
- [x] sport/snow modes

**Issues**
- [ ] "Check Lane Safety system" constant fault when not standstill, lane change, engaged
- [ ] latitude: delayed steering response (tuning/scaling)
- [ ] "Consider taking a break"
- [ ] longitude: clicking actuator noises (may be experimental mode only)
- [x] latitude: oversteering
- [x] longitude: harsh braking

### CODE REVIEW

**Comment by sshane** [comment]
Can you post these routes?

- stock route (openpilot toggle disabled) with both stock lane centering and stock lane keep when leaving the lane
  - try to get as many states as possible: entering/leaving standstill, etc.
- with openpilot, marking with a bookmark the exact moment it first faults and shows errors on the dash, and then when it shows the other various undesired messages

**Comment by royjr** [comment]
81e77f6b5f80e624|2023-12-11--19-52-57 - stock
1,19:54:00-1,19:54:14 - purposely nudging out of lane
4,19:57:06 - hands on steering warning
4,19:57:18 - hands on steering warning (second stage)
4,19:57:51 - nice curve

81e77f6b5f80e624|2023-12-11--20-00-49 - stock
2,20:03:24 - curve
9,20:09:58 - curve

81e77f6b5f80e624|2023-12-11--20-17-22 - openpilot
0,20:18:03 - sharp bend
3,20:20:32 - fault on engage
6,20:23:49 - nice curve
9,20:26:55 - fault on engage
9,20:27:10 - fault on engage
9,20:27:22 - fault on engage
10,20:27:46 - fault on lkas button press

81e77f6b5f80e624|2023-12-11--20-31-33 - openpilot
2,20:34:18-4,20:36:20 - lane change tests
4,20:36:30 - nice curve

**Comment by royjr** [comment]
No visible change `81e77f6b5f80e624|2023-12-12--00-04-42`

**Comment by royjr** [comment]
Maybe similar to https://github.com/commaai/openpilot/pull/30575#issuecomment-1854285579
Screenshot from 2023-12-20 00-26-21

**Comment by royjr** [comment]
need to check lkas fault when switching lanes while disengaged

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
