### PR TITLE
RAV4 2022: Add missing engine fw

### PR DESCRIPTION
**Pull request by sshane**
From 909a5635aa370818|2022-07-12--09-28-44

### CODE REVIEW

**Comment by sshane** [comment]
@funiflips Can you try to replace your USB cable and/or record a video of what's happening on the dash? openpilot sees no issues

**Comment by funiflips** [comment]
I’ll see if I can find another cable and I attached a video of the dash

Uploading IMG_1008.MOV…

**Comment by sshane** [comment]
Make sure you let the video fully upload, I'd try again

**Comment by funiflips** [comment]
https://user-images.githubusercontent.com/101668376/178598390-eff93d68-d3f8-4694-a6f1-e751c2e1fcc1.MOV

**Comment by funiflips** [comment]
Here’s a longer video

https://vimeo.com/729374064

**Comment by sshane** [comment]
Does this happen without the comma device plugged in? Does it happen immediately after startup of the comma three, or exists before the comma three starts? A video of the car off to started with audio and a view of the C3 would be helpful

**Comment by funiflips** [comment]
Video of startup

https://vimeo.com/729389733

**Comment by sshane** [comment]
Yeah I would try replacing your cable as the first course of action, you're missing a lot of messages on bus 1. And your car should be no different as any of the other 2022 RAV4s

**Comment by funiflips** [comment]
Swapped out the cable and it worked! You’re a wizard Shane. Thank you for all of your help! I really appreciate it

**Comment by sshane** [comment]
Great! Can you connect your device to WiFi to upload a route with it engaged and driving?

**Comment by funiflips** [comment]
Yeah I did a short test drive earlier. Let me know if you need me to do another drive

**Comment by sshane** [comment]
Logs look good! Let me know if there's any other issues

**Comment by funiflips** [comment]
Will do, thanks again!

**Comment by funiflips** [comment]
Hey @ sshane if I get a new 2022 rav4, do we need to fingerprint again?

**Comment by funiflips** [comment]
Hi @sshane I got a new 2022 rav4 and it’s in dashcam mode again. Can you help me fingerprint? I’m about to go for a quick drive and upload it

**Comment by funiflips** [comment]
My dongle is 909a5635aa370818

**Pull request merged**
