### PR TITLE
visiond: replace wiggly model with non wiggly model

### PR DESCRIPTION
**Pull request by geohot**
Retrained the temporal model on the same dataset but added more dropout. This fixes the wiggle issue, potentially at the expense of responsiveness. Comment here on which model you like the best and issues with them:

1. 0.5.3 model
2. 0.5.4 model
3. 0.5.4-nowiggle model

### CODE REVIEW

**Comment by ch4se** [comment]
Wiggles are better because you can see that OP is actually working hard at making decisions

**Comment by jfrux** [comment]
I tend to agree Chase.
I do think we could maybe do something with it… but I’m not sure how we could get the best of both worlds.

**Comment by geohot** [comment]
From a purely visual perspective, I would not say wiggles inspire confidence.

**Comment by ch4se** [comment]
Yeah I wouldn’t say wiggles inspire confidence, but it at least gives you an idea of when the model actually is confident. 

Wiggly model probably makes the user pay more attention, people seem to be overly confident in the system.

**Comment by openmechanics** [comment]
> Yeah I wouldn’t say wiggles inspire confidence, but it at least gives you an idea of when the model actually is confident.
> 
> Wiggly model probably makes the user pay more attention, people seem to be overly confident in the system.

agree^ lol

**Comment by jeankalud** [comment]
Tested both 0.5.4 with and without wiggle. I prefer the no_wiggle version personally. 

I liked seeing the wiggle version trying to find the lines but it doesn't inspires confidence. Also, compared to the previous 0.5.3 version I feel it should be given less authority when confidence level is low. Right now it tends to turn right-left back and forth in some no lines conditions. This should be smoothed out imho.

I REALLY appreciate the increased turn angle limit, its amazing, so manu thanks for this.

**Comment by zeeexsixare** [comment]
Both versions of 0.5.4 drive similarly for me.  I agree that wiggles don't inspire confidence.  However, the white lines , or the green path line could potentially be turned orange or red dynamically if we want to "feel" how confident the model is.  This way we can remove the wiggles but retain model confidence.

**Comment by pjlao307** [comment]
no-wiggle feels more "natural" to me on surface streets.  On highway it seems very similar.

**Comment by ewumnrr** [comment]
Works well, lane detection is more stable. All in all an improvement on local roads and gives very solid highway performance.

**Comment by jfrux** [comment]
image
RIP

**Pull request merged**
