### PR TITLE
add china golf 7.5 values

### PR DESCRIPTION
**Pull request by dingyf12593**
china golf 7.5 values

### CODE REVIEW

**Comment by pd0wm** [comment]
Can you add the missing values the the original golf fingerprint?

**Comment by dingyf12593** [comment]
> Can you add the missing values the the original golf fingerprint?

Always modify values.py to add my golf fingerprint , Sometimes restart the device and the files are restored

**Comment by pd0wm** [comment]
I mean, can you merge the missing values in the existing fingerprint on the line above and submit that as a PR?

**Comment by dingyf12593** [comment]
> I mean, can you merge the missing values in the existing fingerprint on the line above and submit that as a PR?

Sorry, don't understand your mean, try to merge the values in the one line?😂

**Pull request closed without merging**
