### PR TITLE
Honda Steering Improvements

### PR DESCRIPTION
**Pull request by gregjhogan**
Move steering params to CarParams, use interpolation to simplify logic, and lower STEER_MAX to eliminate dead zone for vehicles we know where the dead zone starts (see #946)

### CODE REVIEW

**Comment by VirtuallyChris** [comment]
Tested this PR with the most recent eps_modified values, and it does an amazing job of preserving stock functionality while allowing for torque ramp-up when necessary. Kept openpilot operation smooth as butter on straights and even on steep turns while having none of the wheel wobble that I've found hard to tune away with previous methods. Huge thumbs up from me Greg!

**Comment by geohot** [comment]
Can we get this merged?

**Comment by gregjhogan** [comment]
need to figure out the appropriate adjustment to kp/ki/kf

**Comment by ffhspa** [comment]
Can we expect this changes with next Release 0.7.3? 
I'm sure all Honda users are waiting for this improvement. 
Thanks a lot!

**Comment by gregjhogan** [comment]
found today that reverse interp over fw table values is strictly worse, and stretching out the tail end of the range is a significant improvement

there is now a [script](https://github.com/commaai/openpilot/blob/01f157312226e05295b38d3a34fd443a77a8edf4/selfdrive/debug/internal/measure_steering_accuracy.py) that quantifies steering error at different angles and we have things tuned extremely well for civic (numbers below)
```
angle:  0 | error: 0.17 | =: 80% | +:  4% | -: 14% | count: 1090
angle:  1 | error: 0.20 | =: 78% | +: 14% | -:  7% | count:  905
angle:  2 | error: 0.23 | =: 76% | +: 11% | -: 12% | count:  363
angle:  3 | error: 0.25 | =: 78% | +:  8% | -: 12% | count:  353
angle:  4 | error: 0.28 | =: 69% | +: 16% | -: 14% | count:  177
angle:  5 | error: 0.39 | =: 69% | +: 17% | -: 13% | count:  147
angle:  6 | error: 0.37 | =: 58% | +: 21% | -: 19% | count:  229
angle:  7 | error: 0.43 | =: 60% | +: 24% | -: 14% | count:  223
angle:  8 | error: 0.45 | =: 50% | +: 24% | -: 24% | count:  193
```

**Comment by ffhspa** [comment]
I merged your PR in to my Fork and made a test drive. 
I think there is a improvement in Steering, at least thats my Feeling. 
It was a short drive, if you need more data, pls let me know: 

angle:  0 | error: 2.11 | =: 64% | +: 16% | -: 19% | count:   42
angle:  1 | error: 1.58 | =: 64% | +: 21% | -: 14% | count:   92
angle:  2 | error: 3.88 | =: 55% | +: 34% | -: 10% | count:   29
angle:  3 | error: 3.46 | =: 39% | +: 39% | -: 21% | count:   23
angle:  4 | error: 4.42 | =: 29% | +: 58% | -: 11% | count:   17
angle:  5 | error: 3.32 | =: 18% | +: 36% | -: 45% | count:   11
angle:  6 | error: 6.58 | =:  9% | +: 45% | -: 45% | count:   11
angle:  7 | error: 4.02 | =: 18% | +: 45% | -: 36% | count:   11
angle:  8 | error: 5.48 | =:  0% | +: 16% | -: 83% | count:    6
angle:  9 | error: 7.82 | =:  0% | +: 20% | -: 80% | count:    5
angle: 10 | error: 10.90 | =:  0% | +: 14% | -: 85% | count:    7
angle: 11 | error: 5.89 | =: 13% | +:  0% | -: 86% | count:   29
angle: 12 | error: 5.78 | =:  0% | +: 75% | -: 25% | count:    4
angle: 13 | error: 8.36 | =:  0% | +: 88% | -: 11% | count:    9
angle: 14 | error: 7.51 | =:  0% | +: 93% | -:  6% | count:   16

Here are changes i made to include your PR in my Fork, my Car is FP as CAR.CIVIC_BOSCH_DIESEL

https://github.com/ffhspa/openpilot/commit/af57aed3a38f4abc2071956723aa6de404bc2e0f

If you have any information to improve it i would be happy!

Thanks a lot!

**Comment by gregjhogan** [comment]
@ffhspa you want to drive for a lot longer (10 min is a good start) to get a high number of samples so the error numbers are statistically meaningful.  The angle error numbers that I have achieved in a civic and cr-v near zero degrees is 0.2 or less driving at 60-70 mph.  The script is most useful when making tuning changes and driving the same road in the same conditions with different values (if the angle error numbers go down you know things are improving).

**Comment by gregjhogan** [comment]
also note that these changes only improve the civic (not bosch) and cr-v, so people with other vehicles will need to determine if they have a dead zone at the end of the request range and submit a separate PR

**Pull request merged**
