### PR TITLE
Added the fingerprint for HighLander LE Plus

### PR DESCRIPTION
**Pull request by srnand**
Created a 106 message fingerprint for the lastest 2018 Highlander LE Plus.

### CODE REVIEW

**Comment by rbiasini** [comment]
@srnand , if you send me a cabana link of one of your driver, I'll refactor this.

**Comment by srnand** [comment]
@rbiasini I didn't do the DBC part yet. I do not have access to the car for some time. But I will do that as soon as I get access to the car.

**Comment by rbiasini** [comment]
@srnand , no need for dbc changes I think. Just need to add the new fingerprint to the list of the Highlanders.

**Comment by zeeexsixare** [comment]
@srnand I recommend not creating a new car model for this and instead just add it to the Highlander ICE (non-hybrid).  Try putting it under my 2017 Highlander ICE Limited

**Comment by rbiasini** [comment]
issues did not get resolved. closing

**Pull request closed without merging**
