### PR TITLE
WIP: Subaru preglobal models support

### PR DESCRIPTION
**Pull request by martinl**
**Checklist**

- [x] added to README
  - [x] Outback 2015-18
  - [x] Forester 2017-18
  - [x] Legacy 2015-18
  - [x] Outback 2019
- [ ] test route added to [test_car_models](../blob/master/selfdrive/test/test_car_models.py)
  - [x] Outback 2015-18
  - [x] Forester 2017-18
  - [x] Legacy 2015-18
  - [ ] Outback 2019
- [ ] route with openpilot: 
  - [x] Outback 2015-18: 5ab784f361e19b78|2020-06-08--16-30-41
  - [x] Forester 2017-18: 95441c38ae8c130e|2020-06-08--12-10-17
  - [x] Legacy 2015-18: df5ca7660000fba8|2020-06-16--17-37-19
  - [ ] Outback 2019
- [ ] route with stock system:
  - [ ] Outback 2015-18: 5ab784f361e19b78|2020-07-01--20-40-39
  - [ ] Forester 2017-18:
  - [x] Legacy 2015-18: df5ca7660000fba8|2020-07-01--06-53-52
  - [ ] Outback 2019:

This PR adds support for Subaru preglobal models. All credit goes to @bugsy924. 

Prerequisites
- opendbc
  - [x] https://github.com/commaai/opendbc/pull/260
  - [x] https://github.com/commaai/opendbc/pull/270
  - [x] https://github.com/commaai/opendbc/pull/278
- panda
  - [x] https://github.com/commaai/panda/pull/532
  - [ ] https://github.com/commaai/panda/pull/564

TODO
- [ ] update submodule references
- [ ] merge commented out overlapping FPv1 fingerprints in values.py

PR has been tested on
- Subaru Forester 2017 (Nougat)
- Subaru Forester 2018 (Oreo)
- Subaru Legacy 2018 (something_original_)
- Subaru Outback 2015 (Bugsy)
- Subaru Outback 2017 (Anthony)
- Subaru Outback 2019 (jp)

### CODE REVIEW

**Comment by geohot** [comment]
Submodules seem wrong. And can you add the cars to the README?

**Comment by geohot** [comment]
submodules still seem to have the wrong commits. If you need submodule updates, can you submit PRs and reference them here?

**Comment by martinl** [comment]
Updated the submodule references and readme. Prerequisite panda and opendbc PR-s are referenced in the first comment above

**Comment by mkrupczak3** [comment]
👀

**Comment by martinl** [comment]
Added replay tests for Outback 2017 (5ab784f361e19b78|2020-06-08--16-30-41)

**Comment by martinl** [comment]
Added replay tests for Forester (95441c38ae8c130e|2020-06-08--12-10-17) and Legacy (df5ca7660000fba8|2020-06-16--17-37-19)

**Comment by adeebshihadeh** [comment]
This will need a panda PR as well to ship the SUBARU_LEGACY with the signed firmware. https://github.com/commaai/panda/blob/master/board/safety.h#L253

**Comment by martinl** [comment]
All tests should pass once panda and Outback 2019 dbc PR are merged and replay tests are added on server side. I'll see if I can merge any of the commented out overlapping FPv1 fingerprints to existing ones in values.py

**Comment by adeebshihadeh** [comment]
Closing as this has been broken up per-model starting with #1805

**Pull request closed without merging**
