### PR TITLE
WIP: 2017 Toyota Highlander port

### PR DESCRIPTION
**Pull request by vanillagorillaa**

### CODE REVIEW

**Comment by Glidepathuav** [comment]
I have a 2017 Highlander. Toyota giraffe installed :-) and Panda working overtime tonight. 
*cheers*

**Comment by Glidepathuav** [comment]
What the heck! Prius is down with bad Navi. 3k miles go figure. Renting 2017 Camry.

**Comment by vanillagorillaa** [comment]
@Glidepathuav Please keep discussion in the PR strictly to Highlander

**Comment by vanillagorillaa** [comment]
@rbiasini going to close this so that @ConservativeEconomist can open once he has completed the safety tests.

**Pull request closed without merging**
