### PR TITLE
Job summaries for UI tests

### LINKED ISSUE #31007: [$500 bounty] Post UI screenshots on PRs that modify the UI
We have a CI job that generates a bunch of UI screenshots in various states. The goal of this bounty is to get those screenshots posted as a comment to PRs:
* only comment if `selfdrive/ui/` has changes in the PR
* comment gets updated when new commits are pushed
* must be formatted nicely (e.g. doesn't take up the whole screen). maybe put them in a table?

https://github.com/commaai/openpilot/blob/c9531b463a6cb4a2a56792046fd69f9041006d81/.github/workflows/selfdrive_tests.yaml#L320

### PR DESCRIPTION
**Pull request by thenhnn**
Add fancy job summaries with screenshots.

TODO:
- [x] Find place (CDN, etc) for storing screenshots.
- [ ] Create restricted Azure token for storing screenshots outside of commaai/openpilot. (@jnewb1)

Depends on #31996
Closes #31007

### CODE REVIEW

**Comment by thenhnn** [comment]
I'm waiting for #31996......

@jnewb1

**Comment by thenhnn** [comment]
@jnewb1 is there any way to allow access to azure from ci from prs?

**Comment by adeebshihadeh** [comment]
> @jnewb1 is there any way to allow access to azure from ci from prs?

Unfortunately, no. Can we not just upload them as attachments to a comment like a person can?

**Comment by thenhnn** [comment]
> > @jnewb1 is there any way to allow access to azure from ci from prs?
> 
> Unfortunately, no. Can we not just upload them as attachments to a comment like a person can?

We can't. There's no official documentation from GitHub about uploads to their CDN + it's very rate-limited.

**Pull request closed without merging**
