### PR TITLE
Optimize capnp

### PR DESCRIPTION
**Pull request by adeebshihadeh**
Follow [capnp best practices](https://capnproto.org/cxx.html#tips-and-best-practices) in hopes of saving a bit of CPU in each process.

### CODE REVIEW

**Comment by deanlee** [comment]
x.y is 3x-4x faster than reader.x.y in my tests

**Comment by adeebshihadeh** [comment]
@deanlee do you see any other best practices we’re currently violating? pycapnp seems to make up a decent amount of the CPU usage in our python processes

**Comment by adeebshihadeh** [comment]
Not merging as-is. This doesn't have a significant impact on performance, and it's less readable.

**Comment by deanlee** [comment]
maybe we should find or create a capnp's compiler plugin to compile  schemas to cython.

**Comment by adeebshihadeh** [comment]
This still makes very little difference. I think the way to go is optimizing pycapnp for cheap encoding (currently it makes a few copies) or writing something in Sub/PubMaster to serialize capnp bytes to python dicts for cheap read/write, because currently we're paying for read/write and serialization.

**Pull request closed without merging**
