### PR TITLE
prevent cloudlog spam in tmux a unless manager isn't doing its job

### PR DESCRIPTION
**Pull request by AskAlice**
so much dev friction with this one honestly.

May I suggest, if you don't like the way this works, log when a process dies only, and prevent spam entirely?

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What problem does this solve?

**Comment by AskAlice** [comment]
@adeebshihadeh if you're developing openpilot, and you get a traceback, the tmux buffer probably fills up 100x slower in comparison, which is great when you get a full screen disengage alert on the highway and feel like pulling over to send the logs back, or just general sanity when you're testing code within a vehicle. I've lost a few juicy tracebacks just because the buffer fills up with these useless messages

**Comment by pd0wm** [comment]
Should we just increase the tmux traceback in neos? @jyoung8607 can we do something like 7200 llines? That should be enough for an hour.

**Comment by jyoung8607** [comment]
@AskAlice, right now we value the heartbeat in the logs for a few reasons, but I'm going to increase the tmux scrollback buffer, and @pd0wm and I are talking about making it more convenient for community developers to capture tmux console output to disk. Stay tuned.

**Comment by jyoung8607** [comment]
> Should we just increase the tmux traceback in neos? @jyoung8607 can we do something like 7200 llines? That should be enough for an hour.

Done: https://github.com/commaai/eon-neos-builder/pull/26/commits/1aea85e47001740aa65c7018a45488233a1e13a7

**Comment by AskAlice** [comment]
beautiful. thanks. I knew you guys had a better solution, i just wanted you to have it on your mind as you're thinking about updating neos

**Pull request closed without merging**
