### PR TITLE
ui/onroad: move duplicated code to `drawIcon()`

### PR DESCRIPTION
**Pull request by deanlee**
The UI is exactly the same as before
before
Screenshot 2023-07-26 14:06:38
after
Screenshot 2023-07-26 14:09:20

### CODE REVIEW

**Comment by sshane** [comment]
maybe put it into a base class? or do you think this is cleaner?

**Comment by deanlee** [comment]
think this is cleaner

**Comment by sshane** [comment]
it looks like this breaks something about the circle background (straight line on top and left)

Old:
image


New:
image

**Comment by deanlee** [comment]
fixed

**Comment by sshane** [comment]
ty!

**Pull request merged**
