### PR TITLE
Setup a PR review bot

### PR DESCRIPTION
**Pull request by guhitb**
Created a PR review bot. It does the following:
1. Marks new PRs with the `bot-review` label and sets it to draft status.
2. Checks to see if the PR contains the elements of a PR Template (from `.github/pull_request_template.md`).
3. If PR matches a template, it removes the `bot-review` label and removes the PR from draft status.

The bot determines if a template has been used by looking at the `**bolded headings**`.  It checks each known template against the body of the pull request.

Editing the pull request body causes the PR review bot to run again.

Issue: https://github.com/commaai/openpilot/issues/30715

### CODE REVIEW

**Comment by jnewb1** [comment]
do you have some examples of it working on your fork?

**Comment by guhitb** [comment]
Here are some examples.

**No template found, PR failed**

https://github.com/commaai/openpilot/assets/147658676/9b2c7979-c5bd-4618-8495-218166bf978a

**Template found, PR passed**

https://github.com/commaai/openpilot/assets/147658676/74b85266-62b3-4bff-adbd-4af028c6a882


**PR is edited, status is updated**

https://github.com/commaai/openpilot/assets/147658676/51a42c3b-dd79-49d2-a6cf-30bd1f7216be

**Comment by jnewb1** [comment]
does pygithub have an api for doing stuff like converting to draft, getting pull request id, etc?

**Comment by guhitb** [comment]
As far as I could discover, draft status cannot be be modified by the REST endpoint that PyGithub uses internally.

Only the GraphQL endpoint can convert a PR to and from a draft. The required pull request id can only be obtained through the GraphQL endpoint.

**Comment by adeebshihadeh** [comment]
Thanks for the PR! 

This is bigger and more custom than I was expecting? This is pretty generic stuff, and it's important that it has basically no maintenance cost (i.e. in the next year, we don't have to touch it to get it working again). Are there existing Actions we can use instead? The ideal thing is a single action, but perhaps there's a few different ones we can chain together. There's also [github-script](https://github.com/actions/github-script) which I imagine would simplify this a bit.

**Review by adeebshihadeh — CHANGES_REQUESTED** [review]
Thanks for the PR! 

This is bigger and more custom than I was expecting. This is pretty generic stuff, and it's important that it has basically no maintenance cost (i.e. in the next year, we don't have to touch it to get it working again because some endpoint changed or something). Are there existing Actions we can use instead? The ideal thing is a single action, but perhaps there's a few different ones we can chain together. There's also [github-script](https://github.com/actions/github-script) which I imagine would simplify this a bit.

**Pull request closed without merging**
