### PR TITLE
Sidebar: repaint only when properties updated

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Does this actually save any CPU?  When the sidebar isn't visible, it should only update the state without redrawing, which should be cheap.

**Comment by deanlee** [comment]
Just want to make it consistent with the update logic of other widgets (update only when visible), free is always better than cheap.

**Comment by deanlee** [comment]
If you think the added complexity is not worth it, I will remove the `isVisible` part

**Comment by deanlee** [comment]
If you think the added complexity is not worth it, I will remove the isVisible part

**Comment by adeebshihadeh** [comment]
I don't think this PR is worth merging as is, but I like the idea. There's probably a nice way to setup the properties in Qt, so it'll automatically repaint when certain properties are changed. Let's also remove the visible check.

**Pull request merged**
