### PR TITLE
Update ci weekly report summary

### LINKED ISSUE #32902: CI: improve `CI_weekly_report` generation
continuation of #32869 should match the criteria that were set there:

> Suggestions for improving the report:
> 
>     * replace counts with pass/fail percentages, plus total runs on top
> 
>     * color the background of each "Job" cell with the pass percent, gradient from green to red
> 
>     * the actions links in the table aren't links
> 
>     * maybe also replace the text for the links with "here" or something short so the table doesn't change size when opening the dropdown

### PR DESCRIPTION
**Pull request by signed-long**
Closes #32902

https://github.com/signed-long/openpilot/actions/runs/9803187594/attempts/1#summary-27069501960

### CODE REVIEW

**Comment by maxime-desroches** [comment]
Maybe in the case where a job failed many times you could add the logs in a dropdown so the table is still viewable (unless it is already formatted correctly)

**Comment by signed-long** [comment]
> Maybe in the case where a job failed many times you could add the logs in a dropdown so the table is still viewable (unless it is already formatted correctly)

Yeah the formatting gets messed up a bit with lots of failures, used a different approach to template the html and fixed it. 
https://github.com/signed-long/openpilot/actions/runs/9817056181/attempts/1#summary-27108271075

**Comment by maxime-desroches** [comment]
Instead of just having 'log', can you make it such that it shows 'Failure #<job_number>"

**Comment by signed-long** [comment]
> Instead of just having 'log', can you make it such that it shows 'Failure #<job_number>"

Like `Failure #1`, `Failure #2`, `Failure #3`. Or with the job ID `Failure #27107976960` ?

**Comment by maxime-desroches** [comment]
If the run number 3 of the static_analysis test failed, it should show something like 'log for run #3' or 'Failure #3'

**Comment by signed-long** [comment]
> If the run number 3 of the static_analysis test failed, it should show something like 'log for run #3' or 'Failure #3'

I like `Log for run #3` so it doesn't sound like it's the 3rd failure

https://github.com/signed-long/openpilot/actions/runs/9849555812/attempts/1#summary-27193413442

**Comment by maxime-desroches** [comment]
Looks great now. Just apply the above reviews and we should be good to merge!

**Comment by signed-long** [comment]
> Looks great now. Just apply the above reviews and we should be good to merge!

Awesome! That was made with the same code as the last commit so good to go

**Pull request merged**
