### PR TITLE
Mazda: get blinker state from switch

### PR DESCRIPTION
**Pull request by Jafaral**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
What's the difference? Can you post a route?

**Comment by sshane** [comment]
Hmm, this removes the ability to use the convenience blinker for lane changes.

Screenshot from 2022-08-26 17-42-25

**Comment by jyoung8607** [comment]
If there's benefit to using this signal, it can be wrapped with `update_blinker_from_stalk` instead of the existing `update_blinker_from_lamp`.

**Comment by Jafaral** [comment]
@sshane , not sure where you pulled the data, here is what I see: \
image

**Comment by Jafaral** [comment]
I thought  that is a cleaner signal to use, it is the actual turn signal, and not the lamp signal. Or am I missing something from OP logic here?

**Comment by Jafaral** [comment]
I see the point now. Updated using the  stalk function per @jyoung8607 suggestion. Thanks!

**Comment by sshane** [comment]
What happens if you use convenience blinker for left, then right to cancel the left?

**Comment by Jafaral** [comment]
I will test that scenario.

**Comment by sshane** [comment]
Have a route with the changes?

**Comment by Jafaral** [comment]
@sshane   8c521516df3527d8|2022-08-30--10-05-04--2

There was a bit of a lag before with lamp signals, now it is instantaneous.

**Comment by adeebshihadeh** [comment]
The blinker preference is generally in this order: continuous signal when blinker is activated, lamp state, then stalk state. The lamp state is better than the stalk state since you don't need to worry about things like convenience blinkers.

**Comment by Jafaral** [comment]
What is stake state vs continous signal  @adeebshihadeh ?

**Comment by Jafaral** [comment]
Because what I have above looks like continuous signal to me.

**Comment by adeebshihadeh** [comment]
As far as I understand, this new signal is the position of the blinker stalk, which doesn't capture things like the convenience blinkers.

**Pull request closed without merging**
