### PR TITLE
remove hotspot exceptions in uploader

### PR DESCRIPTION
**Pull request by adeebshihadeh**
This shouldn't be necessary anymore since we don't upload raw logs while onroad.

### CODE REVIEW

**Comment by pd0wm** [comment]
Why do we still run the network check at all while onroad? Shouldn't we just only upload qlogs when onroad?

**Comment by xps-genesis** [comment]
Right now the upload will wait till it can connect to home wifi if I forget to disconnect the hotspot after a drive.

will this change enable the upload on the hotspot when offroad? sometimes my phones hotspot is still connected to comma while the car is in the garage, don't want it upload on the hotspot.

**Comment by adeebshihadeh** [comment]
@xps-genesis yes, this change remove the exceptions for hotspots. what's your use case for connecting the hotspot?

**Comment by xps-genesis** [comment]
> @xps-genesis yes, this change remove the exceptions for hotspots. what's your use case for connecting the hotspot?

mainly live tuning, try code change while on a drive, and debugging. Is there a reason to remove this check? I thought this check is very smart and stopped uploading huge data files over mobile hotpot.

**Comment by pd0wm** [comment]
The problem is issue like this https://github.com/commaai/openpilot/issues/2316. There is always going to be another os/version that has a different IP range.

**Pull request merged**
