### PR TITLE
VW MQB: Add FW for 2016 Passat B8 2.0D 240PS DSG 7

### PR DESCRIPTION
**Pull request by netadvanced**
**Description** [Add FW for 2016 Passat B8 2.0D 240PS DSG 7]
**Verification** []

### CODE REVIEW

**Comment by jyoung8607** [comment]
May we trouble you to add these to the firmware lists in sorted order? Makes it easier to check for duplicates later. Also, comma will need your dongle ID to verify.

**Comment by sshane** [comment]
There's a nice test for duplicate fps already!

**Comment by netadvanced** [comment]
@sshane sorry of course, the id is 5405cac0c9d58c3d

**Comment by netadvanced** [comment]
> May we trouble you to add these to the firmware lists in sorted order? Makes it easier to check for duplicates later. Also, comma will need your dongle ID to verify.

Sorry @jyoung8607 my previous fingerprint, you asked me to put it in input date order.
Do you still need me to reorder them ?

**Comment by jyoung8607** [comment]
> Do you still need me to reorder them ?

I took care of it in #24957, preserving your credit/commit history. Thanks for the PR!

**Pull request closed without merging**
