### PR TITLE
2021 Hyundai Sonata N Line: Fingerprint

### PR DESCRIPTION
**Pull request by sunnyhaibin**
2021 Hyundai Sonata N Line: Add additional fingerprints that came up randomly and caused Car Unrecognized message.

Dongle ID: ac404ef8838ff10f

### CODE REVIEW

**Comment by pd0wm** [comment]
Can we just merge the engine one? Is that enough to pass the fuzzy fingerprint in case it returns a corrupted fw version?

**Comment by sunnyhaibin** [comment]
> Can we just merge the engine one since that's the only one that's actually new? Is that enough to pass the fuzzy fingerprint in case one of the other modules returns a corrupted fw version?

I believe merging the engine one should be enough to pass fuzzy fingerprint. If it is not enough to pass fuzzy fingerprint and still  causes similar issues, we can reconvene.

Here are the 3 consecutive instances where it returned with different fw versions:

1:
```
Found FW versions
{
  (Ecu.fwdRadar, 0x7d0, None): [b'\xf1\x00DN8 1.00 99110-L0000         \xaa\xaa\xaa\xaa\xaa\xaa\xaa\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
  (Ecu.eps, 0x7d4, None): [b'\xf1\x00DN8 MDPS R 1.00 1.00 57700-L0000 4DNAP100']
  (Ecu.fwdCamera, 0x7c4, None): [b'\xf1\x00DN8 MFC  AT USA LHD 1.00 1.01 99211-L0000 191016']
  (Ecu.esp, 0x7d1, None): [b'\xf1\x00DN ESC \x03 100 \x08\x01 58910-L0300']
  (Ecu.transmission, 0x7e1, None): [b'\xf1\x00T02601BL  T02730A1  VDN8T25XXX730NS5\xf7_\x92\xf5']
  (Ecu.engine, 0x7e0, None): [b'HM6M1_0a0_G20']
}
```

2:
```
Found FW versions
{
  (Ecu.fwdRadar, 0x7d0, None): [b'\xf1\x00DN8 1.00 99110-L0000         \xaa\xaa\xaa\xaa\xaa\xaa\xaa\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
  (Ecu.eps, 0x7d4, None): [b'\xf1\x00DN8 MDPS R 1.00 1.00 57700-L0000 4DNAP100']
  (Ecu.fwdCamera, 0x7c4, None): [b'\xf1\x00DN8 MFC  AT USA LHD 1.00 1.01 99211-L0000 191016']
  (Ecu.esp, 0x7d1, None): [b'\xf1\x00DN ESC \x03 100 \x08\x01 58910-L0300']
  (Ecu.transmission, 0x7e1, None): [b'\xf1\x00T02601BL  T02730A1  VDN8T25XXX730NS5\xf7_\x92\xf5']
  (Ecu.engine, 0x7e0, None): [b'HM6M1_0a0_G20']
}
```

3:
```
Found FW versions
{
  (Ecu.fwdRadar, 0x7d0, None): [b'\xf1\x00DN8_ SCC FHCUP      1.00 1.00 99110-L0000         ']
  (Ecu.fwdCamera, 0x7c4, None): [b'\xf1\x00DN8 MFC  AT USA LHD 1.00 1.01 99211-L0000 191016']
  (Ecu.eps, 0x7d4, None): [b'\xf1\x00DN8 MDPS R 1.00 1.00 57700-L0000 4DNAP100']
  (Ecu.esp, 0x7d1, None): [b'\xf1\x00DN ESC \x03 100 \x08\x01 58910-L0300']
  (Ecu.transmission, 0x7e1, None): [b'\xf1\x00T02601BL  T02730A1  VDN8T25XXX730NS5\xf7_\x92\xf5']
  (Ecu.engine, 0x7e0, None): [b'HM6M1_0a0_G20']
}
```

**Comment by pd0wm** [comment]
What are the route ids for those three instances? I can add the engine FW and then simulate the fingerprinting locally using https://github.com/commaai/openpilot/blob/master/selfdrive/debug/test_fw_query_on_routes.py

**Comment by sunnyhaibin** [comment]
> What are the route ids for those three instances? I can add the engine FW and then simulate the fingerprinting locally using https://github.com/commaai/openpilot/blob/master/selfdrive/debug/test_fw_query_on_routes.py
> 
> the corrupted fw versions are being tracked here: #21333

Here's the most recent ones I have found for 1st instance: `ac404ef8838ff10f|2021-09-21--12-11-22--0`

I can't seem to find which routes have 2nd or 3rd instance, but they were confirmed multiple times through the [**Fingerprinting 2.0 (Alternative)**](https://github.com/commaai/openpilot/wiki/Fingerprinting#fingerprinting-20-alternative) method in SSH.

**Comment by pd0wm** [comment]
It actually looks like 
```
  (Ecu.fwdRadar, 0x7d0, None): [b'\xf1\xa01.00'],
  (Ecu.eps, 0x7d4, None): [b'\xf1\xa01.00'],
  (Ecu.fwdCamera, 0x7c4, None): [b'\xf1\xa01.01'],
  (Ecu.esp, 0x7d1, None): [b'\xf1\xa01.00'],
  (Ecu.engine, 0x7e0, None): [b'\xf1\x82DNBWN5TMDCXXXG2E'],
```

Is somewhat common on your car unfortunately. I'll merge the current (non short) ones and then hopefully it will be fully fixed when #21333 is resolved.

**Comment by sunnyhaibin** [comment]
Thanks. The current (non short) ones hopefully are enough to do fuzzy fingerprint after the merge. Thanks.

**Comment by pd0wm** [comment]
Unfortunately not in the case where all other ECUs return a short one. It needs 3 known ones to fingerprint.

**Comment by pd0wm** [comment]
I merged some improvements to the fingerprinting code (https://github.com/commaai/openpilot/pull/22344/files). Can you see if the situation has improved for your car?

**Pull request merged**
