### PR TITLE
remove MPC integration

### PR DESCRIPTION
**Pull request by ClockeNessMnstr**
MPC state integration seems to cause oscillation.

I currently have been using with jerk_pts from @nuwandavek's MPC turning PR. 
not using heading cost also doesn't make sense. I see @HaraldSchafer has been looking at this change recently in some of the model PR's.

### CODE REVIEW

**Comment by ClockeNessMnstr** [comment]
going to keep the branch out there but just split this up when i have time.

**Comment by ClockeNessMnstr** [comment]
still some code from other PR's included here but the integration commit is the improvement.

**Comment by ClockeNessMnstr** [comment]
still some code from other PR's included here but the integration commit is the improvement.

**Comment by HaraldSchafer** [comment]
Unfortunately all PRs that affect optimizers such as this need to be large scale validation. Which makes them unmergeable by default.

**Pull request closed without merging**
