### PR TITLE
PlayStation® model

### PR DESCRIPTION
**Pull request by YassineYousfi**

### CODE REVIEW

**Comment by commaci-public** [comment]
ref for commit e25041bbda1d367cd0b60ac8aa9318d5810343f5: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_ps-driving/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_e25041bbda1d367cd0b60ac8aa9318d5810343f5.zst<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by AlexandreSato** [comment]
I liked soo much! using in 075b133b6181e058

**Comment by gomtings** [comment]
It's very stable except that you can't keep your lane at low speed.

**Comment by YassineYousfi** [comment]
Yes we're merging this model soon, one more improvement coming to this branch before we merge to master. 
Lane change failures are not new to this model though, we're planning to address those after a few more fixes we're working on.

**Comment by commaci-public** [comment]
ref for commit 684aa11eb759ca757ebfa3dcfe012b3c33d138ae: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_ps-driving/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_684aa11eb759ca757ebfa3dcfe012b3c33d138ae.zst<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Comment by commaci-public** [comment]
ref for commit 4f9edfbf9fef1f6d4ce1fe6437dda26725a9f7e5: https://raw.githubusercontent.com/commaai/ci-artifacts/refs/heads/model_replay_ps-driving/2f4452b03ccb98f0|2022-12-03--13-45-30_model_tici_4f9edfbf9fef1f6d4ce1fe6437dda26725a9f7e5.zst<details open><summary>Model Replay Differences</summary><table><tr><td></td><td></td></tr></table></details><details ><summary>All Model Replay Plots</summary><table><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr><tr><td></td></table></details>

**Pull request merged**
