### PR TITLE
log ERROR messages in qlogs too

### PR DESCRIPTION
**Pull request by pd0wm**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
The volume of error messages is way too high, but I like this idea. Perhaps we use the critical level instead, and call the service name something a bit more generic in case we want to change the level in the future.

**Comment by pd0wm** [comment]
I'm fine with critical. I chose error since exceptions are logged at that level.

**Comment by adeebshihadeh** [comment]
I think this should ultimately be error, but are we ok with massive qlogs until the error volume is more reasonable? I’m fine with it either way.

**Comment by pd0wm** [comment]
I'm fine with going over everything that logs as an error and check if that's really necessary

**Pull request merged**
