### PR TITLE
Hyundai: Car Port for Creta (Non-US only) 2024

### PR DESCRIPTION
**Pull request by sunnyhaibin**
**Checklist**

- [x] added entry to CAR in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [ ] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [ ] route with openpilot:
- [x] route with stock system: `b89913b6091ceb05/00000000--690edc369d`
- [x] car harness used (if comma doesn't sell it, put N/A): `Harness A`

Thanks to community 2024 Hyundai Creta owner ricardohalfeld.

### CODE REVIEW

**Comment by ricardohalfeld** [comment]
I noticed a lot of fingerprints are included in this if statement related to LKAS. I wonder if adding Creta's FP to it would resolve the steering issues. Haven't looked into it too much yet.

**Comment by sshane** [comment]
That's for the LKAS HUD UI and really should be detected soon. What steering issues are you experiencing?

**Comment by sunnyhaibin** [comment]
> That's for the LKAS HUD UI and really should be detected soon. What steering issues are you experiencing?

The change has been updated, but still awaiting user feedback.

**Comment by ricardohalfeld** [comment]
> That's for the LKAS HUD UI and really should be detected soon. What steering issues are you experiencing?

Longitudinal control was working, but not lateral. It works now, although it feels a little weird, turning in steps. I'll look into the code some more to see if there's something to be done about that, but only after resolving a work crisis. Be back soon.

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
