### PR TITLE
Translation into Spanish

### PR DESCRIPTION
**Pull request by maria2518**

### CODE REVIEW

**Comment by sshane** [comment]
Thanks for the PR! There's just a few small UI bugs. Do you know if there are any shorter words/phrases for these strings that are too long for the UI?

Screenshot from 2023-04-17 22-25-53
Screenshot from 2023-04-17 22-26-20
Screenshot from 2023-04-17 22-26-43
Screenshot from 2023-04-17 22-27-04
Screenshot from 2023-04-17 22-27-47
Screenshot from 2023-04-17 22-28-25

**Comment by sshane** [comment]
@maria2518 do you have any suggestions for the issues?

**Comment by maria2518** [comment]
My apologies for the errors, I didn't see them at the time. I'll close the pull request and fix the issues, once fixed I'll open a new pull request.

**Comment by sshane** [comment]
No need to close this pull request! You can keep it open as you push changes to it

**Pull request closed without merging**
