### PR TITLE
Port brazilian honda HR-V 2023

### PR DESCRIPTION
**Pull request by AlexandreSato**
Splitted from #27915 

Discord user: kotarou9692 
DongleId: 147613502316e718

**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot: 
147613502316e718|2024-01-07--09-11-33 (Gabriel 2024)
147613502316e718|2024-01-07--10-12-31 (Alex Takeda 2023)
- [x] route with stock system:
147613502316e718|2024-01-07--09-20-48 (Gabriel 2024)

video with me, Alex Takeda (Kotarou) and Gabriel in this routes: https://youtu.be/Q11veROVwF4?t=27m

### CODE REVIEW

**Review by thegauravgiri — APPROVED** [review]
LGTM, thanks for the contribution

**Comment by adeebshihadeh** [comment]
Why is the Brazilian one special and require its own port?

**Comment by AlexandreSato** [comment]
Brazilian not require ALT_BRAKE

Enviado do meu iPhone

Em 10 de jan. de 2024, à(s) 00:26, Adeeb Shihadeh ***@***.***> escreveu:

﻿

Why is the Brazilian one special and require its own port?

**Comment by adeebshihadeh** [comment]
Can we defect that?

**Comment by AlexandreSato** [comment]
> Can we defect that?

From #27915 with:
image

**Comment by Ktrtkd** [comment]
Any news regarding this port? @gaurovgiri

**Pull request closed without merging**
