### PR TITLE
use PubMaster & SubMaster

### PR DESCRIPTION
**Pull request by deanlee**
use PubMaster & SubMaster added in cereal https://github.com/commaai/cereal/pull/42

### CODE REVIEW

**Comment by deanlee** [comment]
I have tested it and it seems to work fine.

**Comment by deanlee** [comment]
since the copy between event:Reader is very cheap (just set the internal pointer to others), SubMaster::poll return std::vector<event::Reader>  to make it more easy to use.

**Comment by deanlee** [comment]
updated to new Sub&Pub AP I:https://github.com/commaai/cereal/pull/42#issuecomment-628481128

**Comment by pd0wm** [comment]
Moved to a new branch so I can get all the CI to run.

**Pull request closed without merging**
