### PR TITLE
UI: choose fcam_intrinsic matrix, zoom and y_offset based on video size

### LINKED ISSUE #22230: ui: choose fcam_intrinsic matrix, zoom and y_offset based on video size

### PR DESCRIPTION
**Pull request by deanlee**
resolve #22230

### CODE REVIEW

**Comment by ZwX1616** [comment]
can we also refactor the driverview.cc code to not use hardware::tici?

**Comment by deanlee** [comment]
need to modify the code after #22263

**Comment by pd0wm** [comment]
Is this good to review?

**Comment by deanlee** [comment]
Not yet, I'm still testing

**Comment by deanlee** [comment]
closed, moved to https://github.com/commaai/openpilot/pull/23315

**Pull request closed without merging**
