### PR TITLE
Honda Civic 2022: forward fault bit from camera

### PR DESCRIPTION
**Pull request by royjr**
Master branch causes a brake system light to stay on my dash, may require a restart after install for brake system light to come up, then shows up every restart after. The light never shows up again with this fix. @sshane 

Civic22 users with issues
-First (sport, confirmed fix)
-Kevin
-Marco the Dingo (sport touring, experiences issue with sunnypilot, but not on master-ci)

Civic22 users without issues
-Rethkir (sport touring)

### CODE REVIEW

**Comment by sshane** [comment]
Do you have a route?

**Comment by royjr** [comment]
master
1a5d045d2c531a6d|2022-07-25--17-05-43
1a5d045d2c531a6d|2022-07-25--17-06-06

civic22_brakesystemlight
1a5d045d2c531a6d|2022-07-25--17-07-18

**Comment by sshane** [comment]
Looks like your car doesn't have the same symptoms as the other users (missing pandaStates or can packets), let me have you try one thing.

It's possible we're initializing and sending 0 for LKAS_PROBLEM too early sometimes, and the car is waiting for a set amount of time before it accepts that value transitioning to 0. So if we just pass it through from the camera, it might work as well.

**Comment by sshane** [comment]
@royjr see if this fixes it

**Comment by royjr** [comment]
Looks good @sshane!

1a5d045d2c531a6d|2022-07-25--18-00-19
1a5d045d2c531a6d|2022-07-25--18-00-51

**Comment by sshane** [comment]
If you drive on this in the next couple of days let me know how it goes. About how often would it remain faulted without these changes on master?

**Comment by royjr** [comment]
@sshane Still looks good, no problems with the fix. Remains faulted on master for at least 1.5hrs, haven't gone on longer rides recently.

**Comment by sshane** [comment]
Any problems since then on this branch or is all good?

**Comment by royjr** [comment]
All good! Wanted to confirm issue persists on master.

**Pull request merged**
