### PR TITLE
camerad: add CameraConfig struct for initializing CameraState in constructor

### PR DESCRIPTION
**Pull request by deanlee**
reopen https://github.com/commaai/openpilot/pull/33034

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
trigger-jenkins

**Comment by adeebshihadeh** [comment]
Failed on OX03C10
image

**Comment by deanlee** [comment]
Strange, but I don't think this PR is the likely cause. It only initializes a few parameters for the camera before opening it. However, I'll double-check later.

**Comment by deanlee** [comment]
> Failed on OX03C10 

I ran test_camerad.py on device (OX03C10)  multiple times without encountering any errors. This error report might be due to a flaky test.

**Comment by adeebshihadeh** [comment]
This test is quite reliable, but let's try again.

trigger-jenkins

**Comment by deanlee** [comment]
The issue should be identified now. It's an initialization problem.

Previously, the `CameraState` had no constructor and did not manage its own initialization, depending on `MultiCameraState cameras = {}; `to set its member variables to zero.

This pull request introduces a constructor for `CameraState`, meaning that `CameraState` must now take responsibility for initializing its own member variables. Otherwise, the member variables could contain corrupt data.

I have committed the fix. The `CameraState` class now properly manages its own initialization, which should help it pass the test and improve overall reliability.

**Comment by adeebshihadeh** [comment]
trigger-jenkins

**Pull request merged**
