### PR TITLE
Hyundai longitudinal: enable for `KIA_CEED`

### PR DESCRIPTION
**Pull request by sunnyhaibin**
Split from https://github.com/commaai/openpilot/pull/26967

**Checklist**
- [x] updated entry in CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [x] test route updated in [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [x] route with openpilot longitudinal: `99315f265be0b26c|2023-09-07--14-32-24`

### CODE REVIEW

**Comment by sshane** [comment]
Let's avoid letting small PRs like this sit around, opening only when ready to go.

**Comment by sshane** [comment]
This has FCA11, but still faults, so we're probably sending unexpected values.

https://github.com/commaai/openpilot/pull/28479#issuecomment-1683423682

**Comment by sshane** [comment]
@sunnyhaibin let me know when you do some investigation.

**Comment by sunnyhaibin** [comment]
@sshane Probably similar to this
- https://github.com/commaai/openpilot/issues/25221

**Pull request closed without merging**
