### PR TITLE
Mazda: Support CX-9 2022

### PR DESCRIPTION
**Pull request by Jafaral**
Same as CX-9 2021, no change in LKAS system.

dongle-id: 8c6e0e30decb68f7

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Nice, can you update the year in the CarInfo section too?

**Comment by Jafaral** [comment]
> Nice, can you update the year in the CarInfo section too?

I just  pushed an update but it got rejected, looks like @sshane  beat  me to it!

**Comment by Jafaral** [comment]
BTW,  car info  doesn't look complete. I will submit a PR to fix it.

**Comment by sshane** [comment]
Fixing that comment bug now, it really shouldn't be trying to write it for contributor PRs

**Comment by sshane** [comment]
Thanks for the PR!

**Pull request merged**
