### PR TITLE
classify honda ecus

### PR DESCRIPTION
**Pull request by jpancotti**
classify Honda ecus according to Honda nomenclature

### CODE REVIEW

**Comment by pd0wm** [comment]
Nice!

We also need to make a change to fw_versions.py to make sure we ignore ECUs that are not important like we did when they were still unknown.

https://github.com/commaai/openpilot/blob/master/selfdrive/car/fw_versions.py#L97
Let's change that to `if ecu_type not in ESSENTIAL_ECUS`, where `ESSENTIAL_ECUS = [engine, eps, esp, vsa, fwRadar, fwdCamera, brakeBooster]`. Basically anything that has to do with ACC, steering, gas and brakes.

**Comment by jpancotti** [comment]
> Nice!
> 
> We also need to make a change to fw_versions.py to make sure we ignore ECUs that are not important like we did when they were still unknown.
> 
> https://github.com/commaai/openpilot/blob/master/selfdrive/car/fw_versions.py#L97
> Let's change that to `if ecu_type not in ESSENTIAL_ECUS`, where `ESSENTIAL_ECUS = [engine, eps, esp, vsa, fwRadar, fwdCamera, brakeBooster]`. Basically anything that has to do with ACC, steering, gas and brakes.

done

**Comment by pd0wm** [comment]
Just merged your cereal PR and updated master. Can you rebase your branch to latest master?

**Comment by jpancotti** [comment]
> Just merged your cereal PR and updated master. Can you rebase your branch to latest master?

done

**Comment by pd0wm** [comment]
The code is broken. See linter.

Also I also see changes to the submodules. Did you rebase properly?

**Comment by pd0wm** [comment]
Looks good! 

I'll run a fingerprint test on all the versions that we got back to make sure there are no regressions, and then I'll merge it.

**Pull request merged**
