### PR TITLE
Refactor model

### PR DESCRIPTION
**Pull request by haraschax**
New 3D models.

Still WIP, some scenarios the model predictions are not very accurate. Besides that should work.

### CODE REVIEW

**Comment by ShaneSmiskol** [comment]
Getting this: `selfdrive/modeld/runners/snpemodel.cc:97: SNPEModel::SNPEModel(const char *, float *, size_t, int): assertion "output_size == bufferShape[1]" failed`

The output size and bufferShape:
`output size: 614
bufferShape: 11327`

**Comment by HaraldSchafer** [comment]
Lol it's not ready yet!

**Comment by Martint1980** [comment]
At city and country roads it drive a little bit drunk, sometimes over lane lines. Before a curve it makes quite aggressive corrections. I had to lower PI to drive with it, but still not optimal.

**Comment by HaraldSchafer** [comment]
> At city and country roads it drive a little bit drunk, sometimes over lane lines. Before a curve it makes quite aggressive corrections. I had to lower PI to drive with it, but still not optimal.

ty for feedback!

**Comment by rav4kumar** [comment]
lane changes does not work. it says changing lane for sec and the restarts to "nudge to lane change"

**Comment by HaraldSchafer** [comment]
> lane changes does not work. it says changing lane for sec and the restarts to "nudge to lane change"

were you on latest commit? Should be dealt with.

**Comment by rav4kumar** [comment]
> > lane changes does not work. it says changing lane for sec and the restarts to "nudge to lane change"
> 
> were you on latest commit? Should be dealt with.

ill try out your latest commit from today. but need to upsteam my new 2021 prius so i dont have to add it manually on every branch lol

**Comment by ShaneSmiskol** [comment]
Just tried it out yesterday, seeing the lane lines and path actually move in 3D space, up and down for hills and dips was pretty cool! Path prediction seems better than release2 currently, and it's picking up most faint lane lines like new_segnet does.

**Pull request closed without merging**
