### PR TITLE
Add Arabic translations

### PR DESCRIPTION
**Pull request by sshane**
Thanks to @nasser-glx!

### CODE REVIEW

**Comment by sshane** [comment]
Yeah, I recommend you create your own PR so you can make edits

**Comment by Jafaral** [comment]
The Arabic translation could use some polishing. Will find time to give some suggestions

**Comment by sshane** [comment]
Sounds good, feel free to create your own PR so you can edit it

**Comment by sshane** [comment]
Moved to https://github.com/commaai/openpilot/pull/25153

**Pull request closed without merging**
