### PR TITLE
Add 2018 Civic Hatchback 1.0l CVT (European) support

### PR DESCRIPTION
**Pull request by csouers**
Basically the same as as current civic bosch cars. No major complaints from the discord user, Noillek.

I include a comment in README.MD that we also support european spec versions of this car. I can remove this if desired.

### CODE REVIEW

**Comment by rbiasini** [comment]
As usual, we need a cabana link. Thanks!

**Comment by csouers** [comment]
Done.

Cabana link > https://my.comma.ai/cabana/?route=a859a044a447c2b0%7C2019-09-25--06-03-16&exp=1600974915&sig=z94CVpbP0RWzyuyUHXvP%2BWb1HbO79hM9CFoGR4TuVog%3D&max=-1&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fa859a044a447c2b0%2F6315468eebfa40e48ae19d4a9e29f620_2019-09-25--06-03-16

**Comment by csouers** [comment]
The fingerprint for this car encompasses the previous fingerprint (combo of the 2017 and the 2019 canadian model, plus these three frames. ```460: 3, 1625: 5, 1629: 5```

**Comment by rbiasini** [comment]
confirmed. Haven't found msg 1633 in the drive you posted, but that's ok. Not worth separating the fingerprints for such a low frequency message.
Thanks!

**Pull request merged**
