### PR TITLE
cars: platform enums -> prepend brand name

### PR DESCRIPTION
**Pull request by jnewb1**
keeps the enums consistent. for example

```RAM_HD_5TH_GEN``` -> has brand before
```PACIFICA_2017_HYBRID``` -> no brand

### CODE REVIEW

**Comment by jnewb1** [comment]
dont think we need to add these to migration since it was only in master for a few hours

**Comment by jnewb1** [comment]
replay diff is the car fingerprints changing (again!)

**Comment by sshane** [comment]
Do your notebook tests pass? It's missing more migrations on the same line

**Comment by jnewb1** [comment]
> Do your notebook tests pass? It's missing more migrations on the same line

ah, we disabled them because of the huggingface thing. I'll fix them

**Review by sshane — APPROVED** [review]

**Pull request merged**
