### PR TITLE
QT: scrollable toggles panel, show description on click 

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Nice, does this look like the current UI?

**Comment by deanlee** [comment]
panel

**Comment by adeebshihadeh** [comment]
Looks good :)

**Comment by adeebshihadeh** [comment]
Tried it out on a device, and I like it! The scrolling doesn't feel quite right, but @iejMac is fixing that in https://github.com/commaai/openpilot/pull/20392. Waiting on fixing scrolling on QCOM2 to merge.

**Pull request closed without merging**
