### PR TITLE
0.4.2

### PR DESCRIPTION
**Pull request by rbiasini**
Version 0.4.2 (2018-02-05)
==========================
 * Add alpha support for 2017 Lexus RX Hybrid
 * Add alpha support for 2018 ACURA RDX
 * Updated fingerprint to include Toyota Rav4 SE and Prius Prime
 * Bugfixes for Acura ILX and Honda Odyssey

### CODE REVIEW

**Comment by rbiasini** [comment]
@voland696 yeah, we can add those MYs once we have the fingerprint for those cars and openpilot has been succesfully tested. Good chances are that the even the fingerprints are the same for 2016-2018 MYs.

**Comment by energee** [comment]
We haven't seen any difference in can fingerprints across same generation hondas (at the same trim level). I would assume the 16 & 17, if they are same gen, would all be compatible without an additional fingerprint. That being said, I agree with the design decision to specify the year so that we know what year the port was developed on.

**Comment by vanillagorillaa** [comment]
@energee Looks like RDX second gen is 13-Present with a facelift in 16 which added AcuraWatch Plus. So it is probably the same across the board. @voland696 feel free to message me on slack (same username) if you would like to discuss this

**Comment by billy2kool** [comment]
is there anyone working on a 2016 Honda accord touring

**Comment by vanillagorillaa** [comment]
@billy2kool I don't believe that there is anyone specifically working on the 16 accords. These models use a different protocol to communicate on the bus. To my knowledge nobody has started working on it

**Pull request merged**
