### PR TITLE
Subaru: Ascent 2023 dashcam mode

### PR DESCRIPTION
**Pull request by martinl**
**Checklist**
- [x] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [ ] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [ ] route with openpilot:
- [ ] route with stock system:

### CODE REVIEW

**Comment by martinl** [comment]
Route: `99437cef6d5ff2ee|2023-03-13--21-21-38`

2023 engine and transmission ecus are on different addresses than older global and gen2 models. We are currently looking into fingerprinting issues. So far it looks like some of the ecus are not responding to regular Subaru fw queries and need multiple tries to respond.

**Comment by sshane** [comment]
Can you post the results of the panda FW query and let me know which are spotty in openpilot?

**Comment by martinl** [comment]
Typically abs and eps reported fw versions; engine (0x7a2), transmission (0x7a3) and fwdCamera (0x787) did not:
```
Found FW versions
{
  Brand: subaru, bus: 1 - (Ecu.abs, 0x7b0, None): [b'\xa5 #\x03\x00']
  Brand: subaru, bus: 1 - (Ecu.eps, 0x746, None): [b'%\xc0\xd0\x11']
}
```

User reported he got fingerprinting working about 95% of time with following query configuration:
```
FW_QUERY_CONFIG = FwQueryConfig(
  requests=[
    Request(
      [StdQueries.TESTER_PRESENT_REQUEST, SUBARU_VERSION_REQUEST],
      [StdQueries.TESTER_PRESENT_RESPONSE, SUBARU_VERSION_RESPONSE],
    ),
    Request(
      [SUBARU_VERSION_REQUEST],
      [SUBARU_VERSION_RESPONSE],
    ),
    Request(
      [StdQueries.TESTER_PRESENT_REQUEST, StdQueries.DEFAULT_DIAGNOSTIC_REQUEST, StdQueries.EXTENDED_DIAGNOSTIC_REQUEST],
      [StdQueries.TESTER_PRESENT_RESPONSE, StdQueries.DEFAULT_DIAGNOSTIC_RESPONSE, StdQueries.EXTENDED_DIAGNOSTIC_RESPONSE],
    ),
  ],
)
```

**Comment by martinl** [comment]
ecu responses using panda example fw version query results:

```
*** Results for address 0x787 ***


0xF100 IDENTIFICATION_OPTION_VEHICLE_MANUFACTURER_SPECIFIC_DATA_IDENTIFIER: b' \x02\x0e'
0xF101 IDENTIFICATION_OPTION_VEHICLE_MANUFACTURER_SPECIFIC_DATA_IDENTIFIER: b'0521081D4B052108012F'
0xF102 IDENTIFICATION_OPTION_VEHICLE_MANUFACTURER_SPECIFIC_DATA_IDENTIFIER: b'87501XC10B'
0xF182 APPLICATION_DATA_IDENTIFICATION: b'\x05!\x08\x1dK\x05!\x08\x01/'
0xF186 ACTIVE_DIAGNOSTIC_SESSION: b'\x01'
0xF197 SYSTEM_NAME_OR_ENGINE_TYPE: b'EyeSight                        '
0xF198 REPAIR_SHOP_CODE_OR_TESTER_SERIAL_NUMBER: b'!\x853F'


*** Results for address 0x7A2 ***


0xF100 IDENTIFICATION_OPTION_VEHICLE_MANUFACTURER_SPECIFIC_DATA_IDENTIFIER: b'\xa1\x10\x0f'
0xF182 APPLICATION_DATA_IDENTIFICATION: b'\xe5,\xa0P\x07'
0xF186 ACTIVE_DIAGNOSTIC_SESSION: b'\x03'
0xF18E VEHICLE_MANUFACTURER_KIT_ASSEMBLY_PART_NUMBER: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
0xF190 VIN: b'4S4WMAWD3P3417292'
0xF197 SYSTEM_NAME_OR_ENGINE_TYPE: b'2.4 TURBO                       '


*** Results for address 0x7A3 ***


0xF100 IDENTIFICATION_OPTION_VEHICLE_MANUFACTURER_SPECIFIC_DATA_IDENTIFIER: b'\xd7\x10@'
0xF182 APPLICATION_DATA_IDENTIFICATION: b'\x04\xfe\xf3\x00\x00'
0xF186 ACTIVE_DIAGNOSTIC_SESSION: b'\x03'
0xF197 SYSTEM_NAME_OR_ENGINE_TYPE: b'CVT 
```

**Comment by martinl** [comment]
Here is one failed fingerprinting route `99437cef6d5ff2ee|2023-03-14--11-42-59`

**Comment by sshane** [comment]
I don't know how we successfully parsed the response any of the time, but it looks like the ECU does not like the tester response request. Try removing that from the list.

**Comment by ilyk** [comment]
Removed `TESTER_PRESENT_REQUEST`, stick to the `SUBARU_VERSION_REQUEST` only. The result is the following:
```Found FW versions
{
  Brand: subaru, bus: 1 - (Ecu.eps, 0x746, None): [b'%\xc0\xd0\x11']
  Brand: subaru, bus: 1 - (Ecu.abs, 0x7b0, None): [b'\xa5 #\x03\x00']
  Brand: subaru, bus: 1 - (Ecu.fwdCamera, 0x787, None): [b'\x05!\x08\x1dK\x05!\x08\x01/']
}

Possible matches: set()```

So neither `Ecu.engine` nor `Ecu.transmission` were detected.

Added `SHORT_TESTER_PRESENT_REQUEST`, the results:

```iso-tp query bad response: (1968, None) - 0x7f3e13
iso-tp query bad response: (1862, None) - 0x7f3e12
iso-tp query bad response: (1927, None) - 0x7f3e7f
iso-tp query bad response: (1955, None) - 0x7f3e13

Found FW versions
{
}```

So looks like `SHORT_TESTER_PRESENT_REQUEST` doesn't work for this car.


PS. Having the following: ```FW_QUERY_CONFIG = FwQueryConfig(
  requests=[
    Request(
      [SUBARU_VERSION_REQUEST],
      [SUBARU_VERSION_RESPONSE],
    ),
    Request(
      [StdQueries.TESTER_PRESENT_REQUEST, SUBARU_VERSION_REQUEST],
      [StdQueries.TESTER_PRESENT_RESPONSE, SUBARU_VERSION_RESPONSE],
    ),
    Request(
      [StdQueries.TESTER_PRESENT_REQUEST, SUBARU_VERSION_REQUEST],
      [StdQueries.TESTER_PRESENT_RESPONSE, SUBARU_VERSION_RESPONSE],
    ),
  ],
)```

Gives me this:

```iso-tp query bad response: (1927, None) - 0x7f3e7f
iso-tp query bad response: (1927, None) - 0x7f3e7f

Found FW versions
{
  Brand: subaru, bus: 1 - (Ecu.abs, 0x7b0, None): [b'\xa5 #\x03\x00']
  Brand: subaru, bus: 1 - (Ecu.eps, 0x746, None): [b'%\xc0\xd0\x11']
  Brand: subaru, bus: 1 - (Ecu.fwdCamera, 0x787, None): [b'\x05!\x08\x1dK\x05!\x08\x01/']
  Brand: subaru, bus: 1 - (Ecu.engine, 0x7a2, None): [b'\xe5,\xa0P\x07']
  Brand: subaru, bus: 1 - (Ecu.transmission, 0x7a3, None): [b'\x04\xfe\xf3\x00\x00']
  Brand: subaru, bus: 1 - (Ecu.abs, 0x7b0, None): [b'\xa5 #\x03\x00']
  Brand: subaru, bus: 1 - (Ecu.eps, 0x746, None): [b'%\xc0\xd0\x11']
  Brand: subaru, bus: 1 - (Ecu.abs, 0x7b0, None): [b'\xa5 #\x03\x00']
  Brand: subaru, bus: 1 - (Ecu.eps, 0x746, None): [b'%\xc0\xd0\x11']
}

Possible matches: {'SUBARU ASCENT 2023'}```

**Comment by sshane** [comment]
So what did you end up with on your branch? It looks like it's returning engine FW now

**Comment by ilyk** [comment]
Unfortunately, even having three requests, two of which are identical. Still, the rate of success looks like it is near 90%. Sometimes only `Ecu.abs` and `Ecu.eps` are detected. Sometimes all but engine, sometimes all but transmission, or even all but fwdCamera. It looks random and unpredictable. Maybe we're missing something.

**Comment by sshane** [comment]
Okay, can you try to switch the query bus? It's possible there's a gateway that is managing the communication at the OBD port that's inconsistent. Try to switch to bus 0 (from the camera), something like this: https://github.com/commaai/openpilot/blob/master/selfdrive/car/toyota/values.py#L223

**Comment by ilyk** [comment]
Yep. I've tried playing around with bus=0/1. Sometimes something shows up on the bus=0, but it's more common to find all those on the bus=1.

**Comment by martinl** [comment]
2023 Outback has same issue

**Comment by sshane** [comment]
@jnewb1 can you merge as dashcam mode, with a comment somewhere for the fingerprinting problems?

**Comment by jnewb1** [comment]
> @jnewb1 can you merge as dashcam mode, with a comment somewhere for the fingerprinting problems?

this one uses LKAS_ANGLE as well

**Comment by jnewb1** [comment]
@sshane good to merge this?

**Pull request merged**
