### PR TITLE
add core python deps

### PR DESCRIPTION
**Pull request by maxime-desroches**
setuptools is required to build openpilot (cythonize files)
tqdm is imported on start

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
How come CI doesn't fail without setuptools?

**Comment by maxime-desroches** [comment]
It was installed as a required dep of timezonefinder. We now have removed timezonefinder 
( https://github.com/commaai/openpilot/pull/32665 ) so we have to install it manually.

CI did not failed because the build was cached

**Comment by adeebshihadeh** [comment]
Hmm, we've gotta fix this cache problem then

**Comment by adeebshihadeh** [comment]
Hmm, we've gotta fix this cache problem then

**Pull request merged**
