### PR TITLE
acados: update to 0.2.2

### PR DESCRIPTION
**Pull request by maxime-desroches**

### CODE REVIEW

**Comment by fredyshox** [comment]
Mac binaries are not updated, I can build them if you don't have any mac at hand

**Comment by maxime-desroches** [comment]
@fredyshox Yes please do

**Comment by fredyshox** [comment]
Is the ref 28f4f22196632ec6ea145c09f635010622d99504 the one that you used? After building it on my machine I've got different files in `include/` and `acados_template/`

**Comment by maxime-desroches** [comment]
Should be good now

**Comment by fredyshox** [comment]
something is up with 0.2.1, because mpc tests are not passing on my mac too (same outputs), while on master they do

**Pull request merged**
