### PR TITLE
Add more German zone rules.

### PR DESCRIPTION
**Pull request by arne182**
https://wiki.openstreetmap.org/wiki/Key:zone:maxspeed

### CODE REVIEW

**Comment by rbiasini** [comment]
@arne182 can you please run `default_speeds_generator.py` to generate the new json file?

**Comment by arne182** [comment]
./default_speeds_generator.py
Traceback (most recent call last):
  File "./default_speeds_generator.py", line 215, in <module>
    main()
  File "./default_speeds_generator.py", line 143, in main
    DE.add_rule({"zone:maxspeed": "DE:30"}, "30")
  File "./default_speeds_generator.py", line 177, in add_rule
    raise ValueError("Rule tag keys must be in allowable tag kesy") # If this is by mistake, please update ALLOWABLE_TAG_KEYS
ValueError: Rule tag keys must be in allowable tag kesy
$

**Comment by legonigel** [comment]
The "zone:maxspeed" is not one of the currently allowed tag keys. You need to add this tag to the list below called `ALLOWABLE_TAG_KEYS`

**Comment by arne182** [comment]
./default_speeds_generator.py
Traceback (most recent call last):
  File "./default_speeds_generator.py", line 215, in <module>
    main()
  File "./default_speeds_generator.py", line 154, in main
    write_json(countries)
  File "./default_speeds_generator.py", line 159, in write_json
    out_dict.update(country.jsonify())
  File "./default_speeds_generator.py", line 208, in jsonify
    for r_name, region in self.regions.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
$

**Comment by nanamiwang** [comment]
seems you are running python2 script under python3 environment. In python3 iteritems is renamed to items

**Comment by legonigel** [comment]
merged internally, will be in next release. Thanks!

**Pull request closed without merging**
