### PR TITLE
Re add support for missing COROLLA_TSS2 engine f/w

### PR DESCRIPTION
**Pull request by Papi94**
Re add support for missing COROLLA_TSS2 engine f/w

Please merge this , updates are currently breaking my device, there was a pull request for this change 4 months ago but it's not in the latest branch. 
Prev: https://github.com/commaai/openpilot/pull/20988/commits/4177aafd6cb8373f5e120120f261c81c3f7b1fe4

**Verification** [](Explain how you tested this bug fix.)

Ran the following on my comma confirmed after reboot it recognized my car
curl https://raw.githubusercontent.com/commaai/openpilot/10f0296df30b5c4fd6c18be800d5b04836bad991/selfdrive/car/toyota/values.py > /data/openpilot/selfdrive/car/toyota/values.py

Subsequently did a test drive and calibrated the device.

### CODE REVIEW

**Comment by pd0wm** [comment]
I'm confused. That line is exactly the same as the line above. Our tests even catches it as a duplicate.

Can you send a driver on `release2` where your car is not recognized?

**Comment by Papi94** [comment]
> I'm confused. That line is exactly the same as the line above. Our tests even catches it as a duplicate.
> 
> Can you post a drive on `release2` where your car is not recognized?

I see what you mean. I think the problem here is this fingerprint hasnt made it in to a release yet. which is surprising cause there has been 3 updates since the original merge.

**Comment by pd0wm** [comment]
It has definitely made it into the release. If it's not fingerprinting on `release2` please make an issue and fill out the template.

**Comment by ErichMoraga** [comment]
It's likely user error.  It would help if Papi would spell my name properly and/or tag me so hours don't go by.  The common reason for these issues is **empty carFw**.

**Pull request closed without merging**
