### PR TITLE
MLSIM V2

### PR DESCRIPTION
**Pull request by haraschax**

### CODE REVIEW

**Comment by pfeiferj** [comment]
Seems to have trouble with rolling hills. When going over rolling hills the path lifts up off the road like it doesn’t know how to follow the hill. This results in pretty poor lateral performance, especially if there’s curves on the rolling hills. Noticed this behavior a little with mlsim v1, but is much more apparent on mlsim v2

**Comment by YassineYousfi** [comment]
Fully trained model coming later today. This model is only trained to 25% which explains the behavior in complex situations like hills, turns, etc.

**Comment by pfeiferj** [comment]
Yep, latest update is significantly better. It does seem to want to cut in on curves pretty bad though. Had a couple hill crests where it felt like it wanted to go off the road as well, but that isn’t necessarily a new issue

**Comment by pfeiferj** [comment]
Latest version seems to have resolved the worst of the cutting. Still cuts a bit more than other models, but only went over the line a couple times on my latest drive vs nearly every curve on my previous comment. Noticed some occasional odd behavior like floating towards the center line. Overall though I have enough confidence in this version to not bother with reverting back to mlsim_v1

**Pull request merged**
