### PR TITLE
Add proper fingerprint for 2017 Honda Civic Hatchback LX

### PR DESCRIPTION
**Pull request by cfranyota**
# Fingerprint
This pull requests adds a fingerprint for <Honda- Civic - 2017 - Hatchback LX>.

### CODE REVIEW

**Comment by cfranhonda** [comment]
So, how do I fix this? It works for my car.....

**Comment by cfranhonda** [comment]
So, how do I fix this? It works for my car.....

**Comment by alabastri** [comment]
@cfranhonda seems like this fingerprint was taken on the wrong bus. If you have the harness and you are on a Honda-Bosch, you should scan bus 1, not 0.

**Comment by rbiasini** [comment]
@cfranhonda seems like this fingerprint was taken on the wrong bus. If you have the harness and you are on a Honda-Bosch, you should scan bus 1, not 0.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
