### PR TITLE
regen: use WideCameraOnly

### PR DESCRIPTION
**Pull request by fredyshox**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Want to get #27640 merged instead?

**Comment by fredyshox** [comment]
Ok, that seams reasonable. Much more seamless than settings the param yourself. Also why is the wide road camera stream assumed to be default when using single camera, instead of the standard road one?

**Comment by adeebshihadeh** [comment]
> Ok, that seams reasonable. Much more seamless than settings the param yourself. Also why is the wide road camera stream assumed to be default when using single camera, instead of the standard road one?

No good reason, it was originally a toggle in the UI during comma three development to completely switch to the wide cam for testing.

**Comment by adeebshihadeh** [comment]
Merged #27640, is this still necessary?

**Comment by fredyshox** [comment]
Gonna see how it works on the regen side, and if we need some changes there.

**Pull request closed without merging**
