### PR TITLE
openpilot v0.7.1

### PR DESCRIPTION
**Pull request by geohot**
comma two support!
Lane Change Assist above 45 mph!
Replace zmq with custom messaging library, msgq!
Supercombo model: calibration and driving models are combined for better lead estimate
More robust updater thanks to jyoung8607! Requires NEOS update
Improve low speed ACC tuning

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Nice try, George ;-)

**Comment by geohot** [comment]
Haha, nice try how? This is the new openpilot release workflow, give everyone a chance to comment.

**Comment by ErichMoraga** [comment]
Yeah, I saw you needed an extra reviewer.  I guess Willem has your back.

**Comment by geohot** [comment]
We have branch protection!

**Comment by arne182** [comment]
Here is something:
framebuffer_init in selfdrive/common/framebuffer.h has changed but 
https://github.com/commaai/openpilot/blob/nightly/installer/updater/updater.cc#L200 has not
../../selfdrive/common/framebuffer.h:12:19: note: candidate function not viable:
      requires 5 arguments, but 7 were provided
FramebufferState* framebuffer_init(

**Comment by geohot** [comment]
Nice catch, will fix internally, but the binary should be fine for this release. Can't wait until we are developing on openpilot master!

**Review by pd0wm — APPROVED** [review]

**Pull request merged**
