### PR TITLE
Cabana: stable initial release

### PR DESCRIPTION
**Pull request by deanlee**
abc

### CODE REVIEW

**Comment by deanlee** [comment]
lgtm,  many refactoring efforts to make the code more robust and clean. probably the last big change I'll make to it.

**Comment by deanlee** [comment]
it would be better if this pr can be merged first. Many follow-up work depends on it.

**Comment by adeebshihadeh** [comment]
Where did this new icon come from? Can we avoid introducing a new asset image for now?

**Comment by deanlee** [comment]
> Where did this new icon come from? Can we avoid introducing a new asset image for now?

removed

**Comment by michaelhonan** [comment]
This seems to be breaking OP build? 

```
scons: *** Import of non-existent variable ''replay_lib''
File "/data/openpilot/tools/cabana/SConscript", line 1, in <module>
```

**Pull request merged**
