### PR TITLE
ignore double tap on experimental button

### PR DESCRIPTION
**Pull request by MoreTore**
https://github.com/commaai/openpilot/issues/27703

### CODE REVIEW

**Comment by deanlee** [comment]
Is there any special reason you need to `installeventFilter` to self  instead of just overloading `event()`?
In addition, this depends on the time interval of db click, this is probably too short and out of our control.

**Comment by MoreTore** [comment]
> Is there any special reason you need to `installeventFilter` to self instead of just overloading `event()`? 

your right. I changed it

>In addition, this depends on the time interval of db click, it is probably too short and out of our control.

So far it seems to have fix the issue.

**Comment by deanlee** [comment]
how about use a timer? https://github.com/commaai/openpilot/pull/27865.

**Comment by MoreTore** [comment]
> how about use a timer? #27865.

that does seem better.

**Pull request closed without merging**
