### PR TITLE
loggerd: c++ LoggerState

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Can you rebase this?

**Comment by adeebshihadeh** [comment]
A lot of the line reduction here is just from removing the thread safety, which is unrelated to the rest of the refactor. That should really be done in its own PR.

**Comment by adeebshihadeh** [comment]
Merged anyway since we good tests around this now and it was pretty straightforward. Next time let's break it up though.

**Comment by deanlee** [comment]
>  Next time let's break it up though.

ok!

**Pull request merged**
