### PR TITLE
Added FP for 2019HLH XLE

### PR DESCRIPTION
**Pull request by mokahata**
Added fingerprint for 2019 Highlander Hybrid XLE to values.py

https://my.comma.ai/f1a9e408dcb1359e/1560736639735/1560738884011

### CODE REVIEW

**Comment by rbiasini** [comment]
Hi @mokahata , unfortunately the fingerprint was not taken in stock mode. Could you please follow the procedure in `get_fingerprint.py`?

See:
https://github.com/commaai/openpilot/blob/devel/selfdrive/debug/get_fingerprint.py

**Comment by rbiasini** [comment]
@mokahata , any update on this?

**Comment by mokahata** [comment]
I re-captured the FP in stock mode but got exactly the same fingerprint...

**Comment by rbiasini** [comment]
@mokahata , I think the drive you posted is not from a Toyota. Can you confirm?

**Comment by mokahata** [comment]
It's 2019 Toyota Highlander Hybrid.

**Comment by rbiasini** [comment]
not sure where the issue is, but this route reallu does not look like from a Toyota:
https://my.comma.ai/cabana/?route=f1a9e408dcb1359e%7C2019-07-18--19-52-27&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Ff1a9e408dcb1359e%2F0a1503538b0c6e8248d005d74bd771f4_2019-07-18--19-52-27&seekTime=-2767203

**Comment by ErichMoraga** [comment]
@mokahata What country was the vehicle purchased in?

**Comment by mokahata** [comment]
I have two cars with OP - Highlander Hybrid and Outback.  They are both purchased in the US.  I've been driving Highlander Hybrid since Feb and just setup Outback a couple of weeks ago.  When I PRed, I only had Toyota with OP but the link above is pointed to my Subaru driving record for some reason.  Please check this link. I can confirm this is 2019 Toyota Highlander Hybrid https://my.comma.ai/94f212077845faf0/1563647071960/1563649593283

**Comment by mokahata** [comment]
Also please disregard the change I made in interface.py.  I meant to PR my Highlander Hybrid's fingerprint in values.py only.

**Comment by mokahata** [comment]
@rbiasini have you guys had chance to review the link I posted [above](https://github.com/commaai/openpilot/pull/703#issuecomment-517509657)?

**Comment by rbiasini** [comment]
@mokahata , I've merged in your fingerprint, except for message 1235 which I have not found in the route you sent me. Support will be in the next openpilot release. Thanks!

**Pull request closed without merging**
