### PR TITLE
process_replay: fix radard replays when radarUnavailable

### PR DESCRIPTION
**Pull request by fredyshox**
Most (all?) radar interfaces, fake the desired radar frequency with `time.sleep` if `carParams.radarUnavailable` is true. Since process_replay sets `NO_RADAR_SLEEP`, it needs to control the frequency by buffering can msgs.

### CODE REVIEW

**Comment by haraschax** [comment]
Is this the only process like this? Maybe we can just have radard follow modeld? I think that probably makes more sense?

**Comment by adeebshihadeh** [comment]
> Is this the only process like this? Maybe we can just have radard follow modeld? I think that probably makes more sense?

That would be nice to have regardless of process replay if we're ok with the extra latency.

**Comment by fredyshox** [comment]
> If we change that, @fredyshox this will be a new pattern for process replay: poll on modelV2 and drain on can.

Gonna look into that, but I believe the current ReplayContext should be able to accommodate that, if it would set up events for `modelV2` and leave `can` be.

**Comment by fredyshox** [comment]
Refactor of radard #29063 will make this unnecessary

**Pull request closed without merging**
