### PR TITLE
Update values.py

### PR DESCRIPTION
**Pull request by praeluceo**
Added support for 2019 Prius Prime Advanced per testing performed on Arne's branch here:
https://github.com/arne182/openpilot/blob/9dffe392ac85bedfb5d234657e167cfd9315a35f/selfdrive/car/toyota/values.py

### CODE REVIEW

**Comment by rbiasini** [comment]
@praeluceo : can you please post a cabana link for that car? We need to be able to verify the fingerprint. Tnx

**Comment by praeluceo** [comment]
https://my.comma.ai/4d1c22feeadd32c7/1562718385317/1562719171601

**Comment by rbiasini** [comment]
@praeluceo the fingerprint of the drive you sent is entirely included in the existing Prius one. Do you happen to have another route?

**Comment by zorrobyte** [comment]
My '19 Prius Prime advanced works perfectly fine with OP, and has since day one. I've ran OP versions all the way back to 0.5.8

IMG_1975

**Comment by rbiasini** [comment]
Ok, thanks @zorrobyte . @praeluceo , let me know if you have extra info and you think this PR should be kept open.

**Pull request closed without merging**
