### PR TITLE
Tesla: Fix for crash in controlsd

### LINKED ISSUE #21530: Crash in controlsd
**Describe the bug**

Crash in controlsd
**How to reproduce or log data**
Engage and wait

Latest master.
Tesla Model S

```
Traceback (most recent call last):
  File "capnp/lib/capnp.pyx", line 1262, in capnp.lib.capnp._DynamicStructBuilder.__setattr__
  File "capnp/lib/capnp.pyx", line 1255, in capnp.lib.capnp._DynamicStructBuilder._set
  File "capnp/lib/capnp.pyx", line 747, in capnp.lib.capnp._setDynamicField
capnp.lib.capnp.KjException: Tried to set field: 'gas' with a value of: '0.4994253880211296' which is an unsupported type: '<class 'numpy.float64'>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/openpilot/selfdrive/manager/process.py", line 36, in launcher
    mod.main()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 673, in main
    controls.controlsd_thread()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 667, in controlsd_thread
    self.step()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 657, in step
    actuators, lac_log = self.state_control(CS)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 455, in state_control
    actuators.gas, actuators.brake, self.v_target, self.a_target = self.LoC.update(self.active, CS, self.CP, long_plan)
  File "capnp/lib/capnp.pyx", line 1264, in capnp.lib.capnp._DynamicStructBuilder.__setattr__
  File "capnp/lib/capnp.pyx", line 234, in capnp.lib.capnp.KjException._to_python
AttributeError: 'NoneType' object has no attribute 'type'
Process controlsd:
Traceback (most recent call last):
  File "capnp/lib/capnp.pyx", line 1262, in capnp.lib.capnp._DynamicStructBuilder.__setattr__
  File "capnp/lib/capnp.pyx", line 1255, in capnp.lib.capnp._DynamicStructBuilder._set
  File "capnp/lib/capnp.pyx", line 747, in capnp.lib.capnp._setDynamicField
capnp.lib.capnp.KjException: Tried to set field: 'gas' with a value of: '0.4994253880211296' which is an unsupported type: '<class 'numpy.float64'>'
```

### PR DESCRIPTION
**Pull request by kennedyshead**
Not sure if this is correct, it sorts the crash in #21530

### CODE REVIEW

**Comment by kennedyshead** [comment]
How about starting to type annotate?

**Comment by pd0wm** [comment]
Where does the numpy value originate from?

**Comment by kennedyshead** [comment]
Not really sure actually, it's not in car port as faik.

**Comment by adeebshihadeh** [comment]
Fixed in 148c202bc4a9d2b5be3c7dfc529da89c62dd7230

**Pull request closed without merging**
