### PR TITLE
Subaru FPv2 values for currently supported models

### PR DESCRIPTION
**Pull request by martinl**
**Description** Here are Subaru FW values from subaru-PR-test branch for each model currently supported in upstream

**Verification** FW values have been submitted and verified working by discord users mentioned in comments

How should we handle adding the FW values - do you need dongle id / route for each car?

### CODE REVIEW

**Comment by pd0wm** [comment]
Can you remove the comments?

@adeebshihadeh I assume we're ok with accepting a big batch at first?

**Comment by adeebshihadeh** [comment]
I’m cool with it. Let’s just remove the comments on the values.

**Comment by martinl** [comment]
I removed the comments

**Comment by adeebshihadeh** [comment]
Thanks @martinl!

**Pull request merged**
