### PR TITLE
Add 2021 Honda Passport

### PR DESCRIPTION
**Pull request by justinmccaffrey**
Add fingerprint for 2021 Honda Passport to honda pilot 2019 car model

Route: 684e8f96bd491a0e|2021-11-02--14-23-37
Discord user: jmac12
```
{'carParams': {'carFingerprint': 'mock',
               'carFw': [{'address': 416944369, 'ecu': 'programmedFuelInjection', 'fwVersion': b'37805-RLV-B220\x00\x00', 'subAddress': 0},
                         {'address': 416952561, 'ecu': 'eps', 'fwVersion': b'39990-TGS-A230\x00\x00', 'subAddress': 0},
                         {'address': 416985329, 'ecu': 'fwdRadar', 'fwVersion': b'36161-TGS-A030\x00\x00', 'subAddress': 0},
                         {'address': 417001457, 'ecu': 'gateway', 'fwVersion': b'38897-TG7-A040\x00\x00', 'subAddress': 0},
                         {'address': 416961521, 'ecu': 'srs', 'fwVersion': b'77959-TGS-A010\x00\x00', 'subAddress': 0},
                         {'address': 416943089, 'ecu': 'shiftByWire', 'fwVersion': b'54008-TG7-A530\x00\x00', 'subAddress': 0},
                         {'address': 416947953, 'ecu': 'transmission', 'fwVersion': b'28101-5EZ-A600\x00\x00', 'subAddress': 0},
                         {'address': 416964849, 'ecu': 'combinationMeter', 'fwVersion': b'78109-TGS-AT20\x00\x00', 'subAddress': 0},
                         {'address': 416950513, 'ecu': 'vsa', 'fwVersion': b'57114-TGS-A530\x00\x00', 'subAddress': 0}],
```

Should i have made a new car? I had been using the 2019 pilot params for the last few months until 8.10 stopped it from working

### CODE REVIEW

**Comment by justinmccaffrey** [comment]
Vehicle is recognized after pushing change over ssh.

**Comment by pd0wm** [comment]
In this case it's best to add it as a new car

**Comment by justinmccaffrey** [comment]
I'm not quite sure how to transfer my route from connect to the CI store. I see `regen.py` and `update_ci_routes.py` but i'm seeing azure token stuff so i'm not sure how this works

**Comment by pd0wm** [comment]
Route should be synced to the CI bucket. Unfortunately that's something we have to do manually.

**Comment by pd0wm** [comment]
Decided to merge it back into the Pilot after all, since splitting it out makes it harder for pilot/passport to fuzzy fingerprint if needed. The extra firmware versions should be fine. Too bad we won't be able to tune them separately.

**Pull request merged**
