### PR TITLE
FP - Toyota Corolla Hatchback Hybrid 2019 Excite (Israel)

### PR DESCRIPTION
**Pull request by bharel**
This pull requests adds a fingerprint for Toyota Corolla Hatchback Hybrid 2019 Excite (Israel).

How do I enable stock though?

### CODE REVIEW

**Comment by ErichMoraga** [comment]
Don't forget to include a Cabana share link.

**Comment by bharel** [comment]
[Cabana link](https://my.comma.ai/cabana/?route=50ef592d1c5f5e39%7C2019-12-31--05-08-19&exp=1609440222&sig=kqZEN69pgXToqha6LQYbblWaPaUzCdNGG28PUC%2BWIec%3D&max=-1&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F50ef592d1c5f5e39%2F5a11ade2ffc0724ba24a0536f4817b18_2019-12-31--05-08-19)
It seems like there are some discrepancies between OP information on-screen and dashboard information:

1. The set ACC speed, written on the car dashboard fluctuates between 3 to 5 kph over the max seen on OP. If the car dashboard say's ACC is set on 100kph, OP says it's on 97.
2. Car's speed as shown on dashboard, is +-2 kph than the speed shown on OP.
3. OP does not disengage on turn signals, so I need to either cancel it manually or fight the steering wheel to change lanes.
4. The ACC distance-keep setting doesn't work (maybe it's just not implemented in OP)?

Other than these issues which are frankly quite small, OP works amazingly well.

**Comment by ErichMoraga** [comment]
This is all very old news.  Spend more time in Discord, read the pins, use the search feature, etc.

**Comment by bharel** [comment]
Alright, if so, are there any fixes needed in order to to merge the PR?

**Comment by ErichMoraga** [comment]
Since you took my advice, and looked through Discord, you already know...

1. Overshooting speed comes down to longitudinal tuning... #tuning in Discord. 

2. Toyota speed discrepancy is intentional from the mfgr.  Discord search "speed discrepancy" FTW.

3. WAD, but... will actually change soon.  Discord search "ALC" FTW.

4. WAD... like you said, not implemented yet. TSS-P vehicles like mine have options like @Arne's DSU Buttons project, @wocsor's Smart DSU (potentially renamed to ECU Interceptor), or just leave the DSU connected (you don't have that option with your TSS2 Corolla).  Discord search any of those fun words... FTW, and if you run into issues, give @Chas a holler!

**Comment by bharel** [comment]
Oh I just wondered if there's anything else I need to do for the PR.
I understood these 4 issues were already known like you said in your first comment.

**Comment by ErichMoraga** [comment]
This PR is for a fingerprint, and should be kept simple.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master!

**Pull request closed without merging**
