### PR TITLE
Added old firmware version to support Lexus NX 2020

### PR DESCRIPTION
**Pull request by grokker001**
Lexus NX 2020 is already supported, however, some Lexus NX 2020 have the older firmware version, and OP is not able to recognize it. 
The older firmware version is added in this PR.

### CODE REVIEW

**Comment by sshane** [comment]
Can you provide the dongle id this came frmo?

**Comment by grokker001** [comment]
@sshane 

> Can you provide the dongle id this came from?

Sent it to your email.

**Comment by grokker001** [comment]
> Can you provide the dongle id this came from?
c7a06a775d4a0b29

**Comment by grokker001** [comment]
> Can you provide the dongle id this came from?

c7a06a775d4a0b29

**Comment by sshane** [comment]
You're missing your fwdRadar FW: `b'\x018821F3301400\x00\x00\x00\x00',`

**Pull request merged**
