### PR TITLE
Reverse Car Port: Merge Pilot_2019 into Pilot

### PR DESCRIPTION
**Pull request by vanillagorillaa**
The 2019 Pilot was made it's own car port due to having a different radar keep alive command (back when camera was disconnected and we had to keep the radar happy). https://github.com/commaai/openpilot/pull/334 as well as using a different message and signal for car_gas. The car_gas code was refactored in https://github.com/commaai/openpilot/pull/22010 so now all Honda's use the same message/signal. 

Because of these two differences no longer being an issue, I have gone ahead and merged these into one. Since the Honda Pilot had some firmware versions that the Pilot_2019 did not, and to avoid breaking support for these, I have removed these values and left only the common values between each vehicle. 

Probably want to get someone with a 2019 Pilot to test this

### CODE REVIEW

**Comment by pd0wm** [comment]
Any reason why we shouldn't just merge the FW versions?

**Comment by vanillagorillaa** [comment]
For ECU's that both vehicle definitions had this is what I did. I removed a few ECU's that were only defined in one vehicle because I think this would cause some vehicles to fail fingerprinting unless they had that version. Unless I'm wrong on this, in which case I can certainly add those back in.

**Comment by VirtuallyChris** [comment]
Yeah you’re right about that

**Comment by pd0wm** [comment]
If the ECUs are not in the list of essential ECUs (https://github.com/commaai/openpilot/blob/master/selfdrive/car/fw_versions.py#L255) `[Ecu.engine, Ecu.eps, Ecu.esp, Ecu.fwdRadar, Ecu.fwdCamera, Ecu.vsa]`, being absent shouldn't be an issue.

**Comment by vanillagorillaa** [comment]
The ones originally removed are non essential, so added back in, and now we just have a simple FW merge

**Comment by pd0wm** [comment]
LGTM

**Pull request merged**
