### PR TITLE
Mazda: Add CX-5 2023 to supported cars

### PR DESCRIPTION
**Pull request by Jafaral**
Confirmed working by a couple of users.

### CODE REVIEW

**Comment by sshane** [comment]
Do you have a dongle id for a user? Are their fingerprints already in openpilot?

**Comment by Jafaral** [comment]
@sshane 

e36424ef0cb55df0

**Comment by adeebshihadeh** [comment]
Confirmed with VIN that it's a 2023. It was missing a camera FW version.

**Comment by Jafaral** [comment]
Ah,  make sense sense OP falls  back to fuzzy matching and new users may not know what that means. Thanks @adeebshihadeh

**Pull request merged**
