### PR TITLE
Toyota: extend wheel speed factor to 2017 Lexus RX

### PR DESCRIPTION
**Pull request by cecnic1989**
**Description** applying the wheelSpeedFactor fix discussed in #2106 to LEXUS_RX

### CODE REVIEW

**Comment by pd0wm** [comment]
Thanks! Wasn't sure if the older model was affected too. Do you have a drive/dongle ID so I can quickly check if the factor is correct for your car too?

Do you know if the hybrid version is affected as well?

**Comment by cecnic1989** [comment]
Sure, my dongle Id is 515dd251c598ea16. I just checked comma connect, and I only have three drives there. I don't think any contain highway drives to show the rev issue. Let me know if you need me to do some highway driving for this PR.

**Comment by cecnic1989** [comment]
I'm not sure if the hybrid version is affected. All the community members that I've been talking to are non-hybrid RX owners.

**Comment by adeebshihadeh** [comment]
The parameters for all supported RXs are very similar. We should probably just merge them.

**Comment by adeebshihadeh** [comment]
Merged all the RX params in #23374.

**Comment by cecnic1989** [comment]
Cheers thanks Adeeb! Yeah I’m not sure why all the other params are slightly different. It’s should be fine to merge them.

**Comment by adeebshihadeh** [comment]
@cecnic1989 the tuning for your car changed slightly after merging that PR. Let me know how it feels now!

**Pull request closed without merging**
