### PR TITLE
Delphi ESR

### PR DESCRIPTION
**Pull request by AdasCoder**
Delphi ESR used in Volvo Vehicles.

### CODE REVIEW

**Comment by AdasCoder** [comment]
DBC file for the Radar used in passenger cars from Volvo, such as the V60, S60, V40 e.t.c.

**Comment by rbiasini** [comment]
This is great, thanks. Would you mind making this PR for https://github.com/commaai/opendbc instead? the latest version of opendbc will automatically be included into the next openpilot release.

**Comment by AdasCoder** [comment]
Sure. I've opened a pull request for the openDBC repository instead. I wasn't aware of that one yet.

**Comment by csouers** [comment]
@AdasCoder Should probably close this pull request now that you've made one over at opendbc.

**Pull request closed without merging**
