### PR TITLE
Rename RGB vision streams to match YUV streams

### PR DESCRIPTION
**Pull request by gijskoning**
I am going to take a look at issue https://github.com/commaai/openpilot/issues/23916 and noticed the confusion in the names. 

Renaming VISION_STREAM_RGB_.. to match yuv names like VISION_STREAM_ROAD
The yuv stream names were changed after pr https://github.com/commaai/openpilot/pull/23071
VISION_STREAM_RGB_BACK -> VISION_STREAM_RGB_ROAD
VISION_STREAM_RGB_FRONT -> VISION_STREAM_RGB_DRIVER

Refactor also done in Cereal. Includes Cereal bump.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Great first step for #23916 :)

Can you open the matching cereal PR?

**Comment by adeebshihadeh** [comment]
Nice first PR! Looking forward to the CARLA PR!

**Comment by gijskoning** [comment]
I had no experience in submodules pr's before. Thanks for merging the one in cereal

**Comment by ebadi** [comment]
Hi @adeebshihadeh,  does this PR breaks the openpilot's integration with CARLA?

**Pull request merged**
