### PR TITLE
 VW MQB: Add FW for 2015 VOLKSWAGEN GOLF 7TH GEN

### PR DESCRIPTION
**Pull request by Saber422**

### CODE REVIEW

**Comment by jyoung8607** [comment]
Thank you for the data! comma will need the dongle ID/route in order to verify and merge.

**Comment by sshane** [comment]
@Saber422 any update? You just need to post what it says for dongle id in Device settings.

**Comment by Saber422** [comment]
I forgot to save the route file for this car, so now I have no data in my cabana. The car owner had installed window tint on the windshild that blocked GPS signals, resulting in a trip with no GPS information. Therefore, I suggested that he should not pair his account before replacing the window tint to avoid his account being banned by server. After I meet with the car owner, I will provide the Route ID of this car.

**Comment by Saber422** [comment]
I have time to meet this car, and setup my C3 on this car.(I can't get GPS since his windows tint is with metal)
@sshane route name ：0bbe367c98fa1538|2023-04-02--09-02-57--0

**Pull request merged**
