### PR TITLE
framereader: support hardware decoding

### PR DESCRIPTION
**Pull request by deanlee**
currently supports CUDA, ~MediaCodec and VideoToolbox~

### CODE REVIEW

**Comment by pd0wm** [comment]
Can we detect which ones are available and automatically enable them?

**Comment by deanlee** [comment]
It may take at least 150 lines of code to accurately detect the hardware type （https://ffmpeg.org/doxygen/trunk/hwdevice_8c_source.html）.it might be better to implement it in another Pr later if necessary. what do you think?

**Comment by pd0wm** [comment]
Can you add the flag to override the choice (and force no hw decoding)?

**Comment by pd0wm** [comment]
Is it worth it to support videtoolbox and mediacodec? From my quick testing they don't seem to support hevc. Or is that a problem with my setup?

**Comment by pd0wm** [comment]
Noticed ui.py doesn't work when using `cuda` as a hw decoder (can't match the buffer size to a camera).

**Comment by deanlee** [comment]
Then we can only support CUDA for the time being.
auto detection is complicated.  I suggest still using flag for hw-decode, what do you think?

**Comment by deanlee** [comment]
> Noticed ui.py doesn't work when using `cuda` as a hw decoder (can't match the buffer size to a camera).

Hardware decoder requires 16-pixels aligned height. I'll fix this issue

**Comment by deanlee** [comment]
> Noticed ui.py doesn't work when using `cuda` as a hw decoder (can't match the buffer size to a camera).

fixed

**Comment by pd0wm** [comment]
Just supporting cuda is fine. Think it can be default on, but disabled using `--no-cuda` or something like that.

**Pull request merged**
