### PR TITLE
Add support for 2019 Civic Sedan 1.6L Diesel with CVT

### PR DESCRIPTION
**Pull request by csouers**
Unlike other 2019 civics, this car doesn't steer down to 2mph. It's 12mph like the others. Differences in GEARBOX and GAS_PEDAL_2 frames like CRV HYBRID and some other obscure cars like Odyssey and Pilot.

Public cabana route: https://my.comma.ai/cabana/?route=d83f36766f8012a5%7C2020-02-05--18-42-21&exp=1612469711&sig=wgaItnHLgnNBZ1FDm3QS2JdO%2F%2BwtQTIs6illZcfsvik%3D&max=12&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2Fd83f36766f8012a5%2Fa640feac185d79812f37e7f7a2553597_2020-02-05--18-42-21

Todo:
- [ ]  Verify firmware fingerprint is successful on this car. Car belongs to @ffhspa

### CODE REVIEW

**Comment by pd0wm** [comment]
A final thing, as we don't add new Honda/Toyota fingerprints we need to make sure it only fingerprints using FW query. Add a `IGNORED_FINGERPRINTS` list to values, like for the RAVH_TSS2: https://github.com/commaai/openpilot/blob/master/selfdrive/car/toyota/values.py#L270

To make sure the test still works, set 'fingerprintSource' to 'fixed' in the test_car_models.py route definition. Like: https://github.com/commaai/openpilot/blob/master/selfdrive/test/test_car_models.py#L292

**Comment by csouers** [comment]
Thank you. Will revise this and also the Euro CRV PR with this in mind.

**Comment by csouers** [comment]
@pd0wm Do you want me to remove the can-based fingerprint from this as well?

**Comment by csouers** [comment]
@pd0wm I think this is good to go. I'll squash and force push again right now.

**Pull request merged**
