### PR TITLE
Stop-n-go hack

### PR DESCRIPTION
**Pull request by pratikchhatbar**
Stop-n-go hack

### CODE REVIEW

**Comment by pratikchhatbar** [comment]
Stop-n-go hack

**Comment by ErichMoraga** [comment]
Nice try!

**Comment by rbiasini** [comment]
Which car? You should add it to the list of cars with stop and go capability. See `values.py`

**Comment by geohot** [comment]
The problem with disabling this is if you are on a hill, then the car will ignore acceleration commands. Better to be reliability annoying than unreliably good.

**Comment by pratikchhatbar** [comment]
I like it to be PREDICTABLY annoying occasionally (uphill) than CONSISTENTLY annoying.

I prefer to OCCASIONALLY push the gas on uphill when the car does not move (which is WAY less than always) than ALWAYS keep hitting the cruise stick in the rush hour.

**Comment by pratikchhatbar** [comment]
> Nice try!

Thanks :-D - would you unblock me now ;-)

**Comment by ErichMoraga** [comment]
Just make your own fork, or edit the file directly on your EON.

**Comment by pratikchhatbar** [comment]
> Just make your own fork, or edit the file directly on your EON.

exactly what i did: PATCH-3 on my fork and i push gas when uphill. I know you like this hack!

**Comment by ErichMoraga** [comment]
That's not really how to do it.

**Comment by pratikchhatbar** [comment]
> That's not really how to do it.

suggest a better way please! thanks in advance.

**Comment by ErichMoraga** [comment]
The main problem is you're making PRs directly against Comma's code... which wastes a lot of our time.  Make changes to your own fork, not the origin. Plenty of videos on YouTube for GitHub 101.

**Comment by pratikchhatbar** [comment]
Apologies :-) and thanks for helping me help you save time! A rationalizing comment next to SnG in the code similar to George's response would've prevented it. Sorry for being redundant here and please let me know what i missed. Peace!

**Pull request closed without merging**
