### PR TITLE
mapsd: release MapRenderer on exit

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Left it running for a bit and doesn't quit cleanly:
```
comma@tici:/data/openpilot/selfdrive/navd$ ./mapsd
gbm_create_device(156): Info: backend name is: msm_drm
Starting listener for: navd
: [ ERROR ]  "{unknown}[Style]: Failed to load sprite: HTTP status code 403"
: [ ERROR ]  "{unknown}[Style]: Failed to load source composite: HTTP status code 403"
: [ ERROR ]  "{unknown}[Style]: Failed to load sprite: HTTP status code 403"
^CcStopping listener for: navd
Segmentation fault (core dumped)
```

**Comment by deanlee** [comment]
> ^CcStopping listener for: navd

the vipc_server has been released. so the `m_map`, `sm`, `pm`, `vipc_server` should has been released (destructors are called in reversed order). the segfault should be caused by releasing one of `fbo`, `surface`, and `ctx`.

**Comment by adeebshihadeh** [comment]
Have you checked it out with valgrind?

**Comment by deanlee** [comment]
running valgrind on the pc seems to have no problem.

Hope it can exit normally on device after [36b400c](https://github.com/commaai/openpilot/pull/29059/commits/36b400cdfbde2b885f5f01816f6b605c49f1e91f)

**Comment by adeebshihadeh** [comment]
I'll test, but doesn't that defeat the whole point of the unique_ptr?

**Comment by deanlee** [comment]
Yes, we can get rid of the unique_ptr after it can exit normally.

**Comment by adeebshihadeh** [comment]
This doesn't seem to completely fix the issue.

**Comment by adeebshihadeh** [comment]
This seems to be fixed since we moved mapsd to the CPU.

**Pull request closed without merging**
