### PR TITLE
Adds check to bosch for passive mode

### PR DESCRIPTION
**Pull request by energee**
Allows passive mode on Bosch vehicles.

In order to use Honda Sensing in any bosch, you must unplug your EON which means you can't record drives.

If Can 2 and 3 are jumped on Bosch giraffe, openpilot should check for this and switch to passive mode.

### CODE REVIEW

**Comment by rbiasini** [comment]
@energee, yeah, we need a passive check for those cars. what if we check for 0xe4 in the fingerprinted messages?
The radar should be reforwarding 0xe4 from acc_can tothe main can, right?

**Comment by energee** [comment]
I think this is the only way to do it, the radar does forward 0xe4 to F-Can but its always persistent with empty bytes + counter checksum even if camera is unplugged. Once you start sending 0xe4 to on the private can, it populates that data into its message on F-Can.

**Comment by rbiasini** [comment]
mmm... is reading all empty bytes in 0xe4 (except cnt and chksum) a sufficient indication that the camera is disconnected?

**Comment by energee** [comment]
There are empty bytes on 0xe4 from when camera is connected or disconnected.

There is likely a fault bit we could check on can 0 that goes high when private can is not forwarding (and dash is lit up with ambers). This would be less invasive but since there could be other factors that result in these faults other than lack of forwarded messages, I was concerned that this could create a false positive scenarios.

**Comment by energee** [comment]
@rbiasini Confirming that there is an indirect way to detect "an issue" and switch to passive mode false. I still suggest the current code since it directly checks presence of 0xe4 going to radar from camera whereas the alternate checks for an "ACC problem" (which could be more appropriate to default to passive) but we would be using "ACC problem" to confirm that we want openpilot.

**Comment by maxduan123** [comment]
I really want to add this to my eon, but Im not good at editing files in ssh, do you know how to do it in one line command in eon?

**Comment by energee** [comment]
@maxduan123 
cd /data; rm -Rf openpilot; git clone -b passive-mode git@github.energee/openpilot.git

**Comment by maxduan123** [comment]
@energee 
I got this message

> fatal: repository 'git@github.energee/openpilot.git' does not exist

**Comment by maxduan123** [comment]
@energee 
I tried   
cd /data; rm -Rf openpilot; git clone -b passive-mode git://github.energee/openpilot.git

got this
fatal: Unable to look up github.energee (port 9418) (No address associated with hostname)

**Comment by chrisj951** [comment]
When trying this on my insight the ACC/LKAS error out when stock adas is off and OP is in control.

**Comment by energee** [comment]
I'm closing this, we don't even have 4 switches on the bosch giraffe anymore

**Pull request closed without merging**
