### PR TITLE
openpilot 0.3.3

### PR DESCRIPTION
**Pull request by geohot**
This is the space for public comment before we merge into release.

### CODE REVIEW

**Comment by pjlao307** [comment]
After installing 0.3.3 and rebooting I get a blank screen after the NEO splash screen.  After several reboots the NEO then would not even connect to Wifi.  I ended up having to reflash the NEOS onto the phone and reinstalling OpenPilot.

Now everything comes up however it's not logging into Google.  After logging in and allowing access to Chffr it stays logged out.

**Comment by geohot** [comment]
How did you install it? When this happens, you can also use adb to connect to the phone to recover.

**Comment by pjlao307** [comment]
I had my branch running but also had the release repo on the phone in another folder so I renamed the release folder back to /data/openpilot and did git pull; git checkout devel; reboot.

It looks like now it's back to normal. It finally was able to log into google.

**Comment by vntarasov** [comment]
+1, having same issue.
oneplus3t, volt branch (issue happened after merging latest develop changes)

Do we have two separate issues here, 1) Google login and 2) phone getting unresponsive to a point it requires flashing / reset?

@geohot, does sign-in logic require board to be connected & powered on? 

@geohot, after I couldn't ssh into phone over WiFi, I couldn't connect to it with adb either. Had to do a factory reset (without flashing) to be able to do anything.

**Comment by geohot** [comment]
sign-in logic shouldn't require board.

unplug and replug to after boot up to have the phone adb

**Comment by vntarasov** [comment]
@geohot, re-plugging didn't fix adb connectivity.

I could still ping Neo over wifi, but not ssh into it.

For me, it was a gradual decline in responsiveness. From visibly lagging visiond ('top'  was showing plenty of idle CPU though), to a totally unusable system day after.

I'll do more troubleshooting tonight, anything specific you'd want me to look into?

**Comment by pjlao307** [comment]
For me, when I noticed wifi wasn't working on the NEO I was still able to adb into the phone and when I looked at top I didn't see any of the OpenPilot services running.

**Comment by TheMutley** [comment]
Still driving on it , had few intermittent issues trying to ssh to it , but was able to manage to connect to it in the end. Had theses with previous versions before. 

Going from the driving mode to the wallpaper screen seem slower . Also the whole system seem to lag a tiny bit, again more than previous. 

Finally , saw a difference with new visiond when a car cut me close in a lane , the path planning is jerking left and right a bit and I have to take control back for a couple of seconds. Don't recall seeing this with 0.3.1. I will put it back and give a try to see if I get the same behavior.

**Comment by geohot** [comment]
@pjlao307 You can forward the ssh port over adb and attach to the tmux session. If someone can repro and paste the tmux contents we can debug a lot better.

@vntarasov Huh, never seen this gradual decline before. Out of space?

**Comment by pjlao307** [comment]
@geohot I'm not sure how to do that.  Not really familiar with adb or tmux.  Would it be easier from a user perspective to maybe have a debug switch in the code that can log all the tmux output to a file that can then be sent to comma.ai?

**Pull request merged**
