### PR TITLE
ui/map: hide icon if no maneuver type

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by sshane** [comment]
It looks like there's one navInstruction packet that's valid with no text, type, but distance is still present when you reach your destination. Fixing that in navd sounds like the real fix (since it still shows the distance here, right?). Did you have any other cases where type is empty?

image

**Comment by deanlee** [comment]
I'm not sure what else would cause maneuver to be empty. I didn't check the packages in the logs. just thought it would better/safer to  complete the if-else check.

**Comment by sshane** [comment]
Is icon_01 reset somewhere? Does it look like that if there is no type, it will show the previous icon? Or does that realistically never happen?

**Comment by sshane** [comment]
it's added conditionally in parse_banner_step, so it's possible it's empty based on the API response

**Pull request merged**
