### PR TITLE
24625 pagination to list upload queue

### LINKED ISSUE #24625: athena: pagination to listUploadQueue
listing all items in the upload queue is much more manageable with pagination if the upload queue is very large

this also creates a consistently fast way to check if the queue is empty (limit results to first item)

assuming results returned are always sorted consistently we could add two new params to listUploadQueue to accomplish this:

start = the file name to start returning results after
limit = max number of results to return
start can be an empty string by default to start at the beginning, and then you pass the last file name returned in subsequent calls to get the next page of results (excluding the start file name you passed)

you know you have received all results when you get less than the limit or no results (if we don't like this approach we could enhance what is returned to include if there are more results)

### PR DESCRIPTION
**Pull request by AndjelaMandic-SYRMIA**
Fixes #24625 
FYI @gregjhogan @adeebshihadeh @sshane 

**Description**
Added pagination to listUploadQueue method.

**Verification**
Changed the test_athenad.py file for the listUploadQueue function. Ran all the tests, they passed successfully.

### CODE REVIEW

**Comment by gregjhogan** [comment]
requiring an exact match on the `start` param doesn't really work because the value could no longer exist

**Comment by gregjhogan** [comment]
Closing because the logic is flawed and it also seems pretty sloppy (for example it doesn't break out of the for loop when it finds a match).

**Comment by AndjelaMandic-SYRMIA** [comment]
@gregjhogan Thank you for your input. I will look into it again during this week.

**Comment by AndjelaMandic-SYRMIA** [comment]
> requiring an exact match on the `start` param doesn't really work because the value could no longer exist

@gregjhogan 
Sorry, I didn't manage to get to this sooner. I'm not sure I follow why do you think that searching for exact match wouldn't work? At the start of the loop I set `start_index` to 0, so if the element isn't found it will give us all remaining sorted elements from the `upload_queue`. From what I understood in the code, this is a list of all items (videos) that are ready for the upload, and that they should be sorted by name (closest thing I think is the path value). 

Could you explain in a bit more detail what exactly you wanted to be done here? 

Also, I added break in the for loop, sorry I'm a novice to programming so any feedback is greatly appreciated.

**Pull request closed without merging**
