### PR TITLE
Fingerprinting v2 support for Nissan vehicles

### PR DESCRIPTION
**Pull request by robin-reckmann**
Added fpv2 support for Nissan vehicles.

Tested with Nissan Leaf 2018 (IC),Nissan X-Trail 2017 and Nissan Altima.

### CODE REVIEW

**Comment by pd0wm** [comment]
@adeebshihadeh Can you quickly test this PR on a Toyota and the Audi and post the routes? There is an overlap in engine address but the query (this PR requests `VEHICLE_MANUFACTURER_ECU_SOFTWARE_NUMBER` instead of `APPLICATION_SOFTWARE_IDENTIFICATION`) is different.

@robin-reckmann Is it really necessary to go through the whole sequence of `TESTER_PRESENT_REQUEST, DEFAULT_DIAGNOSTIC_REQUEST, EXTENDED_DIAGNOSTIC_REQUEST, NISSAN_VERSION_REQUEST_STANDARD`? What happens if you leave out the first 1, 2, or 3 steps.

**Comment by robin-reckmann** [comment]
@avolmensky Could you provide a route for the xtrail?

**Comment by robin-reckmann** [comment]
@pd0wm : Using only NISSAN_VERSION_REQUEST_STANDARD works! Never tested that :-) Thanks for the hint. I'll remove the first 3 commands from the sequence.

**Comment by pd0wm** [comment]
> @pd0wm : Using only NISSAN_VERSION_REQUEST_STANDARD works! Never tested that :-) Thanks for the hint. I'll remove the first 3 commands from the sequence.

Ah, great! That also reduces the chance of a different car responding to the query.

**Comment by robin-reckmann** [comment]
> > @pd0wm : Using only NISSAN_VERSION_REQUEST_STANDARD works! Never tested that :-) Thanks for the hint. I'll remove the first 3 commands from the sequence.
> 
> 
> 
> Ah, great! That also reduces the chance of a different car responding to the query.

I removed the first command of the nissan specific queries as wel and it still works for 13/15 Ecus using --Scan (including all the ones used for fingerprinting the leaf). Should we also remove these if the other Nissans also work without it?

**Comment by pd0wm** [comment]
Yeah, the shorter the better since that will improve fingerprinting speed for all cars.

**Comment by robin-reckmann** [comment]
The route using the latest commit (with reduced standard query): fd3b0ef05a984a10|2021-11-01--22-03-13

**Comment by robin-reckmann** [comment]
I stumbled upon the same issues (missing frames in multi-frame packers) as discussed in #21333. For the Leaf is only happens for 0x79d. After confirming, that this happens also for other vehicles, we might remove this particular ECU to ensure reliable fingerprinting.

**Comment by avolmensky** [comment]
Route from the X-Trail: `2c976ff547f21516|2021-11-03--03-26-28`

**Comment by adeebshihadeh** [comment]
Here's a route from our Rav4: `4cf7a6ad03080c90|2021-11-03--15-14-40`. Our A3 isn't at the office and may not be available until Friday. Perhaps @jyoung8607 can get us a quick route.

**Comment by jyoung8607** [comment]
> Our A3 isn't at the office and may not be available until Friday. Perhaps @jyoung8607 can get us a quick route.

A test startup with this branch on my Tiguan: `3cfdec54aa035f3f|2021-11-03--23-24-53`

At a quick glance everything seems normal.

**Comment by pd0wm** [comment]
Looks good! Toyota engines don't respond to uds 0x22 at all (service not supported), while the VW gives an out of range error for `VEHICLE_MANUFACTURER_ECU_SOFTWARE_NUMBER`

**Comment by robin-reckmann** [comment]
I'm not entirely sure that 0x742 is really the EPS since the FW looks a bit different. But I added it nevertheless.

**Comment by robin-reckmann** [comment]
Altima EPS needs the diagnostic request part. Leaving it in then...

**Pull request merged**
