### PR TITLE
Optimized Lateral Tuning LEXUS_ES_TSS2 and LEXUS_ESH_TSS2

### PR DESCRIPTION
**Pull request by rpaulhanna**
Optimized steering ratio, tire stiffness and lateral tuning parameters for LEXUS_ES_TSS2 and LEXUS_ESH_TSS2.

Changes to OP versions beyond 0.8.4 exposed lateral tuning deficiencies in the LEXUS_ES_TSS2 and LEXUS_ESH_TSS2 resulting in cyclic oversteer/correct cycles throughout sharper curves both at low-speed in city-driving and high-speed interstate driving.  The result was a feel in the vehicle that the car was fighting its way through turns in a series of short, choppy segments rather than a smooth, continuous path.

Mechanically, the Avalon and ES are practically identical as both have a 113.0” wheelbase and the exact tire/wheel size.  So, initially, I started with the Avalon lateral turning parameters to correct the aforementioned problem, but adjusted the curb weight to the approximate mid-point trim-level weight (ES 300h) of the ES range (3,690-3,780).

After testing, the Avalon’s kp & ki numbers in the ES seemed a bit low as there was a hint of understeer and ever-so-slight sharper correction at turn entry.  After increasing these numbers halfway between the Avalon numbers and the default 0.6 & 0.1 that was assigned to the ES, the result improved.  Further testing at 0.4925, 0.0825 achieved optimum performance in both low and high speed sharper curves with smooth entry and maintenance of the curve on centerline and no richochet or ping-pong effect.  On straights, the car maintained centerline smoothly as well with no ping-pong or drift.

The following route demonstrates the smoothness and accuracy of the aforementioned tuning parameters in city and freeway driving:

3a5c5101bd71ad5d|2021-07-30--04-21-08

### CODE REVIEW

**Comment by pd0wm** [comment]
The values look reasonable to me. 

With these tuning changes we require feedback from one or two other users with the same car. Can you ask some people on discord to try the new tune and report back in this GitHub issue?

**Comment by rpaulhanna** [comment]
> The values look reasonable to me.
> 
> With these tuning changes we require feedback from one or two other users with the same car. Can you ask some people on discord to try the new tune and report back in this GitHub issue?

Thanks Willem. I will try and solicit some other ES users on Discord this afternoon. By the way, I enjoyed your presentation on the Comma_Con livestream yesterday. Congrats on all the progress!

**Comment by pd0wm** [comment]
Why was this closed?

**Comment by rpaulhanna** [comment]
Sorry Willem.  Closing it was an unintended (auto) accident due to reseting master & master-ci branches on my fork.  Honestly, though, I reached out to about 5 ES users via Discord and there doesn't seem to be a lot of interest in this at the moment.  I'll keep running these numbers on my fork and if anyone sees this or needs assistance with tuning to that spec, I'll help where I can and then we can revisit this optimization in the future.  Thanks.

**Comment by salah608** [comment]
I was just able to try this tune on a 4 hour drive and my 2019 Lexus ES feels much more stable around sharp curves no oversteer or correct cycles.

**Comment by rpaulhanna** [comment]
> I was just able to try this tune on a 4 hour drive and my 2019 Lexus ES feels much more stable around sharp curves no oversteer or correct cycles.

Thanks for trying that out.  I'll re-open this and when enough users report positive feedback or recommended adjustments to the values, hopefully it can get merged.

**Comment by rpaulhanna** [comment]
I'm not sure why when I tried to re-open the pull request it added so many other unrelated commits/comments into my pull request.  I don't know how to fix that.  So, I'm just going to leave this closed.

**Pull request closed without merging**
