### PR TITLE
GM: soft disengage on PCM fault

### PR DESCRIPTION
**Pull request by vntarasov**
Happens when
- first attempt to engage is done with "resume" instead lf "set" button.
- attempt to engage outside of PCM's speed limits (shouldn't happen unless people override min allowed engage speed).
- pre-enable doesn't work on 2018 Volt.

In all those cases, showing openpilot as engages is confusing, because car ignores gas commands.

### CODE REVIEW

**Comment by kishkaru** [comment]
If I understand correctly, does the soft disengage for PCM speed limit only apply to 2017 Volts? Since 2018 Volt can resume from 0, thus does not have a PCM speed limit?

**Comment by rbiasini** [comment]
@vntarasov , you also need to define the 2 alerts (disengage and no-entry) in the alert database file. Other than that it looks good. Tnx

**Comment by vntarasov** [comment]
@rbiasini I already see controlsFailed and comtrolsFailedNoEntry in https://github.com/commaai/openpilot/blob/860a48765d1016ba226fb2c64aea35a45fe40e4a/selfdrive/controls/lib/alerts.py#L359

**Comment by rbiasini** [comment]
@vntarasov , if this PR is still relevant, I'm ok merging it.

**Comment by vntarasov** [comment]
@rbiasini Still relevant. Pretty much every new openpilot user with 2018 Volt is asking "openpilot is engaged but car doesn't accelerate".

**Comment by rbiasini** [comment]
merged internally. will be in 0.5.12. Thanks.

**Pull request closed without merging**
