### PR TITLE
agnos casync script improvements

### PR DESCRIPTION
**Pull request by jnewb1**

### CODE REVIEW

**Comment by jnewb1** [comment]
```{
  "build_metadata": {
    "channel": "finish-upload",
    "openpilot": {
      "version": "0.9.7",
      "release_notes": "Version 0.9.7 (2024-XX-XX)\n========================\n* New driving model\n* Adjust driving personality with the follow distance button\n* Support for hybrid variants of supported Ford models",
      "git_commit": "101bd48b8d91fa634e4ab945a186ba70c896f0f7",
      "git_origin": "https://github.com/commaai/openpilot",
      "git_commit_date": "'1712787761 2024-04-10 22:22:41 +0000'",
      "build_style": "unknown",
      "is_dirty": true
    }
  },
  "manifest": [
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-boot.caibx"
      },
      "path": "/dev/disk/by-partlabel/boot_a",
      "size": 15636480,
      "full_check": true,
      "hash_raw": "f0de74e139b8b99224738d4e72a5b1831758f20b09ff6bb28f3aaaae1c4c1ebe"
    },
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-abl.caibx"
      },
      "path": "/dev/disk/by-partlabel/abl_a",
      "size": 274432,
      "full_check": true,
      "hash_raw": "eeb89a74c968a5a2ffce96f23158b72e03e2814adf72ef59d1200ba8ea5d2f39"
    },
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-xbl.caibx"
      },
      "path": "/dev/disk/by-partlabel/xbl_a",
      "size": 3282672,
      "full_check": true,
      "hash_raw": "bcef195b00a1ab685da601f4072722569773ab161e91c8753ad99ca4217a28f5"
    },
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-xbl_config.caibx"
      },
      "path": "/dev/disk/by-partlabel/xbl_config_a",
      "size": 98124,
      "full_check": true,
      "hash_raw": "19791056558c16f8dae787531b5e30b3b3db2ded9d666688df45ce1b91a72bac"
    },
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-devcfg.caibx"
      },
      "path": "/dev/disk/by-partlabel/devcfg_a",
      "size": 40336,
      "full_check": true,
      "hash_raw": "be44b73dda5be840b09d5347d536459e31098da3fea97596956c0bdad19bdf27"
    },
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-aop.caibx"
      },
      "path": "/dev/disk/by-partlabel/aop_a",
      "size": 184364,
      "full_check": true,
      "hash_raw": "5d764611a683d6a738cf06a1dcf8a926d0f47b5117ad40d3054167de6dd8bd0f"
    },
    {
      "type": "partition",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/agnos-releases/agnos-9.7-system.caibx"
      },
      "path": "/dev/disk/by-partlabel/system_a",
      "size": 10737418240,
      "full_check": false,
      "hash_raw": "0f69173d5f3058f7197c139442a6556be59e52f15402a263215a329ba5ec41e2"
    },
    {
      "type": "path_tarred",
      "path": "/data/openpilot",
      "casync": {
        "caibx": "https://commadist.blob.core.windows.net/openpilot-releases/0.9.7-101bd48b8d91fa634e4ab945a186ba70c896f0f7-unknown.caibx"
      }
    }
  ]
}```

**Comment by adeebshihadeh** [comment]
Nice. Add an `ab: True` field?

**Comment by jnewb1** [comment]
hmm, making the casync agnos build takes way to long to run on device..

**Comment by jnewb1** [comment]
even takes 20 minutes on the pc, doesn't look like there is any option for multithreading...

**Pull request merged**
