### PR TITLE
Hyundai: support HDA1 EV6 and Ioniq 5

### PR DESCRIPTION
**Pull request by hoomoose**
**Simple code fix to make OP work with hda1 ev6 & I5 - no full port required!**

**Description** 
OP does not work with HDA1 versions of Kia EV6 or Hyundai Ioniq5 giving CAN Errors. Changing all instances of the ACCELERATOR signal to be based on "alt_buttons" flag rather than "hda2" flag fix this issue. This replaces the need for the Car Port PR https://github.com/commaai/openpilot/pull/25629 that has subsequently been closed.

Fixes:
carstate.py
1) The ACCELERATOR signal on the hda1 EV6/I5 is the same as the hda2 EV6/I5, therefore I changed the logic in carstate.py to pick the ACCELERATOR notation to use based on the "alt_buttons" flag rather than "hda2" flag
2) The Accelerator check at the bottom of carstate.py was made to have check based on alt_buttons flag rather than hda2 flag.

values.py
1) I updated notation so that hda1 and hda2 have separate harness requirements
<s>2) Max steer needed to be 384 to make basic turns - the attached route demonstrates this. Without this adjustment, unnecessary "max steering" alerts occur.</s>

<s>override.yml
1) The EV6 required a lower Lateral Accel of 2.5 in order to perfectly complete the turns in the route provided when the Max steer was adjusted to 384</s>

**Prerequisite Minor Additional Panda Fix Required**
https://github.com/commaai/panda/pull/1063
1) The Accelerator check signal needed to be on bus 0 for hda1 EV6/I5.
2) The Accelerator RX check was changed to be based on "alt_buttons" flag rather than "hda2" flag
<s>3) Max steer was adjusted to 384</s>

**Verification** 
This branch has been installed on my C3 (with the Panda changes made locally), force fingerprinted to be an EV6, and tested on my hda1 EV6 (Wind trim). The dramatic S-curve performs perfectly with this branch! You can check "torque request" data as well as "lat accell" data to see that the "steer max" and "lat accel" changes were required to perform this short route with an S-curve.

**Route**
Route w/ 270 Max Steer and failure: 68d6a96e703c00c9|2022-09-10--16-09-39--0
Route w/ 384 Max Steer and perfection: 68d6a96e703c00c9|2022-09-10--16-25-04--0

### CODE REVIEW

**Comment by hoomoose** [comment]
I removed the change to Lat Accell in override.yaml since I see that Comma is continuously re-evaluating and changing this value. I do hope this helps expedite this PR so HDA1 EV6 and I5 will work out of the box with OP. Thanks!

**Comment by hoomoose** [comment]
I removed the change to steer_max and reverted it to 270 since that may affect more cars than just the EV6. 
At this point, the modifications simply make OP so that it works on HDA1 EV6 and I5 without affecting any other vehicle.

**Comment by adeebshihadeh** [comment]
Thanks for the PR! I'll check this out when I get a chance.

**Comment by crwusiz** [comment]
add other kor ioniq5

'carFw': [{'address': 2001,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'abs',
                          'fwVersion': b'\xf1\x00NE1 IEB \x01 107"\x02$ 58520-GI010',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2009,
                          'subAddress': 0},
                         {'address': 2004,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'\xf1\x00NE  MDPS R 1.00 1.07 57700GI000  4NEDR107',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2012,
                          'subAddress': 0},
                         {'address': 2000,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'\xf1\x00NE1_ RDR -----      1.00 1.00 99110-GI000         ',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2008,
                          'subAddress': 0},
                         {'address': 1988,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'\xf1\x00NE1 MFC  AT KOR LHD 1.00 1.05 99211-GI010 220614',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1996,
                          'subAddress': 0},

**Comment by rafaelcastillolopez** [comment]
I don't know if it's the way to include this info, but just in case here you have my Ioniq5 from EUR values (this PR works in my car after adding these values) :

'carFw': [{'address': 2001,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'esp',
                          'fwVersion': b'\xf1\x00NE1 IEB \x03 105!\x07\x01 58520-GI000',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2009,
                          'subAddress': 0},
                         {'address': 2004,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'\xf1\x00NE  MDPS R 1.00 1.06 57700GI000  4NEDR106',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2012,
                          'subAddress': 0},
                         {'address': 2000,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'\xf1\x00NE1_ RDR -----      1.00 1.00 99110-GI000         ',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 2008,
                          'subAddress': 0},
                         {'address': 1988,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'fwdCamera',
                          'fwVersion': b'\xf1\x00NE1 MFC  AT EUR LHD 1.00 1.01 99211-GI010 211007',
                          'request': [b'"\xf1\x00'],
                          'responseAddress': 1996,
                          'subAddress': 0},
                         {'address': 2001,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'esp',
                          'fwVersion': b'\xf1\x8758520GI000\xf1\x00NE1 IEB \x03 105!\x07\x01 58520-GI000',
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2009,
                          'subAddress': 0},
                         {'address': 2004,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'\xf1\x8757700GI000 \xf1\x00NE  MDPS R 1.00 1.06 57700GI000  4NEDR106',
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2012,
                          'subAddress': 0},
                         {'address': 2000,
                          'brand': 'hyundai',
                          'bus': 1,
                          'ecu': 'fwdRadar',
                          'fwVersion': b'\xf1\x8799110GI000\xf1\x00NE1_ RDR -----      1.00 1.00 99110-GI000         ',
                          'request': [b'"\xf1\x87\xf1\x81\xf1\x00'],
                          'responseAddress': 2008,
                          'subAddress': 0}]

**Comment by chrissantamaria** [comment]
Sorry to contribute to all the noise but this worked on my Ioniq 5 SE trim as well! Used a K harness, no pin swaps.

Had to add a few FPv2 values to have it recognize my car - included those + a `panda` submodule update (to reference changes in https://github.com/commaai/panda/pull/1063) on my fork: https://github.com/chrissantamaria/openpilot/commit/5288e682bf804d49650d6a2400e312292d5a10f6

**Comment by tsaiDavid** [comment]
Very interested in seeing this, I likely will rely on some of these changes for the GV60 port I'm planning on working on, which is equipped with HDA1

**Comment by ktm3194** [comment]
I have Ioniq 5, and it works very well on hda1

**Comment by mattwebbio** [comment]
Also interested in seeing this merged! I've been using this branch for about a month with no issues :pray:

**Comment by adeebshihadeh** [comment]
I cleaned up the branch. Can you guys give it another test before we merge?

**Comment by mattwebbio** [comment]
> I cleaned up the branch. Can you guys give it another test before we merge?

Engages and steers! Route: `859ffc6fd4e4168c|2022-10-13--08-16-08`

**Comment by hoomoose** [comment]
You beat me to it! I concur that it works.
68d6a96e703c00c9|2022-10-13--09-53-30--0

**Pull request merged**
