### PR TITLE
hyundai - wind down torque on disengage

### PR DESCRIPTION
**Pull request by gregjhogan**
This is supposed to cause gentle wind-down of torque when disengaging

seems to work but need to review in cabana to confirm

### CODE REVIEW

**Comment by AskAlice** [comment]
This is literally the reason I got banned from the openpilot discord. One day I got quite upset as I had almost gotten into an accident while going around a turn on a highway while adjusting to the new safety rules that required disengage on brake for vehicles without ACC/SCC. 

Is there panda code associated with this? I cant imagine this is the only thing necessary.

**Comment by gregjhogan** [comment]
@AskAlice this isn't to make things safer and you may want to lower the max torque allowed for your vehicle.  The safety requirement  which would apply to the situation you described is [here](https://blog.comma.ai/how-to-write-a-car-port-for-openpilot/#background--safety-architecture):
> Steer loss: while in a turn, in the case of an immediate loss of steering torque, the driver shall have at least 1 second of reaction time before the car significantly deviates from the desired path (e.g. lane lines crossing).

The best way to ensure this is to limit the max torque allowed such that even a complete failure of the power steering motor still meets this requirement.  If the power steering motor failed obviously you cannot rely on this functionality.

I found this functionality in the power steering motor controller firmware of my vehicle and I think it makes things more chill.

No panda changes are necessary to make this work because the wind down is completely handled by the power steering motor controller.

**Comment by AskAlice** [comment]
I will test this tomorrow.

**Comment by AskAlice** [comment]
Tested it, this is much better than the existing behavior. MUCH safer. 100% should merge in my book.

**Comment by gregjhogan** [comment]
if your car was unsafe before this change, it is still unsafe after this change because openpilot is QM and therefore you cannot depend on it to take action to keep you safe (as described [here](https://blog.comma.ai/how-to-write-a-car-port-for-openpilot/#background--safety-architecture))

**Comment by AskAlice** [comment]
> if your car was unsafe before this change, it is still unsafe after this change because openpilot is QM and therefore you cannot depend on it to take action to keep you safe (as described [here](https://blog.comma.ai/how-to-write-a-car-port-for-openpilot/#background--safety-architecture))

Definitely, however, it is a great improvement.

**Comment by TK211X** [comment]
This is one of the better changes for a safer OpenPilot in a while. Thank you @gregjhogan

**Pull request closed without merging**
