### PR TITLE
convert .format() to f-sting: PEP 498.

### PR DESCRIPTION
**Pull request by bbennett80**

### CODE REVIEW

**Comment by pd0wm** [comment]
Did you use a tool to do this or change it manually?

**Comment by bbennett80** [comment]
@pd0wm i used a tool. It is called flynt. Might this be something to add to a pre-commit workflow?

**Comment by pd0wm** [comment]
Pre-commit isn't necessary. Don't think I've seen a new `format()` been committed after we moved to python3.

**Comment by bbennett80** [comment]
Understood. Is the f-string conversion something you would consider given the speed benchmark improvements?

**Comment by pd0wm** [comment]
The diff is quite large to review, but if I can regenerate it myself using the tool it might be worth it. What exact flags did you use to run `flynt`? Is the PR ready for review?

**Comment by bbennett80** [comment]
I used "flynt openpilot" without other flags. 

I believe both pyextra and phonelibs were included. Happy to exclude those and resubmit. 

PR currently not ready for review. There are a few outstanding string concatenations for urls.

**Comment by bbennett80** [comment]
Final flynt command for string concats: flynt --transform-concats openpilot --exclude pyextra phonelibs

**Comment by bbennett80** [comment]
We just had the power go out. Let me close this and I will open another. Is that OK with you?

**Pull request closed without merging**
