### PR TITLE
Docs: Centralized links with markdown_include

### PR DESCRIPTION
**Pull request by ugtthis**
Found links in car port and how to section that could not be clicked on

### CODE REVIEW

**Comment by ugtthis** [comment]
I just noticed my markdown settings on my IDE changed the "*" to "-". Will change, right when I get back, away from the computer rn

**Comment by adeebshihadeh** [comment]
There must be a better way to fix this. Duplicating state is generally a bad idea.

**Comment by ugtthis** [comment]
This makes it easier to manage all links and update them as docs get bigger.

- Adding `{!links.md!}` lets the .md file have access to the central source of all links
- `links.md` will get bigger as docs grow which has multiple categories to easier find. (ex. category: Github Repos, Youtube, Pr & Commit Links, etc.).
- Easier to write docs since now link names can be referenced like a constant variable so long as you include {!links!} in each .md file that uses links
- Editing links in the `links.md` will update all links
- I tried building a simple script to add links from `links.md` to the end of the files but then script got bigger and it seemed like using the `markdown-include` was what I was trying to build but better and tested. https://github.com/cmacmackin/markdown-include

**Comment by adeebshihadeh** [comment]
This is a regression in the docs writing experience. Instead of writing a self-contained Markdown file, I need to know about this links file.

**Comment by ugtthis** [comment]
Got it thanks for the feedback

**Pull request closed without merging**
