### PR TITLE
GitHub Actions for CI

### PR DESCRIPTION
**Pull request by adeebshihadeh**
Improvements over Travis:
* Run tests in parallel (without external docker registry)
* Debug artifacts from process replay and longitudinal test
* [Nicer interface](https://github.com/quillford/openpilot/actions) and output isn't one giant block of text
* Possible docker layer caching built-in, still looking into this
* Seems to run automatically as long as the config file is in the repo, unlike Travis, so forks would automatically have CI

### CODE REVIEW

**Comment by pd0wm** [comment]
Cool! How does it save the docker container after the build to run stuff in parallel?

I was looking into moving everything to azure-pipelines, but that still requires a registry to push things to.

**Comment by quillford** [comment]
Instead of pushing to a registry, it’s just building the image fresh each time and uploading it as an artifact for the test stages to download.

**Comment by pd0wm** [comment]
Ah, I see, you're using `docker save` and gzipping them.

**Comment by quillford** [comment]
Seems like docker layer caching isn't implemented in GitHub Actions yet, but it can still be done with a docker registry. Other than that, this should be good to merge.

**Comment by pd0wm** [comment]
- Can we remove the travis file? We don't need that anymore.
 - The caching solution you implemented sounds fine.
 - Where can I see the test outputs, "checks" doesn't show anything for me. Do I need to enable it on the repo?

**Comment by quillford** [comment]
I think it needs to be merged in to a branch on `commaai/openpilot` before it'll run.

**Comment by pd0wm** [comment]
Let's see what happens!

Thanks for this PR :)

**Pull request merged**
