### PR TITLE
move plotjuggler to segment range reader

### PR DESCRIPTION
**Pull request by jnewb1**
broken:
  - cabana/internal(cd) links https://github.com/commaai/openpilot/pull/30970
  - direct link to a segment (https, local) https://github.com/commaai/openpilot/pull/30973
  - auto switching to qlogs

(both should be handled by segmentrangereader)

### CODE REVIEW

**Comment by sshane** [comment]
> auto switching to qlogs

Some notification of that would be nice, unless PJ makes it clear which parts are decimated.

**Comment by jnewb1** [comment]
> > auto switching to qlogs
> 
> 
> 
> Some notification of that would be nice, unless PJ makes it clear which parts are decimated. Or you need to explicitly tell it to auto switch or something

We are still figuring out exactly how this should work. We are thinking the default would be automatic, but you can specify you want rlogs with /r. Perhaps the automatic should print something saying it's switching, or require a manual toggle like PJ has now.

**Comment by adeebshihadeh** [comment]
Let's just pick something reasonable and merge. We can keep iterating once it's merged.

**Comment by jnewb1** [comment]
removing qlog fallback, until we add it to segment range reader

**Comment by sshane** [comment]
@jnewb1 you can't view routes with only qlogs after this change

**Comment by jnewb1** [comment]
> @jnewb1 you can't view routes with only qlogs after this change. Can we add back the qlog flag for now?
> 
> File "/home/batman/openpilot/openpilot/tools/lib/logreader.py", line 99, in comma_api_source assert not len(invalid_segs), f"Some of the requested segments are not available: {invalid_segs}"

we should just use the ```/q``` with segmentrangereader, we don't want a --qlog argument required for every tool

**Comment by sshane** [comment]
Right -- I totally forgot the whole point of the upgrade. That works.

**Comment by jnewb1** [comment]
I'll have it defaulting back to qlogs soon with a message

**Pull request merged**
