### PR TITLE
loggerd: run clear_locks() asynchronously

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
Is there a clear benefit? Is this operation slowing down loggerd start significantly?

**Comment by deanlee** [comment]
I'm not sure,still testing.I have encountered it running for 0.5 seconds

**Comment by pd0wm** [comment]
Why do we want to clear the locks up in the first place? In case loggerd didn't shut down cleanly?

**Comment by deanlee** [comment]
this seems to be the reason.

**Comment by adeebshihadeh** [comment]
Closing this for now. I think we re-evaluate whether we really want to clear the locks. If anything, the uploader should probably do this.

**Pull request closed without merging**
