### PR TITLE
HKG: Add missing FW versions for Kia Forte 2023

### PR DESCRIPTION
**Pull request by sunnyhaibin**
Add firmware versions for the 2023 Kia Forte.

Dongle ID: `753639a1c1872d8c`

Thanks to the community 2023 Kia Forte owner byron_88676 (Discord).

### CODE REVIEW

**Comment by sshane** [comment]
@sunnyhaibin same thing here https://github.com/commaai/openpilot/pull/30759#issuecomment-1864300881

**Comment by ahr2435tech** [comment]
This does not work on my 2023 Kia Forte. I get car unrecognized message

**Comment by sshane** [comment]
@ahr2435tech what is your dongle id?

**Comment by vesenwa** [comment]
Same unit worked in crv 2020. Tried forte 2023, guess fw issue. Error - can error, check connections. 

dongle id bbc520c51098bebc

**Pull request merged**
