### PR TITLE
TSS-P Corolla: use torque lateral control

### PR DESCRIPTION
**Pull request by ntegan1**
pid 69262f5e389c247d|2022-05-07--09-48-23
torque 69262f5e389c247d|2022-05-07--10-25-42

torque joint model 69262f5e389c247d|2022-05-09--08-02-57 (lost my lead at around 8:43am est and started to drive through them)
pid joint model 69262f5e389c247d|2022-05-09--10-10-01 (lost lead again at 10:16)

master commit ed41b14b55426fe4400e1a87ac7c4e9d4f031b40

https://github.com/ntegan1/openpilot/tree/tsspcorollatorque-patches/p2

2022-05-18 rip torque ctrl

### CODE REVIEW

**Comment by sshane** [comment]
We will fine tune the PI gains in the coming days and then start to bring cars over from there, so making a draft for now

**Comment by sshane** [comment]
@ntegan1 Can you rebase and get one more drive before and after on a common route? Then should be good to merge 🥳

**Comment by ntegan1** [comment]
@sshane getting another route now.

route is reversed between pid/torque since i'm going somewhere and switching to pid and then going back, hope that's ok.

**Comment by sshane** [comment]
Thanks for the updated routes! We've decided to wait until after release to merge this

**Comment by sshane** [comment]
You can keep this as a draft, or reopen when torque control is ready btw

**Comment by ntegan1** [comment]
no new routes cause banned for now

**Pull request merged**
