### PR TITLE
Genesis Type 2 Port

### PR DESCRIPTION
**Pull request by emmertex**
Both Port and Tuning work well.
User is 'andrewhlr' on slack

### CODE REVIEW

**Comment by rbiasini** [comment]
looks good. Thanks.

**Comment by rbiasini** [comment]
@emmertex , do you happen to have a cabana link to a drive with the GENESIS 2? In case, you can pm it to me on Discord

**Comment by emmertex** [comment]
Have sent the link.
Also corrected the year and updated the readme

**Comment by rbiasini** [comment]
something is not right: the fingerprint I get from the drive you sent me includes `832: 8`.

**Comment by rbiasini** [comment]
Also, since the vehicle params are the same, this should just be a fingerprint addition to the already existing `GENESIS`

**Comment by emmertex** [comment]
I would need to go back and see why, but we used to have 3x Genesis fingerprints, and it was changed to capture 2 of them.

**Comment by rbiasini** [comment]
In our internal branch I've just added this new fingerprint in `GENESIS` so this vehicle variant will be supported in next release. I will close this PR for now unless there are reasons for the car params to be different (and currently they are not except for a small delta in min steer speed)

**Pull request closed without merging**
