### PR TITLE
loggerd: single lock file per segment

### PR DESCRIPTION
**Pull request by deanlee**
The qlog/rlog is always closed last, one .lock file in logger.cc is enough

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
I support this, but let's formalize it a bit more. Maybe just make a single `.lock` file in the directory and remove the rlog and qlog lock files?

**Review by adeebshihadeh — CHANGES_REQUESTED** [review]
I support this, but let's formalize it a bit more. Maybe just make a single `.lock` file in the directory and remove the rlog and qlog lock files?

**Comment by adeebshihadeh** [comment]
Maybe loggerd itself should make the lock? We want to make sure the cases where either the rlog or cameras don't rotate are handled.

**Comment by deanlee** [comment]
Think it's safer to create/remove lock in loggerstate

**Comment by adeebshihadeh** [comment]
I didn't realize that these locks are used in a bunch of other places besides openpilot's uploader, such as the connect web app. This should stay as it is.

**Pull request closed without merging**
