### PR TITLE
GM camera ACC: always set long tune

### LINKED ISSUE #26893: GM camera cars crashing on first long engagement due to no long tune set if camera and no exp. mode toggle
### Describe the bug

The long tune in gm/interface.py is only set for camera cars if experimental mode is enabled, otherwise it's left uninitialized, causing a controlsd crash on first long engagement due to long kp_bp being different length than kp_v (which is uninitialized). This PR fixes the problem: https://github.com/commaai/openpilot/pull/26892

Here's the stack trace of the controlsd crash:
```crash
Traceback (most recent call last):                                                                                                                                                           File "/data/openpilot/selfdrive/manager/process.py", line 43, in launcher
    getattr(mod, 'main')()                                                                                                                                                                   File "/data/openpilot/selfdrive/controls/controlsd.py", line 906, in main
    controls.controlsd_thread()                                                                                                                                                              File "/data/openpilot/selfdrive/controls/controlsd.py", line 899, in controlsd_thread
    self.step()                                                                                                                                                                              File "/data/openpilot/selfdrive/controls/controlsd.py", line 887, in step
    CC, lac_log = self.state_control(CS)                                                                                                                                                     File "/data/openpilot/selfdrive/controls/controlsd.py", line 640, in state_control
    actuators.accel = self.LoC.update(CC.longActive, CS, long_plan, pid_accel_limits, t_since_plan)                                                                                          File "/data/openpilot/selfdrive/controls/lib/longcontrol.py", line 128, in update
    output_accel = self.pid.update(error_deadzone, speed=CS.vEgo,                                                                                                                            File "/data/openpilot/selfdrive/controls/lib/pid.py", line 55, in update
    self.p = float(error) * self.k_p                                                                                                                                                         File "/data/openpilot/selfdrive/controls/lib/pid.py", line 31, in k_p
    return interp(self.speed, self._k_p[0], self._k_p[1])                                                                                                                                    File "/data/openpilot/common/numpy_fast.py", line 16, in interp
    return [get_interp(v) for v in x] if hasattr(x, '__iter__') else get_interp(x)                                                                                                           File "/data/openpilot/common/numpy_fast.py", line 14, in get_interp
    (xv - xp[low]) * (fp[hi] - fp[low]) / (xp[hi] - xp[low]) + fp[low])                                                                                                                      File "capnp/lib/capnp.pyx", line 562, in capnp.lib.capnp._DynamicListBuilder.__getitem__
IndexError: Out of bounds                                                                                                                                                                  selfdrive/ui/qt/onroad.cc: slow frame rate: 12.65 fps
Traceback (most recent call last):                                                                                                                                                           File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()                                                                                                                                                                               File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)                                                                                                                                                File "/data/openpilot/selfdrive/manager/process.py", line 43, in launcher
    getattr(mod, 'main')()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 906, in main
    controls.controlsd_thread()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 899, in controlsd_thread
    self.step()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 887, in step
    CC, lac_log = self.state_control(CS)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 640, in state_control
    actuators.accel = self.LoC.update(CC.longActive, CS, long_plan, pid_accel_limits, t_since_plan)
  File "/data/openpilot/selfdrive/controls/lib/longcontrol.py", line 128, in update
    output_accel = self.pid.update(error_deadzone, speed=CS.vEgo,
  File "/data/openpilot/selfdrive/controls/lib/pid.py", line 55, in update
    self.p = float(error) * self.k_p
  File "/data/openpilot/selfdrive/controls/lib/pid.py", line 31, in k_p
    return interp(self.speed, self._k_p[0], self._k_p[1])
  File "/data/openpilot/common/numpy_fast.py", line 16, in interp
    return [get_interp(v) for v in x] if hasattr(x, '__iter__') else get_interp(x)
  File "/data/openpilot/common/numpy_fast.py", line 14, in get_interp
    (xv - xp[low]) * (fp[hi] - fp[low]) / (xp[hi] - xp[low]) + fp[low])
  File "capnp/lib/capnp.pyx", line 562, in capnp.lib.capnp._DynamicListBuilder.__getitem__
IndexError: Out of bounds```

### Which car does this affect?

GM camera cars (Bolt EUV, Silverado)

### Provide a route where the issue occurs

3140e1c6195c880e|2023-01-05--05-24-42

### openpilot version

master 0.9.0 (b74f2d1)

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by twilsonco**
The GM long tune isn't set if a car is a "camera car" and the user has the experimental long toggle disabled, causing a controlsd crash on first engagement (from a Bolt EUV). To fix, copy the non-camera car long tune so it's used for camera cars when experimental mode is disabled.

```crash
Traceback (most recent call last):                                                                                                                                                           File "/data/openpilot/selfdrive/manager/process.py", line 43, in launcher
    getattr(mod, 'main')()                                                                                                                                                                   File "/data/openpilot/selfdrive/controls/controlsd.py", line 906, in main
    controls.controlsd_thread()                                                                                                                                                              File "/data/openpilot/selfdrive/controls/controlsd.py", line 899, in controlsd_thread
    self.step()                                                                                                                                                                              File "/data/openpilot/selfdrive/controls/controlsd.py", line 887, in step
    CC, lac_log = self.state_control(CS)                                                                                                                                                     File "/data/openpilot/selfdrive/controls/controlsd.py", line 640, in state_control
    actuators.accel = self.LoC.update(CC.longActive, CS, long_plan, pid_accel_limits, t_since_plan)                                                                                          File "/data/openpilot/selfdrive/controls/lib/longcontrol.py", line 128, in update
    output_accel = self.pid.update(error_deadzone, speed=CS.vEgo,                                                                                                                            File "/data/openpilot/selfdrive/controls/lib/pid.py", line 55, in update
    self.p = float(error) * self.k_p                                                                                                                                                         File "/data/openpilot/selfdrive/controls/lib/pid.py", line 31, in k_p
    return interp(self.speed, self._k_p[0], self._k_p[1])                                                                                                                                    File "/data/openpilot/common/numpy_fast.py", line 16, in interp
    return [get_interp(v) for v in x] if hasattr(x, '__iter__') else get_interp(x)                                                                                                           File "/data/openpilot/common/numpy_fast.py", line 14, in get_interp
    (xv - xp[low]) * (fp[hi] - fp[low]) / (xp[hi] - xp[low]) + fp[low])                                                                                                                      File "capnp/lib/capnp.pyx", line 562, in capnp.lib.capnp._DynamicListBuilder.__getitem__
IndexError: Out of bounds                                                                                                                                                                  selfdrive/ui/qt/onroad.cc: slow frame rate: 12.65 fps
Traceback (most recent call last):                                                                                                                                                           File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()                                                                                                                                                                               File "/usr/local/pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)                                                                                                                                                File "/data/openpilot/selfdrive/manager/process.py", line 43, in launcher
    getattr(mod, 'main')()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 906, in main
    controls.controlsd_thread()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 899, in controlsd_thread
    self.step()
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 887, in step
    CC, lac_log = self.state_control(CS)
  File "/data/openpilot/selfdrive/controls/controlsd.py", line 640, in state_control
    actuators.accel = self.LoC.update(CC.longActive, CS, long_plan, pid_accel_limits, t_since_plan)
  File "/data/openpilot/selfdrive/controls/lib/longcontrol.py", line 128, in update
    output_accel = self.pid.update(error_deadzone, speed=CS.vEgo,
  File "/data/openpilot/selfdrive/controls/lib/pid.py", line 55, in update
    self.p = float(error) * self.k_p
  File "/data/openpilot/selfdrive/controls/lib/pid.py", line 31, in k_p
    return interp(self.speed, self._k_p[0], self._k_p[1])
  File "/data/openpilot/common/numpy_fast.py", line 16, in interp
    return [get_interp(v) for v in x] if hasattr(x, '__iter__') else get_interp(x)
  File "/data/openpilot/common/numpy_fast.py", line 14, in get_interp
    (xv - xp[low]) * (fp[hi] - fp[low]) / (xp[hi] - xp[low]) + fp[low])
  File "capnp/lib/capnp.pyx", line 562, in capnp.lib.capnp._DynamicListBuilder.__getitem__
IndexError: Out of bounds```

### CODE REVIEW

**Comment by sshane** [comment]
Not sure how this slipped through, thanks for catching. Test to catch similar bugs: https://github.com/commaai/openpilot/pull/26894

**Comment by sshane** [comment]
Do you have a route? This isn't an issue since longActive is never true without long control, unless you were on a fork making modifications

**Comment by sshane** [comment]
This isn't an issue since longActive is never true without long control, unless you were on a fork making modifications. Please always mention if you are reporting an error from a fork with a route, it wastes time looking into issues that aren't a problem on upstream.

The bug is in sunny's fork not gating longActive on CP.openpilotLongitudinalControl: https://github.com/sunnyhaibin/sunnypilot/blob/f34deb644419752d8ba7d50f794901c0341674d7/selfdrive/controls/controlsd.py#L627

I like the idea of the test though, so we should fix the mismatch in lengths regardless

**Comment by twilsonco** [comment]
Oops sorry. I was told by the user that reported it that he had reproduced it on master with experimental mode disabled.

**Pull request merged**
