### PR TITLE
Add Fingerprints for all ECUs on 2023 Kia Sportage Hybrid SX Prestige

### PR DESCRIPTION
**Pull request by geerhead**
**Car**

2023 Kia Sportage Hybrid SX-Prestige

**Route**

d99dc2fc2790c1ab/00000001--0ab81f330c

**Notes**:

Originally my car was not being recognized, found missing ECUs and fingerprints that needed to be added for it to recognize the vehicle. Tested by installing this branch to my C3X

I added the additional ECUs in the same order they are shown in the logs so future contributors will be able to easily add them.

### CODE REVIEW

**Comment by sshane** [comment]
Looks like https://github.com/commaai/openpilot/pull/31254 would have fuzzy fingerprinted this

**Comment by ggeer8** [comment]
> Looks like #31254 would have fuzzy fingerprinted this

@sshane I can deploy the branch from #31254 to my C3X and see if it recognizes the vehicle and report back, sound good?

**Comment by sshane** [comment]
That's okay, that's just a note for you. You'll want to open your PR against the correct target branch: `master`

@jnewb1 can we have the bot check for the correct base branch to avoid these problems?

**Comment by ggeer8** [comment]
> That's okay, that's just a note for myself. You'll want to open your PR against the correct target branch: `master`
> 
> @jnewb1 can we have the bot check for the correct base branch to avoid these problems?

Done! Appreciate you guys, cheers mate!

**Comment by jnewb1** [comment]
Hmm, CI does that but there is no CI within the master-ci branch (it's a release branch)

**Pull request closed without merging**
