### PR TITLE
Add rate-based feed-forward for lateral control

### PR DESCRIPTION
**Pull request by Gernby**
This enhancement combines desired steering rate with desired angle to calculate a more effective feed-forward input to the PID / PIF function for steering torque.  The benefits are significant, but the logic is rather simple.

Since _**angle**_-based feed-forward is increasingly problematic near steering center, the proposed logic only uses **_rate_**-based feed-forward when the desired steering angle is close to center.  However, since _**rate**_-based feed-forward is increasingly problematic in the outer steering range, the proposed logic interpolates the transition from rate-based to angle-based feed-forward as the desired steering angle departs from center.

I have found this to be very effective for reducing "lane hugging", typically caused by high steering angle offsets or alignment problems.  It also improves lane centering, and reduces "ping-pong", which I believe is a problem with angle-based feed-forward in general.  For cars with high actuator latency (like Toyota's), the ability to adjust steering behavior in the inner and outer steering ranges separately should improve overall performance tremendously.

A side benefit to the proposed logic is that it removes the need to be so conservative with angle-based feed-forward.  By increasing angle-based feed-forward gain, the reliance on proportional and integral error is reduced.  This improves steering response and reduces over-correction that's commonly caused by high proportional error.  This is especially beneficial for cars with limited steering torque (like Honda's), where over-correction in the outer steering range comes at a high cost. 

[EDIT]: I forgot to mention that I tested a broad range of gain values, and found that the logic is very forgiving of large and small values.  I tested rate-based gain values in the range of 0.1 to 3.0, and observed that the steering was very relaxed at 0.1, but very "knife-edged" at 3.0.  The behavior between those values seemed proportional to the value.  I tested angle-based gain values in the range of 1.0 to 5.0, and observed that steering was similar to standard at 1.0, but had a tendency toward the inside lane line at 5.0. 

I believe the gain values could be optimized dynamically in ParamsLearner, so that they don't need to be manually tuned.  The rate-based gain could be optimized based on PIF noise near the zero crossing.  The angle-based gain could be optimized based on the percentage of feedforward within PIF when target angle is in the outer range.

image

[Here](https://snapshot.raintank.io/dashboard/snapshot/CJ603rss5q0VPgDnXfalbOkkjSrF5ULu) is a Grafana snapshot from a drive in my 2018 Accord on the highway.  The snapshot is interactive, so you can zoom in / out, and pan left / right by clicking the buttons on the page OR using keyboard shortcuts.

I've also captures some screen prints of a few significant segments below.

image

image

### CODE REVIEW

**Comment by ErichMoraga** [comment]
I wad very optimistic about your concept and explanation, but when I tried this out on my 2017 Prius Prime, it was dangerously unstable at medium to high speeds as it would develop a runaway ping pong, with progressively dramatic counte-steering.  Perhaps PID tuning would help, though it's strange your minimalist modification would necessitate that.

**Comment by Gernby** [comment]
Thanks for the feedback!  

While testing logic to auto-tune the angle and rate gain values, I found that the rate gain value can be _**much smaller**_ without losing its effectiveness.  My Honda Accord performed well with a rate gain below 0.01, so it seems that 0.2 is not as conservative as I first thought.  I have reduced the default rate gain value to 0.02 and the default angle gain to 1.0.

**Comment by Gernby** [comment]
Also, since the Toyota Prius provides such a unique steering challenge, I believe that it needs a Prius-specific fix.  Over the past few months, while developing various strategies for lateral control, it seems that the Prius responded very well to an approach like this to reduce over-correction.
`  if self.CP.carFingerprint == CAR.PRIUS:  self.angle_steers += self.angle_steers_rate * 0.1`

**Review by ErichMoraga — COMMENTED** [review]
Makes sense.  I'll try it out later today.

**Comment by Gernby** [comment]
FYI.  I enhanced the logic to include a simple (but effective) auto-adjustment for the angle and rate gain values.  I found that the gain value for rate-based feedforward should be much smaller than originally thought.

**Comment by icmma** [comment]
bro i wish i could try it:(

**Comment by arne182** [comment]
@icmma this is integrated into my fork

**Comment by Gernby** [comment]
FYI, it originally seemed that steer_override would be a condition that should block auto-adjust of the feed-forward gain values.  However, after testing on other vehicles (specifically Toyota's), it was clear that OP's torque requests alone can trigger false positives for steering overrides.  This resulted in the rate-based feed-forward gain value to go off-scale positive, which caused extremely poor steering performance in a short period of time.  The steer_override condition has been removed, but it seems that Toyota's steer_override threshold value should be reviewed.

**Comment by Gernby** [comment]
This enhancement has been successful for many people, and tested for months in @arne182 release2.  If the only thing blocking it from being merged are the recent merge conflicts, please let me know.  I'm willing to rebase the PR if there's a willingness to merge it.

**Comment by geohot** [comment]
If this pull request is still relevant, please resubmit it to the master branch. This should allow our development flow to work better, we commit to master, you commit to master, everyone commits to master! Learn more: https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3

**Pull request closed without merging**
