### PR TITLE
Add ECU of European Lexus UX250h 2019

### PR DESCRIPTION
**Pull request by Rafale83**
Add ECU of European Lexus UX250h 2019

### CODE REVIEW

**Comment by vanillagorillaa** [comment]
Please provide the dongleID of the device this was gathered from.

**Comment by Rafale83** [comment]
Can you explain me more explicitly? I dont anderstand explicitly.

Also, I would like to help and translate the interface into French. Point
me to the strings in the GitHub repository and I'll gladly translate them.

Le jeu. 5 janv. 2023, 17:39, vanillagorillaa ***@***.***> a
écrit :

**Comment by croumegous** [comment]
Hello, from the official documentation "the dongle ID is an 16-character alphanumeric device identifier. Each comma device has a unique dongle ID."
The dongleID of your device can be found in Settings of the device in the Device tab. 

BTW, I've created a PR to add french support: https://github.com/commaai/openpilot/pull/26889 don't hesitate to suggest improvements.

**Comment by sshane** [comment]
Can you re-open your pull request against master, not master-ci?

**Comment by Rafale83** [comment]
My dongle_id is 7748c5efc634eb13

The updates I made are functional.

You can commit. My MY19 Lexus 250h is working with Rafale83 fork.
--


<br class="Apple-interchange-newline">[7748c5efc634eb13](https://useradmin.comma.ai/?onebox=7748c5efc634eb13)

**Comment by Rafale83** [comment]
Here is my dongle_id
7748c5efc634eb13 <https://useradmin.comma.ai/?onebox=7748c5efc634eb13>
I tried to ask for a pull request better thi time.
I'm a bit learning all this.
I'll become better with time.

Le ven. 6 janv. 2023 à 22:57, Cyril Roumégous ***@***.***> a
écrit :

**Comment by Rafale83** [comment]
Done.
I think that this exactly what I just tried to do.
Tell me what you think

Rafael
7748c5efc634eb13 <https://useradmin.comma.ai/?onebox=7748c5efc634eb13>


Le sam. 7 janv. 2023 à 01:47, Shane Smiskol ***@***.***> a
écrit :

**Pull request closed without merging**
