### PR TITLE
UI Update - Add Skins

### PR DESCRIPTION
**Pull request by klaus385**
@pjlao307 decided that he wasn't going to be updating his ui-update branch. However, I am one of the users that greatly appreciates it. As such I have talked with @pjlao307 before submitting this updated pull request for 0.3.7 of openpilot. 

This pull request allows for the other "Add Skins" pull request to be closed. As such I hope that this request will be able to be merged so others can have the option of using skins.

### CODE REVIEW

**Comment by energee** [comment]
I was using this for a bit, i like it too, but its just on the heavy side for what it is, takes longer to load vision when starting, needs to be lightened up, maybe the pngs be replaced with vectors

**Comment by klaus385** [comment]
@energee I wrote a small script to batch convert the pngs to svg however it strips the colors. Though it does shave a ton off the size of the files. As you can see by the attached zip file.

[speed-tmp.zip](https://github.com/commaai/openpilot/files/1360426/speed-tmp.zip)

**Comment by klaus385** [comment]
@energee just fixed this issue of stripping the colors though the size increases on each image. Which I assume that's what you meant by heavy.

[speed-svg-color.zip](https://github.com/commaai/openpilot/files/1360444/speed-svg-color.zip)

**Comment by pjlao307** [comment]
The delay in starting up visiond is because it has to extract and load the PNGs into memory.  So if you can speed that process up that would solve the delay issue.  Otherwise, you can just remove the use of those PNGs and get rid of the "notch" code so it's just the background circles around the speeds.

**Comment by klaus385** [comment]
Updated for 0.3.8.2 still praying you will merge this or if not then is their a ui update coming up the pipe?

**Comment by mcampa** [comment]
Can you post screenshots?

**Comment by klaus385** [comment]
@mcampa sure though with the updates of 0.4 these UI changes are irrelevant.

Thus, I’m closing this Pull Request.

**Pull request closed without merging**
