### PR TITLE
Toyota: radar_acc_tssp_car radar parser (v_ego)

### PR DESCRIPTION
**Pull request by Smartype**
Please review.
Another PR which requires less file changed. https://github.com/commaai/openpilot/pull/27486

### CODE REVIEW

**Comment by Smartype** [comment]
You can accept this one, or accept the cereal PR. If you accept the cereal PR. I will work on another radar ACC PR.

cereal PR: https://github.com/commaai/cereal/pull/414
another radar ACC PR: https://github.com/commaai/openpilot/pull/27486

**Comment by cydia2020** [comment]
Can this be merged? I've this in my fork and folks are reporting it works well, it also doesn't affect the functionality of other platforms.

**Comment by chadgauth** [comment]
When reviewing the original I thought the vRel from radars providing absolute velocity should be calculated in the radar interface, but I can put my finger on exactly the best way to implement this. I could be available to clean this up some perhaps tomorrow.

**Comment by williefeb19** [comment]
I can confirm that cydia2020 fork does work well. I have been hoping for OP support for Smartype's firmware/hardware for a while.

**Comment by sshane** [comment]
Closing this in favor of https://github.com/commaai/openpilot/pull/27487 since they're both very similar.

**Pull request closed without merging**
