### PR TITLE
watchdog_kick: non-allocating

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
Should we just write the 4 bytes of the uint64 timestamp in the watchdog file and `struct.unpack` it on the python side?

**Comment by deanlee** [comment]
~25% of the QUIState::update()'s time is spent on  watchdog_kick when onroad. think it's better not to  waste any cpu on unnecessary things even just a tiny bit.

**Comment by pd0wm** [comment]
We also don't need to kick the watchdog on every `update()` call. Maybe that got changed in one of the refactors? The timeout is 5 seconds, so it's fine to only call `kick` every second.

**Comment by pd0wm** [comment]
Good to merge?

**Comment by deanlee** [comment]
yes

**Pull request merged**
