### PR TITLE
Toyota: show hybrid 2023 RAV4 in docs

### PR DESCRIPTION
**Pull request by sshane**

### CODE REVIEW

**Comment by sshane** [comment]
@adeebshihadeh should we add to releases too?

`* Toyota RAV4 Hybrid (Japanese-manufactured) 2023 support`

**Comment by adeebshihadeh** [comment]
Unless the Japanese-built ones are most of the ones sold in the US, this is too confusing to show right now.

**Comment by sshane** [comment]
Of 14 RAV4 Hybrids last 30 days, 7 of them are built in Japan.

Only 1 RAV4 ICE and it's built in United States.

**Comment by sshane** [comment]
[2023 RAV4 allocation](https://docs.google.com/spreadsheets/d/1kj0LJxur-ACyYgp5OLUiv3P6j7NzJwl_xaReMih4Ym8/edit?usp=sharing) (percent made in Japan):

```
Limited: 3904/9194 (42.46%)
LE: 2638/5351 (49.3%)
XLE: 7332/17672 (41.49%)
SE: 3486/9925 (35.12%)
XSE: 4244/17939 (23.66%)
XLE Premium: 8142/17213 (47.3%)
Woodland Edition: 0/4152 (0%)
```

So about 35%, going to close since it's not even the majority in the US.

**Comment by adeebshihadeh** [comment]
35% of one of the best sold cars is a lot. If we don't get the rest supported very soon, we should revisit this.

**Pull request closed without merging**
