### PR TITLE
Test LogReader scenarios for auro_source function

### PR DESCRIPTION
**Pull request by markopetkovic96**
for #31223 
After @adeebshihadeh's suggestion, tests are updated.

### CODE REVIEW

**Comment by markopetkovic96** [comment]
@adeebshihadeh

**Comment by markopetkovic96** [comment]
@adeebshihadeh

**Comment by markopetkovic96** [comment]
.

**Comment by maxime-desroches** [comment]
This PR was closed because of a git history rewrite.
Please read https://github.com/commaai/openpilot/issues/33399 for what to do with your fork and your PRs.

**Pull request closed without merging**
