### PR TITLE
c++ replay: publish all frames in CameraServer

### PR DESCRIPTION
**Pull request by deanlee**

### CODE REVIEW

**Comment by pd0wm** [comment]
Any reason YUV frames are not enabled? If we have support for that, and routes with only 1 segment we can delete unlogger.py since we reached feature parity.

**Comment by deanlee** [comment]
There is no particular reason. I wanted to support it after #22217. but #22195 can also work. we can use it before #22217

**Comment by pd0wm** [comment]
How big is the performance hit by always broadcasting YUV? I.e. is it worth it to gate it behind a flag like we did for unlogger.py?

**Comment by deanlee** [comment]
the yuv data is already cached by framereader in the decoder thread.  the only time consumed while publish is memcpy to vipc buffer. it's extreme fast

**Comment by pd0wm** [comment]
Last PR needed to delete unlogger.py!

**Comment by pd0wm** [comment]
Confirmed YUV works by running modeld live

**Pull request merged**
