### PR TITLE
support for Chrysler Pacifica 2020 Hybrid

### PR DESCRIPTION
**Pull request by adhintz**
Thanks to Benson in Discord.
Example segment: 8190c7275a24557b|2020-01-29--08-33-58--7

### CODE REVIEW

**Comment by pd0wm** [comment]
Can you add a route to `selfdrive/test/test_car_models.py`? If you add it to the list I'll sync it to the public bucket.

**Comment by adhintz** [comment]
Sure thing, just added it after confirming with Benson that it's fine to make public.

**Comment by pd0wm** [comment]
Can you remove the `--7` from the segment? I synced the route to the public bucket.

**Comment by adhintz** [comment]
Sure thing, I've now removed the --7.

**Pull request merged**
