### PR TITLE
WIP: 2024 Kia EV9 - Angle Control

### PR DESCRIPTION
**Pull request by epchris**
# IMPORTANT NOTE: This PR is still actively being worked on and is a WIP.  Lateral control has initial support, long control is not supported yet.

**There are currently debug messages added to this PR to help diagnose the situation on the EV9**

**Car**
2024 Kia EV9

**Route**
A route with the fingerprint: ef58ea5826475344/2024-02-14--12-06-44

**Checklist**

- [X] added entry to CarInfo in selfdrive/car/*/values.py and ran `selfdrive/car/docs.py` to generate new docs
- [ ] test route added to [routes.py](https://github.com/commaai/openpilot/blob/master/selfdrive/car/tests/routes.py)
- [ ] route with openpilot: f58ea5826475344/2024-02-17--14-48-54
- [ ] route with stock system: ef58ea5826475344/2024-02-14--12-06-44
- [X] car harness used (if comma doesn't sell it, put N/A): Hyundai R

### CODE REVIEW

**Comment by epchris** [comment]
@adeebshihadeh I opened this PR because the author of the other PR hasn't seemed to have been responsive since the PR was opened and I'm happy to be actively involved.

**Comment by sshane** [comment]
Took a quick look, this may be an angle-based controller:

image

```
BO_ 272 LKAS_ALT: 32 XXX
 SG_ LKAS_BIT : 77|2@0+ (1,0) [0|3] "" XXX
 SG_ ANGLE_CMD_MAYBE : 80|16@1- (-0.025,0) [0|511] "" XXX
 SG_ UNKNOWN : 96|8@1+ (1,0) [0|255] "" XXX
```

**Comment by sshane** [comment]
Camera seen lowering angle cmd at 0.2 deg/frame and raising at 0.1 deg/frame at 100Hz.

image

**Comment by epchris** [comment]
Summary of current testing (from Discord)

1. Angle-based steering seems to be working
2. the "UNKNOWN" value effects "steering strength", but high values can be scary to override and introduce jitter. Values above ~170 cause EPS failures when overriding
3. An UNKNOWN value of 110 feels "good", but can't handle sharper turns
4. iPedal can't be engaged when OP is enabled
5. Can't engage OP at a standstill
6. Lane Changing doesn't work
7. Highway driving sees a "ping pong" behavior at a low frequency, may need to look into overriding HDA2 lane centering

**Comment by epchris** [comment]
`UNKNOWN` signal is possibly some kind of torque strength message, but in stock routes seems to not often be > 0, but rather has a value > 0 when driver is making corrective steering: 
image

**Comment by epchris** [comment]
Screen shot of adjusting the (currently) `UNKNOWN` LKAS value that we are treating as a torque value while OP is engaged and manual steering is done to adjust: 
image


Current code uses a steady value of 130 unless torque on the steering wheel is applied by the driver.

**Comment by crwusiz** [comment]
Vehicles with LFA2

KIA EV9 (MV)
HYUNDAI SANTAFE (MX5)
HYUNDAI IONIQ5_FL (NE)

**Comment by owenpann** [comment]
I purchased 3x and they are being shipped. My EV9 is the Asian Taiwan version （wo/HDA2）and will be delivery around mid-April. I will test it to see if there are any problems.

**Comment by tvturnhout** [comment]
> I purchased 3x and they are being shipped. My KIA EV9 is the Asian Taiwan version (wo/HDA2) and will be deliver around mid-April. I'll install it for testing.

Did you have any luck with your EV9?

**Comment by owenpann** [comment]
> > I purchased 3x and they are being shipped. My KIA EV9 is the Asian Taiwan version (wo/HDA2) and will be deliver around mid-April. I'll install it for testing.
> 
> 
> 
> Did you have any luck with your EV9?

Sorry, postpone.

Planned for the end of June.

**Comment by theawes0megamer** [comment]
> > > I purchased 3x and they are being shipped. My KIA EV9 is the Asian Taiwan version (wo/HDA2) and will be deliver around mid-April. I'll install it for testing.
> > 
> > 
> > Did you have any luck with your EV9?
> 
> Sorry, postpone.
> 
> Planned for the end of June.

How did it go?

**Comment by sshane** [comment]
We've moved the car interfacing code to our [`opendbc`](https://github.com/commaai/opendbc) repository, which is now the new home for car ports and fingerprints. Please re-open your pull request against [`opendbc`](https://github.com/commaai/opendbc) at your convenience by using this command below. This will transform all changes under `selfdrive/car/` to `opendbc_repo/opendbc/car/`. Make sure you have initialized submodules beforehand and have checked out the latest `opendbc` commit.

```bash
PR_NUMBER=33045
curl -L https://github.com/commaai/openpilot/pull/$PR_NUMBER.patch | sed -e 's/selfdrive\/car/opendbc_repo\/opendbc\/car/g' | git apply -v --reject
```

Simply replace the PR number with your own. Once done, add the files, fix any conflicts, and open a new PR. Alternatively, you may start a new PR from scratch if that is easier for you.

**Pull request closed without merging**
