### PR TITLE
Update Subaru Outback 2.5i-ES Taiwan version to values.py

### PR DESCRIPTION
**Pull request by stevenctc**
Add Outback Taiwan version's fingerprint v1

### CODE REVIEW

**Comment by pd0wm** [comment]
What's your dongle id?

Is it possible to merge/combine the fingerprint into the existing one?

**Comment by stevenctc** [comment]
My dongle id = 07dfea38d3a6511f

It works with Martinl's Subaru fork.

**Comment by pd0wm** [comment]
Can you merge the two fingerprints?

**Comment by stevenctc** [comment]
@pd0wm Do you mean the existing Outback 3.6R and mine together? I guess I cannot.

**Comment by pd0wm** [comment]
What's wrong with this one?

```python
{2: 8, 208: 8, 209: 4, 210: 8, 211: 7, 212: 8, 316: 8, 320: 8, 321: 8, 324: 8, 328: 8, 329: 8, 336: 2, 338: 8, 342: 8, 346: 8, 352: 8, 353: 8, 354: 8, 356: 8, 358: 8, 359: 8, 392: 8, 554: 8, 604: 8, 640: 8, 642: 8, 644: 8, 805: 8, 864: 8, 865: 8, 866: 8, 872: 8, 880: 8, 881: 8, 882: 8, 884: 8, 885: 8, 886: 2, 977: 8, 1614: 8, 1632: 8, 1640: 8, 1657: 8, 1658: 8, 1672: 8, 1722: 8, 1736: 8, 1743: 8, 1745: 8, 1785: 5, 1786: 5, 1787: 5, 1788: 8, 1862: 8, 1870: 8, 1920: 8, 1927: 8, 1928: 8, 1935: 8, 1968: 8, 1976: 8, 2016: 8, 2017: 8, 2024: 8, 2025: 8}
```

**Comment by stevenctc** [comment]
Can I just combine 2 of them and just use it on my car? O didn't know that...

**Comment by pd0wm** [comment]
Yes, that's what I meant.

**Comment by adeebshihadeh** [comment]
Closing due to inactivity. Feel free to reopen after addressing comments.

**Pull request closed without merging**
