### PR TITLE
Fix gyro orientation offset for EONs with OP3T mainboards

### PR DESCRIPTION
**Pull request by jyoung8607**
The localizer in 0.8 exposed a problem with some devices reporting orientation with an strange offset. Only OP3T-based devices seem affected, and only a subset of those. Resetting the sensor HAL registry and letting the device rebuild it seems to clear the issue. The origin of the bad sensor registry data isn't clear. No other devices seem to be affected.

As of this change, all OP3T will have their sensor registry reset and rebuilt, exactly one time. The old sensor registry is kept as a backup (in case this has unforeseen fallout) and it serves as a flag that we've already performed the reset on this device.

### CODE REVIEW

**Comment by TK211X** [comment]
Wouldn’t it be better to periodically calibrate the 0 position of the sensor against vision data so that it accounts for any variables in installation position. I’m sure every sensor has some variance in how it’s installed on the board. This would make it so that it wouldn’t matter what position the sensor is in.


This is how an AHRS unit works and I think implementation of this logic would be universal to any previous or future product.

**Comment by pd0wm** [comment]
We already do this in the backend, which is how we found the issue with the op3ts. We just want to reset them once to make sure the consistent offset is gone.

**Comment by jyoung8607** [comment]
Checks out with repeated loop testing for sensor count, and limited drive testing.

**Comment by jyoung8607** [comment]
Merged per offline discussion with @pd0wm.

**Pull request merged**
