### PR TITLE
Combine fingerprint and add 808

### PR DESCRIPTION
**Pull request by arne182**
Adding the 168 and 808 into one fingerprint for the 2018 Chrysler Pacifica Hybrid

### CODE REVIEW

**Comment by legonigel** [comment]
Can you please rebase this on devel, so that the new fingerprint tests will run?

**Comment by arne182** [comment]
No. As I don't understand what you want me to do.

**Comment by rbiasini** [comment]
@arne182 , the request was to merge devel into your branch so automatic regression tests run and we can automatically catch if the fingerprint change will cause any issue.

**Comment by legonigel** [comment]
What Riccardo said was correct. [This link](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) also has a good write up on what rebasing is. We would like to get this fingerprint fixed.

**Comment by adhintz** [comment]
I've now included this change in https://github.com/commaai/openpilot/pull/590

**Pull request closed without merging**
