### PR TITLE
logmessaged: avoid dropping messages

### LINKED ISSUE #29086: logmessaged: drops first few log messages for new processes
For example, I'm missing the first few logs from dmonitoringmodeld, but there are logs from before that for navmodeld:

```
batman@workstation-shane:~/openpilot/selfdrive/debug$ ./filter_log_message.py "" 0 | grep "\/modeld"
[62681.644093] selfdrive/modeld/navmodeld.cc:45 - main: navmodeld waiting for dmonitoringmodeld to initialize
[62681.695226] selfdrive/modeld/runners/snpemodel.cc:37 - SNPEModel: loaded model with size: 4443461, models/dmonitoring_model_q.dlc
[62681.696085] selfdrive/modeld/runners/snpemodel.cc:41 - SNPEModel: snpe_builder, models/dmonitoring_model_q.dlc
[62681.696610] selfdrive/modeld/runners/snpemodel.cc:43 - SNPEModel: !snpe, models/dmonitoring_model_q.dlc
[62682.128067] selfdrive/modeld/modeld.cc:209 - main: models loaded, modeld starting
[62682.274577] selfdrive/modeld/runners/snpemodel.cc:56 - SNPEModel: build, models/dmonitoring_model_q.dlc
[62682.275326] selfdrive/modeld/runners/snpemodel.cc:61 - SNPEModel: got snpe, models/dmonitoring_model_q.dlc
[62682.275950] selfdrive/modeld/runners/snpemodel.cc:65 - SNPEModel: created output buffer, models/dmonitoring_model_q.dlc
```

### PR DESCRIPTION
**Pull request by deanlee**
resolve: https://github.com/commaai/openpilot/issues/29086

related document: http://api.zeromq.org/master:zmq-setsockopt

### CODE REVIEW

**Comment by sshane** [comment]
I applied this commit on my local branch, but still it drops messages :/

image

Local diff on test_dmon branch:

image

**Comment by deanlee** [comment]
Does this still happen if set high_watermark to 0?
>     int high_watermark = 0;
>     zmq_setsockopt(sock, ZMQ_SNDHWM, &high_watermark, sizeof(high_watermark));

**Comment by sshane** [comment]
Don't think so, out of 27 routes last 10 minutes, only only 4 had all the logs I needed to calculate the startup timings

**Comment by sshane** [comment]
should we close this for now or do you have any ideas how to fix this?

**Comment by deanlee** [comment]
closed

**Pull request closed without merging**
