### PR TITLE
Subaru: remove rest of CAN fingerprints

### LINKED ISSUE #23847: FW versions dump
Subaru
- [ ] look into removing rest of CAN fingerprints (Impreza 2020 and Forester)

### PR DESCRIPTION
**Pull request by adeebshihadeh**
Subaru models with unknown fw are falling back to CAN and mis-fingerprinting.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Affected dongles

```
  SUBARU IMPREZA SPORT 2020
       {'2f2dccde48fab6ac', '522ff91c7c405658', '75925349de84c868', '26b7e0304e11849c', '59755a6574d9ac67', '0e371e79d12e793f', '797896fccd22e29d', '6dd6cf7a0121d845', 'cc0cfd8493eab106', '68654ec8de4f7567', '5b81b838fa584544', 'c583a6c04d0bd448'}

  SUBARU FORESTER 2019
       {'4f59a3e381b0333f', 'e8444e7797eb3797', '45ec76ce7de3e0e8', '5a5875f50b78f825', '23460f6a966d049b', 'cdd68f15f697f91d', '596beb05fdfa3832', 'be44434f27731ff8', 'ffb24d475c36bab4', 'a890bfb5ae838564', '9772731082ef46d0', 'c13dd4a9a77ee2bc', 'd0830228206c82a7', 'c778b637e6402ce1', '2e5c2e175dc035d5', '749feedf221e9389', 'f39f98d80425fa13', '57e4ba71585fefbc'}
```

**Comment by KyleBoyer** [comment]
Latest Route ID: `c2f528d49fe19d53|2022-04-13--20-11-17`

`carFw` values:
```
               'carFw': [{'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x02\x00', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xcf"`0\x07', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\x1a\xf6F`\x00', 'subAddress': 0},
                         {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa3  \x14\x01', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x8d\xc0\x04\x00', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00e\x97\x1f@ 0', 'subAddress': 0}],
```

**Comment by tango2590** [comment]
Car: 2020 Subaru Crosstrek Limited
Latest Route ID: 0f33f7a9d1949fa6|2022-04-13--14-29-58

carFw values:
```
               'carFw': [{'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xca!f@\x07', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\xe6\xf5D0\x00', 'subAddress': 0},
                         {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x03\x00', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x9a\xc0\x04\x00', 'subAddress': 0},
                         {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa2  `\x00', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00eq\x1f@ "', 'subAddress': 0}],

```

**Comment by Zapman69** [comment]
Car: 2019 Subaru Forester Sport
Latest Route ID: f6e178e18ba27ca1|2022-03-26--14-21-16

'carFw':            [{'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x02\x00', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xb6"`A\x07', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\x1a\xf6B`\x00', 'subAddress': 0},
                         {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa3 \x18\x14\x00', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x8d\xc0\x04\x00', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00e!\x1f@ \x11', 'subAddress': 0}],

**Comment by infinite-ideation** [comment]
Car: 2021 Subaru Forester Touring 
Latest Route ID: 6fcb17b9ef924548|2022-04-14--05-37-28

`'carFw': [{'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x02\x00', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xcf"`0\x07', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\x1a\xf6F`\x00', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x8d\xc0\x04\x00', 'subAddress': 0},
                         {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa3  \x14\x01', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00e\x97\x1f@ 0', 'subAddress': 0}],`

**Comment by choongsoo** [comment]
Car: 2019 Subaru Forester Limited
Latest Route ID: a447729c1d15ff89|2022-04-13--17-54-27
`               'carFw': [{'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xf1\x00\xbb\r\x05', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x8d\xc0\x04\x00', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xf1\x00\xa2\x10\n', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\xf1\x00\xa4\x10@', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00e!\x1f@ \x11', 'subAddress': 0},
                         {'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x02\x00', 'subAddress': 0}],`

**Comment by trailtacos** [comment]
Car: Subaru 2020 Sport (US)
RouteID: 8bf7e79a3ce64055|2021-05-24--09-58-54

```
'carFw': [{'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xca!ap\x07', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\xe6\xf5\x04\x00\x00', 'subAddress': 0},
                         {'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x9a\xc0\x00\x00', 'subAddress': 0},
                         {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa2 \x194\x00', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00eb\x1f@ "', 'subAddress': 0}],
```

**Comment by scullionw** [comment]
Car: Subaru Crosstrek 2020 Sport (Canada)
RouteID: `a2af7643da1d4017|2022-04-14--12-00-31`

```
'carFw': 
[
    {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xf1\x00\xa2\x10\t', 'subAddress': 0},
    {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\xf1\x00\xd7\x10@', 'subAddress': 0},
    {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x9a\xc0\x04\x00', 'subAddress': 0},
    {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00eq\x1f@ "', 'subAddress': 0},
    {'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
    {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x03\x00', 'subAddress': 0},
    {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xf1\x00\xb2\x06\x04', 'subAddress': 0}
],
```

Since master-ci removed fpv1, I am now misidentifying as  as `SUBARU IMPREZA LIMITED 2019` instead of `SUBARU IMPREZA SPORT 2020`

**Comment by AndresAH** [comment]
route: 6627bfa1dedc9d9e|2022-04-13--11-04-55 

               'carFingerprint': 'SUBARU FORESTER 2019'

               'carFw': [{'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x02\x00', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xb6"`A\x07', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\x1a\xf6B0\x00', 'subAddress': 0},
                         {'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x8d\xc0\x04\x00', 'subAddress': 0},
                         {'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa3 \x18\x14\x00', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00e!\x1f@ \x11', 'subAddress': 0}]

**Comment by Fryelock** [comment]
Route:  36e19891049b91e3\|2022-04-15--08-08-01
         
             
               'carFw': [{'address': 1968, 'ecu': 'esp', 'fwVersion': b'\xa3  \x14\x01', 'subAddress': 0},
                         {'address': 2016, 'ecu': 'engine', 'fwVersion': b'\xf1\x00\xa2\x10\n', 'subAddress': 0},
                         {'address': 2017, 'ecu': 'transmission', 'fwVersion': b'\xf1\x00\xa4\x10@', 'subAddress': 0},
                         {'address': 1862, 'ecu': 'eps', 'fwVersion': b'\x8d\xc0\x04\x00', 'subAddress': 0},
                         {'address': 1927, 'ecu': 'fwdCamera', 'fwVersion': b'\x00\x00e\x97\x1f@ 0', 'subAddress': 0},
                         {'address': 1988, 'ecu': 'fwdCamera', 'fwVersion': b'\xf1\x00\xac\x02\x00', 'subAddress': 0},
                         {'address': 2000, 'ecu': 'fwdRadar', 'fwVersion': b'\xf1\x00\x00\x00\x02', 'subAddress': 0}],

**Comment by martinl** [comment]
> On master-ci, I am now misidentifying as as `SUBARU IMPREZA LIMITED 2019` instead of `SUBARU IMPREZA SPORT 2020`, which is expected I guess.

It depends if you tested on master-ci before or after this PR was merged and removed FPv1 fingerprints. 

Before, it would be correct. After this PR was merged, your car should not be identified (mock/dashcam) until FPv2 fw values are added (in a separate PR https://github.com/commaai/openpilot/pull/24225)

**Pull request merged**
