### PR TITLE
cameras_qcom: refactor focus

### PR DESCRIPTION
**Pull request by deanlee**
Consistent with the original code, the following refactor was performed:
-  ~Move focusing related code into class `RearCameraFocus`~
-  Use a single std::mutex to guarantee that the focusing procedure are real atomic and thread safe.(The code before refactoring is not,std::atomic can only guarantee that a single variable is atomic,not the whole procedure )

### CODE REVIEW

**Comment by deanlee** [comment]
For the convenience of review, does not encapsulate the focus-related code into class in this PR.

**Comment by deanlee** [comment]
@ZwX1616 : It works great on my device, is there anything else that needs to be improved in this PR?

**Comment by deanlee** [comment]
For making the code clearer, we may need to use a class to encapsulate related operations

**Comment by ZwX1616** [comment]
We currently don't have any solid regression test for AF, so this is very hard to test and risky to merge. I doubt if we ever would add test for AF in the future. I suggest we just keep the AF code as is, thoughts? @adeebshihadeh

**Pull request closed without merging**
