### PR TITLE
cabana: remove the installed handlers on exit

### PR DESCRIPTION
**Pull request by deanlee**
issue: the `MainWindow` is no longer valid when replay exits. But replay will still call the handler installed by mainwin to update the  download progress bar & logging messages. this can cause Cabana to hang on exit (or crash).

fixed: remove the installed handlers on exit

prereq pr: https://github.com/commaai/openpilot/pull/30296

### CODE REVIEW

**Comment by sshane** [comment]
I'll let you know if it happens again!

**Comment by deanlee** [comment]
ok!

**Comment by deanlee** [comment]
@sshane I'm still having some issues with hanging on exit. Checking , hopes to solve it completely.

**Comment by sshane** [comment]
@deanlee this has happened again, still not reliable when it happens. I noticed this time, the messages view was hidden by default when I opened a new Cabana. Does it write some params on closing?

```
Drawing same frame twice 150
Skipped frame 188
Skipped frame 229
Skipped frame 269
Skipped frame 278
Drawing same frame twice 278
^C
exiting...
^C
```

**Comment by sshane** [comment]
I specifically remember clicking on cancel to close, none of my windows are showing this Window.

**Pull request merged**
