### PR TITLE
Fixes overactive and noisy brake pump during braking on Honda cars

### PR DESCRIPTION
**Pull request by ghost**
Prior to this fix, supplied by @rbiasini at comma.ai, the brake pump would always be set to ON any time the braking value was non-zero while OP was active.  This created more braking pump noise than necessary during braking and possibly overworked the pump.  This fix mimics Honda's stock ACC behaviour, where the brake pump only turns on during times of increasing braking pressure.  The result is decreased pump activity (and noise) during braking.

### CODE REVIEW

**Comment by jfrux** [comment]
I swear... I will send you n00dz if this actually works.

**Comment by kegman** [comment]
The BRAKE_PUMP_REQUEST signal is binary:  ON or OFF.  I haven't seen a pressure indicator signal.  Without the pedal the difference is massive, especially when the car is almost at a stop and creeping.  There is no pump sound at all during slow creeps.  In any case matching Honda's behaviour for stock ACC is probably better than just turning the pump on whenever there is a non-zero braking applied.

**Comment by jfrux** [comment]
This PR is solid.  Restores brake noise back to factory.  And it also got rid of a rattle I was hearing while the car was running... like a ticking that was constant while the car was on.  Not sure if that is coincidence or not.

**Comment by kegman** [comment]
I'm also playing with having the pump turn off at a stop and the brake_stopping_target (put less pressure on the brake when the car comes to a stop).  OP puts a lot of pressure on the brake when the car comes to a stop causing the pump to activate and also is a bit jarring when the car starts up again.  We'll see how my experiments go.....  I'll report back.

**Comment by jfrux** [comment]
Really really excited to see your findings...

**Comment by dekerr** [comment]
curious as to why you removed method documentation in this PR..

**Comment by kegman** [comment]
@dekerr not sure what you mean?

**Comment by dekerr** [comment]
docstrings in hondacan methods were removed. I don't think they should have been.

**Comment by kegman** [comment]
@dekerr: code changes came from Comma....  I just submitted the PR as per @rbiasini suggestion.

**Comment by rbiasini** [comment]
merged into devel in 0.5.6

**Pull request closed without merging**
