### PR TITLE
Subaru: move non-obd requests out of logging

### LINKED ISSUE #25754: Subaru: query FW versions on non-OBD bus

### PR DESCRIPTION
**Pull request by jnewb1**
gen1: ```d9df6f87e8feff94|2023-12-29--18-01-11```

we get all ecus ```transmission, engine, abs, eps, fwdCamera``` (bus 0)

gen2: ```344c5c15b34f2d8a|2024-01-25--10-35-15```

we get ```transmission, engine, abs``` (bus 1) and ```fwdCamera``` (bus 0)

so both have enough to fingerprint

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Nice, so Subaru is ready to go OBD-less?

**Comment by jnewb1** [comment]
Running the OB without comma power now, fingerprinted fine. Also seems to keep power at the camera so the experience is the same! I'll get some gen1 people to test too

**Comment by sshane** [comment]
I thought you said we didn't get the EPS? https://github.com/commaai/openpilot/issues/25754#issuecomment-1832740254

**Comment by sshane** [comment]
Ah, we don't for gen 1:

```
               'carFw': [{'address': 1862,
                          'brand': 'subaru',
                          'bus': 1,
                          'ecu': 'eps',
                          'fwVersion': b'\n\xc0\x04\x00',
                          'logging': False,
                          'obdMultiplexing': True,
                          'request': [b'>\x00', b'"\xf1\x82'],
                          'responseAddress': 1870,
                          'subAddress': 0},
```

**Comment by sshane** [comment]
Can you check our data with a notebook to make sure that the ECUs we expect are all there? bus 0 // bus 1 & obdMultiplexing=false

**Comment by jnewb1** [comment]
gen1 without comma power, all expected ecus: ```11fa0800e2a72919|2024-01-26--00-35-33```

I will do the validation tomorrow

**Comment by jnewb1** [comment]
using big commaCarSegments database: 

notebook: [subaru_obd_fingerprint.zip](https://github.com/commaai/openpilot/files/14071852/subaru_obd_fingerprint.zip)
```
-----------------------
Got 1305 segments for platform SUBARU FORESTER 2019
1305it [00:09, 141.80it/s]
0/240 failed to properly fingerprint through obd port.
-----------------------
-----------------------
Got 1 segments for platform SUBARU LEGACY 7TH GEN
1it [00:00,  9.89it/s]
0/0 failed to properly fingerprint through obd port.
-----------------------
-----------------------
Got 1267 segments for platform SUBARU OUTBACK 6TH GEN
1267it [00:09, 140.47it/s]
0/67 failed to properly fingerprint through obd port.
-----------------------
-----------------------
Got 1227 segments for platform SUBARU ASCENT LIMITED 2019

1227it [00:08, 145.79it/s]
0/16 failed to properly fingerprint through obd port.
-----------------------
-----------------------
Got 1141 segments for platform SUBARU IMPREZA SPORT 2020
1141it [00:07, 143.22it/s]
0/198 failed to properly fingerprint through obd port.
-----------------------
-----------------------
Got 1082 segments for platform SUBARU IMPREZA LIMITED 2019

1082it [00:06, 156.40it/s]
0/5 failed to properly fingerprint through obd port.
-----------------------
```

**Comment by sshane** [comment]
Nice, any gain for mock cars?

**Comment by jnewb1** [comment]
> Nice, any gain for mock cars?

I think we will need to expand the "mock" part of the database, only a couple segments from subaru

**Comment by adeebshihadeh** [comment]
Let’s delete the old queries?

**Comment by jnewb1** [comment]
> Let’s delete the old queries?

We still only get eps with the comma power, is that worth keeping the query?

**Comment by adeebshihadeh** [comment]
We don't use it for fingerprinting though? We can keep it as a logging only query.

**Comment by sshane** [comment]
Yes, we should have deleted the queries and ECUs, else they won't exact match.

**Pull request merged**
